COPASI API: CLGradientBase Class Reference
CLGradientBase Class Reference
#include <CLGradientBase.h>
Public Types
enum SPREADMETHOD { PAD , REFLECT , REPEAT }
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
void addGradientStop (const CLGradientStop *pStop)
virtual void addSBMLAttributes (GradientBase *pBase) const
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CLGradientBase (const CLGradientBase &source, CDataContainer *pParent=NULL)
CLGradientBase (const GradientBase &source, const std::string &name, CDataContainer *pParent=NULL)
CLGradientBase (const std::string &name, CDataContainer *pParent=NULL)
CLGradientStop * createGradientStop ()
CLGradientStop * getGradientStop (size_t i)
const CLGradientStop * getGradientStop (size_t i) const
const std::string & getId () const
const std::string & getKey () const
CDataVector< CLGradientStop > * getListOfGradientStops ()
const CDataVector< CLGradientStop > * getListOfGradientStops () const
size_t getNumGradientStops () const
SPREADMETHOD getSpreadMethod () const
void setId (const std::string &id)
void setSpreadMethod (SPREADMETHOD method)
virtual CData toData () const
virtual ~CLGradientBase ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CLGradientBase * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Attributes
CDataVector< CLGradientStop > mGradientStops
std::string mId
std::string mKey
SPREADMETHOD mSpreadMethod
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLGradientBase & operator= (const CLGradientBase &source)
Additional Inherited Members
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Member Enumeration Documentation
SPREADMETHOD
enum CLGradientBase::SPREADMETHOD
Enumerator
PAD
REFLECT
REPEAT
Constructor & Destructor Documentation
CLGradientBase() [1/3]
CLGradientBase::CLGradientBase (const std::string & name, CDataContainer * pParent = NULL)
Constructor.
Referenced by fromData().
CLGradientBase() [2/3]
CLGradientBase::CLGradientBase (const CLGradientBase & source, CDataContainer * pParent = NULL)
Copy Constructor.
CLGradientBase() [3/3]
CLGradientBase::CLGradientBase (const GradientBase & source, const std::string & name, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
References addGradientStop(), mSpreadMethod, PAD, REFLECT, and REPEAT.
~CLGradientBase()
CLGradientBase::~CLGradientBase () virtual
Destructor.
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
addGradientStop()
void CLGradientBase::addGradientStop (const CLGradientStop * pStop)
Adds a copy of the given GradientStop object.
Adds a copy of the given CLGradientStop object.
References CDataVector< CType >::add(), and mGradientStops.
Referenced by CLGradientBase(), and GradientStopHandler::processStart().
addSBMLAttributes()
void CLGradientBase::addSBMLAttributes (GradientBase * pBase) const virtual
Adds gradient base attributes to the gradient passed as the argument.
References mGradientStops, mId, mSpreadMethod, REFLECT, REPEAT, and CDataVector< CType >::size().
Referenced by CLLinearGradient::toSBML(), and CLRadialGradient::toSBML().
applyData()
bool CLGradientBase::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References fatalError.
createGradientStop()
CLGradientStop * CLGradientBase::createGradientStop ()
Creates a new GradientStop.
Creates a new CLGradientStop.
References CDataVector< CType >::add(), and mGradientStops.
fromData()
CLGradientBase * CLGradientBase::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CLGradientBase * pDataObject
References CLGradientBase(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getGradientStop() [1/2]
CLGradientStop * CLGradientBase::getGradientStop (size_t i)
Returns a pointer to the gradient stop with the given index or NULL if the index is invalid.
References mGradientStops, and CDataVector< CType >::size().
Referenced by CLGradientStops::CLGradientStops(), CLLayoutRenderer::map_gradient_color(), CCopasiXML::saveGradientElements(), and CLLayoutRenderer::update_colors().
getGradientStop() [2/2]
const CLGradientStop * CLGradientBase::getGradientStop (size_t i) const
Returns a const pointer to the gradient stop with the given index or NULL if the index is invalid.
References mGradientStops, and CDataVector< CType >::size().
getId()
const std::string & CLGradientBase::getId () const
Returns the id of the object.
References mId.
Referenced by CLRenderResolver::fill_base_maps(), CLRenderFlattener::flatten(), and CCopasiXML::saveGradientAttributes().
getKey()
const std::string & CLGradientBase::getKey () const virtual
Returns the key of the color definition.
Reimplemented from CDataObject.
References mKey.
getListOfGradientStops() [1/2]
CDataVector< CLGradientStop > * CLGradientBase::getListOfGradientStops ()
Returns a pointer to the gradient stop vector.
References mGradientStops.
getListOfGradientStops() [2/2]
const CDataVector< CLGradientStop > * CLGradientBase::getListOfGradientStops () const
Returns a const pointer to the gradient stop vector.
References mGradientStops.
getNumGradientStops()
size_t CLGradientBase::getNumGradientStops () const
Returns the number of gradient stops.
References mGradientStops, and CDataVector< CType >::size().
Referenced by CLGradientStops::CLGradientStops(), CLLayoutRenderer::map_gradient_color(), CCopasiXML::saveGradientElements(), and CLLayoutRenderer::update_colors().
getSpreadMethod()
CLGradientBase::SPREADMETHOD CLGradientBase::getSpreadMethod () const
Returns the spreadmethod of the gradient.
Returns the spreadmethod of he gradient.
References mSpreadMethod.
Referenced by CLLayoutRenderer::map_gradient_color(), and CCopasiXML::saveGradientAttributes().
operator=()
CLGradientBase& CLGradientBase::operator= (const CLGradientBase & source) private
setId()
void CLGradientBase::setId (const std::string & id)
Sets the id of the object.
References mId.
Referenced by LinearGradientHandler::processStart(), and RadialGradientHandler::processStart().
setSpreadMethod()
void CLGradientBase::setSpreadMethod (CLGradientBase::SPREADMETHOD method)
Sets the spread method.
References mSpreadMethod.
Referenced by LinearGradientHandler::processStart(), and RadialGradientHandler::processStart().
toData()
CData CLGradientBase::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References fatalError.
Member Data Documentation
mGradientStops
CDataVector<CLGradientStop> CLGradientBase::mGradientStops protected
Referenced by addGradientStop(), addSBMLAttributes(), createGradientStop(), getGradientStop(), getListOfGradientStops(), and getNumGradientStops().
mId
std::string CLGradientBase::mId protected
The gradient base needs an id in addition to the key. The id corresponds to the id in the SBML render extension and it does not have to be globally unique. As a matter of fact, it is sometimes needed that gradient base of different render information have the same id.
Referenced by addSBMLAttributes(), getId(), and setId().
mKey
std::string CLGradientBase::mKey protected
key string for the gradient.
Referenced by CLLinearGradient::CLLinearGradient(), CLRadialGradient::CLRadialGradient(), getKey(), and ~CLGradientBase().
mSpreadMethod
SPREADMETHOD CLGradientBase::mSpreadMethod protected
Referenced by addSBMLAttributes(), CLGradientBase(), getSpreadMethod(), and setSpreadMethod().
The documentation for this class was generated from the following files:
CLGradientBase.h
CLGradientBase.cpp