COPASI API: CChemEqElement Class Reference
CChemEqElement Class Reference
#include <CChemEqElement.h>
Public Member Functions
void addToMultiplicity (const C_FLOAT64 multiplicity=1.0)
CChemEqElement (const CChemEqElement &src, const CDataContainer *pParent)
CChemEqElement (const std::string &name="Chem Eq Element", const CDataContainer *pParent=NO_PARENT)
void cleanup ()
const CMetab * getMetabolite () const
const std::string & getMetaboliteKey () const
const C_FLOAT64 & getMultiplicity () const
void setMetabolite (const std::string &key)
void setMultiplicity (const C_FLOAT64 multiplicity)
~CChemEqElement ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual CData toData () const override
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CChemEqElement * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Member Functions
CChemEqElement (const CChemEqElement &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Private Member Functions
void initObjects ()
Private Attributes
std::string mMetaboliteKey
C_FLOAT64 mMultiplicity
Friends
std::ostream & operator<< (std::ostream &os, const CChemEqElement &d)
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CChemEqElement() [1/3]
CChemEqElement::CChemEqElement (const CChemEqElement & src) protected
Referenced by fromData().
CChemEqElement() [2/3]
CChemEqElement::CChemEqElement (const std::string & name = "Chem Eq Element", const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CDataContainer * pParent (default: NULL)
References CONSTRUCTOR_TRACE, and initObjects().
CChemEqElement() [3/3]
CChemEqElement::CChemEqElement (const CChemEqElement & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CChemEqElement & src
const CDataContainer * pParent (default: NULL)
References CONSTRUCTOR_TRACE, and initObjects().
~CChemEqElement()
CChemEqElement::~CChemEqElement ()
Destructor
References DESTRUCTOR_TRACE.
Member Function Documentation
addToMultiplicity()
void CChemEqElement::addToMultiplicity (const C_FLOAT64 multiplicity = 1.0)
Add to the multiplicity of the element.
Parameters
const C_FLOAT64 multiplicity (default = 1.0)
References mMultiplicity.
cleanup()
void CChemEqElement::cleanup ()
cleanup
fromData()
CChemEqElement * CChemEqElement::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CChemEqElement * pDataObject
References CChemEqElement(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getMetabolite()
const CMetab * CChemEqElement::getMetabolite () const
Retrieves the metabolite of the element.
Returns
"CMetab *" metabolite
References CKeyFactory::get(), CRootContainer::getKeyFactory(), and mMetaboliteKey.
Referenced by SBMLImporter::applyStoichiometricExpressions(), CSBMLExporter::createReaction(), CModelExpansion::duplicateReaction(), CODEExporterC::KineticFunction2ODEmember(), CModelMerging::mergeMetabolites(), and CModelExpansion::replaceInReaction().
getMetaboliteKey()
const std::string & CChemEqElement::getMetaboliteKey () const
Retrieve the key of the species
Returns
const std::string & speciesKey
References mMetaboliteKey.
Referenced by CChemEq::addElement(), CModelAdd::addReactions(), SBMLImporter::applyStoichiometricExpressions(), CODEExporter::exportKineticFunction(), and SBMLImporter::isMassActionExpression().
getMultiplicity()
const C_FLOAT64 & CChemEqElement::getMultiplicity () const
Retrieves the multiplicity of the element.
Returns
const C_FLOAT64 & multiplicity
References mMultiplicity.
Referenced by CChemEq::addElement(), CModelAdd::addReactions(), SBMLImporter::applyStoichiometricExpressions(), CSBMLExporter::createReaction(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), SBMLImporter::isMassActionExpression(), and CODEExporterC::KineticFunction2ODEmember().
initObjects()
void CChemEqElement::initObjects () private
References CDataContainer::addObjectReference(), mMetaboliteKey, mMultiplicity, and CDataObject::ValueDbl.
Referenced by CChemEqElement().
setMetabolite()
void CChemEqElement::setMetabolite (const std::string & key)
Set the metabolite of the element.
Parameters
CMetab * metabolite
References CKeyFactory::get(), CRootContainer::getKeyFactory(), CDataObject::getObjectName(), mMetaboliteKey, and CDataObject::setObjectName().
Referenced by CChemEq::addMetabolite(), CModelMerging::mergeMetabolites(), and CModelExpansion::replaceInReaction().
setMultiplicity()
void CChemEqElement::setMultiplicity (const C_FLOAT64 multiplicity)
Set the multiplicity of the element.
Parameters
const C_FLOAT64 multiplicity
References mMultiplicity.
Referenced by CChemEq::addElement(), CChemEq::addMetabolite(), and CChemEq::setMultiplicity().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CChemEqElement & d) friend
Member Data Documentation
mMetaboliteKey
std::string CChemEqElement::mMetaboliteKey private
The name of the metabolite the element
Referenced by getMetabolite(), getMetaboliteKey(), initObjects(), and setMetabolite().
mMultiplicity
C_FLOAT64 CChemEqElement::mMultiplicity private
The multiplicity of the metabolite
Referenced by addToMultiplicity(), getMultiplicity(), initObjects(), and setMultiplicity().
The documentation for this class was generated from the following files:
CChemEqElement.h
CChemEqElement.cpp