COPASI API: utility.cpp File Reference
utility.cpp File Reference
#include <algorithm>
#include <cmath>
#include <limits>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "copasi/copasi.h"
#include "utility.h"
#include "CCopasiMessage.h"
Macros
#define toBeEscaped "\\\""
Functions
bool containsTag (const std::string &filename, const std::string &tagname, int numLines)
void FixSName (const std::string &original, std::string &fixed)
bool isNumber (const std::string &str)
std::string ISODateTime (tm *pTime)
bool isProbablySBML (const std::string &filename)
std::string LocalTimeStamp ()
std::string nameToSbmlId (const std::string &name)
std::string pointerToString (const void *pVoid)
std::string quote (const std::string &name, const std::string &additionalEscapes)
std::string StringPrint (const char *format,...)
bool stringReplace (std::string &str, const std::string &target, const std::string &replacement)
void * stringToPointer (const std::string str)
double strToDouble (const char *str, char const **pTail)
bool strToIndex (const std::string &str, size_t &index)
C_INT32 strToInt (const char *str, char const **pTail)
unsigned C_INT32 strToUnsignedInt (const char *str, char const **pTail)
time_t timeFromUTC (const std::string utc)
std::string unQuote (const std::string &name)
std::string UTCTimeStamp ()
size_t utf8Length (const std::string &str)
Macro Definition Documentation
toBeEscaped
#define toBeEscaped "\\\""
Function Documentation
containsTag()
bool containsTag (const std::string & filename, const std::string & tagname, int numLines = 10)
Test whether a given XML tag is present in the first number of lines of a given file.
Parameters
filename the filename to be tested
tagname the tag name to be tested for
numLines the number of lines to be tested (default 10)
Returns
boolean indicating whether the tag appeared in the first numLines.
Referenced by isProbablySBML().
FixSName()
void FixSName (const std::string & original, std::string & fixed)
isNumber()
bool isNumber (const std::string & str)
Check whether the given string represents a number
Parameters
const std::string & str
Returns
bool isNumber
References strToDouble().
Referenced by COptItem::compileLowerBound(), COptItem::compileUpperBound(), ConverterASTNode::ConverterASTNode(), CMetabNameInterface::createUniqueDisplayName(), CMetabNameInterface::getDisplayName(), COptItem::setLowerBound(), CDataObject::setObjectName(), COptItem::setUpperBound(), and CChemEqInterface::writeElement().
ISODateTime()
std::string ISODateTime (tm * pTime)
Returns the time pointed to by pTime in ISO format
Referenced by COptLogItem::fillString(), LocalTimeStamp(), and UTCTimeStamp().
isProbablySBML()
bool isProbablySBML (const std::string & filename)
Tests whether the file is SBML by reading the first 10 lines and looking for the presence of the sbml tag.
Parameters
filename the filename to be tested
Returns
true, if the first 10 lines contain the sbml tag, false otherwise.
References containsTag().
Referenced by CDataModel::addModel().
LocalTimeStamp()
std::string LocalTimeStamp ()
Returns the current local time in ISO format
References ISODateTime().
Referenced by COptLogEntry::COptLogEntry(), and CCopasiMessage::handler().
nameToSbmlId()
std::string nameToSbmlId (const std::string & name)
Convert a utf8 encoded name to a XmlId
Parameters
const std::string & name
Returns
std::string SbmlId
Referenced by CSBMLExporter::createFunctionDefinition(), and CSBMLExporter::createUniqueId().
pointerToString()
std::string pointerToString (const void * pVoid)
Convert a void pointer to a string
Parameters
const void * pVoid
Returns
std::string str
References fatalError.
Referenced by CEvaluationNodeObject::CEvaluationNodeObject(), CMathEvent::CAssignment::compile(), CMathObject::compileDependentMass(), CMathObject::compileFlux(), CMathObject::compileParticleFlux(), CMathObject::compilePropensity(), CMathObject::compileReactionNoise(), CMathObject::compileTotalMass(), CMathObject::compileTransitionTime(), CMathObject::createExtensiveNoiseExpression(), CMathObject::createExtensiveODERateExpression(), CMathObject::createExtensiveReactionNoiseExpression(), CMathObject::createExtensiveReactionRateExpression(), CMathObject::createExtensiveValueExpression(), CMathObject::createIntensiveRateExpression(), CMathObject::createIntensiveValueExpression(), CMathDelay::modifyMathObject(), and CEvaluationNodeObject::setObjectValuePtr().
quote()
std::string quote (const std::string & name, const std::string & additionalEscapes = "")
Surround a name with quotes if the name contains a space or double quote else the name is returned unmodified. In the quoted name " and \ are escaped. The parameter additionalEscapes forces quotes around names containing any of the character in the parameter.
Parameters
const std::string & name
const std::string & additionalEscapes (default: "")
Returns
std::string quote
References toBeEscaped.
Referenced by CChemEqInterface::addModifier(), CMetabNameInterface::createUniqueDisplayName(), CEvaluationNodeCall::getBerkeleyMadonnaString(), CEvaluationNodeCall::getCCodeString(), CEvaluationNodeCall::getData(), CMetabNameInterface::getDisplayName(), CEvaluationNodeCall::getDisplayString(), CEvaluationNodeCall::getInfix(), CEvaluationNodeCall::getMMLString(), CEvaluationNodeCall::getXPPString(), CUnitDefinitionDB::quoteSymbol(), CEvaluationNodeCall::setData(), and CMetabNameInterface::splitDisplayName().
StringPrint()
std::string StringPrint (const char * format, ...)
sprintf like function for strings
Parameters
const char * format sprintf like format string
...
Returns
"string"
References C_INT32, and INITIALTEXTSIZE.
Referenced by CDataArray::addElementReference(), CExperimentSet::addExperiment(), CExperiment::elevateChildren(), CDataArray::getAnnotationsString(), CExperimentObjectMap::getDefaultScale(), CExperimentObjectMap::getName(), CExperimentObjectMap::getObjectCN(), CExperimentObjectMap::getRole(), CExperimentObjectMap::getScale(), CCopasiTimeVariable::LL2String(), CReaction::loadOld(), CReaction::loadOneRole(), ParameterDescriptionHandler::processStart(), CExperimentObjectMap::setNumCols(), CExperimentObjectMap::setObjectCN(), CExperimentObjectMap::setRole(), CExperimentObjectMap::setScale(), and CVersion::setString().
stringReplace()
bool stringReplace (std::string & str, const std::string & target, const std::string & replacement)
Replaces the all occurrences of target string in str with the replacement and returns true if the target string was replaced
Parameters
std::string & str
const std::string & target
const std::string & replacement
Returns
bool replaced
Referenced by CUnit::buildExpression(), and CModel::replaceInExpressions().
stringToPointer()
void* stringToPointer (const std::string str)
Convert a character sequence to a void pointer
Parameters
const std::string str
Returns
void * pVoid
Referenced by CEvaluationNodeObject::CEvaluationNodeObject(), CEvaluationNodeObject::compile(), and CMathExpression::relocate().
strToDouble()
double strToDouble (const char * str, char const ** pTail = NULL)
Convert a character sequence to a double
Parameters
const char * str
char const ** pTail (default: NULL)
Returns
double
Referenced by CEvaluationNodeNumber::CEvaluationNodeNumber(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CReadConfig::getVariable(), isNumber(), EllipseHandler::processStart(), GroupHandler::processStart(), PolygonHandler::processStart(), RectangleHandler::processStart(), RenderCurveHandler::processStart(), RenderTextHandler::processStart(), COptItem::setLowerBound(), COptItem::setUpperBound(), and CEvaluationNodeNumber::toAST().
strToIndex()
bool strToIndex (const std::string & str, size_t & index)
Convert a string to a size_t index. Returns true if the conversion is successful, i.e., the whole string has been converted.
Parameters
const std::string & str
size_t & index
Returns
bool success
References C_INVALID_INDEX.
Referenced by CDataArray::cnToIndex(), CDataArray::displayNamesToCN(), CCommonName::getElementIndex(), and CArrayElementReference::updateObjectName().
strToInt()
C_INT32 strToInt (const char * str, char const ** pTail = NULL)
Convert a character sequence to a double
Parameters
const char * str
char const ** pTail (default: NULL)
Returns
C_INT32
References C_INT32.
Referenced by COPASIHandler::processStart(), ParameterHandler::processStart(), and CVersion::setVersion().
strToUnsignedInt()
unsigned C_INT32 strToUnsignedInt (const char * str, char const ** pTail = NULL)
Convert a character sequence to a double
Parameters
const char * str
char const ** pTail (default: NULL)
Returns
unsigned C_INT32
References C_INT32.
Referenced by CCopasiParameterGroup::getObject(), CompartmentHandler::processStart(), ParameterDescriptionHandler::processStart(), ParameterHandler::processStart(), ReportDefinitionHandler::processStart(), and SliderHandler::processStart().
timeFromUTC()
time_t timeFromUTC (const std::string utc)
Converts the UTC time to time_t
Parameters
const std::string utc
Returns
time_t time
Referenced by CCheckForUpdates::checkRequired().
unQuote()
std::string unQuote (const std::string & name)
Unesacape a quoted name. If the name is surrounded by quotes these are removed and included escape sequences '.' are reduced to '.' else the name is returned unmodified.
Parameters
const std::string & name
Returns
std::string unQuote
Referenced by CModel::findMetabByName(), CEvaluationNodeCall::getData(), CDataVectorN< CType >::getIndex(), CUnitDefinitionDB::getUnitDefFromSymbol(), and CEvaluationNodeCall::setData().
UTCTimeStamp()
std::string UTCTimeStamp ()
Returns the current time in ISO format
References ISODateTime().
Referenced by CMIRIAMInfo::addDefaultCreatedDT(), CModelVersionHierarchy::addVersion(), CCheckForUpdates::checkRequired(), CFitProblem::createParameterSet(), CCopasiTimer::print(), CConfigurationFile::CXML::save(), CCopasiXML::save(), CCopasiXML::saveModelParameterSets(), and CCheckForUpdates::setChecked().
utf8Length()
size_t utf8Length (const std::string & str)
calculate the number of utf8 characters in a givent string
Parameters
const std::string & str
Returns
size_t utf8Length
Referenced by SBMLUnitSupport::createUnitExpressionFor().