COPASI API: CPointerMathContext< Data > Class Template Reference
CPointerMathContext< Data > Class Template Reference
#include <CPointerMathContext.h>
Public Types
typedef CPointerContextWithParent< Data > Base
Public Types inherited from CPointerContextWithParent< Data >
typedef CPointerContext< Data > Base
Public Types inherited from CPointerContext< Data >
typedef CContext< Data * > Base
Public Member Functions
CPointerMathContext ()=delete
CPointerMathContext (const bool &parallel, CDataContainer *pParent)
CPointerMathContext (const CPointerMathContext &src)=delete
void setMathContext (CMathContext &Context)
~CPointerMathContext ()
Public Member Functions inherited from CPointerContextWithParent< Data >
CPointerContextWithParent ()=delete
CPointerContextWithParent (const bool &parallel, CDataContainer *pParent)
CPointerContextWithParent (const CPointerContextWithParent &src)=delete
void setMaster (Data *pMaster)
~CPointerContextWithParent ()
Public Member Functions inherited from CPointerContext< Data >
CPointerContext ()=delete
CPointerContext (const bool &parallel)
CPointerContext (const CPointerContext &src)=delete
void setMaster (Data *pMaster)
~CPointerContext ()
Public Member Functions inherited from CContext< Data * >
Data * & active ()
const Data * & active () const
Data * * beginThread ()
const Data * * beginThread () const
CContext (const bool &parallel=true)
CContext (const CContext &src)
Data * * endThread ()
const Data * * endThread () const
int globalIndex (const Data * *data) const
void init ()
bool isMaster (const Data * *data) const
bool isThread (const Data * *data) const
int localIndex (const Data * *data) const
Data * & master ()
const Data * & master () const
CContext & operator= (const CContext &rhs)
bool operator== (const CContext &rhs) const
void release ()
const size_t & size () const
~CContext ()
Member Typedef Documentation
Base
template<class Data > typedef CPointerContextWithParent< Data > CPointerMathContext< Data >::Base
Constructor & Destructor Documentation
CPointerMathContext() [1/3]
template<class Data > CPointerMathContext< Data >::CPointerMathContext () delete
CPointerMathContext() [2/3]
template<class Data > CPointerMathContext< Data >::CPointerMathContext (const CPointerMathContext< Data > & src) delete
CPointerMathContext() [3/3]
template<class Data > CPointerMathContext< Data >::CPointerMathContext (const bool & parallel, CDataContainer * pParent)
~CPointerMathContext()
template<class Data > CPointerMathContext< Data >::~CPointerMathContext
Member Function Documentation
setMathContext()
template<class Data > void CPointerMathContext< Data >::setMathContext (CMathContext & Context)
Set the pointer to container used for calculations
Parameters
CMathContext * pContext
References CContext< Data >::beginThread(), and CContext< Data >::master().
Referenced by COptMethod::COptMethod(), COptMethod::initialize(), COptMethod::setProblem(), and COptMethod::signalMathContainerChanged().
The documentation for this class was generated from the following file:
CPointerMathContext.h