COPASI API: CLRenderInformationBase Class Reference
CLRenderInformationBase Class Reference abstract
#include <CLRenderInformationBase.h>
Public Member Functions
void addColorDefinition (const CLColorDefinition *cd)
void addGradientDefinition (const CLGradientBase *gradient)
void addLineEnding (const CLLineEnding *le)
void addSBMLAttributes (RenderInformationBase *pBase) const
CLRenderInformationBase (const CLRenderInformationBase &source, CDataContainer *pParent)
CLRenderInformationBase (const RenderInformationBase &source, const std::string &name, CDataContainer *pParent=NULL)
CLRenderInformationBase (const std::string &name, CDataContainer *pParent=NULL)
CLColorDefinition * createColorDefinition ()
CLLinearGradient * createLinearGradientDefinition ()
CLLineEnding * createLineEnding ()
CLRadialGradient * createRadialGradientDefinition ()
virtual CLStyle * createStyle ()=0
const std::string & getBackgroundColor () const
CLColorDefinition * getColorDefinition (size_t index)
const CLColorDefinition * getColorDefinition (size_t index) const
CLGradientBase * getGradientDefinition (size_t index)
const CLGradientBase * getGradientDefinition (size_t index) const
const std::string & getKey () const
CLLineEnding * getLineEnding (size_t index)
const CLLineEnding * getLineEnding (size_t index) const
CDataVector< CLColorDefinition > * getListOfColorDefinitions ()
const CDataVector< CLColorDefinition > * getListOfColorDefinitions () const
CDataVector< CLGradientBase > * getListOfGradientDefinitions ()
const CDataVector< CLGradientBase > * getListOfGradientDefinitions () const
CDataVector< CLLineEnding > * getListOfLineEndings ()
const CDataVector< CLLineEnding > * getListOfLineEndings () const
const std::string & getName () const
size_t getNumColorDefinitions () const
size_t getNumGradientDefinitions () const
size_t getNumLineEndings () const
virtual size_t getNumStyles () const =0
const std::string & getReferenceRenderInformationKey () const
virtual const CLStyle * getStyle (size_t index) const =0
virtual CLStyle * getStyle (size_t index)=0
virtual const CLStyle * getStyleForGraphicalObject (const CLGraphicalObject *pObject) const =0
void removeColorDefinition (size_t index)
void removeGradientDefinition (size_t index)
void removeLineEnding (size_t index)
void setBackgroundColor (const std::string &bg)
void setName (const std::string &name)
void setReferenceRenderInformationKey (const std::string &key)
~CLRenderInformationBase ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual CData toData () const override
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Protected Attributes
std::string mBackgroundColor
std::string mKey
CDataVector< CLColorDefinition > mListOfColorDefinitions
CDataVector< CLGradientBase > mListOfGradientDefinitions
CDataVector< CLLineEnding > mListOfLineEndings
std::string mName
std::string mReferenceRenderInformation
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLRenderInformationBase & operator= (const CLRenderInformationBase &source)
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLRenderInformationBase() [1/3]
CLRenderInformationBase::CLRenderInformationBase (const std::string & name, CDataContainer * pParent = NULL)
Constructor.
CLRenderInformationBase() [2/3]
CLRenderInformationBase::CLRenderInformationBase (const CLRenderInformationBase & source, CDataContainer * pParent)
Copy constructor.
CLRenderInformationBase() [3/3]
CLRenderInformationBase::CLRenderInformationBase (const RenderInformationBase & source, const std::string & name, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
References CDataVector< CType >::add(), mListOfColorDefinitions, mListOfGradientDefinitions, and mListOfLineEndings.
~CLRenderInformationBase()
CLRenderInformationBase::~CLRenderInformationBase ()
Destructor
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
addColorDefinition()
void CLRenderInformationBase::addColorDefinition (const CLColorDefinition * pCD)
Adds a copy of the given color definition to the end of the list of color definitions.
References CDataVector< CType >::add(), and mListOfColorDefinitions.
Referenced by CLRenderFlattener::flatten().
addGradientDefinition()
void CLRenderInformationBase::addGradientDefinition (const CLGradientBase * pGradient)
Adds a copy of the given gradient definition to the end of the list of gradient definitions.
References CDataVector< CType >::add(), and mListOfGradientDefinitions.
Referenced by CLRenderFlattener::flatten().
addLineEnding()
void CLRenderInformationBase::addLineEnding (const CLLineEnding * pLE)
Adds a copy of the given line ending to the end of the list of line endings.
References CDataVector< CType >::add(), and mListOfLineEndings.
Referenced by CLRenderFlattener::flatten().
addSBMLAttributes()
void CLRenderInformationBase::addSBMLAttributes (RenderInformationBase * pBase) const
Adds the attributes for a graphical primitive 1D object to the passed in. object.
References getBackgroundColor(), getColorDefinition(), getGradientDefinition(), getKey(), getLineEnding(), getReferenceRenderInformationKey(), mListOfColorDefinitions, mListOfGradientDefinitions, mListOfLineEndings, mName, CDataVector< CType >::size(), CLColorDefinition::toSBML(), and CLLineEnding::toSBML().
Referenced by CLGlobalRenderInformation::toSBML(), and CLLocalRenderInformation::toSBML().
createColorDefinition()
CLColorDefinition * CLRenderInformationBase::createColorDefinition ()
Creates a new color definition.
References CDataVector< CType >::add(), and mListOfColorDefinitions.
Referenced by ColorDefinitionHandler::processStart().
createLinearGradientDefinition()
CLLinearGradient * CLRenderInformationBase::createLinearGradientDefinition ()
Creates a new linear gradient definition.
References CDataVector< CType >::add(), and mListOfGradientDefinitions.
Referenced by LinearGradientHandler::processStart().
createLineEnding()
CLLineEnding * CLRenderInformationBase::createLineEnding ()
Creates a new line ending.
References CDataVector< CType >::add(), and mListOfLineEndings.
Referenced by LineEndingHandler::processStart().
createRadialGradientDefinition()
CLRadialGradient * CLRenderInformationBase::createRadialGradientDefinition ()
Creates a new radial gradient definition.
References CDataVector< CType >::add(), and mListOfGradientDefinitions.
Referenced by RadialGradientHandler::processStart().
createStyle()
virtual CLStyle* CLRenderInformationBase::createStyle () pure virtual
Creates a new style, and adds it to the list of styles (where it is owned)
Returns
the newly created style
Implemented in CLLocalRenderInformation, and CLGlobalRenderInformation.
Referenced by StyleHandler::processStart().
getBackgroundColor()
const std::string & CLRenderInformationBase::getBackgroundColor () const
Returns the background color which is either the id of a color in the list of color definitions, or a color value.
References mBackgroundColor.
Referenced by addSBMLAttributes(), CLRenderFlattener::flatten(), CCopasiXML::saveRenderInformationAttributes(), and CLRenderResolver::setBackgroundColor().
getColorDefinition() [1/2]
CLColorDefinition * CLRenderInformationBase::getColorDefinition (size_t index)
Returns a pointer to the color definition with the given index, or NULL if the index is invalid.
References mListOfColorDefinitions, and CDataVector< CType >::size().
Referenced by addSBMLAttributes(), CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
getColorDefinition() [2/2]
const CLColorDefinition * CLRenderInformationBase::getColorDefinition (size_t index) const
Returns a const pointer to the color definition with the given index, or NULL if the index is invalid.
References mListOfColorDefinitions, and CDataVector< CType >::size().
getGradientDefinition() [1/2]
CLGradientBase * CLRenderInformationBase::getGradientDefinition (size_t index)
Returns a pointer to the gradient definition with the given index, or NULL if the index is invalid.
References mListOfGradientDefinitions, and CDataVector< CType >::size().
Referenced by addSBMLAttributes(), CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
getGradientDefinition() [2/2]
const CLGradientBase * CLRenderInformationBase::getGradientDefinition (size_t index) const
Returns a const pointer to the gradient definition with the given index, or NULL if the index is invalid.
References mListOfGradientDefinitions, and CDataVector< CType >::size().
getKey()
const std::string & CLRenderInformationBase::getKey () const virtual
Returns the key of the render infomation object
Returns the key of the color definition.
Reimplemented from CDataObject.
References mKey.
Referenced by addSBMLAttributes(), SBMLDocumentLoader::createLayout(), SBMLDocumentLoader::readListOfLayouts(), and CCopasiXML::saveRenderInformationAttributes().
getLineEnding() [1/2]
CLLineEnding * CLRenderInformationBase::getLineEnding (size_t index)
Returns a pointer to the line ending with the given index, or NULL if the index is invalid.
References mListOfLineEndings, and CDataVector< CType >::size().
Referenced by addSBMLAttributes(), CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
getLineEnding() [2/2]
const CLLineEnding * CLRenderInformationBase::getLineEnding (size_t index) const
Returns a const pointer to the line ending with the given index, or NULL if the index is invalid.
References mListOfLineEndings, and CDataVector< CType >::size().
getListOfColorDefinitions() [1/2]
CDataVector< CLColorDefinition > * CLRenderInformationBase::getListOfColorDefinitions ()
Returns a pointer to the list of color definitions.
References mListOfColorDefinitions.
getListOfColorDefinitions() [2/2]
const CDataVector< CLColorDefinition > * CLRenderInformationBase::getListOfColorDefinitions () const
Returns a const pointer to the list of color definitions.
References mListOfColorDefinitions.
getListOfGradientDefinitions() [1/2]
CDataVector< CLGradientBase > * CLRenderInformationBase::getListOfGradientDefinitions ()
Returns a pointer to the list of gradient definitions.
References mListOfGradientDefinitions.
getListOfGradientDefinitions() [2/2]
const CDataVector< CLGradientBase > * CLRenderInformationBase::getListOfGradientDefinitions () const
Returns a const pointer to the list of gradient definitions.
References mListOfGradientDefinitions.
getListOfLineEndings() [1/2]
CDataVector< CLLineEnding > * CLRenderInformationBase::getListOfLineEndings ()
Returns a pointer to the list of line endings.
References mListOfLineEndings.
getListOfLineEndings() [2/2]
const CDataVector< CLLineEnding > * CLRenderInformationBase::getListOfLineEndings () const
Returns a const pointer to the list of line endings.
References mListOfLineEndings.
getName()
const std::string & CLRenderInformationBase::getName () const
Returns the id of the object.
Returns the name of the object.
References mName.
Referenced by CCopasiXML::saveRenderInformationAttributes().
getNumColorDefinitions()
size_t CLRenderInformationBase::getNumColorDefinitions () const
Returns the number of color definitions.
References mListOfColorDefinitions, and CDataVector< CType >::size().
Referenced by CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
getNumGradientDefinitions()
size_t CLRenderInformationBase::getNumGradientDefinitions () const
Returns the number of gradient definitions.
References mListOfGradientDefinitions, and CDataVector< CType >::size().
Referenced by CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
getNumLineEndings()
size_t CLRenderInformationBase::getNumLineEndings () const
Returns the number of line endings.
References mListOfLineEndings, and CDataVector< CType >::size().
Referenced by CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
getNumStyles()
virtual size_t CLRenderInformationBase::getNumStyles () const pure virtual
Returns
the number of styles
Implemented in CLLocalRenderInformation, and CLGlobalRenderInformation.
getReferenceRenderInformationKey()
const std::string & CLRenderInformationBase::getReferenceRenderInformationKey () const
Returns the key of the referenced render information object..
Returns the id of the referenced render information object..
References mReferenceRenderInformation.
Referenced by addSBMLAttributes(), CLRenderFlattener::flatten(), and CCopasiXML::saveRenderInformationAttributes().
getStyle() [1/2]
virtual const CLStyle* CLRenderInformationBase::getStyle (size_t index) const pure virtual
Returns
the style with the given index, or NULL
Implemented in CLLocalRenderInformation, and CLGlobalRenderInformation.
getStyle() [2/2]
virtual CLStyle* CLRenderInformationBase::getStyle (size_t index) pure virtual
Returns
the style with the given index, or NULL
Implemented in CLLocalRenderInformation, and CLGlobalRenderInformation.
getStyleForGraphicalObject()
virtual const CLStyle* CLRenderInformationBase::getStyleForGraphicalObject (const CLGraphicalObject * pObject) const pure virtual
Returns the style for the graphical object or NULL
Parameters
pObject the graphical object
Returns
the style if one is available for the object
Implemented in CLLocalRenderInformation, and CLGlobalRenderInformation.
operator=()
CLRenderInformationBase& CLRenderInformationBase::operator= (const CLRenderInformationBase & source) private
removeColorDefinition()
void CLRenderInformationBase::removeColorDefinition (size_t index)
Removes the color definition with the given index.
References mListOfColorDefinitions, CDataVector< CType >::remove(), and CDataVector< CType >::size().
removeGradientDefinition()
void CLRenderInformationBase::removeGradientDefinition (size_t index)
Removes the gradient definition with the given index.
References mListOfGradientDefinitions, CDataVector< CType >::remove(), and CDataVector< CType >::size().
removeLineEnding()
void CLRenderInformationBase::removeLineEnding (size_t index)
Removes the line ending with the given index.
References mListOfLineEndings, CDataVector< CType >::remove(), and CDataVector< CType >::size().
setBackgroundColor()
void CLRenderInformationBase::setBackgroundColor (const std::string & bg)
Sets the background color to either the id of a color in the list of color definitions, or a color value.
References mBackgroundColor.
Referenced by CLRenderFlattener::flatten(), RenderInformationHandler::processStart(), and CLRenderResolver::setBackgroundColor().
setName()
void CLRenderInformationBase::setName (const std::string & name)
Sets the id of the object.
Sets the name of the object.
References mName.
setReferenceRenderInformationKey()
void CLRenderInformationBase::setReferenceRenderInformationKey (const std::string & key)
Sets the key of the referenced render information object.
Sets the id of the referenced render information object.
References mReferenceRenderInformation.
Member Data Documentation
mBackgroundColor
std::string CLRenderInformationBase::mBackgroundColor protected
Referenced by getBackgroundColor(), and setBackgroundColor().
mKey
std::string CLRenderInformationBase::mKey protected
key string for the render information.
Referenced by CLGlobalRenderInformation::CLGlobalRenderInformation(), CLLocalRenderInformation::CLLocalRenderInformation(), getKey(), and ~CLRenderInformationBase().
mListOfColorDefinitions
CDataVector<CLColorDefinition> CLRenderInformationBase::mListOfColorDefinitions protected
Referenced by addColorDefinition(), addSBMLAttributes(), CLRenderInformationBase(), createColorDefinition(), getColorDefinition(), getListOfColorDefinitions(), getNumColorDefinitions(), and removeColorDefinition().
mListOfGradientDefinitions
CDataVector<CLGradientBase> CLRenderInformationBase::mListOfGradientDefinitions protected
Referenced by addGradientDefinition(), addSBMLAttributes(), CLRenderInformationBase(), createLinearGradientDefinition(), createRadialGradientDefinition(), getGradientDefinition(), getListOfGradientDefinitions(), getNumGradientDefinitions(), and removeGradientDefinition().
mListOfLineEndings
CDataVector<CLLineEnding> CLRenderInformationBase::mListOfLineEndings protected
Referenced by addLineEnding(), addSBMLAttributes(), CLRenderInformationBase(), createLineEnding(), getLineEnding(), getListOfLineEndings(), getNumLineEndings(), and removeLineEnding().
mName
std::string CLRenderInformationBase::mName protected
The name of the render information, which is more informative than the key.
Referenced by addSBMLAttributes(), getName(), and setName().
mReferenceRenderInformation
std::string CLRenderInformationBase::mReferenceRenderInformation protected
Referenced by getReferenceRenderInformationKey(), and setReferenceRenderInformationKey().
The documentation for this class was generated from the following files:
CLRenderInformationBase.h
CLRenderInformationBase.cpp