COPASI API: CModelParameterReactionParameter Class Reference
CModelParameterReactionParameter Class Reference
#include <CModelParameter.h>
Public Member Functions
CModelParameterReactionParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type=CModelParameter::Type::ReactionParameter)
CModelParameterReactionParameter (const CModelParameterReactionParameter &src, CModelParameterGroup *pParent)
virtual void compile ()
const CRegisteredCommonName & getGlobalQuantityCN () const
const CReaction * getReaction () const
void setGlobalQuantityCN (const std::string &globalQuantityCN)
virtual ~CModelParameterReactionParameter ()
Public Member Functions inherited from CModelParameter
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CModelParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type)
CModelParameter (const CModelParameter &src, CModelParameterGroup *pParent)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual void destruct ()
virtual const CompareResult & diff (const CModelParameter &other, const CCore::Framework &framework=CCore::Framework::ParticleNumbers, const bool &createMissing=false)
virtual const CModelParameter * getChild (const size_t &index) const
const CCommonName & getCN () const
const CompareResult & getCompareResult () const
virtual size_t getIndex () const
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CModel * getModel () const
virtual std::string getName () const
virtual size_t getNumChildren () const
CDataObject * getObject () const
CModelParameterGroup * getParent () const
CModelParameterSet * getSet () const
const CModelEntity::Status & getSimulationType () const
const Type & getType () const
CValidatedUnit getUnit (const CCore::Framework &framework) const
virtual const double & getValue (const CCore::Framework &framework) const
bool isInitialExpressionValid () const
bool isReadOnly () const
bool operator< (const CModelParameter &rhs) const
virtual bool refreshFromModel (const bool &modifyExistence)
virtual void setCN (const CCommonName &cn)
void setCompareResult (const CompareResult &compareResult)
void setInitialExpression (const std::string &initialExpression)
void setParent (CModelParameterGroup *pParent)
bool setSimulationType (const CModelEntity::Status &simulationType)
virtual void setValue (const C_FLOAT64 &value, const CCore::Framework &framework, bool updateModelIfActive=true)
virtual CData toData () const
virtual CModelParameterSet * toSet ()
virtual const CModelParameterSet * toSet () const
virtual bool updateModel ()
virtual ~CModelParameter ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CCommonName getReactionCN (const CCommonName &reactionParameterCN)
Static Public Member Functions inherited from CModelParameter
static CModelParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Private Attributes
CRegisteredCommonName mGlobalQuantityCN
CModelParameter * mpGlobalQuantity
CReaction * mpReaction
Additional Inherited Members
Public Types inherited from CModelParameter
enum class CompareResult {
Obsolete , Missing , Modified , Conflict ,
Identical , __SIZE
}
enum class Type {
Model , Compartment , Species , ModelValue ,
ReactionParameter , Reaction , Group , Set ,
unknown , __SIZE
}
Static Public Attributes inherited from CModelParameter
static const CEnumAnnotation< std::string, CompareResult > CompareResultNames
static const CEnumAnnotation< std::string, Type > TypeNames
Protected Attributes inherited from CModelParameter
CRegisteredCommonName mCN
CompareResult mCompareResult
bool mIsInitialExpressionValid
CExpression * mpInitialExpression
CDataObject * mpObject
CModelParameterGroup * mpParent
CModelEntity::Status mSimulationType
Type mType
double mValue
Constructor & Destructor Documentation
CModelParameterReactionParameter() [1/2]
CModelParameterReactionParameter::CModelParameterReactionParameter (CModelParameterGroup * pParent, const CModelParameter::Type & type = CModelParameter::Type::ReactionParameter)
Constructor
CModelParameterReactionParameter() [2/2]
CModelParameterReactionParameter::CModelParameterReactionParameter (const CModelParameterReactionParameter & src, CModelParameterGroup * pParent)
Copy constructor
~CModelParameterReactionParameter()
CModelParameterReactionParameter::~CModelParameterReactionParameter () virtual
Destructor
Member Function Documentation
compile()
void CModelParameterReactionParameter::compile () virtual
Compile the parameter
Reimplemented from CModelParameter.
References CModelEntity::ASSIGNMENT, CModelParameter::compile(), CObjectInterface::DataObject(), CModelEntity::FIXED, CModelParameter::getCN(), CModelParameter::getInitialExpression(), CModelParameter::getModel(), CModelParameterGroup::getModelParameter(), CObjectInterface::GetObjectFromCN(), CModelParameter::getSet(), CModelParameter::getValue(), mGlobalQuantityCN, mpGlobalQuantity, CModelParameter::mpParent, mpReaction, CModelParameter::mValue, CCore::ParticleNumbers, CModelParameter::setSimulationType(), CCommonName::split(), and CModelParameterSet::toGroup().
Referenced by setGlobalQuantityCN().
getGlobalQuantityCN()
const CRegisteredCommonName & CModelParameterReactionParameter::getGlobalQuantityCN () const
Retrieve the CN of the assigned global quantity
Returns
const CRegisteredCommonName & globalQuantityCN
References mGlobalQuantityCN.
Referenced by CModelParameterGroup::getObjectUnit().
getReaction()
const CReaction * CModelParameterReactionParameter::getReaction () const
Retrieve a pointer to the reaction the parameter belongs to.
Returns
const CReaction * reaction
References mpReaction.
getReactionCN()
CCommonName CModelParameterReactionParameter::getReactionCN (const CCommonName & reactionParameterCN) static
Retrieve the CN of the reaction the parameter belongs to
Parameters
const CCommonName & reactionParameterCN
Returns
CCommonName reationCN
Referenced by CModelParameterSet::insert().
setGlobalQuantityCN()
void CModelParameterReactionParameter::setGlobalQuantityCN (const std::string & globalQuantityCN)
Set the CN of the assigned global quantity. If the CN is empty the assignment is removed.
Parameters
const std::string & globalQuantityCN
References compile(), CModelParameterGroup::compile(), CModelParameter::mpParent, and CModelParameter::setInitialExpression().
Member Data Documentation
mGlobalQuantityCN
CRegisteredCommonName CModelParameterReactionParameter::mGlobalQuantityCN private
The CN of the assigned global quantity.
Referenced by compile(), and getGlobalQuantityCN().
mpGlobalQuantity
CModelParameter* CModelParameterReactionParameter::mpGlobalQuantity private
A pointer to the parameter representing the assigned global quantity.
Referenced by compile().
mpReaction
CReaction* CModelParameterReactionParameter::mpReaction private
A pointer to the reaction the parameter belongs to.
Referenced by compile(), and getReaction().
The documentation for this class was generated from the following files:
CModelParameter.h
CModelParameter.cpp