COPASI API: CLRectangle Class Reference
CLRectangle Class Reference
#include <CLRectangle.h>
Public Member Functions
CLRectangle (CDataContainer *pParent=NULL)
CLRectangle (const CLRectangle &source, CDataContainer *pParent=NULL)
CLRectangle (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &w, const CLRelAbsVector &h, CDataContainer *pParent=NULL)
CLRectangle (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z, const CLRelAbsVector &w, const CLRelAbsVector &h, CDataContainer *pParent=NULL)
CLRectangle (const sbmlRectangle &source, CDataContainer *pParent=NULL)
CLRelAbsVector & getHeight ()
const CLRelAbsVector & getHeight () const
const std::string & getKey () const
CLRelAbsVector & getRadiusX ()
const CLRelAbsVector & getRadiusX () const
CLRelAbsVector & getRadiusY ()
const CLRelAbsVector & getRadiusY () const
CLRelAbsVector & getWidth ()
const CLRelAbsVector & getWidth () const
CLRelAbsVector & getX ()
const CLRelAbsVector & getX () const
CLRelAbsVector & getY ()
const CLRelAbsVector & getY () const
CLRelAbsVector & getZ ()
const CLRelAbsVector & getZ () const
void setCoordinates (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z)
void setCoordinatesAndSize (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z, const CLRelAbsVector &w, const CLRelAbsVector &h)
void setHeight (const CLRelAbsVector &h)
void setRadii (const CLRelAbsVector &rx, const CLRelAbsVector &ry)
void setRadiusX (const CLRelAbsVector &rx)
void setRadiusY (const CLRelAbsVector &ry)
void setSize (const CLRelAbsVector &w, const CLRelAbsVector &h)
void setWidth (const CLRelAbsVector &w)
void setX (const CLRelAbsVector &x)
void setY (const CLRelAbsVector &y)
void setZ (const CLRelAbsVector &z)
sbmlRectangle * toSBML (unsigned int level, unsigned int version) const
~CLRectangle ()
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
virtual const CDataObject * getValueObject () const
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const override
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Protected Attributes
CLRelAbsVector mHeight
std::string mKey
CLRelAbsVector mRX
CLRelAbsVector mRY
CLRelAbsVector mWidth
CLRelAbsVector mX
CLRelAbsVector mY
CLRelAbsVector mZ
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLRectangle & operator= (const CLRectangle &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET , NONZERO , EVENODD , INHERIT }
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLRectangle() [1/5]
CLRectangle::CLRectangle (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLRectangle() [2/5]
CLRectangle::CLRectangle (const CLRectangle & source, CDataContainer * pParent = NULL)
Copy Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLRectangle() [3/5]
CLRectangle::CLRectangle (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z, const CLRelAbsVector & w, const CLRelAbsVector & h, CDataContainer * pParent = NULL)
Constructor that takes x, y and z coordinate values, the width and the height.
Constructor that takes an id, the x, y and z coordinate values, the width and the height.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLRectangle() [4/5]
CLRectangle::CLRectangle (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & w, const CLRelAbsVector & h, CDataContainer * pParent = NULL)
Constructor that takes x and y coordinate values, the width and the height.
Constructor that takes an id, x and y coordinate values, the width and the height.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLRectangle() [5/5]
CLRectangle::CLRectangle (const sbmlRectangle & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
~CLRectangle()
CLRectangle::~CLRectangle ()
Destructor.
Destructor
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
getHeight() [1/2]
CLRelAbsVector & CLRectangle::getHeight ()
Returns the height.
References mHeight.
getHeight() [2/2]
const CLRelAbsVector & CLRectangle::getHeight () const
Returns the height.
References mHeight.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
getKey()
const std::string & CLRectangle::getKey () const virtual
Returns the key string of the object.
Returns the key of the rectangle
Reimplemented from CDataObject.
References mKey.
getRadiusX() [1/2]
CLRelAbsVector & CLRectangle::getRadiusX ()
Returns the corner radius along th x axis.
References mRX.
getRadiusX() [2/2]
const CLRelAbsVector & CLRectangle::getRadiusX () const
Returns the corner radius along th x axis.
References mRX.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
getRadiusY() [1/2]
CLRelAbsVector & CLRectangle::getRadiusY ()
Returns the corner radius along the y axis.
References mRY.
getRadiusY() [2/2]
const CLRelAbsVector & CLRectangle::getRadiusY () const
Returns the corner radius along the y axis.
References mRY.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
getWidth() [1/2]
CLRelAbsVector & CLRectangle::getWidth ()
Returns the width.
References mWidth.
getWidth() [2/2]
const CLRelAbsVector & CLRectangle::getWidth () const
Returns the width.
References mWidth.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
getX() [1/2]
CLRelAbsVector & CLRectangle::getX ()
Returns the x coordinate.
References mX.
getX() [2/2]
const CLRelAbsVector & CLRectangle::getX () const
Returns the x coordinate.
References mX.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
getY() [1/2]
CLRelAbsVector & CLRectangle::getY ()
Returns the y coordinate.
References mY.
getY() [2/2]
const CLRelAbsVector & CLRectangle::getY () const
Returns the y coordinate.
References mY.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
getZ() [1/2]
CLRelAbsVector & CLRectangle::getZ ()
Returns the z coordinate.
References mZ.
getZ() [2/2]
const CLRelAbsVector & CLRectangle::getZ () const
Returns the z coordinate.
References mZ.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
operator=()
CLRectangle& CLRectangle::operator= (const CLRectangle & source) private
setCoordinates()
void CLRectangle::setCoordinates (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z)
Sets the position.
References mX, mY, and mZ.
Referenced by setCoordinatesAndSize().
setCoordinatesAndSize()
void CLRectangle::setCoordinatesAndSize (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z, const CLRelAbsVector & w, const CLRelAbsVector & h)
Sets the position, the width and the height.
References setCoordinates(), and setSize().
Referenced by RectangleHandler::processStart().
setHeight()
void CLRectangle::setHeight (const CLRelAbsVector & h)
Sets the height.
References mHeight.
setRadii()
void CLRectangle::setRadii (const CLRelAbsVector & rx, const CLRelAbsVector & ry)
Sets the corner radii.
Sets the size.
References mRX, and mRY.
Referenced by RectangleHandler::processStart().
setRadiusX()
void CLRectangle::setRadiusX (const CLRelAbsVector & rx)
Sets the x radius for the corners.
References mRX.
setRadiusY()
void CLRectangle::setRadiusY (const CLRelAbsVector & ry)
Sets the y radius for the corners.
References mRY.
setSize()
void CLRectangle::setSize (const CLRelAbsVector & w, const CLRelAbsVector & h)
Sets the size.
References mHeight, and mWidth.
Referenced by setCoordinatesAndSize().
setWidth()
void CLRectangle::setWidth (const CLRelAbsVector & w)
Sets the width.
References mWidth.
setX()
void CLRectangle::setX (const CLRelAbsVector & x)
Sets the x position.
References mX.
setY()
void CLRectangle::setY (const CLRelAbsVector & y)
Sets the y position.
References mY.
setZ()
void CLRectangle::setZ (const CLRelAbsVector & z)
Sets the z position.
References mZ.
toSBML()
Rectangle * CLRectangle::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLGraphicalPrimitive2D::addSBMLAttributes(), mHeight, mRX, mRY, mWidth, mX, mY, mZ, and CLRelAbsVector::toSBML().
Member Data Documentation
mHeight
CLRelAbsVector CLRectangle::mHeight protected
Referenced by getHeight(), setHeight(), setSize(), and toSBML().
mKey
std::string CLRectangle::mKey protected
key for the object.
Referenced by CLRectangle(), getKey(), and ~CLRectangle().
mRX
CLRelAbsVector CLRectangle::mRX protected
Referenced by getRadiusX(), setRadii(), setRadiusX(), and toSBML().
mRY
CLRelAbsVector CLRectangle::mRY protected
Referenced by getRadiusY(), setRadii(), setRadiusY(), and toSBML().
mWidth
CLRelAbsVector CLRectangle::mWidth protected
Referenced by getWidth(), setSize(), setWidth(), and toSBML().
mX
CLRelAbsVector CLRectangle::mX protected
Referenced by getX(), setCoordinates(), setX(), and toSBML().
mY
CLRelAbsVector CLRectangle::mY protected
Referenced by getY(), setCoordinates(), setY(), and toSBML().
mZ
CLRelAbsVector CLRectangle::mZ protected
Referenced by getZ(), setCoordinates(), setZ(), and toSBML().
The documentation for this class was generated from the following files:
CLRectangle.h
CLRectangle.cpp