COPASI API: CLNATask Class Reference
CLNATask Class Reference
#include <CLNATask.h>
Public Member Functions
CLNATask (const CDataContainer *pParent, const CTaskEnum::Task &type=CTaskEnum::Task::lna)
CLNATask (const CLNATask &src, const CDataContainer *pParent)
virtual const CTaskEnum::Method * getValidMethods () const override
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream) override
void load (CReadConfig &configBuffer)
void printResult (std::ostream *ostream) const
virtual bool process (const bool &useInitialValues) override
virtual bool setCallBack (CProcessReportLevel callBack) override
virtual bool updateMatrices () override
virtual ~CLNATask ()
Public Member Functions inherited from CCopasiTask
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiTask (const CCopasiTask &src, const CDataContainer *pParent)
CCopasiTask (const CDataContainer *pParent, const CTaskEnum::Task &taskType, const std::string &type="Task")
void cleanup ()
virtual void clearCallBack ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const CProcessReportLevel & getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CMathContainer * getMathContainer () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CReport & getReport () const
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
CTaskEnum::Task getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual bool restore (const bool &updateModel=true)
virtual void separate (const COutputInterface::Activity &activity)
void setIgnoreProblemData (const bool &ignoreProblemData)
void setMathContainer (CMathContainer *pContainer)
bool setMethodType (const CTaskEnum::Method &type)
void setScheduled (const bool &scheduled)
void setType (const CTaskEnum::Task &type)
virtual void setUpdateModel (const bool &updateModel)
virtual CData toData () const
virtual ~CCopasiTask ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Private Member Functions
void cleanup ()
CLNATask ()
Friends
std::ostream & operator<< (std::ostream &os, const CLNATask &A)
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01 , STREAM = 0x02 , FINISH = 0x04 , REPORT = 0x10 ,
PLOT = 0x20 , TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0 , OUTPUT_BEFORE = INITIALIZE , OUTPUT_DURING = STREAM , OUTPUT_AFTER = FINISH ,
OUTPUT = REPORT | PLOT | STREAM , OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH , OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH , ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiTask
static CCopasiTask * fromData (const CData &data, CUndoObjectInterface *pParent)
static bool isValidMethod (const CTaskEnum::Method &method, const CTaskEnum::Method *validMethods)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CCopasiTask
bool isTaskValid () const
virtual void signalMathContainerChanged ()
virtual void signalMethodChanged ()
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
bool mIgnoreProblemData
CVector< C_FLOAT64 > mInitialState
std::string mKey
unsigned C_INT32 mOutputCounter
CMathContainer * mpContainer
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CProcessReportLevel mProcessReport
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
CTaskEnum::Task mType
bool mUpdateModel
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CLNATask() [1/3]
CLNATask::CLNATask () private
Default constructor
CLNATask() [2/3]
CLNATask::CLNATask (const CDataContainer * pParent, const CTaskEnum::Task & type = CTaskEnum::Task::lna)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Task & type (default: lna)
References CMethodFactory::create(), CCopasiTask::getType(), CTaskEnum::linearNoiseApproximation, and CCopasiTask::mpMethod.
CLNATask() [3/3]
CLNATask::CLNATask (const CLNATask & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CLNATask & src
const CDataContainer * pParent (default: NULL)
~CLNATask()
CLNATask::~CLNATask () virtual
Destructor
Member Function Documentation
cleanup()
void CLNATask::cleanup () private
cleanup()
getValidMethods()
const CTaskEnum::Method * CLNATask::getValidMethods () const override virtual
Retrieve the list of valid methods
Returns
const CTaskEnum::Method * pValidMethods
Reimplemented from CCopasiTask.
References CTaskEnum::linearNoiseApproximation, and CTaskEnum::UnsetMethod.
initialize()
bool CLNATask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) override virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
References CReport::getStream(), CLNAProblem::getSubTask(), CCopasiTask::initialize(), CCopasiMethod::isValidProblem(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiTask::mReport, CCopasiTask::NO_OUTPUT, and updateMatrices().
load()
void CLNATask::load (CReadConfig & configBuffer)
Loads parameters for this solver with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
configbuffer reference to a CReadConfig object.
References CReadConfig::getVariable(), CReadConfig::LOOP, CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CCopasiTask::mScheduled.
printResult()
void CLNATask::printResult (std::ostream * ostream) const
This functionality is expected from the problem but has to be implemented here for the moment. This is called from the corresponding method of the problem
References CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateMethod::foundNegative, CLNAMethod::getCovarianceMatrixAnn(), CLNAMethod::getSteadyStateStatus(), CLNAProblem::getSubTask(), CLNAProblem::isSteadyStateRequested(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CSteadyStateMethod::notFound.
Referenced by CLNAProblem::printResult().
process()
bool CLNATask::process (const bool & useInitialValues) override virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
References COutputInterface::AFTER, CLNAMethod::allNeg, CMathContainer::applyInitialValues(), COutputInterface::BEFORE, COutputInterface::DURING, CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateTask::getEigenValuesReduced(), CEigen::getNimag(), CEigen::getNposreal(), CEigen::getNzero(), CCopasiTask::getProblem(), CSteadyStateTask::getResult(), CCopasiProblem::getSubTask(), CCopasiTask::mpContainer, CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiTask::mProcessReport, CLNAMethod::nonNegEigenvaluesExist, CSteadyStateMethod::notFound, CCopasiTask::output(), CLNAMethod::process(), CSteadyStateTask::process(), CCopasiTask::setCallBack(), CLNAMethod::setEigenValueStatus(), CSteadyStateProblem::setStabilityAnalysisRequested(), and CLNAMethod::setSteadyStateStatus().
setCallBack()
bool CLNATask::setCallBack (CProcessReportLevel callBack) override virtual
Set the call back of the task
Parameters
CProcessReport * pCallBack
Returns
bool success
Reimplemented from CCopasiTask.
References CCopasiProblem::getSubTask(), CCopasiTask::mpProblem, CCopasiTask::mProcessReport, and CCopasiTask::setCallBack().
updateMatrices()
bool CLNATask::updateMatrices () override virtual
Resizes result matrices and updates array annotations for a specific task. This is used when we need to know about the data structures of a task result without actually performing the task, e.g. when selecting objects for output. For now we assume that this functionality is also performed when initialize() is called.
Reimplemented from CCopasiTask.
References CCopasiMethod::isValidProblem(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CLNAMethod::resizeAllMatrices().
Referenced by initialize().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CLNATask & A) friend
The documentation for this class was generated from the following files:
CLNATask.h
CLNATask.cpp