COPASI API: CUnitParserBase Class Reference
CUnitParserBase Class Reference abstract
#include <CUnitParser.h>
Classes
struct Data
Public Member Functions
CUnitParserBase ()
const std::set< CUnitComponent > & getComponents () const
const std::string & getReplacedExpression () const
const std::set< std::string > & getSymbols () const
void replaceSymbol (const std::string &oldSymbol, const std::string &newSymbol)
virtual int yylex ()=0
virtual int yyparse ()
virtual ~ CUnitParserBase ()
Protected Member Functions
void correctErrorPosition ()
Protected Attributes
std::string mNewSymbol
std::string mOldSymbol
const CUnitDefinition * mpCurrentUnitDef
unsigned C_INT32 mPosition
CUnit * mpUnit
std::string mReplacedExpression
std::set< std::string > mSymbols
Detailed Description
This is a base class for the CUnitParser adding member attributes to enhance the internal functionality.
Constructor & Destructor Documentation
CUnitParserBase()
CUnitParserBase::CUnitParserBase ()
Default constructor
~ CUnitParserBase()
virtual CUnitParserBase::~ CUnitParserBase () virtual
Destructor
Member Function Documentation
correctErrorPosition()
void CUnitParserBase::correctErrorPosition () protected
getComponents()
const std::set< CUnitComponent > & CUnitParserBase::getComponents () const
References CUnit::getComponents(), and mpUnit.
Referenced by CUnit::compile().
getReplacedExpression()
const std::string & CUnitParserBase::getReplacedExpression () const
References mReplacedExpression.
Referenced by CUnit::replaceSymbol().
getSymbols()
const std::set< std::string > & CUnitParserBase::getSymbols () const
References mSymbols.
Referenced by CUnit::compile().
replaceSymbol()
void CUnitParserBase::replaceSymbol (const std::string & oldSymbol, const std::string & newSymbol)
References mNewSymbol, and mOldSymbol.
Referenced by CUnit::replaceSymbol().
yylex()
virtual int CUnitParserBase::yylex () pure virtual
Implemented in CUnitParser.
yyparse()
int CUnitParserBase::yyparse (void) virtual
References YY_, YY_ASSERT, YY_CAST, YY_IGNORE_USELESS_CAST_BEGIN, YY_IGNORE_USELESS_CAST_END, YYABORT, YYACCEPT, yychar, YYDPRINTF, YYEMPTY, YYFINAL, YYINITDEPTH, YYMAXDEPTH, yynerrs, YYNSTATES, YYPTRDIFF_T, YYSIZE_T, YYSIZEOF, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYSTYPE, and yyalloc::yyvs_alloc.
Referenced by CUnit::compile(), and CUnit::replaceSymbol().
Member Data Documentation
mNewSymbol
std::string CUnitParserBase::mNewSymbol protected
Referenced by replaceSymbol().
mOldSymbol
std::string CUnitParserBase::mOldSymbol protected
Referenced by replaceSymbol().
mpCurrentUnitDef
const CUnitDefinition* CUnitParserBase::mpCurrentUnitDef protected
mPosition
unsigned C_INT32 CUnitParserBase::mPosition protected
mpUnit
CUnit* CUnitParserBase::mpUnit protected
Referenced by getComponents().
mReplacedExpression
std::string CUnitParserBase::mReplacedExpression protected
Referenced by getReplacedExpression().
mSymbols
std::set< std::string > CUnitParserBase::mSymbols protected
Referenced by getSymbols().
The documentation for this class was generated from the following files:
CUnitParser.h
CUnitParser.cpp
CUnitParser_yacc.cpp