COPASI API: CLRenderCurve Class Reference
CLRenderCurve Class Reference
#include <CLRenderCurve.h>
Public Member Functions
void addCurveElement (const CLRenderPoint *cs)
CLRenderCurve (CDataContainer *pParent=NULL)
CLRenderCurve (const CLRenderCurve &source, CDataContainer *pParent=NULL)
CLRenderCurve (const RenderCurve &source, CDataContainer *pParent=NULL)
CLRenderCubicBezier * createCubicBezier ()
CLRenderPoint * createPoint ()
CLRenderPoint * getCurveElement (size_t index)
const CLRenderPoint * getCurveElement (size_t index) const
const std::string & getEndHead () const
const std::string & getKey () const
std::vector< CLRenderPoint * > * getListOfCurveElements ()
const std::vector< CLRenderPoint * > * getListOfCurveElements () const
size_t getNumElements () const
const std::string & getStartHead () const
bool isSetEndHead () const
bool isSetStartHead () const
void removeCurveElement (size_t i)
void setEndHead (const std::string &endHead)
void setStartHead (const std::string &startHead)
RenderCurve * toSBML (unsigned int level, unsigned int version) const
~CLRenderCurve ()
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
virtual const CDataObject * getValueObject () const
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const override
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Protected Attributes
std::string mEndHead
std::string mKey
std::vector< CLRenderPoint * > mListOfElements
std::string mStartHead
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLRenderCurve & operator= (const CLRenderCurve &source)
Friends
class Group
Additional Inherited Members
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLRenderCurve() [1/3]
CLRenderCurve::CLRenderCurve (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLRenderCurve() [2/3]
CLRenderCurve::CLRenderCurve (const CLRenderCurve & source, CDataContainer * pParent = NULL)
Copy Constructor
Copy constructor
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and mListOfElements.
CLRenderCurve() [3/3]
CLRenderCurve::CLRenderCurve (const RenderCurve & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and mListOfElements.
~CLRenderCurve()
CLRenderCurve::~CLRenderCurve ()
Destructor
References CRootContainer::getKeyFactory(), mKey, mListOfElements, and CKeyFactory::remove().
Member Function Documentation
addCurveElement()
void CLRenderCurve::addCurveElement (const CLRenderPoint * pCS)
Adds a copy of the given curve segment to the end of the list of curve segments.
References mListOfElements.
createCubicBezier()
CLRenderCubicBezier * CLRenderCurve::createCubicBezier ()
Creates a new bezier element. The element is added to the curve.
Creates a new cubic bezier curve segment.
References mListOfElements.
createPoint()
CLRenderPoint * CLRenderCurve::createPoint ()
Creates a new point element. The element is added to the curve.
Creates a new curve segment.
References mListOfElements.
getCurveElement() [1/2]
CLRenderPoint * CLRenderCurve::getCurveElement (size_t index)
Returns a pointer to the curve segment with the given index or NULL if the id is invalid.
References mListOfElements.
getCurveElement() [2/2]
const CLRenderPoint * CLRenderCurve::getCurveElement (size_t index) const
Returns a const pointer to the curve segment with the given index or NULL if the id is invalid.
References mListOfElements.
Referenced by CLLayoutRenderer::draw_curve().
getEndHead()
const std::string & CLRenderCurve::getEndHead () const
Returns the id of the end head.
References mEndHead.
Referenced by CLLayoutRenderer::update_textures_and_colors().
getKey()
const std::string & CLRenderCurve::getKey () const virtual
Returns the key string of the object.
Returns the key of the color definition.
Reimplemented from CDataObject.
References mKey.
getListOfCurveElements() [1/2]
std::vector< CLRenderPoint * > * CLRenderCurve::getListOfCurveElements ()
Returns a pointer to the list of curve segments.
References mListOfElements.
getListOfCurveElements() [2/2]
const std::vector< CLRenderPoint * > * CLRenderCurve::getListOfCurveElements () const
Returns a const pointer to the list of curve segments.
References mListOfElements.
Referenced by RenderCurveHandler::processStart(), and CCopasiXML::saveRenderCurveElement().
getNumElements()
size_t CLRenderCurve::getNumElements () const
Returns the number of curve segments.
References mListOfElements.
Referenced by CLLayoutRenderer::draw_curve().
getStartHead()
const std::string & CLRenderCurve::getStartHead () const
Returns the id of the start head.
References mStartHead.
Referenced by CLLayoutRenderer::update_textures_and_colors().
isSetEndHead()
bool CLRenderCurve::isSetEndHead () const
Returns true if the start head is set or false otherwise.
References mEndHead.
Referenced by CLLayoutRenderer::update_textures_and_colors().
isSetStartHead()
bool CLRenderCurve::isSetStartHead () const
Returns true if the start head is set or false otherwise.
References mStartHead.
Referenced by CLLayoutRenderer::update_textures_and_colors().
operator=()
CLRenderCurve& CLRenderCurve::operator= (const CLRenderCurve & source) private
removeCurveElement()
void CLRenderCurve::removeCurveElement (size_t i)
Removes the curve segment with the given index.
References mListOfElements.
setEndHead()
void CLRenderCurve::setEndHead (const std::string & endHead)
Sets the id of the end head.
References mEndHead.
Referenced by RenderCurveHandler::processStart().
setStartHead()
void CLRenderCurve::setStartHead (const std::string & startHead)
Sets the id of the start head.
References mStartHead.
Referenced by RenderCurveHandler::processStart().
toSBML()
RenderCurve * CLRenderCurve::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLGraphicalPrimitive1D::addSBMLAttributes(), mEndHead, mListOfElements, and mStartHead.
Friends And Related Function Documentation
Group
friend class Group friend
Member Data Documentation
mEndHead
std::string CLRenderCurve::mEndHead protected
Referenced by getEndHead(), isSetEndHead(), setEndHead(), and toSBML().
mKey
std::string CLRenderCurve::mKey protected
key for the object.
Referenced by CLRenderCurve(), getKey(), and ~CLRenderCurve().
mListOfElements
std::vector<CLRenderPoint*> CLRenderCurve::mListOfElements protected
Referenced by addCurveElement(), CLRenderCurve(), createCubicBezier(), createPoint(), getCurveElement(), getListOfCurveElements(), getNumElements(), removeCurveElement(), toSBML(), and ~CLRenderCurve().
mStartHead
std::string CLRenderCurve::mStartHead protected
Referenced by getStartHead(), isSetStartHead(), setStartHead(), and toSBML().
The documentation for this class was generated from the following files:
CLRenderCurve.h
CLRenderCurve.cpp