COPASI API: CTimeSensTask Class Reference
CTimeSensTask Class Reference
#include <CTimeSensTask.h>
Public Member Functions
CTimeSensTask (const CDataContainer *pParent, const CTaskEnum::Task &type=CTaskEnum::Task::timeSens)
CTimeSensTask (const CTimeSensTask &src, const CDataContainer *pParent)
const CTimeSeries & getTimeSeries () const
virtual const CTaskEnum::Method * getValidMethods () const
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
virtual void output (const COutputInterface::Activity &activity)
virtual bool process (const bool &useInitialValues)
bool processStart (const bool &useInitialValues)
bool processStep (const C_FLOAT64 &nextTime, const bool &final=false)
virtual bool updateMatrices ()
~CTimeSensTask ()
Public Member Functions inherited from CCopasiTask
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiTask (const CCopasiTask &src, const CDataContainer *pParent)
CCopasiTask (const CDataContainer *pParent, const CTaskEnum::Task &taskType, const std::string &type="Task")
void cleanup ()
virtual void clearCallBack ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const CProcessReportLevel & getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CMathContainer * getMathContainer () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CReport & getReport () const
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
CTaskEnum::Task getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual bool restore (const bool &updateModel=true)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReportLevel callBack)
void setIgnoreProblemData (const bool &ignoreProblemData)
void setMathContainer (CMathContainer *pContainer)
bool setMethodType (const CTaskEnum::Method &type)
void setScheduled (const bool &scheduled)
void setType (const CTaskEnum::Task &type)
virtual void setUpdateModel (const bool &updateModel)
virtual CData toData () const
virtual ~CCopasiTask ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Attributes
static const CTaskEnum::Method ValidMethods []
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions
virtual void signalMathContainerChanged ()
virtual void signalMethodChanged ()
Protected Member Functions inherited from CCopasiTask
bool isTaskValid () const
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
CVectorCore< C_FLOAT64 > mContainerState
C_FLOAT64 mOutputStartTime
C_FLOAT64 * mpContainerStateTime
bool(* mpLess)(const C_FLOAT64 &, const C_FLOAT64 &)
bool(* mpLessOrEqual)(const C_FLOAT64 &, const C_FLOAT64 &)
bool mProceed
CSteadyStateTask * mpSteadyState
CTimeSensMethod * mpTimeSensMethod
CTimeSensProblem * mpTimeSensProblem
CTimeSeries mTimeSeries
bool mTimeSeriesRequested
bool mUpdateMoieties
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
bool mIgnoreProblemData
CVector< C_FLOAT64 > mInitialState
std::string mKey
unsigned C_INT32 mOutputCounter
CMathContainer * mpContainer
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CProcessReportLevel mProcessReport
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
CTaskEnum::Task mType
bool mUpdateModel
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
void cleanup ()
CTimeSensTask ()
Static Private Member Functions
static bool bl (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
static bool ble (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
static bool fl (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
static bool fle (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01 , STREAM = 0x02 , FINISH = 0x04 , REPORT = 0x10 ,
PLOT = 0x20 , TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0 , OUTPUT_BEFORE = INITIALIZE , OUTPUT_DURING = STREAM , OUTPUT_AFTER = FINISH ,
OUTPUT = REPORT | PLOT | STREAM , OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH , OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH , ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiTask
static CCopasiTask * fromData (const CData &data, CUndoObjectInterface *pParent)
static bool isValidMethod (const CTaskEnum::Method &method, const CTaskEnum::Method *validMethods)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Constructor & Destructor Documentation
CTimeSensTask() [1/3]
CTimeSensTask::CTimeSensTask () private
Default constructor
CTimeSensTask() [2/3]
CTimeSensTask::CTimeSensTask (const CDataContainer * pParent, const CTaskEnum::Task & type = CTaskEnum::Task::timeSens)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Task & type (default: timeCourse)
References CMethodFactory::create(), CCopasiTask::getType(), CCopasiTask::mpMethod, mUpdateMoieties, signalMathContainerChanged(), and CTaskEnum::timeSensLsoda.
CTimeSensTask() [3/3]
CTimeSensTask::CTimeSensTask (const CTimeSensTask & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CTimeSensTask & src
const CDataContainer * pParent (default: NULL)
References CCopasiTask::mpMethod, mUpdateMoieties, and signalMathContainerChanged().
~CTimeSensTask()
CTimeSensTask::~CTimeSensTask ()
Destructor
References cleanup().
Member Function Documentation
bl()
bool CTimeSensTask::bl (const C_FLOAT64 & d1, const C_FLOAT64 & d2) static private
Referenced by process().
ble()
bool CTimeSensTask::ble (const C_FLOAT64 & d1, const C_FLOAT64 & d2) static private
Referenced by process().
cleanup()
void CTimeSensTask::cleanup () private
cleanup()
Referenced by ~CTimeSensTask().
fl()
bool CTimeSensTask::fl (const C_FLOAT64 & d1, const C_FLOAT64 & d2) static private
Referenced by process().
fle()
bool CTimeSensTask::fle (const C_FLOAT64 & d1, const C_FLOAT64 & d2) static private
Referenced by process().
getTimeSeries()
const CTimeSeries & CTimeSensTask::getTimeSeries () const
gets a reference to the time series
Returns
time series
References mTimeSeries.
getValidMethods()
const CTaskEnum::Method * CTimeSensTask::getValidMethods () const virtual
Retrieve the list of valid methods
Returns
const CTaskEnum::Method * pValidMethods
Reimplemented from CCopasiTask.
References ValidMethods.
initialize()
bool CTimeSensTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
References COutputHandler::addInterface(), CTimeSeries::allocate(), CTimeSeries::clear(), CDataObject::getObjectDataModel(), CTrajectoryProblem::getStartInSteadyState(), CTrajectoryProblem::getStepNumber(), CDataModel::getTaskList(), CCopasiTask::initialize(), CSteadyStateTask::initialize(), CTimeSensMethod::integrateReducedModel(), CCopasiMethod::isValidProblem(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, mpSteadyState, mpTimeSensMethod, mpTimeSensProblem, mTimeSeries, mTimeSeriesRequested, mUpdateMoieties, CTimeSensMethod::setProblem(), signalMathContainerChanged(), CCopasiTask::TIME_SERIES, CTrajectoryProblem::timeSeriesRequested(), and updateMatrices().
Referenced by CFitProblem::initialize().
output()
void CTimeSensTask::output (const COutputInterface::Activity & activity) virtual
Perform an output event for the current activity
Parameters
const Activity & activity
Reimplemented from CCopasiTask.
References CTimeSensMethod::copySensitivitiesToResultMatrix(), mpTimeSensMethod, and CCopasiTask::output().
Referenced by CTimeSensMethod::output(), process(), and processStep().
process()
bool CTimeSensTask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
References CProcessReportLevel::addItem(), COutputInterface::AFTER, COutputInterface::BEFORE, bl(), ble(), C_FLOAT64, C_INT32, C_INVALID_INDEX, COutputInterface::DURING, CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CProcessReportLevel::finishItem(), fl(), fle(), CTrajectoryProblem::getAutomaticStepSize(), CTrajectoryProblem::getDuration(), CCopasiException::getMessage(), CTrajectoryProblem::getOutputStartTime(), CMathContainer::getState(), CTrajectoryProblem::getStepSize(), mContainerState, MCTrajectoryMethod, MCTrajectoryProblem, min, mOutputStartTime, CCopasiTask::mpContainer, mpContainerStateTime, mpLess, mpLessOrEqual, mProceed, CCopasiTask::mProcessReport, mpTimeSensMethod, mpTimeSensProblem, mUpdateMoieties, output(), CMathContainer::processQueue(), processStart(), processStep(), CProcessReportLevel::progressItem(), CMathContainer::pushAllTransientValues(), CProcessReportLevel::setName(), CMathContainer::setState(), CTimeSensMethod::stateChange(), CMathContainer::updateSimulatedValues(), and CMathContainer::updateTransientDataValues().
processStart()
bool CTimeSensTask::processStart (const bool & useInitialValues)
Starts the process of integration by calling CTimeSensMethod::start
Parameters
const bool & useInitialValues
Returns
bool success
References CMathContainer::applyInitialValues(), CVectorCore< CType >::array(), CCopasiMessage::ERROR, CMathContainer::getCountFixedEventTargets(), CTrajectoryProblem::getStartInSteadyState(), CMathContainer::getState(), CVectorCore< CType >::initialize(), mContainerState, CCopasiTask::mpContainer, mpContainerStateTime, mpSteadyState, mpTimeSensMethod, mpTimeSensProblem, mUpdateMoieties, CSteadyStateTask::process(), and CTimeSensMethod::start().
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), and process().
processStep()
bool CTimeSensTask::processStep (const C_FLOAT64 & nextTime, const bool & final = false)
Integrates one step
Parameters
const C_FLOAT64 & nextTime
const bool & final (default: false)
Returns
bool success;
References C_FLOAT64, COutputInterface::DURING, CCopasiMessage::EXCEPTION, CTimeSensMethod::FAILURE, CTrajectoryProblem::getAutomaticStepSize(), CTrajectoryProblem::getOutputEvent(), CMathContainer::getProcessQueueExecutionTime(), CTimeSensMethod::getRoots(), CMathContainer::getState(), mContainerState, MCTrajectoryMethod, min, mOutputStartTime, CCopasiTask::mpContainer, mpContainerStateTime, mpLessOrEqual, mProceed, CCopasiTask::mProcessReport, mpTimeSensMethod, mpTimeSensProblem, mUpdateMoieties, CFlags< eStateChange >::None, CTimeSensMethod::NORMAL, output(), CProcessReportLevel::proceed(), CMathContainer::processQueue(), CMathContainer::processRoots(), CTimeSensMethod::ROOT, CMathContainer::setState(), CTimeSensMethod::stateChange(), CTimeSensMethod::step(), CMathContainer::updateRootValues(), and CMathContainer::updateSimulatedValues().
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), and process().
signalMathContainerChanged()
void CTimeSensTask::signalMathContainerChanged () protected virtual
Signal that the math container has changed
Reimplemented from CCopasiTask.
References CVectorCore< CType >::array(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getState(), CVectorCore< CType >::initialize(), mContainerState, CCopasiTask::mpContainer, mpContainerStateTime, and mUpdateMoieties.
Referenced by CTimeSensTask(), and initialize().
signalMethodChanged()
void CTimeSensTask::signalMethodChanged () protected virtual
Signal that the method has changed
Reimplemented from CCopasiTask.
References CCopasiTask::mpMethod, and mUpdateMoieties.
updateMatrices()
bool CTimeSensTask::updateMatrices () virtual
Resizes result matrices and updates array annotations for a specific task. For now this will be hard coded in the respective derived classes. We may introduce a more generic mechanism for this in the future. This is used when we need to know about the data structures of a task result without actually performing the task, e.g. when selecting objects for output. For now we assume that this functionality is also performed when initialize() is called.
Reimplemented from CCopasiTask.
References CTimeSensMethod::initResult(), and CCopasiTask::mpMethod.
Referenced by initialize().
Member Data Documentation
mContainerState
CVectorCore< C_FLOAT64 > CTimeSensTask::mContainerState protected
The current state of the integration.
Referenced by process(), processStart(), processStep(), and signalMathContainerChanged().
mOutputStartTime
C_FLOAT64 CTimeSensTask::mOutputStartTime protected
A pointer to the time at which the output starts.
Referenced by process(), and processStep().
mpContainerStateTime
C_FLOAT64* CTimeSensTask::mpContainerStateTime protected
A pointer to the current time of the integration.
Referenced by process(), processStart(), processStep(), and signalMathContainerChanged().
mpLess
bool(* CTimeSensTask::mpLess) (const C_FLOAT64 &, const C_FLOAT64 &) protected
A pointer to less comparison
Referenced by process().
mpLessOrEqual
bool(* CTimeSensTask::mpLessOrEqual) (const C_FLOAT64 &, const C_FLOAT64 &) protected
A pointer to lessOrEqual comparison
Referenced by process(), and processStep().
mProceed
bool CTimeSensTask::mProceed protected
A Boolean flag indication whether to proceed with the integration
Referenced by process(), and processStep().
mpSteadyState
CSteadyStateTask* CTimeSensTask::mpSteadyState protected
Pointer to CSteadyStateTask. To be used in processStart() to start simulation in steady state
Referenced by initialize(), and processStart().
mpTimeSensMethod
CTimeSensMethod* CTimeSensTask::mpTimeSensMethod protected
A pointer to the time sensitivities method
Referenced by initialize(), output(), process(), processStart(), and processStep().
mpTimeSensProblem
CTimeSensProblem* CTimeSensTask::mpTimeSensProblem protected
A pointer to the time sensitivities Problem
Referenced by initialize(), process(), processStart(), and processStep().
mTimeSeries
CTimeSeries CTimeSensTask::mTimeSeries protected
the time series (if requested)
Referenced by getTimeSeries(), and initialize().
mTimeSeriesRequested
bool CTimeSensTask::mTimeSeriesRequested protected
whether the time series should be stored in mTimeSeries
Referenced by initialize().
mUpdateMoieties
bool CTimeSensTask::mUpdateMoieties protected
Indicates whether we need to update moieties.
Referenced by CTimeSensTask(), initialize(), process(), processStart(), processStep(), signalMathContainerChanged(), and signalMethodChanged().
ValidMethods
const CTaskEnum::Method CTimeSensTask::ValidMethods static
Initial value:
=
{
  CTaskEnum::Method::timeSensLsoda,
  CTaskEnum::Method::UnsetMethod
}
Referenced by getValidMethods().
The documentation for this class was generated from the following files:
CTimeSensTask.h
CTimeSensTask.cpp