COPASI API: CSensItem Class Reference
CSensItem Class Reference
#include <CSensProblem.h>
Public Member Functions
CSensItem ()
CSensItem (CObjectLists::ListType type)
CSensItem (const std::string &cn)
const CObjectLists::ListType & getListType () const
std::string getListTypeDisplayName () const
const CCommonName & getSingleObjectCN () const
std::string getSingleObjectDisplayName (const CDataModel *pDataModel) const
std::vector< CDataObject * > getVariablesPointerList (CDataModel *pDataModel)
bool isSingleObject () const
bool operator!= (const CSensItem &rhs) const
bool operator== (const CSensItem &rhs) const
std::string print (const CDataModel *pDataModel) const
void setListType (CObjectLists::ListType lt)
void setSingleObjectCN (const CCommonName &cn)
Private Attributes
CObjectLists::ListType mListType
CCommonName mSingleObjectCN
Detailed Description
This class describes either one specific COPASI object (represented by a registered object CN internally) or a list of objects (see CObjectLists class).
Constructor & Destructor Documentation
CSensItem() [1/3]
CSensItem::CSensItem ()
CSensItem() [2/3]
CSensItem::CSensItem (const std::string & cn)
CSensItem() [3/3]
CSensItem::CSensItem (CObjectLists::ListType type)
Member Function Documentation
getListType()
const CObjectLists::ListType & CSensItem::getListType () const
References mListType.
Referenced by CSensProblem::copySensItemToParameterGroup(), getVariablesPointerList(), CSensMethod::initialize(), and operator==().
getListTypeDisplayName()
std::string CSensItem::getListTypeDisplayName () const
References CObjectLists::ListTypeName, and mListType.
Referenced by CSensMethod::initialize(), and print().
getSingleObjectCN()
const CCommonName & CSensItem::getSingleObjectCN () const
References mSingleObjectCN.
Referenced by CSensProblem::copySensItemToParameterGroup(), getVariablesPointerList(), and operator==().
getSingleObjectDisplayName()
std::string CSensItem::getSingleObjectDisplayName (const CDataModel * pDataModel) const
References CObjectInterface::getObjectDisplayName(), CDataObject::getObjectFromCN(), and mSingleObjectCN.
Referenced by print().
getVariablesPointerList()
std::vector< CDataObject * > CSensItem::getVariablesPointerList (CDataModel * pDataModel)
References CObjectInterface::DataObject(), CObjectLists::getListOfObjects(), getListType(), CDataModel::getModel(), CDataObject::getObjectFromCN(), getSingleObjectCN(), CDataObject::hasFlag(), isSingleObject(), and CDataObject::ValueDbl.
Referenced by CSensMethod::initialize().
isSingleObject()
bool CSensItem::isSingleObject () const
References mListType, and CObjectLists::SINGLE_OBJECT.
Referenced by CSensProblem::collapsRequested(), CSensProblem::copySensItemToParameterGroup(), getVariablesPointerList(), operator==(), and print().
operator!=()
bool CSensItem::operator!= (const CSensItem & rhs) const
operator==()
bool CSensItem::operator== (const CSensItem & rhs) const
References getListType(), getSingleObjectCN(), and isSingleObject().
print()
std::string CSensItem::print (const CDataModel * pDataModel) const
Had to disable the output operator because the datamodel is needed to print a sensitivity item. std::ostream &operator<<(std::ostream &os, const CSensItem & si) { if (si.isSingleObject()) os << si.getSingleObjectDisplayName(); else os << si.getListTypeDisplayName();
return os; }
References getListTypeDisplayName(), getSingleObjectDisplayName(), and isSingleObject().
setListType()
void CSensItem::setListType (CObjectLists::ListType lt)
References mListType.
Referenced by CSensProblem::copyParameterGroupToSensItem(), CSensProblem::CSensProblem(), CSensProblem::initDebugProblem(), and setSingleObjectCN().
setSingleObjectCN()
void CSensItem::setSingleObjectCN (const CCommonName & cn)
References mSingleObjectCN, setListType(), and CObjectLists::SINGLE_OBJECT.
Referenced by CSensProblem::copyParameterGroupToSensItem(), and CSensProblem::initDebugProblem().
Member Data Documentation
mListType
CObjectLists::ListType CSensItem::mListType private
Referenced by getListType(), getListTypeDisplayName(), isSingleObject(), and setListType().
mSingleObjectCN
CCommonName CSensItem::mSingleObjectCN private
Referenced by getSingleObjectCN(), getSingleObjectDisplayName(), and setSingleObjectCN().
The documentation for this class was generated from the following files:
CSensProblem.h
CSensProblem.cpp