COPASI API: CUnitDefinition Class Reference
CUnitDefinition Class Reference
#include <CUnitDefinition.h>
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
CUnitDefinition (const CUnitDefinition &src, const CDataContainer *pParent=NO_PARENT)
CUnitDefinition (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
virtual const std::string & getKey () const
const std::string & getSymbol () const
bool isReadOnly () const
CUnitDefinition & operator= (const CUnitDefinition &src)
virtual CIssue setExpression (const std::string &expression)
bool setSymbol (const std::string &symbol)
virtual CData toData () const
~CUnitDefinition ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Public Member Functions inherited from CUnit
void addComponent (const CUnitComponent &component)
void buildExpression ()
CIssue compile ()
CUnit ()
CUnit (const CBaseUnit::Kind &kind)
CUnit (const CUnit &src)
CUnit (const std::string &expression)
CUnit exponentiate (double exp) const
void filterUsedSymbols (const CUnitDefinitionDB &unitDefinitiionDB)
const std::set< CUnitComponent > & getComponents () const
std::string getExpression () const
std::vector< SymbolComponent > getSymbolComponents () const
const std::set< std::string > & getUsedSymbols () const
bool isDimensionless () const
bool isEquivalent (const CUnit &rightSide) const
bool isUndefined () const
bool isUnitType (UnitType type) const
bool isValid () const
CUnit operator* (const CUnit &rightSide) const
bool operator< (const CUnit &rightSide) const
CUnit & operator= (const CUnit &rightSide)
bool operator== (const CUnit &rightSide) const
void replaceSymbol (const std::string &oldSymbol, const std::string &newSymbol)
void setDimensionLess (double multiplier, double scale, double exponent)
virtual ~CUnit ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static CUnitDefinition * fromData (const CData &data, CUndoObjectInterface *pParent)
static CUnit getSIUnit (const std::string &symbol)
static bool isBuiltinUnitSymbol (std::string symbol)
static void updateSIUnitDefinitions (CUnitDefinitionDB *Units)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Member Functions inherited from CUnit
static std::string prettyPrint (const std::string &expression)
static std::string replaceSymbol (const std::string &expression, const std::string &oldSymbol, const std::string &newSymbol)
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Private Member Functions
void setup ()
Private Attributes
bool mReadOnly
std::string mSymbol
Friends
std::ostream & operator<< (std::ostream &os, const CUnitDefinition &o)
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Types inherited from CUnit
enum UnitType {
time = 0 , quantity , volume , area ,
length
}
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Static Public Attributes inherited from CUnit
static C_FLOAT64 Avogadro
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Protected Attributes inherited from CAnnotation
std::string mKey
Constructor & Destructor Documentation
CUnitDefinition() [1/2]
CUnitDefinition::CUnitDefinition (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CRootContainer::getKeyFactory(), CAnnotation::initMiriamAnnotation(), CAnnotation::mKey, and setup().
Referenced by fromData(), and updateSIUnitDefinitions().
CUnitDefinition() [2/2]
CUnitDefinition::CUnitDefinition (const CUnitDefinition & src, const CDataContainer * pParent = NO_PARENT)
Copy constructor
Parameters
const CUnitDefinition::& src
const CDataContainer * pParent
References CKeyFactory::add(), CRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CAnnotation::mKey, CAnnotation::setMiriamAnnotation(), and setup().
~CUnitDefinition()
CUnitDefinition::~CUnitDefinition ()
References CRootContainer::getKeyFactory(), CDataObject::getObjectParent(), CAnnotation::mKey, CDataContainer::remove(), and CKeyFactory::remove().
Member Function Documentation
applyData()
bool CUnitDefinition::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CAnnotation::applyData(), CDataContainer::applyData(), CData::getProperty(), CData::isSetProperty(), mSymbol, setExpression(), CDataValue::toString(), CData::UNIT_EXPRESSION, and CData::UNIT_SYMBOL.
createUndoData()
void CUnitDefinition::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CUndoData::addProperty(), CUndoData::CHANGE, CAnnotation::createUndoData(), CDataContainer::createUndoData(), CUnit::getExpression(), CData::getProperty(), mSymbol, CData::UNIT_EXPRESSION, and CData::UNIT_SYMBOL.
fromData()
CUnitDefinition * CUnitDefinition::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CUnitDefinition * pDataObject
References CUnitDefinition(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getKey()
const std::string & CUnitDefinition::getKey () const virtual
Retrieve the key
Returns
std::string key
Reimplemented from CAnnotation.
References CAnnotation::getKey().
Referenced by UnitDefinitionHandler::processEnd(), and CCopasiXML::saveUnitDefinitionList().
getSIUnit()
CUnit CUnitDefinition::getSIUnit (const std::string & symbol) static
References CUnit::CUnit(), SIUnit::expression, SIUnit::name, CUnit::setExpression(), SIUnits, and SIUnit::symbol.
getSymbol()
const std::string & CUnitDefinition::getSymbol () const
References mSymbol.
Referenced by CUnitDefinitionDB::add(), CUnitDefinitionDB::appendDependentUnits(), CUnitDefinitionDB::changeSymbol(), CCopasiXML::mergeUnitDefinitions(), operator=(), CUnitDefinitionDB::remove(), and CCopasiXML::saveUnitDefinitionList().
isBuiltinUnitSymbol()
bool CUnitDefinition::isBuiltinUnitSymbol (std::string symbol) static
References SIUnits, and SIUnit::symbol.
isReadOnly()
bool CUnitDefinition::isReadOnly () const
References mReadOnly.
Referenced by CCopasiXML::saveUnitDefinitionList().
operator=()
CUnitDefinition & CUnitDefinition::operator= (const CUnitDefinition & src)
References C_INVALID_INDEX, CUnitDefinitionDB::containsSymbol(), CCopasiMessage::EXCEPTION, CDataVectorN< CType >::getIndex(), CDataObject::getObjectName(), CDataObject::getObjectParent(), getSymbol(), MCUnitDefinition, mSymbol, CUnit::operator=(), CDataObject::setObjectName(), and setSymbol().
setExpression()
CIssue CUnitDefinition::setExpression (const std::string & expression) virtual
Reimplemented from CUnit.
References CValidity::add(), CFlags< Enum >::All, CIssue::Error, CUnit::getExpression(), CUnit::isUndefined(), CObjectInterface::mValidity, CValidity::remove(), CUnit::setExpression(), CIssue::UnitConflict, CIssue::UnitInvalid, CIssue::UnitUndefined, and CIssue::Warning.
Referenced by applyData(), CCopasiXML::mergeUnitDefinitions(), UnitDefinitionHandler::processEnd(), and updateSIUnitDefinitions().
setSymbol()
bool CUnitDefinition::setSymbol (const std::string & symbol)
References CUnitDefinitionDB::changeSymbol(), CCopasiMessage::ERROR, CDataObject::getObjectParent(), MCUnitDefinition, and mSymbol.
Referenced by CCopasiXML::mergeUnitDefinitions(), operator=(), UnitDefinitionHandler::processStart(), setup(), and updateSIUnitDefinitions().
setup()
void CUnitDefinition::setup () private
References CDataContainer::add(), CKeyFactory::add(), CRootContainer::getKeyFactory(), CDataObject::getObjectParent(), CAnnotation::mKey, mSymbol, and setSymbol().
Referenced by CUnitDefinition().
toData()
CData CUnitDefinition::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::addProperty(), CData::appendData(), CUnit::getExpression(), mSymbol, CAnnotation::toData(), CDataContainer::toData(), CData::UNIT_EXPRESSION, and CData::UNIT_SYMBOL.
updateSIUnitDefinitions()
void CUnitDefinition::updateSIUnitDefinitions (CUnitDefinitionDB * Units) static
References C_INVALID_INDEX, CUnitDefinition(), SIUnit::expression, CDataVectorN< CType >::getIndex(), mReadOnly, SIUnit::name, setExpression(), setSymbol(), SIUnits, and SIUnit::symbol.
Referenced by CRootContainer::initializeChildren().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CUnitDefinition & o) friend
Member Data Documentation
mReadOnly
bool CUnitDefinition::mReadOnly private
Referenced by isReadOnly(), and updateSIUnitDefinitions().
mSymbol
std::string CUnitDefinition::mSymbol private
Referenced by applyData(), createUndoData(), getSymbol(), operator=(), setSymbol(), setup(), and toData().
The documentation for this class was generated from the following files:
CUnitDefinition.h
CUnitDefinition.cpp