COPASI API: SBMLUtils Class Reference
SBMLUtils Class Reference
#include <SBMLUtils.h>
Static Public Member Functions
static void collectIds (Model *pModel, std::map< std::string, const SBase * > &ids, std::map< std::string, const SBase * > &metaIds)
static std::string getIdFromSBase (const SBase *s)
Static Protected Member Functions
template<class CType >
static std::string getId (const CType *pA, C_INT32 level=2)
Member Function Documentation
collectIds()
void SBMLUtils::collectIds (Model * pModel, std::map< std::string, const SBase * > & ids, std::map< std::string, const SBase * > & metaIds) static
This method goes through the given SBML model and collects all ids and meta ids used in the model.
References CCopasiMessage::EXCEPTION, MCSBML, and CCopasiMessage::WARNING.
Referenced by CCellDesignerImporter::convertCellDesignerLayout(), CSBMLExporter::createSBMLDocument(), and SBMLImporter::preprocessNode().
getId()
template<class CType > std::string SBMLUtils::getId (const CType * pA, C_INT32 level = 2) static protected
Referenced by getIdFromSBase().
getIdFromSBase()
std::string SBMLUtils::getIdFromSBase (const SBase * s) static
Return the sbml ID if the sbml object actually has one. If not, it returns "". It only handles core sbml objects. No layout objects yet.
References getId().
Referenced by SBMLDocumentLoader::readListOfLayouts().
The documentation for this class was generated from the following files:
SBMLUtils.h
SBMLUtils.cpp