COPASI API: CLLineSegment Class Reference
CLLineSegment Class Reference
#include <CLCurve.h>
Public Member Functions
CLLineSegment ()
CLLineSegment (const CLPoint &s, const CLPoint &e)
CLLineSegment (const CLPoint &s, const CLPoint &e, const CLPoint &b1, const CLPoint &b2)
CLLineSegment (const LineSegment &ls)
void exportToSBMLBezier (CubicBezier *c, const std::map< const CDataObject *, SBase * > &copasimodelmap) const
void exportToSBMLLineSegment (LineSegment *l, const std::map< const CDataObject *, SBase * > &copasimodelmap) const
CLPoint & getBase1 ()
const CLPoint & getBase1 () const
CLPoint & getBase2 ()
const CLPoint & getBase2 () const
CLPoint & getEnd ()
const CLPoint & getEnd () const
CLPoint & getStart ()
const CLPoint & getStart () const
bool isBezier () const
bool operator< (const CLLineSegment &rhs) const
bool operator== (const CLLineSegment &rhs) const
void scale (const double &scaleFactor)
void setBase1 (const CLPoint &p)
void setBase2 (const CLPoint &p)
void setEnd (const CLPoint &p)
void setIsBezier (bool b)
void setStart (const CLPoint &p)
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
CLPoint mBase1
CLPoint mBase2
CLPoint mEnd
bool mIsBezier
CLPoint mStart
Protected Attributes inherited from CLBase
std::string mTag
Friends
std::ostream & operator<< (std::ostream &os, const CLLineSegment &ls)
Detailed Description
This class describes a line segment.
Constructor & Destructor Documentation
CLLineSegment() [1/4]
CLLineSegment::CLLineSegment () inline
CLLineSegment() [2/4]
CLLineSegment::CLLineSegment (const CLPoint & s, const CLPoint & e) inline
Constructor for a straight line segment
CLLineSegment() [3/4]
CLLineSegment::CLLineSegment (const CLPoint & s, const CLPoint & e, const CLPoint & b1, const CLPoint & b2) inline
Constructor for a bezier segment
CLLineSegment() [4/4]
CLLineSegment::CLLineSegment (const LineSegment & ls)
constructor from libsbml object
References mBase1, mBase2, and mIsBezier.
Member Function Documentation
exportToSBMLBezier()
void CLLineSegment::exportToSBMLBezier (CubicBezier * c, const std::map< const CDataObject *, SBase * > & copasimodelmap) const
This method writes the information of the copasi layout object into the corresponding sbml object. This is only guaranteed to work if isBezier() is true.
References exportToSBMLLineSegment(), getBase1(), and getBase2().
exportToSBMLLineSegment()
void CLLineSegment::exportToSBMLLineSegment (LineSegment * l, const std::map< const CDataObject *, SBase * > & copasimodelmap) const
This method writes the information of the copasi layout object into the corresponding sbml object. This is only guaranteed to work if isBezier() is false.
References getEnd(), and getStart().
Referenced by exportToSBMLBezier().
getBase1() [1/2]
CLPoint& CLLineSegment::getBase1 () inline
References mBase1.
getBase1() [2/2]
const CLPoint& CLLineSegment::getBase1 () const inline
References mBase1.
Referenced by CLCurve::calculateBoundingBox(), CLLayoutRenderer::draw_curve(), exportToSBMLBezier(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::move_curve_object(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), and CCopasiXML::saveCurve().
getBase2() [1/2]
CLPoint& CLLineSegment::getBase2 () inline
References mBase2.
getBase2() [2/2]
const CLPoint& CLLineSegment::getBase2 () const inline
References mBase2.
Referenced by CLCurve::calculateBoundingBox(), CLLayoutRenderer::draw_curve(), exportToSBMLBezier(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::move_curve_object(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), and CCopasiXML::saveCurve().
getEnd() [1/2]
CLPoint& CLLineSegment::getEnd () inline
References mEnd.
getEnd() [2/2]
const CLPoint& CLLineSegment::getEnd () const inline
References mEnd.
Referenced by CLCurve::calculateBoundingBox(), CLLayoutRenderer::draw_curve(), exportToSBMLLineSegment(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), and CCopasiXML::saveCurve().
getStart() [1/2]
CLPoint& CLLineSegment::getStart () inline
References mStart.
getStart() [2/2]
const CLPoint& CLLineSegment::getStart () const inline
References mStart.
Referenced by CLCurve::calculateBoundingBox(), CLLayoutRenderer::draw_curve(), exportToSBMLLineSegment(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), CCopasiXML::saveCurve(), and CLLayoutRenderer::update_associations().
isBezier()
bool CLLineSegment::isBezier () const inline
References mIsBezier.
Referenced by CLCurve::calculateBoundingBox(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::move_curve_object(), CLCurve::moveBy(), ListOfCurveSegmentsHandler::processStart(), CLLayoutRenderer::revert_curve(), and CCopasiXML::saveCurve().
operator<()
bool CLLineSegment::operator< (const CLLineSegment & rhs) const inline
References mStart.
operator==()
bool CLLineSegment::operator== (const CLLineSegment & rhs) const inline
References mBase1, mBase2, mEnd, mIsBezier, and mStart.
scale()
void CLLineSegment::scale (const double & scaleFactor) inline
References mBase1, mBase2, mEnd, mIsBezier, mStart, and CLPoint::scale().
setBase1()
void CLLineSegment::setBase1 (const CLPoint & p) inline
References mBase1.
Referenced by CubicBezierHandler::processEnd(), and CLLayoutRenderer::revert_curve().
setBase2()
void CLLineSegment::setBase2 (const CLPoint & p) inline
References mBase2.
Referenced by CubicBezierHandler::processEnd(), and CLLayoutRenderer::revert_curve().
setEnd()
void CLLineSegment::setEnd (const CLPoint & p) inline
References mEnd.
Referenced by CLLayoutRenderer::is_curve_segment_visible(), CubicBezierHandler::processEnd(), and LineSegmentHandler::processEnd().
setIsBezier()
void CLLineSegment::setIsBezier (bool b) inline
References mIsBezier.
Referenced by CLLayoutRenderer::is_curve_segment_visible(), ListOfCurveSegmentsHandler::processStart(), and CLLayoutRenderer::revert_curve().
setStart()
void CLLineSegment::setStart (const CLPoint & p) inline
References mStart.
Referenced by CLLayoutRenderer::is_curve_segment_visible(), CubicBezierHandler::processEnd(), and LineSegmentHandler::processEnd().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CLLineSegment & ls) friend
insert operator
Member Data Documentation
mBase1
CLPoint CLLineSegment::mBase1 protected
Referenced by CLLineSegment(), getBase1(), operator==(), scale(), and setBase1().
mBase2
CLPoint CLLineSegment::mBase2 protected
Referenced by CLLineSegment(), getBase2(), operator==(), scale(), and setBase2().
mEnd
CLPoint CLLineSegment::mEnd protected
Referenced by getEnd(), operator==(), scale(), and setEnd().
mIsBezier
bool CLLineSegment::mIsBezier protected
Referenced by CLLineSegment(), isBezier(), operator==(), scale(), and setIsBezier().
mStart
CLPoint CLLineSegment::mStart protected
Referenced by getStart(), operator<(), operator==(), scale(), and setStart().
The documentation for this class was generated from the following files:
CLCurve.h
CLCurve.cpp