COPASI API: CEventAssignment Class Reference
CEventAssignment Class Reference
#include <CEvent.h>
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CEventAssignment (const CEventAssignment &src, const CDataContainer *pParent)
CEventAssignment (const std::string &targetCN="", const CDataContainer *pParent=NO_PARENT)
CIssue compile (CObjectInterface::ContainerList listOfContainer)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
std::string getExpression () const
CExpression * getExpressionPtr ()
const CExpression * getExpressionPtr () const
const std::string & getKey () const
const std::string & getTargetCN () const
const CDataObject * getTargetObject () const
bool operator!= (const CEventAssignment &rhs) const
bool setExpression (const std::string &expression)
bool setExpressionPtr (CExpression *pExpression)
virtual bool setObjectParent (const CDataContainer *pParent)
bool setTargetCN (const std::string &targetCN)
virtual CData toData () const
~CEventAssignment ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CEventAssignment * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Private Attributes
std::string mKey
CExpression * mpExpression
CModel * mpModel
const CDataObject * mpTarget
CRegisteredCommonName mTargetCN
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CEventAssignment() [1/2]
CEventAssignment::CEventAssignment (const std::string & targetCN = "", const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & targetCN (default: "")
"const CDataContainer * pParent (default: NULL)
Even though this constuctor usually expects the CN of a target, it will also work with a key
References CKeyFactory::get(), CDataObject::getCN(), CRootContainer::getKeyFactory(), CModelEntity::getValueObject(), mpModel, mTargetCN, CModel::setCompileFlag(), and CDataObject::setObjectName().
Referenced by fromData().
CEventAssignment() [2/2]
CEventAssignment::CEventAssignment (const CEventAssignment & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CEventAssignment & src
"const CDataContainer * pParent (default: NULL)
References getExpression(), mpModel, CModel::setCompileFlag(), and setExpression().
~CEventAssignment()
CEventAssignment::~CEventAssignment ()
Destructor
References mpExpression, mpModel, pdelete, and CModel::setCompileFlag().
Member Function Documentation
applyData()
bool CEventAssignment::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CDataContainer::applyData(), CData::EXPRESSION, CDataObject::getObjectAncestor(), CData::getProperty(), CData::isSetProperty(), CData::OBJECT_REFERENCE_CN, CModel::setCompileFlag(), setExpression(), setTargetCN(), and CDataValue::toString().
compile()
CIssue CEventAssignment::compile (CObjectInterface::ContainerList listOfContainer)
Compile the event assignment.
Parameters
CObjectInterface::ContainerList listOfContainer
Returns
CIssue issue
References CValidity::add(), CModelEntity::ASSIGNMENT, CIssue::CExpressionNotFound, CValidity::clear(), CExpression::compile(), CObjectInterface::DataObject(), CCopasiMessage::ERROR, CIssue::Error, CIssue::EventAlreadyHasAssignment, CDataObject::getCN(), CValidity::getFirstWorstIssue(), CDataContainer::getObject(), CDataObject::getObjectDataModel(), CDataObject::getObjectName(), CDataObject::getObjectParent(), CDataObject::getPrerequisites(), CModelEntity::getStatus(), getTargetCN(), CModelEntity::getValueObject(), mpExpression, CDataObject::mPrerequisits, mpTarget, CObjectInterface::mValidity, CIssue::ObjectNotFound, setTargetCN(), CCopasiMessage::WARNING, and CIssue::Warning.
createUndoData()
void CEventAssignment::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CUndoData::addProperty(), CUndoData::CHANGE, CDataContainer::createUndoData(), CData::EXPRESSION, getExpression(), CData::getProperty(), getTargetCN(), and CData::OBJECT_REFERENCE_CN.
fromData()
CEventAssignment * CEventAssignment::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CEventAssignment * pDataObject
References CEventAssignment(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getExpression()
std::string CEventAssignment::getExpression () const
Retrieve the expression as a string.
Returns
std::string expression
References CEvaluationTree::getInfix(), mpExpression, and CExpression::updateInfix().
Referenced by CEventAssignment(), CMathEvent::CAssignment::compile(), createUndoData(), CModelExpansion::duplicateEvent(), operator!=(), and toData().
getExpressionPtr() [1/2]
CExpression * CEventAssignment::getExpressionPtr ()
Retrieve the pointer to the expression.
Returns
CExpression * pExpression
References mpExpression, and CExpression::updateInfix().
getExpressionPtr() [2/2]
const CExpression * CEventAssignment::getExpressionPtr () const
Retrieve the pointer to the expression.
Returns
CExpression * pExpression
References mpExpression, and CExpression::updateInfix().
Referenced by CModelAdd::addEvents(), CMathEvent::CAssignment::compile(), CModelAdd::copyEventAssignmentExpression(), CModel::createEventsForTimeseries(), CModelExpansion::duplicateEvent(), CEvent::getOriginFor(), CModelMerging::mergeMetabolites(), SBMLImporter::removeUnusedFunctions(), and CModelExpansion::replaceInEvent().
getKey()
const std::string & CEventAssignment::getKey () const virtual
Retrieve the key
Returns
const std::string & key
Reimplemented from CDataObject.
References mKey.
getTargetCN()
const std::string & CEventAssignment::getTargetCN () const
Retrieve the target CN
Returns
const std::string & targetCN
References mTargetCN.
Referenced by compile(), createUndoData(), CModelExpansion::duplicateEvent(), operator!=(), setTargetCN(), and toData().
getTargetObject()
const CDataObject * CEventAssignment::getTargetObject () const
Retrieve a pointer to the target object.
Returns
const CDataObject * targetObject
References mpTarget.
Referenced by CMathEvent::CAssignment::compile(), CEvent::getOriginFor(), and CModelExpansion::replaceInEvent().
operator!=()
bool CEventAssignment::operator!= (const CEventAssignment & rhs) const
Comparison operator
Parameters
const CEventAssignment & rhs
Returns
bool notEqual
References getExpression(), and getTargetCN().
setExpression()
bool CEventAssignment::setExpression (const std::string & expression)
Set the expression from an infix string. The return value indicates if parsing the expression was successful.
Parameters
const std::string & expression
Returns
bool success
References CEvaluationTree::getInfix(), mpExpression, mpModel, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by applyData(), CEventAssignment(), CModelAdd::copyEventAssignmentExpression(), CModel::createEventsForTimeseries(), CModelExpansion::duplicateEvent(), and AssignmentHandler::processEnd().
setExpressionPtr()
bool CEventAssignment::setExpressionPtr (CExpression * pExpression)
Set the expression from an expression pointer. CEventAssignment takes ownership.
Parameters
CExpression* pExpression
Returns
bool success
References CDataContainer::add(), CExpression::compile(), mpExpression, mpModel, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
Referenced by SBMLImporter::importEvent().
setObjectParent()
bool CEventAssignment::setObjectParent (const CDataContainer * pParent) virtual
Set the object parent
Parameters
const CDataContainer * pParent
Returns
bool success
Reimplemented from CDataObject.
References CDataObject::getObjectAncestor(), CDataObject::getObjectParent(), mpModel, CModel::setCompileFlag(), and CDataObject::setObjectParent().
setTargetCN()
bool CEventAssignment::setTargetCN (const std::string & targetCN)
Set the CN of the target
Parameters
const std::string & targetCN
Returns
bool success;
References getTargetCN(), mpModel, mTargetCN, CModel::setCompileFlag(), and CDataObject::setObjectName().
Referenced by applyData(), compile(), and CModelExpansion::replaceInEvent().
toData()
CData CEventAssignment::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::addProperty(), CData::EXPRESSION, getExpression(), getTargetCN(), CData::OBJECT_REFERENCE_CN, and CDataContainer::toData().
Member Data Documentation
mKey
std::string CEventAssignment::mKey private
The key
Referenced by getKey().
mpExpression
CExpression* CEventAssignment::mpExpression private
The expression to calculate the new value
Referenced by compile(), getExpression(), getExpressionPtr(), setExpression(), setExpressionPtr(), and ~CEventAssignment().
mpModel
CModel* CEventAssignment::mpModel private
The parent model
Referenced by CEventAssignment(), setExpression(), setExpressionPtr(), setObjectParent(), setTargetCN(), and ~CEventAssignment().
mpTarget
const CDataObject* CEventAssignment::mpTarget private
The target object
Referenced by compile(), and getTargetObject().
mTargetCN
CRegisteredCommonName CEventAssignment::mTargetCN private
target object CN
Referenced by CEventAssignment(), getTargetCN(), and setTargetCN().
The documentation for this class was generated from the following files:
CEvent.h
CEvent.cpp