COPASI API: CUnit.cpp File Reference
CUnit.cpp File Reference
#include <math.h>
#include <string.h>
#include <algorithm>
#include "copasi/copasi.h"
#include "copasi/core/CRootContainer.h"
#include "copasi/utilities/CUnitDefinition.h"
#include "copasi/utilities/CUnit.h"
#include "copasi/utilities/CUnitParser.h"
#include "copasi/model/CModel.h"
#include "copasi/xml/CCopasiXMLInterface.h"
#include "copasi/utilities/CUnitDefinitionDB.h"
#include "CCopasiException.h"
Functions
std::ostream & operator<< (std::ostream &os, const CUnit &o)
std::list< std::pair< std::string, CUnit > > sortSymbols (const std::set< std::string > symbols)
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & os, const CUnit & o)
sortSymbols()
std::list< std::pair< std::string, CUnit > > sortSymbols (const std::set< std::string > symbols)
References CUnit::getUsedSymbols(), and CUnit::isUndefined().
Referenced by CUnit::getSymbolComponents().