COPASI API: CFlags.h File Reference
CFlags.h File Reference
#include <bitset>
#include <vector>
#include "copasi/core/CEnumAnnotation.h"
Classes
class CFlags< Enum >
Functions
template<class Enum >
CFlags< Enum > operator& (const CFlags< Enum > &lhs, const CFlags< Enum > &rhs)
template<class Enum >
CFlags< Enum > operator& (const CFlags< Enum > &lhs, const Enum &rhs)
template<class Enum >
CFlags< Enum > operator^ (const CFlags< Enum > &lhs, const CFlags< Enum > &rhs)
template<class Enum >
CFlags< Enum > operator^ (const CFlags< Enum > &lhs, const Enum &rhs)
template<class Enum >
CFlags< Enum > operator| (const CFlags< Enum > &lhs, const CFlags< Enum > &rhs)
template<class Enum >
CFlags< Enum > operator| (const CFlags< Enum > &lhs, const Enum &rhs)
Function Documentation
operator&() [1/2]
template<class Enum > CFlags< Enum > operator& (const CFlags< Enum > & lhs, const CFlags< Enum > & rhs)
Bitwise AND operator
Parameters
const CFlags< Enum > & lhs
const CFlags< Enum > & rhs
Returns
CFlags< Enum > result
Referenced by operator&().
operator&() [2/2]
template<class Enum > CFlags< Enum > operator& (const CFlags< Enum > & lhs, const Enum & rhs)
Bitwise AND operator
Parameters
const CFlags< Enum > & lhs
const Enum & rhs
Returns
CFlags< Enum > result
References operator&().
operator^() [1/2]
template<class Enum > CFlags< Enum > operator^ (const CFlags< Enum > & lhs, const CFlags< Enum > & rhs)
Bitwise XOR operator
Parameters
const CFlags< Enum > & lhs
const CFlags< Enum > & rhs
Returns
CFlags< Enum > result
Referenced by operator^().
operator^() [2/2]
template<class Enum > CFlags< Enum > operator^ (const CFlags< Enum > & lhs, const Enum & rhs)
Bitwise XOR operator
Parameters
const CFlags< Enum > & lhs
const Enum & rhs
Returns
CFlags< Enum > result
References operator^().
operator|() [1/2]
template<class Enum > CFlags< Enum > operator| (const CFlags< Enum > & lhs, const CFlags< Enum > & rhs)
Bitwise OR operator
Parameters
const CFlags< Enum > & lhs
const CFlags< Enum > & rhs
Returns
CFlags< Enum > result
Referenced by operator|().
operator|() [2/2]
template<class Enum > CFlags< Enum > operator| (const CFlags< Enum > & lhs, const Enum & rhs)
Bitwise OR operator
Parameters
const CFlags< Enum > & lhs
const Enum & rhs
Returns
CFlags< Enum > result
References operator|().