COPASI API: CDataObjectMap::type_iterator< CType > Class Template Reference
CDataObjectMap::type_iterator< CType > Class Template Reference
#include <CDataObjectMap.h>
Public Member Functions
bool operator!= (const type_iterator &rhs) const
CType * operator* () const
type_iterator< CType > & operator++ ()
type_iterator operator++ (int)
CType * operator-> () const
type_iterator ()
type_iterator (const CDataObjectMap::iterator &src)
type_iterator (const type_iterator< CType > &src)
Additional Inherited Members
Protected Member Functions inherited from CDataObjectMap::iterator
iterator ()
iterator (const CDataObjectMap &map, const bool &begin)
iterator (const iterator &src)
bool operator!= (const iterator &rhs) const
CDataObject * operator* () const
iterator & operator++ ()
iterator operator++ (int)
CDataObject * operator-> () const
~iterator ()
Protected Attributes inherited from CDataObjectMap::iterator
std::map< std::string, std::set< CDataObject * > >::iterator mName
bool mNameEnd
std::set< CDataObject * >::iterator mObject
bool mObjectEnd
const std::map< std::string, std::set< CDataObject * > > * mpMap
Constructor & Destructor Documentation
type_iterator() [1/3]
template<class CType > CDataObjectMap::type_iterator< CType >::type_iterator () inline
type_iterator() [2/3]
template<class CType > CDataObjectMap::type_iterator< CType >::type_iterator (const type_iterator< CType > & src) inline
type_iterator() [3/3]
template<class CType > CDataObjectMap::type_iterator< CType >::type_iterator (const CDataObjectMap::iterator & src) inline
References CDataObjectMap::type_iterator< CType >::operator++().
Member Function Documentation
operator!=()
template<class CType > bool CDataObjectMap::type_iterator< CType >::operator!= (const type_iterator< CType > & rhs) const inline
References CDataObjectMap::iterator::operator!=().
operator*()
template<class CType > CType* CDataObjectMap::type_iterator< CType >::operator* () const inline
References CDataObjectMap::iterator::operator*().
operator++() [1/2]
template<class CType > type_iterator< CType >& CDataObjectMap::type_iterator< CType >::operator++ () inline
References CDataObjectMap::iterator::mNameEnd, CDataObjectMap::iterator::mObjectEnd, and CDataObjectMap::iterator::operator++().
Referenced by CDataObjectMap::type_iterator< CType >::operator++(), and CDataObjectMap::type_iterator< CType >::type_iterator().
operator++() [2/2]
template<class CType > type_iterator CDataObjectMap::type_iterator< CType >::operator++ (int) inline
References CDataObjectMap::type_iterator< CType >::operator++().
operator->()
template<class CType > CType* CDataObjectMap::type_iterator< CType >::operator-> () const inline
References CDataObjectMap::iterator::operator->().
The documentation for this class was generated from the following file:
CDataObjectMap.h