COPASI API: COutputHandler Class Reference
COutputHandler Class Reference
#include <COutputHandler.h>
Public Member Functions
virtual void addInterface (COutputInterface *pInterface)
virtual bool compile (CObjectInterface::ContainerList listOfContainer)
COutputHandler ()
COutputHandler (const COutputHandler &src)
virtual void finish ()
std::set< COutputInterface * > getInterfaces () const
bool isMaster () const
virtual void output (const Activity &activity)
virtual void removeInterface (COutputInterface *pInterface)
virtual void separate (const Activity &activity)
void setMaster (COutputHandler *pMaster)
virtual ~COutputHandler ()
Public Member Functions inherited from COutputInterface
virtual void close ()
COutputInterface ()
COutputInterface (const COutputInterface &src)
virtual const CObjectInterface::ObjectSet & getObjects () const
virtual ~COutputInterface ()
Protected Member Functions
void applyUpdateSequence ()
bool compileUpdateSequence (const CObjectInterface::ContainerList &listOfContainer)
Protected Attributes
std::set< COutputInterface * > mInterfaces
const CMathContainer * mpContainer
COutputHandler * mpMaster
CCore::CUpdateSequence mUpdateSequence
Protected Attributes inherited from COutputInterface
CObjectInterface::ObjectSet mObjects
Additional Inherited Members
Public Types inherited from COutputInterface
enum Activity { BEFORE = 0x01 , DURING = 0x02 , AFTER = 0x04 , MONITORING = 0x08 }
Detailed Description
This is the lass which drives all output of COPASI.
Constructor & Destructor Documentation
COutputHandler() [1/2]
COutputHandler::COutputHandler ()
Default Constructor
COutputHandler() [2/2]
COutputHandler::COutputHandler (const COutputHandler & src)
Copy constructor
Parameters
const COutputInterface & src
~COutputHandler()
COutputHandler::~COutputHandler () virtual
Destructor
Member Function Documentation
addInterface()
void COutputHandler::addInterface (COutputInterface * pInterface) virtual
Add an interface
Parameters
COutputInterface * pInterface;
References mInterfaces, and setMaster().
Referenced by CScanTask::initialize(), CTimeSensTask::initialize(), CTrajectoryTask::initialize(), CTSSATask::initialize(), and CCopasiTask::initialize().
applyUpdateSequence()
void COutputHandler::applyUpdateSequence () protected
Refresh all objects
References mpContainer, and mUpdateSequence.
Referenced by output().
compile()
bool COutputHandler::compile (CObjectInterface::ContainerList listOfContainer) virtual
compile the object list from name vector
Parameters
CObjectInterface::ContainerList listOfContainer
const CDataModel* pDataModel
Returns
bool success
Implements COutputInterface.
Reimplemented in CDataHandler.
References compileUpdateSequence(), mInterfaces, COutputInterface::mObjects, mpContainer, mpMaster, and setMaster().
Referenced by CCopasiTask::initialize(), and CMoietiesTask::process().
compileUpdateSequence()
bool COutputHandler::compileUpdateSequence (const CObjectInterface::ContainerList & listOfContainer) protected
Compile the object refresh list
Parameters
const CObjectInterface::ContainerList & listOfContainer
Returns
bool success
References CCore::Default, CMathContainer::getSimulationUpToDateObjects(), CMathContainer::getStateObjects(), CMathContainer::getTransientDependencies(), CMathDependencyGraph::getUpdateSequence(), COutputInterface::mObjects, mpContainer, and mUpdateSequence.
Referenced by compile().
finish()
void COutputHandler::finish () virtual
Finish the output
Implements COutputInterface.
Reimplemented in CDataHandler.
References mInterfaces, and removeInterface().
getInterfaces()
std::set< COutputInterface * > COutputHandler::getInterfaces () const
References mInterfaces.
isMaster()
bool COutputHandler::isMaster () const
Check whether the handler is a master
Returns
bool isMaster
References mpMaster.
output()
void COutputHandler::output (const Activity & activity) virtual
Perform an output event for the current activity
Parameters
const Activity & activity
Implements COutputInterface.
Reimplemented in CDataHandler.
References applyUpdateSequence(), mInterfaces, and mpMaster.
Referenced by CCopasiTask::output().
removeInterface()
void COutputHandler::removeInterface (COutputInterface * pInterface) virtual
Remove an interface
Parameters
COutputInterface * pInterface;
References mInterfaces, and setMaster().
Referenced by finish().
separate()
void COutputHandler::separate (const Activity & activity) virtual
Introduce an additional separator into the output
Parameters
const Activity & activity
Implements COutputInterface.
Reimplemented in CDataHandler.
References mInterfaces.
Referenced by CCopasiTask::separate().
setMaster()
void COutputHandler::setMaster (COutputHandler * pMaster)
Set whether the handler is the master handler
Parameters
COutputHandler * pMaster
References mpMaster.
Referenced by addInterface(), compile(), and removeInterface().
Member Data Documentation
mInterfaces
std::set< COutputInterface * > COutputHandler::mInterfaces protected
A list of all active output interfaces.
Referenced by addInterface(), compile(), finish(), getInterfaces(), output(), removeInterface(), and separate().
mpContainer
const CMathContainer* COutputHandler::mpContainer protected
A pointer to the math container
Referenced by applyUpdateSequence(), compile(), and compileUpdateSequence().
mpMaster
COutputHandler* COutputHandler::mpMaster protected
Points to the master handler. The master handler is responsible for the and object updates and all the output.
Referenced by compile(), isMaster(), output(), and setMaster().
mUpdateSequence
CCore::CUpdateSequence COutputHandler::mUpdateSequence protected
An ordered list of refresh methods needed by the master
Referenced by applyUpdateSequence(), and compileUpdateSequence().
The documentation for this class was generated from the following files:
COutputHandler.h
COutputHandler.cpp