COPASI API: CTableauLine Class Reference
CTableauLine Class Reference
#include <CTableauLine.h>
Public Member Functions
CTableauLine ()
CTableauLine (C_FLOAT64 m1, const CTableauLine &src1, C_FLOAT64 m2, const CTableauLine &src2)
CTableauLine (const std::vector< C_FLOAT64 > &reaction, bool reversible, const size_t &reactionCounter, const size_t &reactionNumber)
const std::vector< C_FLOAT64 > & getFluxMode () const
const C_FLOAT64 & getMultiplier (const size_t &index) const
const CFluxScore & getScore () const
bool isReversible () const
~CTableauLine ()
Static Private Member Functions
static void reduce (C_FLOAT64 &r1, C_FLOAT64 &r2)
Private Attributes
std::vector< C_FLOAT64 > mFluxMode
CFluxScore * mpFluxScore
std::vector< C_FLOAT64 > mReaction
bool mReversible
Friends
std::ostream & operator<< (std::ostream &, const CTableauLine &)
Detailed Description
CTableauLine class. This store one row of the Tableau Matrix
Created for COPASI by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Constructor & Destructor Documentation
CTableauLine() [1/3]
CTableauLine::CTableauLine ()
Default constructor
CTableauLine class. This store one row of the Tableau Matrix
Created for COPASI by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
References CONSTRUCTOR_TRACE, and mpFluxScore.
CTableauLine() [2/3]
CTableauLine::CTableauLine (const std::vector< C_FLOAT64 > & reaction, bool reversible, const size_t & reactionCounter, const size_t & reactionNumber)
Specific constructor
References CONSTRUCTOR_TRACE, mFluxMode, mpFluxScore, mReaction, and mReversible.
CTableauLine() [3/3]
CTableauLine::CTableauLine (C_FLOAT64 m1, const CTableauLine & src1, C_FLOAT64 m2, const CTableauLine & src2)
Specific constructor
References CONSTRUCTOR_TRACE, mFluxMode, mpFluxScore, mReaction, mReversible, and reduce().
~CTableauLine()
CTableauLine::~CTableauLine ()
Destructor
References DESTRUCTOR_TRACE, mpFluxScore, and pdelete.
Member Function Documentation
getFluxMode()
const std::vector< C_FLOAT64 > & CTableauLine::getFluxMode () const
Retrieves the flux mode
References mFluxMode.
Referenced by CFluxMode::CFluxMode().
getMultiplier()
const C_FLOAT64 & CTableauLine::getMultiplier (const size_t & index) const
Retrieve the multiplier for this reaction for the indexed species
Parameters
const size_t & index
Returns
const C_FLOAT64 & multiplier
References mReaction.
getScore()
const CFluxScore & CTableauLine::getScore () const
Retrieves the flux score
References mpFluxScore.
Referenced by CTableauMatrix::isValid().
isReversible()
bool CTableauLine::isReversible () const
Checks whether the reaction is reversible
Returns
"bool" isReversible
References mReversible.
Referenced by CTableauMatrix::addLine(), and CFluxMode::CFluxMode().
reduce()
void CTableauLine::reduce (C_FLOAT64 & r1, C_FLOAT64 & r2) static private
Remove the first entry from the reaction vector Divides m1 and m2 by the largest common factor.
References C_FLOAT64, and C_INT32.
Referenced by CTableauLine().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CTableauLine & l) friend
Member Data Documentation
mFluxMode
std::vector<C_FLOAT64> CTableauLine::mFluxMode private
Referenced by CTableauLine(), and getFluxMode().
mpFluxScore
CFluxScore* CTableauLine::mpFluxScore private
Referenced by CTableauLine(), getScore(), and ~CTableauLine().
mReaction
std::vector<C_FLOAT64> CTableauLine::mReaction private
Referenced by CTableauLine(), and getMultiplier().
mReversible
bool CTableauLine::mReversible private
Referenced by CTableauLine(), and isReversible().
The documentation for this class was generated from the following files:
CTableauLine.h
CTableauLine.cpp