COPASI API: CDataVector< CType >::iterator Class Reference
CDataVector< CType >::iterator Class Reference
#include <CDataVector.h>
Public Member Functions
iterator ()
iterator (const iterator &src)
iterator (const typename std::vector< CType * >::iterator &src)
operator CType * () const
CType & operator* () const
iterator operator+ (const typename std::vector< CType * >::iterator::difference_type &n) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator+= (const typename std::vector< CType * >::iterator::difference_type &n)
iterator operator- (const typename std::vector< CType * >::iterator::difference_type &n) const
iterator & operator-- ()
iterator operator-- (int)
iterator & operator-= (const typename std::vector< CType * >::iterator::difference_type &n)
CType * operator-> () const
iterator & operator= (CType *pType)
~iterator ()
Constructor & Destructor Documentation
iterator() [1/3]
template<class CType > CDataVector< CType >::iterator::iterator () inline
Referenced by CDataVector< CType >::iterator::operator+(), CDataVector< CType >::iterator::operator++(), CDataVector< CType >::iterator::operator-(), and CDataVector< CType >::iterator::operator--().
iterator() [2/3]
template<class CType > CDataVector< CType >::iterator::iterator (const iterator & src) inline
iterator() [3/3]
template<class CType > CDataVector< CType >::iterator::iterator (const typename std::vector< CType * >::iterator & src) inline
~iterator()
template<class CType > CDataVector< CType >::iterator::~iterator () inline
Member Function Documentation
operator CType *()
template<class CType > CDataVector< CType >::iterator::operator CType * () const inline
operator*()
template<class CType > CType& CDataVector< CType >::iterator::operator* () const inline
operator+()
template<class CType > iterator CDataVector< CType >::iterator::operator+ (const typename std::vector< CType * >::iterator::difference_type & n) const inline
References CDataVector< CType >::iterator::iterator().
operator++() [1/2]
template<class CType > iterator& CDataVector< CType >::iterator::operator++ () inline
operator++() [2/2]
template<class CType > iterator CDataVector< CType >::iterator::operator++ (int) inline
References CDataVector< CType >::iterator::iterator().
operator+=()
template<class CType > iterator& CDataVector< CType >::iterator::operator+= (const typename std::vector< CType * >::iterator::difference_type & n) inline
operator-()
template<class CType > iterator CDataVector< CType >::iterator::operator- (const typename std::vector< CType * >::iterator::difference_type & n) const inline
References CDataVector< CType >::iterator::iterator().
operator--() [1/2]
template<class CType > iterator& CDataVector< CType >::iterator::operator-- () inline
operator--() [2/2]
template<class CType > iterator CDataVector< CType >::iterator::operator-- (int) inline
References CDataVector< CType >::iterator::iterator().
operator-=()
template<class CType > iterator& CDataVector< CType >::iterator::operator-= (const typename std::vector< CType * >::iterator::difference_type & n) inline
operator->()
template<class CType > CType* CDataVector< CType >::iterator::operator-> () const inline
operator=()
template<class CType > iterator& CDataVector< CType >::iterator::operator= (CType * pType) inline
The documentation for this class was generated from the following file:
CDataVector.h