COPASI API: FlexLexer Class Reference
FlexLexer Class Reference abstract
#include <FlexLexer.h>
Public Member Functions
int debug () const
int lineno () const
void set_debug (int flag)
virtual void switch_streams (std::istream &new_in, std::ostream &new_out)=0
virtual void switch_streams (std::istream *new_in, std::ostream *new_out)=0
virtual yy_buffer_state * yy_create_buffer (std::istream &s, int size)=0
virtual yy_buffer_state * yy_create_buffer (std::istream *s, int size)=0
virtual void yy_delete_buffer (yy_buffer_state *b)=0
virtual void yy_switch_to_buffer (yy_buffer_state *new_buffer)=0
int YYLeng () const
virtual int yylex ()=0
int yylex (std::istream &new_in, std::ostream &new_out)
int yylex (std::istream *new_in, std::ostream *new_out=0)
virtual void yyrestart (std::istream &s)=0
virtual void yyrestart (std::istream *s)=0
const char * YYText () const
virtual ~FlexLexer ()
Protected Attributes
int yy_flex_debug
int yyleng
int yylineno
char * yytext
Constructor & Destructor Documentation
~FlexLexer()
virtual FlexLexer::~FlexLexer () inline virtual
Member Function Documentation
debug()
int FlexLexer::debug () const inline
References yy_flex_debug.
lineno()
int FlexLexer::lineno () const inline
References yylineno.
set_debug()
void FlexLexer::set_debug (int flag) inline
References yy_flex_debug.
switch_streams() [1/2]
virtual void FlexLexer::switch_streams (std::istream & new_in, std::ostream & new_out) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
switch_streams() [2/2]
virtual void FlexLexer::switch_streams (std::istream * new_in, std::ostream * new_out) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
Referenced by yylex().
yy_create_buffer() [1/2]
virtual yy_buffer_state* FlexLexer::yy_create_buffer (std::istream & s, int size) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
yy_create_buffer() [2/2]
virtual yy_buffer_state* FlexLexer::yy_create_buffer (std::istream * s, int size) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
yy_delete_buffer()
virtual void FlexLexer::yy_delete_buffer (yy_buffer_state * b) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
yy_switch_to_buffer()
virtual void FlexLexer::yy_switch_to_buffer (yy_buffer_state * new_buffer) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
YYLeng()
int FlexLexer::YYLeng () const inline
References yyleng.
yylex() [1/3]
virtual int FlexLexer::yylex () pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
Referenced by yylex().
yylex() [2/3]
int FlexLexer::yylex (std::istream & new_in, std::ostream & new_out) inline
References switch_streams(), and yylex().
yylex() [3/3]
int FlexLexer::yylex (std::istream * new_in, std::ostream * new_out = 0) inline
References switch_streams(), and yylex().
yyrestart() [1/2]
virtual void FlexLexer::yyrestart (std::istream & s) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
yyrestart() [2/2]
virtual void FlexLexer::yyrestart (std::istream * s) pure virtual
Implemented in CUnitParser, CChemEqParser, CEvaluationLexer, and yyFlexLexer.
YYText()
const char* FlexLexer::YYText () const inline
References yytext.
Member Data Documentation
yy_flex_debug
int FlexLexer::yy_flex_debug protected
Referenced by CEvaluationLexer::ctor_common(), debug(), and set_debug().
yyleng
int FlexLexer::yyleng protected
Referenced by YYLeng().
yylineno
int FlexLexer::yylineno protected
Referenced by CEvaluationLexer::ctor_common(), and lineno().
yytext
char* FlexLexer::yytext protected
Referenced by YYText().
The documentation for this class was generated from the following file:
FlexLexer.h