COPASI API: CModelExpansion::ElementsMap Class Reference
CModelExpansion::ElementsMap Class Reference
#include <CModelExpansion.h>
Public Member Functions
void add (const CDataObject *source, const CDataObject *copy)
add a source->duplicate mapping
bool exists (const CDataObject *source) const
does a copy of the source object exist?
bool exists (const std::string &sourceKey) const
CCommonName getDuplicateFromCN (const CCommonName &cn) const
find the key of the duplicated object from the source object (if it exists)
const CDataObject * getDuplicateFromObject (const CDataObject *source) const
find the pointer of the duplicated object from the pointer to the source object (if it exists)
const std::map< const CDataObject *, const CDataObject * > & getMap () const
Protected Attributes
std::map< const CDataObject *, const CDataObject * > mMap
Detailed Description
This class contains a map from original to duplicated sets of model elements
Member Function Documentation
add()
void CModelExpansion::ElementsMap::add (const CDataObject * source, const CDataObject * copy)
add a source->duplicate mapping
Referenced by CModelExpansion::copyCompleteModel(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), and CModelExpansion::duplicateReaction().
exists() [1/2]
bool CModelExpansion::ElementsMap::exists (const CDataObject * source) const
does a copy of the source object exist?
Referenced by CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CModelExpansion::replaceInMetab(), and CModelExpansion::updateExpression().
exists() [2/2]
bool CModelExpansion::ElementsMap::exists (const std::string & sourceKey) const
References CKeyFactory::get(), and CRootContainer::getKeyFactory().
getDuplicateFromCN()
CCommonName CModelExpansion::ElementsMap::getDuplicateFromCN (const CCommonName & cn) const
find the key of the duplicated object from the source object (if it exists)
References CObjectInterface::DataObject(), CDataObject::getCN(), and CRootContainer::getRoot().
getDuplicateFromObject()
const CDataObject * CModelExpansion::ElementsMap::getDuplicateFromObject (const CDataObject * source) const
find the pointer of the duplicated object from the pointer to the source object (if it exists)
Referenced by CModelExpansion::duplicateEvent(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CModelExpansion::replaceInEvent(), CModelExpansion::replaceInExpression(), CModelExpansion::replaceInMetab(), CModelExpansion::replaceInReaction(), CModelExpansion::simpleCall(), and CModelExpansion::updateExpression().
getMap()
const std::map< const CDataObject *, const CDataObject * > & CModelExpansion::ElementsMap::getMap () const
Referenced by CModelExpansion::copyCompleteModel(), and CModelExpansion::replaceInModel().
Member Data Documentation
mMap
std::map<const CDataObject*, const CDataObject*> CModelExpansion::ElementsMap::mMap protected
The documentation for this class was generated from the following files:
CModelExpansion.h
CModelExpansion.cpp