COPASI API: CMathEvent::CTrigger::CRootProcessor Class Reference
CMathEvent::CTrigger::CRootProcessor Class Reference
#include <CMathEvent.h>
Public Member Functions
void applyInitialValues ()
void calculateTrueValue ()
bool compile (CEvaluationNode *pRootNode, const bool &equality, CMathContainer &container)
void copy (const CRootProcessor &src, CMathContainer &container)
CEvaluationNode * createTriggerExpressionNode () const
CRootProcessor ()
CRootProcessor (const CRootProcessor &src)
void initialize (CMath::sPointers &pointers)
const bool & isEquality () const
bool isTrue () const
void relocate (const CMathContainer *pContainer, const std::vector< CMath::sRelocate > &relocations)
void setDataObject (const CDataObject *pDataObject)
void toggle (const C_FLOAT64 &time)
void toggle (const C_FLOAT64 &time, const bool &equality)
~CRootProcessor ()
Public Attributes
bool mDiscrete
bool mEquality
C_FLOAT64 mLastToggleTime
CMathObject * mpRoot
CMathObject * mpRootState
C_FLOAT64 * mpRootStateValue
C_FLOAT64 * mpRootValue
Friends
std::ostream & operator<< (std::ostream &os, const CRootProcessor &o)
Constructor & Destructor Documentation
CRootProcessor() [1/2]
CMathEvent::CTrigger::CRootProcessor::CRootProcessor ()
Default constructor
CRootProcessor() [2/2]
CMathEvent::CTrigger::CRootProcessor::CRootProcessor (const CRootProcessor & src)
Copy constructor
~CRootProcessor()
CMathEvent::CTrigger::CRootProcessor::~CRootProcessor ()
Destructor
Member Function Documentation
applyInitialValues()
void CMathEvent::CTrigger::CRootProcessor::applyInitialValues ()
Initialize all values of the root processor.
calculateTrueValue()
void CMathEvent::CTrigger::CRootProcessor::calculateTrueValue ()
Determine the truth value for the current root.
compile()
bool CMathEvent::CTrigger::CRootProcessor::compile (CEvaluationNode * pRootNode, const bool & equality, CMathContainer & container)
References CCopasiNode< _Data >::addChild(), C_FLOAT64, and CEvaluationNode::GT.
Referenced by CMathEvent::CTrigger::compileLE().
copy()
void CMathEvent::CTrigger::CRootProcessor::copy (const CRootProcessor & src, CMathContainer & container)
Copy an existing object
Parameters
const CRootProcessor & src
CMathContainer & container
Referenced by CMathEvent::CTrigger::copy().
createTriggerExpressionNode()
CEvaluationNode * CMathEvent::CTrigger::CRootProcessor::createTriggerExpressionNode () const
Referenced by CMathEvent::CTrigger::compileLE().
initialize()
void CMathEvent::CTrigger::CRootProcessor::initialize (CMath::sPointers & pointers)
References CMath::Event, CMath::EventRoot, CMath::EventRootState, CMathObject::initialize(), CMath::sPointers::pEventRoots, CMath::sPointers::pEventRootsObject, CMath::sPointers::pEventRootStates, CMath::sPointers::pEventRootStatesObject, and CMath::Undefined.
Referenced by CMathEvent::CTrigger::initialize().
isEquality()
const bool & CMathEvent::CTrigger::CRootProcessor::isEquality () const
Check whether the root needs to be checked for equality;
Returns
const bool & isEquality
isTrue()
bool CMathEvent::CTrigger::CRootProcessor::isTrue () const
Check whether the root state is true
Returns
bool isTrue
relocate()
void CMathEvent::CTrigger::CRootProcessor::relocate (const CMathContainer * pContainer, const std::vector< CMath::sRelocate > & relocations)
The objects and values are relocated
Parameters
const CMathContainer * pContainer
const std::vector< CMath::sRelocate > & relocations
References CMathContainer::relocateObject(), and CMathContainer::relocateValue().
Referenced by CMathEvent::CTrigger::relocate().
setDataObject()
void CMathEvent::CTrigger::CRootProcessor::setDataObject (const CDataObject * pDataObject)
Set the pointer to the data object
Parameters
const CDataObject * pDataObject
Referenced by CMathEvent::CTrigger::compile().
toggle() [1/2]
void CMathEvent::CTrigger::CRootProcessor::toggle (const C_FLOAT64 & time)
Toggle the root status dependent on the processed equality status
Parameters
const C_FLOAT64 & time
toggle() [2/2]
void CMathEvent::CTrigger::CRootProcessor::toggle (const C_FLOAT64 & time, const bool & equality)
Toggle the root status dependent on the processed equality status
Parameters
const C_FLOAT64 & time
const bool & equality
const bool & continuous
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CRootProcessor & o) friend
Member Data Documentation
mDiscrete
bool CMathEvent::CTrigger::CRootProcessor::mDiscrete
mEquality
bool CMathEvent::CTrigger::CRootProcessor::mEquality
mLastToggleTime
C_FLOAT64 CMathEvent::CTrigger::CRootProcessor::mLastToggleTime
mpRoot
CMathObject* CMathEvent::CTrigger::CRootProcessor::mpRoot
Referenced by CMathContainer::analyzeRoots(), and CMathEvent::CTrigger::setExpression().
mpRootState
CMathObject* CMathEvent::CTrigger::CRootProcessor::mpRootState
Referenced by CMathEvent::CTrigger::setExpression().
mpRootStateValue
C_FLOAT64* CMathEvent::CTrigger::CRootProcessor::mpRootStateValue
mpRootValue
C_FLOAT64* CMathEvent::CTrigger::CRootProcessor::mpRootValue
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp