COPASI API: CUnitDefinitionDB Class Reference
CUnitDefinitionDB Class Reference
#include <CUnitDefinitionDB.h>
Public Member Functions
virtual bool add (const CUnitDefinition &src)
virtual bool add (CUnitDefinition *src, bool adopt=false)
bool appendDependentUnits (std::set< const CDataObject * > candidates, std::set< const CDataObject * > &dependentUnits) const
bool changeSymbol (CUnitDefinition *pUnitDef, const std::string &symbol)
bool containsSymbol (std::string symbol) const
CUnitDefinitionDB (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
std::vector< CUnit > getAllValidUnits (const std::string &expression, const C_FLOAT64 &exponent) const
const CUnitDefinition * getUnitDefFromSymbol (std::string symbol) const
std::string quoteSymbol (const std::string &symbol) const
virtual bool remove (CDataObject *pObject)
virtual void remove (const size_t &index)
virtual void remove (const std::string &name)
~CUnitDefinitionDB ()
Public Member Functions inherited from CDataVectorN< CUnitDefinition >
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CDataVectorN (const CDataVectorN< CUnitDefinition > &src, const CDataContainer *pParent)
CDataVectorN (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
void createUniqueName (std::string &name) const
virtual size_t getIndex (const std::string &name) const
virtual const CObjectInterface * getObject (const CCommonName &name) const
CDataVectorN< CUnitDefinition > & operator= (const std::vector< CUnitDefinition * > &rhs)
CUnitDefinition & operator[] (const size_t &index)
const CUnitDefinition & operator[] (const size_t &index) const
CUnitDefinition & operator[] (const std::string &name)
const CUnitDefinition & operator[] (const std::string &name) const
virtual CData toData () const
virtual ~CDataVectorN ()
Public Member Functions inherited from CDataVector< CType >
virtual bool add (const CType &src)
iterator begin ()
const_iterator begin () const
name_iterator beginName ()
const_name_iterator beginName () const
CDataVector (const CDataVector< CType > &src, const CDataContainer *pParent)
CDataVector (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void cleanup ()
virtual void clear ()
void deepCopy (const CDataVector< CType > &source)
virtual bool empty () const
iterator end ()
const_iterator end () const
name_iterator endName ()
const_name_iterator endName () const
virtual size_t getIndex (const CDataObject *pObject) const
virtual CUndoObjectInterface * insert (const CData &data)
bool operator!= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const std::vector< CType * > &rhs)
CType & operator[] (const size_t &index)
const CType & operator[] (const size_t &index) const
virtual void resize (const size_t &newSize)
virtual size_t size () const
virtual void swap (const size_t &indexFrom, const size_t &indexTo)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CDataVector ()
Public Member Functions inherited from CDataContainer
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Private Member Functions
void replaceSymbol (const std::string &oldSymbol, const std::string &newSymbol)
Private Attributes
std::map< std::string, CUnitDefinition * > mSymbolToUnitDefinitions
Additional Inherited Members
Public Types inherited from CDataVectorN< CUnitDefinition >
typedef CDataObjectMap::const_type_iterator< CUnitDefinition > const_name_iterator
typedef CDataObjectMap::type_iterator< CUnitDefinition > name_iterator
Public Types inherited from CDataVector< CType >
typedef CDataObjectMap::const_type_iterator< CType > const_name_iterator
typedef CDataObjectMap::type_iterator< CType > name_iterator
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataVector< CType >
CDataVector (const CDataVector< CType > &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CUnitDefinitionDB()
CUnitDefinitionDB::CUnitDefinitionDB (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT)
~CUnitDefinitionDB()
CUnitDefinitionDB::~CUnitDefinitionDB () inline
Member Function Documentation
add() [1/2]
bool CUnitDefinitionDB::add (const CUnitDefinition & src) virtual
Add a copy of the object to the end of the vector.
Parameters
const CType & src
Returns
bool success.
Reimplemented from CDataVectorN< CUnitDefinition >.
References C_INVALID_INDEX, containsSymbol(), CDataVectorN< CUnitDefinition >::getIndex(), CDataObject::getObjectName(), and CUnitDefinition::getSymbol().
Referenced by CCopasiXML::mergeUnitDefinitions(), and UnitDefinitionHandler::processStart().
add() [2/2]
bool CUnitDefinitionDB::add (CUnitDefinition * src, bool adopt = false) virtual
References CDataVectorN< CType >::add(), C_INVALID_INDEX, containsSymbol(), CDataVectorN< CUnitDefinition >::getIndex(), CDataObject::getObjectName(), CUnitDefinition::getSymbol(), and mSymbolToUnitDefinitions.
appendDependentUnits()
bool CUnitDefinitionDB::appendDependentUnits (std::set< const CDataObject * > candidates, std::set< const CDataObject * > & dependentUnits) const
Appends pointers to units, which are dependent on any of the candidates to the list dependentUnits.
Parameters
std::set< const CDataObject * > candidates
std::set< const CDataObject * > & dependentUnits
Returns
bool unitsAppended
References CDataVector< CType >::begin(), CDataVector< CType >::end(), CUnitDefinition::getSymbol(), and CDataContainer::insert().
changeSymbol()
bool CUnitDefinitionDB::changeSymbol (CUnitDefinition * pUnitDef, const std::string & symbol)
References CDataObject::getObjectParent(), CUnitDefinition::getSymbol(), mSymbolToUnitDefinitions, and replaceSymbol().
Referenced by CUnitDefinition::setSymbol().
containsSymbol()
bool CUnitDefinitionDB::containsSymbol (std::string symbol) const
References mSymbolToUnitDefinitions.
Referenced by add(), CUnit::filterUsedSymbols(), CCopasiXML::mergeUnitDefinitions(), and CUnitDefinition::operator=().
getAllValidUnits()
std::vector< CUnit > CUnitDefinitionDB::getAllValidUnits (const std::string & expression, const C_FLOAT64 & exponent) const
References CUnit::addComponent(), CDataVector< CType >::begin(), CUnit::buildExpression(), C_INT32, CBaseUnit::dimensionless, CDataVector< CType >::end(), CUnit::exponentiate(), getUnitDefFromSymbol(), CBaseUnit::item, CBaseUnit::yocto, and CBaseUnit::yotta.
getUnitDefFromSymbol()
const CUnitDefinition * CUnitDefinitionDB::getUnitDefFromSymbol (std::string symbol) const
References mSymbolToUnitDefinitions, and unQuote().
Referenced by getAllValidUnits(), CRootContainer::getUnitDefFromSymbol(), and quoteSymbol().
quoteSymbol()
std::string CUnitDefinitionDB::quoteSymbol (const std::string & symbol) const
References getUnitDefFromSymbol(), and quote().
Referenced by CRootContainer::quoteUnitDefSymbol().
remove() [1/3]
bool CUnitDefinitionDB::remove (CDataObject * pObject) virtual
Removes the pointer to the object, from the vector
Parameters
CDataObject * pObject
Returns
bool success
Reimplemented from CDataVector< CType >.
References CUnitDefinition::getSymbol(), mSymbolToUnitDefinitions, and CDataVector< CType >::remove().
remove() [2/3]
void CUnitDefinitionDB::remove (const size_t & index) virtual
Removes the index-th element from the vector
Parameters
const size_t & index
Reimplemented from CDataVector< CType >.
Referenced by remove().
remove() [3/3]
void CUnitDefinitionDB::remove (const std::string & name) virtual
Remove the object with the given name from the vector.
Parameters
const std::string & name
Reimplemented from CDataVectorN< CUnitDefinition >.
References remove().
replaceSymbol()
void CUnitDefinitionDB::replaceSymbol (const std::string & oldSymbol, const std::string & newSymbol) private
Replace all old symbols with new symbols in the unit definition DB
Parameters
const std::string & oldSymbol
const std::string & newSymbol
References CDataVector< CType >::begin(), CDataVector< CType >::end(), CDataObject::getObjectParent(), CRootContainer::getRoot(), and CRootContainer::replaceSymbol().
Referenced by changeSymbol().
Member Data Documentation
mSymbolToUnitDefinitions
std::map<std::string, CUnitDefinition *> CUnitDefinitionDB::mSymbolToUnitDefinitions private
Referenced by add(), changeSymbol(), containsSymbol(), getUnitDefFromSymbol(), and remove().
The documentation for this class was generated from the following files:
CUnitDefinitionDB.h
CUnitDefinitionDB.cpp