COPASI API: CSensProblem Class Reference
CSensProblem Class Reference
#include <CSensProblem.h>
Public Types
enum SubTaskType {
Evaluation , SteadyState , TimeSeries , ParameterEstimation ,
Optimization , CrossSection , __SIZE
}
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
void addVariables (const CSensItem &item)
bool changeVariables (size_t index, const CSensItem &item)
bool collapsRequested () const
CSensProblem (const CDataContainer *pParent=NO_PARENT)
CSensProblem (const CSensProblem &src, const CDataContainer *pParent)
CArray & getCollapsedResult ()
const CArray & getCollapsedResult () const
CDataArray * getCollapsedResultAnnotated ()
const CDataArray * getCollapsedResultAnnotated () const
size_t getNumberOfVariables () const
CArray & getResult ()
const CArray & getResult () const
CDataArray * getResultAnnotated ()
const CDataArray * getResultAnnotated () const
CArray & getScaledResult ()
const CArray & getScaledResult () const
CDataArray * getScaledResultAnnotated ()
const CDataArray * getScaledResultAnnotated () const
virtual CCopasiTask * getSubTask () const override
CSensProblem::SubTaskType getSubTaskType () const
CSensItem getTargetFunctions () const
CSensItem getVariables (size_t index) const
virtual void print (std::ostream *ostream) const override
virtual void printResult (std::ostream *ostream) const override
bool removeVariables ()
bool removeVariables (size_t index)
void setSubTaskType (const CSensProblem::SubTaskType &type)
void setTargetFunctions (const CSensItem item)
virtual ~CSensProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CDataContainer *pParent)
virtual void clearCallBack ()
CCopasiProblem * copy () const
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
const CTaskEnum::Task & getType () const
virtual bool initialize ()
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual bool setModel (CModel *model)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual bool elevateChildren ()
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static std::vector< CObjectLists::ListType > getPossibleTargetFunctions (CSensProblem::SubTaskType)
static std::vector< CObjectLists::ListType > getPossibleVariables (CSensProblem::SubTaskType)
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes
static const std::string SubTaskName []
static const CEnumAnnotation< CTaskEnum::Task, SubTaskType > SubTaskTypeToTask
static const char * XMLSubTask []
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Private Member Functions
void initDebugProblem ()
void initializeParameter ()
void initObjects ()
Static Private Member Functions
static void copyParameterGroupToSensItem (const CCopasiParameterGroup *pg, CSensItem *si)
static void copySensItemToParameterGroup (const CSensItem *si, CCopasiParameterGroup *pg)
static void createParametersInGroup (CCopasiParameterGroup *pg)
Private Attributes
CArray mCollapsedResult
CDataArray * mpCollapsedResultAnnotation
CDataArray * mpResultAnnotation
CDataArray * mpScaledResultAnnotation
CSensProblem::SubTaskType * mpSubTaskType
CCopasiParameterGroup * mpTargetFunctions
CCopasiParameterGroup * mpVariablesGroup
CArray mResult
CArray mScaledResult
Friends
std::ostream & operator<< (std::ostream &os, const CSensProblem &o)
Additional Inherited Members
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src)
CCopasiProblem (const CTaskEnum::Task &type, const CDataContainer *pParent)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CCopasiProblem
CMathContainer * mpContainer
CReport * mpReport
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Detailed Description
CSensProblem class.
Member Enumeration Documentation
SubTaskType
enum CSensProblem::SubTaskType
this enumeration
Enumerator
Evaluation
SteadyState
TimeSeries
ParameterEstimation
Optimization
CrossSection
__SIZE
Constructor & Destructor Documentation
CSensProblem() [1/2]
CSensProblem::CSensProblem (const CDataContainer * pParent = NO_PARENT)
Default constructor.
Parameters
const CDataContainer * pParent (default: NULL)
Default constructor.
Parameters
CModel * pModel
References addVariables(), CObjectLists::ALL_PARAMETER_VALUES, CObjectLists::EMPTY_LIST, initializeParameter(), initObjects(), CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CSensItem::setListType(), and setTargetFunctions().
CSensProblem() [2/2]
CSensProblem::CSensProblem (const CSensProblem & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CSensProblem & src @paramconst CDataContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CSensProblem & src
References initializeParameter(), and initObjects().
~CSensProblem()
CSensProblem::~CSensProblem () virtual
Destructor.
References DESTRUCTOR_TRACE.
Member Function Documentation
addVariables()
void CSensProblem::addVariables (const CSensItem & item)
References CCopasiParameterGroup::addGroup(), copySensItemToParameterGroup(), createParametersInGroup(), getNumberOfVariables(), CCopasiParameterGroup::getParameter(), and mpVariablesGroup.
Referenced by changeVariables(), CSensProblem(), and initDebugProblem().
changeVariables()
bool CSensProblem::changeVariables (size_t index, const CSensItem & item)
References addVariables(), copySensItemToParameterGroup(), getNumberOfVariables(), CCopasiParameterGroup::getParameter(), and mpVariablesGroup.
collapsRequested()
bool CSensProblem::collapsRequested () const
References getTargetFunctions(), and CSensItem::isSingleObject().
Referenced by CSensMethod::do_collapsing(), CSensMethod::initialize(), and printResult().
copyParameterGroupToSensItem()
void CSensProblem::copyParameterGroupToSensItem (const CCopasiParameterGroup * pg, CSensItem * si) static private
References CCopasiParameterGroup::getValue(), CSensItem::setListType(), and CSensItem::setSingleObjectCN().
Referenced by getTargetFunctions(), and getVariables().
copySensItemToParameterGroup()
void CSensProblem::copySensItemToParameterGroup (const CSensItem * si, CCopasiParameterGroup * pg) static private
References C_INT32, CSensItem::getListType(), CSensItem::getSingleObjectCN(), CSensItem::isSingleObject(), and CCopasiParameterGroup::setValue().
Referenced by addVariables(), changeVariables(), and setTargetFunctions().
createParametersInGroup()
void CSensProblem::createParametersInGroup (CCopasiParameterGroup * pg) static private
create the copasi parameters corresponding to the members of a CSensItem
References CCopasiParameterGroup::assertParameter(), C_INT32, CCopasiParameter::CN, and CCopasiParameter::UINT.
Referenced by addVariables(), and initializeParameter().
getCollapsedResult() [1/2]
CArray & CSensProblem::getCollapsedResult ()
References mCollapsedResult.
Referenced by CSensMethod::do_collapsing(), and CSensMethod::initialize().
getCollapsedResult() [2/2]
const CArray & CSensProblem::getCollapsedResult () const
References mCollapsedResult.
getCollapsedResultAnnotated() [1/2]
CDataArray * CSensProblem::getCollapsedResultAnnotated ()
References mpCollapsedResultAnnotation.
Referenced by CSensMethod::initialize().
getCollapsedResultAnnotated() [2/2]
const CDataArray * CSensProblem::getCollapsedResultAnnotated () const
References mpCollapsedResultAnnotation.
getNumberOfVariables()
size_t CSensProblem::getNumberOfVariables () const
References mpVariablesGroup, and CCopasiParameterGroup::size().
Referenced by addVariables(), changeVariables(), and CSensMethod::initialize().
getPossibleTargetFunctions()
std::vector< CObjectLists::ListType > CSensProblem::getPossibleTargetFunctions (CSensProblem::SubTaskType type) static
References CObjectLists::ALL_VARIABLES, CrossSection, Evaluation, CObjectLists::GLOBAL_PARAMETER_RATES, CObjectLists::METAB_CONC_RATES, CObjectLists::METAB_PART_RATES, CObjectLists::NON_CONST_GLOBAL_PARAMETER_VALUES, CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CObjectLists::NON_CONST_METAB_NUMBERS, Optimization, ParameterEstimation, CObjectLists::REACTION_CONC_FLUXES, CObjectLists::REACTION_PART_FLUXES, CObjectLists::REDUCED_JACOBIAN_EV_IM, CObjectLists::REDUCED_JACOBIAN_EV_RE, CObjectLists::SINGLE_OBJECT, SteadyState, and TimeSeries.
getPossibleVariables()
std::vector< CObjectLists::ListType > CSensProblem::getPossibleVariables (CSensProblem::SubTaskType type) static
References CObjectLists::ALL_LOCAL_PARAMETER_VALUES, CObjectLists::ALL_PARAMETER_AND_INITIAL_VALUES, CObjectLists::ALL_PARAMETER_VALUES, CrossSection, Evaluation, CObjectLists::GLOBAL_PARAMETER_VALUES, CObjectLists::METAB_CONCENTRATIONS, CObjectLists::METAB_INITIAL_CONCENTRATIONS, CObjectLists::NON_CONST_GLOBAL_PARAMETER_VALUES, CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CObjectLists::NON_CONST_METAB_NUMBERS, Optimization, ParameterEstimation, CObjectLists::SINGLE_OBJECT, SteadyState, and TimeSeries.
getResult() [1/2]
CArray & CSensProblem::getResult ()
References mResult.
Referenced by CSensMethod::do_scaling(), CSensMethod::initialize(), CSensMethod::process(), and CSensMethod::scaling_targetfunction().
getResult() [2/2]
const CArray & CSensProblem::getResult () const
References mResult.
getResultAnnotated() [1/2]
CDataArray * CSensProblem::getResultAnnotated ()
References mpResultAnnotation.
Referenced by CSensMethod::initialize().
getResultAnnotated() [2/2]
const CDataArray * CSensProblem::getResultAnnotated () const
References mpResultAnnotation.
getScaledResult() [1/2]
CArray & CSensProblem::getScaledResult ()
References mScaledResult.
Referenced by CSensMethod::do_collapsing(), CSensMethod::do_collapsing_innerloop(), CSensMethod::initialize(), and CSensMethod::scaling_targetfunction().
getScaledResult() [2/2]
const CArray & CSensProblem::getScaledResult () const
References mScaledResult.
getScaledResultAnnotated() [1/2]
CDataArray * CSensProblem::getScaledResultAnnotated ()
References mpScaledResultAnnotation.
Referenced by CSensMethod::initialize().
getScaledResultAnnotated() [2/2]
const CDataArray * CSensProblem::getScaledResultAnnotated () const
References mpScaledResultAnnotation.
getSubTask()
CCopasiTask * CSensProblem::getSubTask () const override virtual
Retrieve the optional sub task
Returns
CCopasiTask* * pSubTask
Reimplemented from CCopasiProblem.
References CDataVector< CType >::begin(), CDataVector< CType >::end(), CDataObject::getObjectDataModel(), CDataModel::getTaskList(), mpSubTaskType, and SubTaskTypeToTask.
getSubTaskType()
CSensProblem::SubTaskType CSensProblem::getSubTaskType () const
get the problem's SubTaskType:
References Evaluation, and mpSubTaskType.
Referenced by CSensMethod::initialize().
getTargetFunctions()
CSensItem CSensProblem::getTargetFunctions () const
References copyParameterGroupToSensItem(), and mpTargetFunctions.
Referenced by collapsRequested(), and CSensMethod::initialize().
getVariables()
CSensItem CSensProblem::getVariables (size_t index) const
References copyParameterGroupToSensItem(), CCopasiParameterGroup::getParameter(), and mpVariablesGroup.
Referenced by CSensMethod::initialize().
initDebugProblem()
void CSensProblem::initDebugProblem () private
this sets up a problem for debugging purposes
References addVariables(), CCopasiParameter::getCN(), CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CSensItem::setListType(), and CSensItem::setSingleObjectCN().
initializeParameter()
void CSensProblem::initializeParameter () private
Initialize the method parameter
References CCopasiParameterGroup::assertGroup(), CCopasiParameterGroup::assertParameter(), C_INT32, createParametersInGroup(), mpSubTaskType, mpTargetFunctions, mpVariablesGroup, SteadyState, and CCopasiParameter::UINT.
Referenced by CSensProblem().
initObjects()
void CSensProblem::initObjects () private
References mCollapsedResult, mpCollapsedResultAnnotation, mpResultAnnotation, mpScaledResultAnnotation, mResult, mScaledResult, CDataArray::Objects, CDataArray::setDescription(), and CDataArray::setMode().
Referenced by CSensProblem().
print()
void CSensProblem::print (std::ostream * ostream) const override virtual
This is the output method for any object. It calls the insert operator<<
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
printResult()
void CSensProblem::printResult (std::ostream * ostream) const override virtual
This is the output method for any result of a problem. The default implementation provided with CCopasiProblem. Does only print "Not implemented." To overide this default behaviour one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
References collapsRequested(), mpCollapsedResultAnnotation, mpResultAnnotation, and mpScaledResultAnnotation.
removeVariables() [1/2]
bool CSensProblem::removeVariables ()
References CCopasiParameterGroup::clear(), and mpVariablesGroup.
removeVariables() [2/2]
bool CSensProblem::removeVariables (size_t index)
References mpVariablesGroup, and CCopasiParameterGroup::removeParameter().
setSubTaskType()
void CSensProblem::setSubTaskType (const CSensProblem::SubTaskType & type)
set the problem's SubTaskType:
References mpSubTaskType.
setTargetFunctions()
void CSensProblem::setTargetFunctions (const CSensItem item)
References copySensItemToParameterGroup(), and mpTargetFunctions.
Referenced by CSensProblem().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CSensProblem & o) friend
Output stream operator. Prints description of the problem
Parameters
ostream & os
const Problem & A
Returns
ostream & os
Member Data Documentation
mCollapsedResult
CArray CSensProblem::mCollapsedResult private
This holds the collapsed result
Referenced by getCollapsedResult(), and initObjects().
mpCollapsedResultAnnotation
CDataArray* CSensProblem::mpCollapsedResultAnnotation private
Referenced by getCollapsedResultAnnotated(), initObjects(), and printResult().
mpResultAnnotation
CDataArray* CSensProblem::mpResultAnnotation private
Referenced by getResultAnnotated(), initObjects(), and printResult().
mpScaledResultAnnotation
CDataArray* CSensProblem::mpScaledResultAnnotation private
Referenced by getScaledResultAnnotated(), initObjects(), and printResult().
mpSubTaskType
CSensProblem::SubTaskType* CSensProblem::mpSubTaskType private
Referenced by getSubTask(), getSubTaskType(), initializeParameter(), and setSubTaskType().
mpTargetFunctions
CCopasiParameterGroup* CSensProblem::mpTargetFunctions private
Referenced by getTargetFunctions(), initializeParameter(), and setTargetFunctions().
mpVariablesGroup
CCopasiParameterGroup* CSensProblem::mpVariablesGroup private
This holds the variables items
Referenced by addVariables(), changeVariables(), getNumberOfVariables(), getVariables(), initializeParameter(), and removeVariables().
mResult
CArray CSensProblem::mResult private
This holds the result
Referenced by getResult(), and initObjects().
mScaledResult
CArray CSensProblem::mScaledResult private
This holds the scaled result
Referenced by getScaledResult(), and initObjects().
SubTaskName
const std::string CSensProblem::SubTaskName static
Initial value:
=
{
  "Evaluation",
  "Steady State",
  "Time Series",
  "Parameter Estimation",
  "Optimization",
  "Cross Section",
  ""
}
SubTaskTypeToTask
const CEnumAnnotation< CTaskEnum::Task, CSensProblem::SubTaskType > CSensProblem::SubTaskTypeToTask static
Referenced by getSubTask().
XMLSubTask
const char * CSensProblem::XMLSubTask static
Initial value:
=
{
  "Evaluation",
  "SteadyState",
  "TimeSeries",
  "ParameterEstimation",
  "Optimization",
  "CrossSection",
  NULL
}
The documentation for this class was generated from the following files:
CSensProblem.h
CSensProblem.cpp