COPASI API: CDataMatrixReference< CType > Class Template Reference
CDataMatrixReference< CType > Class Template Reference
#include <CDataObjectReference.h>
Public Types
typedef CType referenceType
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
CDataMatrixReference (const CDataMatrixReference< referenceType > &src, const CDataContainer *pParent)
CDataMatrixReference (const std::string &name, const CDataContainer *pParent, referenceType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual CDataObject * getObject (const CCommonName &cn)
virtual const CDataObject * getValueObject () const override
virtual void * getValuePointer () const override
virtual ~CDataMatrixReference ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const override
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Private Member Functions
CDataMatrixReference ()
Private Attributes
CType & mReference
Additional Inherited Members
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Member Typedef Documentation
referenceType
template<class CType > typedef CType CDataMatrixReference< CType >::referenceType
Constructor & Destructor Documentation
CDataMatrixReference() [1/3]
template<class CType > CDataMatrixReference< CType >::CDataMatrixReference () inline private
CDataMatrixReference() [2/3]
template<class CType > CDataMatrixReference< CType >::CDataMatrixReference (const std::string & name, const CDataContainer * pParent, referenceType & reference, const CFlags< Flag > & flag = CFlags< Flag >::None) inline
CDataMatrixReference() [3/3]
template<class CType > CDataMatrixReference< CType >::CDataMatrixReference (const CDataMatrixReference< referenceType > & src, const CDataContainer * pParent) inline
~CDataMatrixReference()
template<class CType > virtual CDataMatrixReference< CType >::~CDataMatrixReference () inline virtual
Member Function Documentation
getObject()
template<class CType > virtual CDataObject* CDataMatrixReference< CType >::getObject (const CCommonName & cn) inline virtual
References CCommonName::getElementIndex(), CDataObject::getObjectName(), CDataObject::getObjectParent(), and CDataMatrixReference< CType >::mReference.
getValueObject()
template<class CType > virtual const CDataObject* CDataMatrixReference< CType >::getValueObject () const inline override virtual
Reimplemented from CDataObject.
getValuePointer()
template<class CType > virtual void* CDataMatrixReference< CType >::getValuePointer () const inline override virtual
Retrieve a pointer to the value of the object
Reimplemented from CDataObject.
References CDataMatrixReference< CType >::mReference.
Member Data Documentation
mReference
template<class CType > CType& CDataMatrixReference< CType >::mReference private
Referenced by CDataMatrixReference< CType >::getObject(), and CDataMatrixReference< CType >::getValuePointer().
The documentation for this class was generated from the following files:
CDataContainer.h
CDataObjectReference.h