COPASI API: CVector< CType > Class Template Reference
CVector< CType > Class Template Reference
#include <CVector.h>
Public Member Functions
CVector (const CVector< CType > &src)
CVector (const CVectorCore< CType > &src)
CVector (size_t size=0)
CVector< CType > & operator= (const CType &value)
CVector< CType > & operator= (const CVector< CType > &rhs)
CVector< CType > & operator= (const CVectorCore< CType > &rhs)
void resize (size_t size, const bool &copy=false)
virtual ~CVector ()
Public Member Functions inherited from CVectorCore< CType >
bool applyPivot (const CVectorCore< size_t > &pivot)
CType * array ()
const CType * array () const
CType * begin ()
const CType * begin () const
CVectorCore (const size_t &size=0, CType *buffer=NULL)
CType * end ()
const CType * end () const
void initialize (const CVectorCore< CType > &src)
void initialize (const size_t &size, const CType *vector)
CType & operator() (const size_t &row)
const CType & operator() (const size_t &row) const
CVectorCore< CType > & operator= (const CType &value)
CVectorCore< CType > & operator= (const CVectorCore< CType > &rhs)
bool operator== (const CVectorCore< CType > &rhs) const
CType & operator[] (const size_t &row)
const CType & operator[] (const size_t &row) const
size_t size () const
virtual ~CVectorCore ()
Protected Member Functions
void copy (const CVectorCore< CType > &rhs)
Additional Inherited Members
Public Types inherited from CVectorCore< CType >
typedef CType elementType
Protected Attributes inherited from CVectorCore< CType >
CType * mpBuffer
size_t mSize
Detailed Description
template<class CType>
class CVector< CType >
Template class CVector < class CType > This template class is a simple vector class allowing standard C-style and fortran style access to the elements. It also supplies an ostream operator.
Constructor & Destructor Documentation
CVector() [1/3]
template<class CType > CVector< CType >::CVector (size_t size = 0) inline
Default constructor
Parameters
size_t size (default = 0)
References CVector< CType >::resize(), and CVectorCore< CType >::size().
CVector() [2/3]
template<class CType > CVector< CType >::CVector (const CVectorCore< CType > & src) inline
Copy constructor
Parameters
const CVectorCore <CType> & src
References CVector< CType >::copy().
CVector() [3/3]
template<class CType > CVector< CType >::CVector (const CVector< CType > & src) inline
Copy constructor
Parameters
const CVector <CType> & src
References CVector< CType >::copy().
~CVector()
template<class CType > virtual CVector< CType >::~CVector () inline virtual
Destructor.
Member Function Documentation
copy()
template<class CType > void CVector< CType >::copy (const CVectorCore< CType > & rhs) inline protected
References CVectorCore< CType >::array(), CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by CVector< CType >::CVector(), CVector< CType >::operator=(), and CVector< CType >::resize().
operator=() [1/3]
template<class CType > CVector< CType>& CVector< CType >::operator= (const CType & value) inline
Assignment operator
Parameters
const CType & value
operator=() [2/3]
template<class CType > CVector< CType >& CVector< CType >::operator= (const CVector< CType > & rhs) inline
Assignment operator
Parameters
const CVector <CType> & rhs
Returns
CVector <CType> & lhs
References CVector< CType >::copy().
operator=() [3/3]
template<class CType > CVector< CType >& CVector< CType >::operator= (const CVectorCore< CType > & rhs) inline
Assignment operator
Parameters
const CVectorCore <CType> & rhs
Returns
CVector <CType> & lhs
References CVector< CType >::copy().
Referenced by CXMLHandlerFactory::CXMLHandlerFactory(), and CMathUpdateSequence::operator=().
resize()
template<class CType > void CVector< CType >::resize (size_t size, const bool & copy = false) inline
Resize the vector. The previous content is lost
Parameters
size_t size
References C_FLOAT64, CVector< CType >::copy(), CCopasiMessage::EXCEPTION, max, MCopasiBase, min, and CVectorCore< CType >::size().
Referenced by CProcessReport::addItem(), CMathContainer::analyzeRoots(), CLinkMatrix::build(), CEvaluationTree::buildCalculationSequence(), CSSAMethod::buildExtremeCurrents(), CModel::buildStoi(), CModel::buildUserOrder(), CFitProblem::calcCov(), CFitProblem::calcEigen(), CEigen::calcEigenValues(), CLNAMethod::calculateCovarianceMatrixReduced(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CExperiment::calculateStatistics(), CExperimentSet::calculateStatistics(), COptProblem::calculateStatistics(), CFitProblem::calculateStatistics(), CMCAMethod::calculateUnscaledConcentrationCC(), CFluxScore::CFluxScore(), CMCAMethod::checkSummationTheorems(), CTimeSeries::clear(), COptMethodSS::combination(), CMathExpression::compile(), CTimeSeries::compile(), CMathEvent::compile(), CExperiment::compile(), CExperimentObjectMap::compile(), CExperimentSet::compile(), CMathObject::compileDependentMass(), CEvaluationTree::compileNodes(), CMathObject::compilePropensity(), CMathObject::compileTotalMass(), CMathObject::compileTransitionTime(), CLinkMatrix::completePivotInformation(), CVector< CType >::copy(), CMathDelay::create(), CMathObject::createExtensiveReactionNoiseExpression(), CMathObject::createExtensiveReactionRateExpression(), CTimeSensLsodaMethod::createRootMask(), CHybridMethodODE45::createRootMask(), CLsodaMethod::createRootMask(), CLsodaMethod2::createRootMask(), CRadau5Method::createRootMask(), CStochasticRungeKuttaRI5::createRootMask(), CCSPMethod::CSPImportanceIndex(), CCSPMethod::CSPParticipationIndex(), CCSPMethod::cspstep(), CVector< CType >::CVector(), CHybridMethodODE45::destroyRootMask(), CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), CStepMatrixColumn::getAllUnsetBitIndexes(), CStepMatrix::getUnsetBitIndexes(), CMathContainer::ignoreDiscontinuityEvent(), CExperiment::initExtendedTimeSeries(), COptMethodCoranaWalk::initialize(), COptMethodDE::initialize(), COptMethodEP::initialize(), COptMethodGA::initialize(), COptMethodGASR::initialize(), COptMethodHookeJeeves::initialize(), COptMethodLevenbergMarquardt::initialize(), COptMethodNelderMead::initialize(), COptMethodNL2SOL::initialize(), COptMethodPraxis::initialize(), COptMethodPS::initialize(), COptMethodSA::initialize(), COptMethodSRES::initialize(), COptMethodSS::initialize(), COptMethodStatistics::initialize(), COptMethodSteepestDescent::initialize(), COptMethodTruncatedNewton::initialize(), CRandomSearch::initialize(), CEigen::initialize(), COptProblem::initialize(), CFitProblem::initialize(), CMathObject::initialize(), CMathReaction::initialize(), CNewtonMethod::initialize(), CLyapTask::initialize(), CCopasiTask::initialize(), CSensMethod::initialize(), CRootFinder::initialize(), CMathContainer::initializeAtolVector(), CModel::initializeAtolVector(), CTimeSensMethod::initializeDerivativesCalculations(), CLyapTask::initObjects(), LUfactor(), CEvaluationTree::mapObjectNodes(), CTSSAMethod::mat_anal_fast_space_thomas(), CTSSAMethod::mat_anal_metab(), CTSSAMethod::mat_anal_mod(), CILDMMethod::newton(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), COptMethodLevenbergMarquardt::optimise(), partialSortWithPivot(), CHybridMethodODE45::partitionSystem(), CExperiment::read(), CMathContainer::relocate(), CStateTemplate::resize(), CTSSAMethod::schur(), CTSSAMethod::schur_desc(), CFitProblem::setResidualsRequired(), CTimeSensLsodaMethod::setRootMaskType(), CLsodaMethod::setRootMaskType(), CRadau5Method::setRootMaskType(), CHybridMethod::setupPartition(), CStateTemplate::setUserOrder(), CLeastSquareSolution::solve(), sortWithPivot(), CLyapWolfMethod::start(), CMathEventQueue::start(), CTimeSensLsodaMethod::start(), CHybridMethodODE45::start(), CHybridNextReactionRKMethod::start(), CLsodaMethod::start(), CLsodaMethod2::start(), CRadau5Method::start(), CStochasticRungeKuttaRI5::start(), CStochDirectMethod::start(), CTauLeapMethod::start(), CTrajAdaptiveSA::start(), CCSPMethod::start(), CILDMMethod::start(), CILDMModifiedMethod::start(), CILDMMethod::step(), CILDMModifiedMethod::step(), CTSSAMethod::sylvester(), and CCSPMethod::yCorrection().
The documentation for this class was generated from the following file:
CVector.h