COPASI API: CLayoutEngine Class Reference
CLayoutEngine Class Reference
#include <CLayoutEngine.h>
Classes
struct Data
Public Member Functions
void calcForces (std::vector< double > &state, std::vector< double > &forces)
void calcRHS (std::vector< double > &state, double *rhs)
CLayoutEngine (CAbstractLayoutInterface *l, bool so)
CAbstractLayoutInterface * getLayoutInterface ()
void requestStop ()
double step ()
Protected Member Functions
void evalF (const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
void stepIntegration ()
Static Protected Member Functions
static void EvalF (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
Protected Attributes
Data mData
std::vector< C_FLOAT64 > mDWork
std::ostringstream mErrorMsg
unsigned int mIndex
std::vector< C_INT > mIWork
CLSODA mLSODA
C_INT mLsodaStatus
CAbstractLayoutInterface * mpLayout
std::vector< double > mRhs
std::vector< double > mRhsA
std::vector< double > mRhsB
std::vector< double > mRhsC
bool mSecondOrder
bool mStopRequested
C_FLOAT64 mTime
std::vector< double > mVar2
std::vector< double > mVariables
Constructor & Destructor Documentation
CLayoutEngine()
CLayoutEngine::CLayoutEngine (CAbstractLayoutInterface * l, bool so)
References CLayoutEngine::Data::dim, CAbstractLayoutInterface::getInitialValues(), mData, mDWork, mErrorMsg, mIWork, mLSODA, mLsodaStatus, mpLayout, mRhs, mRhsA, mRhsB, mRhsC, mSecondOrder, mTime, mVar2, mVariables, CLayoutEngine::Data::pMethod, and CInternalSolver::setOstream().
Member Function Documentation
calcForces()
void CLayoutEngine::calcForces (std::vector< double > & state, std::vector< double > & forces)
References CAbstractLayoutInterface::getNumVariables(), CAbstractLayoutInterface::getPotential(), mpLayout, mStopRequested, and CAbstractLayoutInterface::setState().
Referenced by calcRHS().
calcRHS()
void CLayoutEngine::calcRHS (std::vector< double > & state, double * rhs)
References calcForces(), CAbstractLayoutInterface::getMassVector(), CAbstractLayoutInterface::getNumVariables(), mpLayout, mSecondOrder, and mStopRequested.
Referenced by evalF(), step(), and stepIntegration().
evalF()
void CLayoutEngine::evalF (const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) protected
This evaluates the derivatives
References calcRHS(), and mVariables.
Referenced by EvalF().
EvalF()
void CLayoutEngine::EvalF (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) static protected
References evalF(), and CLayoutEngine::Data::pMethod.
getLayoutInterface()
CAbstractLayoutInterface* CLayoutEngine::getLayoutInterface () inline
References mpLayout.
requestStop()
void CLayoutEngine::requestStop ()
request the current operation to stop
References mStopRequested.
step()
double CLayoutEngine::step ()
References calcRHS(), CAbstractLayoutInterface::getPotential(), mpLayout, mRhs, mStopRequested, mVariables, and CAbstractLayoutInterface::setState().
stepIntegration()
void CLayoutEngine::stepIntegration () protected
References calcRHS(), mpLayout, mRhs, mRhsA, mRhsB, mRhsC, mVar2, mVariables, and CAbstractLayoutInterface::setState().
Member Data Documentation
mData
Data CLayoutEngine::mData protected
mData.dim is the dimension of the ODE system. mData.pMethod contains CLsodaMethod * this to be used in the static method EvalF
Referenced by CLayoutEngine().
mDWork
std::vector< C_FLOAT64 > CLayoutEngine::mDWork protected
LSODA C_FLOAT64 work area
Referenced by CLayoutEngine().
mErrorMsg
std::ostringstream CLayoutEngine::mErrorMsg protected
Stream to capture LSODA error messages
Referenced by CLayoutEngine().
mIndex
unsigned int CLayoutEngine::mIndex protected
mIWork
std::vector< C_INT > CLayoutEngine::mIWork protected
LSODA C_INT work area
Referenced by CLayoutEngine().
mLSODA
CLSODA CLayoutEngine::mLSODA protected
Referenced by CLayoutEngine().
mLsodaStatus
C_INT CLayoutEngine::mLsodaStatus protected
LSODA state.
Referenced by CLayoutEngine().
mpLayout
CAbstractLayoutInterface* CLayoutEngine::mpLayout protected
Referenced by calcForces(), calcRHS(), CLayoutEngine(), getLayoutInterface(), step(), and stepIntegration().
mRhs
std::vector<double> CLayoutEngine::mRhs protected
Referenced by CLayoutEngine(), step(), and stepIntegration().
mRhsA
std::vector<double> CLayoutEngine::mRhsA protected
Referenced by CLayoutEngine(), and stepIntegration().
mRhsB
std::vector<double> CLayoutEngine::mRhsB protected
Referenced by CLayoutEngine(), and stepIntegration().
mRhsC
std::vector<double> CLayoutEngine::mRhsC protected
Referenced by CLayoutEngine(), and stepIntegration().
mSecondOrder
bool CLayoutEngine::mSecondOrder protected
Referenced by calcRHS(), and CLayoutEngine().
mStopRequested
bool CLayoutEngine::mStopRequested protected
Referenced by calcForces(), calcRHS(), requestStop(), and step().
mTime
C_FLOAT64 CLayoutEngine::mTime protected
Current time.
Referenced by CLayoutEngine().
mVar2
std::vector<double> CLayoutEngine::mVar2 protected
Referenced by CLayoutEngine(), and stepIntegration().
mVariables
std::vector<double> CLayoutEngine::mVariables protected
Referenced by CLayoutEngine(), evalF(), step(), and stepIntegration().
The documentation for this class was generated from the following files:
CLayoutEngine.h
CLayoutEngine.cpp