COPASI API: CLRelAbsVector Class Reference
CLRelAbsVector Class Reference
#include <CLRelAbsVector.h>
Public Member Functions
CLRelAbsVector (const RelAbsVector &source)
CLRelAbsVector (const std::string &coordString)
CLRelAbsVector (double a=0.0, double r=0.0)
double getAbsoluteValue () const
double getRelativeValue () const
bool operator!= (const CLRelAbsVector &other) const
CLRelAbsVector operator+ (const CLRelAbsVector &other) const
CLRelAbsVector operator/ (double x) const
CLRelAbsVector & operator= (const CLRelAbsVector &src)
bool operator== (const CLRelAbsVector &other) const
void setAbsoluteValue (double abs)
void setCoordinate (const std::string &coordString)
void setCoordinate (double abs, double rel=0.0)
void setRelativeValue (double rel)
RelAbsVector * toSBML () const
std::string toString () const
Protected Attributes
double mAbs
double mRel
Constructor & Destructor Documentation
CLRelAbsVector() [1/3]
CLRelAbsVector::CLRelAbsVector (double a = 0.0, double r = 0.0)
Constructor with two values. First value sets the absolute value, econd sets the relative value.
Referenced by operator+(), and operator/().
CLRelAbsVector() [2/3]
CLRelAbsVector::CLRelAbsVector (const std::string & coordString)
Constructor with a string. The string has to be parsed. If the string does not represent a valid value, the relative and the absolute component of the CLRelAbsVector are set to NaN.
Constructor with two values. First value sets the absolute value, econd sets the relative value.
References setCoordinate().
CLRelAbsVector() [3/3]
CLRelAbsVector::CLRelAbsVector (const RelAbsVector & source)
Constructor to generate object from the corresponding SBML object.
Member Function Documentation
getAbsoluteValue()
double CLRelAbsVector::getAbsoluteValue () const
Returns the absolute coordinate value.
References mAbs.
Referenced by CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::create_linear_gradient_texture(), CLLayoutRenderer::create_radial_gradient_texture(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_text(), CLLayoutRenderer::getFontSpec(), CLGroup::isSetFontSize(), and CLText::isSetFontSize().
getRelativeValue()
double CLRelAbsVector::getRelativeValue () const
Returns the relative coordinate value.
References mRel.
Referenced by CLGradientStops::CLGradientStops(), CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::create_linear_gradient_texture(), CLLayoutRenderer::create_radial_gradient_texture(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_text(), CLLayoutRenderer::getFontSpec(), and CLLayoutRenderer::map_gradient_color().
operator!=()
bool CLRelAbsVector::operator!= (const CLRelAbsVector & other) const
operator+()
CLRelAbsVector CLRelAbsVector::operator+ (const CLRelAbsVector & other) const
addition operator
References CLRelAbsVector(), mAbs, and mRel.
operator/()
CLRelAbsVector CLRelAbsVector::operator/ (double x) const
division by a double.
References CLRelAbsVector(), mAbs, and mRel.
operator=()
CLRelAbsVector & CLRelAbsVector::operator= (const CLRelAbsVector & src)
References mAbs, and mRel.
operator==()
bool CLRelAbsVector::operator== (const CLRelAbsVector & other) const
References mAbs, and mRel.
setAbsoluteValue()
void CLRelAbsVector::setAbsoluteValue (double abs)
Sets the absolute coordinate value.
References abs, and mAbs.
setCoordinate() [1/2]
void CLRelAbsVector::setCoordinate (const std::string & coordString)
Sets the coordiantes from the given string.
References mAbs, and mRel.
setCoordinate() [2/2]
void CLRelAbsVector::setCoordinate (double abs, double rel = 0.0)
Sets the coordiantes.
References abs, mAbs, and mRel.
Referenced by CLRelAbsVector().
setRelativeValue()
void CLRelAbsVector::setRelativeValue (double rel)
Sets the relative coordinate value.
References mRel.
toSBML()
RelAbsVector * CLRelAbsVector::toSBML () const
Converts this object to the corresponding SBML object.
References mAbs, and mRel.
Referenced by CLRenderPoint::addSBMLAttributes(), CLEllipse::toSBML(), CLGradientStop::toSBML(), CLGroup::toSBML(), CLImage::toSBML(), CLLinearGradient::toSBML(), CLRadialGradient::toSBML(), CLRectangle::toSBML(), CLRenderCubicBezier::toSBML(), and CLText::toSBML().
toString()
std::string CLRelAbsVector::toString () const
References mAbs, and mRel.
Referenced by operator<<(), CCopasiXML::saveEllipseElement(), CCopasiXML::saveGradientStop(), CCopasiXML::saveImageElement(), CCopasiXML::saveLinearGradient(), CCopasiXML::saveRadialGradient(), CCopasiXML::saveRectangleElement(), CCopasiXML::saveRenderPoint(), and CCopasiXML::saveRenderTextElement().
Member Data Documentation
mAbs
double CLRelAbsVector::mAbs protected
Referenced by getAbsoluteValue(), operator+(), operator/(), operator=(), operator==(), setAbsoluteValue(), setCoordinate(), toSBML(), and toString().
mRel
double CLRelAbsVector::mRel protected
Referenced by getRelativeValue(), operator+(), operator/(), operator=(), operator==(), setCoordinate(), setRelativeValue(), toSBML(), and toString().
The documentation for this class was generated from the following files:
CLRelAbsVector.h
CLRelAbsVector.cpp