COPASI API: CCopasiTask Class Reference
CCopasiTask Class Reference
#include <CCopasiTask.h>
Classes
class CDescription
class CResult
Public Types
enum eOutputFlagBase {
INITIALIZE = 0x01 , STREAM = 0x02 , FINISH = 0x04 , REPORT = 0x10 ,
PLOT = 0x20 , TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0 , OUTPUT_BEFORE = INITIALIZE , OUTPUT_DURING = STREAM , OUTPUT_AFTER = FINISH ,
OUTPUT = REPORT | PLOT | STREAM , OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH , OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH , ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiTask (const CCopasiTask &src, const CDataContainer *pParent)
CCopasiTask (const CDataContainer *pParent, const CTaskEnum::Task &taskType, const std::string &type="Task")
void cleanup ()
virtual void clearCallBack ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const CProcessReportLevel & getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CMathContainer * getMathContainer () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CReport & getReport () const
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
CTaskEnum::Task getType () const
virtual const CTaskEnum::Method * getValidMethods () const
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual bool process (const bool &useInitialValues)
virtual bool restore (const bool &updateModel=true)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReportLevel callBack)
void setIgnoreProblemData (const bool &ignoreProblemData)
void setMathContainer (CMathContainer *pContainer)
bool setMethodType (const CTaskEnum::Method &type)
void setScheduled (const bool &scheduled)
void setType (const CTaskEnum::Task &type)
virtual void setUpdateModel (const bool &updateModel)
virtual CData toData () const
virtual bool updateMatrices ()
virtual ~CCopasiTask ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CCopasiTask * fromData (const CData &data, CUndoObjectInterface *pParent)
static bool isValidMethod (const CTaskEnum::Method &method, const CTaskEnum::Method *validMethods)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Public Attributes
std::string Error
std::string Warning
Protected Member Functions
bool isTaskValid () const
virtual void signalMathContainerChanged ()
virtual void signalMethodChanged ()
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
CDescription mDescription
OutputFlag mDoOutput
bool mIgnoreProblemData
CVector< C_FLOAT64 > mInitialState
std::string mKey
unsigned C_INT32 mOutputCounter
CMathContainer * mpContainer
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CProcessReportLevel mProcessReport
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
CTaskEnum::Task mType
bool mUpdateModel
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CCopasiTask ()
void initObjects ()
Additional Inherited Members
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Member Enumeration Documentation
eOutputFlagBase
enum CCopasiTask::eOutputFlagBase
Enumerator
INITIALIZE
STREAM
FINISH
REPORT
PLOT
TIME_SERIES
OutputFlag
enum CCopasiTask::OutputFlag
Enumerator
NO_OUTPUT
OUTPUT_BEFORE
OUTPUT_DURING
OUTPUT_AFTER
OUTPUT
OUTPUT_SE
OUTPUT_UI
ONLY_TIME_SERIES
Constructor & Destructor Documentation
CCopasiTask() [1/3]
CCopasiTask::CCopasiTask () private
Default constructor
References initObjects().
CCopasiTask() [2/3]
CCopasiTask::CCopasiTask (const CDataContainer * pParent, const CTaskEnum::Task & taskType, const std::string & type = "Task")
Specific constructor
Parameters
const Type & taskType
const CDataContainer * pParent
const std::string & type (default: "Task")
References CProblemFactory::create(), initObjects(), and mpProblem.
CCopasiTask() [3/3]
CCopasiTask::CCopasiTask (const CCopasiTask & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CCopasiTask & src
const CDataContainer * pParent (default: NULL)
References CMethodFactory::copy(), CProblemFactory::copy(), initObjects(), mpMethod, and mpProblem.
~CCopasiTask()
CCopasiTask::~CCopasiTask () virtual
Destructor
References CRootContainer::getKeyFactory(), mKey, mpMethod, mpProblem, mpSliders, pdelete, and CKeyFactory::remove().
Member Function Documentation
applyData()
bool CCopasiTask::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CCopasiParameterGroup::applyData(), CDataContainer::applyData(), fatalError, CDataObject::getObjectFromCN(), CData::getProperty(), CCopasiMethod::getSubType(), CData::isSetProperty(), CData::METHOD, CData::METHOD_TYPE, CTaskEnum::MethodName, mpMethod, mpProblem, mReport, mScheduled, mType, mUpdateModel, CData::PROBLEM, CReport::setAppend(), CReport::setConfirmOverwrite(), setMethodType(), CReport::setReportDefinition(), CReport::setTarget(), CData::TASK_REPORT, CData::TASK_REPORT_APPEND, CData::TASK_REPORT_CONFIRM_OVERWRITE, CData::TASK_REPORT_TARGET, CData::TASK_SCHEDULED, CData::TASK_TYPE, CData::TASK_UPDATE_MODEL, CTaskEnum::TaskName, CDataValue::toBool(), CDataValue::toData(), toEnum(), and CDataValue::toString().
cleanup()
void CCopasiTask::cleanup ()
Cleanup function
clearCallBack()
void CCopasiTask::clearCallBack () virtual
resets the currently set callback by calling setCallBack(NULL)
References setCallBack().
createUndoData()
void CCopasiTask::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CUndoData::addPostProcessData(), CUndoData::addPreProcessData(), CUndoData::addProperty(), CReport::append(), CUndoData::CHANGE, CUndoData::clear(), CReport::confirmOverwrite(), CMethodFactory::create(), CCopasiParameterGroup::createUndoData(), CDataContainer::createUndoData(), CDataObject::getCN(), CUndoData::getNewData(), CUndoData::getOldData(), CData::getProperty(), CReport::getReportDefinition(), CCopasiMethod::getSubType(), CReport::getTarget(), getType(), CUndoData::isChangedProperty(), CData::METHOD, CData::METHOD_TYPE, CTaskEnum::MethodName, mIgnoreProblemData, mpMethod, mpProblem, mReport, mScheduled, mType, mUpdateModel, CCore::ParticleNumbers, CData::PROBLEM, CData::TASK_REPORT, CData::TASK_REPORT_APPEND, CData::TASK_REPORT_CONFIRM_OVERWRITE, CData::TASK_REPORT_TARGET, CData::TASK_SCHEDULED, CData::TASK_TYPE, CData::TASK_UPDATE_MODEL, CTaskEnum::TaskName, CDataValue::toData(), CCopasiParameterGroup::toData(), toEnum(), CDataValue::toString(), and CTaskEnum::UnsetMethod.
fromData()
CCopasiTask * CCopasiTask::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CCopasiTask * pDataObject
CCopasiTask class. This class is used to describe a task in COPASI. This class is intended to be used as the parent class for all tasks within COPASI.
Created for COPASI by Stefan Hoops 2003
References CTaskFactory::create(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, CDataObject::setObjectName(), CData::TASK_TYPE, CTaskEnum::TaskName, toEnum(), and CDataValue::toString().
getCallBack()
const CProcessReportLevel & CCopasiTask::getCallBack () const
Returns
the currently set callback
References mProcessReport.
getDescription()
const CCopasiTask::CDescription & CCopasiTask::getDescription () const
Retrieve the description
References mDescription.
getKey()
const std::string & CCopasiTask::getKey () const virtual
Retrieve the key for the task.
Returns
std::string key
Reimplemented from CDataObject.
References mKey.
Referenced by CCopasiXML::saveTaskList(), CLNAProblem::setSteadyStateRequested(), and CMCAProblem::setSteadyStateRequested().
getMathContainer()
CMathContainer * CCopasiTask::getMathContainer () const
Retrieve the pointer to the container used for calculations
Returns
CMathContainer * pContainer
References mpContainer.
Referenced by CCopasiProblem::CCopasiProblem(), CMethodFactory::copy(), CProblemFactory::copy(), CMethodFactory::create(), CProblemFactory::create(), and COutputAssistant::createDefaultOutput().
getMethod() [1/2]
CCopasiMethod * CCopasiTask::getMethod ()
Retrieve the method
References mpMethod.
Referenced by SEDMLImporter::applyAlgorithm(), CFitProblem::calculate(), CSEDMLExporter::createTimeCourseTask(), COptProblem::initialize(), CNewtonMethod::initialize(), CTSSAProblem::printResult(), TaskHandler::processEnd(), MethodHandler::processStart(), and CCopasiXML::saveTaskList().
getMethod() [2/2]
const CCopasiMethod * CCopasiTask::getMethod () const
Retrieve the method
References mpMethod.
getOutputHandler()
COutputHandler * CCopasiTask::getOutputHandler () const
References mpOutputHandler.
getOutputMode()
const OutputFlag& CCopasiTask::getOutputMode () const inline
References mDoOutput.
getProblem() [1/2]
CCopasiProblem * CCopasiTask::getProblem ()
Retrieve the problem
References mpProblem.
Referenced by ResultData::appliesTo(), ResultData::applyToModelStateFromOptTask(), COptProblem::calculate(), CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), COutputAssistant::createDefaultOutput(), CModel::createEventsForTimeseries(), COutputAssistant::createPlot(), CSEDMLExporter::createScanTask(), CSEDMLExporter::createSteadyStateTask(), CSEDMLExporter::createTimeCourseTask(), CNewtonMethod::doIntegration(), CODEExporter::exportExpression(), CODEExporterBM::exportTitleData(), CODEExporterXPPAUT::exportTitleData(), SEDMLImporter::importTask(), CEFMMethod::initialize(), CSSAMethod::initialize(), CFitProblem::initialize(), CNewtonMethod::initialize(), isTaskValid(), CLNATask::process(), CMCATask::process(), CScanTask::processCallback(), TaskHandler::processEnd(), TaskHandler::processStart(), CCopasiXML::saveTaskList(), ResultData::setOptItemStartValues(), SEDMLImporter::updateCopasiTaskForSimulation(), and ResultData::updateFitItemsFromOptItems().
getProblem() [2/2]
const CCopasiProblem * CCopasiTask::getProblem () const
Retrieve the problem
References mpProblem.
getReport() [1/2]
CReport & CCopasiTask::getReport ()
Retrieve the report
References mReport.
Referenced by CDataModel::addDefaultReports(), CSEDMLExporter::createDataGenerators(), COptProblem::initialize(), ReportTargetHandler::processStart(), and CCopasiXML::saveTaskList().
getReport() [2/2]
const CReport & CCopasiTask::getReport () const
Retrieve the report
References mReport.
getResult()
const CCopasiTask::CResult & CCopasiTask::getResult () const
Retrieve the result
References mResult.
getSliders()
CCopasiParameterGroup * CCopasiTask::getSliders ()
Retrieve a pointer to the group of sliders.
Returns
CCopasiParameterGroup * pSliders
References mpSliders.
getType()
CTaskEnum::Task CCopasiTask::getType (void) const
Retrieve the type of the task
Returns
CTaskEnum::Task type
References mType.
Referenced by CPlotSpecification::appliesTo(), COptProblem::calculate(), CAnalyticsTask::CAnalyticsTask(), CCrossSectionTask::CCrossSectionTask(), CEFMTask::CEFMTask(), CFitTask::CFitTask(), CLNATask::CLNATask(), CMCATask::CMCATask(), CMoietiesTask::CMoietiesTask(), COptTask::COptTask(), CTaskFactory::copy(), COscillationTask::COscillationTask(), CMethodFactory::create(), COutputAssistant::createPlot(), createUndoData(), CScanTask::CScanTask(), CSensTask::CSensTask(), CSteadyStateTask::CSteadyStateTask(), CTimeSensTask::CTimeSensTask(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), COutputAssistant::getListOfDefaultOutputDescriptions(), COptProblem::getSubtaskType(), CTrajectoryTask::load(), ParameterGroupHandler::processEnd(), TaskHandler::processEnd(), CCopasiXML::saveTaskList(), and setMethodType().
getValidMethods()
const CTaskEnum::Method * CCopasiTask::getValidMethods () const virtual
Retrieve the list of valid methods
Returns
const CTaskEnum::Method * pValidMethods
Reimplemented in CSteadyStateTask, CMCATask, CFitTask, COptTask, CMoietiesTask, CLNATask, CCrossSectionTask, CAnalyticsTask, CTSSATask, CTrajectoryTask, CTimeSensTask, CSensTask, CScanTask, CLyapTask, and CEFMTask.
References CTaskEnum::UnsetMethod.
Referenced by CMethodFactory::create(), and setMethodType().
initialize()
bool CCopasiTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented in CSteadyStateTask, CMCATask, CFitTask, COptTask, CMoietiesTask, CLNATask, CCrossSectionTask, CAnalyticsTask, CTSSATask, CTrajectoryTask, CTimeSensTask, CSensTask, CScanTask, COscillationTask, CLyapTask, and CEFMTask.
References COutputHandler::addInterface(), CCopasiMessage::COMMANDLINE, COutputHandler::compile(), CMathContainer::getInitialState(), CDataObject::getObjectDataModel(), CDataObject::getObjectName(), CReport::getTarget(), isTaskValid(), MCCopasiTask, mDoOutput, mInitialState, mOutputCounter, mpContainer, mpOutputHandler, mReport, NO_OUTPUT, CReport::open(), REPORT, CVector< CType >::resize(), and CCopasiMessage::WARNING.
Referenced by COptProblem::calculate(), CEFMTask::initialize(), CLyapTask::initialize(), COscillationTask::initialize(), CScanTask::initialize(), CSensTask::initialize(), CTimeSensTask::initialize(), CTrajectoryTask::initialize(), CTSSATask::initialize(), CLNATask::initialize(), CMoietiesTask::initialize(), COptTask::initialize(), CMCATask::initialize(), CSteadyStateTask::initialize(), CSensMethod::initialize(), COptProblem::initializeSubtaskBeforeOutput(), and CScanTask::initSubtask().
initObjects()
void CCopasiTask::initObjects () private
References CDataContainer::addObjectReference(), CModel::getMathContainer(), CDataModel::getModel(), CDataObject::getObjectDataModel(), mOutputCounter, CCopasiTimer::PROCESS, setMathContainer(), CDataObject::ValueInt, and CCopasiTimer::WALL.
Referenced by CCopasiTask().
isScheduled()
const bool & CCopasiTask::isScheduled () const
Check whether the task is scheduled
Returns
const bool & scheduled
References mScheduled.
Referenced by CSEDMLExporter::createTasks(), and CCopasiXML::saveTaskList().
isTaskValid()
bool CCopasiTask::isTaskValid () const protected
Check whether the task definition is valid
Returns
bool isValid
References CCopasiMessage::ERROR, CDataObject::getObjectName(), getProblem(), CCopasiProblem::getSubTask(), CDataContainer::insert(), MCCopasiTask, mpContainer, mpMethod, and mpProblem.
Referenced by CScanTask::initialize(), CSensTask::initialize(), initialize(), COptTask::initialize(), and setCallBack().
isUpdateModel()
const bool & CCopasiTask::isUpdateModel () const
Check whether the task must update the model
Returns
const bool & updateModel
References mUpdateModel.
Referenced by CSensMethod::initialize(), CScanTask::processCallback(), and CCopasiXML::saveTaskList().
isValidMethod()
bool CCopasiTask::isValidMethod (const CTaskEnum::Method & method, const CTaskEnum::Method * validMethods) static
Check whether the given method is in the list of valid methods This list must end with CCopasiMethod::unset
Parameters
const CTaskEnum::Method & method
const CTaskEnum::Method * validMethods
Returns
bool isValid
References C_INT32, and CTaskEnum::UnsetMethod.
Referenced by CMethodFactory::create(), and setMethodType().
output()
void CCopasiTask::output (const COutputInterface::Activity & activity) virtual
Perform an output event for the current activity
Parameters
const Activity & activity
Reimplemented in CTimeSensTask.
References COutputInterface::AFTER, COutputInterface::BEFORE, COutputInterface::DURING, mDoOutput, mOutputCounter, mpOutputHandler, NO_OUTPUT, COutputHandler::output(), OUTPUT_AFTER, and OUTPUT_BEFORE.
Referenced by COptMethodNL2SOL::calcr(), CExperimentSet::calculateStatistics(), COptMethodPS::create(), COptMethodPraxis::evaluateFunction(), CCrossSectionTask::eventCallBack(), CAnalyticsTask::finish(), CCrossSectionTask::finish(), CLyapTask::methodCallback(), COptMethodPS::move(), COptMethodCoranaWalk::optimise(), COptMethodDE::optimise(), COptMethodEP::optimise(), COptMethodGA::optimise(), COptMethodGASR::optimise(), COptMethodHookeJeeves::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodNelderMead::optimise(), COptMethodNL2SOL::optimise(), COptMethodPraxis::optimise(), COptMethodPS::optimise(), COptMethodSA::optimise(), COptMethodSRES::optimise(), COptMethodSS::optimise(), COptMethodStatistics::optimise(), COptMethodSteepestDescent::optimise(), COptMethodTruncatedNewton::optimise(), CRandomSearch::optimise(), CTrajectoryMethod::output(), CTimeSensTask::output(), CEFMTask::process(), CLyapTask::process(), COscillationTask::process(), CScanTask::process(), CSensTask::process(), CTSSATask::process(), CCrossSectionTask::process(), CLNATask::process(), CMoietiesTask::process(), COptTask::process(), CFitTask::process(), CMCATask::process(), CSteadyStateTask::process(), CScanTask::processCallback(), CTrajectoryTask::processStep(), CTrajectoryTask::processTrajectory(), CTrajectoryTask::processValues(), and COptMethodTruncatedNewton::sFun().
process()
bool CCopasiTask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented in CSteadyStateTask, CMCATask, CFitTask, COptTask, CMoietiesTask, CLNATask, CCrossSectionTask, CAnalyticsTask, CTSSATask, CTrajectoryTask, CTimeSensTask, CSensTask, CScanTask, COscillationTask, CLyapTask, and CEFMTask.
Referenced by COptProblem::calculate(), CSensMethod::do_target_calculation(), and CScanTask::processCallback().
restore()
bool CCopasiTask::restore (const bool & updateModel = true) virtual
Perform necessary cleanup procedures
Parameters
const bool & updateModel (default: true)
Reimplemented in CSteadyStateTask, CCrossSectionTask, and CAnalyticsTask.
References CMathContainer::getCountFixed(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getInitialState(), CMathContainer::getState(), CMathContainer::isAutonomous(), CMathContainer::isStateValid(), mInitialState, mpContainer, mpProblem, mUpdateModel, CCore::ParticleNumbers, CMathContainer::pushAllTransientValues(), CMathContainer::pushInitialState(), CCopasiProblem::restore(), setCallBack(), CMathContainer::setInitialState(), CMathContainer::updateInitialValues(), CMathContainer::updateSimulatedValues(), and CMathContainer::updateTransientDataValues().
Referenced by CSensMethod::restore(), COptProblem::restore(), CScanProblem::restore(), CFitProblem::restore(), CAnalyticsTask::restore(), and CCrossSectionTask::restore().
separate()
void CCopasiTask::separate (const COutputInterface::Activity & activity) virtual
Introduce an additional separator into the output
Parameters
const Activity & activity
References COutputInterface::AFTER, COutputInterface::BEFORE, COutputInterface::DURING, mDoOutput, mpOutputHandler, OUTPUT_AFTER, OUTPUT_BEFORE, and COutputHandler::separate().
Referenced by CScanTask::outputSeparatorCallback().
setCallBack()
bool CCopasiTask::setCallBack (CProcessReportLevel callBack) virtual
Set the call back of the task
Parameters
CProcessReport & callBack
Returns
bool success
Reimplemented in CMCATask, CFitTask, COscillationTask, COptTask, CMoietiesTask, CLNATask, and CEFMTask.
References isTaskValid(), mpMethod, mProcessReport, and CCopasiMethod::setCallBack().
Referenced by clearCallBack(), CNewtonMethod::doIntegration(), CFitProblem::initialize(), CSensMethod::initialize(), COptProblem::initializeSubtaskBeforeOutput(), CScanTask::initSubtask(), CSensMethod::process(), CScanTask::process(), CLNATask::process(), CMCATask::process(), restore(), CSteadyStateTask::restore(), CEFMTask::setCallBack(), CLNATask::setCallBack(), CMoietiesTask::setCallBack(), COptProblem::setCallBack(), COptTask::setCallBack(), COscillationTask::setCallBack(), CFitProblem::setCallBack(), CFitTask::setCallBack(), CSensMethod::setCallBack(), and CMCATask::setCallBack().
setIgnoreProblemData()
void CCopasiTask::setIgnoreProblemData (const bool & ignoreProblemData)
Set whether the task shall ignoew problem data
Parameters
const bool & ignoreProblemData
References mIgnoreProblemData.
setMathContainer()
void CCopasiTask::setMathContainer (CMathContainer * pContainer)
Set the pointer to container used for calculations
Parameters
CMathContainer * pContainer
References mpContainer, mpMethod, mpProblem, CCopasiMethod::setMathContainer(), CCopasiProblem::setMathContainer(), and signalMathContainerChanged().
Referenced by SEDMLImporter::importTask(), CFitProblem::initialize(), CSensMethod::initialize(), COptProblem::initializeSubtaskBeforeOutput(), initObjects(), CScanTask::initSubtask(), TaskHandler::processStart(), and SEDMLImporter::updateCopasiTaskForSimulation().
setMethodType()
bool CCopasiTask::setMethodType (const CTaskEnum::Method & type)
Set the method type applied to solve the task
Parameters
const CTaskEnum::Method & type
Returns
bool success
References CMethodFactory::create(), CCopasiMethod::getSubType(), getType(), getValidMethods(), isValidMethod(), mpMethod, pdelete, and signalMethodChanged().
Referenced by SEDMLImporter::applyAlgorithm(), applyData(), CNewtonMethod::initialize(), and MethodHandler::processStart().
setScheduled()
void CCopasiTask::setScheduled (const bool & scheduled)
Set whether the task is scheduled
Parameters
const bool & scheduled
References mScheduled.
Referenced by SEDMLImporter::importTask(), TaskHandler::processStart(), and SEDMLImporter::updateCopasiTaskForSimulation().
setType()
void CCopasiTask::setType (const CTaskEnum::Task & type)
Set the type of the task
Parameters
CTaskEnum::Task & type
References mType.
setUpdateModel()
void CCopasiTask::setUpdateModel (const bool & updateModel) virtual
Set whether the task must update the model
Parameters
const bool & updateModel
References mUpdateModel.
Referenced by CFitProblem::initialize(), CSensMethod::process(), and TaskHandler::processStart().
signalMathContainerChanged()
void CCopasiTask::signalMathContainerChanged () protected virtual
Signal that the math container has changed
Reimplemented in CTrajectoryTask, and CTimeSensTask.
Referenced by setMathContainer().
signalMethodChanged()
void CCopasiTask::signalMethodChanged () protected virtual
Signal that the method has changed
Reimplemented in CTrajectoryTask, and CTimeSensTask.
Referenced by setMethodType().
toData()
CData CCopasiTask::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::addProperty(), CReport::append(), CReport::confirmOverwrite(), CDataObject::getCN(), CReport::getReportDefinition(), CCopasiMethod::getSubType(), CReport::getTarget(), CData::METHOD, CData::METHOD_TYPE, CTaskEnum::MethodName, mIgnoreProblemData, mpMethod, mpProblem, mReport, mScheduled, mType, mUpdateModel, CData::PROBLEM, CData::TASK_REPORT, CData::TASK_REPORT_APPEND, CData::TASK_REPORT_CONFIRM_OVERWRITE, CData::TASK_REPORT_TARGET, CData::TASK_SCHEDULED, CData::TASK_TYPE, CData::TASK_UPDATE_MODEL, CTaskEnum::TaskName, CCopasiParameterGroup::toData(), CDataContainer::toData(), and CTaskEnum::UnsetMethod.
updateMatrices()
virtual bool CCopasiTask::updateMatrices () inline virtual
Resizes result matrices and updates array annotations for a specific task. For now this will be hard coded in the respective derived classes. We may introduce a more generic mechanism for this in the future. This is used when we need to know about the data structures of a task result without actually performing the task, e.g. when selecting objects for output. For now we assume that this functionality is also performed when initialize() is called.
Reimplemented in CSteadyStateTask, CMCATask, CLNATask, CTSSATask, CTimeSensTask, and CSensTask.
Member Data Documentation
Error
std::string CCopasiTask::Error
mDescription
CDescription CCopasiTask::mDescription protected
The description of the task.
Referenced by getDescription().
mDoOutput
OutputFlag CCopasiTask::mDoOutput protected
Referenced by getOutputMode(), initialize(), output(), and separate().
mIgnoreProblemData
bool CCopasiTask::mIgnoreProblemData protected
Referenced by createUndoData(), setIgnoreProblemData(), and toData().
mInitialState
CVector< C_FLOAT64 > CCopasiTask::mInitialState protected
The state of the model before execution of the task. If mUpdateModel is false this state is restored.
Referenced by initialize(), restore(), and CSteadyStateTask::restore().
mKey
std::string CCopasiTask::mKey protected
The key of the task
Referenced by getKey(), and ~CCopasiTask().
mOutputCounter
unsigned C_INT32 CCopasiTask::mOutputCounter protected
Referenced by initialize(), initObjects(), and output().
mpContainer
CMathContainer* CCopasiTask::mpContainer protected
A pointer to the math container used for calculation
Referenced by CAnalyticsTask::computeSelectedStatistics(), CAnalyticsTask::createEvent(), CCrossSectionTask::createEvent(), CAnalyticsTask::eventCallBack(), CCrossSectionTask::eventCallBack(), CAnalyticsTask::finish(), CEFMTask::getInternalSpecies(), getMathContainer(), CEFMTask::getNetReaction(), CTSSATask::initialize(), initialize(), CFitTask::initialize(), CSteadyStateTask::initialize(), CScanTask::initSubtask(), isTaskValid(), CLyapTask::process(), CScanTask::process(), CSensTask::process(), CTimeSensTask::process(), CTSSATask::process(), CAnalyticsTask::process(), CCrossSectionTask::process(), CLNATask::process(), CMoietiesTask::process(), CMCATask::process(), CSteadyStateTask::process(), CTimeSensTask::processStart(), CTrajectoryTask::processStart(), CTSSATask::processStart(), CTSSATask::processStep(), CTimeSensTask::processStep(), CTrajectoryTask::processStep(), CTrajectoryTask::processTrajectory(), CTrajectoryTask::processValues(), CAnalyticsTask::relativeDifferenceOfStates(), CCrossSectionTask::relativeDifferenceOfStates(), CAnalyticsTask::removeEvent(), CCrossSectionTask::removeEvent(), restore(), CSteadyStateTask::restore(), setMathContainer(), CTimeSensTask::signalMathContainerChanged(), CTrajectoryTask::signalMathContainerChanged(), CTSSATask::updateMatrices(), and CSteadyStateTask::updateMatrices().
mpMethod
CCopasiMethod* CCopasiTask::mpMethod protected
The method used to solve the problem.
Referenced by applyData(), CAnalyticsTask::CAnalyticsTask(), CCopasiTask(), CCrossSectionTask::CCrossSectionTask(), CEFMTask::CEFMTask(), CFitTask::CFitTask(), CLNATask::CLNATask(), CLyapTask::CLyapTask(), CMCATask::CMCATask(), CMoietiesTask::CMoietiesTask(), COptTask::COptTask(), COscillationTask::COscillationTask(), createUndoData(), CScanTask::CScanTask(), CSensTask::CSensTask(), CSteadyStateTask::CSteadyStateTask(), CTimeSensTask::CTimeSensTask(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), CEFMTask::getFluxModeDescription(), getMethod(), CEFMTask::getReactionEquation(), CEFMTask::initialize(), CLyapTask::initialize(), COscillationTask::initialize(), CScanTask::initialize(), CTimeSensTask::initialize(), CTrajectoryTask::initialize(), CTSSATask::initialize(), CAnalyticsTask::initialize(), CCrossSectionTask::initialize(), CLNATask::initialize(), CMoietiesTask::initialize(), COptTask::initialize(), CMCATask::initialize(), CSteadyStateTask::initialize(), isTaskValid(), CLNATask::load(), CMCATask::load(), CSteadyStateTask::load(), CTrajectoryTask::load(), CLNATask::printResult(), CMCATask::printResult(), CEFMTask::process(), COscillationTask::process(), CScanTask::process(), CSensTask::process(), CTSSATask::process(), CLNATask::process(), CMoietiesTask::process(), COptTask::process(), CFitTask::process(), CMCATask::process(), CSteadyStateTask::process(), CEFMTask::setCallBack(), setCallBack(), CMoietiesTask::setCallBack(), COscillationTask::setCallBack(), CFitTask::setCallBack(), setMathContainer(), setMethodType(), CTimeSensTask::signalMethodChanged(), CTrajectoryTask::signalMethodChanged(), toData(), CSensTask::updateMatrices(), CTimeSensTask::updateMatrices(), CTSSATask::updateMatrices(), CLNATask::updateMatrices(), CMCATask::updateMatrices(), and ~CCopasiTask().
mpOutputHandler
COutputHandler* CCopasiTask::mpOutputHandler protected
Referenced by getOutputHandler(), initialize(), output(), CMoietiesTask::process(), and separate().
mpProblem
CCopasiProblem* CCopasiTask::mpProblem protected
The problem of the task
Referenced by applyData(), CCopasiTask(), CFitTask::CFitTask(), COptTask::COptTask(), COscillationTask::COscillationTask(), createUndoData(), CScanTask::CScanTask(), CFitTask::fixBuild55(), CScanTask::fixBuild81(), CEFMTask::getFluxModeDescription(), CEFMTask::getFluxModes(), CEFMTask::getNetReactionData(), getProblem(), CEFMTask::getReactionEquation(), CEFMTask::getSpeciesChanges(), CEFMTask::initialize(), CLyapTask::initialize(), COscillationTask::initialize(), CScanTask::initialize(), CTimeSensTask::initialize(), CTrajectoryTask::initialize(), CTSSATask::initialize(), CAnalyticsTask::initialize(), CCrossSectionTask::initialize(), CLNATask::initialize(), CMoietiesTask::initialize(), COptTask::initialize(), CFitTask::initialize(), CMCATask::initialize(), CSteadyStateTask::initialize(), CScanTask::initSubtask(), isTaskValid(), CLNATask::load(), CMCATask::load(), CSteadyStateTask::load(), CTrajectoryTask::load(), CLNATask::printResult(), CMCATask::printResult(), COscillationTask::process(), CScanTask::process(), CSensTask::process(), CTSSATask::process(), CCrossSectionTask::process(), CLNATask::process(), COptTask::process(), CFitTask::process(), CMCATask::process(), CSteadyStateTask::process(), restore(), CEFMTask::setCallBack(), CLNATask::setCallBack(), CMoietiesTask::setCallBack(), COptTask::setCallBack(), COscillationTask::setCallBack(), CFitTask::setCallBack(), CMCATask::setCallBack(), setMathContainer(), toData(), CSensTask::updateMatrices(), CTSSATask::updateMatrices(), CLNATask::updateMatrices(), CMCATask::updateMatrices(), and ~CCopasiTask().
mProcessReport
CProcessReportLevel CCopasiTask::mProcessReport protected
progress bar handler
Referenced by CAnalyticsTask::eventCallBack(), CCrossSectionTask::eventCallBack(), CAnalyticsTask::finish(), CCrossSectionTask::finish(), getCallBack(), CLyapTask::methodCallback(), CLyapTask::process(), CScanTask::process(), CTimeSensTask::process(), CTSSATask::process(), CAnalyticsTask::process(), CCrossSectionTask::process(), CLNATask::process(), COptTask::process(), CFitTask::process(), CMCATask::process(), CSteadyStateTask::process(), CScanTask::processCallback(), CTimeSensTask::processStep(), CTrajectoryTask::processStep(), CTrajectoryTask::processTrajectory(), CTrajectoryTask::processValues(), CEFMTask::setCallBack(), setCallBack(), CLNATask::setCallBack(), CMoietiesTask::setCallBack(), COptTask::setCallBack(), CFitTask::setCallBack(), and CMCATask::setCallBack().
mpSliders
CCopasiParameterGroup* CCopasiTask::mpSliders protected
Pointer to group of sliders associated with the task.
Referenced by getSliders(), and ~CCopasiTask().
mReport
CReport CCopasiTask::mReport protected
The report that belongs to this specific task
Referenced by applyData(), createUndoData(), getReport(), CScanTask::initialize(), initialize(), CLNATask::initialize(), CMCATask::initialize(), and toData().
mResult
CResult CCopasiTask::mResult protected
The result of the task.
Referenced by getResult().
mScheduled
bool CCopasiTask::mScheduled protected
Tells whether the task is scheduled for execution
Referenced by applyData(), createUndoData(), isScheduled(), CLNATask::load(), CMCATask::load(), CSteadyStateTask::load(), CTrajectoryTask::load(), setScheduled(), and toData().
mType
CTaskEnum::Task CCopasiTask::mType protected
The type of the task
Referenced by applyData(), createUndoData(), getType(), setType(), and toData().
mUpdateModel
bool CCopasiTask::mUpdateModel protected
Tells whether the task shall update the model with the result. The restore method must act accordingly.
Referenced by applyData(), createUndoData(), isUpdateModel(), restore(), CSteadyStateTask::restore(), setUpdateModel(), and toData().
Warning
std::string CCopasiTask::Warning
The documentation for this class was generated from the following files:
CCopasiTask.h
CCopasiTask.cpp