COPASI API: CCrossSectionProblem Class Reference
CCrossSectionProblem Class Reference
#include <CCrossSectionProblem.h>
Public Member Functions
CCrossSectionProblem (const CCrossSectionProblem &src, const CDataContainer *pParent)
CCrossSectionProblem (const CDataContainer *pParent=NO_PARENT)
const C_FLOAT64 & getConvergenceOutTolerance () const
const C_FLOAT64 & getConvergenceTolerance () const
const unsigned C_INT32 & getCrossingsLimit () const
bool getFlagLimitConvergence () const
bool getFlagLimitCrossings () const
bool getFlagLimitOutConvergence () const
bool getFlagLimitOutCrossings () const
bool getFlagLimitOutTime () const
const unsigned C_INT32 & getOutCrossingsLimit () const
const std::string & getSingleObjectCN () const
const C_FLOAT64 & getThreshold () const
const C_FLOAT64 & getTimeLimit () const
bool isPositiveDirection () const
virtual void print (std::ostream *ostream) const
void setConvergenceOutTolerance (const C_FLOAT64 &convergenceTolerance)
void setConvergenceTolerance (const C_FLOAT64 &convergenceTolerance)
void setCrossingsLimit (const unsigned C_INT32 &crossingLimit)
void setFlagLimitConvergence (bool flagLimitConvergence)
void setFlagLimitCrossings (bool flagLimitCrossing)
void setFlagLimitOutConvergence (bool flagLimitConvergence)
void setFlagLimitOutCrossings (bool flagLimitCrossing)
void setFlagLimitOutTime (bool flagLimitTime)
void setOutCrossingsLimit (const unsigned C_INT32 &crossingLimit)
void setPositiveDirection (bool isPositive)
void setSingleObjectCN (const CDataObject *pObject)
void setSingleObjectCN (const std::string &cn)
void setThreshold (const C_FLOAT64 &threshold)
void setTimeLimit (const C_FLOAT64 &timeLimit)
virtual ~CCrossSectionProblem ()
Public Member Functions inherited from CTrajectoryProblem
CTrajectoryProblem (const CDataContainer *pParent=NO_PARENT)
CTrajectoryProblem (const CTrajectoryProblem &src, const CDataContainer *pParent)
virtual bool elevateChildren ()
bool getAutomaticStepSize () const
const C_FLOAT64 & getDuration () const
const bool & getOutputEvent () const
const C_FLOAT64 & getOutputStartTime () const
bool getStartInSteadyState () const
const unsigned C_INT32 & getStepNumber () const
const C_FLOAT64 & getStepSize () const
bool getUseValues () const
std::set< C_FLOAT64 > getValues () const
const std::string & getValueString () const
void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::NEXT)
virtual void printResult (std::ostream *ostream) const
void setAutomaticStepSize (const bool &automaticStepSize)
void setDuration (const C_FLOAT64 &duration)
void setOutputEvent (const bool &outputEvent)
void setOutputStartTime (const C_FLOAT64 &endTime)
void setStartInSteadyState (bool flag)
void setStepNumber (const unsigned C_INT32 &stepNumber)
void setStepSize (const C_FLOAT64 &stepSize)
void setTimeSeriesRequested (bool flag)
void setUseValues (bool flag)
void setValues (const std::string &values)
void setValues (const std::vector< C_FLOAT64 > &values)
bool timeSeriesRequested () const
~CTrajectoryProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CDataContainer *pParent)
virtual void clearCallBack ()
CCopasiProblem * copy () const
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
virtual CCopasiTask * getSubTask () const
const CTaskEnum::Task & getType () const
virtual bool initialize ()
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual bool setModel (CModel *model)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Protected Member Functions
CCrossSectionProblem (const CCrossSectionProblem &src)
Protected Member Functions inherited from CTrajectoryProblem
CTrajectoryProblem (const CTaskEnum::Task &type, const CDataContainer *pParent)
CTrajectoryProblem (const CTrajectoryProblem &src)
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src)
CCopasiProblem (const CTaskEnum::Task &type, const CDataContainer *pParent)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Private Member Functions
unsigned C_INT32 getStepNumber () const
C_FLOAT64 getStepSize () const
void initializeParameter ()
void initObjects ()
Private Attributes
C_FLOAT64 * mpConvergenceOutTolerance
C_FLOAT64 * mpConvergenceTolerance
unsigned C_INT32 * mpCrossingsLimit
bool * mpFlagLimitConvergence
bool * mpFlagLimitCrossings
bool * mpFlagLimitOutConvergence
bool * mpFlagLimitOutCrossings
bool * mpFlagLimitOutTime
bool * mpFlagPositiveDirection
unsigned C_INT32 * mpOutCrossingsLimit
C_FLOAT64 * mpThreshold
std::string * mpTriggerExpression
std::string * mSingleObjectCN
Friends
std::ostream & operator<< (std::ostream &os, const CCrossSectionProblem &o)
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Attributes inherited from CTrajectoryProblem
bool * mpAutomaticStepSize
C_FLOAT64 * mpDuration
bool * mpOutputEvent
C_FLOAT64 * mpOutputStartTime
bool * mpStartInSteadyState
unsigned C_INT32 * mpStepNumber
C_FLOAT64 * mpStepSize
bool * mpTimeSeriesRequested
bool * mpUseValues
std::string * mpValueString
bool mStepNumberSetLast
Protected Attributes inherited from CCopasiProblem
CMathContainer * mpContainer
CReport * mpReport
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CCrossSectionProblem() [1/3]
CCrossSectionProblem::CCrossSectionProblem (const CCrossSectionProblem & src) protected
CCrossSectionProblem() [2/3]
CCrossSectionProblem::CCrossSectionProblem (const CDataContainer * pParent = NO_PARENT)
Default constructor.
Parameters
const CDataContainer * pParent (default: NULL)
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
CCrossSectionProblem() [3/3]
CCrossSectionProblem::CCrossSectionProblem (const CCrossSectionProblem & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CCrossSectionProblem & src @paramconst CDataContainer * pParent (default: NULL)
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
~CCrossSectionProblem()
CCrossSectionProblem::~CCrossSectionProblem () virtual
Destructor.
References DESTRUCTOR_TRACE.
Member Function Documentation
getConvergenceOutTolerance()
const C_FLOAT64 & CCrossSectionProblem::getConvergenceOutTolerance () const
Function to get mpConvergenceOutTolerance
References mpConvergenceOutTolerance.
getConvergenceTolerance()
const C_FLOAT64 & CCrossSectionProblem::getConvergenceTolerance () const
Function to get mpConvergenceTolerance
References mpConvergenceTolerance.
getCrossingsLimit()
const unsigned C_INT32 & CCrossSectionProblem::getCrossingsLimit () const
Function to get mpCrossingsLimit
References mpCrossingsLimit.
Referenced by CCrossSectionTask::process().
getFlagLimitConvergence()
bool CCrossSectionProblem::getFlagLimitConvergence () const
Function to get mpFlagLimitConvergence
References mpFlagLimitConvergence.
Referenced by CCrossSectionTask::eventCallBack().
getFlagLimitCrossings()
bool CCrossSectionProblem::getFlagLimitCrossings () const
Function to get mpFlagLimitCrossings
References mpFlagLimitCrossings.
Referenced by CCrossSectionTask::process().
getFlagLimitOutConvergence()
bool CCrossSectionProblem::getFlagLimitOutConvergence () const
Function to get mpFlagLimitOutConvergence
References mpFlagLimitOutConvergence.
Referenced by CCrossSectionTask::eventCallBack().
getFlagLimitOutCrossings()
bool CCrossSectionProblem::getFlagLimitOutCrossings () const
Function to get mpFlagLimitOutCrossings
References mpFlagLimitOutCrossings.
Referenced by CCrossSectionTask::eventCallBack(), and CCrossSectionTask::process().
getFlagLimitOutTime()
bool CCrossSectionProblem::getFlagLimitOutTime () const
Function to get mpFlagLimitOutTime
References mpFlagLimitOutTime.
Referenced by CCrossSectionTask::eventCallBack(), and CCrossSectionTask::process().
getOutCrossingsLimit()
const unsigned C_INT32 & CCrossSectionProblem::getOutCrossingsLimit () const
Function to get mpOutCrossingsLimit
References mpOutCrossingsLimit.
Referenced by CCrossSectionTask::process().
getSingleObjectCN()
const std::string & CCrossSectionProblem::getSingleObjectCN () const
return the variable
References mSingleObjectCN.
Referenced by CCrossSectionTask::createEvent().
getStepNumber()
unsigned C_INT32 CCrossSectionProblem::getStepNumber () const inline private
getStepSize()
C_FLOAT64 CCrossSectionProblem::getStepSize () const inline private
getThreshold()
const C_FLOAT64 & CCrossSectionProblem::getThreshold () const
References mpThreshold.
Referenced by CCrossSectionTask::createEvent().
getTimeLimit()
const C_FLOAT64 & CCrossSectionProblem::getTimeLimit () const
Function to get mpTimeLimit
References CTrajectoryProblem::mpDuration.
initializeParameter()
void CCrossSectionProblem::initializeParameter () private
Initialize the parameters
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameter::CN, CCopasiParameter::DOUBLE, CCopasiParameter::EXPRESSION, mpConvergenceOutTolerance, mpConvergenceTolerance, mpCrossingsLimit, mpFlagLimitConvergence, mpFlagLimitCrossings, mpFlagLimitOutConvergence, mpFlagLimitOutCrossings, mpFlagLimitOutTime, mpFlagPositiveDirection, mpOutCrossingsLimit, mpThreshold, mpTriggerExpression, mSingleObjectCN, CTrajectoryProblem::setOutputEvent(), and CCopasiParameter::UINT.
Referenced by CCrossSectionProblem().
initObjects()
void CCrossSectionProblem::initObjects () private
Referenced by CCrossSectionProblem().
isPositiveDirection()
bool CCrossSectionProblem::isPositiveDirection () const
References mpFlagPositiveDirection.
Referenced by CCrossSectionTask::createEvent().
print()
void CCrossSectionProblem::print (std::ostream * ostream) const virtual
This is the output method for any object. It calls the insert operator<<
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
setConvergenceOutTolerance()
void CCrossSectionProblem::setConvergenceOutTolerance (const C_FLOAT64 & convergenceTolerance)
Function to set mpConvergenceOutTolerance
References mpConvergenceOutTolerance.
setConvergenceTolerance()
void CCrossSectionProblem::setConvergenceTolerance (const C_FLOAT64 & convergenceTolerance)
Function to set mpConvergenceTolerance
References mpConvergenceTolerance.
setCrossingsLimit()
void CCrossSectionProblem::setCrossingsLimit (const unsigned C_INT32 & crossingLimit)
Function to set mpCrossingsLimit
References mpCrossingsLimit.
setFlagLimitConvergence()
void CCrossSectionProblem::setFlagLimitConvergence (bool flagLimitConvergence)
Function to set mpFlagLimitConvergence
References mpFlagLimitConvergence.
setFlagLimitCrossings()
void CCrossSectionProblem::setFlagLimitCrossings (bool flagLimitCrossing)
Function to set mpFlagLimitCrossings
References mpFlagLimitCrossings.
setFlagLimitOutConvergence()
void CCrossSectionProblem::setFlagLimitOutConvergence (bool flagLimitConvergence)
Function to set mpFlagLimitOutConvergence
References mpFlagLimitOutConvergence.
setFlagLimitOutCrossings()
void CCrossSectionProblem::setFlagLimitOutCrossings (bool flagLimitCrossing)
Function to set mpFlagLimitOutCrossings
References mpFlagLimitOutCrossings.
setFlagLimitOutTime()
void CCrossSectionProblem::setFlagLimitOutTime (bool flagLimitTime)
Function to set mpFlagLimitOutTime
References mpFlagLimitOutTime.
setOutCrossingsLimit()
void CCrossSectionProblem::setOutCrossingsLimit (const unsigned C_INT32 & crossingLimit)
Function to set mpOutCrossingsLimit
References mpOutCrossingsLimit.
setPositiveDirection()
void CCrossSectionProblem::setPositiveDirection (bool isPositive)
References mpFlagPositiveDirection.
setSingleObjectCN() [1/2]
void CCrossSectionProblem::setSingleObjectCN (const CDataObject * pObject)
References CDataObject::getCN(), and setSingleObjectCN().
setSingleObjectCN() [2/2]
void CCrossSectionProblem::setSingleObjectCN (const std::string & cn)
References mSingleObjectCN.
Referenced by setSingleObjectCN().
setThreshold()
void CCrossSectionProblem::setThreshold (const C_FLOAT64 & threshold)
References mpThreshold.
setTimeLimit()
void CCrossSectionProblem::setTimeLimit (const C_FLOAT64 & timeLimit)
Function to set mpTimeLimit
References CTrajectoryProblem::mpDuration.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CCrossSectionProblem & o) friend
This is the output method for any result of a problem. The default implementation provided with CCopasiProblem. Does only print "Not implemented." To overide this default behaviour one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream Output stream operator. Prints description of the problem
ostream & os
const Problem & A
Returns
ostream & os
Member Data Documentation
mpConvergenceOutTolerance
C_FLOAT64* CCrossSectionProblem::mpConvergenceOutTolerance private
this variable indicates the tolerance after which the calculation should be considered converged and output should commence
this member variable is mapped to a CCopasiParameter
Referenced by getConvergenceOutTolerance(), initializeParameter(), and setConvergenceOutTolerance().
mpConvergenceTolerance
C_FLOAT64* CCrossSectionProblem::mpConvergenceTolerance private
this variable indicates the tolerance after which the calculation should be considered converged
this member variable is mapped to a CCopasiParameter
Referenced by getConvergenceTolerance(), initializeParameter(), and setConvergenceTolerance().
mpCrossingsLimit
unsigned C_INT32* CCrossSectionProblem::mpCrossingsLimit private
this variable indicates after how many crossings the calculation should be stopped if the corresponding flag is true.
this member variable is mapped to a CCopasiParameter
Referenced by getCrossingsLimit(), initializeParameter(), and setCrossingsLimit().
mpFlagLimitConvergence
bool* CCrossSectionProblem::mpFlagLimitConvergence private
this flag indicates whether the calculation should be stopped when convergence is reached
this member variable is mapped to a CCopasiParameter
Referenced by getFlagLimitConvergence(), initializeParameter(), and setFlagLimitConvergence().
mpFlagLimitCrossings
bool* CCrossSectionProblem::mpFlagLimitCrossings private
this flag indicates whether the calculation should be stopped after a given number of detected crossings
this member variable is mapped to a CCopasiParameter
Referenced by getFlagLimitCrossings(), initializeParameter(), and setFlagLimitCrossings().
mpFlagLimitOutConvergence
bool* CCrossSectionProblem::mpFlagLimitOutConvergence private
this flag indicates whether the output should only be collected once convergence is reached
this member variable is mapped to a CCopasiParameter
Referenced by getFlagLimitOutConvergence(), initializeParameter(), and setFlagLimitOutConvergence().
mpFlagLimitOutCrossings
bool* CCrossSectionProblem::mpFlagLimitOutCrossings private
this flag indicates whether the output should be collected after a given number of detected crossings
this member variable is mapped to a CCopasiParameter
Referenced by getFlagLimitOutCrossings(), initializeParameter(), and setFlagLimitOutCrossings().
mpFlagLimitOutTime
bool* CCrossSectionProblem::mpFlagLimitOutTime private
this flag indicates whether output should be selected after a delay
this member variable is mapped to a CCopasiParameter
Referenced by getFlagLimitOutTime(), initializeParameter(), and setFlagLimitOutTime().
mpFlagPositiveDirection
bool* CCrossSectionProblem::mpFlagPositiveDirection private
Referenced by initializeParameter(), isPositiveDirection(), and setPositiveDirection().
mpOutCrossingsLimit
unsigned C_INT32* CCrossSectionProblem::mpOutCrossingsLimit private
this variable indicates after how many crossings the output should start if the corresponding flag is true.
this member variable is mapped to a CCopasiParameter
Referenced by getOutCrossingsLimit(), initializeParameter(), and setOutCrossingsLimit().
mpThreshold
C_FLOAT64* CCrossSectionProblem::mpThreshold private
Referenced by getThreshold(), initializeParameter(), and setThreshold().
mpTriggerExpression
std::string* CCrossSectionProblem::mpTriggerExpression private
this variable holds the trigger expression
this member variable is mapped to a CCopasiParameter
Referenced by initializeParameter().
mSingleObjectCN
std::string* CCrossSectionProblem::mSingleObjectCN private
Referenced by getSingleObjectCN(), initializeParameter(), and setSingleObjectCN().
The documentation for this class was generated from the following files:
CCrossSectionProblem.h
CCrossSectionProblem.cpp