COPASI API: CEvaluationNodeVector Class Reference
CEvaluationNodeVector Class Reference
#include <CEvaluationNodeVector.h>
Public Member Functions
bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
CEvaluationNodeVector ()
CEvaluationNodeVector (const CEvaluationNodeVector &src)
CEvaluationNodeVector (const SubType &subType, const Data &data)
virtual std::string getBerkeleyMadonnaString (const std::vector< std::string > &children) const
virtual std::string getCCodeString (const std::vector< std::string > &children) const
virtual std::string getDisplayString (const std::vector< std::string > &children) const
virtual std::string getInfix (const std::vector< std::string > &children) const
const std::vector< CEvaluationNode * > & getNodes () const
virtual CValidatedUnit getUnit (const CMathContainer &container, const std::vector< CValidatedUnit > &units) const
virtual std::string getXPPString (const std::vector< std::string > &children) const
virtual CValidatedUnit setUnit (const CMathContainer &container, const std::map< CEvaluationNode *, CValidatedUnit > &currentUnits, std::map< CEvaluationNode *, CValidatedUnit > &targetUnits) const
virtual ASTNode * toAST (const CDataModel *pDataModel) const
virtual ~CEvaluationNodeVector ()
Public Member Functions inherited from CEvaluationNode
void addChildren (const std::vector< CEvaluationNode * > &children)
std::string buildBerkeleyMadonnaString () const
std::string buildCCodeString () const
std::string buildDisplayString () const
std::string buildInfix () const
std::string buildMMLString (bool expand, const std::vector< std::vector< std::string > > &variables) const
std::string buildXPPString () const
virtual void calculate ()
CEvaluationNode ()
CEvaluationNode (const CEvaluationNode &src)
virtual CIssue compile ()
CEvaluationNode * copyBranch () const
CEvaluationNode * copyNode (CEvaluationNode *child1, CEvaluationNode *child2) const
CEvaluationNode * copyNode (const std::vector< CEvaluationNode * > &children) const
const CEvaluationNode * findTopMinus (const std::vector< CFunctionAnalyzer::CValue > &callParameters) const
virtual std::string getMMLString (const std::vector< std::string > &children, bool expand, const std::vector< std::vector< std::string > > &variables) const
const CEvaluationTree * getTree () const
const C_FLOAT64 * getValuePointer () const
const ValueType & getValueType () const
virtual bool isBoolean () const
const MainType & mainType () const
bool operator!= (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &rhs)
bool operator< (const CEvaluationNode &right) const
bool operator== (const CEvaluationNode &right) const
void printRecursively () const
void printRecursively (std::ostream &os, int indent=0) const
void setTree (const CEvaluationTree *pTree)
virtual CIssue setValueType (const ValueType &valueType)
virtual CEvaluationNode * simplifyNode (const std::vector< CEvaluationNode * > &children) const
CEvaluationNode * splitBranch (const CEvaluationNode *splitnode, bool left) const
const SubType & subType () const
virtual ~CEvaluationNode ()
Public Member Functions inherited from CCopasiNode< std::string >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual Data & getData ()
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Static Public Member Functions
static CEvaluationNode * fromAST (const ASTNode *pASTNode, const std::vector< CEvaluationNode * > &children)
Static Public Member Functions inherited from CEvaluationNode
static CEvaluationNode * create (const MainType &mainType, const SubType &subType, const std::string &data)
static bool isKeyword (const std::string &str)
Private Attributes
std::vector< CEvaluationNode * > mNodes
std::vector< const C_FLOAT64 * > mValues
Additional Inherited Members
Public Types inherited from CEvaluationNode
enum class MainType {
INVALID , NUMBER , CONSTANT , OPERATOR ,
OBJECT , FUNCTION , CALL , STRUCTURE ,
CHOICE , VARIABLE , WHITESPACE , LOGICAL ,
MV_FUNCTION , VECTOR , DELAY , UNIT ,
__SIZE
}
enum class SubType {
DEFAULT , DELAY , IF , VECTOR ,
CN , DOUBLE , FUNCTION , LOG ,
OPEN , PI , POWER , EXPRESSION ,
POINTER , EXPONENTIALE , INTEGER , LOG10 ,
MULTIPLY , OR , VECTOROPEN , COMMA ,
DIVIDE , ENOTATION , EXP , True ,
XOR , RATIONALE , AND , CLOSE ,
False , MODULUS , SIN , VECTORCLOSE ,
COS , EQ , Infinity , PLUS ,
NaN , MINUS , NE , TAN ,
REMAINDER , GT , SEC , CSC ,
GE , COT , LT , LE ,
SINH , COSH , TANH , SECH ,
CSCH , COTH , ARCSIN , ARCCOS ,
ARCTAN , ARCSEC , ARCCSC , ARCCOT ,
ARCSINH , ARCCOSH , ARCTANH , ARCSECH ,
ARCCSCH , ARCCOTH , SQRT , ABS ,
FLOOR , CEIL , FACTORIAL , NOT ,
RUNIFORM , RNORMAL , MAX , MIN ,
RGAMMA , RPOISSON , SIGN , AVOGADRO ,
INVALID , __SIZE
}
enum class ValueType { Unknown , Boolean , Number , __SIZE }
Public Types inherited from CCopasiNode< std::string >
typedef std::string Data
Static Public Attributes inherited from CEvaluationNode
static const CEnumAnnotation< std::string, MainType > MainTypeName
static const CEnumAnnotation< std::string, SubType > SubTypeName
Protected Member Functions inherited from CEvaluationNode
CEvaluationNode (const MainType &type, const SubType &subType, const Data &data)
Protected Member Functions inherited from CCopasiNode< std::string >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CEvaluationNode
MainType mMainType
class CEvaluationNode::CPrecedence mPrecedence
const CEvaluationTree * mpTree
const C_FLOAT64 * mpValue
SubType mSubType
C_FLOAT64 mValue
ValueType mValueType
Protected Attributes inherited from CCopasiNode< std::string >
Data mData
Detailed Description
This is the class for nodes presenting operators used in an evaluation trees.
Constructor & Destructor Documentation
CEvaluationNodeVector() [1/3]
CEvaluationNodeVector::CEvaluationNodeVector ()
Default constructor
References CEvaluationNode::mPrecedence, and PRECEDENCE_FUNCTION.
CEvaluationNodeVector() [2/3]
CEvaluationNodeVector::CEvaluationNodeVector (const SubType & subType, const Data & data)
Default constructor
Parameters
const SubType & subType
const Data & data
References fatalError, CEvaluationNode::mPrecedence, PRECEDENCE_FUNCTION, CEvaluationNode::subType(), and CEvaluationNode::VECTOR.
CEvaluationNodeVector() [3/3]
CEvaluationNodeVector::CEvaluationNodeVector (const CEvaluationNodeVector & src)
Copy constructor
Parameters
const CEvaluationNodeVector & src
~CEvaluationNodeVector()
CEvaluationNodeVector::~CEvaluationNodeVector () virtual
Destructor
Member Function Documentation
addChild()
bool CEvaluationNodeVector::addChild (CCopasiNode< Data > * pChild, CCopasiNode< Data > * pAfter = NULL)
Add a child to a node. If pAfter == this the child will be inserted at the fornt of the list of children.
Parameters
CCopasiNode< Data > * pChild
CCopasiNode< Data > * pAfter (default: NULL appended to the list of children)
Returns
bool Success
References CCopasiNode< _Data >::addChild(), and mNodes.
fromAST()
CEvaluationNode * CEvaluationNodeVector::fromAST (const ASTNode * pASTNode, const std::vector< CEvaluationNode * > & children) static
Creates a new CEvaluationNodeCall from an ASTNode and the given children
Parameters
const ASTNode* pNode
const std::vector< CEvaluationNode * > & children
Returns
CEvaluationNode * pCretedNode
getBerkeleyMadonnaString()
std::string CEvaluationNodeVector::getBerkeleyMadonnaString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in Berkeley Madonna format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
getCCodeString()
std::string CEvaluationNodeVector::getCCodeString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in C.
Returns
const Data & value
Reimplemented from CEvaluationNode.
getDisplayString()
std::string CEvaluationNodeVector::getDisplayString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
getInfix()
std::string CEvaluationNodeVector::getInfix (const std::vector< std::string > & children) const virtual
Retrieve the infix value of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
getNodes()
const std::vector< CEvaluationNode * > & CEvaluationNodeVector::getNodes () const
Retrieve the vector of evaluation nodes
Returns
const std::vector< CEvaluationNode * > & vector
References mNodes.
Referenced by CEvaluationNodeCall::buildParameters(), and CEvaluationNodeCall::clearParameters().
getUnit()
CValidatedUnit CEvaluationNodeVector::getUnit (const CMathContainer & container, const std::vector< CValidatedUnit > & units) const virtual
Figure out the appropriate CUnit to use, based on the child nodes. This sets the default, appropriate for many cases, as Dimensionless
Parameters
const CMathContainer & container
const std::vector< CUnit > & units
Returns
CUnit unit
Reimplemented from CEvaluationNode.
References CValidatedUnit::merge(), mNodes, CValidatedUnit::setConflict(), and CBaseUnit::undefined.
getXPPString()
std::string CEvaluationNodeVector::getXPPString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in XPPAUT format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
setUnit()
CValidatedUnit CEvaluationNodeVector::setUnit (const CMathContainer & container, const std::map< CEvaluationNode *, CValidatedUnit > & currentUnits, std::map< CEvaluationNode *, CValidatedUnit > & targetUnits) const virtual
Set the unit for the node and return the resulting unit. The child node units are added to the map
Parameters
const CMathContainer & container
const std::map < CEvaluationNode * , CValidatedUnit > & currentUnits
std::map < CEvaluationNode * , CValidatedUnit > & targetUnits
Returns
CUnit unit
Reimplemented from CEvaluationNode.
References mNodes, and CEvaluationNode::setUnit().
toAST()
ASTNode * CEvaluationNodeVector::toAST (const CDataModel * pDataModel) const virtual
Create a new ASTNode corresponding to this choice node.
Returns
ASTNode* return a pointer to the newly created node;
Reimplemented from CEvaluationNode.
Member Data Documentation
mNodes
std::vector< CEvaluationNode * > CEvaluationNodeVector::mNodes private
Referenced by addChild(), getNodes(), getUnit(), and setUnit().
mValues
std::vector< const C_FLOAT64 * > CEvaluationNodeVector::mValues private
The documentation for this class was generated from the following files:
CEvaluationNodeVector.h
CEvaluationNodeVector.cpp