COPASI API: CCommonName Class Reference
CCommonName Class Reference
#include <CCommonName.h>
Public Member Functions
CCommonName ()
CCommonName (const CCommonName &src)
CCommonName (const char *name)
CCommonName (const std::string &name)
std::string::size_type findNext (const std::string &toFind, const std::string::size_type &pos=0) const
std::string::size_type findPrevious (const std::string &toFind, const std::string::size_type &pos=std::string::npos) const
size_t getElementIndex (const size_t &pos=0) const
std::string getElementName (const size_t &pos, const bool &unescape=true) const
std::string getObjectName () const
std::string getObjectType () const
CCommonName getPrimary () const
CCommonName getRemainder () const
void split (CCommonName &parentCN, std::string &objectType, std::string &objectName) const
~CCommonName ()
Static Public Member Functions
static std::string compartmentNameFromCN (const CCommonName &cn)
static std::string construct (const CCommonName &parent, const std::string &objectType, const std::string &objectName)
static std::string escape (const std::string &name)
static std::string fromData (const CData &data)
static std::string nameFromCN (const CCommonName &cn)
static std::string unescape (const std::string &name)
Private Member Functions
void fixSpelling ()
Constructor & Destructor Documentation
CCommonName() [1/4]
CCommonName::CCommonName ()
Default Constructor
Referenced by getRemainder().
CCommonName() [2/4]
CCommonName::CCommonName (const CCommonName & src)
Copy Constructor
Parameters
const CRegisteredCommonName & src
~CCommonName()
CCommonName::~CCommonName ()
Destructor
CCommonName() [3/4]
CCommonName::CCommonName (const char * name)
Constructor from base class
Parameters
const char * name
References fixSpelling().
CCommonName() [4/4]
CCommonName::CCommonName (const std::string & name)
Constructor from base class
Parameters
const std::string & name
References fixSpelling().
Member Function Documentation
compartmentNameFromCN()
std::string CCommonName::compartmentNameFromCN (const CCommonName & cn) static
References split().
construct()
std::string CCommonName::construct (const CCommonName & parent, const std::string & objectType, const std::string & objectName) static
References escape(), and split().
Referenced by fromData().
escape()
std::string CCommonName::escape (const std::string & name) static
References toBeEscaped.
Referenced by CDataVectorN< CType >::applyData(), construct(), CReactionInterface::createUndoData(), CDataObject::getCN(), CCopasiParameter::getCN(), CDataArray::getObject(), CUndoData::getObject(), CMetabNameInterface::getSpeciesCN(), CRegisteredCommonName::sanitizeObjectNames(), CDataArray::setAnnotationString(), CDataObject::setObjectName(), split(), and CArrayElementReference::updateObjectName().
findNext()
std::string::size_type CCommonName::findNext (const std::string & toFind, const std::string::size_type & pos = 0) const
Referenced by getElementName(), getObjectName(), getObjectType(), getPrimary(), getRemainder(), and CRegisteredCommonName::sanitizeObjectNames().
findPrevious()
std::string::size_type CCommonName::findPrevious (const std::string & toFind, const std::string::size_type & pos = std::string::npos) const
Referenced by split().
fixSpelling()
void CCommonName::fixSpelling () private
Referenced by CCommonName().
fromData()
std::string CCommonName::fromData (const CData & data) static
References construct(), CData::getProperty(), CData::OBJECT_NAME, CData::OBJECT_PARENT_CN, CData::OBJECT_TYPE, and CDataValue::toString().
Referenced by CUndoData::change(), CUndoData::getObjectCN(), CUndoData::insert(), and CUndoData::remove().
getElementIndex()
size_t CCommonName::getElementIndex (const size_t & pos = 0) const
References C_INVALID_INDEX, getElementName(), and strToIndex().
Referenced by CDataVectorReference< CType >::getObject(), CDataMatrixReference< CType >::getObject(), and CDataVector< CType >::getObject().
getElementName()
std::string CCommonName::getElementName (const size_t & pos, const bool & unescape = true) const
References findNext(), getPrimary(), and unescape().
Referenced by getElementIndex(), CDataArray::getObject(), CDataContainer::getObject(), CDataVectorN< CType >::getObject(), CUndoData::getObjectDisplayName(), CRegisteredCommonName::sanitizeObjectNames(), and split().
getObjectName()
std::string CCommonName::getObjectName () const
References findNext(), getObjectType(), getPrimary(), and unescape().
Referenced by CReportDefinition::addTableElement(), CCopasiParameterGroup::getObject(), CDataContainer::getObject(), CReaction::resolveCN(), CRegisteredCommonName::sanitizeObjectNames(), and split().
getObjectType()
std::string CCommonName::getObjectType () const
References findNext(), getPrimary(), and unescape().
Referenced by CDataContainer::getObject(), CObjectInterface::GetObjectFromCN(), getObjectName(), CReaction::resolveCN(), CRegisteredCommonName::sanitizeObjectNames(), split(), and CModelExpansion::updateExpression().
getPrimary()
CCommonName CCommonName::getPrimary () const
References findNext().
Referenced by getElementName(), CMathContainer::getObject(), CObjectInterface::GetObjectFromCN(), getObjectName(), getObjectType(), and CModelExpansion::updateExpression().
getRemainder()
CCommonName CCommonName::getRemainder () const
References CCommonName(), and findNext().
Referenced by CDataArray::getObject(), CCopasiParameterGroup::getObject(), CDataContainer::getObject(), CDataVector< CType >::getObject(), CDataVectorN< CType >::getObject(), CObjectInterface::GetObjectFromCN(), CReaction::resolveCN(), CRegisteredCommonName::sanitizeObjectNames(), and CModelExpansion::updateExpression().
nameFromCN()
std::string CCommonName::nameFromCN (const CCommonName & cn) static
References split().
Referenced by CModelParameter::getName(), and CModelParameterSpecies::getName().
split()
void CCommonName::split (CCommonName & parentCN, std::string & objectType, std::string & objectName) const
References escape(), findPrevious(), getElementName(), getObjectName(), and getObjectType().
Referenced by compartmentNameFromCN(), CModelParameterReactionParameter::compile(), construct(), and nameFromCN().
unescape()
std::string CCommonName::unescape (const std::string & name) static
Referenced by CDataArray::displayNamesToCN(), getElementName(), getObjectName(), and getObjectType().
The documentation for this class was generated from the following files:
CCommonName.h
CCommonName.cpp