COPASI API: CCSPMethod Class Reference
CCSPMethod Class Reference
The CCSPMethod class implements the CSP method.
#include <CCSPMethod.h>
Public Member Functions
CCSPMethod (const CCSPMethod &src, const CDataContainer *pParent)
CCSPMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType=CTaskEnum::Method::tssCSP, const CTaskEnum::Task &taskType=CTaskEnum::Task::tssAnalysis)
virtual void createAnnotationsM ()
void CSPOutput (C_INT &N, C_INT &M, C_INT &R)
void emptyVectors ()
const CDataArray * getFastParticipationIndexAnn () const
const CDataArray * getFastReactionPointerAnn () const
const CDataArray * getFastReactionPointerNormedAnn () const
const CDataArray * getImportanceIndexAnn () const
const CDataArray * getImportanceIndexNormedRowAnn () const
const CDataArray * getParticipationIndexAnn () const
const CDataArray * getParticipationIndexNormedColumnAnn () const
const CDataArray * getParticipationIndexNormedRowAnn () const
const CDataArray * getRadicalPointerAnn () const
const CDataArray * getSlowParticipationIndexAnn () const
virtual void initializeOutput ()
void initializeParameter ()
virtual void printResult (std::ostream *ostream) const
virtual bool setAnnotationM (size_t step)
void setVectors (int fast)
void setVectorsToNaN ()
virtual void start ()
virtual void step (const double &deltaT)
virtual ~CCSPMethod ()
Public Member Functions inherited from CTSSAMethod
CTSSAMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType=CTaskEnum::Task::tssAnalysis)
CTSSAMethod (const CTSSAMethod &src, const CDataContainer *pParent)
void emptyVectors ()
const int & getCurrentStep () const
const CDataArray * getTable (const std::string &name)
const std::vector< std::string > & getTableNames () const
C_FLOAT64 getTimeForStep (int step) const
CVector< C_FLOAT64 > getVec_TimeScale (int step)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (CTSSAProblem *problem)
void setVectors (int slowMode)
virtual ~CTSSAMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CDataContainer *pParent)
virtual void clearCallBack ()
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
const CTaskEnum::Method & getSubType () const
const CTaskEnum::Task & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
CCopasiMethod & operator= (const CCopasiMethod &rhs)
virtual void print (std::ostream *ostream) const
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Protected Member Functions
void basisRefinement (C_INT N, C_INT M, const CMatrix< C_FLOAT64 > &ALA, const CMatrix< C_FLOAT64 > &TAU, CMatrix< C_FLOAT64 > &A, CMatrix< C_FLOAT64 > &B, CMatrix< C_FLOAT64 > &A0, CMatrix< C_FLOAT64 > &B0)
void calculateJacobian (C_INT &n, CVector< C_FLOAT64 > &y, CMatrix< C_FLOAT64 > &J)
void CSPImportanceIndex (C_INT &N, C_FLOAT64 &tauM1, CMatrix< C_FLOAT64 > &Q)
void CSPParticipationIndex (C_INT &N, C_INT &M, C_FLOAT64 &tauM1, CMatrix< C_FLOAT64 > &B0)
void CSPradicalPointer (C_INT &N, C_INT &M, CMatrix< C_FLOAT64 > &A, CMatrix< C_FLOAT64 > &B)
void cspstep (const double &deltaT, C_INT &n, C_INT &m, CMatrix< C_FLOAT64 > &A, CMatrix< C_FLOAT64 > &B)
void emptyOutputData (C_INT N, C_INT M, C_INT R)
void findCandidatesNumber (C_INT &n, C_INT &k, CVector< C_FLOAT64 > &tsc, C_INT &info)
void findTimeScaleSeparation (C_INT &n, C_INT &k, CVector< C_FLOAT64 > &tsc, C_INT &info)
C_INT isBlockDiagonal (C_INT N, C_INT M, const CMatrix< C_FLOAT64 > &ALA, const C_FLOAT64 &SMALL)
void modesAmplitude (C_INT N, const CVector< C_FLOAT64 > &g, const CMatrix< C_FLOAT64 > &B, CMatrix< C_FLOAT64 > &F)
bool modesAreExhausted (C_INT N, C_INT M, C_FLOAT64 &tauM, C_FLOAT64 &tauM1, CVector< C_FLOAT64 > &g, const CMatrix< C_FLOAT64 > &A, const CMatrix< C_FLOAT64 > &B, CMatrix< C_FLOAT64 > &F)
void smadd (const CMatrix< C_FLOAT64 > &A, const CMatrix< C_FLOAT64 > &B, CMatrix< C_FLOAT64 > &C, C_INT n1, C_INT n2)
void sminverse (C_INT n, const CMatrix< C_FLOAT64 > &A, CMatrix< C_FLOAT64 > &B)
void smmult (const CMatrix< C_FLOAT64 > &A, const CMatrix< C_FLOAT64 > &B, CMatrix< C_FLOAT64 > &C, C_INT n1, C_INT n2, C_INT n3)
void smnorm (C_INT n, CMatrix< C_FLOAT64 > &A, CMatrix< C_FLOAT64 > &B, C_INT n1)
void smsubst (const CMatrix< C_FLOAT64 > &A, const CMatrix< C_FLOAT64 > &B, CMatrix< C_FLOAT64 > &C, C_INT n1, C_INT n2)
void yCorrection (C_INT &N, C_INT &M, CVector< C_FLOAT64 > &y, CMatrix< C_FLOAT64 > &TAUM, CMatrix< C_FLOAT64 > &F, CMatrix< C_FLOAT64 > &A)
Protected Member Functions inherited from CTSSAMethod
void calculateDerivatives (C_FLOAT64 *X1, C_FLOAT64 *Y1, bool useReducedModel)
bool elevateChildren ()
void integrationMethodStart ()
void integrationStep (const double &deltaT)
void map_index (C_FLOAT64 *eval_r, C_INT *index, const C_INT &dim)
void map_index_desc (C_FLOAT64 *eval_r, C_INT *index, const C_INT &dim)
void mat_anal_fast_space (C_INT &slow)
void mat_anal_fast_space_thomas (C_INT &slow)
void mat_anal_metab (C_INT &slow)
void mat_anal_mod (C_INT &slow)
void mat_anal_mod_space (C_INT &slow)
double orthog (C_INT &number1, C_INT &number2)
void schur (C_INT &info)
void schur_desc (C_INT &info)
void sylvester (C_INT slow, C_INT &info)
void update_nid (C_INT *index, C_INT *nid, const C_INT &dim)
void update_pid (C_INT *index, C_INT *pid, const C_INT &dim)
virtual void updateCurrentTime ()
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src)
CCopasiMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
C_FLOAT64 mAerror
CVector< C_FLOAT64 > mAmplitude
CMatrix< C_FLOAT64 > mB
C_INT mCSPbasis
C_FLOAT64 mEps
CVector< C_FLOAT64 > mFastParticipationIndex
CMatrix< C_FLOAT64 > mFastParticipationIndexTab
CMatrix< C_FLOAT64 > mFastReactionPointer
CMatrix< C_FLOAT64 > mFastReactionPointerNormed
CMatrix< C_FLOAT64 > mFastReactionPointerNormedTab
CMatrix< C_FLOAT64 > mFastReactionPointerTab
CVectorCore< const C_FLOAT64 > mG
CMatrix< C_FLOAT64 > mI
CMatrix< C_FLOAT64 > mImportanceIndex
CMatrix< C_FLOAT64 > mImportanceIndexNormedRow
CMatrix< C_FLOAT64 > mImportanceIndexNormedRowTab
CMatrix< C_FLOAT64 > mImportanceIndexTab
C_INT mIter
CMatrix< C_FLOAT64 > mParticipationIndex
CMatrix< C_FLOAT64 > mParticipationIndexNormedColumn
CMatrix< C_FLOAT64 > mParticipationIndexNormedColumnTab
CMatrix< C_FLOAT64 > mParticipationIndexNormedRow
CMatrix< C_FLOAT64 > mParticipationIndexNormedRowTab
CMatrix< C_FLOAT64 > mParticipationIndexTab
CMatrix< C_FLOAT64 > mRadicalPointer
CMatrix< C_FLOAT64 > mRadicalPointerTab
bool mReducedModel
C_FLOAT64 mRerror
C_INT mSetVectors
CVector< C_FLOAT64 > mSlowParticipationIndex
CMatrix< C_FLOAT64 > mSlowParticipationIndexTab
C_FLOAT64 mTsc
C_INT mTStep
std::vector< CMatrix< C_FLOAT64 > > mVec_mFastParticipationIndex
std::vector< CMatrix< C_FLOAT64 > > mVec_mFastReactionPointer
std::vector< CMatrix< C_FLOAT64 > > mVec_mFastReactionPointerNormed
std::vector< CMatrix< C_FLOAT64 > > mVec_mImportanceIndex
std::vector< CMatrix< C_FLOAT64 > > mVec_mImportanceIndexNormedRow
std::vector< CMatrix< C_FLOAT64 > > mVec_mParticipationIndex
std::vector< CMatrix< C_FLOAT64 > > mVec_mParticipationIndexNormedColumn
std::vector< CMatrix< C_FLOAT64 > > mVec_mParticipationIndexNormedRow
std::vector< CMatrix< C_FLOAT64 > > mVec_mRadicalPointer
std::vector< CMatrix< C_FLOAT64 > > mVec_mSlowParticipationIndex
CVectorCore< C_FLOAT64 > mY
CVector< C_FLOAT64 > mYerror
CDataArray * pFastParticipationIndexAnn
CDataArray * pFastReactionPointerAnn
CDataArray * pFastReactionPointerNormedAnn
CDataArray * pImportanceIndexAnn
CDataArray * pImportanceIndexNormedRowAnn
CDataArray * pParticipationIndexAnn
CDataArray * pParticipationIndexNormedColumnAnn
CDataArray * pParticipationIndexNormedRowAnn
CDataArray * pRadicalPointerAnn
CDataArray * pSlowParticipationIndexAnn
Protected Attributes inherited from CTSSAMethod
std::map< std::string, CDataArray * > mapTableToName
CVector< C_FLOAT64 > mCfast
C_FLOAT64 mConcentration2Number
CVectorCore< C_FLOAT64 > mContainerState
int mCurrentStep
std::vector< C_FLOAT64 > mCurrentTime
C_INT mDim
C_FLOAT64 mDtol
C_FLOAT64 mEPS
CMatrix< C_FLOAT64 > mJacobian
CMatrix< C_FLOAT64 > mJacobian_initial
C_FLOAT64 mNumber2Concentration
C_FLOAT64 * mpContainerStateTime
C_FLOAT64 * mpFirstSpecies
const C_FLOAT64 * mpFirstSpeciesRate
CLsodaMethod * mpLsodaMethod
CTSSAProblem * mpProblem
CMatrix< C_FLOAT64 > mQ
CMatrix< C_FLOAT64 > mQ_desc
CMatrix< C_FLOAT64 > mQz
CMatrix< C_FLOAT64 > mR
CMatrix< C_FLOAT64 > mR_desc
C_INT32 mSlow
CMatrix< C_FLOAT64 > mTd
CMatrix< C_FLOAT64 > mTd_save
CMatrix< C_FLOAT64 > mTdInverse
CMatrix< C_FLOAT64 > mTdInverse_save
std::vector< C_INT > mVec_SlowModes
std::vector< CVector< C_FLOAT64 > > mVec_TimeScale
CVector< C_FLOAT64 > mVfast_space
CMatrix< C_FLOAT64 > mVslow
CMatrix< C_FLOAT64 > mVslow_metab
CVector< C_FLOAT64 > mVslow_space
CVector< C_FLOAT64 > mY_cons
CVector< C_FLOAT64 > mY_initial
std::vector< std::string > tableNames
Protected Attributes inherited from CCopasiMethod
CMathContainer * mpContainer
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CCSPMethod ()
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Detailed Description
The CCSPMethod class implements the CSP method.
more information under: http://copasi.org/Support/User_Manual/Methods/Time_Scale_Separation_Methods/CSP/
Constructor & Destructor Documentation
CCSPMethod() [1/3]
CCSPMethod::CCSPMethod () private
Default constructor.
CCSPMethod() [2/3]
CCSPMethod::CCSPMethod (const CDataContainer * pParent, const CTaskEnum::Method & methodType = CTaskEnum::Method::tssCSP, const CTaskEnum::Task & taskType = CTaskEnum::Task::tssAnalysis)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Method & methodType (defaulf: tssCSP)
const CTaskEnum::Task & taskType (default: tssAnalysis)
References createAnnotationsM(), and initializeParameter().
CCSPMethod() [3/3]
CCSPMethod::CCSPMethod (const CCSPMethod & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CCSPMethod & src
const CDataContainer * pParent (default: NULL)
References createAnnotationsM(), and initializeParameter().
~CCSPMethod()
CCSPMethod::~CCSPMethod () virtual
Destructor.
Member Function Documentation
basisRefinement()
void CCSPMethod::basisRefinement (C_INT N, C_INT M, const CMatrix< C_FLOAT64 > & ALA, const CMatrix< C_FLOAT64 > & TAU, CMatrix< C_FLOAT64 > & A, CMatrix< C_FLOAT64 > & B, CMatrix< C_FLOAT64 > & A0, CMatrix< C_FLOAT64 > & B0) protected
Refinement Procedre : Lamm, Combustion Science and Technoligy, 1993.
References C_INT, and TAU.
Referenced by cspstep().
calculateJacobian()
void CCSPMethod::calculateJacobian (C_INT & n, CVector< C_FLOAT64 > & y, CMatrix< C_FLOAT64 > & J) protected
evaluate Jacobian for the current y
createAnnotationsM()
void CCSPMethod::createAnnotationsM () virtual
create the CArraAnnotations for every table in the CQTSSAResultSubWidget input for each CArraAnnotations is a seperate CMatrix
Create the CArraAnnotations for tables in the CQTSSAResultSubWidget. Input for each CArraAnnotations is a separate CMatrix.
Reimplemented from CTSSAMethod.
References CTSSAMethod::mapTableToName, mFastParticipationIndexTab, mFastReactionPointerNormedTab, mFastReactionPointerTab, mImportanceIndexNormedRowTab, mImportanceIndexTab, mParticipationIndexNormedColumnTab, mParticipationIndexNormedRowTab, mParticipationIndexTab, mRadicalPointerTab, mSlowParticipationIndexTab, pFastParticipationIndexAnn, pFastReactionPointerAnn, pFastReactionPointerNormedAnn, pImportanceIndexAnn, pImportanceIndexNormedRowAnn, pParticipationIndexAnn, pParticipationIndexNormedColumnAnn, pParticipationIndexNormedRowAnn, pRadicalPointerAnn, pSlowParticipationIndexAnn, CDataArray::setDescription(), CDataArray::setDimensionDescription(), CDataArray::setMode(), CDataArray::Strings, CTSSAMethod::tableNames, and CDataArray::Vector.
Referenced by CCSPMethod().
CSPImportanceIndex()
void CCSPMethod::CSPImportanceIndex (C_INT & N, C_FLOAT64 & tauM1, CMatrix< C_FLOAT64 > & Q) protected
compute CSP Importance Index
compute CSP Importance Index : a measure of relative importance of the contribution of r-th elementary reaction to the current reaction rate of the i-th species
References C_FLOAT64, C_INT, CMathContainer::getParticleFluxes(), CMathContainer::getReactions(), CMathContainer::getStoichiometry(), mImportanceIndex, mImportanceIndexNormedRow, CCopasiMethod::mpContainer, mReducedModel, mYerror, CMatrix< CType >::resize(), CVector< CType >::resize(), CVectorCore< CType >::size(), and smmult().
Referenced by cspstep().
CSPOutput()
void CCSPMethod::CSPOutput (C_INT & N, C_INT & M, C_INT & R)
CSP output
References CStateTemplate::beginIndependent(), C_INT, CMathContainer::getModel(), CDataObject::getObjectName(), CModel::getReactions(), CModel::getStateTemplate(), mAmplitude, mFastReactionPointer, mImportanceIndex, mParticipationIndex, CCopasiMethod::mpContainer, and mRadicalPointer.
Referenced by cspstep().
CSPParticipationIndex()
void CCSPMethod::CSPParticipationIndex (C_INT & N, C_INT & M, C_FLOAT64 & tauM1, CMatrix< C_FLOAT64 > & B0) protected
compute CSP Participation Index
compute CSP Participation Index: a measure of participation of the r-th elementary reaction to the balancing act of the i-th mode It is assumed that forward and reverse reactions are counted as distinct
References C_FLOAT64, C_INT, CMathContainer::getParticleFluxes(), CMathContainer::getReactions(), CMathContainer::getStoichiometry(), mFastParticipationIndex, mParticipationIndex, mParticipationIndexNormedColumn, mParticipationIndexNormedRow, CCopasiMethod::mpContainer, mReducedModel, mSlowParticipationIndex, mYerror, CMatrix< CType >::resize(), CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by cspstep().
CSPradicalPointer()
void CCSPMethod::CSPradicalPointer (C_INT & N, C_INT & M, CMatrix< C_FLOAT64 > & A, CMatrix< C_FLOAT64 > & B) protected
compute CSP radical pointer and fast reaction pointers
some comments on the Qm matrix: Qm(i,i) , i = 0,1,...,N, is a measure of projection of i-th unit vector in the m-th mode, whenever Qm(i,i) is not a small number, species m is said to be a CSP radical
Pmr is a measure of projection of r-th stoichiometric vector in the m-th mode, whenever Pmr is not a small number, the r-th reaction is said to be a fast reaction
References C_FLOAT64, C_INT, CMathContainer::getReactions(), CMathContainer::getStoichiometry(), mFastReactionPointer, mFastReactionPointerNormed, CCopasiMethod::mpContainer, mRadicalPointer, mReducedModel, CMatrix< CType >::resize(), and CVectorCore< CType >::size().
Referenced by cspstep().
cspstep()
void CCSPMethod::cspstep (const double & deltaT, C_INT & n, C_INT & m, CMatrix< C_FLOAT64 > & A, CMatrix< C_FLOAT64 > & B) protected
Start procedure of the CSP algorithm. S.H. Lam and D.A. Gaussis, International Journal of Chemical Kinetics, 26, pp. 461-486, 1994
compute CSP Participation Index: a measure of participation of the r-th elementary reaction to the balancing act of the i-th mode It is assumed that forward and reverse reactions are counted as distinct
compute CSP Importance Index : a measure of relative importance of the contribution of r-th elementary reaction to the current reaction rate of the i-th species
References CVectorCore< CType >::array(), basisRefinement(), C_FLOAT64, C_INT, CSPImportanceIndex(), CSPOutput(), CSPParticipationIndex(), CSPradicalPointer(), emptyOutputData(), findCandidatesNumber(), CMetab::getCompartment(), CMathObject::getDataObject(), CModelEntity::getInitialValue(), CMathContainer::getMathObject(), CDataObject::getObjectParent(), CMathContainer::getReactions(), isBlockDiagonal(), mAerror, mAmplitude, MCTSSAMethod, mG, mI, mIter, CTSSAMethod::mJacobian, CTSSAMethod::mJacobian_initial, modesAmplitude(), modesAreExhausted(), CCopasiMethod::mpContainer, CTSSAMethod::mpContainerStateTime, CTSSAMethod::mQ, CTSSAMethod::mR, mRerror, mY, mYerror, CMatrix< CType >::resize(), CVector< CType >::resize(), CTSSAMethod::schur(), CVectorCore< CType >::size(), sminverse(), smmult(), smnorm(), smsubst(), and CCopasiMessage::WARNING.
Referenced by step().
emptyOutputData()
void CCSPMethod::emptyOutputData (C_INT N, C_INT M, C_INT R) protected
CSP output : empty
References C_INT, mAmplitude, mFastParticipationIndex, mFastReactionPointer, mFastReactionPointerNormed, mImportanceIndex, mImportanceIndexNormedRow, mParticipationIndex, mParticipationIndexNormedColumn, mParticipationIndexNormedRow, mRadicalPointer, and mSlowParticipationIndex.
Referenced by cspstep().
emptyVectors()
void CCSPMethod::emptyVectors ()
empty every vector to be able to fill them with new values for a new calculation also nullify the step counter
Empty every vector to be able to fill them with new values for a new calculation. Also nullify the step counter.
References CTSSAMethod::mCurrentStep, CTSSAMethod::mCurrentTime, mVec_mFastParticipationIndex, mVec_mFastReactionPointer, mVec_mFastReactionPointerNormed, mVec_mImportanceIndex, mVec_mImportanceIndexNormedRow, mVec_mParticipationIndex, mVec_mParticipationIndexNormedColumn, mVec_mParticipationIndexNormedRow, mVec_mRadicalPointer, mVec_mSlowParticipationIndex, CTSSAMethod::mVec_SlowModes, and CTSSAMethod::mVec_TimeScale.
Referenced by start().
findCandidatesNumber()
void CCSPMethod::findCandidatesNumber (C_INT & n, C_INT & k, CVector< C_FLOAT64 > & tsc, C_INT & info) protected
find the number of candidates to fast according to the time-scale separation ratio
References C_FLOAT64, C_INT, and mEps.
Referenced by cspstep().
findTimeScaleSeparation()
void CCSPMethod::findTimeScaleSeparation (C_INT & n, C_INT & k, CVector< C_FLOAT64 > & tsc, C_INT & info) protected
find the new number of fast according to the time-scale separation ratio
getFastParticipationIndexAnn()
const CDataArray * CCSPMethod::getFastParticipationIndexAnn () const
References pFastParticipationIndexAnn.
getFastReactionPointerAnn()
const CDataArray * CCSPMethod::getFastReactionPointerAnn () const
References pFastReactionPointerAnn.
getFastReactionPointerNormedAnn()
const CDataArray * CCSPMethod::getFastReactionPointerNormedAnn () const
References pFastReactionPointerNormedAnn.
getImportanceIndexAnn()
const CDataArray * CCSPMethod::getImportanceIndexAnn () const
References pImportanceIndexAnn.
getImportanceIndexNormedRowAnn()
const CDataArray * CCSPMethod::getImportanceIndexNormedRowAnn () const
References pImportanceIndexNormedRowAnn.
getParticipationIndexAnn()
const CDataArray * CCSPMethod::getParticipationIndexAnn () const
References pParticipationIndexAnn.
getParticipationIndexNormedColumnAnn()
const CDataArray * CCSPMethod::getParticipationIndexNormedColumnAnn () const
References pParticipationIndexNormedColumnAnn.
getParticipationIndexNormedRowAnn()
const CDataArray * CCSPMethod::getParticipationIndexNormedRowAnn () const
References pParticipationIndexNormedRowAnn.
getRadicalPointerAnn()
const CDataArray * CCSPMethod::getRadicalPointerAnn () const
return CArrayAnnotation for visualization in the CQTSSAResultSubWidget
References pRadicalPointerAnn.
getSlowParticipationIndexAnn()
const CDataArray * CCSPMethod::getSlowParticipationIndexAnn () const
References pSlowParticipationIndexAnn.
initializeOutput()
void CCSPMethod::initializeOutput () virtual
initialize output for the result elements, this method initializes the output elements so that an output handler can be used afterwards
Predefine the CArrayAnnotation for plots
Reimplemented from CTSSAMethod.
References CDataVector< CType >::add(), CStateTemplate::beginIndependent(), CMathContainer::getModel(), CModel::getNumDependentReactionMetabs(), CModel::getNumIndependentReactionMetabs(), CModel::getReactions(), CModel::getStateTemplate(), mFastParticipationIndexTab, mImportanceIndexTab, CCopasiMethod::mpContainer, mReducedModel, mSlowParticipationIndexTab, pFastParticipationIndexAnn, pImportanceIndexAnn, pSlowParticipationIndexAnn, CDataArray::resize(), CMatrix< CType >::resize(), CDataArray::setAnnotationString(), CDataArray::setCopasiVector(), and CDataVector< CType >::size().
initializeParameter()
void CCSPMethod::initializeParameter () virtual
Intialize the method parameter
Reimplemented from CTSSAMethod.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CTSSAMethod::initializeParameter(), CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CCSPMethod().
isBlockDiagonal()
C_INT CCSPMethod::isBlockDiagonal (C_INT N, C_INT M, const CMatrix< C_FLOAT64 > & ALA, const C_FLOAT64 & SMALL) protected
compute the norm C of the off-diagonal blocks
References C_FLOAT64, C_INT, and max.
Referenced by cspstep().
modesAmplitude()
void CCSPMethod::modesAmplitude (C_INT N, const CVector< C_FLOAT64 > & g, const CMatrix< C_FLOAT64 > & B, CMatrix< C_FLOAT64 > & F) protected
compute amplitudes of fast and slow modes
References C_INT.
Referenced by cspstep(), and modesAreExhausted().
modesAreExhausted()
bool CCSPMethod::modesAreExhausted (C_INT N, C_INT M, C_FLOAT64 & tauM, C_FLOAT64 & tauM1, CVector< C_FLOAT64 > & g, const CMatrix< C_FLOAT64 > & A, const CMatrix< C_FLOAT64 > & B, CMatrix< C_FLOAT64 > & F) protected
check : whether each of the analysed M modes is exhausted
References C_FLOAT64, C_INT, modesAmplitude(), and mYerror.
Referenced by cspstep().
printResult()
void CCSPMethod::printResult (std::ostream * ostream) const virtual
print of the standart report sequence for ILDM Method
Parameters
std::ostream * ostream
Reimplemented from CCopasiMethod.
References CStateTemplate::beginIndependent(), C_INT, C_INT32, CMathContainer::getModel(), CDataObject::getObjectName(), CModel::getReactions(), CModel::getStateTemplate(), CTSSAMethod::getTimeForStep(), CModel::getTimeUnitName(), CTSSAMethod::mDim, CCopasiMethod::mpContainer, mVec_mImportanceIndex, mVec_mParticipationIndex, mVec_mRadicalPointer, CTSSAMethod::mVec_SlowModes, CTSSAMethod::mVec_TimeScale, and CDataVector< CType >::size().
setAnnotationM()
bool CCSPMethod::setAnnotationM (size_t step) virtual
set the every CArrayAnnotation for the requested step set the desription of CArayAnnotation for both dimensions
Set the every CArrayAnnotation for the requested step. Set also the description of CArayAnnotation for both dimensions:
dimension description could consists of some std::strings some strings contain the Time Scale values for requested step
dimension description could consists of arrays of CommonNames
Implements CTSSAMethod.
References CDataVector< CType >::add(), CStateTemplate::beginIndependent(), C_INT32, CMathContainer::getModel(), CModel::getNumDependentReactionMetabs(), CModel::getNumIndependentReactionMetabs(), CModel::getReactions(), CModel::getStateTemplate(), CTSSAMethod::mDim, mFastParticipationIndexTab, mFastReactionPointerNormedTab, mFastReactionPointerTab, mImportanceIndexNormedRowTab, mImportanceIndexTab, mParticipationIndexNormedColumnTab, mParticipationIndexNormedRowTab, mParticipationIndexTab, CCopasiMethod::mpContainer, mRadicalPointerTab, mReducedModel, mSlowParticipationIndexTab, mVec_mFastParticipationIndex, mVec_mFastReactionPointer, mVec_mFastReactionPointerNormed, mVec_mImportanceIndex, mVec_mImportanceIndexNormedRow, mVec_mParticipationIndex, mVec_mParticipationIndexNormedColumn, mVec_mParticipationIndexNormedRow, mVec_mRadicalPointer, mVec_mSlowParticipationIndex, CTSSAMethod::mVec_SlowModes, CTSSAMethod::mVec_TimeScale, pFastParticipationIndexAnn, pFastReactionPointerAnn, pFastReactionPointerNormedAnn, pImportanceIndexAnn, pImportanceIndexNormedRowAnn, pParticipationIndexAnn, pParticipationIndexNormedColumnAnn, pParticipationIndexNormedRowAnn, pRadicalPointerAnn, pSlowParticipationIndexAnn, CDataArray::resize(), CMatrix< CType >::resize(), CDataArray::setAnnotationString(), CDataArray::setCopasiVector(), CDataVector< CType >::size(), and step().
Referenced by step().
setVectors()
void CCSPMethod::setVectors (int fast)
upgrade all vectors with values from actually calculalion for current step
upgrade all vectors with values from actually calculation for current step
References C_INT, CMathContainer::getReactions(), CTSSAMethod::mCurrentStep, CTSSAMethod::mDim, mFastParticipationIndex, mFastReactionPointer, mFastReactionPointerNormed, mImportanceIndex, mImportanceIndexNormedRow, mParticipationIndex, mParticipationIndexNormedColumn, mParticipationIndexNormedRow, CCopasiMethod::mpContainer, CTSSAMethod::mR, mRadicalPointer, mSlowParticipationIndex, mVec_mFastParticipationIndex, mVec_mFastReactionPointer, mVec_mFastReactionPointerNormed, mVec_mImportanceIndex, mVec_mImportanceIndexNormedRow, mVec_mParticipationIndex, mVec_mParticipationIndexNormedColumn, mVec_mParticipationIndexNormedRow, mVec_mRadicalPointer, mVec_mSlowParticipationIndex, CTSSAMethod::mVec_SlowModes, CTSSAMethod::mVec_TimeScale, and CVectorCore< CType >::size().
Referenced by step().
setVectorsToNaN()
void CCSPMethod::setVectorsToNaN ()
set vectors to NaN when the reduction was not possible
References C_INT, CMathContainer::getReactions(), CTSSAMethod::mCurrentStep, CTSSAMethod::mDim, CCopasiMethod::mpContainer, CTSSAMethod::mR, mVec_mFastParticipationIndex, mVec_mFastReactionPointer, mVec_mFastReactionPointerNormed, mVec_mImportanceIndex, mVec_mImportanceIndexNormedRow, mVec_mParticipationIndex, mVec_mParticipationIndexNormedColumn, mVec_mParticipationIndexNormedRow, mVec_mRadicalPointer, mVec_mSlowParticipationIndex, CTSSAMethod::mVec_SlowModes, CTSSAMethod::mVec_TimeScale, and CVectorCore< CType >::size().
Referenced by step().
smadd()
void CCSPMethod::smadd (const CMatrix< C_FLOAT64 > & A, const CMatrix< C_FLOAT64 > & B, CMatrix< C_FLOAT64 > & C, C_INT n1, C_INT n2) protected
Addition of submatrix
References C_INT.
sminverse()
void CCSPMethod::sminverse (C_INT n, const CMatrix< C_FLOAT64 > & A, CMatrix< C_FLOAT64 > & B) protected
Inverse submatrix
References CMatrix< CType >::array(), C_INT, and dgesv_().
Referenced by cspstep().
smmult()
void CCSPMethod::smmult (const CMatrix< C_FLOAT64 > & A, const CMatrix< C_FLOAT64 > & B, CMatrix< C_FLOAT64 > & C, C_INT n1, C_INT n2, C_INT n3) protected
CSP related staff Multiplication of submatrix
References C_INT.
Referenced by CSPImportanceIndex(), cspstep(), and yCorrection().
smnorm()
void CCSPMethod::smnorm (C_INT n, CMatrix< C_FLOAT64 > & A, CMatrix< C_FLOAT64 > & B, C_INT n1) protected
Normalize submatrix
References C_FLOAT64, and C_INT.
Referenced by cspstep().
smsubst()
void CCSPMethod::smsubst (const CMatrix< C_FLOAT64 > & A, const CMatrix< C_FLOAT64 > & B, CMatrix< C_FLOAT64 > & C, C_INT n1, C_INT n2) protected
Substruction of submatrix
References C_INT.
Referenced by cspstep().
start()
void CCSPMethod::start () virtual
This instructs the method to prepare for integration starting with the initialState given.
Reimplemented from CTSSAMethod.
References C_INT, emptyVectors(), CMathContainer::getCountDependentSpecies(), CMathContainer::getModel(), CModel::getNumber2QuantityFactor(), CMathContainer::getReactions(), CVectorCore< CType >::initialize(), CTSSAMethod::integrationMethodStart(), mAerror, mAmplitude, mB, mCSPbasis, CTSSAMethod::mDim, mEps, mFastParticipationIndex, mFastParticipationIndexTab, mFastReactionPointer, mFastReactionPointerNormed, mG, mI, mImportanceIndex, mImportanceIndexNormedRow, mImportanceIndexTab, mIter, mParticipationIndex, mParticipationIndexNormedColumn, mParticipationIndexNormedRow, CCopasiMethod::mpContainer, CTSSAMethod::mpFirstSpecies, CTSSAMethod::mpFirstSpeciesRate, CTSSAMethod::mpLsodaMethod, mRadicalPointer, mReducedModel, mRerror, mSetVectors, mSlowParticipationIndex, mSlowParticipationIndexTab, mTStep, mVec_mFastParticipationIndex, mVec_mImportanceIndex, mVec_mSlowParticipationIndex, mY, mYerror, pFastParticipationIndexAnn, pImportanceIndexAnn, pSlowParticipationIndexAnn, CDataArray::resize(), CDataVector< CType >::resize(), CMatrix< CType >::resize(), CVector< CType >::resize(), CDataArray::setCopasiVector(), CCopasiParameterGroup::setValue(), CVectorCore< CType >::size(), CTSSAMethod::start(), and CMathContainer::updateSimulatedValues().
step()
void CCSPMethod::step (const double & deltaT) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
Reimplemented from CTSSAMethod.
References C_INT, CMathContainer::calculateJacobian(), cspstep(), CTSSAMethod::integrationStep(), mB, CTSSAMethod::mCurrentStep, CTSSAMethod::mDim, CTSSAMethod::mJacobian, CCopasiMethod::mpContainer, mReducedModel, mTStep, CMatrix< CType >::resize(), setAnnotationM(), setVectors(), setVectorsToNaN(), CTSSAMethod::updateCurrentTime(), and CMathContainer::updateSimulatedValues().
Referenced by setAnnotationM().
yCorrection()
void CCSPMethod::yCorrection (C_INT & N, C_INT & M, CVector< C_FLOAT64 > & y, CMatrix< C_FLOAT64 > & TAUM, CMatrix< C_FLOAT64 > & F, CMatrix< C_FLOAT64 > & A) protected
correct for the contribution of the fast time-scales to y
References C_INT, CMatrix< CType >::resize(), CVector< CType >::resize(), and smmult().
Member Data Documentation
mAerror
C_FLOAT64 CCSPMethod::mAerror protected
A maximux absolute error
Referenced by cspstep(), and start().
mAmplitude
CVector<C_FLOAT64> CCSPMethod::mAmplitude protected
Amplitudes of reaction modes (column vector);
Referenced by CSPOutput(), cspstep(), emptyOutputData(), and start().
mB
CMatrix<C_FLOAT64> CCSPMethod::mB protected
The basis vectors B from the time step (T - delta T)
Referenced by start(), and step().
mCSPbasis
C_INT CCSPMethod::mCSPbasis protected
indicates whether the basis vectors B were computed on the time step (T - delta T)
Referenced by start().
mEps
C_FLOAT64 CCSPMethod::mEps protected
A value related to a measure of the time scale separation of the fast and slow modes
Referenced by findCandidatesNumber(), and start().
mFastParticipationIndex
CVector<C_FLOAT64> CCSPMethod::mFastParticipationIndex protected
Referenced by CSPParticipationIndex(), emptyOutputData(), setVectors(), and start().
mFastParticipationIndexTab
CMatrix<C_FLOAT64> CCSPMethod::mFastParticipationIndexTab protected
Referenced by createAnnotationsM(), initializeOutput(), setAnnotationM(), and start().
mFastReactionPointer
CMatrix<C_FLOAT64> CCSPMethod::mFastReactionPointer protected
Fast Reaction Pointer of the m-th reaction mode : whenever is not a small number, the r-th reaction is said to be a fast reaction
Referenced by CSPOutput(), CSPradicalPointer(), emptyOutputData(), setVectors(), and start().
mFastReactionPointerNormed
CMatrix<C_FLOAT64> CCSPMethod::mFastReactionPointerNormed protected
Referenced by CSPradicalPointer(), emptyOutputData(), setVectors(), and start().
mFastReactionPointerNormedTab
CMatrix<C_FLOAT64> CCSPMethod::mFastReactionPointerNormedTab protected
Referenced by createAnnotationsM(), and setAnnotationM().
mFastReactionPointerTab
CMatrix<C_FLOAT64> CCSPMethod::mFastReactionPointerTab protected
Referenced by createAnnotationsM(), and setAnnotationM().
mG
CVectorCore< const C_FLOAT64 > CCSPMethod::mG protected
A vector of the current right hand side
Referenced by cspstep(), and start().
mI
CMatrix<C_FLOAT64> CCSPMethod::mI protected
Unit matrix
Referenced by cspstep(), and start().
mImportanceIndex
CMatrix<C_FLOAT64> CCSPMethod::mImportanceIndex protected
Importance Index: is a measure of relative importance of the contribution of r-th elementary reaction to the current reaction rate of i-th species
Referenced by CSPImportanceIndex(), CSPOutput(), emptyOutputData(), setVectors(), and start().
mImportanceIndexNormedRow
CMatrix<C_FLOAT64> CCSPMethod::mImportanceIndexNormedRow protected
Referenced by CSPImportanceIndex(), emptyOutputData(), setVectors(), and start().
mImportanceIndexNormedRowTab
CMatrix<C_FLOAT64> CCSPMethod::mImportanceIndexNormedRowTab protected
Referenced by createAnnotationsM(), and setAnnotationM().
mImportanceIndexTab
CMatrix<C_FLOAT64> CCSPMethod::mImportanceIndexTab protected
Referenced by createAnnotationsM(), initializeOutput(), setAnnotationM(), and start().
mIter
C_INT CCSPMethod::mIter protected
Max number of the refinement iterations
Referenced by cspstep(), and start().
mParticipationIndex
CMatrix<C_FLOAT64> CCSPMethod::mParticipationIndex protected
Participation Index : is a mesure of participation of the r-th elementary reaction to the balancing act of the i-th mode (matrix)
Referenced by CSPOutput(), CSPParticipationIndex(), emptyOutputData(), setVectors(), and start().
mParticipationIndexNormedColumn
CMatrix<C_FLOAT64> CCSPMethod::mParticipationIndexNormedColumn protected
Referenced by CSPParticipationIndex(), emptyOutputData(), setVectors(), and start().
mParticipationIndexNormedColumnTab
CMatrix<C_FLOAT64> CCSPMethod::mParticipationIndexNormedColumnTab protected
Referenced by createAnnotationsM(), and setAnnotationM().
mParticipationIndexNormedRow
CMatrix<C_FLOAT64> CCSPMethod::mParticipationIndexNormedRow protected
Referenced by CSPParticipationIndex(), emptyOutputData(), setVectors(), and start().
mParticipationIndexNormedRowTab
CMatrix<C_FLOAT64> CCSPMethod::mParticipationIndexNormedRowTab protected
Referenced by createAnnotationsM(), and setAnnotationM().
mParticipationIndexTab
CMatrix<C_FLOAT64> CCSPMethod::mParticipationIndexTab protected
Referenced by createAnnotationsM(), and setAnnotationM().
mRadicalPointer
CMatrix<C_FLOAT64> CCSPMethod::mRadicalPointer protected
Radical Pointer: whenever is not a small number, species k is said to be CSP radical
Referenced by CSPOutput(), CSPradicalPointer(), emptyOutputData(), setVectors(), and start().
mRadicalPointerTab
CMatrix<C_FLOAT64> CCSPMethod::mRadicalPointerTab protected
input for every CArraAnnotations contain data for single stepcalculation
Referenced by createAnnotationsM(), and setAnnotationM().
mReducedModel
bool CCSPMethod::mReducedModel protected
CSP related staff
Referenced by CSPImportanceIndex(), CSPParticipationIndex(), CSPradicalPointer(), initializeOutput(), setAnnotationM(), start(), and step().
mRerror
C_FLOAT64 CCSPMethod::mRerror protected
A maximux relative error
Referenced by cspstep(), and start().
mSetVectors
C_INT CCSPMethod::mSetVectors protected
CSP Output
Referenced by start().
mSlowParticipationIndex
CVector<C_FLOAT64> CCSPMethod::mSlowParticipationIndex protected
Referenced by CSPParticipationIndex(), emptyOutputData(), setVectors(), and start().
mSlowParticipationIndexTab
CMatrix<C_FLOAT64> CCSPMethod::mSlowParticipationIndexTab protected
Referenced by createAnnotationsM(), initializeOutput(), setAnnotationM(), and start().
mTsc
C_FLOAT64 CCSPMethod::mTsc protected
An alternative value related to a mesure of the time scale separation of the fast and slow modes
mTStep
C_INT CCSPMethod::mTStep protected
Referenced by start(), and step().
mVec_mFastParticipationIndex
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mFastParticipationIndex protected
Referenced by emptyVectors(), setAnnotationM(), setVectors(), setVectorsToNaN(), and start().
mVec_mFastReactionPointer
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mFastReactionPointer protected
Referenced by emptyVectors(), setAnnotationM(), setVectors(), and setVectorsToNaN().
mVec_mFastReactionPointerNormed
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mFastReactionPointerNormed protected
Referenced by emptyVectors(), setAnnotationM(), setVectors(), and setVectorsToNaN().
mVec_mImportanceIndex
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mImportanceIndex protected
Referenced by emptyVectors(), printResult(), setAnnotationM(), setVectors(), setVectorsToNaN(), and start().
mVec_mImportanceIndexNormedRow
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mImportanceIndexNormedRow protected
Referenced by emptyVectors(), setAnnotationM(), setVectors(), and setVectorsToNaN().
mVec_mParticipationIndex
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mParticipationIndex protected
Referenced by emptyVectors(), printResult(), setAnnotationM(), setVectors(), and setVectorsToNaN().
mVec_mParticipationIndexNormedColumn
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mParticipationIndexNormedColumn protected
Referenced by emptyVectors(), setAnnotationM(), setVectors(), and setVectorsToNaN().
mVec_mParticipationIndexNormedRow
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mParticipationIndexNormedRow protected
Referenced by emptyVectors(), setAnnotationM(), setVectors(), and setVectorsToNaN().
mVec_mRadicalPointer
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mRadicalPointer protected
vectors contain whole data for all calculation steps
Referenced by emptyVectors(), printResult(), setAnnotationM(), setVectors(), and setVectorsToNaN().
mVec_mSlowParticipationIndex
std::vector< CMatrix<C_FLOAT64> > CCSPMethod::mVec_mSlowParticipationIndex protected
Referenced by emptyVectors(), setAnnotationM(), setVectors(), setVectorsToNaN(), and start().
mY
CVectorCore< C_FLOAT64 > CCSPMethod::mY protected
Referenced by cspstep(), and start().
mYerror
CVector<C_FLOAT64> CCSPMethod::mYerror protected
An error vector build on the basis of the solution vector
Referenced by CSPImportanceIndex(), CSPParticipationIndex(), cspstep(), modesAreExhausted(), and start().
pFastParticipationIndexAnn
CDataArray* CCSPMethod::pFastParticipationIndexAnn protected
Referenced by createAnnotationsM(), getFastParticipationIndexAnn(), initializeOutput(), setAnnotationM(), and start().
pFastReactionPointerAnn
CDataArray* CCSPMethod::pFastReactionPointerAnn protected
Referenced by createAnnotationsM(), getFastReactionPointerAnn(), and setAnnotationM().
pFastReactionPointerNormedAnn
CDataArray* CCSPMethod::pFastReactionPointerNormedAnn protected
Referenced by createAnnotationsM(), getFastReactionPointerNormedAnn(), and setAnnotationM().
pImportanceIndexAnn
CDataArray* CCSPMethod::pImportanceIndexAnn protected
Referenced by createAnnotationsM(), getImportanceIndexAnn(), initializeOutput(), setAnnotationM(), and start().
pImportanceIndexNormedRowAnn
CDataArray* CCSPMethod::pImportanceIndexNormedRowAnn protected
Referenced by createAnnotationsM(), getImportanceIndexNormedRowAnn(), and setAnnotationM().
pParticipationIndexAnn
CDataArray* CCSPMethod::pParticipationIndexAnn protected
Referenced by createAnnotationsM(), getParticipationIndexAnn(), and setAnnotationM().
pParticipationIndexNormedColumnAnn
CDataArray* CCSPMethod::pParticipationIndexNormedColumnAnn protected
Referenced by createAnnotationsM(), getParticipationIndexNormedColumnAnn(), and setAnnotationM().
pParticipationIndexNormedRowAnn
CDataArray* CCSPMethod::pParticipationIndexNormedRowAnn protected
Referenced by createAnnotationsM(), getParticipationIndexNormedRowAnn(), and setAnnotationM().
pRadicalPointerAnn
CDataArray* CCSPMethod::pRadicalPointerAnn protected
CArraAnnotations for CQTSSAResultSubWidget
Referenced by createAnnotationsM(), getRadicalPointerAnn(), and setAnnotationM().
pSlowParticipationIndexAnn
CDataArray* CCSPMethod::pSlowParticipationIndexAnn protected
Referenced by createAnnotationsM(), getSlowParticipationIndexAnn(), initializeOutput(), setAnnotationM(), and start().
The documentation for this class was generated from the following files:
CCSPMethod.h
CCSPMethod.cpp