COPASI API: SedmlInfo Class Reference
SedmlInfo Class Reference
#include <SEDMLUtils.h>
Public Member Functions
std::string getFirstModel (const std::string &taskId="")
std::string getFirstReport (const std::string &taskId)
std::string getFirstTaskWithOutput ()
std::set< std::string > getModelForDataGen (SedDataGenerator *dg)
std::set< std::string > getModelForTask (const std::string &taskId)
std::set< std::string > getModelForTask (SedAbstractTask *task)
std::vector< std::pair< std::string, std::string > > getPlotsForTask (const std::string &taskId)
std::string getReportFileName (const std::string &reportId)
std::vector< std::pair< std::string, std::string > > getReportsForTask (const std::string &taskId)
std::vector< std::pair< std::string, std::string > > getTaskNames ()
std::set< std::string > getTasks (const std::string &dgId)
std::set< std::string > getTasks (SedAbstractCurve *curve)
std::set< std::string > getTasks (SedDataGenerator *dg)
std::set< std::string > getTasks (SedOutput *output)
std::set< std::string > getTasks (SedSurface *surface)
bool hasOutputs (const std::string &taskId)
bool isComplex ()
bool isRecursiveWithoutOutputs (SedAbstractTask *task)
bool isSupported ()
SedmlInfo (SedDocument *pDocument, bool ownDocument=false)
void setReportFileName (const std::string &reportId, const std::string &fileName)
~SedmlInfo ()
Static Public Member Functions
static void addSets (std::set< std::string > &target, const std::set< std::string > &source)
static SedmlInfo forArchive (const std::string &fileName)
static SedmlInfo forFile (const std::string &fileName)
Private Attributes
bool mComplex
std::map< std::string, std::string > mFileNames
std::vector< std::string > mMessages
std::map< std::string, std::set< std::string > > mOutputMap
bool mOwnDocument
SedDocument * mpDocument
std::map< std::string, std::vector< std::pair< std::string, std::string > > > mPlots
std::map< std::string, std::vector< std::pair< std::string, std::string > > > mReports
bool mSupported
std::map< std::string, std::set< std::string > > mTaskMap
std::vector< std::pair< std::string, std::string > > mTaskNames
Detailed Description
Utility class describing the SEDML document
Constructor & Destructor Documentation
SedmlInfo()
SedmlInfo::SedmlInfo (SedDocument * pDocument, bool ownDocument = false)
References getModelForTask(), getTasks(), isRecursiveWithoutOutputs(), mComplex, mOutputMap, mPlots, mReports, mTaskMap, and mTaskNames.
Referenced by forArchive(), and forFile().
~SedmlInfo()
SedmlInfo::~SedmlInfo ()
References mOwnDocument, mpDocument, and pdelete.
Member Function Documentation
addSets()
void SedmlInfo::addSets (std::set< std::string > & target, const std::set< std::string > & source) static
Referenced by getModelForDataGen(), getModelForTask(), and getTasks().
forArchive()
SedmlInfo SedmlInfo::forArchive (const std::string & fileName) static
References SEDMLUtils::getSedMLStringForArchive(), and SedmlInfo().
forFile()
SedmlInfo SedmlInfo::forFile (const std::string & fileName) static
References SedmlInfo().
getFirstModel()
std::string SedmlInfo::getFirstModel (const std::string & taskId = "")
References mTaskMap.
getFirstReport()
std::string SedmlInfo::getFirstReport (const std::string & taskId)
References mReports.
getFirstTaskWithOutput()
std::string SedmlInfo::getFirstTaskWithOutput ()
References mOutputMap.
getModelForDataGen()
std::set< std::string > SedmlInfo::getModelForDataGen (SedDataGenerator * dg)
References addSets(), and getModelForTask().
getModelForTask() [1/2]
std::set< std::string > SedmlInfo::getModelForTask (const std::string & taskId)
References getModelForTask(), and mpDocument.
getModelForTask() [2/2]
std::set< std::string > SedmlInfo::getModelForTask (SedAbstractTask * task)
References addSets(), and mTaskMap.
Referenced by getModelForDataGen(), getModelForTask(), and SedmlInfo().
getPlotsForTask()
std::vector< std::pair< std::string, std::string > > SedmlInfo::getPlotsForTask (const std::string & taskId)
References mPlots.
getReportFileName()
std::string SedmlInfo::getReportFileName (const std::string & reportId)
References mFileNames.
getReportsForTask()
std::vector< std::pair< std::string, std::string > > SedmlInfo::getReportsForTask (const std::string & taskId)
References mReports.
getTaskNames()
std::vector< std::pair< std::string, std::string > > SedmlInfo::getTaskNames ()
References mTaskNames.
getTasks() [1/5]
std::set< std::string > SedmlInfo::getTasks (const std::string & dgId)
References mpDocument.
Referenced by getTasks(), and SedmlInfo().
getTasks() [2/5]
std::set< std::string > SedmlInfo::getTasks (SedAbstractCurve * curve)
References addSets(), and getTasks().
getTasks() [3/5]
std::set< std::string > SedmlInfo::getTasks (SedDataGenerator * dg)
getTasks() [4/5]
std::set< std::string > SedmlInfo::getTasks (SedOutput * output)
References addSets(), and getTasks().
getTasks() [5/5]
std::set< std::string > SedmlInfo::getTasks (SedSurface * surface)
References addSets(), and getTasks().
hasOutputs()
bool SedmlInfo::hasOutputs (const std::string & taskId)
References mPlots, and mReports.
Referenced by isRecursiveWithoutOutputs().
isComplex()
bool SedmlInfo::isComplex ()
Returns
true, if the document is complex (> 1 model, multiple tasks of the same type) requiring the user to choose which one to import.
References mComplex.
isRecursiveWithoutOutputs()
bool SedmlInfo::isRecursiveWithoutOutputs (SedAbstractTask * task)
References hasOutputs().
Referenced by SedmlInfo().
isSupported()
bool SedmlInfo::isSupported ()
References mSupported.
setReportFileName()
void SedmlInfo::setReportFileName (const std::string & reportId, const std::string & fileName)
References mFileNames.
Member Data Documentation
mComplex
bool SedmlInfo::mComplex private
Referenced by isComplex(), and SedmlInfo().
mFileNames
std::map< std::string, std::string > SedmlInfo::mFileNames private
Referenced by getReportFileName(), and setReportFileName().
mMessages
std::vector< std::string > SedmlInfo::mMessages private
mOutputMap
std::map< std::string, std::set< std::string > > SedmlInfo::mOutputMap private
Referenced by getFirstTaskWithOutput(), and SedmlInfo().
mOwnDocument
bool SedmlInfo::mOwnDocument private
Referenced by ~SedmlInfo().
mpDocument
SedDocument* SedmlInfo::mpDocument private
Referenced by getModelForTask(), getTasks(), and ~SedmlInfo().
mPlots
std::map< std::string, std::vector< std::pair< std::string, std::string > > > SedmlInfo::mPlots private
Referenced by getPlotsForTask(), hasOutputs(), and SedmlInfo().
mReports
std::map< std::string, std::vector< std::pair< std::string, std::string > > > SedmlInfo::mReports private
Referenced by getFirstReport(), getReportsForTask(), hasOutputs(), and SedmlInfo().
mSupported
bool SedmlInfo::mSupported private
Referenced by isSupported().
mTaskMap
std::map< std::string, std::set< std::string > > SedmlInfo::mTaskMap private
Referenced by getFirstModel(), getModelForTask(), and SedmlInfo().
mTaskNames
std::vector< std::pair< std::string, std::string > > SedmlInfo::mTaskNames private
Referenced by getTaskNames(), and SedmlInfo().
The documentation for this class was generated from the following files:
SEDMLUtils.h
SEDMLUtils.cpp