COPASI API: CRadau5.cpp File Reference
CRadau5.cpp File Reference
#include <cmath>
#include "copasi/copasi.h"
#include "CRadau5.h"
#include "Cxerrwd.h"
#include "CInternalSolver.h"
#include "common.h"
Macros
#define conra5_1 conra5_
#define linal_1 linal_
Functions
double contr5_ (C_INT *i__, double *x, double *cont, C_INT *lrc)
double d_sign (double *a, double *b)
int radcor_ (C_INT *n, CRadau5::evalF fcn, double *x, double *y, double *xend, double *hmax, double *h__, double *rtol, double *atol, C_INT *itol, CRadau5::evalJ jac, C_INT *ijac, C_INT *mljac, C_INT *mujac, CRadau5::evalM mas, C_INT *mlmas, C_INT *mumas, CRadau5::evalO solout, C_INT *iout, C_INT *idid, C_INT *nmax, double *uround, double *safe, double *thet, double *fnewt, double *quot1, double *quot2, C_INT *nit, C_INT *ijob, C_LOGICAL *startn, C_INT *nind1, C_INT *nind2, C_INT *nind3, C_LOGICAL *pred, double *facl, double *facr, C_INT *m1, C_INT *m2, C_INT *nm1, C_LOGICAL *implct, C_LOGICAL *banded, C_INT *ldjac, C_INT *lde1, C_INT *ldmas, double *z1, double *z2, double *z3, double *y0, double *scal, double *f1, double *f2, double *f3, double *fjac, double *e1, double *e2r, double *e2i, double *fmas, C_INT *ip1, C_INT *ip2, C_INT *iphes, double *cont, C_INT *nfcn, C_INT *njac, C_INT *nstep, C_INT *naccpt, C_INT *nrejct, C_INT *ndec, C_INT *nsol, double *rpar, C_INT *ipar)
Variables
struct {
double c1m1
double c2m1
double hsol
C_INT nn
C_INT nn2
C_INT nn3
C_INT nn4
double xsol
} conra5_
struct {
C_INT mbb
C_INT mbdiag
C_INT mbjac
C_INT mdiag
C_INT mdiff
C_INT mle
C_INT mue
} linal_
Macro Definition Documentation
conra5_1
#define conra5_1 conra5_
linal_1
#define linal_1 linal_
Function Documentation
contr5_()
double contr5_ (C_INT * i__, double * x, double * cont, C_INT * lrc)
References conra5_1.
d_sign()
double d_sign (double * a, double * b)
radcor_()
int radcor_ (C_INT * n, CRadau5::evalF fcn, double * x, double * y, double * xend, double * hmax, double * h__, double * rtol, double * atol, C_INT * itol, CRadau5::evalJ jac, C_INT * ijac, C_INT * mljac, C_INT * mujac, CRadau5::evalM mas, C_INT * mlmas, C_INT * mumas, CRadau5::evalO solout, C_INT * iout, C_INT * idid, C_INT * nmax, double * uround, double * safe, double * thet, double * fnewt, double * quot1, double * quot2, C_INT * nit, C_INT * ijob, C_LOGICAL * startn, C_INT * nind1, C_INT * nind2, C_INT * nind3, C_LOGICAL * pred, double * facl, double * facr, C_INT * m1, C_INT * m2, C_INT * nm1, C_LOGICAL * implct, C_LOGICAL * banded, C_INT * ldjac, C_INT * lde1, C_INT * ldmas, double * z1, double * z2, double * z3, double * y0, double * scal, double * f1, double * f2, double * f3, double * fjac, double * e1, double * e2r, double * e2i, double * fmas, C_INT * ip1, C_INT * ip2, C_INT * iphes, double * cont, C_INT * nfcn, C_INT * njac, C_INT * nstep, C_INT * naccpt, C_INT * nrejct, C_INT * ndec, C_INT * nsol, double * rpar, C_INT * ipar)
References C_INT, C_LOGICAL, conra5_1, decomc_(), decomr_(), estrad_(), and slvrad_().
Referenced by CRadau5::operator()().
Variable Documentation
c1m1
double c1m1
c2m1
double c2m1
struct { ... } conra5_
hsol
double hsol
struct { ... } linal_
mbb
C_INT mbb
mbdiag
C_INT mbdiag
mbjac
C_INT mbjac
mdiag
C_INT mdiag
mdiff
C_INT mdiff
mle
C_INT mle
mue
C_INT mue
nn
C_INT nn
Referenced by dq7apl_(), dq7rad_(), and drn2gb_().
nn2
C_INT nn2
nn3
C_INT nn3
nn4
C_INT nn4
xsol
double xsol