COPASI API: CStochasticRungeKuttaRI5 Class Reference
CStochasticRungeKuttaRI5 Class Reference
#include <CStochasticRungeKuttaRI5.h>
Public Member Functions
CStochasticRungeKuttaRI5 (const CDataContainer *pParent, const CTaskEnum::Method &methodType=CTaskEnum::Method::stochasticRunkeKuttaRI5, const CTaskEnum::Task &taskType=CTaskEnum::Task::timeCourse)
CStochasticRungeKuttaRI5 (const CStochasticRungeKuttaRI5 &src, const CDataContainer *pParent)
virtual bool elevateChildren ()
void evalRoot (const double &time, CVectorCore< C_FLOAT64 > &rootValues)
virtual void start ()
virtual void stateChange (const CMath::StateChange &change)
virtual Status step (const double &deltaT, const bool &final=false)
~CStochasticRungeKuttaRI5 ()
Public Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType=CTaskEnum::Task::timeCourse)
CTrajectoryMethod (const CTrajectoryMethod &src, const CDataContainer *pParent)
const CVectorCore< C_INT > & getRoots () const
const bool & integrateReducedModel () const
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (CTrajectoryProblem *problem)
~CTrajectoryMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CDataContainer *pParent)
virtual void clearCallBack ()
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
const CTaskEnum::Method & getSubType () const
const CTaskEnum::Task & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
CCopasiMethod & operator= (const CCopasiMethod &rhs)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Private Member Functions
void buildStage1 ()
void buildStage2 ()
void buildStage3 ()
C_FLOAT64 calculateSmallestPhysicalValue () const
void calculateStateVariables (const double &time)
void createRootMask ()
CStochasticRungeKuttaRI5 ()
void destroyRootMask ()
void evalNoise (C_FLOAT64 *pNoise, const size_t &noiseDimension)
void evalRate (C_FLOAT64 *rates)
void generateRandomNumbers ()
void initializeParameter ()
CTrajectoryMethod::Status internalStep ()
C_FLOAT64 randomIHat ()
C_FLOAT64 randomITilde ()
Private Attributes
CMatrix< C_FLOAT64 > mA
CVector< C_FLOAT64 > mAtol
CVector< CMatrix< C_FLOAT64 > > mB
CVector< CMatrix< C_FLOAT64 > > mBB
CVectorCore< C_FLOAT64 > mContainerNoise
CVectorCore< C_FLOAT64 > mContainerRates
CVectorCore< C_FLOAT64 > mContainerRoots
CVectorCore< C_FLOAT64 > mContainerVariables
CVector< C_FLOAT64 > mH10
CVector< C_FLOAT64 > mH20
CMatrix< C_FLOAT64 > mH2k
CVector< C_FLOAT64 > mH30
CMatrix< C_FLOAT64 > mH3k
CMatrix< C_FLOAT64 > mHH2k
CMatrix< C_FLOAT64 > mHH3k
size_t mInternalSteps
C_FLOAT64 mLastCalculatedTime
CVector< C_FLOAT64 > mLastCalculatedVariables
CVector< C_FLOAT64 * > mNoiseInputValues
CVector< CCore::CUpdateSequence > mNoiseUpdateSequences
size_t mNumNoise
size_t mNumRoots
size_t mNumVariables
C_FLOAT64 * mpAbsoluteTolerance
bool * mpForcePhysicalCorrectness
CVector< bool > mPhysicalValues
C_FLOAT64 * mpInternalStepSize
unsigned C_INT32 * mpMaxInternalSteps
C_INT * mpPhysicalCorrectnessRootFound
CRandom * mpRandom
C_FLOAT64 * mpRootRelativeTolerance
CRootFinder::Eval * mpRootValueCalculator
CVector< C_FLOAT64 > mRandomIHat
CMatrix< C_FLOAT64 > mRandomIMatrix
CVector< C_FLOAT64 > mRandomITilde
size_t mRootCounter
CRootFinder mRootFinder
CVector< C_INT > mRootMask
CRootFinder::RootMasking mRootMasking
CVectorCore< C_FLOAT64 > mRoots
C_FLOAT64 mSqrtStepSize
C_FLOAT64 mStepSize
CVector< C_FLOAT64 > mSumAll1
CVector< C_FLOAT64 > mSumAll2
CMatrix< C_FLOAT64 > mSumPartial1
CMatrix< C_FLOAT64 > mSumPartial2
C_FLOAT64 mTargetDelta
C_FLOAT64 mTargetTime
C_FLOAT64 mTime
Additional Inherited Members
Public Types inherited from CTrajectoryMethod
enum Status { FAILURE = -1 , NORMAL = 0 , ROOT = 1 }
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CTrajectoryMethod
void output (const bool &useMoieties)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src)
CCopasiMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CTrajectoryMethod
CVectorCore< C_FLOAT64 > mContainerState
C_FLOAT64 * mpContainerStateTime
CTrajectoryProblem * mpProblem
const bool * mpReducedModel
CTrajectoryTask * mpTask
CVectorCore< C_INT > mRootsFound
Protected Attributes inherited from CCopasiMethod
CMathContainer * mpContainer
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Static Protected Attributes inherited from CTrajectoryMethod
static const bool ReducedModel
Constructor & Destructor Documentation
CStochasticRungeKuttaRI5() [1/3]
CStochasticRungeKuttaRI5::CStochasticRungeKuttaRI5 () private
Constructor.
CStochasticRungeKuttaRI5() [2/3]
CStochasticRungeKuttaRI5::CStochasticRungeKuttaRI5 (const CDataContainer * pParent, const CTaskEnum::Method & methodType = CTaskEnum::Method::stochasticRunkeKuttaRI5, const CTaskEnum::Task & taskType = CTaskEnum::Task::timeCourse)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Method & methodType (default: deterministic)
const CTaskEnum::Task & taskType (default: timeCourse)
References evalRoot(), initializeParameter(), and mpRootValueCalculator.
CStochasticRungeKuttaRI5() [3/3]
CStochasticRungeKuttaRI5::CStochasticRungeKuttaRI5 (const CStochasticRungeKuttaRI5 & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CStochasticRungeKuttaRI5 & src
const CDataContainer * pParent (default: NULL)
References CVectorCore< CType >::initialize(), initializeParameter(), mContainerNoise, mContainerRates, mContainerRoots, mContainerVariables, and mRoots.
~CStochasticRungeKuttaRI5()
CStochasticRungeKuttaRI5::~CStochasticRungeKuttaRI5 ()
Destructor.
Member Function Documentation
buildStage1()
void CStochasticRungeKuttaRI5::buildStage1 () private
References CMatrix< CType >::array(), CVectorCore< CType >::begin(), c01, c11, c21, C_FLOAT64, evalNoise(), evalRate(), mA, mB, mBB, mContainerVariables, mH10, mNumNoise, mNumVariables, CTrajectoryMethod::mpContainerStateTime, mRandomIHat, mRandomIMatrix, mStepSize, mSumAll1, mSumPartial1, and mTime.
Referenced by calculateStateVariables().
buildStage2()
void CStochasticRungeKuttaRI5::buildStage2 () private
References A021, A121, A221, CMatrix< CType >::array(), B021, B121, B221, CVectorCore< CType >::begin(), c02, c12, c22, C_FLOAT64, CVectorCore< CType >::end(), evalNoise(), evalRate(), mA, mB, mBB, mContainerVariables, mH10, mH20, mH2k, mHH2k, mNumNoise, mNumVariables, CTrajectoryMethod::mpContainerStateTime, mRandomIHat, mRandomIMatrix, mSqrtStepSize, mStepSize, mSumAll1, mSumAll2, mSumPartial1, mSumPartial2, and mTime.
Referenced by calculateStateVariables().
buildStage3()
void CStochasticRungeKuttaRI5::buildStage3 () private
References A031, A032, A131, A132, A231, A232, B031, B032, B131, B132, B231, B232, CVectorCore< CType >::begin(), c03, c13, c23, C_FLOAT64, CVectorCore< CType >::end(), evalNoise(), evalRate(), mA, mB, mBB, mContainerVariables, mH10, mH30, mH3k, mHH3k, mNumNoise, mNumVariables, CTrajectoryMethod::mpContainerStateTime, mSqrtStepSize, mStepSize, mSumAll1, mSumAll2, mSumPartial1, mSumPartial2, and mTime.
Referenced by calculateStateVariables().
calculateSmallestPhysicalValue()
C_FLOAT64 CStochasticRungeKuttaRI5::calculateSmallestPhysicalValue () const private
References CVectorCore< CType >::begin(), C_FLOAT64, CVectorCore< CType >::end(), mAtol, mContainerVariables, mpForcePhysicalCorrectness, and mPhysicalValues.
Referenced by evalRoot(), and internalStep().
calculateStateVariables()
void CStochasticRungeKuttaRI5::calculateStateVariables (const double & time) private
References alpha1, alpha2, alpha3, CMatrix< CType >::array(), CVectorCore< CType >::array(), CVectorCore< CType >::begin(), beta11, beta12, beta13, beta21, beta22, beta23, beta31, beta32, beta33, beta41, beta42, beta43, buildStage1(), buildStage2(), buildStage3(), C_FLOAT64, CVectorCore< CType >::end(), mA, mB, mBB, mContainerVariables, mH10, mLastCalculatedTime, mLastCalculatedVariables, mNumNoise, mNumVariables, CTrajectoryMethod::mpContainerStateTime, mpInternalStepSize, mRandomIHat, mRandomIMatrix, mSqrtStepSize, mStepSize, and mTime.
Referenced by evalRoot(), and internalStep().
createRootMask()
void CStochasticRungeKuttaRI5::createRootMask () private
References CRootFinder::ALL, CVectorCore< CType >::array(), CVectorCore< CType >::begin(), C_FLOAT64, C_INT, CMathContainer::calculateRootDerivatives(), CRootFinder::CONTINUOUS, CRootFinder::DISCRETE, CVectorCore< CType >::end(), CMathContainer::getRootIsDiscrete(), mContainerRoots, min, mNumRoots, CCopasiMethod::mpContainer, mRootMask, mRootMasking, CVector< CType >::resize(), and CMathContainer::updateSimulatedValues().
Referenced by internalStep().
destroyRootMask()
void CStochasticRungeKuttaRI5::destroyRootMask () private
References CVectorCore< CType >::begin(), C_FLOAT64, C_INT, CRootFinder::DISCRETE, CVectorCore< CType >::end(), CRootFinder::getRootError(), mContainerRoots, min, CCopasiMethod::mpContainer, mRootFinder, mRootMask, mRootMasking, CRootFinder::NONE, and CMathContainer::updateSimulatedValues().
Referenced by stateChange().
elevateChildren()
bool CStochasticRungeKuttaRI5::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
References initializeParameter().
evalNoise()
void CStochasticRungeKuttaRI5::evalNoise (C_FLOAT64 * pNoise, const size_t & noiseDimension) private
This evaluates the noise
References CMathContainer::applyUpdateSequence(), CVectorCore< CType >::begin(), C_FLOAT64, mContainerNoise, mNoiseUpdateSequences, mNumVariables, CCopasiMethod::mpContainer, and CMathContainer::resetNoise().
Referenced by buildStage1(), buildStage2(), and buildStage3().
evalRate()
void CStochasticRungeKuttaRI5::evalRate (C_FLOAT64 * rates) private
This evaluates the derivatives
References CVectorCore< CType >::begin(), C_FLOAT64, mContainerRates, mNumVariables, CCopasiMethod::mpContainer, and CMathContainer::updateSimulatedValues().
Referenced by buildStage1(), buildStage2(), and buildStage3().
evalRoot()
void CStochasticRungeKuttaRI5::evalRoot (const double & time, CVectorCore< C_FLOAT64 > & rootValues)
This evaluates the roots
References CVectorCore< CType >::begin(), C_FLOAT64, calculateSmallestPhysicalValue(), calculateStateVariables(), mContainerRoots, mNumRoots, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, CVectorCore< CType >::size(), and CMathContainer::updateRootValues().
Referenced by CStochasticRungeKuttaRI5().
generateRandomNumbers()
void CStochasticRungeKuttaRI5::generateRandomNumbers () private
References CMatrix< CType >::array(), CVectorCore< CType >::begin(), C_FLOAT64, mInternalSteps, mLastCalculatedTime, mNumNoise, mRandomIHat, mRandomIMatrix, mRandomITilde, randomIHat(), and randomITilde().
Referenced by internalStep().
initializeParameter()
void CStochasticRungeKuttaRI5::initializeParameter () private
Initialize the method parameter
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, mpAbsoluteTolerance, mpForcePhysicalCorrectness, mpInternalStepSize, mpMaxInternalSteps, mpRootRelativeTolerance, CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CStochasticRungeKuttaRI5(), and elevateChildren().
internalStep()
CTrajectoryMethod::Status CStochasticRungeKuttaRI5::internalStep () private
References CRootFinder::ALL, CVectorCore< CType >::begin(), C_FLOAT64, C_INT, calculateSmallestPhysicalValue(), calculateStateVariables(), CRootFinder::checkRoots(), createRootMask(), CRootFinder::DISCRETE, CVectorCore< CType >::end(), CCopasiMessage::EXCEPTION, CTrajectoryMethod::FAILURE, fatalError, generateRandomNumbers(), CRootFinder::getRootTime(), CRootFinder::InvalidInterval, CMathContainer::isStateValid(), max, mContainerVariables, MCTrajectoryMethod, mH10, min, mInternalSteps, mNumRoots, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mpForcePhysicalCorrectness, mpInternalStepSize, mpMaxInternalSteps, mpPhysicalCorrectnessRootFound, mpRootRelativeTolerance, mRootFinder, mRootMasking, CTrajectoryMethod::mRootsFound, mTargetTime, mTime, CTrajectoryMethod::NORMAL, CRootFinder::NotAdvanced, CRootFinder::NotFound, CMath::NoToggle, CRootFinder::restart(), CTrajectoryMethod::ROOT, and CRootFinder::RootFound.
Referenced by step().
randomIHat()
C_FLOAT64 CStochasticRungeKuttaRI5::randomIHat () private
References CRandom::getRandomU(), and mpRandom.
Referenced by generateRandomNumbers().
randomITilde()
C_FLOAT64 CStochasticRungeKuttaRI5::randomITilde () private
References CRandom::getRandomU(), and mpRandom.
Referenced by generateRandomNumbers().
start()
void CStochasticRungeKuttaRI5::start () virtual
This instructs the method to prepare for integration
Reimplemented from CTrajectoryMethod.
References CVectorCore< CType >::begin(), CMathUpdateSequence::begin(), C_FLOAT64, C_INT, CMath::Compartment, CCore::Default, CRootFinder::DISCRETE, CMathUpdateSequence::empty(), CVectorCore< CType >::end(), CMathUpdateSequence::end(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getCountNoise(), CMathObject::getEntityType(), CMathContainer::getMathObject(), CMathContainer::getNoise(), CMathContainer::getNoiseInputObjects(), CMathContainer::getRandomGenerator(), CMathContainer::getRate(), CMathContainer::getRootIsDiscrete(), CMathContainer::getRoots(), CRootFinder::getRootValues(), CMathContainer::getStateObjects(), CRootFinder::getToggledRoots(), CMathContainer::getTransientDependencies(), CMathDependencyGraph::getUpdateSequence(), CVectorCore< CType >::initialize(), CRootFinder::initialize(), CMathContainer::initializeAtolVector(), CMathUpdateSequence::insert(), mA, mAtol, mB, mBB, mContainerNoise, mContainerRates, mContainerRoots, CTrajectoryMethod::mContainerState, mContainerVariables, mH10, mH20, mH2k, mH30, mH3k, mHH2k, mHH3k, mLastCalculatedTime, mNoiseInputValues, mNoiseUpdateSequences, mNumNoise, mNumRoots, mNumVariables, mpAbsoluteTolerance, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mPhysicalValues, mpInternalStepSize, mpPhysicalCorrectnessRootFound, mpRandom, mpRootRelativeTolerance, mpRootValueCalculator, mRandomIHat, mRandomIMatrix, mRandomITilde, mRootFinder, mRootMask, mRoots, CTrajectoryMethod::mRootsFound, mSqrtStepSize, mStepSize, mSumAll1, mSumAll2, mSumPartial1, mSumPartial2, mTargetTime, mTime, CRootFinder::NONE, CMatrix< CType >::resize(), CVector< CType >::resize(), CVectorCore< CType >::size(), CMath::Species, and CTrajectoryMethod::start().
stateChange()
void CStochasticRungeKuttaRI5::stateChange (const CMath::StateChange & change) virtual
Inform the trajectory method that the state has changed outside its control
Parameters
const CMath::StateChange & change
Reimplemented from CTrajectoryMethod.
References CMath::ContinuousSimulation, destroyRootMask(), CFlags< Enum >::isSet(), mContainerVariables, mH10, mLastCalculatedTime, mRootFinder, CRootFinder::restart(), and CMath::State.
step()
CTrajectoryMethod::Status CStochasticRungeKuttaRI5::step (const double & deltaT, const bool & final = false) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
const bool & final (default: false)
Returns
Status status
Reimplemented from CTrajectoryMethod.
References CTrajectoryMethod::FAILURE, CTrajectoryProblem::getAutomaticStepSize(), internalStep(), mInternalSteps, mpInternalStepSize, mpMaxInternalSteps, CTrajectoryMethod::mpProblem, mRootCounter, mTargetDelta, mTargetTime, mTime, and CTrajectoryMethod::NORMAL.
Member Data Documentation
mA
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mA private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), and start().
mAtol
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mAtol private
Referenced by calculateSmallestPhysicalValue(), and start().
mB
CVector< CMatrix< C_FLOAT64 > > CStochasticRungeKuttaRI5::mB private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), and start().
mBB
CVector< CMatrix< C_FLOAT64 > > CStochasticRungeKuttaRI5::mBB private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), and start().
mContainerNoise
CVectorCore< C_FLOAT64 > CStochasticRungeKuttaRI5::mContainerNoise private
Referenced by CStochasticRungeKuttaRI5(), evalNoise(), and start().
mContainerRates
CVectorCore< C_FLOAT64 > CStochasticRungeKuttaRI5::mContainerRates private
Referenced by CStochasticRungeKuttaRI5(), evalRate(), and start().
mContainerRoots
CVectorCore< C_FLOAT64 > CStochasticRungeKuttaRI5::mContainerRoots private
Referenced by createRootMask(), CStochasticRungeKuttaRI5(), destroyRootMask(), evalRoot(), and start().
mContainerVariables
CVectorCore< C_FLOAT64 > CStochasticRungeKuttaRI5::mContainerVariables private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateSmallestPhysicalValue(), calculateStateVariables(), CStochasticRungeKuttaRI5(), internalStep(), start(), and stateChange().
mH10
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mH10 private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), internalStep(), start(), and stateChange().
mH20
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mH20 private
Referenced by buildStage2(), and start().
mH2k
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mH2k private
Referenced by buildStage2(), and start().
mH30
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mH30 private
Referenced by buildStage3(), and start().
mH3k
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mH3k private
Referenced by buildStage3(), and start().
mHH2k
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mHH2k private
Referenced by buildStage2(), and start().
mHH3k
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mHH3k private
Referenced by buildStage3(), and start().
mInternalSteps
size_t CStochasticRungeKuttaRI5::mInternalSteps private
Referenced by generateRandomNumbers(), internalStep(), and step().
mLastCalculatedTime
C_FLOAT64 CStochasticRungeKuttaRI5::mLastCalculatedTime private
Referenced by calculateStateVariables(), generateRandomNumbers(), start(), and stateChange().
mLastCalculatedVariables
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mLastCalculatedVariables private
Referenced by calculateStateVariables().
mNoiseInputValues
CVector< C_FLOAT64 * > CStochasticRungeKuttaRI5::mNoiseInputValues private
Referenced by start().
mNoiseUpdateSequences
CVector< CCore::CUpdateSequence > CStochasticRungeKuttaRI5::mNoiseUpdateSequences private
Referenced by evalNoise(), and start().
mNumNoise
size_t CStochasticRungeKuttaRI5::mNumNoise private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), generateRandomNumbers(), and start().
mNumRoots
size_t CStochasticRungeKuttaRI5::mNumRoots private
Referenced by createRootMask(), evalRoot(), internalStep(), and start().
mNumVariables
size_t CStochasticRungeKuttaRI5::mNumVariables private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), evalNoise(), evalRate(), and start().
mpAbsoluteTolerance
C_FLOAT64* CStochasticRungeKuttaRI5::mpAbsoluteTolerance private
A pointer to to the value "Absolute Tolerance"
Referenced by initializeParameter(), and start().
mpForcePhysicalCorrectness
bool* CStochasticRungeKuttaRI5::mpForcePhysicalCorrectness private
A pointer to the value "Force Physical Correctness"
Referenced by calculateSmallestPhysicalValue(), initializeParameter(), and internalStep().
mPhysicalValues
CVector< bool > CStochasticRungeKuttaRI5::mPhysicalValues private
Referenced by calculateSmallestPhysicalValue(), and start().
mpInternalStepSize
C_FLOAT64* CStochasticRungeKuttaRI5::mpInternalStepSize private
A pointer to the value of "Internal Steps Size"
Referenced by calculateStateVariables(), initializeParameter(), internalStep(), start(), and step().
mpMaxInternalSteps
unsigned C_INT32* CStochasticRungeKuttaRI5::mpMaxInternalSteps private
A pointer to the value of "Max Internal Steps"
Referenced by initializeParameter(), internalStep(), and step().
mpPhysicalCorrectnessRootFound
C_INT* CStochasticRungeKuttaRI5::mpPhysicalCorrectnessRootFound private
A pointer to the value which indicate the physical correctness root was found.
Referenced by internalStep(), and start().
mpRandom
CRandom* CStochasticRungeKuttaRI5::mpRandom private
A pointer to the random number generator
Referenced by randomIHat(), randomITilde(), and start().
mpRootRelativeTolerance
C_FLOAT64* CStochasticRungeKuttaRI5::mpRootRelativeTolerance private
A pointer to the value of "Tolerance for Root Finder"
Referenced by initializeParameter(), internalStep(), and start().
mpRootValueCalculator
CRootFinder::Eval* CStochasticRungeKuttaRI5::mpRootValueCalculator private
Referenced by CStochasticRungeKuttaRI5(), and start().
mRandomIHat
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mRandomIHat private
Referenced by buildStage1(), buildStage2(), calculateStateVariables(), generateRandomNumbers(), and start().
mRandomIMatrix
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mRandomIMatrix private
Referenced by buildStage1(), buildStage2(), calculateStateVariables(), generateRandomNumbers(), and start().
mRandomITilde
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mRandomITilde private
Referenced by generateRandomNumbers(), and start().
mRootCounter
size_t CStochasticRungeKuttaRI5::mRootCounter private
Referenced by step().
mRootFinder
CRootFinder CStochasticRungeKuttaRI5::mRootFinder private
Referenced by destroyRootMask(), internalStep(), start(), and stateChange().
mRootMask
CVector< C_INT > CStochasticRungeKuttaRI5::mRootMask private
Referenced by createRootMask(), destroyRootMask(), and start().
mRootMasking
CRootFinder::RootMasking CStochasticRungeKuttaRI5::mRootMasking private
Referenced by createRootMask(), destroyRootMask(), and internalStep().
mRoots
CVectorCore< C_FLOAT64 > CStochasticRungeKuttaRI5::mRoots private
Referenced by CStochasticRungeKuttaRI5(), and start().
mSqrtStepSize
C_FLOAT64 CStochasticRungeKuttaRI5::mSqrtStepSize private
Referenced by buildStage2(), buildStage3(), calculateStateVariables(), and start().
mStepSize
C_FLOAT64 CStochasticRungeKuttaRI5::mStepSize private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), and start().
mSumAll1
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mSumAll1 private
Referenced by buildStage1(), buildStage2(), buildStage3(), and start().
mSumAll2
CVector< C_FLOAT64 > CStochasticRungeKuttaRI5::mSumAll2 private
Referenced by buildStage2(), buildStage3(), and start().
mSumPartial1
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mSumPartial1 private
Referenced by buildStage1(), buildStage2(), buildStage3(), and start().
mSumPartial2
CMatrix< C_FLOAT64 > CStochasticRungeKuttaRI5::mSumPartial2 private
Referenced by buildStage2(), buildStage3(), and start().
mTargetDelta
C_FLOAT64 CStochasticRungeKuttaRI5::mTargetDelta private
Referenced by step().
mTargetTime
C_FLOAT64 CStochasticRungeKuttaRI5::mTargetTime private
Referenced by internalStep(), start(), and step().
mTime
C_FLOAT64 CStochasticRungeKuttaRI5::mTime private
Referenced by buildStage1(), buildStage2(), buildStage3(), calculateStateVariables(), internalStep(), start(), and step().
The documentation for this class was generated from the following files:
CStochasticRungeKuttaRI5.h
CStochasticRungeKuttaRI5.cpp