COPASI API: CMCAMethod Class Reference
CMCAMethod Class Reference
#include <CMCAMethod.h>
Public Member Functions
bool CalculateMCA (C_FLOAT64 res)
bool calculateUnscaledConcentrationCC ()
void calculateUnscaledElasticities (C_FLOAT64 res)
bool calculateUnscaledFluxCC (const bool &status)
bool checkSummationTheorems (const C_FLOAT64 &resolution)
CMCAMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType=CTaskEnum::Method::mcaMethodReder, const CTaskEnum::Task &taskType=CTaskEnum::Task::mca)
CMCAMethod (const CMCAMethod &src, const CDataContainer *pParent)
virtual bool elevateChildren ()
const CModel * getModel () const
const CMatrix< C_FLOAT64 > & getScaledConcentrationCC () const
const CDataArray * getScaledConcentrationCCAnn () const
const CMatrix< C_FLOAT64 > & getScaledElasticities () const
const CDataArray * getScaledElasticitiesAnn () const
const CMatrix< C_FLOAT64 > & getScaledFluxCC () const
const CDataArray * getScaledFluxCCAnn () const
const CSteadyStateMethod::ReturnCode & getSteadyStateStatus () const
const CMatrix< C_FLOAT64 > & getUnscaledConcentrationCC () const
const CDataArray * getUnscaledConcentrationCCAnn () const
const CMatrix< C_FLOAT64 > & getUnscaledElasticities () const
const CDataArray * getUnscaledElasticitiesAnn () const
const CMatrix< C_FLOAT64 > & getUnscaledFluxCC () const
const CDataArray * getUnscaledFluxCCAnn () const
virtual bool isValidProblem (const CCopasiProblem *pProblem)
C_INT32 load (CReadConfig &configBuffer)
virtual bool process ()
virtual void resizeAllMatrices ()
bool scaleMCA (const bool &status, C_FLOAT64 res)
void setFactor (C_FLOAT64 factor)
void setSteadyStateResolution (C_FLOAT64 factor)
void setSteadyStateTask (CSteadyStateTask *pSteadyStateTask)
virtual ~CMCAMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CDataContainer *pParent)
virtual void clearCallBack ()
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
const CTaskEnum::Method & getSubType () const
const CTaskEnum::Task & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
CCopasiMethod & operator= (const CCopasiMethod &rhs)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Private Member Functions
CMCAMethod ()
bool createLinkMatrix (const bool &useSmallbone=false)
void initializeParameter ()
void initObjects ()
Private Attributes
CMatrix< C_INT32 > mElasticityDependencies
C_FLOAT64 mFactor
CLinkMatrix mLinkZero
CSteadyStateTask * mpSteadyStateTask
bool * mpUseReder
bool * mpUseSmallbone
CMatrix< C_FLOAT64 > mReducedStoichiometry
CMatrix< C_FLOAT64 > mScaledConcCC
CDataArray * mScaledConcCCAnn
CMatrix< C_FLOAT64 > mScaledElasticities
CDataArray * mScaledElasticitiesAnn
CMatrix< C_FLOAT64 > mScaledFluxCC
CDataArray * mScaledFluxCCAnn
C_INT16 mSSReder
CSteadyStateMethod::ReturnCode mSSStatus
std::vector< C_FLOAT64 > mSsx
C_FLOAT64 mSteadyStateResolution
CMatrix< C_FLOAT64 > mUnscaledConcCC
CDataArray * mUnscaledConcCCAnn
CMatrix< C_FLOAT64 > mUnscaledElasticities
CDataArray * mUnscaledElasticitiesAnn
CMatrix< C_FLOAT64 > mUnscaledFluxCC
CDataArray * mUnscaledFluxCCAnn
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src)
CCopasiMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CCopasiMethod
CMathContainer * mpContainer
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CMCAMethod() [1/3]
CMCAMethod::CMCAMethod () private
Default constructor.
CMCAMethod() [2/3]
CMCAMethod::CMCAMethod (const CDataContainer * pParent, const CTaskEnum::Method & methodType = CTaskEnum::Method::mcaMethodReder, const CTaskEnum::Task & taskType = CTaskEnum::Task::mca)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Method & methodType (default: mcaMethodReder)
const CTaskEnum::Task & taskType (default: mca)
Default constructor
References initializeParameter(), and initObjects().
CMCAMethod() [3/3]
CMCAMethod::CMCAMethod (const CMCAMethod & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CMCAMethod & src
const CDataContainer * pParent (Default: NULL)
References initializeParameter(), and initObjects().
~CMCAMethod()
CMCAMethod::~CMCAMethod () virtual
Destructor
Deconstructor
References DESTRUCTOR_TRACE.
Member Function Documentation
CalculateMCA()
bool CMCAMethod::CalculateMCA (C_FLOAT64 res)
the steady state MCA entry point
Parameters
ss_solution refer to steady-state solution
refer to the resolution
References calculateUnscaledConcentrationCC(), calculateUnscaledElasticities(), calculateUnscaledFluxCC(), checkSummationTheorems(), createLinkMatrix(), CSteadyStateMethod::found, MCMCA, mpUseReder, mpUseSmallbone, mSSStatus, mUnscaledConcCC, mUnscaledFluxCC, scaleMCA(), and CCopasiMessage::WARNING.
Referenced by process().
calculateUnscaledConcentrationCC()
bool CMCAMethod::calculateUnscaledConcentrationCC ()
References CMatrix< CType >::array(), CVectorCore< CType >::array(), C_INT, dgetrf_(), dgetri_(), CLinkMatrix::doColumnPivot(), dgemm::eval(), CLinkMatrix::leftMultiply(), mLinkZero, mReducedStoichiometry, mUnscaledConcCC, mUnscaledElasticities, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), CMatrix< CType >::resize(), CVector< CType >::resize(), CLinkMatrix::rightMultiply(), CLinkMatrix::undoColumnPivot(), and CLinkMatrix::undoRowPivot().
Referenced by CalculateMCA().
calculateUnscaledElasticities()
void CMCAMethod::calculateUnscaledElasticities (C_FLOAT64 res)
References CMatrix< CType >::array(), CVectorCore< CType >::array(), C_FLOAT64, CMathContainer::calculateElasticityDependencies(), CMathContainer::getCountDependentSpecies(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getCountIndependentSpecies(), CMathContainer::getCountODEs(), CMathContainer::getMathObject(), CMathContainer::getParticleFluxes(), CMathContainer::getState(), CMathContainer::getTransientDependencies(), CMathObject::getValuePointer(), mElasticityDependencies, mFactor, min, CCopasiMethod::mpContainer, mUnscaledElasticities, CMatrix< CType >::size(), CVectorCore< CType >::size(), and CMathContainer::updateSimulatedValues().
Referenced by CalculateMCA().
calculateUnscaledFluxCC()
bool CMCAMethod::calculateUnscaledFluxCC (const bool & status)
References CMatrix< CType >::array(), C_FLOAT64, C_INT, dlaset_(), dgemm::eval(), mUnscaledConcCC, mUnscaledElasticities, mUnscaledFluxCC, and CMatrix< CType >::numRows().
Referenced by CalculateMCA().
checkSummationTheorems()
bool CMCAMethod::checkSummationTheorems (const C_FLOAT64 & resolution)
Check whether the summation theorems hold.
References CMatrix< CType >::array(), CVectorCore< CType >::array(), C_FLOAT64, max, min, mScaledConcCC, mScaledFluxCC, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), CVector< CType >::resize(), and CMatrix< CType >::size().
Referenced by CalculateMCA().
createLinkMatrix()
bool CMCAMethod::createLinkMatrix (const bool & useSmallbone = false) private
References CLinkMatrix::build(), CLinkMatrix::doRowPivot(), CSteadyStateTask::getJacobian(), CModel::getL0(), CMathContainer::getModel(), CLinkMatrix::getNumIndependent(), CModel::getNumIndependentReactionMetabs(), CModel::getRedStoi(), CModel::getStoi(), mLinkZero, CCopasiMethod::mpContainer, mpSteadyStateTask, mReducedStoichiometry, CMatrix< CType >::numCols(), and CMatrix< CType >::resize().
Referenced by CalculateMCA().
elevateChildren()
bool CMCAMethod::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
References initializeParameter().
getModel()
const CModel * CMCAMethod::getModel () const
Get the Model
References CMathContainer::getModel(), and CCopasiMethod::mpContainer.
getScaledConcentrationCC()
const CMatrix<C_FLOAT64>& CMCAMethod::getScaledConcentrationCC () const inline
References mScaledConcCC.
getScaledConcentrationCCAnn()
const CDataArray* CMCAMethod::getScaledConcentrationCCAnn () const inline
References mScaledConcCCAnn.
Referenced by CMCATask::printResult().
getScaledElasticities()
const CMatrix<C_FLOAT64>& CMCAMethod::getScaledElasticities () const inline
References mScaledElasticities.
getScaledElasticitiesAnn()
const CDataArray* CMCAMethod::getScaledElasticitiesAnn () const inline
References mScaledElasticitiesAnn.
Referenced by CMCATask::printResult().
getScaledFluxCC()
const CMatrix<C_FLOAT64>& CMCAMethod::getScaledFluxCC () const inline
References mScaledFluxCC.
getScaledFluxCCAnn()
const CDataArray* CMCAMethod::getScaledFluxCCAnn () const inline
References mScaledFluxCCAnn.
Referenced by CMCATask::printResult().
getSteadyStateStatus()
const CSteadyStateMethod::ReturnCode& CMCAMethod::getSteadyStateStatus () const inline
References mSSStatus.
Referenced by CMCATask::printResult().
getUnscaledConcentrationCC()
const CMatrix<C_FLOAT64>& CMCAMethod::getUnscaledConcentrationCC () const inline
References mUnscaledConcCC.
getUnscaledConcentrationCCAnn()
const CDataArray* CMCAMethod::getUnscaledConcentrationCCAnn () const inline
References mUnscaledConcCCAnn.
Referenced by CMCATask::printResult().
getUnscaledElasticities()
const CMatrix<C_FLOAT64>& CMCAMethod::getUnscaledElasticities () const inline
References mUnscaledElasticities.
getUnscaledElasticitiesAnn()
const CDataArray* CMCAMethod::getUnscaledElasticitiesAnn () const inline
References mUnscaledElasticitiesAnn.
Referenced by CMCATask::printResult().
getUnscaledFluxCC()
const CMatrix<C_FLOAT64>& CMCAMethod::getUnscaledFluxCC () const inline
References mUnscaledFluxCC.
getUnscaledFluxCCAnn()
const CDataArray* CMCAMethod::getUnscaledFluxCCAnn () const inline
References mUnscaledFluxCCAnn.
Referenced by CMCATask::printResult().
initializeParameter()
void CMCAMethod::initializeParameter () private
Initialize the method parameter
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), mpUseReder, mpUseSmallbone, CCopasiParameterGroup::removeParameter(), CCopasiParameterGroup::setValue(), and CCopasiParameter::UDOUBLE.
Referenced by CMCAMethod(), and elevateChildren().
initObjects()
void CMCAMethod::initObjects () private
References mScaledConcCC, mScaledConcCCAnn, mScaledElasticities, mScaledElasticitiesAnn, mScaledFluxCC, mScaledFluxCCAnn, mUnscaledConcCC, mUnscaledConcCCAnn, mUnscaledElasticities, mUnscaledElasticitiesAnn, mUnscaledFluxCC, mUnscaledFluxCCAnn, CDataArray::setDescription(), CDataArray::setDimensionDescription(), CDataArray::setMode(), and CDataArray::Vector.
Referenced by CMCAMethod().
isValidProblem()
bool CMCAMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CCopasiMethod.
References CDataVector< CType >::begin(), CCore::Default, CDataVector< CType >::end(), CCopasiMessage::ERROR, CModel::getCompartments(), CMathContainer::getCountODEs(), CMathContainer::getMathObject(), CMathContainer::getModel(), CMathContainer::getStateObjects(), CMathContainer::getTransientDependencies(), CMathDependencyGraph::getUpdateSequence(), CCopasiMethod::isValidProblem(), CCopasiMethod::mpContainer, mpUseReder, mpUseSmallbone, and CMathUpdateSequence::size().
load()
C_INT32 CMCAMethod::load (CReadConfig & configBuffer)
Read SSMCAUnscaled from configuration file
References C_INT32, CReadConfig::getVariable(), CReadConfig::LOOP, and mSSReder.
process()
bool CMCAMethod::process () virtual
References CalculateMCA(), and mSteadyStateResolution.
Referenced by CMCATask::process().
resizeAllMatrices()
void CMCAMethod::resizeAllMatrices () virtual
Resizes all result matrices and updates the corresponding array annotations. This needs to be called before output initialization (in case the output references parts of the matrix) from the task initialization, but it also needs to be called before selecting elements of the matrices in the object selection dialog. The model needs to be set before calling this.
References CMathContainer::getCountDependentSpecies(), CMathContainer::getCountIndependentSpecies(), CModel::getMetabolitesX(), CMathContainer::getModel(), CMathContainer::getReactions(), CModel::getReactions(), mElasticityDependencies, CCopasiMethod::mpContainer, mScaledConcCC, mScaledConcCCAnn, mScaledElasticities, mScaledElasticitiesAnn, mScaledFluxCC, mScaledFluxCCAnn, mUnscaledConcCC, mUnscaledConcCCAnn, mUnscaledElasticities, mUnscaledElasticitiesAnn, mUnscaledFluxCC, mUnscaledFluxCCAnn, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), CDataArray::resize(), CMatrix< CType >::resize(), CDataArray::setAnnotationString(), CDataArray::setCopasiVector(), and CVectorCore< CType >::size().
Referenced by CMCATask::updateMatrices().
scaleMCA()
bool CMCAMethod::scaleMCA (const bool & status, C_FLOAT64 res)
Scales the coefficients (i.e. Kacser format, rather than Reder)
References CMatrix< CType >::array(), CVectorCore< CType >::array(), C_FLOAT64, C_INT32, CSteadyStateMethod::found, CMathContainer::getCompartment(), CMathObject::getCorrespondingProperty(), CMathContainer::getCountDependentSpecies(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getCountIndependentSpecies(), CMathContainer::getCountODEs(), CMathContainer::getFluxes(), CMathContainer::getLargestReactionCompartment(), CMathContainer::getMathObject(), CMathContainer::getParticleFluxes(), CMathContainer::getReactions(), CMathContainer::getState(), CMathObject::getValuePointer(), mElasticityDependencies, CCopasiMethod::mpContainer, mScaledConcCC, mScaledElasticities, mScaledFluxCC, mSSStatus, mUnscaledConcCC, mUnscaledElasticities, mUnscaledFluxCC, CMatrix< CType >::numCols(), CVectorCore< CType >::size(), and CMathContainer::updateTransientDataValues().
Referenced by CalculateMCA().
setFactor()
void CMCAMethod::setFactor (C_FLOAT64 factor)
References mFactor.
setSteadyStateResolution()
void CMCAMethod::setSteadyStateResolution (C_FLOAT64 factor)
References mSteadyStateResolution.
setSteadyStateTask()
void CMCAMethod::setSteadyStateTask (CSteadyStateTask * pSteadyStateTask)
References CSteadyStateTask::getResult(), mpSteadyStateTask, mSSStatus, and CSteadyStateMethod::notFound.
Referenced by CMCATask::process().
Member Data Documentation
mElasticityDependencies
CMatrix< C_INT32 > CMCAMethod::mElasticityDependencies private
Referenced by calculateUnscaledElasticities(), resizeAllMatrices(), and scaleMCA().
mFactor
C_FLOAT64 CMCAMethod::mFactor private
Modulation factor for finite differences derivation
Referenced by calculateUnscaledElasticities(), and setFactor().
mLinkZero
CLinkMatrix CMCAMethod::mLinkZero private
Referenced by calculateUnscaledConcentrationCC(), and createLinkMatrix().
mpSteadyStateTask
CSteadyStateTask* CMCAMethod::mpSteadyStateTask private
Referenced by createLinkMatrix(), and setSteadyStateTask().
mpUseReder
bool* CMCAMethod::mpUseReder private
Referenced by CalculateMCA(), initializeParameter(), and isValidProblem().
mpUseSmallbone
bool* CMCAMethod::mpUseSmallbone private
Referenced by CalculateMCA(), initializeParameter(), and isValidProblem().
mReducedStoichiometry
CMatrix< C_FLOAT64 > CMCAMethod::mReducedStoichiometry private
Referenced by calculateUnscaledConcentrationCC(), and createLinkMatrix().
mScaledConcCC
CMatrix<C_FLOAT64> CMCAMethod::mScaledConcCC private
Referenced by checkSummationTheorems(), getScaledConcentrationCC(), initObjects(), resizeAllMatrices(), and scaleMCA().
mScaledConcCCAnn
CDataArray* CMCAMethod::mScaledConcCCAnn private
Referenced by getScaledConcentrationCCAnn(), initObjects(), and resizeAllMatrices().
mScaledElasticities
CMatrix<C_FLOAT64> CMCAMethod::mScaledElasticities private
Referenced by getScaledElasticities(), initObjects(), resizeAllMatrices(), and scaleMCA().
mScaledElasticitiesAnn
CDataArray* CMCAMethod::mScaledElasticitiesAnn private
Referenced by getScaledElasticitiesAnn(), initObjects(), and resizeAllMatrices().
mScaledFluxCC
CMatrix<C_FLOAT64> CMCAMethod::mScaledFluxCC private
Referenced by checkSummationTheorems(), getScaledFluxCC(), initObjects(), resizeAllMatrices(), and scaleMCA().
mScaledFluxCCAnn
CDataArray* CMCAMethod::mScaledFluxCCAnn private
Referenced by getScaledFluxCCAnn(), initObjects(), and resizeAllMatrices().
mSSReder
C_INT16 CMCAMethod::mSSReder private
1 if MCA coeffs are to be unscaled
Referenced by load().
mSSStatus
CSteadyStateMethod::ReturnCode CMCAMethod::mSSStatus private
Referenced by CalculateMCA(), getSteadyStateStatus(), scaleMCA(), and setSteadyStateTask().
mSsx
std::vector<C_FLOAT64> CMCAMethod::mSsx private
If need to evaluate the elasticities, ss_x will be assigned in calculateTimeMCA()
mSteadyStateResolution
C_FLOAT64 CMCAMethod::mSteadyStateResolution private
Referenced by process(), and setSteadyStateResolution().
mUnscaledConcCC
CMatrix<C_FLOAT64> CMCAMethod::mUnscaledConcCC private
Referenced by CalculateMCA(), calculateUnscaledConcentrationCC(), calculateUnscaledFluxCC(), getUnscaledConcentrationCC(), initObjects(), resizeAllMatrices(), and scaleMCA().
mUnscaledConcCCAnn
CDataArray* CMCAMethod::mUnscaledConcCCAnn private
Referenced by getUnscaledConcentrationCCAnn(), initObjects(), and resizeAllMatrices().
mUnscaledElasticities
CMatrix<C_FLOAT64> CMCAMethod::mUnscaledElasticities private
MCA Matrices
Referenced by calculateUnscaledConcentrationCC(), calculateUnscaledElasticities(), calculateUnscaledFluxCC(), getUnscaledElasticities(), initObjects(), resizeAllMatrices(), and scaleMCA().
mUnscaledElasticitiesAnn
CDataArray* CMCAMethod::mUnscaledElasticitiesAnn private
Referenced by getUnscaledElasticitiesAnn(), initObjects(), and resizeAllMatrices().
mUnscaledFluxCC
CMatrix<C_FLOAT64> CMCAMethod::mUnscaledFluxCC private
Referenced by CalculateMCA(), calculateUnscaledFluxCC(), getUnscaledFluxCC(), initObjects(), resizeAllMatrices(), and scaleMCA().
mUnscaledFluxCCAnn
CDataArray* CMCAMethod::mUnscaledFluxCCAnn private
Referenced by getUnscaledFluxCCAnn(), initObjects(), and resizeAllMatrices().
The documentation for this class was generated from the following files:
CMCAMethod.h
CMCAMethod.cpp