COPASI API: COutputAssistant Class Reference
COutputAssistant Class Reference
#include <COutputAssistant.h>
Static Public Member Functions
static CDataObject * createDefaultOutput (C_INT32 id, CCopasiTask *task, CDataModel *pDataModel, bool activate=true, const std::vector< COutputOption > *pOptions=NULL)
static C_INT32 findItemByName (const std::string &name, bool isPlot=true)
static C_INT32 getDefaultPlotIndex (const CCopasiProblem *problem)
static C_INT32 getDefaultReportIndex (const CCopasiProblem *problem)
static const CDefaultOutputDescription & getItem (C_INT32 id)
static const std::string & getItemName (C_INT32 id)
static std::vector< C_INT32 > getListOfDefaultOutputDescriptions (const CCopasiTask *task=NULL)
Private Types
typedef std::map< C_INT32, CDefaultOutputDescription > Map
Static Private Member Functions
static void add2DDataArrayToVector (std::vector< const CDataObject * > &pVector, const CDataArray *pArray)
static CPlotSpecification * createPlot (const std::string &name, const CDataObject *x, bool logX, const std::vector< const CDataObject * > &y, bool logY, const CTaskEnum::Task &taskType, CDataModel *pDataModel, CCopasiTask *task=NULL)
static CReportDefinition * createTable (const std::string &name, const std::vector< const CDataObject * > &d, const std::string &comment, const CTaskEnum::Task &taskType, CDataModel *pDataModel)
static bool initialize ()
static bool isOptionEnabled (const std::vector< COutputOption > *pOptions, const std::string &name, bool defaultValue=true)
Static Private Attributes
static const CDefaultOutputDescription emptyItem
static const std::string emptyString
static Map mMap
Member Typedef Documentation
Map
typedef std::map<C_INT32, CDefaultOutputDescription> COutputAssistant::Map private
Member Function Documentation
add2DDataArrayToVector()
void COutputAssistant::add2DDataArrayToVector (std::vector< const CDataObject * > & pVector, const CDataArray * pArray) static private
References CDataArray::addElementReference(), C_INT32, CDataArray::dimensionality(), and CDataArray::size().
createDefaultOutput()
CDataObject * COutputAssistant::createDefaultOutput (C_INT32 id, CCopasiTask * task, CDataModel * pDataModel, bool activate = true, const std::vector< COutputOption > * pOptions = NULL) static
create a plot or report from template with index id. returns a pointer to the plot or report definition (or NULL) if activate==true and the ouput is a report the report is set as the current report for the task (possibly replacing an already set report)
References CPlotItem::addChannel(), CPlotSpecification::addTaskType(), COutputInterface::AFTER, CCopasiParameterGroup::assertParameter(), CDataVector< CType >::begin(), C_INT32, CPlotSpecification::createItem(), createPlot(), COutputDefinitionVector::createPlotSpec(), CPlotItem::curve2d, COutputInterface::DURING, CDataVector< CType >::end(), CObjectInterface::getCN(), CDataObject::getCN(), CPlotColors::getCopasiColorStr(), CExperimentSet::getExperiment(), CExperimentSet::getExperimentCount(), CFitProblem::getExperimentSet(), CExperiment::getExperimentType(), CExperiment::getFittingPoints(), getItem(), getItemName(), CPlotSpecification::getItems(), CCopasiTask::getMathContainer(), CMathContainer::getModel(), CCopasiParameterGroup::getObject(), CDataContainer::getObject(), CDataVector< CType >::getObject(), CDataObject::getObjectDisplayName(), CDataObject::getObjectName(), CDataModel::getPlotDefinitionList(), CCopasiTask::getProblem(), CDataModel::getTaskList(), isOptionEnabled(), CTaskEnum::parameterFitting, CPlotItem::plot2d, CPlotItem::setActivity(), CPlotSpecification::setLogY(), CCopasiParameterGroup::setValue(), CDataVector< CType >::size(), CPlotItem::Square, CCopasiParameter::STRING, and CTaskEnum::timeCourse.
createPlot()
CPlotSpecification * COutputAssistant::createPlot (const std::string & name, const CDataObject * x, bool logX, const std::vector< const CDataObject * > & y, bool logY, const CTaskEnum::Task & taskType, CDataModel * pDataModel, CCopasiTask * task = NULL) static private
References CPlotItem::addChannel(), CPlotSpecification::addTaskType(), CCopasiParameterGroup::assertParameter(), C_INT32, CPlotSpecification::createItem(), COutputDefinitionVector::createPlotSpec(), CTaskEnum::crosssection, CPlotItem::curve2d, CDataObject::getCN(), CDataObject::getObjectDisplayName(), CDataModel::getPlotDefinitionList(), CCopasiTask::getProblem(), CScanProblem::getSubtask(), CCopasiTask::getType(), CTaskEnum::optimization, CTaskEnum::parameterFitting, CPlotItem::plot2d, CTaskEnum::scan, CPlotSpecification::setLogX(), CPlotSpecification::setLogY(), CCopasiParameterGroup::setValue(), CCopasiParameter::STRING, and CTaskEnum::timeSens.
Referenced by createDefaultOutput().
createTable()
CReportDefinition * COutputAssistant::createTable (const std::string & name, const std::vector< const CDataObject * > & d, const std::string & comment, const CTaskEnum::Task & taskType, CDataModel * pDataModel) static private
References C_INT32, CReportDefinitionVector::createReportDefinition(), CDataModel::getReportDefinitionList(), CReportDefinition::getTableAddr(), CReportDefinition::setIsTable(), CReportDefinition::setSeparator(), and CReportDefinition::setTaskType().
findItemByName()
C_INT32 COutputAssistant::findItemByName (const std::string & name, bool isPlot = true) static
get the id of output definition with the given name
Parameters
name the name of the default output description to find
isPlot boolean indicating whether we are looking for a plot (true, default) or report.
Returns
the item id if found, or -1 if it is not
References initialize(), and mMap.
getDefaultPlotIndex()
C_INT32 COutputAssistant::getDefaultPlotIndex (const CCopasiProblem * problem) static
get an index of a default plot that is recommended for the given problem. If no such plot exists, -1 is returned
References CCopasiProblem::getType(), CTaskEnum::steadyState, and CTaskEnum::timeCourse.
getDefaultReportIndex()
C_INT32 COutputAssistant::getDefaultReportIndex (const CCopasiProblem * problem) static
get an index of a default output report that is recommended for the given problem. If no such report exists, -1 is returned
References CCopasiProblem::getType(), CTaskEnum::steadyState, and CTaskEnum::timeCourse.
getItem()
const CDefaultOutputDescription & COutputAssistant::getItem (C_INT32 id) static
get complete description of output definition with index id.
References emptyItem, and mMap.
Referenced by createDefaultOutput().
getItemName()
const std::string & COutputAssistant::getItemName (C_INT32 id) static
get title of output definition with index id.
References emptyString, and mMap.
Referenced by createDefaultOutput().
getListOfDefaultOutputDescriptions()
std::vector< C_INT32 > COutputAssistant::getListOfDefaultOutputDescriptions (const CCopasiTask * task = NULL) static
get a list of indices of output definitions that are suitable for the problem. If problem=NULL (default) all indices in the map are returned.
References CTaskEnum::crosssection, CCopasiTask::getType(), initialize(), mMap, CTaskEnum::timeCourse, and CTaskEnum::UnsetTask.
initialize()
bool COutputAssistant::initialize () static private
numbering scheme:
0-99: time course plots 200-299: plots with scan parameter on x-axis
above 1000: reports
1000-1099: reports with time and some other variables 1200-1299: reports with scan parameters and some other variables
the meaning of the last two digits should be the same in all those cases.
Special plots, e.g. for parameter estimation, use numbers 900-998.
References mMap, CTaskEnum::optimization, CTaskEnum::parameterFitting, CTaskEnum::scan, CTaskEnum::steadyState, CTaskEnum::timeCourse, CTaskEnum::timeSens, and CTaskEnum::UnsetTask.
Referenced by findItemByName(), and getListOfDefaultOutputDescriptions().
isOptionEnabled()
bool COutputAssistant::isOptionEnabled (const std::vector< COutputOption > * pOptions, const std::string & name, bool defaultValue = true) static private
Referenced by createDefaultOutput().
Member Data Documentation
emptyItem
const CDefaultOutputDescription COutputAssistant::emptyItem static private
Referenced by getItem().
emptyString
const std::string COutputAssistant::emptyString static private
Referenced by getItemName().
mMap
COutputAssistant::Map COutputAssistant::mMap static private
Referenced by findItemByName(), getItem(), getItemName(), getListOfDefaultOutputDescriptions(), and initialize().
The documentation for this class was generated from the following files:
COutputAssistant.h
COutputAssistant.cpp