COPASI API: CEvent Class Reference
CEvent Class Reference
#include <CEvent.h>
Public Types
enum Type { Assignment , Discontinuity , Callback , Stop }
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Public Member Functions
bool appendDependentAssignments (std::set< const CDataObject * > candidates, std::set< const CDataObject * > &dependents) const
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CEvent (const CEvent &src, const CDataContainer *pParent)
CEvent (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
void cleanup ()
CIssue compile (CObjectInterface::ContainerList listOfContainer)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
void deleteAssignment (const std::string &key)
CDataVectorN< CEventAssignment > & getAssignments ()
const CDataVectorN< CEventAssignment > & getAssignments () const
const bool & getDelayAssignment () const
std::string getDelayExpression () const
CExpression * getDelayExpressionPtr ()
const CExpression * getDelayExpressionPtr () const
const bool & getFireAtInitialTime () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName () const
std::string getOriginFor (const DataObjectSet &deletedObjects) const
const bool & getPersistentTrigger () const
std::string getPriorityExpression () const
CExpression * getPriorityExpressionPtr ()
const CExpression * getPriorityExpressionPtr () const
const std::string & getSBMLId () const
std::string getTriggerExpression () const
CExpression * getTriggerExpressionPtr ()
const CExpression * getTriggerExpressionPtr () const
const Type & getType () const
void setDelayAssignment (const bool &delayCalculation)
bool setDelayExpression (const std::string &expression)
bool setDelayExpressionPtr (CExpression *pExpression)
void setFireAtInitialTime (const bool &fireAtInitialTime)
virtual bool setObjectParent (const CDataContainer *pParent)
void setPersistentTrigger (const bool &persistentTrigger)
bool setPriorityExpression (const std::string &expression)
bool setPriorityExpressionPtr (CExpression *pExpression)
void setSBMLId (const std::string &id) const
bool setTriggerExpression (const std::string &expression)
bool setTriggerExpressionPtr (CExpression *pExpression)
void setType (const Type &type)
virtual CData toData () const
~CEvent ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static CEvent * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Private Member Functions
void initObjects ()
CEvent & operator= (const CEvent &)
Private Attributes
CDataVectorN< CEventAssignment > mAssignments
bool mDelayAssignment
bool mFireAtInitialTime
CCallbackInterface * mpCallback
CExpression * mpDelayExpression
bool mPersistentTrigger
CModel * mpModel
CExpression * mpPriorityExpression
CExpression * mpTriggerExpression
std::string mSBMLId
Type mType
Friends
std::ostream & operator<< (std::ostream &os, const CEvent &d)
Additional Inherited Members
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Protected Attributes inherited from CAnnotation
std::string mKey
Member Enumeration Documentation
Type
enum CEvent::Type
Enumerator
Assignment
Discontinuity
Callback
Stop
Constructor & Destructor Documentation
CEvent() [1/2]
CEvent::CEvent (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CRootContainer::getKeyFactory(), CDataObject::getObjectType(), CAnnotation::initMiriamAnnotation(), initObjects(), and CAnnotation::mKey.
Referenced by fromData().
CEvent() [2/2]
CEvent::CEvent (const CEvent & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CEvent & src
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CDataObject::getObjectType(), initObjects(), CAnnotation::mKey, and CAnnotation::setMiriamAnnotation().
~CEvent()
CEvent::~CEvent ()
Destructor
References CRootContainer::getKeyFactory(), CAnnotation::mKey, mpDelayExpression, mpModel, mpPriorityExpression, mpTriggerExpression, pdelete, CKeyFactory::remove(), and CModel::setCompileFlag().
Member Function Documentation
appendDependentAssignments()
bool CEvent::appendDependentAssignments (std::set< const CDataObject * > candidates, std::set< const CDataObject * > & dependents) const
Appends pointers to assignments which are dependent on the candidates to the list.
Parameters
std::set< const CDataObject * > candidates
std::set< const CDataObject * > & dependents
Returns
bool objectsAppended
applyData()
bool CEvent::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CData::addProperty(), CDataVectorN< CType >::applyData(), CAnnotation::applyData(), CDataContainer::applyData(), CData::ASSIGNMENTS, CData::DELAY_ASSIGNMENT, CData::DELAY_EXPRESSION, CData::EXPRESSION, CData::FIRE_AT_INITIALTIME, CDataObject::getObjectAncestor(), CData::getProperty(), CData::isSetProperty(), mAssignments, mDelayAssignment, mFireAtInitialTime, mPersistentTrigger, CData::PERSISTENT_TRIGGER, CData::PRIORITY_EXPRESSION, CModel::setCompileFlag(), setDelayExpression(), setPriorityExpression(), setTriggerExpression(), CDataValue::toBool(), CDataValue::toString(), CData::TRIGGER_EXPRESSION, and CData::VECTOR_CONTENT.
cleanup()
void CEvent::cleanup ()
Delete
compile()
CIssue CEvent::compile (CObjectInterface::ContainerList listOfContainer)
Compile the event.
Parameters
CObjectInterface::ContainerList listOfContainer
Returns
CIssue issue
References CValidity::add(), CDataVector< CType >::begin(), CValidity::clear(), CExpression::compile(), CDataVector< CType >::empty(), CDataVector< CType >::end(), CIssue::Error, CIssue::EventMissingAssignment, CIssue::EventMissingTriggerExpression, CValidity::getFirstWorstIssue(), CDataObject::getPrerequisites(), mAssignments, mpDelayExpression, mpPriorityExpression, CDataObject::mPrerequisits, mpTriggerExpression, CObjectInterface::mValidity, and CIssue::Warning.
Referenced by CAnalyticsTask::createEvent(), and CCrossSectionTask::createEvent().
createUndoData()
void CEvent::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CUndoData::addPostProcessData(), CUndoData::addPreProcessData(), CUndoData::addProperty(), CData::addProperty(), CData::ASSIGNMENTS, CUndoData::CHANGE, CDataVectorN< CType >::createUndoData(), CAnnotation::createUndoData(), CDataContainer::createUndoData(), CData::DELAY_ASSIGNMENT, CData::DELAY_EXPRESSION, CData::FIRE_AT_INITIALTIME, getDelayExpression(), CUndoData::getNewData(), CUndoData::getOldData(), CUndoData::getPostProcessData(), CUndoData::getPreProcessData(), getPriorityExpression(), CData::getProperty(), getTriggerExpression(), CUndoData::isChangedProperty(), mAssignments, mDelayAssignment, mFireAtInitialTime, mPersistentTrigger, CData::PERSISTENT_TRIGGER, CData::PRIORITY_EXPRESSION, CData::TRIGGER_EXPRESSION, and CData::VECTOR_CONTENT.
Referenced by CModelExpansion::duplicateEvent().
deleteAssignment()
void CEvent::deleteAssignment (const std::string & key)
Delete assignment with the given key. Please note this is not the target key.
Parameters
const std::string & key
References CKeyFactory::get(), CRootContainer::getKeyFactory(), and mAssignments.
fromData()
CEvent * CEvent::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CEvent * pDataObject
References CEvent(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getAssignments() [1/2]
CDataVectorN< CEventAssignment > & CEvent::getAssignments ()
Retrieve the assignments
Returns
CDataVectorN< CEventAssignment > & assignments
References mAssignments.
getAssignments() [2/2]
const CDataVectorN< CEventAssignment > & CEvent::getAssignments () const
Retrieve the assignments
Returns
const CDataVectorN< CEventAssignment > & assignments
References mAssignments.
Referenced by CModelAdd::addEvents(), CMathEvent::allocate(), CModel::appendDirectDependents(), CMathEvent::compile(), CModel::createEventsForTimeseries(), CModelExpansion::duplicateEvent(), SBMLImporter::importEvent(), CSBMLExporter::isEventSBMLCompatible(), AssignmentHandler::processStart(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInEvent(), and CCopasiXML::saveModel().
getDelayAssignment()
const bool & CEvent::getDelayAssignment () const
Retrieve whether to delay the calculation of the assignment.
Returns
const bool & delayCalculation
References mDelayAssignment.
Referenced by CModelAdd::addEvents(), CMathEvent::compile(), CSBMLExporter::createEvent(), CModelExpansion::duplicateEvent(), and CCopasiXML::saveModel().
getDelayExpression()
std::string CEvent::getDelayExpression () const
Retrieve the expression of the delay as a string.
Returns
std::string expression
References CEvaluationTree::getInfix(), mpDelayExpression, and CExpression::updateInfix().
Referenced by CMathEvent::compile(), createUndoData(), CModelExpansion::duplicateEvent(), CCopasiXML::saveModel(), and toData().
getDelayExpressionPtr() [1/2]
CExpression * CEvent::getDelayExpressionPtr ()
Retrieve the pointer to the expression of the delay.
Returns
CExpression* pExpression
References mpDelayExpression, and CExpression::updateInfix().
Referenced by CModelAdd::addEvents(), CMathEvent::compile(), CModelAdd::copyDelayExpression(), CModelExpansion::duplicateEvent(), CSBMLExporter::isEventSBMLCompatible(), SBMLImporter::removeUnusedFunctions(), and CModelExpansion::replaceInEvent().
getDelayExpressionPtr() [2/2]
const CExpression * CEvent::getDelayExpressionPtr () const
Retrieve the pointer to the expression of the delay.
Returns
CExpression* pExpression
References mpDelayExpression, and CExpression::updateInfix().
getFireAtInitialTime()
const bool & CEvent::getFireAtInitialTime () const
Retrieve whether the trigger may fire at the initial time.
Returns
const bool & fireAtInitialTime
References mFireAtInitialTime.
Referenced by CMathEvent::compile(), CSBMLExporter::createEvent(), CModelExpansion::duplicateEvent(), and CCopasiXML::saveModel().
getKey()
const std::string & CEvent::getKey () const virtual
Retrieves the key of the event
Returns
std::string key
Reimplemented from CAnnotation.
References CAnnotation::getKey().
Referenced by CModelExpansion::duplicateEvent(), EventHandler::processEnd(), and CCopasiXML::saveModel().
getObjectDisplayName()
std::string CEvent::getObjectDisplayName () const virtual
Retrieve display name. Special treatment for reaction to provide a shorter display
Reimplemented from CDataObject.
References CDataObject::getObjectAncestor(), CDataObject::getObjectDisplayName(), and CDataObject::getObjectName().
getOriginFor()
std::string CEvent::getOriginFor (const DataObjectSet & deletedObjects) const
Return information where the element in the object set is being used.
Parameters
deletedObjects an object set that is used by the event
Returns
a string representing how the object is being used, this will be one of "Unused", "Trigger", "Priority", "Delay", "EventAssignment Expression" or "EventAssignment Target"
References CDataVector< CType >::begin(), CEvaluationTree::containsCN(), CDataVector< CType >::end(), CDataObject::getCN(), CEventAssignment::getExpressionPtr(), CDataObject::getObjectDisplayName(), CEventAssignment::getTargetObject(), mAssignments, mpDelayExpression, mpPriorityExpression, mpTriggerExpression, and CDataObject::Separator.
getPersistentTrigger()
const bool & CEvent::getPersistentTrigger () const
Retrieve whether the trigger must remain true between firing and executions.
Returns
const bool & persistentTrigger
References mPersistentTrigger.
Referenced by CMathEvent::compile(), CSBMLExporter::createEvent(), CModelExpansion::duplicateEvent(), and CCopasiXML::saveModel().
getPriorityExpression()
std::string CEvent::getPriorityExpression () const
Retrieve the expression of the priority as a string.
Returns
std::string expression
References CEvaluationTree::getInfix(), mpPriorityExpression, and CExpression::updateInfix().
Referenced by CMathEvent::compile(), createUndoData(), CModelExpansion::duplicateEvent(), CCopasiXML::saveModel(), and toData().
getPriorityExpressionPtr() [1/2]
CExpression * CEvent::getPriorityExpressionPtr ()
Retrieve the pointer to the expression of the priority.
Returns
CExpression* pExpression
References mpPriorityExpression, and CExpression::updateInfix().
Referenced by CMathEvent::compile(), and CModelExpansion::duplicateEvent().
getPriorityExpressionPtr() [2/2]
const CExpression * CEvent::getPriorityExpressionPtr () const
Retrieve the pointer to the expression of the priority.
Returns
CExpression* pExpression
References mpPriorityExpression, and CExpression::updateInfix().
getSBMLId()
const std::string & CEvent::getSBMLId () const
Returns a reference to the SBML Id.
References mSBMLId.
Referenced by CSBMLExporter::collectIds(), CSBMLExporter::createEvent(), CSBMLExporter::exportEventAssignments(), and CCopasiXML::saveModel().
getTriggerExpression()
std::string CEvent::getTriggerExpression () const
Retrieve the expression of trigger as a string.
Returns
std::string expression
References CEvaluationTree::getInfix(), mpTriggerExpression, and CExpression::updateInfix().
Referenced by CMathEvent::CTrigger::allocate(), CMathEvent::CTrigger::compile(), createUndoData(), CModelExpansion::duplicateEvent(), CCopasiXML::saveModel(), and toData().
getTriggerExpressionPtr() [1/2]
CExpression * CEvent::getTriggerExpressionPtr ()
Retrieve the pointer to the expression of trigger.
Returns
CExpression* pExpression
References mpTriggerExpression, and CExpression::updateInfix().
getTriggerExpressionPtr() [2/2]
const CExpression * CEvent::getTriggerExpressionPtr () const
Retrieve the pointer to the expression of trigger.
Returns
CExpression* pExpression
References mpTriggerExpression, and CExpression::updateInfix().
Referenced by CModelAdd::addEvents(), CMathEvent::CTrigger::compile(), CModelAdd::copyTriggerExpression(), CModel::createEventsForTimeseries(), CModelExpansion::duplicateEvent(), CSBMLExporter::isEventSBMLCompatible(), SBMLImporter::removeUnusedFunctions(), and CModelExpansion::replaceInEvent().
getType()
const CEvent::Type & CEvent::getType () const
Retrieve the type of the event
Returns
const Type & type
References mType.
Referenced by CMathEvent::compile().
initObjects()
void CEvent::initObjects () private
References mpModel, and CModel::setCompileFlag().
Referenced by CEvent().
operator=()
CEvent& CEvent::operator= (const CEvent &) private
setDelayAssignment()
void CEvent::setDelayAssignment (const bool & delayCalculation)
Set whether the calculation or the assignment shall be delayed.
Parameters
const bool & delayCalculation
References mDelayAssignment, mpModel, and CModel::setCompileFlag().
Referenced by CModelAdd::addEvents(), CAnalyticsTask::createEvent(), CCrossSectionTask::createEvent(), CModelExpansion::duplicateEvent(), SBMLImporter::importEvent(), and EventHandler::processStart().
setDelayExpression()
bool CEvent::setDelayExpression (const std::string & expression)
Set the expression of delay from a string. The return value indicates if parsing the expression was successful.
Parameters
const std::string & expression
Returns
bool success
References CEvaluationTree::getInfix(), mpDelayExpression, mpModel, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by applyData(), CModelAdd::copyDelayExpression(), CModelExpansion::duplicateEvent(), and EventHandler::processEnd().
setDelayExpressionPtr()
bool CEvent::setDelayExpressionPtr (CExpression * pExpression)
Set the expression of delay from an expression.
Parameters
CExpression* pExpression
Returns
bool success
References CDataContainer::add(), CExpression::compile(), mpDelayExpression, mpModel, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
Referenced by SBMLImporter::importEvent().
setFireAtInitialTime()
void CEvent::setFireAtInitialTime (const bool & fireAtInitialTime)
Set whether the trigger may fire at the initial time.
Parameters
const bool & fireAtInitialTime
References mFireAtInitialTime, mpModel, and CModel::setCompileFlag().
Referenced by CModelExpansion::duplicateEvent(), SBMLImporter::importEvent(), and EventHandler::processStart().
setObjectParent()
bool CEvent::setObjectParent (const CDataContainer * pParent) virtual
Set the object parent
Parameters
const CDataContainer * pParent
Returns
bool success
Reimplemented from CDataObject.
References CDataObject::getObjectAncestor(), CDataObject::getObjectParent(), mpModel, CModel::setCompileFlag(), and CDataObject::setObjectParent().
setPersistentTrigger()
void CEvent::setPersistentTrigger (const bool & persistentTrigger)
Set whether the trigger must remain true between firing and executions.
Parameters
const bool & persistentTrigger
References mPersistentTrigger, mpModel, and CModel::setCompileFlag().
Referenced by CAnalyticsTask::createEvent(), CCrossSectionTask::createEvent(), CModelExpansion::duplicateEvent(), SBMLImporter::importEvent(), and EventHandler::processStart().
setPriorityExpression()
bool CEvent::setPriorityExpression (const std::string & expression)
Set the expression of priority from a string. The return value indicates if parsing the expression was successful.
Parameters
const std::string & expression
Returns
bool success
References CEvaluationTree::getInfix(), mpModel, mpPriorityExpression, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by applyData(), CModelExpansion::duplicateEvent(), and EventHandler::processEnd().
setPriorityExpressionPtr()
bool CEvent::setPriorityExpressionPtr (CExpression * pExpression)
Set the expression of priority from an expression.
Parameters
CExpression* pExpression
Returns
bool success
References CDataContainer::add(), CExpression::compile(), mpModel, mpPriorityExpression, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
Referenced by SBMLImporter::importEvent().
setSBMLId()
void CEvent::setSBMLId (const std::string & id) const
Sets the SBMLId.
Parameters
const std::string & id
References mSBMLId.
Referenced by SBMLImporter::importEvent().
setTriggerExpression()
bool CEvent::setTriggerExpression (const std::string & expression)
Set the expression of trigger from a string. The return value indicates if parsing the expression was successful.
Parameters
const std::string & expression
Returns
bool success
References Discontinuity, CEvaluationTree::getInfix(), mpModel, mpTriggerExpression, mType, CModel::setCompileFlag(), CExpression::setInfix(), and CExpression::setIsBoolean().
Referenced by applyData(), CModelAdd::copyTriggerExpression(), CMathContainer::createDiscontinuityDataEvent(), CAnalyticsTask::createEvent(), CCrossSectionTask::createEvent(), CModel::createEventsForTimeseries(), CModelExpansion::duplicateEvent(), EventHandler::processEnd(), and CMathContainer::replaceDiscontinuousNode().
setTriggerExpressionPtr()
bool CEvent::setTriggerExpressionPtr (CExpression * pExpression)
Set the expression of trigger from an expression.
Parameters
CExpression* pExpression
Returns
bool success
References CDataContainer::add(), CExpression::compile(), mpModel, mpTriggerExpression, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
Referenced by SBMLImporter::importEvent().
setType()
void CEvent::setType (const Type & type)
Set the type of the event
Parameters
const Type & type
References mType.
Referenced by CMathContainer::createDiscontinuityDataEvent(), CAnalyticsTask::createEvent(), CCrossSectionTask::createEvent(), and CMathContainer::replaceDiscontinuousNode().
toData()
CData CEvent::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::addProperty(), CData::appendData(), CData::ASSIGNMENTS, CData::DELAY_ASSIGNMENT, CData::DELAY_EXPRESSION, CData::FIRE_AT_INITIALTIME, getDelayExpression(), getPriorityExpression(), CData::getProperty(), getTriggerExpression(), mAssignments, mDelayAssignment, mFireAtInitialTime, mPersistentTrigger, CData::PERSISTENT_TRIGGER, CData::PRIORITY_EXPRESSION, CDataVectorN< CType >::toData(), CAnnotation::toData(), CDataContainer::toData(), CData::TRIGGER_EXPRESSION, and CData::VECTOR_CONTENT.
Referenced by CModelExpansion::duplicateEvent().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CEvent & d) friend
insert operator
Member Data Documentation
mAssignments
CDataVectorN< CEventAssignment > CEvent::mAssignments private
A vector assignments expressions which specify the changes made by the event.
Referenced by applyData(), compile(), createUndoData(), deleteAssignment(), getAssignments(), getOriginFor(), and toData().
mDelayAssignment
bool CEvent::mDelayAssignment private
A Boolean flag indicating whether the calculation or the assignment should be delayed in the case that a delay is present.
Referenced by applyData(), createUndoData(), getDelayAssignment(), setDelayAssignment(), and toData().
mFireAtInitialTime
bool CEvent::mFireAtInitialTime private
A Boolean flag indicating whether the trigger may fire at the initial time if the trigger expression is true;
Referenced by applyData(), createUndoData(), getFireAtInitialTime(), setFireAtInitialTime(), and toData().
mpCallback
CCallbackInterface* CEvent::mpCallback private
A pointer to an optional callback function to be executed when the event is triggered.
mpDelayExpression
CExpression* CEvent::mpDelayExpression private
Pointer to the Delay Expression of the event
Referenced by compile(), getDelayExpression(), getDelayExpressionPtr(), getOriginFor(), setDelayExpression(), setDelayExpressionPtr(), and ~CEvent().
mPersistentTrigger
bool CEvent::mPersistentTrigger private
A Boolean flag indicating whether the trigger expression must remain true between firing and executing the event.
Referenced by applyData(), createUndoData(), getPersistentTrigger(), setPersistentTrigger(), and toData().
mpModel
CModel* CEvent::mpModel private
The parent model
Referenced by initObjects(), setDelayAssignment(), setDelayExpression(), setDelayExpressionPtr(), setFireAtInitialTime(), setObjectParent(), setPersistentTrigger(), setPriorityExpression(), setPriorityExpressionPtr(), setTriggerExpression(), setTriggerExpressionPtr(), and ~CEvent().
mpPriorityExpression
CExpression* CEvent::mpPriorityExpression private
Pointer to the Priority Expression of the event
Referenced by compile(), getOriginFor(), getPriorityExpression(), getPriorityExpressionPtr(), setPriorityExpression(), setPriorityExpressionPtr(), and ~CEvent().
mpTriggerExpression
CExpression* CEvent::mpTriggerExpression private
Pointer to the boolean Trigger Expression of the event
Referenced by compile(), getOriginFor(), getTriggerExpression(), getTriggerExpressionPtr(), setTriggerExpression(), setTriggerExpressionPtr(), and ~CEvent().
mSBMLId
std::string CEvent::mSBMLId mutable private
The id of the corresponding event in an SBML file. This value is either set upon importing an SBML file, or when the object is first exported to an SBML file.
Referenced by getSBMLId(), and setSBMLId().
mType
Type CEvent::mType private
The type of the event
Referenced by getType(), setTriggerExpression(), and setType().
The documentation for this class was generated from the following files:
CEvent.h
CEvent.cpp