COPASI API: dc_decsol.cpp File Reference
dc_decsol.cpp File Reference
#include "dc_decsol.h"
Macros
#define linal_1 linal_
Functions
int decomc_ (integer *n, doublereal *fjac, integer *ldjac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, integer *m1, integer *m2, integer *nm1, doublereal *alphn, doublereal *betan, doublereal *e2r, doublereal *e2i, integer *lde1, integer *ip2, integer *ier, integer *ijob)
int decomr_ (integer *n, doublereal *fjac, integer *ldjac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, integer *m1, integer *m2, integer *nm1, doublereal *fac1, doublereal *e1, integer *lde1, integer *ip1, integer *ier, integer *ijob, logical *calhes, integer *iphes)
int estrad_ (integer *n, doublereal *fjac, integer *ldjac, integer *mljac, integer *mujac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, doublereal *h__, doublereal *dd1, doublereal *dd2, doublereal *dd3, CRadau5::evalF fcn, integer *nfcn, doublereal *y0, doublereal *y, integer *ijob, doublereal *x, integer *m1, integer *m2, integer *nm1, doublereal *e1, integer *lde1, doublereal *z1, doublereal *z2, doublereal *z3, doublereal *cont, doublereal *f1, doublereal *f2, integer *ip1, integer *iphes, doublereal *scal, doublereal *err, logical *first, logical *reject, doublereal *fac1, doublereal *rpar, integer *ipar)
int estrav_ (integer *n, doublereal *fjac, integer *ldjac, integer *mljac, integer *mujac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, doublereal *h__, doublereal *dd, S_fp fcn, integer *nfcn, doublereal *y0, doublereal *y, integer *ijob, doublereal *x, integer *m1, integer *m2, integer *nm1, integer *ns, integer *nns, doublereal *e1, integer *lde1, doublereal *zz, doublereal *cont, doublereal *ff, integer *ip1, integer *iphes, doublereal *scal, doublereal *err, logical *first, logical *reject, doublereal *fac1, doublereal *rpar, integer *ipar)
int slvrad_ (integer *n, doublereal *fjac, integer *ldjac, integer *mljac, integer *mujac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, integer *m1, integer *m2, integer *nm1, doublereal *fac1, doublereal *alphn, doublereal *betan, doublereal *e1, doublereal *e2r, doublereal *e2i, integer *lde1, doublereal *z1, doublereal *z2, doublereal *z3, doublereal *f1, doublereal *f2, doublereal *f3, doublereal *cont, integer *ip1, integer *ip2, integer *iphes, integer *ier, integer *ijob)
int slvrai_ (integer *n, doublereal *fjac, integer *ldjac, integer *mljac, integer *mujac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, integer *m1, integer *m2, integer *nm1, doublereal *alphn, doublereal *betan, doublereal *e2r, doublereal *e2i, integer *lde1, doublereal *z2, doublereal *z3, doublereal *f2, doublereal *f3, doublereal *cont, integer *ip2, integer *iphes, integer *ier, integer *ijob)
int slvrar_ (integer *n, doublereal *fjac, integer *ldjac, integer *mljac, integer *mujac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, integer *m1, integer *m2, integer *nm1, doublereal *fac1, doublereal *e1, integer *lde1, doublereal *z1, doublereal *f1, integer *ip1, integer *iphes, integer *ier, integer *ijob)
int slvrod_ (integer *n, doublereal *fjac, integer *ldjac, integer *mljac, integer *mujac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, integer *m1, integer *m2, integer *nm1, doublereal *fac1, doublereal *e, integer *lde, integer *ip, doublereal *dy, doublereal *ak, doublereal *fx, doublereal *ynew, doublereal *hd, integer *ijob, logical *stage1)
int slvseu_ (integer *n, doublereal *fjac, integer *ldjac, integer *mljac, integer *mujac, doublereal *fmas, integer *ldmas, integer *mlmas, integer *mumas, integer *m1, integer *m2, integer *nm1, doublereal *fac1, doublereal *e, integer *lde, integer *ip, integer *iphes, doublereal *del, integer *ijob)
Macro Definition Documentation
linal_1
#define linal_1 linal_
Function Documentation
decomc_()
int decomc_ (integer * n, doublereal * fjac, integer * ldjac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, integer * m1, integer * m2, integer * nm1, doublereal * alphn, doublereal * betan, doublereal * e2r, doublereal * e2i, integer * lde1, integer * ip2, integer * ier, integer * ijob)
References decbc_(), decc_(), dechc_(), linal_1, max, and min.
Referenced by radcor_().
decomr_()
int decomr_ (integer * n, doublereal * fjac, integer * ldjac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, integer * m1, integer * m2, integer * nm1, doublereal * fac1, doublereal * e1, integer * lde1, integer * ip1, integer * ier, integer * ijob, logical * calhes, integer * iphes)
References dec_(), decb_(), dech_(), elmhes_(), linal_1, max, and min.
Referenced by radcor_().
estrad_()
int estrad_ (integer * n, doublereal * fjac, integer * ldjac, integer * mljac, integer * mujac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, doublereal * h__, doublereal * dd1, doublereal * dd2, doublereal * dd3, CRadau5::evalF fcn, integer * nfcn, doublereal * y0, doublereal * y, integer * ijob, doublereal * x, integer * m1, integer * m2, integer * nm1, doublereal * e1, integer * lde1, doublereal * z1, doublereal * z2, doublereal * z3, doublereal * cont, doublereal * f1, doublereal * f2, integer * ip1, integer * iphes, doublereal * scal, doublereal * err, logical * first, logical * reject, doublereal * fac1, doublereal * rpar, integer * ipar)
References linal_1, max, min, sol_(), solb_(), and solh_().
Referenced by radcor_().
estrav_()
int estrav_ (integer * n, doublereal * fjac, integer * ldjac, integer * mljac, integer * mujac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, doublereal * h__, doublereal * dd, S_fp fcn, integer * nfcn, doublereal * y0, doublereal * y, integer * ijob, doublereal * x, integer * m1, integer * m2, integer * nm1, integer * ns, integer * nns, doublereal * e1, integer * lde1, doublereal * zz, doublereal * cont, doublereal * ff, integer * ip1, integer * iphes, doublereal * scal, doublereal * err, logical * first, logical * reject, doublereal * fac1, doublereal * rpar, integer * ipar)
References linal_1, max, min, sol_(), solb_(), and solh_().
slvrad_()
int slvrad_ (integer * n, doublereal * fjac, integer * ldjac, integer * mljac, integer * mujac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, integer * m1, integer * m2, integer * nm1, doublereal * fac1, doublereal * alphn, doublereal * betan, doublereal * e1, doublereal * e2r, doublereal * e2i, integer * lde1, doublereal * z1, doublereal * z2, doublereal * z3, doublereal * f1, doublereal * f2, doublereal * f3, doublereal * cont, integer * ip1, integer * ip2, integer * iphes, integer * ier, integer * ijob)
References linal_1, max, min, sol_(), solb_(), solbc_(), solc_(), solh_(), and solhc_().
Referenced by radcor_().
slvrai_()
int slvrai_ (integer * n, doublereal * fjac, integer * ldjac, integer * mljac, integer * mujac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, integer * m1, integer * m2, integer * nm1, doublereal * alphn, doublereal * betan, doublereal * e2r, doublereal * e2i, integer * lde1, doublereal * z2, doublereal * z3, doublereal * f2, doublereal * f3, doublereal * cont, integer * ip2, integer * iphes, integer * ier, integer * ijob)
References linal_1, max, min, solbc_(), solc_(), and solhc_().
slvrar_()
int slvrar_ (integer * n, doublereal * fjac, integer * ldjac, integer * mljac, integer * mujac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, integer * m1, integer * m2, integer * nm1, doublereal * fac1, doublereal * e1, integer * lde1, doublereal * z1, doublereal * f1, integer * ip1, integer * iphes, integer * ier, integer * ijob)
References linal_1, max, min, sol_(), solb_(), and solh_().
slvrod_()
int slvrod_ (integer * n, doublereal * fjac, integer * ldjac, integer * mljac, integer * mujac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, integer * m1, integer * m2, integer * nm1, doublereal * fac1, doublereal * e, integer * lde, integer * ip, doublereal * dy, doublereal * ak, doublereal * fx, doublereal * ynew, doublereal * hd, integer * ijob, logical * stage1)
References linal_1, max, min, sol_(), and solb_().
slvseu_()
int slvseu_ (integer * n, doublereal * fjac, integer * ldjac, integer * mljac, integer * mujac, doublereal * fmas, integer * ldmas, integer * mlmas, integer * mumas, integer * m1, integer * m2, integer * nm1, doublereal * fac1, doublereal * e, integer * lde, integer * ip, integer * iphes, doublereal * del, integer * ijob)
References linal_1, max, min, sol_(), solb_(), and solh_().
Variable Documentation
mbb
integer mbb
mbdiag
integer mbdiag
mbjac
integer mbjac
mdiag
integer mdiag
mdiff
integer mdiff
mle
integer mle
mue
integer mue