COPASI API: CReaction Class Reference
CReaction Class Reference
#include <CReaction.h>
Public Types
enum class KineticLawUnit { Default , AmountPerTime , ConcentrationPerTime , __SIZE }
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Public Member Functions
bool addModifier (const std::string &metabKey, const C_FLOAT64 &multiplicity=1.0)
bool addParameterObject (const size_t &index, const CDataObject *object)
bool addParameterObject (const std::string &name, const CDataObject *object)
bool addProduct (const std::string &metabKey, const C_FLOAT64 &multiplicity=1.0)
bool addSubstrate (const std::string &metabKey, const C_FLOAT64 &multiplicity=1.0)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CIssue compile ()
CReaction (const CReaction &src, const CDataContainer *pParent)
CReaction (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
CFunction * createFunctionFromExpression (const std::string &infix)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const CCallParameters< C_FLOAT64 > & getCallParameters () const
CChemEq & getChemEq ()
const CChemEq & getChemEq () const
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
size_t getCompartmentNumber () const
std::string getDefaultNoiseExpression () const
KineticLawUnit getEffectiveKineticLawUnitType () const
CEvaluationNode * getExpressionTree ()
const C_FLOAT64 & getFlux () const
CDataObject * getFluxReference ()
const CDataObject * getFluxReference () const
const CFunction * getFunction () const
const CFunctionParameters & getFunctionParameters () const
virtual const std::string & getKey () const
std::string getKineticLawUnit () const
const KineticLawUnit & getKineticLawUnitType () const
const CCompartment * getLargestCompartment () const
const CFunctionParameterMap & getMap () const
std::string getNoiseExpression () const
CExpression * getNoiseExpressionPtr ()
const CExpression * getNoiseExpressionPtr () const
const CDataObject * getNoiseReference () const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
virtual std::string getObjectDisplayName () const
const std::vector< std::vector< CRegisteredCommonName > > & getParameterCNs () const
const std::vector< CRegisteredCommonName > & getParameterCNs (const size_t &index) const
const std::vector< CRegisteredCommonName > & getParameterCNs (const std::string &name) const
size_t getParameterIndex (const std::string &parameterName, const CFunctionParameter **ppFunctionParameter=NULL) const
const std::vector< std::vector< const CDataObject * > > & getParameterObjects () const
const std::vector< const CDataObject * > & getParameterObjects (const size_t &index) const
const std::vector< const CDataObject * > & getParameterObjects (const std::string &name) const
CCopasiParameterGroup & getParameters ()
const CCopasiParameterGroup & getParameters () const
const C_FLOAT64 & getParameterValue (const std::string &parameterName) const
const C_FLOAT64 & getParticleFlux () const
CDataObject * getParticleFluxReference ()
const CDataObject * getParticleFluxReference () const
const CDataObject * getParticleNoiseReference () const
CDataObject * getPropensityReference ()
const CDataObject * getPropensityReference () const
std::string getReactionScheme () const
const std::string & getSBMLId () const
const CCompartment * getScalingCompartment () const
const CCommonName & getScalingCompartmentCN () const
const bool & hasNoise () const
const bool & isFast () const
bool isLocalParameter (const size_t &index) const
bool isLocalParameter (const std::string &parameterName) const
bool isReversible () const
C_INT32 load (CReadConfig &configbuffer)
void printDebug () const
void setFast (const bool &fast)
bool setFunction (CFunction *pFunction)
bool setFunction (const std::string &functionName)
CFunction * setFunctionFromExpressionTree (const CExpression &tree, std::map< const CDataObject *, SBase * > &copasi2sbmlmap)
void setHasNoise (const bool &hasNoise)
void setKineticLawUnitType (const KineticLawUnit &kineticLawUnitType)
bool setNoiseExpression (const std::string &expression)
bool setNoiseExpressionPtr (CExpression *pExpression)
virtual bool setObjectParent (const CDataContainer *pParent)
bool setParameterCNs (const size_t &index, const std::vector< CRegisteredCommonName > &CNs)
bool setParameterCNs (const std::string &name, const std::vector< CRegisteredCommonName > &CNs)
bool setParameterObject (const size_t &index, const CDataObject *object)
bool setParameterObject (const std::string &name, const CDataObject *object)
bool setParameterObjects (const size_t &index, const std::vector< const CDataObject * > &objects)
bool setParameterObjects (const std::string &name, const std::vector< const CDataObject * > &objects)
void setParameterValue (const std::string &parameterName, const C_FLOAT64 &value)
bool setReactionScheme (const std::string &scheme, const std::string &newFunction="", bool createMetabolites=true, bool createOther=true)
void setReversible (bool reversible)
void setSBMLId (const std::string &id) const
void setScalingCompartment (const CCompartment *pCompartment)
void setScalingCompartmentCN (const std::string &compartmentCN)
virtual CData toData () const
virtual ~CReaction ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static CReaction * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Static Public Attributes
static CEnumAnnotation< std::string, KineticLawUnit > KineticLawUnitTypeName
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Private Member Functions
void calculate ()
CIssue compileFunctionParameters (std::set< const CDataObject * > &Dependencies)
std::string escapeId (const std::string &id)
const CModel * getFirstCModelOrDefault (std::map< const CDataObject *, SBase * > &copasi2sbmlmap)
void initializeParameterMapping ()
void initializeParameters ()
void initObjects ()
C_INT32 loadOld (CReadConfig &configbuffer)
bool loadOneRole (CReadConfig &configbuffer, CFunctionParameter::Role role, C_INT32 n, const std::string &prefix)
CEvaluationNodeVariable * object2variable (const CEvaluationNodeObject *objectNode, std::map< std::string, std::pair< CDataObject *, CFunctionParameter * > > &replacementMap, std::map< const CDataObject *, SBase * > &copasi2sbmlmap)
CEvaluationNode * objects2variables (const CEvaluationNode *expression, std::map< std::string, std::pair< CDataObject *, CFunctionParameter * > > &replacementMap, std::map< const CDataObject *, SBase * > &copasi2sbmlmap)
CReaction & operator= (const CReaction &)
CDataObject * resolveCN (const CModel *pModel, CCommonName cn)
void setScalingFactor ()
CEvaluationNodeObject * variable2object (CEvaluationNodeVariable *pVariableNode)
CEvaluationNode * variables2objects (CEvaluationNode *expression)
Static Private Member Functions
static std::string sanitizeSBMLId (const std::string &id)
Private Attributes
CChemEq mChemEq
bool mFast
C_FLOAT64 mFlux
bool mHasNoise
KineticLawUnit mKineticLawUnit
CFunctionParameterMap mMap
C_FLOAT64 mNoise
std::vector< std::vector< CRegisteredCommonName > > mParameterIndexToCNs
std::vector< std::vector< const CDataObject * > > mParameterIndexToObjects
std::map< std::string, size_t > mParameterNameToIndex
CCopasiParameterGroup mParameters
C_FLOAT64 mParticleFlux
C_FLOAT64 mParticleNoise
CDataObjectReference< C_FLOAT64 > * mpFluxReference
CFunction * mpFunction
CExpression * mpNoiseExpression
CDataObjectReference< C_FLOAT64 > * mpNoiseReference
CDataObjectReference< C_FLOAT64 > * mpParticleFluxReference
CDataObjectReference< C_FLOAT64 > * mpParticleNoiseReference
CDataObjectReference< C_FLOAT64 > * mpPropensityReference
C_FLOAT64 mPropensity
const CCompartment * mpScalingCompartment
std::string mSBMLId
CRegisteredCommonName mScalingCompartmentCN
Friends
std::ostream & operator<< (std::ostream &os, const CReaction &d)
Additional Inherited Members
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Protected Attributes inherited from CAnnotation
std::string mKey
Member Enumeration Documentation
KineticLawUnit
enum CReaction::KineticLawUnit strong
Enumerator
Default
AmountPerTime
ConcentrationPerTime
__SIZE
Constructor & Destructor Documentation
CReaction() [1/2]
CReaction::CReaction (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CRootContainer::getKeyFactory(), CDataObject::getObjectType(), CRootContainer::getUndefinedFunction(), CAnnotation::initMiriamAnnotation(), initObjects(), CAnnotation::mKey, and setFunction().
Referenced by fromData().
CReaction() [2/2]
CReaction::CReaction (const CReaction & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CReaction & src
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CDataObject::getObjectType(), initObjects(), CAnnotation::mKey, mpFunction, mScalingCompartmentCN, CAnnotation::setMiriamAnnotation(), and setScalingCompartmentCN().
~CReaction()
CReaction::~CReaction () virtual
Destructor
References CRootContainer::getKeyFactory(), CDataObject::getObjectAncestor(), CAnnotation::mKey, CKeyFactory::remove(), and CModel::setCompileFlag().
Member Function Documentation
addModifier()
bool CReaction::addModifier (const std::string & metabKey, const C_FLOAT64 & multiplicity = 1.0)
Add a modifier to the reaction
Parameters
std::string & metabKey
const C_FLOAT64 & multiplicity (Default 1.0)
Returns
bool success
References CChemEq::addMetabolite(), mChemEq, and CChemEq::MODIFIER.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::duplicateReaction(), and ModifierHandler::processStart().
addParameterObject() [1/2]
bool CReaction::addParameterObject (const size_t & index, const CDataObject * object)
References CDataObject::getCN(), CDataObject::getObjectAncestor(), mParameterIndexToCNs, mParameterIndexToObjects, and CModel::setCompileFlag().
Referenced by addParameterObject().
addParameterObject() [2/2]
bool CReaction::addParameterObject (const std::string & name, const CDataObject * object)
References addParameterObject(), and mParameterNameToIndex.
addProduct()
bool CReaction::addProduct (const std::string & metabKey, const C_FLOAT64 & multiplicity = 1.0)
Add a product to the reaction
Parameters
std::string & metabKey
const C_FLOAT64 & multiplicity (Default 1.0)
Returns
bool success
References CChemEq::addMetabolite(), mChemEq, and CChemEq::PRODUCT.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), and ProductHandler::processStart().
addSubstrate()
bool CReaction::addSubstrate (const std::string & metabKey, const C_FLOAT64 & multiplicity = 1.0)
Add a substrate to the reaction
Parameters
std::string & metabKey
const C_FLOAT64 & multiplicity (Default 1.0)
Returns
bool success
References CChemEq::addMetabolite(), mChemEq, and CChemEq::SUBSTRATE.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), and SubstrateHandler::processStart().
applyData()
bool CReaction::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CData::ADD_NOISE, CAnnotation::applyData(), CDataContainer::applyData(), CCopasiParameter::applyData(), CData::CHEMICAL_EQUATION, CChemEqInterface::fromDataValue(), CDataObject::getObjectAncestor(), CCopasiParameterGroup::getParameter(), CData::getProperty(), CChemEqInterface::init(), CData::isSetProperty(), CData::KINETIC_LAW, CData::KINETIC_LAW_UNIT_TYPE, CData::KINETIC_LAW_VARIABLE_MAPPING, KineticLawUnitTypeName, CData::LOCAL_REACTION_PARAMETERS, mChemEq, mHasNoise, mParameterNameToIndex, mParameters, CData::NOISE_EXPRESSION, CData::OBJECT_NAME, CData::PARAMETER_VALUE, CData::SCALING_COMPARTMENT, CModel::setCompileFlag(), setFunction(), setKineticLawUnitType(), setNoiseExpression(), setParameterCNs(), setScalingCompartmentCN(), CDataValue::toBool(), toData(), CDataValue::toDataVector(), toEnum(), CDataValue::toString(), and CChemEqInterface::writeToChemEq().
calculate()
void CReaction::calculate () private
Calculate the kinetic function
compile()
CIssue CReaction::compile ()
Compile the reaction, i.e., links the metabolites and parameters with the rate function. The connection of the reaction and the function parameter mapping to the actual metabolites is established (before compile() the chemical equation and the reaction only hold the names of the metabolites).
Returns
bool success
References CValidity::add(), CFlags< Enum >::All, CDataVector< CType >::begin(), CExpression::compile(), compileFunctionParameters(), CDataVector< CType >::end(), CChemEq::getModifiers(), CDataObject::getObjectAncestor(), CDataObject::getObjectName(), CChemEq::getProducts(), CChemEq::getSubstrates(), CRootContainer::getUndefinedFunction(), CReactionInterface::init(), CIssue::KineticsUndefined, mChemEq, mFlux, mHasNoise, mParticleFlux, mpFunction, mpNoiseExpression, CDataObject::mPrerequisits, CObjectInterface::mValidity, CIssue::ObjectNotFound, CValidity::remove(), CReactionInterface::setFunctionAndDoMapping(), setScalingFactor(), CIssue::VariablesMismatch, CIssue::Warning, and CReactionInterface::writeBackToReaction().
Referenced by CModel::convert2NonReversible(), CModelExpansion::replaceInReaction(), and setNoiseExpressionPtr().
compileFunctionParameters()
CIssue CReaction::compileFunctionParameters (std::set< const CDataObject * > & Dependencies) private
References CValidity::add(), CFunctionParameterMap::addCallParameter(), CFlags< Enum >::All, CFunctionParameterMap::clearCallParameter(), CObjectInterface::DataObject(), CIssue::Error, CFunctionParameterMap::getFunctionParameters(), getFunctionParameters(), CDataObject::getObjectAncestor(), CDataObject::getObjectFromCN(), CDataObject::getObjectName(), CDataObject::getValueObject(), CUndoObjectInterface::insert(), mMap, mParameterIndexToCNs, mParameterIndexToObjects, CObjectInterface::mValidity, CIssue::ObjectNotFound, CFunctionParameterMap::pUnmappedObject, CValidity::remove(), resolveCN(), CFunctionParameterMap::setCallParameter(), CFunctionParameters::size(), CIssue::VariablesMismatch, and CFunctionParameter::VINT32.
Referenced by compile().
createFunctionFromExpression()
CFunction * CReaction::createFunctionFromExpression (const std::string & infix)
Creates a kinetic function and sets it for the reaction
Parameters
const string & infix
Returns
CFunction * pFunction
References CFunctionDB::addAndAdaptName(), CDataVector< CType >::begin(), CFunctionParameters::begin(), CDataVector< CType >::end(), CFunctionParameters::end(), CCopasiMessage::ERROR, CChemEq::getCompartments(), CRootContainer::getFunctionList(), CChemEq::getModifiers(), CMetab::getObjectDisplayName(), CDataObject::getObjectName(), CChemEq::getProducts(), CChemEq::getSubstrates(), CFunction::getVariables(), mChemEq, MCReaction, CFunctionParameter::MODIFIER, CFunctionParameter::PARAMETER, CFunctionParameter::PRODUCT, CFunction::setInfix(), CDataObject::setObjectName(), CFunctionParameter::SUBSTRATE, CFunctionParameter::TIME, CFunctionParameter::VARIABLE, and CFunctionParameter::VOLUME.
createUndoData()
void CReaction::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CData::ADD_NOISE, CUndoData::addProperty(), CData::addProperty(), CFunctionParameters::begin(), CCopasiParameterGroup::beginName(), C_FLOAT64, CUndoData::CHANGE, CData::CHEMICAL_EQUATION, CAnnotation::createUndoData(), CDataContainer::createUndoData(), CCopasiParameterGroup::endName(), CEvaluationTree::getInfix(), CDataObject::getObjectName(), CData::getProperty(), CFunction::getVariables(), CChemEqInterface::init(), CData::KINETIC_LAW, CData::KINETIC_LAW_UNIT_TYPE, CData::KINETIC_LAW_VARIABLE_MAPPING, KineticLawUnitTypeName, CData::LOCAL_REACTION_PARAMETERS, mChemEq, mHasNoise, mKineticLawUnit, mParameterIndexToCNs, mParameters, mpFunction, mpNoiseExpression, mScalingCompartmentCN, CData::NOISE_EXPRESSION, CData::OBJECT_NAME, CData::PARAMETER_VALUE, CData::SCALING_COMPARTMENT, CChemEqInterface::toDataValue(), and CDataValue::toDataVector().
escapeId()
std::string CReaction::escapeId (const std::string & id) private
Escapes double quotes and backslashes in a string and puts strings with tabs and spaces in double quotes.
Referenced by object2variable().
fromData()
CReaction * CReaction::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CReaction * pDataObject
References CReaction(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getCallParameters()
const CCallParameters< C_FLOAT64 > & CReaction::getCallParameters () const
Retrieve the call parameter given to the kinetic function.
Returns
const CCallParameters< C_FLOAT64 > & callParameters
References CFunctionParameterMap::getPointers(), and mMap.
Referenced by CMathObject::compileFlux().
getChemEq() [1/2]
CChemEq & CReaction::getChemEq ()
Retrieves the chemical equation of the reaction
Returns
CChemEq & chemEq
References mChemEq.
getChemEq() [2/2]
const CChemEq & CReaction::getChemEq () const
Retrieves the chemical equation of the reaction
Returns
const CChemEq & chemEq
References mChemEq.
Referenced by CModelAdd::addReactions(), CModelAnalyzer::checkReaction(), CMathObject::compilePropensity(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createKineticLaw(), CSBMLExporter::createReaction(), CLayoutInitializer::createReactionGlyph(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), SBMLImporter::findCorrespondingFunction(), CChemEqInterface::getChemEqString(), CEFMTask::getNetReactionData(), CEFMTask::getSpeciesChanges(), CReactionInterface::init(), CMathReaction::initialize(), CODEExporterC::KineticFunction2ODEmember(), CModelMerging::mergeMetabolites(), object2variable(), CModelAdd::reactionInvolvesCompartment(), CModelExpansion::replaceInReaction(), CCopasiXML::saveModel(), CChemEqInterface::setChemEqFromString(), SBMLImporter::setCorrectUsage(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), CLLayoutRenderer::update_associations(), CReactionInterface::writeBackToReaction(), and CMMLOutput::writeRHS().
getChildObjectUnits()
std::string CReaction::getChildObjectUnits (const CDataObject * pObject) const virtual
Retrieve the units of the child object.
Returns
std::string units
Reimplemented from CDataContainer.
References CDataObject::getObjectAncestor(), CDataObject::getObjectName(), CModel::getQuantityUnit(), and CModel::getTimeUnit().
getCompartmentNumber()
size_t CReaction::getCompartmentNumber () const
Retrieves the number of compartments the reaction is acting in.
Returns
"size_t" the compartment number
References CChemEq::getCompartmentNumber(), and mChemEq.
getDefaultNoiseExpression()
std::string CReaction::getDefaultNoiseExpression () const
Retrieve the default expression for the noise.
Returns
std::string expression
References CDataObject::getCN(), and mpParticleFluxReference.
Referenced by CReactionInterface::setHasNoise().
getEffectiveKineticLawUnitType()
CReaction::KineticLawUnit CReaction::getEffectiveKineticLawUnitType () const
Retrieve the effective kinetic law unit type
Returns
KineticLawUnit kineticLawUnitType
References AmountPerTime, ConcentrationPerTime, Default, CChemEq::getCompartmentNumber(), mChemEq, and mKineticLawUnit.
Referenced by CMathObject::compileFlux(), CMathObject::compileReactionNoise(), CSBMLExporter::createKineticLaw(), CODEExporter::exportReacParamsAndFuncs(), getKineticLawUnit(), setScalingFactor(), and CMMLOutput::writeRHS().
getExpressionTree()
CEvaluationNode * CReaction::getExpressionTree ()
Converts the function tree into the corresponding expression tree. All variable nodes are replaced by object nodes.
References getFunction(), and variables2objects().
getFirstCModelOrDefault()
const CModel * CReaction::getFirstCModelOrDefault (std::map< const CDataObject *, SBase * > & copasi2sbmlmap) private
Returns
the first non-null CModel from the map or the default one
References CDataObject::getObjectDataModel().
Referenced by object2variable().
getFlux()
const C_FLOAT64 & CReaction::getFlux () const
Retrieves the flux of the reaction
Returns
const C_FLOAT64 & flux
References mFlux.
getFluxReference() [1/2]
CDataObject * CReaction::getFluxReference ()
Retrieve object referencing the flux
Returns
CDataObject * fluxReference
References mpFluxReference.
Referenced by CMathObject::compileParticleFlux(), CModel::convert2NonReversible(), SBMLImporter::createCModelFromSBMLDocument(), CDataModel::findObjectByDisplayName(), CMathContainer::getMathReaction(), CModelParameterGroup::getObjectUnit(), and CMathReaction::initialize().
getFluxReference() [2/2]
const CDataObject * CReaction::getFluxReference () const
Retrieve const object referencing the flux
Returns
CDataObject * fluxReference
References mpFluxReference.
getFunction()
const CFunction * CReaction::getFunction () const
Retrieves the rate function of the reaction
Returns
"CBaseFunction &"
References mpFunction.
Referenced by CModelAdd::addReactions(), CSBMLExporter::checkForPiecewiseFunctions(), CModelAnalyzer::checkReaction(), CMathObject::compileFlux(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CSBMLExporter::createReaction(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), CODEExporterC::exportKineticFunctionGroup(), CReactionInterface::getDeletedParameters(), getExpressionTree(), CReactionInterface::init(), CODEExporterC::KineticFunction2ODEmember(), CModel::prepareElasticity(), CCopasiXML::saveModel(), SBMLImporter::setCorrectUsage(), and CMMLOutput::writeRHS().
getFunctionParameters()
const CFunctionParameters & CReaction::getFunctionParameters () const
Gets the description of what parameters the function expects.
References fatalError, CFunctionParameterMap::getFunctionParameters(), mMap, and mpFunction.
Referenced by CModelAdd::addReactions(), CModelAnalyzer::checkReaction(), compileFunctionParameters(), CFunctionAnalyzer::constructCallParametersActualValues(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CModelExpansion::duplicateReaction(), CODEExporterC::exportTitleData(), CODEExporterC::KineticFunction2ODEmember(), CModelMerging::mergeMetabolites(), CModelExpansion::replaceInReaction(), and CCopasiXML::saveModel().
getKey()
const std::string & CReaction::getKey () const virtual
Retrieves the key of the reaction
Returns
std::string key
Reimplemented from CAnnotation.
References CAnnotation::getKey().
Referenced by CLayoutInitializer::createReactionGlyph(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), CODEExporter::exportSingleFunction(), SBMLImporter::importMIRIAM(), CODEExporterBM::KineticFunction2ODEmember(), CODEExporterXPPAUT::KineticFunction2ODEmember(), ReactionHandler::processEnd(), ReactionGlyphHandler::processStart(), TextGlyphHandler::processStart(), and CCopasiXML::saveModel().
getKineticLawUnit()
std::string CReaction::getKineticLawUnit () const
Retrieve the effective kinetic law unit
Returns
std::string kineticLawUnit
References AmountPerTime, getEffectiveKineticLawUnitType(), CDataObject::getObjectAncestor(), CModel::getQuantityUnit(), CModel::getTimeUnit(), and CModel::getVolumeUnit().
Referenced by CModelParameter::getUnit().
getKineticLawUnitType()
const CReaction::KineticLawUnit & CReaction::getKineticLawUnitType () const
Retrieve the kinetic law unit type
Returns
const KineticLawUnit & kineticLawUnitType
References mKineticLawUnit.
Referenced by CModelExpansion::duplicateReaction(), CReactionInterface::init(), and CCopasiXML::saveModel().
getLargestCompartment()
const CCompartment * CReaction::getLargestCompartment () const
Retrieve the largest compartment that the reaction touches. This is time dependent it can only be called after update initial values has been called. Note for an empty reaction a NULL pointer is returned.
Returns
const CCompartment * pCompartment
References CChemEq::getLargestCompartment(), and mChemEq.
getMap()
const CFunctionParameterMap & CReaction::getMap () const
References mMap.
Referenced by CModel::prepareElasticity().
getNoiseExpression()
std::string CReaction::getNoiseExpression () const
Retrieve the expression for the noise.
Returns
std::string expression
References CEvaluationTree::getInfix(), mpNoiseExpression, and CExpression::updateInfix().
Referenced by CModelExpansion::duplicateReaction(), CReactionInterface::init(), and CCopasiXML::saveModel().
getNoiseExpressionPtr() [1/2]
CExpression * CReaction::getNoiseExpressionPtr ()
Retrieve the pointer to the expression for ODE model values.
Returns
CExpression*
References mpNoiseExpression, and CExpression::updateInfix().
getNoiseExpressionPtr() [2/2]
const CExpression * CReaction::getNoiseExpressionPtr () const
Retrieve the pointer to the expression for ODE model values.
Returns
CExpression*
References mpNoiseExpression, and CExpression::updateInfix().
Referenced by CMathObject::compileReactionParticleNoise(), and CModelExpansion::duplicateReaction().
getNoiseReference()
const CDataObject * CReaction::getNoiseReference () const
Retrieve object referencing the noise
Returns
const CDataObject * noiseReference
References mpNoiseReference.
getObject()
const CObjectInterface * CReaction::getObject (const CCommonName & cn) const virtual
We are hiding local reaction parameter which are covered by global quantities.
Parameters
const CCommonName & cn
Returns
const CObjectInterface * pObject
Reimplemented from CDataContainer.
References CDataContainer::getObject(), CDataObject::getObjectName(), CDataObject::getObjectParent(), CDataObject::hasFlag(), isLocalParameter(), mParameters, and CDataObject::StaticString.
Referenced by SBMLImporter::sbmlId2CopasiCN().
getObjectDisplayName()
std::string CReaction::getObjectDisplayName () const virtual
Overload display name. Special treatment for reaction to provide a shorter display
Reimplemented from CDataObject.
References CDataObject::getObjectAncestor(), CDataObject::getObjectDisplayName(), and CDataObject::getObjectName().
getParameterCNs() [1/3]
const std::vector< std::vector< CRegisteredCommonName > > & CReaction::getParameterCNs () const
References mParameterIndexToCNs.
Referenced by getParameterCNs().
getParameterCNs() [2/3]
const std::vector< CRegisteredCommonName > & CReaction::getParameterCNs (const size_t & index) const
References mParameterIndexToCNs.
Referenced by CModel::convert2NonReversible().
getParameterCNs() [3/3]
const std::vector< CRegisteredCommonName > & CReaction::getParameterCNs (const std::string & name) const
References getParameterCNs(), and mParameterNameToIndex.
getParameterIndex()
size_t CReaction::getParameterIndex (const std::string & parameterName, const CFunctionParameter ** ppFunctionParameter = NULL) const
Retrieve the index of the given parameter name in the function call. If pType is not NULL the type of the parameter is returned
Parameters
const std::string & parameterName
const CFunctionParameter ** ppFunctionParameter (default: NULL)
Returns
size_t index;
Retrieve the index of the given parameter name in the function call
Parameters
const std::string & parameterName
Returns
size_t index;
References CFunctionParameterMap::findParameterByName(), and mMap.
Referenced by SBMLImporter::findCorrespondingFunction(), CDataModel::findObjectByDisplayName(), CModelParameterGroup::getObjectUnit(), initializeParameters(), and variable2object().
getParameterObjects() [1/3]
const std::vector< std::vector< const CDataObject * > > & CReaction::getParameterObjects () const
References mParameterIndexToObjects.
Referenced by getParameterObjects().
getParameterObjects() [2/3]
const std::vector< const CDataObject * > & CReaction::getParameterObjects (const size_t & index) const
References mParameterIndexToObjects.
Referenced by CModelAnalyzer::checkReaction(), CFunctionAnalyzer::constructCallParametersActualValues(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), CDataModel::findObjectByDisplayName(), CODEExporterC::KineticFunction2ODEmember(), CReactionInterface::loadMappingAndValues(), CModelExpansion::replaceInReaction(), and CCopasiXML::saveModel().
getParameterObjects() [3/3]
const std::vector< const CDataObject * > & CReaction::getParameterObjects (const std::string & name) const
References C_INVALID_INDEX, getParameterObjects(), and mParameterNameToIndex.
getParameters() [1/2]
CCopasiParameterGroup & CReaction::getParameters ()
Gets the list of kinetic parameter objects of the reaction/function
References mParameters.
getParameters() [2/2]
const CCopasiParameterGroup & CReaction::getParameters () const
Gets the list of kinetic parameter objects of the reaction/function
References mParameters.
Referenced by CModelAnalyzer::checkReaction(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CReactionInterface::createUndoData(), CModelExpansion::duplicateReaction(), CODEExporter::exportReacParamsAndFuncs(), CReactionInterface::getDeletedParameters(), CReactionInterface::init(), CReactionInterface::loadMappingAndValues(), ConstantHandler::processStart(), CCopasiXML::saveModel(), and CReactionInterface::writeBackToReaction().
getParameterValue()
const C_FLOAT64 & CReaction::getParameterValue (const std::string & parameterName) const
Retrieves a parameter value
References C_FLOAT64, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), and mParameters.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), and CModelExpansion::duplicateReaction().
getParticleFlux()
const C_FLOAT64 & CReaction::getParticleFlux () const
Retrieves the scaled flux of the reaction
Returns
const C_FLOAT64 & scaledFlux
References mParticleFlux.
getParticleFluxReference() [1/2]
CDataObject * CReaction::getParticleFluxReference ()
Retrieve object referencing the particle flux
Returns
CDataObject * particleFluxReference
References mpParticleFluxReference.
Referenced by CMathObject::compilePropensity(), CModel::convert2NonReversible(), CDataModel::findObjectByDisplayName(), and CMathReaction::initialize().
getParticleFluxReference() [2/2]
const CDataObject * CReaction::getParticleFluxReference () const
Retrieve const object referencing the particle flux
Returns
CDataObject * particleFluxReference
References mpParticleFluxReference.
getParticleNoiseReference()
const CDataObject * CReaction::getParticleNoiseReference () const
Retrieve object referencing the particle noise
Returns
const CDataObject * particleNoiseReference
References mpParticleNoiseReference.
Referenced by CMathObject::compileReactionNoise().
getPropensityReference() [1/2]
CDataObject * CReaction::getPropensityReference ()
Retrieve object referencing the propensity
Returns
CDataObject * propensityReference
References mpPropensityReference.
Referenced by CMathReaction::initialize().
getPropensityReference() [2/2]
const CDataObject * CReaction::getPropensityReference () const
Retrieve object referencing the propensity
Returns
CDataObject * propensityReference
References mpPropensityReference.
getReactionScheme()
std::string CReaction::getReactionScheme () const
Returns
the reaction scheme of this reaction
References CReactionInterface::getChemEqString(), CDataObject::getObjectDataModel(), and CReactionInterface::init().
getSBMLId()
const std::string & CReaction::getSBMLId () const
Returns a reference to the SBML Id.
References mSBMLId.
Referenced by SBMLImporter::applyStoichiometricExpressions(), CSBMLExporter::collectIds(), SBMLImporter::createCModelFromSBMLDocument(), CSBMLExporter::createReaction(), SEDMLUtils::getXPathForObjectAndType(), object2variable(), SBMLImporter::replaceObjectNames(), CCopasiXML::saveModel(), CEvaluationNodeObject::toAST(), and VariableInfo::VariableInfo().
getScalingCompartment()
const CCompartment * CReaction::getScalingCompartment () const
Retrieve the compartment used for scaling the kinetic function
Returns
const CCompartment * scalingCompartment
References mpScalingCompartment.
Referenced by CMathObject::compile(), CMathObject::compileReactionNoise(), CSBMLExporter::createKineticLaw(), CModelExpansion::duplicateReaction(), CReactionInterface::init(), CCopasiXML::saveModel(), and CMMLOutput::writeRHS().
getScalingCompartmentCN()
const CCommonName & CReaction::getScalingCompartmentCN () const
Retrieve the CN of the scaling compartment.
Returns
const CCommonName & scalingCompartmentCN
References mScalingCompartmentCN.
hasNoise()
const bool & CReaction::hasNoise () const
Check whether noise is added to the reaction rate
Returns
const bool & hasNoise
References mHasNoise.
Referenced by CMathObject::compileReactionNoise(), CMathObject::compileReactionParticleNoise(), CModelExpansion::duplicateReaction(), CReactionInterface::init(), CCopasiXML::saveModel(), and setHasNoise().
initializeParameterMapping()
void CReaction::initializeParameterMapping () private
Initializes the mMetabNameMap vectors to the right size.
References fatalError, CFunctionParameterMap::getFunctionParameters(), CDataObject::getObjectName(), CFunctionParameter::getType(), mMap, mParameterIndexToCNs, mParameterIndexToObjects, mParameterNameToIndex, mpFunction, CFunctionParameters::size(), and CFunctionParameter::VINT32.
Referenced by setFunction().
initializeParameters()
void CReaction::initializeParameters () private
creates the mParamters List of CParameter objects. mMap needs to be initialized before.
References CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::beginIndex(), C_FLOAT64, C_INVALID_INDEX, CCopasiParameter::DOUBLE, CCopasiParameterGroup::endIndex(), fatalError, CCopasiParameter::getCN(), CFunctionParameterMap::getFunctionParameters(), CFunctionParameters::getNumberOfParametersByUsage(), CDataObject::getObjectName(), CCopasiParameterGroup::getParameter(), CFunctionParameters::getParameterByUsage(), getParameterIndex(), mMap, mParameterIndexToCNs, mParameterIndexToObjects, mParameterNameToIndex, mParameters, mpFunction, CFunctionParameter::PARAMETER, and CCopasiParameterGroup::removeParameter().
Referenced by setFunction().
initObjects()
void CReaction::initObjects () private
References CDataContainer::addObjectReference(), mFlux, mNoise, mParticleFlux, mParticleNoise, mpFluxReference, mpNoiseReference, mpParticleFluxReference, mpParticleNoiseReference, mpPropensityReference, mPropensity, and CDataObject::ValueDbl.
Referenced by CReaction().
isFast()
const bool & CReaction::isFast () const
Check whether the reaction needs to be treated as fast @ return const bool & fast
References mFast.
Referenced by CModelExpansion::duplicateReaction(), CMathReaction::isFast(), and CCopasiXML::saveModel().
isLocalParameter() [1/2]
bool CReaction::isLocalParameter (const size_t & index) const
Check whether the indexed parameter is a local parameter.
Parameters
const size_t & index
Returns
bool isLocal
References C_INVALID_INDEX, CDataObject::getObjectParent(), mParameterIndexToObjects, and mParameters.
Referenced by CModelAdd::addReactions(), CFixLocalReactionParameters::changeModel(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), CODEExporter::exportReacParamsAndFuncs(), CODEExporterC::exportTitleData(), CReactionInterface::getDeletedParameters(), getObject(), CModelParameterGroup::getObjectUnit(), isLocalParameter(), CODEExporterC::KineticFunction2ODEmember(), CReactionInterface::loadMappingAndValues(), and toData().
isLocalParameter() [2/2]
bool CReaction::isLocalParameter (const std::string & parameterName) const
Check whether the named parameter is a local parameter.
Parameters
const std::string & parameterName
Returns
bool isLocal
References isLocalParameter(), and mParameterNameToIndex.
isReversible()
bool CReaction::isReversible () const
Retrieves whether the reaction is reversible
Returns
bool
References CChemEq::getReversibility(), and mChemEq.
Referenced by CModelAdd::addReactions(), CModelAnalyzer::checkReaction(), CMathObject::compilePropensity(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createReaction(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), SBMLImporter::findCorrespondingFunction(), CEFMTask::getReactionEquation(), CModel::prepareElasticity(), CCopasiXML::saveModel(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), and setFunctionFromExpressionTree().
load()
C_INT32 CReaction::load (CReadConfig & configbuffer)
Loads an object with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
pconfigbuffer reference to a CReadConfig object.
Returns
mFail
See also
mFail
References C_INT32, CReadConfig::getVariable(), loadOld(), mChemEq, mpFunction, CReadConfig::SEARCH, CChemEqInterface::setChemEqFromString(), setFunction(), CDataObject::setObjectName(), and CChemEq::setReversibility().
loadOld()
C_INT32 CReaction::loadOld (CReadConfig & configbuffer) private
Loads a reaction from a Gepasi file
References C_FLOAT64, C_INT32, fatalError, CFunctionParameter::FLOAT64, CFunctionParameterMap::getFunctionParameters(), CFunctionParameters::getNumberOfParametersByUsage(), CDataObject::getObjectName(), CFunctionParameters::getParameterByUsage(), CFunctionParameter::getType(), CReadConfig::getVariable(), loadOneRole(), mMap, CFunctionParameter::MODIFIER, CFunctionParameter::PARAMETER, CFunctionParameter::PRODUCT, setParameterValue(), StringPrint(), and CFunctionParameter::SUBSTRATE.
Referenced by load().
loadOneRole()
bool CReaction::loadOneRole (CReadConfig & configbuffer, CFunctionParameter::Role role, C_INT32 n, const std::string & prefix) private
Used for loading Gepasi files. Loads the mapping for one role
References CChemEq::addMetabolite(), C_INT32, fatalError, CModel::findMetabByName(), CDataObject::getCN(), CFunctionParameterMap::getFunctionParameters(), CModelEntity::getKey(), CFunctionParameters::getNumberOfParametersByUsage(), CDataObject::getObjectAncestor(), CDataObject::getObjectDataModel(), CDataObject::getObjectName(), CFunctionParameters::getParameterByUsage(), CFunctionParameter::getType(), CReadConfig::getVariable(), CFunctionParameters::isVector(), mChemEq, mMap, CFunctionParameter::MODIFIER, CChemEq::MODIFIER, mParameterIndexToCNs, mParameterIndexToObjects, mParameterNameToIndex, CDataModel::pOldMetabolites, StringPrint(), and CFunctionParameter::VINT32.
Referenced by loadOld().
object2variable()
CEvaluationNodeVariable * CReaction::object2variable (const CEvaluationNodeObject * objectNode, std::map< std::string, std::pair< CDataObject *, CFunctionParameter * > > & replacementMap, std::map< const CDataObject *, SBase * > & copasi2sbmlmap) private
Converts a single object node to a variable node. The usage term of the variable nodes is recorded in terms of CFunctionParameters that are stored in the replacementMap. On failure a NULL pointer is returned.
References CEvaluationNode::DEFAULT, CCopasiMessage::ERROR, escapeId(), CCopasiMessage::EXCEPTION, CFunctionParameter::FLOAT64, getChemEq(), CEvaluationNodeObject::getData(), getFirstCModelOrDefault(), CChemEq::getModifiers(), CChemEq::getProducts(), getSBMLId(), CChemEq::getSubstrates(), MCReaction, MCSBML, CFunctionParameter::MODIFIER, CFunctionParameter::PARAMETER, CFunctionParameter::PRODUCT, resolveCN(), sanitizeSBMLId(), CDataVector< CType >::size(), CFunctionParameter::SUBSTRATE, CFunctionParameter::TIME, and CFunctionParameter::VOLUME.
Referenced by objects2variables().
objects2variables()
CEvaluationNode * CReaction::objects2variables (const CEvaluationNode * expression, std::map< std::string, std::pair< CDataObject *, CFunctionParameter * > > & replacementMap, std::map< const CDataObject *, SBase * > & copasi2sbmlmap) private
Replaces all object nodes in an expression tree by variable nodes. The usage term of the variable nodes is recorded in terms of CFunctionParameters that are stored in the replacementMap. On failure a NULL pointer is returned.
References CEvaluationNode::AVOGADRO, CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CCopasiMessage::ERROR, fatalError, CEvaluationNode::INVALID, MCReaction, CEvaluationNode::MV_FUNCTION, CNodeContextIterator< Node, Context >::next(), CEvaluationNode::OBJECT, object2variable(), CNodeContextIterator< Node, Context >::parentContextPtr(), CEvaluationNode::STRUCTURE, and CEvaluationNode::VARIABLE.
Referenced by setFunctionFromExpressionTree().
operator=()
CReaction& CReaction::operator= (const CReaction &) private
printDebug()
void CReaction::printDebug () const
resolveCN()
CDataObject * CReaction::resolveCN (const CModel * pModel, CCommonName cn) private
Parameters
pModel the model in which to resolve the cn
cn the common name, primary parts before model will be dropped
Returns
the data object for the given cn
References CObjectInterface::DataObject(), CDataContainer::getObject(), CCommonName::getObjectName(), CCommonName::getObjectType(), and CCommonName::getRemainder().
Referenced by compileFunctionParameters(), and object2variable().
sanitizeSBMLId()
std::string CReaction::sanitizeSBMLId (const std::string & id) static private
Convert SBML to a valid COPASI infix identifier
Parameters
const std::string & id
Returns
std::string
Referenced by object2variable().
setFast()
void CReaction::setFast (const bool & fast)
Set whether the reaction is to be treated as fast
Parameters
const bool & fast
References mFast.
Referenced by CModelExpansion::duplicateReaction(), and ReactionHandler::processStart().
setFunction() [1/2]
bool CReaction::setFunction (CFunction * pFunction)
Sets the rate function of the reaction
Parameters
CFunction * pFunction
Returns
bool success
References CRootContainer::getUndefinedFunction(), CFunction::getVariables(), CFunctionParameterMap::initializeFromFunctionParameters(), initializeParameterMapping(), initializeParameters(), mMap, mpFunction, and CDataObject::mPrerequisits.
setFunction() [2/2]
bool CReaction::setFunction (const std::string & functionName)
Sets the rate function of the reaction
Parameters
const string & functionName
Returns
bool success
References CCopasiMessage::ERROR, CFunctionDB::findLoadFunction(), CRootContainer::getFunctionList(), and MCReaction.
Referenced by CModelAdd::addReactions(), applyData(), CModel::convert2NonReversible(), CReaction(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), load(), KineticLawHandler::processEnd(), setFunctionFromExpressionTree(), and CReactionInterface::writeBackToReaction().
setFunctionFromExpressionTree()
CFunction * CReaction::setFunctionFromExpressionTree (const CExpression & tree, std::map< const CDataObject *, SBase * > & copasi2sbmlmap)
Converts an expression tree into a CFunction object and sets the mapping for the reaction.
References CDataContainer::add(), CFunction::addVariable(), SBMLImporter::areEqualFunctions(), CEvaluationTree::compile(), CEvaluationNode::copyBranch(), CCopasiMessage::ERROR_FILTERED, findFunction(), CRootContainer::getFunctionList(), CDataObject::getObjectName(), CEvaluationTree::getRoot(), CFunctionParameter::getType(), CFunctionParameter::getUsage(), CFunction::getVariables(), CFunction::isReversible(), isReversible(), mParameterIndexToCNs, mParameterIndexToObjects, mParameterNameToIndex, mpFunction, objects2variables(), pdelete, setFunction(), CDataObject::setObjectName(), CFunction::setReversible(), CEvaluationTree::setRoot(), TriFalse, and TriTrue.
Referenced by SBMLImporter::createCReactionFromReaction().
setHasNoise()
void CReaction::setHasNoise (const bool & hasNoise)
Set whether to add noise to the reaction rate
Parameters
const bool & hasNoise
References CDataObject::getObjectAncestor(), hasNoise(), mHasNoise, and CModel::setCompileFlag().
Referenced by CModelExpansion::duplicateReaction(), ReactionHandler::processStart(), and CReactionInterface::writeBackToReaction().
setKineticLawUnitType()
void CReaction::setKineticLawUnitType (const KineticLawUnit & kineticLawUnitType)
Set the kinetic law unit type;
Parameters
const KineticLawUnit & kineticLawUnit
References mKineticLawUnit.
Referenced by applyData(), CModelExpansion::duplicateReaction(), KineticLawHandler::processStart(), and CReactionInterface::writeBackToReaction().
setNoiseExpression()
bool CReaction::setNoiseExpression (const std::string & expression)
Set the expression expression for the noise
Parameters
const std::string & expression
Returns
bool success
References CEvaluationTree::getInfix(), CDataObject::getObjectAncestor(), mpNoiseExpression, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by applyData(), CModelExpansion::duplicateReaction(), ReactionHandler::processEnd(), and CReactionInterface::writeBackToReaction().
setNoiseExpressionPtr()
bool CReaction::setNoiseExpressionPtr (CExpression * pExpression)
Set the noise expression for ODE model values
Parameters
CExpression*
Returns
bool success
References CDataContainer::add(), compile(), CDataObject::getObjectAncestor(), mpNoiseExpression, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
setObjectParent()
bool CReaction::setObjectParent (const CDataContainer * pParent) virtual
Sets the parent of the metabolite;
Parameters
const CDataContainer * pParent
Returns
bool success
Reimplemented from CDataObject.
References CDataObject::setObjectParent().
setParameterCNs() [1/2]
bool CReaction::setParameterCNs (const size_t & index, const std::vector< CRegisteredCommonName > & CNs)
References CObjectInterface::DataObject(), CDataObject::getObjectFromCN(), mParameterIndexToCNs, mParameterIndexToObjects, and CFunctionParameterMap::pUnmappedObject.
Referenced by applyData(), CModel::convert2NonReversible(), and setParameterCNs().
setParameterCNs() [2/2]
bool CReaction::setParameterCNs (const std::string & name, const std::vector< CRegisteredCommonName > & CNs)
References mParameterNameToIndex, and setParameterCNs().
setParameterObject() [1/2]
bool CReaction::setParameterObject (const size_t & index, const CDataObject * object)
References setParameterObjects().
setParameterObject() [2/2]
bool CReaction::setParameterObject (const std::string & name, const CDataObject * object)
References setParameterObjects().
setParameterObjects() [1/2]
bool CReaction::setParameterObjects (const size_t & index, const std::vector< const CDataObject * > & objects)
References CDataObject::getObjectAncestor(), mParameterIndexToCNs, mParameterIndexToObjects, and CModel::setCompileFlag().
Referenced by CFixLocalReactionParameters::changeModel(), CModelExpansion::createDiffusionReaction(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), KineticLawHandler::processEnd(), CModelExpansion::replaceInReaction(), setParameterObject(), setParameterObjects(), CModelParameter::updateModel(), and CReactionInterface::writeBackToReaction().
setParameterObjects() [2/2]
bool CReaction::setParameterObjects (const std::string & name, const std::vector< const CDataObject * > & objects)
References mParameterNameToIndex, and setParameterObjects().
setParameterValue()
void CReaction::setParameterValue (const std::string & parameterName, const C_FLOAT64 & value)
Sets a parameter value
Parameters
const std::string & parameterName
const C_FLOAT64 & value
References fatalError, CFunctionParameters::findParameterByName(), CFunctionParameter::FLOAT64, CCopasiParameter::getCN(), CCopasiParameterGroup::getParameter(), CFunctionParameter::getType(), CFunction::getVariables(), mParameterIndexToCNs, mParameterNameToIndex, mParameters, mpFunction, and CCopasiParameter::setValue().
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), CModelExpansion::duplicateReaction(), loadOld(), and CReactionInterface::writeBackToReaction().
setReactionScheme()
bool CReaction::setReactionScheme (const std::string & scheme, const std::string & newFunction = "", bool createMetabolites = true, bool createOther = true)
Initializes this reaction from the specified reaction scheme
Parameters
scheme the new reaction scheme to be used
newFunction a candidate function to be used
createMetaboliets if true, new metabolites will be created
createOther if true, additional elements will be created as well
Returns
success / failure
Initializes this reaction from the specified reaction scheme
References CModel::compileIfNecessary(), CReactionInterface::createMetabolites(), CReactionInterface::createOtherObjects(), CDataModel::getModel(), CDataObject::getObjectDataModel(), CReactionInterface::init(), CReactionInterface::setChemEqString(), and CReactionInterface::writeBackToReaction().
setReversible()
void CReaction::setReversible (bool reversible)
Sets whether the reaction is reversible
Parameters
bool reversible
References mChemEq, and CChemEq::setReversibility().
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), and ReactionHandler::processStart().
setSBMLId()
void CReaction::setSBMLId (const std::string & id) const
Sets the SBMLId.
References mSBMLId.
Referenced by SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createReaction(), ReactionHandler::processStart(), and SBMLMapHandler::processStart().
setScalingCompartment()
void CReaction::setScalingCompartment (const CCompartment * pCompartment)
Set the compartment used for scaling the kinetic function
Parameters
const CCompartment * pCompartment
References CDataObject::getCN(), mpScalingCompartment, and mScalingCompartmentCN.
Referenced by CModelExpansion::duplicateReaction().
setScalingCompartmentCN()
void CReaction::setScalingCompartmentCN (const std::string & compartmentCN)
Set the CN of the compartment used for scaling the kinetic function
Parameters
const std::string & compartmentCN
References CDataObject::getObjectDataModel(), CObjectInterface::GetObjectFromCN(), mpScalingCompartment, and mScalingCompartmentCN.
Referenced by applyData(), CReaction(), KineticLawHandler::processStart(), and CReactionInterface::writeBackToReaction().
setScalingFactor()
void CReaction::setScalingFactor () private
Sets the scaling factor of the for the fluxes
References ConcentrationPerTime, Default, CDataObject::getCN(), CMetab::getCompartment(), getEffectiveKineticLawUnitType(), CDataObject::getObjectDataModel(), CObjectInterface::GetObjectFromCN(), CChemEq::getProducts(), CChemEq::getSubstrates(), mChemEq, mKineticLawUnit, mpScalingCompartment, mScalingCompartmentCN, and CDataVector< CType >::size().
Referenced by compile().
toData()
CData CReaction::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::ADD_NOISE, CData::addProperty(), CData::appendData(), CFunctionParameters::begin(), CCopasiParameterGroup::beginName(), CData::CHEMICAL_EQUATION, CCopasiParameterGroup::endName(), CEvaluationTree::getInfix(), CDataObject::getObjectName(), CFunction::getVariables(), CChemEqInterface::init(), isLocalParameter(), CData::KINETIC_LAW, CData::KINETIC_LAW_UNIT_TYPE, CData::KINETIC_LAW_VARIABLE_MAPPING, KineticLawUnitTypeName, CData::LOCAL_REACTION_PARAMETERS, mChemEq, mHasNoise, mKineticLawUnit, mParameterIndexToCNs, mParameters, mpFunction, mpNoiseExpression, mScalingCompartmentCN, CData::NOISE_EXPRESSION, CData::OBJECT_NAME, CData::PARAMETER_VALUE, CData::SCALING_COMPARTMENT, CAnnotation::toData(), CDataContainer::toData(), and CChemEqInterface::toDataValue().
Referenced by applyData(), and CReactionInterface::createUndoData().
variable2object()
CEvaluationNodeObject * CReaction::variable2object (CEvaluationNodeVariable * pVariableNode) private
Converts a single variable node to an object node. On failure a NULL pointer is returned.
References C_INVALID_INDEX, CEvaluationNode::CN, CObjectInterface::DataObject(), CCopasiMessage::EXCEPTION, CDataObject::getCN(), CCopasiNode< _Data >::getData(), CDataObject::getObjectFromCN(), getParameterIndex(), CFunctionParameter::getType(), MCReaction, mParameterIndexToCNs, CFunctionParameter::VFLOAT64, and CFunctionParameter::VINT32.
Referenced by variables2objects().
variables2objects()
CEvaluationNode * CReaction::variables2objects (CEvaluationNode * expression) private
Replaces all variable nodes in a function tree by object nodes. On failure a NULL pointer is returned.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::CALL, CEvaluationNode::CHOICE, CEvaluationNode::CONSTANT, CCopasiMessage::ERROR, CEvaluationNode::FUNCTION, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::INVALID, CEvaluationNode::LOGICAL, CEvaluationNode::mainType(), MCReaction, CEvaluationNode::MV_FUNCTION, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CEvaluationNode::OPERATOR, CEvaluationNode::STRUCTURE, CEvaluationNode::subType(), CEvaluationNode::VARIABLE, variable2object(), and CEvaluationNode::WHITESPACE.
Referenced by getExpressionTree().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CReaction & d) friend
Friend declaration for ostream operator
Parameters
std::ostream & os
const CReaction & d
Returns
std::ostream & os
Member Data Documentation
KineticLawUnitTypeName
CEnumAnnotation< std::string, CReaction::KineticLawUnit > CReaction::KineticLawUnitTypeName static
Referenced by applyData(), CReactionInterface::createUndoData(), createUndoData(), KineticLawHandler::processStart(), CCopasiXML::saveModel(), and toData().
mChemEq
CChemEq CReaction::mChemEq private
The chemical equation
Referenced by addModifier(), addProduct(), addSubstrate(), applyData(), compile(), createFunctionFromExpression(), createUndoData(), getChemEq(), getCompartmentNumber(), getEffectiveKineticLawUnitType(), getLargestCompartment(), isReversible(), load(), loadOneRole(), setReversible(), setScalingFactor(), and toData().
mFast
bool CReaction::mFast private
This flag indicates whether the reaction is treated as fast. The interpretation of fast is up to to the integration algorithm.
Referenced by isFast(), and setFast().
mFlux
C_FLOAT64 CReaction::mFlux private
The flux of the reaction, as amount of substance/time
Referenced by compile(), getFlux(), and initObjects().
mHasNoise
bool CReaction::mHasNoise private
A Boolean flag indicating whether to add noise to the reaction
Referenced by applyData(), compile(), createUndoData(), hasNoise(), setHasNoise(), and toData().
mKineticLawUnit
KineticLawUnit CReaction::mKineticLawUnit private
This indicates what the units of the kinetic law are
Referenced by createUndoData(), getEffectiveKineticLawUnitType(), getKineticLawUnitType(), setKineticLawUnitType(), setScalingFactor(), and toData().
mMap
CFunctionParameterMap CReaction::mMap private
This describes the mapping of the species and parameters to the function parameters. Here are the pointers to the actual objects and values.
Referenced by compileFunctionParameters(), getCallParameters(), getFunctionParameters(), getMap(), getParameterIndex(), initializeParameterMapping(), initializeParameters(), loadOld(), loadOneRole(), and setFunction().
mNoise
C_FLOAT64 CReaction::mNoise private
The noise of the reaction
Referenced by initObjects().
mParameterIndexToCNs
std::vector< std::vector< CRegisteredCommonName > > CReaction::mParameterIndexToCNs private
Referenced by addParameterObject(), compileFunctionParameters(), createUndoData(), getParameterCNs(), initializeParameterMapping(), initializeParameters(), loadOneRole(), setFunctionFromExpressionTree(), setParameterCNs(), setParameterObjects(), setParameterValue(), toData(), and variable2object().
mParameterIndexToObjects
std::vector< std::vector< const CDataObject * > > CReaction::mParameterIndexToObjects private
Referenced by addParameterObject(), compileFunctionParameters(), getParameterObjects(), initializeParameterMapping(), initializeParameters(), isLocalParameter(), loadOneRole(), setFunctionFromExpressionTree(), setParameterCNs(), and setParameterObjects().
mParameterNameToIndex
std::map< std::string, size_t > CReaction::mParameterNameToIndex private
This describes the mapping of the species to the function parameters. Here the keys of the metabolites (as in the chemical equation) are stored.
Referenced by addParameterObject(), applyData(), getParameterCNs(), getParameterObjects(), initializeParameterMapping(), initializeParameters(), isLocalParameter(), loadOneRole(), setFunctionFromExpressionTree(), setParameterCNs(), setParameterObjects(), and setParameterValue().
mParameters
CCopasiParameterGroup CReaction::mParameters private
This is a list of parameter objects.
Referenced by applyData(), createUndoData(), getObject(), getParameters(), getParameterValue(), initializeParameters(), isLocalParameter(), setParameterValue(), and toData().
mParticleFlux
C_FLOAT64 CReaction::mParticleFlux private
The scaled flux of the reaction, as particle number/time
Referenced by compile(), getParticleFlux(), and initObjects().
mParticleNoise
C_FLOAT64 CReaction::mParticleNoise private
The particle noise
Referenced by initObjects().
mpFluxReference
CDataObjectReference<C_FLOAT64>* CReaction::mpFluxReference private
Referenced by getFluxReference(), and initObjects().
mpFunction
CFunction* CReaction::mpFunction private
A pointer to the rate function of the reaction
Referenced by compile(), CReaction(), createUndoData(), getFunction(), getFunctionParameters(), initializeParameterMapping(), initializeParameters(), load(), setFunction(), setFunctionFromExpressionTree(), setParameterValue(), and toData().
mpNoiseExpression
CExpression* CReaction::mpNoiseExpression private
Optional noise term
Referenced by compile(), createUndoData(), getNoiseExpression(), getNoiseExpressionPtr(), setNoiseExpression(), setNoiseExpressionPtr(), and toData().
mpNoiseReference
CDataObjectReference<C_FLOAT64>* CReaction::mpNoiseReference private
Referenced by getNoiseReference(), and initObjects().
mpParticleFluxReference
CDataObjectReference<C_FLOAT64>* CReaction::mpParticleFluxReference private
Referenced by getDefaultNoiseExpression(), getParticleFluxReference(), and initObjects().
mpParticleNoiseReference
CDataObjectReference<C_FLOAT64>* CReaction::mpParticleNoiseReference private
Referenced by getParticleNoiseReference(), and initObjects().
mpPropensityReference
CDataObjectReference<C_FLOAT64>* CReaction::mpPropensityReference private
Referenced by getPropensityReference(), and initObjects().
mPropensity
C_FLOAT64 CReaction::mPropensity private
The propensity of the reaction
Referenced by initObjects().
mpScalingCompartment
const CCompartment* CReaction::mpScalingCompartment private
Referenced by getScalingCompartment(), setScalingCompartment(), setScalingCompartmentCN(), and setScalingFactor().
mSBMLId
std::string CReaction::mSBMLId mutable private
The id of the corresponding reaction in an SBML file. This value is either set upon importing an SBML file, or when the object is first exported to an SBML file.
Referenced by getSBMLId(), and setSBMLId().
mScalingCompartmentCN
CRegisteredCommonName CReaction::mScalingCompartmentCN private
Referenced by CReaction(), createUndoData(), getScalingCompartmentCN(), setScalingCompartment(), setScalingCompartmentCN(), setScalingFactor(), and toData().
The documentation for this class was generated from the following files:
CReaction.h
CReaction.cpp