COPASI API: CModel.cpp File Reference
CModel.cpp File Reference
#include <sstream>
#include <string>
#include <vector>
#include <limits>
#include <cmath>
#include <algorithm>
#include <chrono>
#include "copasi/copasi.h"
#include "CCompartment.h"
#include "CMetab.h"
#include "CModel.h"
#include "CState.h"
#include "CModelValue.h"
#include "CObjectLists.h"
#include "copasi/function/CFunctionDB.h"
#include "copasi/core/CDataObjectReference.h"
#include "copasi/report/CKeyFactory.h"
#include "copasi/utilities/CCopasiException.h"
#include "copasi/utilities/CCopasiMessage.h"
#include "copasi/core/CDataVector.h"
#include "copasi/CopasiDataModel/CDataModel.h"
#include "copasi/core/CRootContainer.h"
#include "copasi/core/CVector.h"
#include "copasi/utilities/CluX.h"
#include "copasi/utilities/utility.h"
#include "copasi/utilities/CProcessReport.h"
#include "CReactionInterface.h"
#include "copasi/core/CDataArray.h"
#include "CMetabNameInterface.h"
#include "copasi/math/CMathContainer.h"
#include "copasi/lapack/blaswrap.h"
#include "copasi/lapack/lapackwrap.h"
#include <copasi/parameterFitting/CExperiment.h>
#include <copasi/parameterFitting/CExperimentSet.h>
#include <copasi/parameterFitting/CExperimentObjectMap.h>
#include <copasi/parameterFitting/CFitTask.h>
#include <copasi/parameterFitting/CFitProblem.h>
#include <copasi/trajectory/CTrajectoryTask.h>
#include <copasi/trajectory/CTrajectoryProblem.h>
#include <copasi/commandline/CLocaleString.h>
#include "copasi/function/CDerive.h"
Macros
#define MNumMetabolitesReactionDependent (mNumMetabolitesReaction - mNumMetabolitesReactionIndependent)
Functions
const CObjectInterface * getDependentOrNull (const std::map< const CObjectInterface *, size_t > &dependentMap, int index)
std::string getNextId (const std::string &base, int count)
size_t getUsedSymbolCount (const std::string &unit, const std::string &symbol)
Macro Definition Documentation
MNumMetabolitesReactionDependent
#define MNumMetabolitesReactionDependent (mNumMetabolitesReaction - mNumMetabolitesReactionIndependent)
Function Documentation
getDependentOrNull()
const CObjectInterface* getDependentOrNull (const std::map< const CObjectInterface *, size_t > & dependentMap, int index)
Referenced by CModel::createEventsForTimeseries().
getNextId()
std::string getNextId (const std::string & base, int count)
Referenced by CModel::createEventsForTimeseries().
getUsedSymbolCount()
size_t getUsedSymbolCount (const std::string & unit, const std::string & symbol)
References CUnit::getUsedSymbols().
Referenced by CModel::getUnitSymbolUsage().