COPASI API: CAbstractLayoutInterface Class Reference
CAbstractLayoutInterface Class Reference abstract
#include <CAbstractLayoutInterface.h>
Classes
class VariableDescription
Public Member Functions
CAbstractLayoutInterface ()
virtual const std::vector< double > & getInitialValues () const =0
virtual const std::vector< double > & getMassVector () const
std::vector< double >::size_type getNumVariables () const
virtual double getPotential ()=0
const std::vector< VariableDescription > & getVariablesDescription () const
virtual bool setState (const std::vector< double > &vars)=0
virtual ~CAbstractLayoutInterface ()
Protected Attributes
std::vector< double > mMassVector
std::vector< VariableDescription > mVarDescription
Detailed Description
This abstract class describes how an optimization algorithm will see a layout.
Constructor & Destructor Documentation
CAbstractLayoutInterface()
CAbstractLayoutInterface::CAbstractLayoutInterface () inline
~CAbstractLayoutInterface()
virtual CAbstractLayoutInterface::~CAbstractLayoutInterface () inline virtual
Member Function Documentation
getInitialValues()
virtual const std::vector<double>& CAbstractLayoutInterface::getInitialValues () const pure virtual
Implemented in CCopasiSpringLayout.
Referenced by CLayoutEngine::CLayoutEngine().
getMassVector()
const std::vector< double > & CAbstractLayoutInterface::getMassVector () const virtual
References mMassVector.
Referenced by CLayoutEngine::calcRHS().
getNumVariables()
std::vector< double >::size_type CAbstractLayoutInterface::getNumVariables () const
References mVarDescription.
Referenced by CLayoutEngine::calcForces(), and CLayoutEngine::calcRHS().
getPotential()
virtual double CAbstractLayoutInterface::getPotential () pure virtual
Implemented in CCopasiSpringLayout.
Referenced by CLayoutEngine::calcForces(), and CLayoutEngine::step().
getVariablesDescription()
const std::vector< CAbstractLayoutInterface::VariableDescription > & CAbstractLayoutInterface::getVariablesDescription () const
References mVarDescription.
setState()
virtual bool CAbstractLayoutInterface::setState (const std::vector< double > & vars) pure virtual
Implemented in CCopasiSpringLayout.
Referenced by CLayoutEngine::calcForces(), CLayoutEngine::step(), and CLayoutEngine::stepIntegration().
Member Data Documentation
mMassVector
std::vector<double> CAbstractLayoutInterface::mMassVector protected
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addPositionVariables(), CCopasiSpringLayout::addReactionVariables(), CCopasiSpringLayout::createVariables(), and getMassVector().
mVarDescription
std::vector<VariableDescription> CAbstractLayoutInterface::mVarDescription protected
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addPositionVariables(), CCopasiSpringLayout::addReactionVariables(), CCopasiSpringLayout::createVariables(), getNumVariables(), getVariablesDescription(), and CCopasiSpringLayout::setState().
The documentation for this class was generated from the following files:
CAbstractLayoutInterface.h
CAbstractLayoutInterface.cpp