COPASI API: ResultParser Class Reference
ResultParser Class Reference
#include <CParameterEstimationUtils.h>
Static Public Member Functions
static std::vector< ResultData * > fromFile (const std::string &fileName, CDataModel *dataModel=NULL)
static std::string & ltrim (std::string &s)
static std::vector< ResultData * > parseContent (const std::string &content)
static std::vector< ResultData * > parseFile (const std::string &fileName, CDataModel *dataModel=NULL)
static FittingItem * parseItem (const std::string &line)
static std::vector< ResultData * > parseStream (std::istream &reader, CDataModel *dataModel=NULL)
static CheckPoint * parseValue (const std::string &line)
static std::vector< FittingItem * > readItems (std::istream &reader, bool &flag)
static std::vector< CheckPoint * > readValues (std::istream &reader)
static std::string & rtrim (std::string &s)
static double saveToDouble (const std::string &doubleString, double defaultValue=0)
static bool skipTo (std::istream &reader, const std::string &lineStart)
static bool skipTo (std::istream &reader, const std::string &lineStart, bool &flag, bool(*eval)(const std::string &)=NULL)
static std::vector< std::string > split (const std::string &s, char delim, bool removeEmpty=true)
static std::vector< std::string > & split (const std::string &s, char delim, std::vector< std::string > &elems, bool removeEmpty=true)
static std::vector< std::string > & split (const std::string &s, const std::string &delims, std::vector< std::string > &elems)
static int toInt32 (const std::string &str)
static std::string trim (const std::string &s1)
static std::string & trim_in_place (std::string &s)
Member Function Documentation
fromFile()
std::vector< ResultData * > ResultParser::fromFile (const std::string & fileName, CDataModel * dataModel = NULL) static
References parseFile().
ltrim()
std::string & ResultParser::ltrim (std::string & s) inline static
Referenced by trim(), and trim_in_place().
parseContent()
std::vector< ResultData * > ResultParser::parseContent (const std::string & content) static
References parseStream().
parseFile()
std::vector< ResultData * > ResultParser::parseFile (const std::string & fileName, CDataModel * dataModel = NULL) static
References parseStream().
Referenced by fromFile().
parseItem()
FittingItem * ResultParser::parseItem (const std::string & line) static
References FittingItem::mLowerBound, FittingItem::mName, FittingItem::mStartValue, FittingItem::mUpperBound, sanitizeName(), saveToDouble(), and trim().
Referenced by readItems().
parseStream()
std::vector< ResultData * > ResultParser::parseStream (std::istream & reader, CDataModel * dataModel = NULL) static
References readItems(), and readValues().
Referenced by parseContent(), and parseFile().
parseValue()
CheckPoint * ResultParser::parseValue (const std::string & line) static
References CheckPoint::mBestValue, CheckPoint::mFunctionEvaluations, CheckPoint::mParameters, saveToDouble(), split(), and toInt32().
Referenced by readValues().
readItems()
std::vector< FittingItem * > ResultParser::readItems (std::istream & reader, bool & flag) static
References containsOptimization(), FittingItem::mAffectedExperiments, parseItem(), skipTo(), split(), and trim().
Referenced by parseStream().
readValues()
std::vector< CheckPoint * > ResultParser::readValues (std::istream & reader) static
References FUNCTION_EVAL, parseValue(), and skipTo().
Referenced by parseStream().
rtrim()
std::string & ResultParser::rtrim (std::string & s) inline static
Referenced by trim(), and trim_in_place().
saveToDouble()
double ResultParser::saveToDouble (const std::string & doubleString, double defaultValue = 0) static
References trim().
Referenced by CScanItemLinear::CScanItemLinear(), CSEDMLExporter::exportNthScanItem(), CTrajectoryProblem::getValues(), parseItem(), parseValue(), and CDataModel::reparameterizeFromIniFile().
skipTo() [1/2]
bool ResultParser::skipTo (std::istream & reader, const std::string & lineStart) static
Referenced by readItems(), and readValues().
skipTo() [2/2]
bool ResultParser::skipTo (std::istream & reader, const std::string & lineStart, bool & flag, bool(*)(const std::string &) eval = NULL) static
References trim().
split() [1/3]
std::vector< std::string > ResultParser::split (const std::string & s, char delim, bool removeEmpty = true) static
Referenced by CScanItemLinear::CScanItemLinear(), CSEDMLExporter::exportNthScanItem(), CTrajectoryProblem::getValues(), parseValue(), and readItems().
split() [2/3]
std::vector< std::string > & ResultParser::split (const std::string & s, char delim, std::vector< std::string > & elems, bool removeEmpty = true) static
References trim().
split() [3/3]
std::vector< std::string > & ResultParser::split (const std::string & s, const std::string & delims, std::vector< std::string > & elems) static
toInt32()
int ResultParser::toInt32 (const std::string & str) static
Referenced by parseValue().
trim()
std::string ResultParser::trim (const std::string & s1) static
References ltrim(), and rtrim().
Referenced by parseItem(), readItems(), CDataModel::reparameterizeFromIniFile(), saveToDouble(), skipTo(), and split().
trim_in_place()
std::string & ResultParser::trim_in_place (std::string & s) inline static
References ltrim(), and rtrim().
The documentation for this class was generated from the following files:
CParameterEstimationUtils.h
CParameterEstimationUtils.cpp