COPASI API: SliderHandler Class Reference
SliderHandler Class Reference
#include <SliderHandler.h>
Public Member Functions
SliderHandler (CXMLParser &parser, CXMLParserData &data)
virtual ~SliderHandler ()
Public Member Functions inherited from CXMLHandler
CXMLHandler (CXMLParser &parser, CXMLParserData &data, const Type &type)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~CXMLHandler ()
Protected Member Functions
virtual sProcessLogic * getProcessLogic () const
virtual bool processEnd (const XML_Char *pszName)
virtual CXMLHandler * processStart (const XML_Char *pszName, const XML_Char **papszAttrs)
Protected Member Functions inherited from CXMLHandler
void addFix (const std::string &key, CDataObject *pObject)
std::string getElementName (const Type &type) const
std::string getExpectedElements (const Type &type) const
CXMLHandler * getHandler (const Type &type)
void init ()
Private Member Functions
SliderHandler ()
Additional Inherited Members
Public Types inherited from CXMLHandler
enum Type {
BEFORE = 0 , AFTER , UNKNOWN , AdditionalGraphicalObject ,
Assignment , BasePoint1 , BasePoint2 , Body ,
BoundingBox , CallParameter , ChannelSpec , CharacterData ,
ColorDefinition , Comment , Compartment , CompartmentGlyph ,
Constant , COPASI , CubicBezier , Curve ,
CurveSegment , DelayExpression , Dimensions , Ellipse ,
End , Event , Expression , Footer ,
Function , GradientStop , Group , GUI ,
Header , Image , InitialExpression , InitialState ,
KineticLaw , Layout , LinearGradient , LineEnding ,
LineSegment , ListOfAdditionalGraphicalObjects , ListOfAssignments , ListOfCallParameters ,
ListOfChannels , ListOfColorDefinitions , ListOfCompartmentGlyphs , ListOfCompartments ,
ListOfConstants , ListOfCurveSegments , ListOfElements , ListOfEvents ,
ListOfFunctions , ListOfGlobalRenderInformation , ListOfGradientDefinitions , ListOfLayouts ,
ListOfLineEndings , ListOfMetabGlyphs , ListOfMetaboliteReferenceGlyphs , ListOfMetabolites ,
ListOfModelParameterSets , ListOfModelValues , ListOfModifiers , ListOfParameterDescriptions ,
ListOfPlotItems , ListOfPlots , ListOfProducts , ListOfReactionGlyphs ,
ListOfReactions , ListOfRenderInformation , ListOfReports , ListOfSliders ,
ListOfStyles , ListOfSubstrates , ListOfTasks , ListOfTextGlyphs ,
ListOfUnitDefinitions , ListOfUnsupportedAnnotations , MathML , Metabolite ,
MetaboliteGlyph , MetaboliteReferenceGlyph , Method , MiriamAnnotation ,
Model , ModelParameter , ModelParameterGroup , ModelParameterSet ,
ModelValue , Modifier , NoiseExpression , Object ,
Parameter , ParameterDescription , ParameterGroup , ParameterText ,
PlotItem , PlotSpecification , Point , Polygon ,
Position , PriorityExpression , Problem , Product ,
RadialGradient , Reaction , ReactionGlyph , Rectangle ,
RenderCurve , RenderCurveElement , RenderInformation , RenderText ,
ReportDefinition , ReportSection , ReportTarget , SBMLMap ,
SBMLReference , Slider , SourceParameter , Start ,
StateTemplate , StateTemplateVariable , Style , Substrate ,
Table , Task , Text , TextGlyph ,
TriggerExpression , Unit , UnitDefinition , UnsupportedAnnotation ,
HANDLER_COUNT
}
Protected Attributes inherited from CXMLHandler
std::pair< Type, Type > mCurrentElement
std::map< std::string, std::pair< Type, Type > > mElementName2Type
Type mElementType
const Type mHandlerType
std::pair< Type, Type > mLastKnownElement
size_t mLevel
CXMLParserData * mpData
CXMLParser * mpParser
std::map< Type, std::set< Type > > mValidElements
Constructor & Destructor Documentation
SliderHandler() [1/2]
SliderHandler::SliderHandler () private
SliderHandler() [2/2]
SliderHandler::SliderHandler (CXMLParser & parser, CXMLParserData & data)
Constructor
Parameters
CXMLParser & parser
CXMLParserData & data
Replace Slider with the name type of the handler and implement the three methods below.
References CXMLHandler::init().
~SliderHandler()
SliderHandler::~SliderHandler () virtual
Destructor
Member Function Documentation
getProcessLogic()
CXMLHandler::sProcessLogic * SliderHandler::getProcessLogic () const protected virtual
Retrieve the structure containing the process logic for the handler.
Returns
sElementInfo *
Implements CXMLHandler.
References CXMLHandler::AFTER, CXMLHandler::BEFORE, CXMLHandler::HANDLER_COUNT, and CXMLHandler::Slider.
processEnd()
bool SliderHandler::processEnd (const XML_Char * pszName) protected virtual
Process the end of an element
Parameters
const XML_Char *pszName
Returns
bool finished
Implements CXMLHandler.
References CCopasiMessage::EXCEPTION, CExpatTemplate< CType >::getCurrentColumnNumber(), CExpatTemplate< CType >::getCurrentLineNumber(), CXMLHandler::mCurrentElement, MCXML, CXMLHandler::mpParser, and CXMLHandler::Slider.
processStart()
CXMLHandler * SliderHandler::processStart (const XML_Char * pszName, const XML_Char ** papszAttrs) protected virtual
Process the start of an element
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Returns
CXMLHandler * pHandlerToCall
Implements CXMLHandler.
References CDataVector< CType >::add(), CXMLHandler::addFix(), C_FLOAT64, C_INT32, CSlider::convertScaleNameToScale(), CCopasiMessage::EXCEPTION, CSlider::Float, CKeyFactory::get(), CExpatTemplate< CType >::getAttributeValue(), CExpatTemplate< CType >::getCurrentColumnNumber(), CExpatTemplate< CType >::getCurrentLineNumber(), CDataObject::getKey(), SCopasiXMLGUI::getSliderList(), CXMLHandler::mCurrentElement, MCXML, CXMLParserData::mKeyMap, CXMLHandler::mpData, CXMLHandler::mpParser, CXMLParserData::pGUI, CSlider::setAssociatedEntityKey(), CSlider::setMaxValue(), CSlider::setMinValue(), CSlider::setScaling(), CSlider::setSliderObject(), CSlider::setSliderType(), CSlider::setSliderValue(), CSlider::setTickFactor(), CSlider::setTickNumber(), CXMLHandler::Slider, strToUnsignedInt(), toEnum(), and CSlider::TypeName.
The documentation for this class was generated from the following files:
SliderHandler.h
SliderHandler.cpp