COPASI API: CDataVector< CType >::const_iterator Class Reference
CDataVector< CType >::const_iterator Class Reference
#include <CDataVector.h>
Public Member Functions
const_iterator ()
const_iterator (const const_iterator &src)
const_iterator (const iterator &src)
const_iterator (const typename std::vector< CType * >::const_iterator &src)
CType * constCast ()
operator const CType * () const
const CType & operator* () const
const_iterator operator+ (const typename std::vector< CType * >::const_iterator::difference_type &n) const
const_iterator & operator++ ()
const_iterator operator++ (int)
const_iterator & operator+= (const typename std::vector< CType * >::const_iterator::difference_type &n)
const_iterator operator- (const typename std::vector< CType * >::const_iterator::difference_type &n) const
const_iterator & operator-- ()
const_iterator operator-- (int)
const_iterator & operator-= (const typename std::vector< CType * >::const_iterator::difference_type &n)
const CType * operator-> () const
~const_iterator ()
Constructor & Destructor Documentation
const_iterator() [1/4]
template<class CType > CDataVector< CType >::const_iterator::const_iterator () inline
Referenced by CDataVector< CType >::const_iterator::operator+(), and CDataVector< CType >::const_iterator::operator-().
const_iterator() [2/4]
template<class CType > CDataVector< CType >::const_iterator::const_iterator (const const_iterator & src) inline
const_iterator() [3/4]
template<class CType > CDataVector< CType >::const_iterator::const_iterator (const iterator & src) inline
const_iterator() [4/4]
template<class CType > CDataVector< CType >::const_iterator::const_iterator (const typename std::vector< CType * >::const_iterator & src) inline
~const_iterator()
template<class CType > CDataVector< CType >::const_iterator::~const_iterator () inline
Member Function Documentation
constCast()
template<class CType > CType* CDataVector< CType >::const_iterator::constCast () inline
operator const CType *()
template<class CType > CDataVector< CType >::const_iterator::operator const CType * () const inline
operator*()
template<class CType > const CType& CDataVector< CType >::const_iterator::operator* () const inline
operator+()
template<class CType > const_iterator CDataVector< CType >::const_iterator::operator+ (const typename std::vector< CType * >::const_iterator::difference_type & n) const inline
References CDataVector< CType >::const_iterator::const_iterator().
operator++() [1/2]
template<class CType > const_iterator& CDataVector< CType >::const_iterator::operator++ () inline
Referenced by CDataVector< CType >::const_iterator::operator++().
operator++() [2/2]
template<class CType > const_iterator CDataVector< CType >::const_iterator::operator++ (int) inline
References CDataVector< CType >::const_iterator::operator++().
operator+=()
template<class CType > const_iterator& CDataVector< CType >::const_iterator::operator+= (const typename std::vector< CType * >::const_iterator::difference_type & n) inline
operator-()
template<class CType > const_iterator CDataVector< CType >::const_iterator::operator- (const typename std::vector< CType * >::const_iterator::difference_type & n) const inline
References CDataVector< CType >::const_iterator::const_iterator().
operator--() [1/2]
template<class CType > const_iterator& CDataVector< CType >::const_iterator::operator-- () inline
Referenced by CDataVector< CType >::const_iterator::operator--().
operator--() [2/2]
template<class CType > const_iterator CDataVector< CType >::const_iterator::operator-- (int) inline
References CDataVector< CType >::const_iterator::operator--().
operator-=()
template<class CType > const_iterator& CDataVector< CType >::const_iterator::operator-= (const typename std::vector< CType * >::const_iterator::difference_type & n) inline
operator->()
template<class CType > const CType* CDataVector< CType >::const_iterator::operator-> () const inline
The documentation for this class was generated from the following file:
CDataVector.h