COPASI API: CLPolygon Class Reference
CLPolygon Class Reference
#include <CLPolygon.h>
Public Member Functions
void addElement (const CLRenderPoint *ls)
CLPolygon (CDataContainer *pParent=NULL)
CLPolygon (const CLPolygon &source, CDataContainer *pParent)
CLPolygon (const sbmlPolygon &source, CDataContainer *pParent=NULL)
CLRenderCubicBezier * createCubicBezier ()
CLRenderPoint * createPoint ()
CLRenderPoint * getElement (size_t index)
const CLRenderPoint * getElement (size_t index) const
const std::string & getKey () const
std::vector< CLRenderPoint * > * getListOfElements ()
const std::vector< CLRenderPoint * > * getListOfElements () const
size_t getNumElements () const
void removeElement (size_t i)
sbmlPolygon * toSBML (unsigned int level, unsigned int version) const
~CLPolygon ()
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
virtual const CDataObject * getValueObject () const
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const override
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Protected Attributes
std::string mKey
std::vector< CLRenderPoint * > mListOfElements
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLPolygon & operator= (const CLPolygon &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET , NONZERO , EVENODD , INHERIT }
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLPolygon() [1/3]
CLPolygon::CLPolygon (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLPolygon() [2/3]
CLPolygon::CLPolygon (const CLPolygon & source, CDataContainer * pParent)
Copy constructor
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and mListOfElements.
CLPolygon() [3/3]
CLPolygon::CLPolygon (const sbmlPolygon & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
~CLPolygon()
CLPolygon::~CLPolygon ()
Destructor.
References CRootContainer::getKeyFactory(), mKey, mListOfElements, and CKeyFactory::remove().
Member Function Documentation
addElement()
void CLPolygon::addElement (const CLRenderPoint * pLS)
Adds a copy of the given line segment to the list of line segements.
References mListOfElements.
createCubicBezier()
CLRenderCubicBezier * CLPolygon::createCubicBezier ()
Creates a new cubicbezier object and adds it to the list of elements.
Creates a new cubicbezier object and adds it to the list of curve segments.
References mListOfElements.
createPoint()
CLRenderPoint * CLPolygon::createPoint ()
Creates a new point object and adds it to the list of elements.
Creates a new point object and adds it to the list of curve segments.
References mListOfElements.
getElement() [1/2]
CLRenderPoint * CLPolygon::getElement (size_t index)
Returns a pointer to the point with with the given index or NULL if the index is invalid.
Returns a pointer to the line segement with with the given index or NULL if the index is invalid.
References mListOfElements.
Referenced by CLLayoutRenderer::draw_polygon().
getElement() [2/2]
const CLRenderPoint * CLPolygon::getElement (size_t index) const
Returns const a pointer to the line segement with with the given index or NULL if the index is invalid.
References mListOfElements.
getKey()
const std::string & CLPolygon::getKey () const virtual
Returns the key string of the object.
Returns the key of the color definition.
Reimplemented from CDataObject.
References mKey.
getListOfElements() [1/2]
std::vector< CLRenderPoint * > * CLPolygon::getListOfElements ()
Returns a pointer to the list of curve segments.
References mListOfElements.
Referenced by PolygonHandler::processStart(), and CCopasiXML::savePolygonElement().
getListOfElements() [2/2]
const std::vector< CLRenderPoint * > * CLPolygon::getListOfElements () const
Returns a const pointer to the list of curve segments.
References mListOfElements.
getNumElements()
size_t CLPolygon::getNumElements () const
Returns the number of line segments.
References mListOfElements.
Referenced by CLLayoutRenderer::draw_polygon().
operator=()
CLPolygon& CLPolygon::operator= (const CLPolygon & source) private
removeElement()
void CLPolygon::removeElement (size_t i)
Removes the curve segment with the given index.
References mListOfElements.
toSBML()
Polygon * CLPolygon::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLGraphicalPrimitive2D::addSBMLAttributes(), and mListOfElements.
Member Data Documentation
mKey
std::string CLPolygon::mKey protected
key for the object.
Referenced by CLPolygon(), getKey(), and ~CLPolygon().
mListOfElements
std::vector<CLRenderPoint*> CLPolygon::mListOfElements protected
Referenced by addElement(), CLPolygon(), createCubicBezier(), createPoint(), getElement(), getListOfElements(), getNumElements(), removeElement(), toSBML(), and ~CLPolygon().
The documentation for this class was generated from the following files:
CLPolygon.h
CLPolygon.cpp