COPASI API: CBrent Class Reference
CBrent Class Reference
#include <CBrent.h>
Classes
class Eval
class EvalTemplate
Static Public Member Functions
static bool findMinimum (double left, double right, Eval *pFunction, double *pMin, double *pMinValue, double tolerance, int maxIterations)
static bool findRoot (double left, double right, Eval *pFunction, double *pRoot, double *pRootValue, double tolerance)
Member Function Documentation
findMinimum()
bool CBrent::findMinimum (double left, double right, CBrent::Eval * pF, double * pMin, double * pMinValue, double tolerance, int maxIterations) static
Brent minimum finding method.
Parameters
double left
double right
evalF function
double * pMin
double * pMinValue
double tolerance
int maxIterations
Returns
bool success
References min, and SQRT_EPSILON.
Referenced by COptProblem::adjustForIntervals().
findRoot()
bool CBrent::findRoot (double left, double right, CBrent::Eval * pF, double * pRoot, double * pRootValue, double tolerance) static
Brent root finding method.
Parameters
double left
double right
evalF function
double * pRoot
double * pRootValue
double tolerance
Returns
bool success
References max, and min.
Referenced by CRungeKutta::checkRoots(), CRootFinder::checkRoots(), and CStochDirectMethod::doSingleStep().
The documentation for this class was generated from the following files:
CBrent.h
CBrent.cpp