COPASI API: CFitItem Class Reference
CFitItem Class Reference
#include <CFitItem.h>
Public Member Functions
bool addCrossValidation (const std::string &key)
bool addExperiment (const std::string &key)
CFitItem (const CCopasiParameterGroup &group, const CDataContainer *pParent)
CFitItem (const CDataContainer *pParent, const std::string &name="FitItem")
CFitItem (const CFitItem &src, const CDataContainer *pParent)
virtual C_INT32 checkConstraint () const override
virtual bool compile (CObjectInterface::ContainerList listOfContainer=CDataContainer::EmptyList) override
virtual bool elevateChildren () override
virtual C_FLOAT64 getConstraintViolation () const override
const std::string & getCrossValidation (const size_t &index) const
size_t getCrossValidationCount () const
std::string getCrossValidations () const
const std::string & getExperiment (const size_t &index) const
size_t getExperimentCount () const
std::string getExperiments () const
const C_FLOAT64 & getLocalValue () const
virtual const C_FLOAT64 * getObjectValue () const override
virtual bool isValid () const override
bool removeCrossValidation (const size_t &index)
bool removeExperiment (const size_t &index)
void setLocalValue (const C_FLOAT64 &value)
bool updateBounds (const std::vector< COptItem * > &items)
virtual ~CFitItem ()
Public Member Functions inherited from COptItem
void addDependentItem (COptItem *pDependentItem)
virtual void calculateValue () override
C_INT32 checkConstraint (const C_FLOAT64 &value) const
bool checkInterval () const
bool checkIsInitialValue () const
bool checkLowerBound (const C_FLOAT64 &value) const
bool checkUpperBound (const C_FLOAT64 &value) const
COptItem (const CCopasiParameterGroup &group, const CDataContainer *pParent)
COptItem (const CDataContainer *pParent, const std::string &name="OptimizationItem")
COptItem (const COptItem &src, const CDataContainer *pParent)
const std::set< COptItem * > & getDependentItems () const
const CCore::CUpdateSequence & getIntervalUpdateSequence () const
const C_FLOAT64 & getLastStartValue () const
const std::string getLowerBound () const
const C_FLOAT64 * getLowerBoundValue () const
const CObjectInterface * getObject () const
const CCommonName getObjectCN () const
std::string getObjectDisplayName () const override
C_FLOAT64 getRandomValue (CRandom &Random) const
const C_FLOAT64 & getStartValue () const
const std::string getUpperBound () const
const C_FLOAT64 * getUpperBoundValue () const
virtual void * getValuePointer () const override
bool influencesIntervals () const
void rememberStartValue ()
void setIntervalUpdateSequence (const CCore::CUpdateSequence &updateSequence)
bool setLowerBound (const CCommonName &lowerBound)
bool setObjectCN (const CCommonName &objectCN)
bool setStartValue (const C_FLOAT64 &value)
bool setUpperBound (const CCommonName &upperBound)
void updatePrerequisites (const std::vector< COptItem * > &influencingIntervals)
virtual ~COptItem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static bool isValid (CCopasiParameterGroup &group)
Static Public Member Functions inherited from COptItem
static bool isValid (CCopasiParameterGroup &group)
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Member Functions
CFitItem ()
CFitItem (const CFitItem &src)
Protected Member Functions inherited from COptItem
COptItem ()
COptItem (const COptItem &src)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
C_FLOAT64 mLocalValue
CCopasiParameterGroup * mpGrpAffectedCrossValidations
CCopasiParameterGroup * mpGrpAffectedExperiments
Protected Attributes inherited from COptItem
std::set< COptItem * > mDependentItems
C_FLOAT64 mInterval
C_FLOAT64 mLastStartValue
C_FLOAT64 mLowerBound
const C_FLOAT64 * mpLowerBound
const CObjectInterface * mpLowerObject
const CObjectInterface * mpObject
const C_FLOAT64 * mpObjectValue
std::string * mpParmLowerBound
std::string * mpParmObjectCN
C_FLOAT64 * mpParmStartValue
std::string * mpParmUpperBound
const C_FLOAT64 * mpUpperBound
const CObjectInterface * mpUpperObject
CCore::CUpdateSequence mUpdateInterval
C_FLOAT64 mUpperBound
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
void initializeParameter ()
Friends
class CFitProblem
std::ostream & operator<< (std::ostream &os, const CFitItem &o)
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Constructor & Destructor Documentation
CFitItem() [1/5]
CFitItem::CFitItem () protected
Default constructor
CFitItem() [2/5]
CFitItem::CFitItem (const CFitItem & src) protected
CFitItem() [3/5]
CFitItem::CFitItem (const CDataContainer * pParent, const std::string & name = "FitItem")
Specific constructor
Parameters
const CDataContainer * pParent (default: NULL)
const std::string & name (default: FitItem)
References initializeParameter().
CFitItem() [4/5]
CFitItem::CFitItem (const CFitItem & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CFitItem & src
const CDataContainer * pParent (default: src data model)
References initializeParameter().
CFitItem() [5/5]
CFitItem::CFitItem (const CCopasiParameterGroup & group, const CDataContainer * pParent)
Specific constructor used for reading COPASI files
Parameters
const CCopasiParameterGroup & group
const CDataContainer * pParent (default: group data model)
References initializeParameter().
~CFitItem()
CFitItem::~CFitItem () virtual
Destructor
Member Function Documentation
addCrossValidation()
bool CFitItem::addCrossValidation (const std::string & key)
Add an experiment to the list of affected cross validations.
Parameters
const std::string & key
Returns
bool success
References CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::getValue(), CCopasiParameter::KEY, mpGrpAffectedCrossValidations, and CCopasiParameterGroup::size().
addExperiment()
bool CFitItem::addExperiment (const std::string & key)
Add an experiment to the list of affected experiments.
Parameters
const std::string & key
Returns
bool success
References CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::getValue(), CCopasiParameter::KEY, mpGrpAffectedExperiments, and CCopasiParameterGroup::size().
checkConstraint()
C_INT32 CFitItem::checkConstraint () const override virtual
This functions check whether the current value is within the limits of the optimization item.
Returns
C_INT32 result (-1: to small, 0: within boundaries, 1 to large)
Reimplemented from COptItem.
Reimplemented in CFitConstraint.
References mLocalValue, COptItem::mpLowerBound, and COptItem::mpUpperBound.
Referenced by getConstraintViolation().
compile()
bool CFitItem::compile (CObjectInterface::ContainerList listOfContainer = CDataContainer::EmptyList) override virtual
Compile the optimization item. This function must be called before any of the check functions are called.
Parameters
const CObjectInterface::ContainerList listOfContainer
Returns
bool success
Reimplemented from COptItem.
References COptItem::compile(), mLocalValue, and COptItem::mpParmStartValue.
elevateChildren()
bool CFitItem::elevateChildren () override virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
References C_FLOAT64, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), mpGrpAffectedCrossValidations, mpGrpAffectedExperiments, CCopasiParameterGroup::removeParameter(), and COptItem::setStartValue().
Referenced by initializeParameter().
getConstraintViolation()
C_FLOAT64 CFitItem::getConstraintViolation () const override virtual
Retrieve the magnitude of the constraint violation This is always a positive number
Returns
C_FLOAT64 constraintViolation;
Reimplemented from COptItem.
Reimplemented in CFitConstraint.
References checkConstraint(), mLocalValue, COptItem::mpLowerBound, and COptItem::mpUpperBound.
getCrossValidation()
const std::string & CFitItem::getCrossValidation (const size_t & index) const
Retrieve the key of the indexed experiment.
Parameters
const size_t & index
Returns
const std::string & key
References CCopasiParameterGroup::getValue(), mpGrpAffectedCrossValidations, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize().
getCrossValidationCount()
size_t CFitItem::getCrossValidationCount () const
Retrieve the number of cross validations
Returns
size_t size
References mpGrpAffectedCrossValidations, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize().
getCrossValidations()
std::string CFitItem::getCrossValidations () const
Retrieve a string listing all cross validations the item applies to
Returns
std::string crossValidations
References CKeyFactory::get(), CRootContainer::getKeyFactory(), CDataObject::getObjectName(), CCopasiParameterGroup::getValue(), mpGrpAffectedCrossValidations, and CCopasiParameterGroup::size().
getExperiment()
const std::string & CFitItem::getExperiment (const size_t & index) const
Retrieve the key of the indexed experiment.
Parameters
const size_t & index
Returns
const std::string & key
References CCopasiParameterGroup::getValue(), mpGrpAffectedExperiments, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize(), and CFitProblem::printResult().
getExperimentCount()
size_t CFitItem::getExperimentCount () const
Retrieve the number of experiments
Returns
size_t size
References mpGrpAffectedExperiments, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize(), and CFitProblem::printResult().
getExperiments()
std::string CFitItem::getExperiments () const
Retrieve a string listing all experiments the item applies to
Returns
std::string experiments
References CKeyFactory::get(), CRootContainer::getKeyFactory(), CDataObject::getObjectName(), CCopasiParameterGroup::getValue(), mpGrpAffectedExperiments, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize().
getLocalValue()
const C_FLOAT64 & CFitItem::getLocalValue () const
Retrieve the local value.
Returns
const C_FLOAT64 & value
References mLocalValue.
Referenced by CFitProblem::calculate(), CFitProblem::createParameterSets(), CFitProblem::initialize(), CFitProblem::restore(), updateBounds(), and CFitProblem::updateContainer().
getObjectValue()
const C_FLOAT64 * CFitItem::getObjectValue () const override virtual
Retrieve the value of the optimization object.
Returns
const C_FLOAT64 * objectValue
Reimplemented from COptItem.
References mLocalValue.
initializeParameter()
void CFitItem::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
References CCopasiParameterGroup::assertGroup(), elevateChildren(), mpGrpAffectedCrossValidations, and mpGrpAffectedExperiments.
Referenced by CFitItem().
isValid() [1/2]
bool CFitItem::isValid () const override virtual
Check the validity of the optimization item.
Returns
bool isValid
Reimplemented from COptItem.
References COptItem::isValid().
Referenced by isValid().
isValid() [2/2]
bool CFitItem::isValid (CCopasiParameterGroup & group) static
Check whether the group describes a valid optimization item.
Parameters
CCopasiParameterGroup & group
Returns
bool isValid
References isValid(), and NO_PARENT.
removeCrossValidation()
bool CFitItem::removeCrossValidation (const size_t & index)
Remove the indexed experiment from the affected cross validations
Parameters
const size_t & index
Returns
bool success
References mpGrpAffectedCrossValidations, and CCopasiParameterGroup::removeParameter().
removeExperiment()
bool CFitItem::removeExperiment (const size_t & index)
Remove the indexed experiment from the affected experiments
Parameters
const size_t & index
Returns
bool success
References mpGrpAffectedExperiments, and CCopasiParameterGroup::removeParameter().
setLocalValue()
void CFitItem::setLocalValue (const C_FLOAT64 & value)
Set the local value.
Parameters
const C_FLOAT64 & value
References mLocalValue.
updateBounds()
bool CFitItem::updateBounds (const std::vector< COptItem * > & items)
Update bounds
Parameters
const std::vector<COptItem * > & items
Returns
bool success
References getLocalValue(), COptItem::getLowerBound(), COptItem::getUpperBound(), COptItem::mpLowerBound, COptItem::mpLowerObject, COptItem::mpUpperBound, and COptItem::mpUpperObject.
Referenced by CFitProblem::initialize().
Friends And Related Function Documentation
CFitProblem
friend class CFitProblem friend
operator<<
std::ostream& operator<< (std::ostream & os, const CFitItem & o) friend
Output stream operator
Parameters
ostream & os
const CFitItem & A
Returns
ostream & os
Member Data Documentation
mLocalValue
C_FLOAT64 CFitItem::mLocalValue protected
The value for local items, which affect the experiments in the list.
Referenced by checkConstraint(), compile(), getConstraintViolation(), getLocalValue(), getObjectValue(), and setLocalValue().
mpGrpAffectedCrossValidations
CCopasiParameterGroup* CFitItem::mpGrpAffectedCrossValidations protected
A pointer to the value of the CCopasiParameterGroup holding the list of Affected Validation Experiments
Referenced by addCrossValidation(), elevateChildren(), getCrossValidation(), getCrossValidationCount(), getCrossValidations(), initializeParameter(), and removeCrossValidation().
mpGrpAffectedExperiments
CCopasiParameterGroup* CFitItem::mpGrpAffectedExperiments protected
A pointer to the value of the CCopasiParameterGroup holding the list of AffectedExperiments
Referenced by addExperiment(), elevateChildren(), getExperiment(), getExperimentCount(), getExperiments(), initializeParameter(), and removeExperiment().
The documentation for this class was generated from the following files:
CFitItem.h
CFitItem.cpp