COPASI API: Expression2PresentationMMLUnits Class Reference
Expression2PresentationMMLUnits Class Reference
#include <Expression2PresentationMMLUnits.h>
Public Member Functions
Expression2PresentationMMLUnits (const ASTNode *rootnode)
std::string getMathML (const CSBMLunitInformation &ui) const
void setUnitInterface (CSBMLunitInterface *unitInterface, CSBMLunitInterface *unitInterface2)
Public Member Functions inherited from Expression2PresentationMML
Expression2PresentationMML (const ASTNode *rootnode)
void setModel (const Model *m)
void setReaction (const Reaction *m)
void setUseReactionNameInLocalParameters (bool b)
void writeMathML (std::ostream &out) const
virtual ~Expression2PresentationMML ()
Protected Member Functions
std::string getMathML (const Unit *u, bool absExp) const
std::string getMathML (const UnitDefinition &ud) const
void writeMathMLBox (std::ostream &out, const std::string &a, const std::string &b, const std::string &c, const std::string &color, size_t l) const
void writeMathMLBox (std::ostream &out, const std::string &a, const std::string &b, const std::string &color, size_t l) const
virtual void writeMathMLName (std::ostream &out, const ASTNode *node, size_t l) const
virtual void writeMathMLNumber (std::ostream &out, const ASTNode *node, size_t l) const
Protected Member Functions inherited from Expression2PresentationMML
void writeMathML (std::ostream &out, const ASTNode *node, size_t l) const
virtual void writeMathMLFunction (std::ostream &out, const ASTNode *node, size_t l) const
Protected Attributes
CSBMLunitInterface * mpUnitInterface
CSBMLunitInterface * mpUnitInterface2
Protected Attributes inherited from Expression2PresentationMML
const Model * mpModel
const Reaction * mpReaction
const ASTNode * mRootNode
bool mUseReactionNameInLocalParameters
Constructor & Destructor Documentation
Expression2PresentationMMLUnits()
Expression2PresentationMMLUnits::Expression2PresentationMMLUnits (const ASTNode * rootnode)
Member Function Documentation
getMathML() [1/3]
std::string Expression2PresentationMMLUnits::getMathML (const CSBMLunitInformation & ui) const
References CSBMLunitInformation::DEFAULT, CSBMLunitInformation::DERIVED, CSBMLunitInformation::getInfo(), CSBMLunit::getSBMLUnitDefinition(), CSBMLunit::getSymbolicExpExp(), CSBMLunit::getSymbolicExponent(), CSBMLunitInformation::GLOBAL, CSBMLunitInformation::isConflict(), CSBMLunitInformation::PROVIDED, and CSBMLunitInformation::UNKNOWN.
Referenced by getMathML(), writeMathMLName(), and writeMathMLNumber().
getMathML() [2/3]
std::string Expression2PresentationMMLUnits::getMathML (const Unit * u, bool absExp) const protected
References abs.
getMathML() [3/3]
std::string Expression2PresentationMMLUnits::getMathML (const UnitDefinition & ud) const protected
References getMathML().
setUnitInterface()
void Expression2PresentationMMLUnits::setUnitInterface (CSBMLunitInterface * unitInterface, CSBMLunitInterface * unitInterface2)
sets the unit interface to the SBML model so that the units can be displayed. this implicitly also handles setting the model
References CSBMLunitInterface::getModel(), Expression2PresentationMML::mpModel, mpUnitInterface, and mpUnitInterface2.
writeMathMLBox() [1/2]
void Expression2PresentationMMLUnits::writeMathMLBox (std::ostream & out, const std::string & a, const std::string & b, const std::string & c, const std::string & color, size_t l) const protected
References SPC.
writeMathMLBox() [2/2]
void Expression2PresentationMMLUnits::writeMathMLBox (std::ostream & out, const std::string & a, const std::string & b, const std::string & color, size_t l) const protected
write the mathML for a box that is used to display an object identifier + its unit information a and b are mathML strings
References SPC.
Referenced by writeMathMLName(), and writeMathMLNumber().
writeMathMLName()
void Expression2PresentationMMLUnits::writeMathMLName (std::ostream & out, const ASTNode * node, size_t l) const protected virtual
Reimplemented from Expression2PresentationMML.
References CSBMLunitInterface::getListOfConflictingNodes(), CSBMLunitInterface::getMappedUnitFromIdentifier(), getMathML(), CSBMLunitInformation::isEqual(), Expression2PresentationMML::mpReaction, mpUnitInterface, mpUnitInterface2, writeMathMLBox(), and Expression2PresentationMML::writeMathMLName().
writeMathMLNumber()
void Expression2PresentationMMLUnits::writeMathMLNumber (std::ostream & out, const ASTNode * node, size_t l) const protected virtual
Reimplemented from Expression2PresentationMML.
References CSBMLunitInterface::getListOfConflictingNodes(), CSBMLunitInterface::getMappedUnitFromNumberNode(), getMathML(), mpUnitInterface, mpUnitInterface2, writeMathMLBox(), and Expression2PresentationMML::writeMathMLNumber().
Member Data Documentation
mpUnitInterface
CSBMLunitInterface* Expression2PresentationMMLUnits::mpUnitInterface protected
Referenced by setUnitInterface(), writeMathMLName(), and writeMathMLNumber().
mpUnitInterface2
CSBMLunitInterface* Expression2PresentationMMLUnits::mpUnitInterface2 protected
Referenced by setUnitInterface(), writeMathMLName(), and writeMathMLNumber().
The documentation for this class was generated from the following files:
Expression2PresentationMMLUnits.h
Expression2PresentationMMLUnits.cpp