COPASI API: CArray Class Reference
CArray Class Reference
#include <CArray.h>
Public Member Functions
CArray ()
CArray (const index_type &sizes)
size_t dimensionality () const
virtual data_type & operator[] (const index_type &index)
virtual const data_type & operator[] (const index_type &index) const
void resize (const index_type &sizes)
virtual const index_type & size () const
virtual ~CArray ()
Public Member Functions inherited from CArrayInterface
virtual ~CArrayInterface ()
Private Attributes
std::vector< data_type > mData
size_t mDim
index_type mFactors
index_type mSizes
Additional Inherited Members
Public Types inherited from CArrayInterface
typedef C_FLOAT64 data_type
typedef std::vector< size_t > index_type
Detailed Description
this class contains an n-dimensional array
Constructor & Destructor Documentation
CArray() [1/2]
CArray::CArray ()
References mData.
CArray() [2/2]
CArray::CArray (const index_type & sizes)
References resize().
~CArray()
virtual CArray::~CArray () inline virtual
Member Function Documentation
dimensionality()
size_t CArray::dimensionality () const virtual
Implements CArrayInterface.
References mDim.
Referenced by CSensMethod::do_scaling().
operator[]() [1/2]
CArray::data_type & CArray::operator[] (const index_type & index) virtual
Implements CArrayInterface.
References mData, mDim, mFactors, and mSizes.
operator[]() [2/2]
const CArray::data_type & CArray::operator[] (const index_type & index) const virtual
Implements CArrayInterface.
resize()
void CArray::resize (const index_type & sizes)
References mData, mDim, mFactors, and mSizes.
Referenced by CSensMethod::calculate_one_level(), CArray(), CSensMethod::do_target_calculation(), CSensMethod::initialize(), and CTimeSensMethod::initResult().
size()
const CArray::index_type & CArray::size () const virtual
Implements CArrayInterface.
References mSizes.
Referenced by CSensMethod::do_collapsing(), and CSensMethod::do_collapsing_innerloop().
Member Data Documentation
mData
std::vector<data_type> CArray::mData private
Referenced by CArray(), operator[](), and resize().
mDim
size_t CArray::mDim private
Referenced by dimensionality(), operator[](), and resize().
mFactors
index_type CArray::mFactors private
Referenced by operator[](), and resize().
mSizes
index_type CArray::mSizes private
Referenced by operator[](), resize(), and size().
The documentation for this class was generated from the following files:
CArray.h
CArray.cpp