COPASI API: CProblemFactory Class Reference
CProblemFactory Class Reference
#include <CProblemFactory.h>
Static Public Member Functions
static CCopasiProblem * copy (const CCopasiProblem *pSrc, const CDataContainer *pParent)
static CCopasiProblem * create (const CTaskEnum::Task &type, const CDataContainer *pParent)
Member Function Documentation
copy()
CCopasiProblem * CProblemFactory::copy (const CCopasiProblem * pSrc, const CDataContainer * pParent) static
References CTaskEnum::analytics, CTaskEnum::crosssection, CTaskEnum::fluxMode, CCopasiTask::getMathContainer(), CDataObject::getObjectParent(), CCopasiProblem::getType(), CTaskEnum::lna, CTaskEnum::lyap, CTaskEnum::mca, CTaskEnum::moieties, CTaskEnum::optimization, CTaskEnum::parameterFitting, CTaskEnum::scan, CTaskEnum::sens, CCopasiProblem::setMathContainer(), CTaskEnum::steadyState, CTaskEnum::timeCourse, CTaskEnum::timeSens, and CTaskEnum::tssAnalysis.
Referenced by CCopasiTask::CCopasiTask(), and CCopasiProblem::copy().
create()
CCopasiProblem * CProblemFactory::create (const CTaskEnum::Task & type, const CDataContainer * pParent) static
References CTaskEnum::analytics, CTaskEnum::crosssection, CTaskEnum::fluxMode, CCopasiTask::getMathContainer(), CDataObject::getObjectParent(), CTaskEnum::lna, CTaskEnum::lyap, CTaskEnum::mca, CTaskEnum::moieties, CTaskEnum::optimization, CTaskEnum::parameterFitting, CTaskEnum::scan, CTaskEnum::sens, CCopasiProblem::setMathContainer(), CTaskEnum::steadyState, CTaskEnum::timeCourse, CTaskEnum::timeSens, and CTaskEnum::tssAnalysis.
Referenced by CCopasiTask::CCopasiTask().
The documentation for this class was generated from the following files:
CProblemFactory.h
CProblemFactory.cpp