COPASI API: CDataContainer Class Reference
CDataContainer Class Reference
#include <CDataContainer.h>
Inherits CDataObject.
Inherited by CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, CBiologicalDescription, CChemEq, CChemEqElement, CCopasiParameter, CCopasiTask, CCreator, CDataArray, CDataModel, CDataVector< CType >, CEigen, CEvaluationTree, CEvent, CEventAssignment, CFittingPoint, CFunctionDB, CFunctionParameter, CFunctionParameters, CInfo, CLGradientBase, CLGraphicalObject, CLGroup, CLLineEnding, CLRenderInformationBase, CLStyle, CLayout, CMIRIAMInfo, CMathContainer, CMetabOld, CModelEntity, CModelParameterSet, CModification, CMoiety, CReaction, CReference, CRootContainer, CSlider, CStatistics, CUnitDefinition, and SCopasiXMLGUI.
Public Types
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual CData toData () const override
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CDataContainer ()
Member Typedef Documentation
objectMap
typedef CDataObjectMap CDataContainer::objectMap
Constructor & Destructor Documentation
CDataContainer() [1/4]
CDataContainer::CDataContainer () private
Referenced by fromData().
CDataContainer() [2/4]
CDataContainer::CDataContainer (const CDataContainer & src) protected
CDataContainer() [3/4]
CDataContainer::CDataContainer (const std::string & name, const CDataContainer * pParent = NO_PARENT, const std::string & type = "CN", const CFlags< Flag > & flag = CFlags< Flag >::None)
CDataContainer() [4/4]
CDataContainer::CDataContainer (const CDataContainer & src, const CDataContainer * pParent)
~CDataContainer()
CDataContainer::~CDataContainer () virtual
References CDataObjectMap::begin(), CDataObjectMap::end(), mObjects, and CDataObject::setObjectParent().
Member Function Documentation
add()
bool CDataContainer::add (CDataObject * pObject, const bool & adopt = true) virtual
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, and CDataVector< CLGraphicalObject >.
References CDataObject::addReference(), CDataObject::getValidity(), CDataObjectMap::insert(), mObjects, CDataObject::setObjectParent(), and CDataObject::validityChanged().
Referenced by CDataVector< CType >::add(), CDataVectorN< CType >::add(), CCopasiParameterGroup::addParameter(), CDataObject::CDataObject(), CUndoData::change(), CModelEntity::compile(), CMetab::compile(), CCopasiSpringLayout::createLayout(), CDataModel::importSBML(), CDataModel::importSBMLFromString(), CDataVector< CType >::insert(), CCopasiParameterGroup::insert(), CMIRIAMInfo::load(), CDataModel::loadModel(), CCopasiParameterGroup::operator=(), CEvent::setDelayExpressionPtr(), CEventAssignment::setExpressionPtr(), CModelEntity::setExpressionPtr(), CReaction::setFunctionFromExpressionTree(), CModelEntity::setInitialExpressionPtr(), CModelEntity::setNoiseExpressionPtr(), CReaction::setNoiseExpressionPtr(), CEvent::setPriorityExpressionPtr(), CModelEntity::setStatus(), CEvent::setTriggerExpressionPtr(), CUnitDefinition::setup(), and SEDMLImporter::updateContent().
addMatrixReference()
template<class CType > CDataMatrixReference< CType > * CDataContainer::addMatrixReference (const std::string & name, CType & reference, const CFlags< Flag > & flag = CFlags< Flag >::None) protected
Referenced by CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), and CModel::initObjects().
addObjectReference()
template<class CType > CDataObjectReference< CType > * CDataContainer::addObjectReference (const std::string & name, CType & reference, const CFlags< Flag > & flag = CFlags< Flag >::None) protected
Referenced by CCopasiParameter::createValue(), CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), CAnalyticsTask::initObjects(), CStatistics::initObjects(), CCrossSectionTask::initObjects(), CBitPatternMethod::initObjects(), CBitPatternTreeMethod::initObjects(), CEFMAlgorithm::initObjects(), CEvaluationTree::initObjects(), CFunctionDB::initObjects(), CLyapTask::initObjects(), CChemEqElement::initObjects(), CMetab::initObjects(), CModel::initObjects(), CModelEntity::initObjects(), CMoiety::initObjects(), CReaction::initObjects(), COptMethodCoranaWalk::initObjects(), COptMethodHookeJeeves::initObjects(), COptMethodLevenbergMarquardt::initObjects(), COptMethodNelderMead::initObjects(), COptMethodNL2SOL::initObjects(), COptMethodPraxis::initObjects(), COptMethodPS::initObjects(), COptMethodSA::initObjects(), COptMethodSS::initObjects(), COptMethodSteepestDescent::initObjects(), COptMethodTruncatedNewton::initObjects(), COptPopulationMethod::initObjects(), COptProblem::initObjects(), CRandomSearch::initObjects(), CFittingPoint::initObjects(), CFitProblem::initObjects(), CEigen::initObjects(), and CCopasiTask::initObjects().
addVectorReference()
template<class CType > CDataVectorReference< CType > * CDataContainer::addVectorReference (const std::string & name, CType & reference, const CFlags< Flag > & flag = CFlags< Flag >::None) protected
Referenced by CLyapTask::initObjects(), COptProblem::initObjects(), and CEigen::initObjects().
appendDeletedDependentData()
bool CDataContainer::appendDeletedDependentData (CUndoData & undoData) const virtual
Append all required dependent undo data
Parameters
CUndoData & undoData
Returns
bool dataAppended
References CUndoData::addPreProcessData(), CModel::appendAllDependents(), CFunctionDB::appendDependentFunctions(), CUndoData::getAuthorID(), CDataModel::getModel(), CDataObject::getObjectAncestor(), CDataObject::getObjectDataModel(), and CUndoData::REMOVE.
Referenced by createUndoData().
applyData()
bool CDataContainer::applyData (const CData & data, CUndoData::CChangeSet & changes) override virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataObject.
Reimplemented in CCopasiParameter, CModelEntity, CMetab, CUnitDefinition, CSlider, CCopasiTask, CCopasiParameterGroup, CPlotSpecification, CPlotItem, CFittingPoint, CReaction, CMoiety, CModelValue, CModelParameterSet, CModel, CMetabOld, CEvent, CEventAssignment, CCompartment, CReference, CModification, CMIRIAMInfo, CCreator, CBiologicalDescription, CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLReferenceGlyph, CLLocalStyle, CLLocalRenderInformation, CLLineEnding, CLGraphicalObject, CLGradientBase, CLTextGlyph, CLCompartmentGlyph, CLMetabGlyph, CLGlobalStyle, CLGlobalRenderInformation, CLayout, CFunctionParameter, CFunction, CEvaluationTree, CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, and CDataModel.
References CDataObject::applyData().
Referenced by CEvaluationTree::applyData(), CFunctionParameter::applyData(), CBiologicalDescription::applyData(), CCreator::applyData(), CMIRIAMInfo::applyData(), CModification::applyData(), CReference::applyData(), CEventAssignment::applyData(), CEvent::applyData(), CModelParameterSet::applyData(), CReaction::applyData(), CCopasiTask::applyData(), CUnitDefinition::applyData(), CModelEntity::applyData(), and CCopasiParameter::applyData().
createUndoData()
void CDataContainer::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const override virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataObject.
Reimplemented in CCopasiParameter, CModelEntity, CMetab, CUnitDefinition, CCopasiTask, CCopasiParameterGroup, CReaction, CModelValue, CModelParameterSet, CModel, CEvent, CEventAssignment, CCompartment, CReference, CModification, CMIRIAMInfo, CCreator, CBiologicalDescription, CFunction, CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, and CDataVector< CLGraphicalObject >.
References appendDeletedDependentData(), CDataObject::createUndoData(), and CUndoData::REMOVE.
Referenced by CFunction::createUndoData(), CBiologicalDescription::createUndoData(), CCreator::createUndoData(), CMIRIAMInfo::createUndoData(), CModification::createUndoData(), CReference::createUndoData(), CEventAssignment::createUndoData(), CEvent::createUndoData(), CModelParameterSet::createUndoData(), CReaction::createUndoData(), CCopasiTask::createUndoData(), CUnitDefinition::createUndoData(), CModelEntity::createUndoData(), and CCopasiParameter::createUndoData().
fromData()
CDataContainer * CDataContainer::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CDataContainer * pDataObject
References CDataContainer(), CData::getProperty(), NO_PARENT, CData::OBJECT_FLAG, CData::OBJECT_NAME, CData::OBJECT_TYPE, and CDataValue::toString().
getChildObjectUnits()
std::string CDataContainer::getChildObjectUnits (const CDataObject * pObject) const virtual
Retrieve the units of the child object.
Returns
std::string units
Reimplemented in CModelEntity, CMetab, CReaction, and CModel.
Referenced by CDataObject::getUnits().
getDescendants()
void CDataContainer::getDescendants (CDataObject::DataObjectSet & descendants, const bool & recursive = false) const
Retrieve all descendant objects (optionally recursive)
Parameters
CDataObject::DataObjectSet & descendants
const bool & recursive (default: false)
References CDataObjectMap::begin(), CDataObjectMap::end(), getDescendants(), and mObjects.
Referenced by CModel::appendAllDependents(), CModel::appendDirectDependents(), CModelExpansion::SetOfModelElements::fillDependencies(), getDescendants(), and CMathContainer::removeDataObject().
getIndex()
size_t CDataContainer::getIndex (const CDataObject * pObject) const virtual
Reimplemented in CCopasiParameterGroup, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, and CDataVector< CLGraphicalObject >.
References C_INVALID_INDEX.
Referenced by CModel::createMetabolite(), CDataObject::createUndoData(), CDataObject::getCN(), CModelParameterSet::getIndex(), CDataVector< CType >::getIndex(), CCopasiParameterGroup::getIndex(), CModel::load(), and CDataObject::toData().
getObject()
const CObjectInterface * CDataContainer::getObject (const CCommonName & cn) const override virtual
Retrieve a descendant object by its CN.
Parameters
const CCommonName & cn
Returns
const CObjectInterface * pObject
Reimplemented from CDataObject.
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, CCopasiParameterGroup, CReaction, CMathContainer, and CDataArray.
References CAnnotation::allocateMiriamInfo(), CDataObject::Array, CAnnotation::castObject(), CDataObject::Container, CDataObjectMap::equal_range(), CCommonName::getElementName(), CObjectInterface::getObject(), getObject(), CDataObject::getObject(), CCommonName::getObjectName(), CDataObject::getObjectName(), CCommonName::getObjectType(), CDataObject::getObjectType(), CCommonName::getRemainder(), CRootContainer::getRoot(), CDataObject::hasFlag(), CDataObject::Matrix, mObjects, and CDataObject::Root.
Referenced by CSBMLExporter::addInitialAssignmentsToModel(), CDataObject::applyData(), CSBMLExporter::checkForUnsupportedObjectReferences(), CEvaluationNodeCall::compile(), CEventAssignment::compile(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), SBMLImporter::createCModelFromSBMLDocument(), COutputAssistant::createDefaultOutput(), CModel::createEventsForTimeseries(), CExpression::createInitialExpression(), CModelExpansion::duplicateEvent(), CSBMLExporter::exportEventAssignments(), CSEDMLExporter::exportNthScanItem(), CDataModel::findObjectByDisplayName(), CObjectLists::getListOfConstObjects(), CMathContainer::getMathObject(), CEvaluationTree::getNodeObject(), CDataArray::getObject(), CMathContainer::getObject(), CReaction::getObject(), CCopasiParameterGroup::getObject(), getObject(), CDataVector< CType >::getObject(), CUndoData::getObject(), CFittingPoint::getObjectDisplayName(), SEDMLUtils::getObjectForSbmlId(), CObjectInterface::GetObjectFromCN(), CUndoData::getParent(), CSBMLExporter::hasVolumeAssignment(), CExpression::initObjects(), CSBMLExporter::isEventSBMLCompatible(), CEvaluationNodeObject::mapObject(), CModelMerging::mergeInExpression(), CMoietiesProblem::printResult(), CSBMLExporter::replaceSpeciesReferences(), SBMLImporter::replaceTimeAndAvogadroNodeNames(), CReaction::resolveCN(), SEDMLUtils::resolveDatagenerator(), SBMLImporter::sbmlId2CopasiCN(), CSEDMLExporter::setCurrentTime(), SBMLImporter::setInitialValues(), CDataObject::setObjectName(), and CModelExpansion::updateExpression().
getObjects() [1/2]
CDataContainer::objectMap & CDataContainer::getObjects () virtual
References mObjects.
getObjects() [2/2]
const CDataContainer::objectMap & CDataContainer::getObjects () const virtual
References mObjects.
Referenced by CMetabNameInterface::doesExist(), CModel::findMetabByName(), CDataVectorN< CType >::getObject(), CUndoData::getObject(), CCopasiParameterGroup::getParameter(), CDataVectorN< CType >::isInsertAllowed(), CMetabNameInterface::isUnique(), CCopasiParameterGroup::operator=(), CDataVectorN< CType >::operator[](), and CModel::prepareElasticity().
getUnits()
const std::string CDataContainer::getUnits () const override virtual
Retrieve the units of the object.
Returns
std::string units
Reimplemented from CDataObject.
Reimplemented in CMetab, CModelValue, CModel, and CCompartment.
Referenced by CModelEntity::getChildObjectUnits(), CReactionInterface::getUnit(), and CReactionInterface::getUnitVector().
getValueObject()
const CDataObject * CDataContainer::getValueObject () const override virtual
Reimplemented from CDataObject.
Reimplemented in CModelEntity, and CMetab.
References CDataObjectMap::begin(), CDataObjectMap::end(), CDataObject::getValuePointer(), and mObjects.
Referenced by CTimeSensMethod::initializeDerivativesCalculations().
initObjects()
void CDataContainer::initObjects () protected
Referenced by COptMethodStatistics::COptMethodStatistics().
insert()
CUndoObjectInterface * CDataContainer::insert (const CData & data) override virtual
Create and insert an undo object based on the given data. This method needs to be re-implemented in container which support INSERT and REMOVE
Parameters
const CData & data
Returns
CUndoObjectInterface * pUndoObject
Reimplemented from CUndoObjectInterface.
Reimplemented in CCopasiParameterGroup, CModelParameterSet, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, and CDataVector< CLGraphicalObject >.
Referenced by CModel::appendAllDependents(), CUnitDefinitionDB::appendDependentUnits(), CModel::appendDirectDependents(), CDataObject::applyData(), CSBMLExporter::createFunctionDefinitions(), CChemEqInterface::createNonExistingMetabs(), CReactionInterface::createOtherObjects(), CCopasiParameterGroup::createUndoData(), CODEExporterC::exportSingleFunction(), CLGeneralGlyph::exportToSBML(), CLayout::exportToSBML(), SBMLImporter::findFunctionCalls(), CSBMLExporter::findModelEntityDependencies(), CLRenderFlattener::flatten(), CObjectLists::getEventTargets(), CUndoData::insert(), CCopasiTask::isTaskValid(), CCopasiParameterGroup::operator=(), CModel::removeLocalReactionParameter(), and SBMLImporter::removeUnusedFunctions().
objectRenamed()
void CDataContainer::objectRenamed (CDataObject * pObject, const std::string & oldName)
References mObjects, and CDataObjectMap::objectRenamed().
remove()
bool CDataContainer::remove (CDataObject * pObject) virtual
Removes the pointer to the object, from the vector
Parameters
CDataObject * pObject
Returns
bool success
Reimplemented in CUnitDefinitionDB, CCopasiParameterGroup, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, and CDataVector< CLGraphicalObject >.
References CDataObjectMap::erase(), CDataObject::getValidity(), mObjects, CDataObject::removeReference(), and CDataObject::validityRemoved().
Referenced by CUndoData::change(), CDataVector< CType >::cleanup(), CDataVector< CType >::clear(), CDataModel::commonAfterLoad(), CBiologicalDescription::fromData(), CCreator::fromData(), CModification::fromData(), CReference::fromData(), CCopasiParameterGroup::remove(), CDataVector< CType >::remove(), CDataVector< CType >::resize(), CEvent::setDelayExpressionPtr(), CEventAssignment::setExpressionPtr(), CModelEntity::setExpressionPtr(), CModelEntity::setInitialExpressionPtr(), CModelEntity::setNoiseExpressionPtr(), CReaction::setNoiseExpressionPtr(), CDataObject::setObjectParent(), CEvent::setPriorityExpressionPtr(), CEvent::setTriggerExpressionPtr(), CDataObject::~CDataObject(), and CUnitDefinition::~CUnitDefinition().
toData()
CData CDataContainer::toData () const override virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataObject.
Reimplemented in CCopasiParameter, CModelEntity, CMetab, CUnitDefinition, CSlider, CCopasiTask, CCopasiParameterGroup, CPlotSpecification, CPlotItem, CFittingPoint, CReaction, CMoiety, CModelValue, CModelParameterSet, CModel, CMetabOld, CEvent, CEventAssignment, CCompartment, CReference, CModification, CMIRIAMInfo, CCreator, CBiologicalDescription, CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLReferenceGlyph, CLLocalStyle, CLLocalRenderInformation, CLLineEnding, CLGraphicalObject, CLGradientBase, CLTextGlyph, CLCompartmentGlyph, CLMetabGlyph, CLGlobalStyle, CLGlobalRenderInformation, CLayout, CFunctionParameter, CFunction, CEvaluationTree, CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, and CDataModel.
References CDataObject::toData().
Referenced by CEvaluationTree::toData(), CFunctionParameter::toData(), CBiologicalDescription::toData(), CCreator::toData(), CMIRIAMInfo::toData(), CModification::toData(), CReference::toData(), CEventAssignment::toData(), CEvent::toData(), CModelParameterSet::toData(), CReaction::toData(), CCopasiTask::toData(), CUnitDefinition::toData(), CModelEntity::toData(), and CCopasiParameter::toData().
Member Data Documentation
EmptyList
const CObjectInterface::ContainerList CDataContainer::EmptyList static
Class CDataContainer
This class is the is used to group CDataObjects logically. It itself is an object. Contained objects are still globally accessible.
Copyright Stefan Hoops 2002
Referenced by COptItem::setLowerBound(), and COptItem::setUpperBound().
mObjects
objectMap CDataContainer::mObjects protected
Referenced by add(), CDataVector< CType >::beginName(), CCopasiParameterGroup::beginName(), CDataVector< CType >::endName(), CCopasiParameterGroup::endName(), getDescendants(), CDataArray::getObject(), getObject(), getObjects(), getValueObject(), objectRenamed(), remove(), and ~CDataContainer().
The documentation for this class was generated from the following files:
CDataContainer.h
CDataContainer.cpp