COPASI API: CUnitComponent Class Reference
CUnitComponent Class Reference
#include <CUnitComponent.h>
Public Member Functions
CUnitComponent (CBaseUnit::Kind kind, double multiplier=1, double scale=0, double exponent=1)
CUnitComponent (const CUnitComponent &src)
double getExponent () const
CBaseUnit::Kind getKind () const
double getMultiplier () const
double getScale () const
bool isValid () const
bool operator< (const CUnitComponent &rightSide) const
bool operator== (const CUnitComponent &rightSide) const
void setExponent (double exponent)
void setKind (CBaseUnit::Kind kind)
void setMultiplier (double multiplier)
void setScale (double scale)
~CUnitComponent ()
Private Member Functions
CUnitComponent ()
Private Attributes
double mExponent
CBaseUnit::Kind mKind
double mMultiplier
double mScale
Friends
std::ostream & operator<< (std::ostream &os, const CUnitComponent &o)
Constructor & Destructor Documentation
CUnitComponent() [1/3]
CUnitComponent::CUnitComponent () private
CUnitComponent() [2/3]
CUnitComponent::CUnitComponent (CBaseUnit::Kind kind, double multiplier = 1, double scale = 0, double exponent = 1)
CUnitComponent() [3/3]
CUnitComponent::CUnitComponent (const CUnitComponent & src)
Copy constructor
Parameters
const CUnitComponent & src
const CDataContainer * pParent (default: NULL)
~CUnitComponent()
CUnitComponent::~CUnitComponent ()
Member Function Documentation
getExponent()
double CUnitComponent::getExponent () const
References mExponent.
Referenced by CUnit::addComponent(), addCUnitComponentToUnitDefinition(), addSymbolComponentToUnitDefinition(), and CUnit::exponentiate().
getKind()
CBaseUnit::Kind CUnitComponent::getKind () const
References mKind.
Referenced by CUnit::addComponent(), and addCUnitComponentToUnitDefinition().
getMultiplier()
double CUnitComponent::getMultiplier () const
References mMultiplier.
Referenced by CUnit::addComponent(), addCUnitComponentToUnitDefinition(), addSymbolComponentToUnitDefinition(), and CUnit::exponentiate().
getScale()
double CUnitComponent::getScale () const
References mScale.
Referenced by CUnit::addComponent(), addCUnitComponentToUnitDefinition(), addSymbolComponentToUnitDefinition(), and CUnit::exponentiate().
isValid()
bool CUnitComponent::isValid () const
References mExponent, and mScale.
operator<()
bool CUnitComponent::operator< (const CUnitComponent & rightSide) const
References mKind.
operator==()
bool CUnitComponent::operator== (const CUnitComponent & rightSide) const
References mExponent, mKind, mMultiplier, and mScale.
setExponent()
void CUnitComponent::setExponent (double exponent)
References mExponent.
Referenced by CUnit::addComponent(), addSymbolComponentToUnitDefinition(), CUnit::exponentiate(), and CUnit::setDimensionLess().
setKind()
void CUnitComponent::setKind (CBaseUnit::Kind kind)
References mKind.
setMultiplier()
void CUnitComponent::setMultiplier (double multiplier)
References mMultiplier.
Referenced by CUnit::addComponent(), addSymbolComponentToUnitDefinition(), CUnit::exponentiate(), and CUnit::setDimensionLess().
setScale()
void CUnitComponent::setScale (double scale)
References mScale.
Referenced by CUnit::addComponent(), addSymbolComponentToUnitDefinition(), CUnit::exponentiate(), and CUnit::setDimensionLess().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CUnitComponent & o) friend
Member Data Documentation
mExponent
double CUnitComponent::mExponent private
Referenced by getExponent(), isValid(), operator==(), and setExponent().
mKind
CBaseUnit::Kind CUnitComponent::mKind private
Referenced by getKind(), operator<(), operator==(), and setKind().
mMultiplier
double CUnitComponent::mMultiplier private
Referenced by getMultiplier(), operator==(), and setMultiplier().
mScale
double CUnitComponent::mScale private
Referenced by getScale(), isValid(), operator==(), and setScale().
The documentation for this class was generated from the following files:
CUnitComponent.h
CUnitComponent.cpp