COPASI API: CTaskFactory Class Reference
CTaskFactory Class Reference
#include <CTaskFactory.h>
Static Public Member Functions
static CCopasiTask * copy (const CCopasiTask *pSrc, const CDataContainer *pParent)
static CCopasiTask * create (const CTaskEnum::Task &type, const CDataContainer *pParent)
Member Function Documentation
copy()
CCopasiTask * CTaskFactory::copy (const CCopasiTask * pSrc, const CDataContainer * pParent) static
References CTaskEnum::analytics, CTaskEnum::crosssection, CTaskEnum::fluxMode, CCopasiTask::getType(), CTaskEnum::lna, CTaskEnum::lyap, CTaskEnum::mca, CTaskEnum::moieties, CTaskEnum::optimization, CTaskEnum::parameterFitting, CTaskEnum::scan, CTaskEnum::sens, CTaskEnum::steadyState, CTaskEnum::timeCourse, CTaskEnum::timeSens, and CTaskEnum::tssAnalysis.
Referenced by CFitProblem::initialize(), and COptProblem::initializeSubtaskBeforeOutput().
create()
CCopasiTask * CTaskFactory::create (const CTaskEnum::Task & type, const CDataContainer * pParent) static
References CTaskEnum::analytics, CTaskEnum::crosssection, CTaskEnum::fluxMode, CTaskEnum::lna, CTaskEnum::lyap, CTaskEnum::mca, CTaskEnum::moieties, CTaskEnum::optimization, CTaskEnum::parameterFitting, CTaskEnum::scan, CTaskEnum::sens, CTaskEnum::steadyState, CTaskEnum::timeCourse, CTaskEnum::timeSens, and CTaskEnum::tssAnalysis.
Referenced by CDataModel::addTask(), CMethodFactory::create(), CCopasiTask::fromData(), SEDMLImporter::importTask(), TaskHandler::processStart(), and SEDMLImporter::updateCopasiTaskForSimulation().
The documentation for this class was generated from the following files:
CTaskFactory.h
CTaskFactory.cpp