COPASI API: CCopasiParameterGroup.h File Reference
CCopasiParameterGroup.h File Reference
#include <string>
#include <vector>
#include "copasi/utilities/CCopasiParameter.h"
#include "copasi/utilities/CCopasiMessage.h"
Classes
class CCopasiParameterGroup
Functions
template<typename ElevateTo , typename ElevateFrom >
ElevateTo * elevate (CCopasiParameter *pParm)
Function Documentation
elevate()
template<typename ElevateTo , typename ElevateFrom > ElevateTo* elevate (CCopasiParameter * pParm)
Elevate a CCopasiParameter pointer to ElevateTo. If pParm is NULL, not of type ElevateFrom, or the elevation fails a NULL pointer is returned. If the elevation is success full the parameter *pParm is replaced with the elevated object.
Parameters
CCopasiParameter * pParm
Returns
ElevateTo * pTo
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), CCopasiMessage::ERROR, CDataObject::getObjectParent(), MCParameter, and NO_PARENT.