COPASI API: COptLog Class Reference
COptLog Class Reference
#include <COptLog.h>
Public Member Functions
std::vector< COptLogEntry >::const_iterator begin () const
COptLog ()
std::vector< COptLogEntry >::const_iterator end () const
void enterLogEntry (COptLogEntry entry)
size_t getElementCount () const
std::string getPlainLog () const
std::string getRichLog () const
virtual ~COptLog ()
Private Attributes
std::vector< COptLogEntry > mLogEntries
Constructor & Destructor Documentation
COptLog()
COptLog::COptLog ()
Default constructor.
COptLog class Container for a log of events registed by the copasi optimization methods. Stores a list of COptLogItems and has methods for generation of a complete log string.
~COptLog()
COptLog::~COptLog () virtual
Destructor
Member Function Documentation
begin()
std::vector< COptLogEntry >::const_iterator COptLog::begin () const
References mLogEntries.
end()
std::vector< COptLogEntry >::const_iterator COptLog::end () const
References mLogEntries.
enterLogEntry()
void COptLog::enterLogEntry (COptLogEntry entry)
Enter a log message
Parameters
COptLogEntry entry
References mLogEntries.
Referenced by COptMethodEP::creation(), COptMethodSRES::creation(), COptMethodDE::initialize(), COptMethodGASR::initialize(), COptMethodPS::initialize(), COptMethodSRES::initialize(), CTruncatedNewton::lmqnbc_(), lsout_(), CTruncatedNewton::modlnp_(), monit_(), COptMethodCoranaWalk::optimise(), COptMethodDE::optimise(), COptMethodEP::optimise(), COptMethodGA::optimise(), COptMethodGASR::optimise(), COptMethodHookeJeeves::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodNelderMead::optimise(), COptMethodNL2SOL::optimise(), COptMethodPraxis::optimise(), COptMethodPS::optimise(), COptMethodSA::optimise(), COptMethodSRES::optimise(), COptMethodSteepestDescent::optimise(), COptMethodTruncatedNewton::optimise(), CRandomSearch::optimise(), and COptMethodTruncatedNewton::sFun().
getElementCount()
size_t COptLog::getElementCount () const
Get the log element count
Returns
unsigned C_INT32 elementCount
References mLogEntries.
getPlainLog()
std::string COptLog::getPlainLog () const
Retrieve the method log as plain text. Uses html tables for detailed log.
Returns
std::string plainLog
References mLogEntries.
getRichLog()
std::string COptLog::getRichLog () const
Retrieve the method log as rich text. Uses html headings, divs and tables.
Returns
std::string richLog
References mLogEntries.
Member Data Documentation
mLogEntries
std::vector< COptLogEntry > COptLog::mLogEntries private
A vector of all log entries
Referenced by begin(), end(), enterLogEntry(), getElementCount(), getPlainLog(), and getRichLog().
The documentation for this class was generated from the following files:
COptLog.h
COptLog.cpp