COPASI API: CTimeSensProblem Class Reference
CTimeSensProblem Class Reference
#include <CTimeSensProblem.h>
Public Member Functions
void addParameterCN (const CCommonName &cn)
void addTargetCN (const CCommonName &cn)
void clearParameterCNs ()
void clearTargetCNs ()
CTimeSensProblem (const CDataContainer *pParent=NO_PARENT)
CTimeSensProblem (const CTimeSensProblem &src, const CDataContainer *pParent)
virtual bool elevateChildren ()
size_t getNumParameters ()
size_t getNumTargets ()
CCommonName getParameterCN (size_t index)
CArray & getScaledStateResult ()
const CArray & getScaledStateResult () const
CDataArray * getScaledStateResultAnnotated ()
const CDataArray * getScaledStateResultAnnotated () const
CArray & getScaledTargetsResult ()
const CArray & getScaledTargetsResult () const
CDataArray * getScaledTargetsResultAnnotated ()
const CDataArray * getScaledTargetsResultAnnotated () const
CArray & getStateResult ()
const CArray & getStateResult () const
CDataArray * getStateResultAnnotated ()
const CDataArray * getStateResultAnnotated () const
CCommonName getTargetCN (size_t index)
CArray & getTargetsResult ()
const CArray & getTargetsResult () const
CDataArray * getTargetsResultAnnotated ()
const CDataArray * getTargetsResultAnnotated () const
void removeParameterCN (const CCommonName &cn)
void removeParameterCN (size_t index)
void removeTargetCN (const CCommonName &cn)
void removeTargetCN (size_t index)
~CTimeSensProblem ()
Public Member Functions inherited from CTrajectoryProblem
CTrajectoryProblem (const CDataContainer *pParent=NO_PARENT)
CTrajectoryProblem (const CTrajectoryProblem &src, const CDataContainer *pParent)
bool getAutomaticStepSize () const
const C_FLOAT64 & getDuration () const
const bool & getOutputEvent () const
const C_FLOAT64 & getOutputStartTime () const
bool getStartInSteadyState () const
const unsigned C_INT32 & getStepNumber () const
const C_FLOAT64 & getStepSize () const
bool getUseValues () const
std::set< C_FLOAT64 > getValues () const
const std::string & getValueString () const
void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::NEXT)
virtual void printResult (std::ostream *ostream) const
void setAutomaticStepSize (const bool &automaticStepSize)
void setDuration (const C_FLOAT64 &duration)
void setOutputEvent (const bool &outputEvent)
void setOutputStartTime (const C_FLOAT64 &endTime)
void setStartInSteadyState (bool flag)
void setStepNumber (const unsigned C_INT32 &stepNumber)
void setStepSize (const C_FLOAT64 &stepSize)
void setTimeSeriesRequested (bool flag)
void setUseValues (bool flag)
void setValues (const std::string &values)
void setValues (const std::vector< C_FLOAT64 > &values)
bool timeSeriesRequested () const
~CTrajectoryProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CDataContainer *pParent)
virtual void clearCallBack ()
CCopasiProblem * copy () const
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
virtual CCopasiTask * getSubTask () const
const CTaskEnum::Task & getType () const
virtual bool initialize ()
virtual void print (std::ostream *ostream) const
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual bool setModel (CModel *model)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Protected Member Functions
CTimeSensProblem (const CTimeSensProblem &src)
Protected Member Functions inherited from CTrajectoryProblem
CTrajectoryProblem (const CTaskEnum::Task &type, const CDataContainer *pParent)
CTrajectoryProblem (const CTrajectoryProblem &src)
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src)
CCopasiProblem (const CTaskEnum::Task &type, const CDataContainer *pParent)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
CCopasiParameterGroup * mpParametersGroup
CDataArray * mpScaledStateResultAnnotation
CDataArray * mpScaledTargetsResultAnnotation
CDataArray * mpStateResultAnnotation
CCopasiParameterGroup * mpTargetsGroup
CDataArray * mpTargetsResultAnnotation
CArray mScaledStateResult
CArray mScaledTargetsResult
CArray mStateResult
CArray mTargetsResult
Protected Attributes inherited from CTrajectoryProblem
bool * mpAutomaticStepSize
C_FLOAT64 * mpDuration
bool * mpOutputEvent
C_FLOAT64 * mpOutputStartTime
bool * mpStartInSteadyState
unsigned C_INT32 * mpStepNumber
C_FLOAT64 * mpStepSize
bool * mpTimeSeriesRequested
bool * mpUseValues
std::string * mpValueString
bool mStepNumberSetLast
Protected Attributes inherited from CCopasiProblem
CMathContainer * mpContainer
CReport * mpReport
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
void initializeParameter ()
void initObjects ()
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Detailed Description
CTimeSensProblem class. This class describes the time sensitivities problem, i.e., it allows to specify for example initial conditions and number of steps.
Constructor & Destructor Documentation
CTimeSensProblem() [1/3]
CTimeSensProblem::CTimeSensProblem (const CTimeSensProblem & src) protected
CTimeSensProblem() [2/3]
CTimeSensProblem::CTimeSensProblem (const CDataContainer * pParent = NO_PARENT)
Default constructor.
Parameters
const CDataContainer * pParent (default: NULL)
CTimeSensProblem class. This class describes the time sensitivities problem, i.e., it allows to specify for example initial conditions and number of steps. Default constructor.
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
CTimeSensProblem() [3/3]
CTimeSensProblem::CTimeSensProblem (const CTimeSensProblem & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CTimeSensProblem & src @paramconst CDataContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CTimeSensProblem & src
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
~CTimeSensProblem()
CTimeSensProblem::~CTimeSensProblem ()
Destructor.
References DESTRUCTOR_TRACE.
Member Function Documentation
addParameterCN()
void CTimeSensProblem::addParameterCN (const CCommonName & cn)
References CCopasiParameterGroup::addParameter(), CCopasiParameter::CN, and mpParametersGroup.
Referenced by CFitProblem::initialize().
addTargetCN()
void CTimeSensProblem::addTargetCN (const CCommonName & cn)
References CCopasiParameterGroup::addParameter(), CCopasiParameter::CN, and mpTargetsGroup.
Referenced by CFitProblem::initialize().
clearParameterCNs()
void CTimeSensProblem::clearParameterCNs ()
References CCopasiParameterGroup::clear(), and mpParametersGroup.
Referenced by CFitProblem::initialize().
clearTargetCNs()
void CTimeSensProblem::clearTargetCNs ()
References CCopasiParameterGroup::clear(), and mpTargetsGroup.
Referenced by CFitProblem::initialize().
elevateChildren()
bool CTimeSensProblem::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CTrajectoryProblem.
References CTrajectoryProblem::elevateChildren().
getNumParameters()
size_t CTimeSensProblem::getNumParameters ()
References mpParametersGroup, and CCopasiParameterGroup::size().
Referenced by getParameterCN(), CTimeSensMethod::initResult(), and removeParameterCN().
getNumTargets()
size_t CTimeSensProblem::getNumTargets ()
References mpTargetsGroup, and CCopasiParameterGroup::size().
Referenced by CTimeSensLsodaMethod::copySensitivitiesToResultMatrix(), getTargetCN(), CTimeSensMethod::initResult(), and removeTargetCN().
getParameterCN()
CCommonName CTimeSensProblem::getParameterCN (size_t index)
References getNumParameters(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), and mpParametersGroup.
Referenced by CTimeSensMethod::initializeDerivativesCalculations(), CTimeSensMethod::initResult(), and removeParameterCN().
getScaledStateResult() [1/2]
CArray & CTimeSensProblem::getScaledStateResult ()
References mScaledStateResult.
Referenced by CTimeSensLsodaMethod::copySensitivitiesToResultMatrix(), and CTimeSensMethod::initResult().
getScaledStateResult() [2/2]
const CArray & CTimeSensProblem::getScaledStateResult () const
References mScaledStateResult.
getScaledStateResultAnnotated() [1/2]
CDataArray * CTimeSensProblem::getScaledStateResultAnnotated ()
References mpScaledStateResultAnnotation.
Referenced by CTimeSensMethod::initResult().
getScaledStateResultAnnotated() [2/2]
const CDataArray * CTimeSensProblem::getScaledStateResultAnnotated () const
References mpScaledStateResultAnnotation.
getScaledTargetsResult() [1/2]
CArray & CTimeSensProblem::getScaledTargetsResult ()
References mScaledTargetsResult.
Referenced by CTimeSensLsodaMethod::copySensitivitiesToResultMatrix(), and CTimeSensMethod::initResult().
getScaledTargetsResult() [2/2]
const CArray & CTimeSensProblem::getScaledTargetsResult () const
References mScaledTargetsResult.
getScaledTargetsResultAnnotated() [1/2]
CDataArray * CTimeSensProblem::getScaledTargetsResultAnnotated ()
References mpScaledTargetsResultAnnotation.
Referenced by CTimeSensMethod::initResult().
getScaledTargetsResultAnnotated() [2/2]
const CDataArray * CTimeSensProblem::getScaledTargetsResultAnnotated () const
References mpScaledTargetsResultAnnotation.
getStateResult() [1/2]
CArray & CTimeSensProblem::getStateResult ()
References mStateResult.
Referenced by CTimeSensLsodaMethod::copySensitivitiesToResultMatrix(), and CTimeSensMethod::initResult().
getStateResult() [2/2]
const CArray & CTimeSensProblem::getStateResult () const
References mStateResult.
getStateResultAnnotated() [1/2]
CDataArray * CTimeSensProblem::getStateResultAnnotated ()
References mpStateResultAnnotation.
Referenced by CTimeSensMethod::initResult().
getStateResultAnnotated() [2/2]
const CDataArray * CTimeSensProblem::getStateResultAnnotated () const
References mpStateResultAnnotation.
getTargetCN()
CCommonName CTimeSensProblem::getTargetCN (size_t index)
References getNumTargets(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), and mpTargetsGroup.
Referenced by CTimeSensMethod::initializeDerivativesCalculations(), CTimeSensMethod::initResult(), and removeTargetCN().
getTargetsResult() [1/2]
CArray & CTimeSensProblem::getTargetsResult ()
References mTargetsResult.
Referenced by CTimeSensLsodaMethod::copySensitivitiesToResultMatrix(), and CTimeSensMethod::initResult().
getTargetsResult() [2/2]
const CArray & CTimeSensProblem::getTargetsResult () const
References mTargetsResult.
getTargetsResultAnnotated() [1/2]
CDataArray * CTimeSensProblem::getTargetsResultAnnotated ()
References mpTargetsResultAnnotation.
Referenced by CFitProblem::calculate(), and CTimeSensMethod::initResult().
getTargetsResultAnnotated() [2/2]
const CDataArray * CTimeSensProblem::getTargetsResultAnnotated () const
References mpTargetsResultAnnotation.
initializeParameter()
void CTimeSensProblem::initializeParameter () private
Initialize the method parameter
References CCopasiParameterGroup::assertGroup(), mpParametersGroup, and mpTargetsGroup.
Referenced by CTimeSensProblem().
initObjects()
void CTimeSensProblem::initObjects () private
References mpScaledStateResultAnnotation, mpScaledTargetsResultAnnotation, mpStateResultAnnotation, mpTargetsResultAnnotation, mScaledStateResult, mScaledTargetsResult, mStateResult, mTargetsResult, CDataArray::Objects, CDataArray::setDescription(), and CDataArray::setMode().
Referenced by CTimeSensProblem().
removeParameterCN() [1/2]
void CTimeSensProblem::removeParameterCN (const CCommonName & cn)
References getNumParameters(), CCopasiParameterGroup::getParameter(), getParameterCN(), CCopasiParameter::getValue(), mpParametersGroup, and CCopasiParameterGroup::removeParameter().
removeParameterCN() [2/2]
void CTimeSensProblem::removeParameterCN (size_t index)
References getNumParameters(), mpParametersGroup, and CCopasiParameterGroup::removeParameter().
removeTargetCN() [1/2]
void CTimeSensProblem::removeTargetCN (const CCommonName & cn)
References getNumTargets(), CCopasiParameterGroup::getParameter(), getTargetCN(), CCopasiParameter::getValue(), mpTargetsGroup, and CCopasiParameterGroup::removeParameter().
removeTargetCN() [2/2]
void CTimeSensProblem::removeTargetCN (size_t index)
References getNumTargets(), mpTargetsGroup, and CCopasiParameterGroup::removeParameter().
Member Data Documentation
mpParametersGroup
CCopasiParameterGroup* CTimeSensProblem::mpParametersGroup protected
Referenced by addParameterCN(), clearParameterCNs(), getNumParameters(), getParameterCN(), initializeParameter(), and removeParameterCN().
mpScaledStateResultAnnotation
CDataArray* CTimeSensProblem::mpScaledStateResultAnnotation protected
Referenced by getScaledStateResultAnnotated(), and initObjects().
mpScaledTargetsResultAnnotation
CDataArray* CTimeSensProblem::mpScaledTargetsResultAnnotation protected
Referenced by getScaledTargetsResultAnnotated(), and initObjects().
mpStateResultAnnotation
CDataArray* CTimeSensProblem::mpStateResultAnnotation protected
Referenced by getStateResultAnnotated(), and initObjects().
mpTargetsGroup
CCopasiParameterGroup* CTimeSensProblem::mpTargetsGroup protected
Referenced by addTargetCN(), clearTargetCNs(), getNumTargets(), getTargetCN(), initializeParameter(), and removeTargetCN().
mpTargetsResultAnnotation
CDataArray* CTimeSensProblem::mpTargetsResultAnnotation protected
Referenced by getTargetsResultAnnotated(), and initObjects().
mScaledStateResult
CArray CTimeSensProblem::mScaledStateResult protected
Referenced by getScaledStateResult(), and initObjects().
mScaledTargetsResult
CArray CTimeSensProblem::mScaledTargetsResult protected
Referenced by getScaledTargetsResult(), and initObjects().
mStateResult
CArray CTimeSensProblem::mStateResult protected
These hold the results
Referenced by getStateResult(), and initObjects().
mTargetsResult
CArray CTimeSensProblem::mTargetsResult protected
Referenced by getTargetsResult(), and initObjects().
The documentation for this class was generated from the following files:
CTimeSensProblem.h
CTimeSensProblem.cpp