COPASI API: CUndoData::CChangeSet Class Reference
CUndoData::CChangeSet Class Reference
#include <CUndoData.h>
Public Types
typedef std::vector< ChangeInfo >::const_iterator const_iterator
Public Member Functions
void add (const ChangeInfo &info)
iterator begin ()
const_iterator begin () const
CChangeSet ()
CChangeSet (const CChangeSet &src)
void clear ()
bool empty () const
iterator end ()
const_iterator end () const
~CChangeSet ()
Private Member Functions
void remove (const size_t &index)
Private Attributes
std::map< std::string, size_t > mMap
Member Typedef Documentation
const_iterator
typedef std::vector< ChangeInfo >::const_iterator CUndoData::CChangeSet::const_iterator
Constructor & Destructor Documentation
CChangeSet() [1/2]
CUndoData::CChangeSet::CChangeSet ()
CChangeSet() [2/2]
CUndoData::CChangeSet::CChangeSet (const CChangeSet & src)
~CChangeSet()
CUndoData::CChangeSet::~CChangeSet ()
Member Function Documentation
add()
void CUndoData::CChangeSet::add (const ChangeInfo & info)
References CUndoData::CHANGE, CUndoData::INSERT, CUndoData::ChangeInfo::objectAfter, CUndoData::ChangeInfo::objectBefore, CUndoData::REMOVE, CUndoData::remove(), and CUndoData::ChangeInfo::type.
Referenced by CCompartment::applyData(), CUndoData::change(), CUndoData::insert(), and CUndoData::remove().
begin() [1/2]
CUndoData::CChangeSet::iterator CUndoData::CChangeSet::begin ()
begin() [2/2]
CUndoData::CChangeSet::const_iterator CUndoData::CChangeSet::begin () const
clear()
void CUndoData::CChangeSet::clear ()
Referenced by CUndoData::insert().
empty()
bool CUndoData::CChangeSet::empty () const
end() [1/2]
CUndoData::CChangeSet::iterator CUndoData::CChangeSet::end ()
end() [2/2]
CUndoData::CChangeSet::const_iterator CUndoData::CChangeSet::end () const
remove()
void CUndoData::CChangeSet::remove (const size_t & index) private
Member Data Documentation
mMap
std::map< std::string, size_t > CUndoData::CChangeSet::mMap private
The documentation for this class was generated from the following files:
CUndoData.h
CUndoData.cpp