COPASI API: CModelEntity Class Reference
CModelEntity Class Reference
#include <CModelValue.h>
Public Types
enum class Status {
FIXED = 0 , ASSIGNMENT , REACTIONS , ODE ,
TIME , __SIZE
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculate ()
CModelEntity (const CModelEntity &src, const CDataContainer *pParent)
CModelEntity (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const std::string &type="ModelEntity", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual CIssue compile ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const override
std::string getDefaultNoiseExpression () const
std::string getExpression () const
CExpression * getExpressionPtr ()
const CExpression * getExpressionPtr () const
std::string getInitialExpression () const
CExpression * getInitialExpressionPtr ()
const CExpression * getInitialExpressionPtr () const
const C_FLOAT64 & getInitialValue () const
CDataObject * getInitialValueReference () const
virtual const std::string & getKey () const override
CModel * getModel () const
std::string getNoiseExpression () const
CExpression * getNoiseExpressionPtr ()
const CExpression * getNoiseExpressionPtr () const
CDataObject * getNoiseReference () const
const C_FLOAT64 & getRate () const
CDataObject * getRateReference () const
const std::string & getSBMLId () const
const CModelEntity::Status & getStatus () const
virtual const std::string & getUnitExpression () const
const C_FLOAT64 & getValue () const
virtual const CDataObject * getValueObject () const override
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
const bool & hasNoise () const
bool isFixed () const
const bool & isUsed () const
CIssue setExpression (const std::string &expression)
bool setExpressionPtr (CExpression *pExpression)
void setHasNoise (const bool &hasNoise)
CIssue setInitialExpression (const std::string &expression)
bool setInitialExpressionPtr (CExpression *pExpression)
virtual void setInitialValue (const C_FLOAT64 &initialValue)
bool setNoiseExpression (const std::string &expression)
bool setNoiseExpressionPtr (CExpression *pExpression)
virtual bool setObjectParent (const CDataContainer *pParent) override
void setRate (const C_FLOAT64 &rate)
void setSBMLId (const std::string &id) const
bool setStatus (const CModelEntity::Status &status)
virtual CIssue setUnitExpression (std::string unitExpression)
void setUsed (const bool &used)
virtual void setValue (const C_FLOAT64 &value)
virtual CData toData () const override
~CModelEntity ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static CModelEntity * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Static Public Attributes
static const CEnumAnnotation< std::string, Status > StatusName
static const CEnumAnnotation< std::string, Status > XMLStatus
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions
CModelEntity (const CModelEntity &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
bool mHasNoise
C_FLOAT64 mIValue
C_FLOAT64 mNoise
CExpression * mpExpression
CExpression * mpInitialExpression
CDataObjectReference< C_FLOAT64 > * mpIValueReference
CModel * mpModel
CExpression * mpNoiseExpression
CDataObjectReference< C_FLOAT64 > * mpNoiseReference
CDataObjectReference< C_FLOAT64 > * mpRateReference
CDataObjectReference< C_FLOAT64 > * mpValueReference
C_FLOAT64 mRate
std::string mSBMLId
std::string mUnitExpression
C_FLOAT64 mValue
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Protected Attributes inherited from CAnnotation
std::string mKey
Private Member Functions
void initObjects ()
Private Attributes
Status mStatus
bool mUsed
Detailed Description
The base class for CCompartment, CMetab and CModelValue. CModelEntity is a base class for CCompartment, CMetab and CModelValue. These three classes have in common that (in the long run) they can each be model variables (subject to ODEs), constant, or subject to algebraic assignments. In addition, the CMetab objects can also be subject to reactions, and conservation rules.
Member Enumeration Documentation
Status
enum CModelEntity::Status strong
The valid states for metabolites
Enumerator
FIXED
ASSIGNMENT
REACTIONS
ODE
TIME
__SIZE
Constructor & Destructor Documentation
CModelEntity() [1/3]
CModelEntity::CModelEntity (const CModelEntity & src) protected
CModelEntity() [2/3]
CModelEntity::CModelEntity (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT, const std::string & type = "ModelEntity", const CFlags< Flag > & flag = CFlags< Flag >::None)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CRootContainer::getKeyFactory(), CDataObject::getObjectType(), CAnnotation::initMiriamAnnotation(), initObjects(), and CAnnotation::mKey.
CModelEntity() [3/3]
CModelEntity::CModelEntity (const CModelEntity & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CModelValue & src
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CDataObject::getObjectType(), initObjects(), CAnnotation::mKey, mStatus, CAnnotation::setMiriamAnnotation(), and setStatus().
~CModelEntity()
CModelEntity::~CModelEntity ()
Destructor.
References DESTRUCTOR_TRACE, mpModel, and CModel::removeModelEntity().
Member Function Documentation
applyData()
bool CModelEntity::applyData (const CData & data, CUndoData::CChangeSet & changes) override virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
Reimplemented in CMetab, CModelValue, CModel, and CCompartment.
References CData::ADD_NOISE, CAnnotation::applyData(), CDataContainer::applyData(), CData::EXPRESSION, CData::getProperty(), CData::INITIAL_EXPRESSION, CData::INITIAL_VALUE, CData::isSetProperty(), mIValue, mpModel, CData::NOISE_EXPRESSION, CModel::setCompileFlag(), setExpression(), setHasNoise(), setInitialExpression(), setNoiseExpression(), setStatus(), CData::SIMULATION_TYPE, StatusName, CDataValue::toBool(), CDataValue::toDouble(), CEnumAnnotation< Type, Enum >::toEnum(), and CDataValue::toString().
Referenced by CCompartment::applyData(), CModel::applyData(), CModelValue::applyData(), and CMetab::applyData().
calculate()
void CModelEntity::calculate (void) virtual
Calculate the value or the rate depending whether we have an ASIGNMENT or ODE
Reimplemented in CMetab.
References ASSIGNMENT, CExpression::calcValue(), mpExpression, mRate, mStatus, mValue, and ODE.
compile()
CIssue CModelEntity::compile () virtual
Compile the model value. This is only needed for status ASIGNMENT and ODE.
Returns
CIssue issue
Reimplemented in CMetab, and CModel.
References CDataContainer::add(), CValidity::add(), ASSIGNMENT, CExpression::calcValue(), CValidity::clear(), CExpression::compile(), CExpression::createInitialExpression(), CIssue::ExpressionEmpty, getExpression(), CValidity::getFirstWorstIssue(), CEvaluationTree::getInfix(), getNoiseExpression(), CDataObject::getObjectDataModel(), CDataObject::getPrerequisites(), CDataObject::getValidity(), mHasNoise, mIValue, mpExpression, mpInitialExpression, mpModel, mpNoiseExpression, CDataObject::mPrerequisits, mStatus, CObjectInterface::mValidity, ODE, pdelete, CDataObject::setObjectName(), and CIssue::Warning.
Referenced by setExpression(), setExpressionPtr(), setInitialExpression(), setInitialExpressionPtr(), setNoiseExpression(), and setNoiseExpressionPtr().
createUndoData()
void CModelEntity::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const override virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
Reimplemented in CMetab, CModelValue, CModel, and CCompartment.
References CData::ADD_NOISE, CUndoData::addProperty(), CUndoData::CHANGE, CAnnotation::createUndoData(), CDataContainer::createUndoData(), CData::EXPRESSION, getExpression(), getInitialExpression(), getNoiseExpression(), CData::getProperty(), CData::INITIAL_EXPRESSION, CData::INITIAL_VALUE, mHasNoise, mIValue, mStatus, CData::NOISE_EXPRESSION, CData::SIMULATION_TYPE, and StatusName.
Referenced by CCompartment::createUndoData(), CModel::createUndoData(), CModelValue::createUndoData(), and CMetab::createUndoData().
fromData()
CModelEntity * CModelEntity::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CModelEntity * pDataObject
getChildObjectUnits()
std::string CModelEntity::getChildObjectUnits (const CDataObject * pObject) const override virtual
Retrieve the units of the child object.
Returns
const & CUnit units
Reimplemented from CDataContainer.
Reimplemented in CMetab, and CModel.
References CModel::getTimeUnit(), CDataContainer::getUnits(), mpIValueReference, mpModel, mpRateReference, and mpValueReference.
Referenced by CModel::getChildObjectUnits(), CMetab::getChildObjectUnits(), and CModelParameter::getUnit().
getDefaultNoiseExpression()
std::string CModelEntity::getDefaultNoiseExpression () const
Retrieve the default expression for the noise.
Returns
std::string expression
References CDataObject::getCN(), and mpRateReference.
getExpression()
std::string CModelEntity::getExpression () const
Retrieve the expression for non FIXED model values.
Returns
std::string expression
References CEvaluationTree::getInfix(), isFixed(), mpExpression, and CExpression::updateInfix().
Referenced by compile(), CMetab::compile(), CMathObject::createExtensiveODERateExpression(), CSBMLExporter::createRule(), createUndoData(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CCopasiXML::saveModel(), CMetab::setObjectParent(), and toData().
getExpressionPtr() [1/2]
CExpression * CModelEntity::getExpressionPtr ()
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
References mpExpression, and CExpression::updateInfix().
getExpressionPtr() [2/2]
const CExpression * CModelEntity::getExpressionPtr () const
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
References mpExpression, and CExpression::updateInfix().
Referenced by CSBMLExporter::checkForPiecewiseFunctions(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CMathObject::compileRate(), CMathObject::compileValue(), CModelAdd::copyExpression(), CSBMLExporter::createRule(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValuesExpressions(), SBMLImporter::importRuleForModelEntity(), CModelMerging::mergeMetabolites(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInModelEntity(), and CMMLOutput::writeRHS_ModelEntity().
getInitialExpression()
std::string CModelEntity::getInitialExpression () const
Retrieve the expression for ODE or REACTION model values.
Returns
std::string expression
References ASSIGNMENT, CEvaluationTree::getInfix(), mpInitialExpression, mStatus, and CExpression::updateInfix().
Referenced by CModelAdd::addCompartmentsExpressions(), CModelAdd::addMetabolitesExpressions(), CModelAdd::addModelValuesExpressions(), CSBMLExporter::createCompartment(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), createUndoData(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CMathContainer::initializeMathObjects(), CModelMerging::mergeMetabolites(), CCopasiXML::saveModel(), and toData().
getInitialExpressionPtr() [1/2]
CExpression * CModelEntity::getInitialExpressionPtr ()
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
References mpInitialExpression, and CExpression::updateInfix().
getInitialExpressionPtr() [2/2]
const CExpression * CModelEntity::getInitialExpressionPtr () const
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
References mpInitialExpression, and CExpression::updateInfix().
Referenced by CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CMathObject::compileInitialValue(), CModelAdd::copyInitialExpression(), CSBMLExporter::createInitialAssignment(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), SBMLImporter::importInitialAssignments(), CModelMerging::mergeMetabolites(), SBMLImporter::removeUnusedFunctions(), and CModelExpansion::replaceInModelEntity().
getInitialValue()
const C_FLOAT64 & CModelEntity::getInitialValue () const
Retrieve the initial value
References mIValue.
Referenced by CModelAdd::addCompartments(), CModelAdd::addModelValues(), addParticleNumberToInitialValueMap(), SBMLImporter::applyConversionFactors(), CFunctionAnalyzer::constructCallParametersActualValues(), CMetab::convertToConcentration(), CMetab::convertToNumber(), CSBMLExporter::createCompartment(), CModelParameterSet::createFromModel(), CSBMLExporter::createMetabolite(), CModel::createMetabolite(), CSBMLExporter::createParameter(), CCSPMethod::cspstep(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CODEExporter::exportCompartments(), CODEExporter::exportExpression(), CODEExporter::exportMetabolites(), CODEExporter::exportModelValues(), CModel::initializeAtolVector(), CReactionInterface::loadMappingAndValues(), CModelParameter::refreshFromModel(), and CModel::suitableForStochasticSimulation().
getInitialValueReference()
CDataObject * CModelEntity::getInitialValueReference () const
Retrieve object referencing the initial value
Returns
CDataObject * initialValueReference
References mpIValueReference.
Referenced by addParticleNumberToInitialValueMap(), CMathObject::compileInitialValue(), CMathObject::createExtensiveValueExpression(), CModelParameterSet::createFromModel(), CSBMLExporter::createInitialAssignment(), CExpression::createInitialExpression(), CDataModel::findObjectByDisplayName(), CMetab::getChildObjectUnits(), getInitialCNForSBase(), CModelParameter::getUnit(), SBMLImporter::importInitialAssignments(), CMathContainer::initializeAtolVector(), CMathContainer::initializeObjects(), CModelParameter::refreshFromModel(), SBMLImporter::replace_time_with_initial_time(), CModelParameterSet::saveToStream(), and SEDMLImporter::updateCopasiTaskForSimulation().
getKey()
const std::string & CModelEntity::getKey () const override virtual
Retrieve the key
Returns
std::string key
Reimplemented from CAnnotation.
Reimplemented in CModel.
References CAnnotation::getKey().
Referenced by CModelAdd::addCompartments(), CModelAdd::addCompartmentsExpressions(), CModelAdd::addMetabolites(), CModelAdd::addMetabolitesExpressions(), CModelAdd::addModelValues(), CModelAdd::addModelValuesExpressions(), addParticleNumberToInitialValueMap(), CModelAdd::addReactions(), CLayoutInitializer::createCompartmentGlyph(), CCopasiSpringLayout::createLayout(), CLayoutInitializer::createMetabGlyph(), CChemEqInterface::createNonExistingMetabs(), CReactionInterface::createOtherObjects(), CSBMLExporter::createSBMLDocument(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CODEExporter::exportExpression(), CODEExporter::exportKineticFunction(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportODEs(), CODEExporterBM::exportSingleCompartment(), CODEExporterC::exportSingleCompartment(), CODEExporterXPPAUT::exportSingleCompartment(), CODEExporterBM::exportSingleMetabolite(), CODEExporterC::exportSingleMetabolite(), CODEExporterXPPAUT::exportSingleMetabolite(), CODEExporterBM::exportSingleModelEntity(), CODEExporterC::exportSingleModelEntity(), CODEExporterXPPAUT::exportSingleModelEntity(), CODEExporterBM::exportSingleModVal(), CODEExporterC::exportSingleModVal(), CODEExporterXPPAUT::exportSingleModVal(), CODEExporterBM::exportSingleODE(), CODEExporterC::exportSingleODE(), CODEExporterXPPAUT::exportSingleODE(), CMetabNameInterface::getMetaboliteKey(), CEFMTask::getSpeciesChanges(), SBMLImporter::importMIRIAM(), CCopasiSpringLayout::initFromLayout(), CODEExporterC::KineticFunction2ODEmember(), CReaction::loadOneRole(), CModelMerging::mergeMetabolites(), CODEExporter::preprocess(), CODEExporterC::preprocess(), CompartmentHandler::processEnd(), MetaboliteHandler::processEnd(), ModelValueHandler::processEnd(), CompartmentGlyphHandler::processStart(), MetaboliteGlyphHandler::processStart(), ModifierHandler::processStart(), ProductHandler::processStart(), SubstrateHandler::processStart(), TextGlyphHandler::processStart(), CCopasiSpringLayout::randomize(), CModel::removeMetabolite(), CModelExpansion::replaceInReaction(), CCopasiXML::saveModel(), CChemEq::setMultiplicity(), CModelMerging::simpleCall(), and CMMLOutput::writeRHS().
getModel()
CModel * CModelEntity::getModel () const
Retrieve a pointer to the model the entity belongs too
Returns
CModel * pModel
References mpModel.
Referenced by CMetab::convertToConcentration(), CMetab::convertToNumber(), CSBMLExporter::createAreaUnit(), SBMLImporter::createCModelFromSBMLDocument(), CSBMLExporter::createCompartments(), CSBMLExporter::createLengthUnit(), CSBMLExporter::createMetabolites(), CSBMLExporter::createParameters(), CSBMLExporter::createReactions(), CSBMLExporter::createSubstanceUnit(), CSBMLExporter::createTimeUnit(), CSBMLExporter::createVolumeUnit(), CSBMLExporter::hasVolumeAssignment(), CDataModel::loadModelParameterSets(), and CILDMMethod::printResult().
getNoiseExpression()
std::string CModelEntity::getNoiseExpression () const
Retrieve the expression for non FIXED model values.
Returns
std::string expression
References CEvaluationTree::getInfix(), mpNoiseExpression, mStatus, ODE, and CExpression::updateInfix().
Referenced by compile(), CMetab::compile(), CMathObject::createExtensiveNoiseExpression(), createUndoData(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CCopasiXML::saveModel(), and toData().
getNoiseExpressionPtr() [1/2]
CExpression * CModelEntity::getNoiseExpressionPtr ()
Retrieve the pointer to the expression for ODE model values.
Returns
CExpression*
References mpNoiseExpression, and CExpression::updateInfix().
getNoiseExpressionPtr() [2/2]
const CExpression * CModelEntity::getNoiseExpressionPtr () const
Retrieve the pointer to the expression for ODE model values.
Returns
CExpression*
References mpNoiseExpression, and CExpression::updateInfix().
Referenced by CMathObject::compileNoise(), CMathObject::createIntensiveNoiseExpression(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), and CModelExpansion::replaceInModelEntity().
getNoiseReference()
CDataObject * CModelEntity::getNoiseReference () const
Retrieve object referencing the noise
Returns
CDataObject * rateReference
References mpNoiseReference.
getRate()
const C_FLOAT64 & CModelEntity::getRate () const
Return rate of production of this entity
References mRate.
getRateReference()
CDataObject * CModelEntity::getRateReference () const
Retrieve object referencing the rate
Returns
CDataObject * rateReference
References mpRateReference.
Referenced by CModel::appendAllDependents(), CMathObject::compileTransitionTime(), CMathObject::createIntensiveRateExpression(), CDataModel::findObjectByDisplayName(), CMathContainer::initializeObjects(), and SEDMLUtils::resolveVariable().
getSBMLId()
const std::string & CModelEntity::getSBMLId () const
Returns a reference to the SBML Id.
References mSBMLId.
Referenced by SBMLImporter::applyStoichiometricExpressions(), CSBMLExporter::collectIds(), CSBMLExporter::createCompartment(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createKineticLaw(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CSBMLExporter::createReaction(), CSBMLExporter::createRule(), CSBMLExporter::createRules(), CSBMLExporter::createSBMLDocument(), CSBMLExporter::createTimesTree(), CSBMLExporter::exportEventAssignments(), SEDMLUtils::getSbmlId(), SBMLImporter::replaceObjectNames(), CCopasiXML::saveModel(), CEvaluationNodeObject::toAST(), and VariableInfo::VariableInfo().
getStatus()
const CModelEntity::Status & CModelEntity::getStatus () const
Retrieve the status of the entity.
Returns
const CModelEntity::Status & status
References mStatus.
Referenced by CModelAdd::addCompartments(), CModelAdd::addMetabolites(), CModelAdd::addModelValues(), CModel::appendAllDependents(), CMetab::calculate(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), CSBMLExporter::checkForPiecewiseFunctions(), CMetab::compile(), CEventAssignment::compile(), CMathObject::compileTransitionTime(), CFunctionAnalyzer::constructCallParametersActualValues(), CSBMLExporter::createCompartment(), CMathObject::createIntensiveRateExpression(), CCopasiSpringLayout::createLayout(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CSBMLExporter::createRule(), CMathEvent::createUpdateSequences(), CModelParameter::diff(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CODEExporter::exportCompartments(), CODEExporter::exportExpression(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValues(), CODEExporter::exportModelValuesExpressions(), CODEExporter::exportODEs(), CODEExporterBM::exportSingleCompartment(), CODEExporterC::exportSingleCompartment(), CODEExporterXPPAUT::exportSingleCompartment(), CODEExporterBM::exportSingleMetabolite(), CODEExporterC::exportSingleMetabolite(), CODEExporterXPPAUT::exportSingleMetabolite(), CODEExporterBM::exportSingleModelEntity(), CODEExporterC::exportSingleModelEntity(), CODEExporterXPPAUT::exportSingleModelEntity(), CODEExporterBM::exportSingleModVal(), CODEExporterC::exportSingleModVal(), CODEExporterXPPAUT::exportSingleModVal(), SBMLImporter::importRuleForModelEntity(), CMathContainer::initializeObjects(), CSBMLExporter::isEventAssignmentSBMLCompatible(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CModelMerging::mergeMetabolites(), CODEExporter::preprocess(), CODEExporterC::preprocess(), SBMLImporter::removeUnusedFunctions(), CSBMLExporter::replaceSpeciesReferences(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameterSets(), CMetab::setObjectParent(), CModelParameter::updateModel(), and CModelParameterSpecies::updateModel().
getUnitExpression()
const std::string & CModelEntity::getUnitExpression () const virtual
Get the unit.
Returns
CUnit &
References mUnitExpression.
Referenced by CSBMLExporter::createParameter(), CModelParameter::getUnit(), and CCopasiXML::saveModel().
getValue()
const C_FLOAT64 & CModelEntity::getValue () const
Retrieve the value
References mValue.
Referenced by CMetab::calculate(), and CSBMLExporter::replaceSpeciesReferences().
getValueObject()
const CDataObject * CModelEntity::getValueObject () const override virtual
Retrieve the object representing the value;
Reimplemented from CDataContainer.
Reimplemented in CMetab.
References mpValueReference.
Referenced by CEventAssignment::CEventAssignment(), and CEventAssignment::compile().
getValuePointer()
void * CModelEntity::getValuePointer () const override virtual
Retrieve a pointer to the value;
Reimplemented from CDataObject.
Reimplemented in CMetab.
References C_FLOAT64, and mValue.
getValueReference()
CDataObject * CModelEntity::getValueReference () const
Retrieve object referencing the value
Returns
CDataObject * valueReference
References mpValueReference.
Referenced by CMathObject::compile(), CTimeSeries::compile(), CMathEvent::CAssignment::compile(), CMathObject::compilePropensity(), CMathObject::compileTransitionTime(), CMathObject::compileValue(), SEDMLUtils::createAmountMV(), CPlotSpecification::createDefaultPlot(), CMathObject::createExtensiveValueExpression(), CExpression::createInitialExpression(), CSBMLExporter::createRule(), CSBMLExporter::exportEventAssignments(), CDataModel::findObjectByDisplayName(), CMathContainer::getCompartment(), CModel::getCorrespondingTransientObject(), CModelParameterGroup::getObjectUnit(), SBMLImporter::importEvent(), SBMLImporter::importRuleForModelEntity(), CMathReaction::initialize(), CMathContainer::initializeObjects(), CSBMLExporter::replaceSpeciesReferences(), SEDMLUtils::resolveVariable(), SBMLImporter::sbmlId2CopasiCN(), CTrajectoryMethodDsaLsodar::start(), and VariableInfo::VariableInfo().
hasNoise()
const bool & CModelEntity::hasNoise () const
Check whether noise is added to the ODE
Returns
const bool & hasNoise
References mHasNoise.
Referenced by CMathObject::compileNoise(), CMathObject::createExtensiveNoiseExpression(), CMathObject::createIntensiveNoiseExpression(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CCopasiXML::saveModel(), and setHasNoise().
initObjects()
void CModelEntity::initObjects () private
Initialize the contained CDataObjects
References CModel::addModelEntity(), CDataContainer::addObjectReference(), CDataObject::getObjectAncestor(), mIValue, mNoise, mpIValueReference, mpModel, mpNoiseReference, mpRateReference, mpValueReference, mRate, mSBMLId, mValue, CDataObject::ValueDbl, and CDataObject::ValueString.
Referenced by CModelEntity().
isFixed()
bool CModelEntity::isFixed () const inline
Check whether the entity is FIXED or not.
Returns
bool isFixed
References FIXED, and mStatus.
Referenced by getExpression(), CMetab::setConcentration(), setExpression(), and setExpressionPtr().
isUsed()
const bool & CModelEntity::isUsed () const
Retrieve whether the model value is used during simulation
Returns
const bool & used
References mUsed.
Referenced by CModel::buildUserOrder().
setExpression()
CIssue CModelEntity::setExpression (const std::string & expression)
Set the expression for non FIXED model values
Parameters
const std::string & expression
Returns
CIssue issue
References CValidity::add(), CFlags< Enum >::All, compile(), CIssue::Error, CEvaluationTree::getInfix(), isFixed(), mpExpression, mpModel, CObjectInterface::mValidity, CValidity::remove(), CModel::setCompileFlag(), CExpression::setInfix(), and CIssue::SettingFixedExpression.
Referenced by applyData(), CModelAdd::copyExpression(), SEDMLUtils::createAmountMV(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CompartmentHandler::processEnd(), MetaboliteHandler::processEnd(), ModelValueHandler::processEnd(), and CMetab::setObjectParent().
setExpressionPtr()
bool CModelEntity::setExpressionPtr (CExpression * pExpression)
Set the expression for non FIXED model values
Parameters
CExpression*
Returns
bool success
References CDataContainer::add(), compile(), isFixed(), mpExpression, mpModel, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
Referenced by SBMLImporter::importRuleForModelEntity().
setHasNoise()
void CModelEntity::setHasNoise (const bool & hasNoise)
Set whether to add noise to the ODE
Parameters
const bool & hasNoise
References hasNoise(), mHasNoise, mpModel, and CModel::setCompileFlag().
Referenced by applyData(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CompartmentHandler::processStart(), MetaboliteHandler::processStart(), and ModelValueHandler::processStart().
setInitialExpression()
CIssue CModelEntity::setInitialExpression (const std::string & expression)
Set the expression for ODE or REACTION model values
Parameters
const std::string & expression
Returns
CIssue issue
References CValidity::add(), CFlags< Enum >::All, ASSIGNMENT, compile(), CIssue::Error, CEvaluationTree::getInfix(), CIssue::InitialExpressionWithAssignment, mpInitialExpression, mpModel, mStatus, CObjectInterface::mValidity, CValidity::remove(), CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by applyData(), CModelAdd::copyInitialExpression(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CompartmentHandler::processEnd(), MetaboliteHandler::processEnd(), ModelHandler::processEnd(), ModelValueHandler::processEnd(), and CModelParameter::updateModel().
setInitialExpressionPtr()
bool CModelEntity::setInitialExpressionPtr (CExpression * pExpression)
Set the expression for non FIXED model values
Parameters
CExpression*
Returns
bool success
References CDataContainer::add(), ASSIGNMENT, compile(), mpInitialExpression, mpModel, mStatus, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
Referenced by SBMLImporter::importInitialAssignments().
setInitialValue()
void CModelEntity::setInitialValue (const C_FLOAT64 & initialValue) virtual
Set the initial value
Parameters
const C_FLOAT64 & initialValue
References mIValue.
Referenced by CModel::createCompartment(), SBMLImporter::createHasOnlySubstanceUnitFactor(), CModel::createMetabolite(), CModel::createModelValue(), CReactionInterface::createUndoData(), CCompartment::load(), CMetab::operator=(), and CModelParameter::updateModel().
setNoiseExpression()
bool CModelEntity::setNoiseExpression (const std::string & expression)
Set the expression for non FIXED model values
Parameters
const std::string & expression
Returns
bool success
References compile(), mpModel, mpNoiseExpression, mStatus, ODE, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by applyData(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CompartmentHandler::processEnd(), MetaboliteHandler::processEnd(), and ModelValueHandler::processEnd().
setNoiseExpressionPtr()
bool CModelEntity::setNoiseExpressionPtr (CExpression * pExpression)
Set the noise expression for ODE model values
Parameters
CExpression*
Returns
bool success
References CDataContainer::add(), compile(), mpModel, mpNoiseExpression, mStatus, ODE, pdelete, CDataContainer::remove(), CModel::setCompileFlag(), CDataObject::setObjectName(), and CDataObject::setObjectParent().
setObjectParent()
bool CModelEntity::setObjectParent (const CDataContainer * pParent) override virtual
Set the object parent
Parameters
const CDataContainer * pParent
Returns
bool success
Reimplemented from CDataObject.
Reimplemented in CMetab, and CModel.
References CModel::addModelEntity(), CDataObject::getObjectAncestor(), mpModel, CModel::removeModelEntity(), and CDataObject::setObjectParent().
Referenced by CMetab::setObjectParent().
setRate()
void CModelEntity::setRate (const C_FLOAT64 & rate)
Set the rate (dmValue/dt)
Parameters
const C_FLOAT64 & rate
References mRate.
setSBMLId()
void CModelEntity::setSBMLId (const std::string & id) const
Sets the SBMLId.
References mSBMLId.
Referenced by SBMLImporter::createCCompartmentFromCompartment(), SBMLImporter::createCMetabFromSpecies(), SBMLImporter::createCModelFromSBMLDocument(), SBMLImporter::createCModelValueFromParameter(), CSBMLExporter::createCompartment(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), and SBMLMapHandler::processStart().
setStatus()
bool CModelEntity::setStatus (const CModelEntity::Status & status)
Set the status
Parameters
const CModelEntity::Status & status
References __SIZE, CDataContainer::add(), ASSIGNMENT, CExpression::createInitialExpression(), FIXED, CDataObject::getObjectDataModel(), CDataObject::getObjectType(), mpExpression, mpInitialExpression, mpModel, mRate, mStatus, mUsed, ODE, pdelete, REACTIONS, CModel::setCompileFlag(), CDataObject::setObjectName(), and TIME.
Referenced by CModelAdd::addCompartments(), CModelAdd::addMetabolites(), CModelAdd::addModelValues(), applyData(), CCompartment::CCompartment(), CMetab::CMetab(), CModel::CModel(), CModelEntity(), SEDMLUtils::createAmountMV(), SBMLImporter::createCMetabFromSpecies(), SBMLImporter::createCReactionFromReaction(), CModel::createMetabolite(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), SBMLImporter::importRuleForModelEntity(), CMetab::load(), CMetab::operator=(), CompartmentHandler::processStart(), MetaboliteHandler::processStart(), ModelValueHandler::processStart(), and CMetab::setObjectParent().
setUnitExpression()
CIssue CModelEntity::setUnitExpression (std::string unitExpression) virtual
Set the unit.
Parameters
const CUnit & unit
Returns
CIssue issue
References CValidity::add(), CFlags< Enum >::All, mUnitExpression, CObjectInterface::mValidity, CValidity::remove(), CUnit::setExpression(), CIssue::UnitConflict, CIssue::UnitInvalid, CIssue::UnitUndefined, and CIssue::Warning.
Referenced by CModelValue::applyData(), SBMLImporter::createCModelValueFromParameter(), and ModelValueHandler::processEnd().
setUsed()
void CModelEntity::setUsed (const bool & used)
Set whether the model entity is used during simulation
Parameters
const bool & used
References mUsed.
Referenced by CModel::CModel().
setValue()
void CModelEntity::setValue (const C_FLOAT64 & value) virtual
Set the value
Parameters
const C_FLOAT64 & value
References mValue.
toData()
CData CModelEntity::toData () const override virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
Reimplemented in CMetab, CModelValue, CModel, and CCompartment.
References CData::ADD_NOISE, CData::addProperty(), CData::appendData(), CData::EXPRESSION, getExpression(), getInitialExpression(), getNoiseExpression(), CData::INITIAL_EXPRESSION, CData::INITIAL_VALUE, mHasNoise, mIValue, mStatus, CData::NOISE_EXPRESSION, CData::SIMULATION_TYPE, StatusName, CAnnotation::toData(), and CDataContainer::toData().
Referenced by CCompartment::toData(), CModel::toData(), CModelValue::toData(), and CMetab::toData().
Member Data Documentation
mHasNoise
bool CModelEntity::mHasNoise protected
A Boolean flag indicating whether to add noise to the reaction
Referenced by compile(), CMetab::compile(), createUndoData(), hasNoise(), setHasNoise(), and toData().
mIValue
C_FLOAT64 CModelEntity::mIValue protected
Pointer to the initial value of the model entity.
Referenced by CCompartment::applyData(), applyData(), CCompartment::CCompartment(), CModel::CModel(), compile(), CMetab::compile(), CCompartment::createUndoData(), createUndoData(), CModel::getInitialTime(), getInitialValue(), initObjects(), CModel::load(), CModel::setInitialTime(), setInitialValue(), CCompartment::toData(), and toData().
mNoise
C_FLOAT64 CModelEntity::mNoise protected
Noise
Referenced by initObjects().
mpExpression
CExpression* CModelEntity::mpExpression protected
The infix expression for objects of type ASSIGNMENT or ODE
Referenced by calculate(), CMetab::calculate(), compile(), CMetab::compile(), getExpression(), getExpressionPtr(), setExpression(), setExpressionPtr(), and setStatus().
mpInitialExpression
CExpression* CModelEntity::mpInitialExpression protected
Optional initial expression
Referenced by compile(), CMetab::compile(), getInitialExpression(), getInitialExpressionPtr(), setInitialExpression(), setInitialExpressionPtr(), and setStatus().
mpIValueReference
CDataObjectReference<C_FLOAT64>* CModelEntity::mpIValueReference protected
Referenced by CMetab::compileIsInitialValueChangeAllowed(), getChildObjectUnits(), getInitialValueReference(), CCompartment::initObjects(), CMetab::initObjects(), CModel::initObjects(), and initObjects().
mpModel
CModel* CModelEntity::mpModel mutable protected
Referenced by CCompartment::applyData(), applyData(), CMetab::calculate(), compile(), CMetab::compileIsInitialValueChangeAllowed(), CModel::createMetabolite(), CMetab::getChildObjectUnits(), getChildObjectUnits(), CMetab::getCountOfDependentReactions(), getModel(), CCompartment::getUnits(), CModel::initObjects(), initObjects(), CMetab::setCompartment(), setExpression(), setExpressionPtr(), setHasNoise(), setInitialExpression(), setInitialExpressionPtr(), setNoiseExpression(), setNoiseExpressionPtr(), setObjectParent(), setStatus(), CModel::~CModel(), and ~CModelEntity().
mpNoiseExpression
CExpression* CModelEntity::mpNoiseExpression protected
Optional noise term for entities of type ODE
Referenced by compile(), CMetab::compile(), getNoiseExpression(), getNoiseExpressionPtr(), setNoiseExpression(), and setNoiseExpressionPtr().
mpNoiseReference
CDataObjectReference<C_FLOAT64>* CModelEntity::mpNoiseReference protected
Referenced by getNoiseReference(), and initObjects().
mpRateReference
CDataObjectReference<C_FLOAT64>* CModelEntity::mpRateReference protected
Referenced by getChildObjectUnits(), getDefaultNoiseExpression(), getRateReference(), CMetab::initObjects(), and initObjects().
mpValueReference
CDataObjectReference<C_FLOAT64>* CModelEntity::mpValueReference protected
Referenced by getChildObjectUnits(), getValueObject(), getValueReference(), CCompartment::initObjects(), CMetab::initObjects(), CModel::initObjects(), and initObjects().
mRate
C_FLOAT64 CModelEntity::mRate protected
Rate of change/time.
Referenced by calculate(), CMetab::calculate(), CMetab::compile(), getRate(), CModel::initObjects(), initObjects(), CMetab::operator=(), setRate(), and setStatus().
mSBMLId
std::string CModelEntity::mSBMLId mutable protected
The id of the corresponding parameter in an SBML file. This value is either set upon importing an SBML file, or when the object is first exported to an SBML file.
Referenced by getSBMLId(), initObjects(), and setSBMLId().
mStatus
Status CModelEntity::mStatus private
Status of the model entity.
Referenced by calculate(), CModelEntity(), compile(), createUndoData(), getInitialExpression(), getNoiseExpression(), getStatus(), isFixed(), setInitialExpression(), setInitialExpressionPtr(), setNoiseExpression(), setNoiseExpressionPtr(), setStatus(), and toData().
mUnitExpression
std::string CModelEntity::mUnitExpression protected
Pointer to the Unit of the model entity.
Referenced by CModelValue::createUndoData(), getUnitExpression(), CModelValue::getUnits(), setUnitExpression(), and CModelValue::toData().
mUsed
bool CModelEntity::mUsed private
Indicates whether the model value is used, i.e., must be calculated during the simulation
Referenced by isUsed(), setStatus(), and setUsed().
mValue
C_FLOAT64 CModelEntity::mValue protected
Pointer to the value of the model entity.
Referenced by calculate(), CMetab::calculate(), CModel::getTime(), getValue(), getValuePointer(), initObjects(), CModel::setTime(), and setValue().
StatusName
const CEnumAnnotation< std::string, CModelEntity::Status > CModelEntity::StatusName static
String representation of the states
Referenced by CModelParameter::applyData(), applyData(), CModelParameter::createUndoData(), createUndoData(), CODEExporter::exportCompartments(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValues(), CModelParameter::toData(), and toData().
XMLStatus
const CEnumAnnotation< std::string, CModelEntity::Status > CModelEntity::XMLStatus static
XML representation of the states
Referenced by CompartmentHandler::processStart(), MetaboliteHandler::processStart(), ModelParameterHandler::processStart(), ModelValueHandler::processStart(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameter(), and CCopasiXML::saveModelParameterSets().
The documentation for this class was generated from the following files:
CModelValue.h
CModelValue.cpp