COPASI API: CCompressedColumnFormat Class Reference
CCompressedColumnFormat Class Reference
#include <CSparseMatrix.h>
Classes
class const_row_iterator
Public Member Functions
const_row_iterator beginRow (const size_t &row) const
CCompressedColumnFormat (const CSparseMatrix &matrix)
CCompressedColumnFormat (const size_t &rows, const size_t &columns, const size_t &nonZeros)
const_row_iterator endRow (const size_t &row) const
size_t * getColumnStart ()
const size_t * getColumnStart () const
size_t * getRowIndex ()
const size_t * getRowIndex () const
C_FLOAT64 * getValues ()
const C_FLOAT64 * getValues () const
size_t numCols () const
size_t numNonZeros () const
size_t numRows () const
CCompressedColumnFormat & operator= (const CSparseMatrix &ccf)
~CCompressedColumnFormat ()
Private Member Functions
CCompressedColumnFormat ()
Private Attributes
size_t mNumCols
size_t mNumRows
size_t * mpColumnStart
size_t * mpRowIndex
C_FLOAT64 * mpValue
Constructor & Destructor Documentation
CCompressedColumnFormat() [1/3]
CCompressedColumnFormat::CCompressedColumnFormat () private
References mNumCols, and mpColumnStart.
CCompressedColumnFormat() [2/3]
CCompressedColumnFormat::CCompressedColumnFormat (const size_t & rows, const size_t & columns, const size_t & nonZeros)
References mNumCols, and mpColumnStart.
CCompressedColumnFormat() [3/3]
CCompressedColumnFormat::CCompressedColumnFormat (const CSparseMatrix & matrix)
~CCompressedColumnFormat()
CCompressedColumnFormat::~CCompressedColumnFormat ()
References mpColumnStart, mpRowIndex, mpValue, pdelete, and pdeletev.
Member Function Documentation
beginRow()
CCompressedColumnFormat::const_row_iterator CCompressedColumnFormat::beginRow (const size_t & row) const
endRow()
CCompressedColumnFormat::const_row_iterator CCompressedColumnFormat::endRow (const size_t & row) const
getColumnStart() [1/2]
size_t * CCompressedColumnFormat::getColumnStart ()
References mpColumnStart.
getColumnStart() [2/2]
const size_t * CCompressedColumnFormat::getColumnStart () const
References mpColumnStart.
Referenced by CCompressedColumnFormat::const_row_iterator::const_row_iterator(), and CSparseMatrix::operator=().
getRowIndex() [1/2]
size_t * CCompressedColumnFormat::getRowIndex ()
References mpRowIndex.
getRowIndex() [2/2]
const size_t * CCompressedColumnFormat::getRowIndex () const
References mpRowIndex.
Referenced by CCompressedColumnFormat::const_row_iterator::const_row_iterator(), and CSparseMatrix::operator=().
getValues() [1/2]
C_FLOAT64 * CCompressedColumnFormat::getValues ()
References mpValue.
getValues() [2/2]
const C_FLOAT64 * CCompressedColumnFormat::getValues () const
References mpValue.
Referenced by CSparseMatrix::operator=().
numCols()
size_t CCompressedColumnFormat::numCols () const
References mNumCols.
Referenced by CSparseMatrix::operator=().
numNonZeros()
size_t CCompressedColumnFormat::numNonZeros () const
References mNumCols, and mpColumnStart.
numRows()
size_t CCompressedColumnFormat::numRows () const
References mNumRows.
Referenced by CCompressedColumnFormat::const_row_iterator::const_row_iterator(), and CSparseMatrix::operator=().
operator=()
CCompressedColumnFormat & CCompressedColumnFormat::operator= (const CSparseMatrix & ccf)
References C_FLOAT64, CSparseMatrix::getColumns(), mNumCols, mNumRows, mpColumnStart, mpRowIndex, mpValue, CSparseMatrix::numCols(), CSparseMatrix::numNonZeros(), CSparseMatrix::numRows(), pdelete, and pdeletev.
Member Data Documentation
mNumCols
size_t CCompressedColumnFormat::mNumCols private
Referenced by CCompressedColumnFormat(), numCols(), numNonZeros(), and operator=().
mNumRows
size_t CCompressedColumnFormat::mNumRows private
Referenced by numRows(), and operator=().
mpColumnStart
size_t* CCompressedColumnFormat::mpColumnStart private
Referenced by CCompressedColumnFormat(), getColumnStart(), numNonZeros(), operator=(), and ~CCompressedColumnFormat().
mpRowIndex
size_t* CCompressedColumnFormat::mpRowIndex private
Referenced by getRowIndex(), CCompressedColumnFormat::const_row_iterator::operator++(), CCompressedColumnFormat::const_row_iterator::operator=(), operator=(), and ~CCompressedColumnFormat().
mpValue
C_FLOAT64* CCompressedColumnFormat::mpValue private
Referenced by getValues(), operator=(), and ~CCompressedColumnFormat().
The documentation for this class was generated from the following files:
CSparseMatrix.h
CSparseMatrix.cpp