COPASI API: VariableInfo Class Reference
VariableInfo Class Reference
#include <SEDMLUtils.h>
Public Member Functions
SedVariable * addToDataGenerator (SedDataGenerator *pGenerator) const
const std::string & getName () const
const std::string & getSbmlId () const
const std::string & getSymbol () const
const std::string & getTerm () const
const std::string & getXpath () const
bool isValid () const
bool operator< (const VariableInfo &other) const
void setName (const std::string &name)
void setSymbol (const std::string &symbol)
void setTerm (const std::string &term)
void setXpath (const std::string &xpath)
VariableInfo (const CDataObject *pObject)
Private Attributes
bool mIsValid
const CDataObject * mpObject
std::string name
std::string sbmlId
std::string symbol
std::string term
std::string xpath
Detailed Description
Utility class for writing SedVariables for objects
Constructor & Destructor Documentation
VariableInfo()
VariableInfo::VariableInfo (const CDataObject * pObject)
References CMetab::getConcentrationReference(), CDataObject::getObjectDisplayName(), CDataObject::getObjectName(), CDataObject::getObjectParent(), CDataObject::getObjectType(), CModelEntity::getSBMLId(), CReaction::getSBMLId(), CModelEntity::getValueReference(), SEDMLUtils::getXPathForObjectAndType(), mIsValid, name, sbmlId, SEDML_KISAO_CONCENTRATION, SEDML_KISAO_CONCENTRATION_RATE, SEDML_KISAO_FLUX, SEDML_KISAO_PARTICLE_RATE, SEDML_KISAO_PARTICLENUMBER, SEDML_KISAO_RATE, SEDML_KISAO_TIME, SEDML_TIME_URN, symbol, term, and xpath.
Member Function Documentation
addToDataGenerator()
SedVariable * VariableInfo::addToDataGenerator (SedDataGenerator * pGenerator) const
References name, symbol, term, and xpath.
Referenced by CSEDMLExporter::createDataGenerator().
getName()
const std::string & VariableInfo::getName () const
References name.
Referenced by CSEDMLExporter::createDataGenerator().
getSbmlId()
const std::string & VariableInfo::getSbmlId () const
References sbmlId.
Referenced by CSEDMLExporter::createDataGenerator().
getSymbol()
const std::string & VariableInfo::getSymbol () const
References symbol.
getTerm()
const std::string & VariableInfo::getTerm () const
References term.
getXpath()
const std::string & VariableInfo::getXpath () const
References xpath.
isValid()
bool VariableInfo::isValid () const
References mIsValid.
operator<()
bool VariableInfo::operator< (const VariableInfo & other) const
References symbol, term, and xpath.
setName()
void VariableInfo::setName (const std::string & name)
References name.
setSymbol()
void VariableInfo::setSymbol (const std::string & symbol)
References symbol.
setTerm()
void VariableInfo::setTerm (const std::string & term)
References term.
setXpath()
void VariableInfo::setXpath (const std::string & xpath)
References xpath.
Member Data Documentation
mIsValid
bool VariableInfo::mIsValid private
Referenced by isValid(), and VariableInfo().
mpObject
const CDataObject* VariableInfo::mpObject private
name
std::string VariableInfo::name private
Referenced by addToDataGenerator(), getName(), setName(), and VariableInfo().
sbmlId
std::string VariableInfo::sbmlId private
Referenced by getSbmlId(), and VariableInfo().
symbol
std::string VariableInfo::symbol private
Referenced by addToDataGenerator(), getSymbol(), operator<(), setSymbol(), and VariableInfo().
term
std::string VariableInfo::term private
Referenced by addToDataGenerator(), getTerm(), operator<(), setTerm(), and VariableInfo().
xpath
std::string VariableInfo::xpath private
Referenced by addToDataGenerator(), getXpath(), operator<(), setXpath(), and VariableInfo().
The documentation for this class was generated from the following files:
SEDMLUtils.h
SEDMLUtils.cpp