COPASI API: CJitCompiler Class Reference
CJitCompiler Class Reference
#include <CJitCompiler.h>
Public Types
typedef C_FLOAT64(* Function) ()
Public Member Functions
void deregisterExpression (CJitExpression *pExpression)
void registerExpression (CJitExpression *pExpression)
virtual ~CJitCompiler ()
Static Public Member Functions
static CJitCompiler * create ()
static bool JitEnabled ()
Protected Member Functions
CJitCompiler ()
CJitCompiler (const CJitCompiler &src)
Protected Attributes
std::set< CJitExpression * > mExpressions
Static Private Attributes
static bool * pSSE4support = NULL
Member Typedef Documentation
Function
typedef C_FLOAT64(* CJitCompiler::Function) ()
Constructor & Destructor Documentation
CJitCompiler() [1/2]
CJitCompiler::CJitCompiler () protected
CJitCompiler() [2/2]
CJitCompiler::CJitCompiler (const CJitCompiler & src) protected
~CJitCompiler()
CJitCompiler::~CJitCompiler () virtual
Member Function Documentation
create()
CJitCompiler * CJitCompiler::create () static
deregisterExpression()
void CJitCompiler::deregisterExpression (CJitExpression * pExpression)
References mExpressions.
Referenced by CJitExpression::setCompiler(), and CJitExpression::~CJitExpression().
JitEnabled()
bool CJitCompiler::JitEnabled () static
References CRootContainer::getConfiguration(), CConfigurationFile::getDisableJIT(), and pSSE4support.
Referenced by registerExpression().
registerExpression()
void CJitCompiler::registerExpression (CJitExpression * pExpression)
References JitEnabled(), and mExpressions.
Referenced by CJitExpression::setCompiler().
Member Data Documentation
mExpressions
std::set< CJitExpression * > CJitCompiler::mExpressions protected
A set of a compiled expression
Referenced by deregisterExpression(), and registerExpression().
pSSE4support
bool * CJitCompiler::pSSE4support = NULL static private
A pointer to a bool indicating whether the CPU supports the sse4.2 instruction set required for JIT compilation
Referenced by JitEnabled().
The documentation for this class was generated from the following files:
CJitCompiler.h
CJitCompiler.cpp