COPASI API: CLGroup Class Reference
CLGroup Class Reference
#include <CLGroup.h>
Public Member Functions
void addChildElement (const CLTransformation2D *pChild)
CLGroup (CDataContainer *pParent=NULL)
CLGroup (const CLGroup &source, CDataContainer *pParent=NULL)
CLGroup (const RenderGroup &source, CDataContainer *pParent=NULL)
CLRenderCurve * createCurve ()
CLEllipse * createEllipse ()
CLGroup * createGroup ()
CLImage * createImage ()
CLPolygon * createPolygon ()
CLRectangle * createRectangle ()
CLText * createText ()
CDataObject * getElement (size_t n)
const CDataObject * getElement (size_t n) const
const std::string & getEndHead () const
const std::string & getFontFamily () const
CLRelAbsVector & getFontSize ()
const CLRelAbsVector & getFontSize () const
CLText::FONT_STYLE getFontStyle () const
CLText::FONT_WEIGHT getFontWeight () const
const std::string & getKey () const
CDataVector< CDataObject > * getListOfElements ()
const CDataVector< CDataObject > * getListOfElements () const
size_t getNumElements () const
const std::string & getStartHead () const
CLText::TEXT_ANCHOR getTextAnchor () const
CLText::TEXT_ANCHOR getVTextAnchor () const
bool isSetEndHead () const
bool isSetFontFamily () const
bool isSetFontSize () const
bool isSetFontStyle () const
bool isSetFontWeight () const
bool isSetStartHead () const
bool isSetTextAnchor () const
bool isSetVTextAnchor () const
void setEndHead (const std::string &key)
void setFontFamily (const std::string &family)
void setFontSize (const CLRelAbsVector &size)
void setFontStyle (CLText::FONT_STYLE style)
void setFontWeight (CLText::FONT_WEIGHT weight)
void setStartHead (const std::string &key)
void setTextAnchor (CLText::TEXT_ANCHOR anchor)
void setVTextAnchor (CLText::TEXT_ANCHOR anchor)
RenderGroup * toSBML (unsigned int level, unsigned int version) const
~CLGroup ()
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual CData toData () const override
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Protected Attributes
CDataVector< CDataObject > mElements
std::string mEndHead
std::string mFontFamily
CLRelAbsVector mFontSize
CLText::FONT_STYLE mFontStyle
CLText::FONT_WEIGHT mFontWeight
std::string mKey
std::string mStartHead
CLText::TEXT_ANCHOR mTextAnchor
CLText::TEXT_ANCHOR mVTextAnchor
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLGroup & operator= (const CLGroup &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET , NONZERO , EVENODD , INHERIT }
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLGroup() [1/3]
CLGroup::CLGroup (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
Referenced by addChildElement(), CLGroup(), and createGroup().
CLGroup() [2/3]
CLGroup::CLGroup (const CLGroup & source, CDataContainer * pParent = NULL)
Copy constructor.
References CDataVector< CType >::add(), CKeyFactory::add(), CLGroup(), CRootContainer::getKeyFactory(), mElements, mKey, and CDataVector< CType >::size().
CLGroup() [3/3]
CLGroup::CLGroup (const RenderGroup & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
References CDataVector< CType >::add(), CKeyFactory::add(), CLText::ANCHOR_BOTTOM, CLText::ANCHOR_END, CLText::ANCHOR_MIDDLE, CLText::ANCHOR_START, CLText::ANCHOR_TOP, CLText::ANCHOR_UNSET, CLGroup(), CRootContainer::getKeyFactory(), mElements, mKey, setFontStyle(), setFontWeight(), setTextAnchor(), setVTextAnchor(), CLText::STYLE_ITALIC, CLText::STYLE_NORMAL, CLText::STYLE_UNSET, CLText::WEIGHT_BOLD, CLText::WEIGHT_NORMAL, and CLText::WEIGHT_UNSET.
~CLGroup()
CLGroup::~CLGroup ()
Destructor.
Destructor
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
addChildElement()
void CLGroup::addChildElement (const CLTransformation2D * pChild)
Adds a copy of the given element to the end of the list of children elements.
References CDataVector< CType >::add(), CLGroup(), and mElements.
Referenced by GroupHandler::processEnd().
createCurve()
CLRenderCurve * CLGroup::createCurve ()
Creates a curve object and adds it to the end of the list of child elements.
References CDataVector< CType >::add(), and mElements.
createEllipse()
CLEllipse * CLGroup::createEllipse ()
Creates an ellipse object and adds it to the end of the list of child elements.
References CDataVector< CType >::add(), and mElements.
createGroup()
CLGroup * CLGroup::createGroup ()
Creates an image object and adds it to the end of the list of child elements.
References CDataVector< CType >::add(), CLGroup(), and mElements.
createImage()
CLImage * CLGroup::createImage ()
Creates an image object and adds it to the end of the list of child elements.
References CDataVector< CType >::add(), and mElements.
createPolygon()
CLPolygon * CLGroup::createPolygon ()
Creates a polygon object and adds it to the end of the list of child elements.
References CDataVector< CType >::add(), and mElements.
createRectangle()
CLRectangle * CLGroup::createRectangle ()
Creates a rectangle object and adds it to the end of the list of child elements.
References CDataVector< CType >::add(), and mElements.
createText()
CLText * CLGroup::createText ()
Creates a text object and adds it to the end of the list of child elements.
References CDataVector< CType >::add(), and mElements.
getElement() [1/2]
CDataObject * CLGroup::getElement (size_t n)
Returns element with index n. If there is no such element, NULL is returned.
References mElements, and CDataVector< CType >::size().
Referenced by CLLayoutRenderer::draw_group(), CCopasiXML::saveGroupElement(), and CLLayoutRenderer::update_textures_and_colors().
getElement() [2/2]
const CDataObject * CLGroup::getElement (size_t n) const
Returns element with index n. If there is no such element, NULL is returned.
References mElements, and CDataVector< CType >::size().
getEndHead()
const std::string & CLGroup::getEndHead () const
Returns the end head id.
References mEndHead.
Referenced by CLLayoutRenderer::update_textures_and_colors().
getFontFamily()
const std::string & CLGroup::getFontFamily () const
Returns the font family.
References mFontFamily.
Referenced by CLLayoutRenderer::getFontSpec(), and toSBML().
getFontSize() [1/2]
CLRelAbsVector & CLGroup::getFontSize ()
Returns the font size.
References mFontSize.
Referenced by CLLayoutRenderer::getFontSpec(), and toSBML().
getFontSize() [2/2]
const CLRelAbsVector & CLGroup::getFontSize () const
Returns the font size.
References mFontSize.
getFontStyle()
CLText::FONT_STYLE CLGroup::getFontStyle () const
Returns the font style.
References mFontStyle.
Referenced by CLLayoutRenderer::getFontSpec(), and toSBML().
getFontWeight()
CLText::FONT_WEIGHT CLGroup::getFontWeight () const
Returns the font weight.
References mFontWeight.
Referenced by CLLayoutRenderer::getFontSpec(), and toSBML().
getKey()
const std::string & CLGroup::getKey () const virtual
Returns the key string of the object.
Returns the key of the color definition.
Reimplemented from CDataObject.
References mKey.
getListOfElements() [1/2]
CDataVector< CDataObject > * CLGroup::getListOfElements ()
Returns the list of elements.
References mElements.
getListOfElements() [2/2]
const CDataVector< CDataObject > * CLGroup::getListOfElements () const
Returns the list of elements.
References mElements.
getNumElements()
size_t CLGroup::getNumElements () const
Returns the number of elements in the group.
References mElements, and CDataVector< CType >::size().
Referenced by CLLayoutRenderer::draw_group(), CCopasiXML::saveGroupElement(), and CLLayoutRenderer::update_textures_and_colors().
getStartHead()
const std::string & CLGroup::getStartHead () const
Returns the start head id.
References mStartHead.
Referenced by CLLayoutRenderer::update_textures_and_colors().
getTextAnchor()
CLText::TEXT_ANCHOR CLGroup::getTextAnchor () const
Returns the text anchor.
References mTextAnchor.
Referenced by toSBML().
getVTextAnchor()
CLText::TEXT_ANCHOR CLGroup::getVTextAnchor () const
Returns the vertical text anchor.
References mVTextAnchor.
Referenced by toSBML().
isSetEndHead()
bool CLGroup::isSetEndHead () const
Returns true if the start head is set or false otherwise.
References mEndHead.
Referenced by StyleHandler::processEnd(), and CLLayoutRenderer::update_textures_and_colors().
isSetFontFamily()
bool CLGroup::isSetFontFamily () const
Returns true if the font family has been set or false otherwise.
References mFontFamily.
Referenced by CLLayoutRenderer::getFontSpec(), and StyleHandler::processEnd().
isSetFontSize()
bool CLGroup::isSetFontSize () const
Returns true if the font size has been set or false otherwise.
References CLRelAbsVector::getAbsoluteValue(), and mFontSize.
Referenced by CLLayoutRenderer::getFontSpec().
isSetFontStyle()
bool CLGroup::isSetFontStyle () const
Returns true if the font style has been set or false otherwise.
References mFontStyle, and CLText::STYLE_UNSET.
Referenced by CLLayoutRenderer::getFontSpec(), and StyleHandler::processEnd().
isSetFontWeight()
bool CLGroup::isSetFontWeight () const
Returns true if the font weight has been set or false otherwise.
References mFontWeight, and CLText::WEIGHT_UNSET.
Referenced by CLLayoutRenderer::getFontSpec(), and StyleHandler::processEnd().
isSetStartHead()
bool CLGroup::isSetStartHead () const
Returns true if the start head is set or false otherwise.
References mStartHead.
Referenced by StyleHandler::processEnd(), and CLLayoutRenderer::update_textures_and_colors().
isSetTextAnchor()
bool CLGroup::isSetTextAnchor () const
Returns true if the horizonal alignment attribute has been set.
This methods imports a curve in the old format into the new format. Since the old curves could have gaps, the original curve might have to be split into several new curves. void CLGroup::importOldCurve(const XMLNode& node) { const XMLAttributes& curveAttributes=node.getAttributes(); const XMLNode* child; size_t n=0,nMax = node.getNumChildren(); const XMLNode* pOrigAnnotation=NULL; const XMLNode* pOrigNotes=NULL; while(n<nMax) { child=&node.getChild(n); std::string childName=child->getName(); if(childName=="listOfCurveSegments") { size_t i,iMax=child->getNumChildren(); const XMLNode* child2=NULL; CLRenderPoint start; CLRenderPoint end; CLRenderPoint lastEnd; CLRenderPoint bp1; CLRenderPoint bp2; bool startSet=false; bool endSet=false; bool bp1Set=false; bool bp2Set=false; std::string childName2; CLRenderCurve* pCurve=new CLRenderCurve(); read the attributes pCurve->Transformation2D::readAttributes(curveAttributes); pCurve->GraphicalPrimitive1D::readAttributes(curveAttributes); pCurve->readAttributes(curveAttributes); for(i=0;i<iMax;++i) { child2=&child->getChild(i); childName2=child2->getName(); if(childName2=="curveSegment") { startSet=false; endSet=false; bp1Set=false; bp2Set=false; const XMLAttributes& innerAttributes=child2->getAttributes(); int typeIndex=innerAttributes.getIndex("type"); if(typeIndex==-1 || innerAttributes.getURI(typeIndex)!="http://www.w3.org/2001/XMLSchema-instance") { continue; } size_t j,jMax=child2->getNumChildren(); for(j=0;j<jMax;++j) { const XMLNode* child3=&child2->getChild(j); std::string childName3=child3->getName(); if(childName3=="start") { start=CLRenderPoint(<em>child3); startSet=true; } add the basepoints and the endpoint else if(childName3=="end") { end=CLRenderPoint(*child3); endSet=true; } else if(innerAttributes.getValue(typeIndex)=="CubicBezier" && childName3=="basePoint1") { bp1=CLRenderPoint(*child3); bp1Set=true; } else if(innerAttributes.getValue(typeIndex)=="CubicBezier" && childName3=="basePoint2") { bp2=CLRenderPoint(*child3); bp2Set=true; } } if(!startSet || !endSet) { skip this point TODO this is an error continue; } if(pCurve->getNumElements()==0) { add the start point pCurve->addCurveElement(&start); } else { check if start is identical to lastEnd if not, we have to start a new curve if(!(start == lastEnd)) { if(pCurve->getNumElements() > 1) { add the curve to the goup this->mElements.add(pCurve,true); } else { delete pCurve; } we have do clear the endHead on the preceeding curve pCurve->setEndHead("none"); pCurve=new CLRenderCurve(); read the attributes pCurve->Transformation2D::readAttributes(curveAttributes); pCurve->GraphicalPrimitive1D::readAttributes(curveAttributes); pCurve->readAttributes(curveAttributes); we have to clear the start head on this curve pCurve->setStartHead("none"); pCurve->addCurveElement(&start); } } if(innerAttributes.getValue(typeIndex)=="CubicBezier") { if(!bp1Set) { if(bp2Set) { basepoint1 is the same as basepoint2 bp1=bp2; } else { bp1=CLRenderPoint(CLRelAbsVector((start.x().getAbsoluteValue()+end.x().getAbsoluteValue())/2.0,(start.x().getRelativeValue()+end.x().getRelativeValue())/2.0) ,CLRelAbsVector((start.y().getAbsoluteValue()+end.y().getAbsoluteValue())/2.0,(start.y().getRelativeValue()+end.y().getRelativeValue())/2.0) ,CLRelAbsVector((start.z().getAbsoluteValue()+end.z().getAbsoluteValue())/2.0,(start.z().getRelativeValue()+end.z().getRelativeValue())/2.0)); bp1Set=true; } } if(!bp2Set) { at this time bp1 has to be set bp2=bp1; } add the cubic bezier element CLRenderCubicBezier pBezier=new CLRenderCubicBezier(bp1.x(),bp1.y(),bp1.z(), bp2.x(),bp2.y(),bp2.z(), end.x(),end.y(),end.z()); pCurve->addCurveElement(pBezier); delete pBezier; lastEnd=end; } else { add the end point pCurve->addCurveElement(&end); lastEnd=end; } } } if(pCurve->getNumElements() > 1) { add the curve to the goup this->mElements.add(pCurve,true); } } else if(childName=="annotation") { pOrigAnnotation=child; } else if(childName=="notes") { pOrigNotes=child; } ++n; } } Returns true if the horizonal alignment attribute has been set.
References CLText::ANCHOR_UNSET, and mTextAnchor.
Referenced by StyleHandler::processEnd().
isSetVTextAnchor()
bool CLGroup::isSetVTextAnchor () const
Returns true if the vertical alignment attribute has been set.
References CLText::ANCHOR_UNSET, and mVTextAnchor.
Referenced by StyleHandler::processEnd().
operator=()
CLGroup& CLGroup::operator= (const CLGroup & source) private
setEndHead()
void CLGroup::setEndHead (const std::string & key)
Sets the end head id.
References mEndHead.
Referenced by StyleHandler::processEnd(), and GroupHandler::processStart().
setFontFamily()
void CLGroup::setFontFamily (const std::string & family)
Sets the font family.
References mFontFamily.
Referenced by StyleHandler::processEnd(), and GroupHandler::processStart().
setFontSize()
void CLGroup::setFontSize (const CLRelAbsVector & size)
Sets the font size.
References mFontSize.
Referenced by GroupHandler::processStart().
setFontStyle()
void CLGroup::setFontStyle (CLText::FONT_STYLE style)
Sets the font style.
References mFontStyle.
Referenced by CLGroup(), StyleHandler::processEnd(), and GroupHandler::processStart().
setFontWeight()
void CLGroup::setFontWeight (CLText::FONT_WEIGHT weight)
Sets the font weight.
References mFontWeight.
Referenced by CLGroup(), StyleHandler::processEnd(), and GroupHandler::processStart().
setStartHead()
void CLGroup::setStartHead (const std::string & key)
Sets the start head id.
References mStartHead.
Referenced by StyleHandler::processEnd(), and GroupHandler::processStart().
setTextAnchor()
void CLGroup::setTextAnchor (CLText::TEXT_ANCHOR anchor)
Sets the text anchor.
References mTextAnchor.
Referenced by CLGroup(), StyleHandler::processEnd(), and GroupHandler::processStart().
setVTextAnchor()
void CLGroup::setVTextAnchor (CLText::TEXT_ANCHOR anchor)
Sets the vertical text anchor.
References mVTextAnchor.
Referenced by CLGroup(), StyleHandler::processEnd(), and GroupHandler::processStart().
toSBML()
RenderGroup * CLGroup::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLGraphicalPrimitive2D::addSBMLAttributes(), CLText::ANCHOR_BOTTOM, CLText::ANCHOR_END, CLText::ANCHOR_MIDDLE, CLText::ANCHOR_UNSET, getFontFamily(), getFontSize(), getFontStyle(), getFontWeight(), CLText::getText(), getTextAnchor(), getVTextAnchor(), mElements, mEndHead, mStartHead, CDataVector< CType >::size(), CLText::STYLE_ITALIC, CLText::STYLE_UNSET, CLRelAbsVector::toSBML(), CLText::WEIGHT_BOLD, and CLText::WEIGHT_UNSET.
Referenced by CLStyle::addSBMLAttributes(), and CLLineEnding::toSBML().
Member Data Documentation
mElements
CDataVector<CDataObject> CLGroup::mElements protected
Referenced by addChildElement(), CLGroup(), createCurve(), createEllipse(), createGroup(), createImage(), createPolygon(), createRectangle(), createText(), getElement(), getListOfElements(), getNumElements(), and toSBML().
mEndHead
std::string CLGroup::mEndHead protected
Referenced by getEndHead(), isSetEndHead(), setEndHead(), and toSBML().
mFontFamily
std::string CLGroup::mFontFamily protected
Referenced by getFontFamily(), isSetFontFamily(), and setFontFamily().
mFontSize
CLRelAbsVector CLGroup::mFontSize protected
Referenced by getFontSize(), isSetFontSize(), and setFontSize().
mFontStyle
CLText::FONT_STYLE CLGroup::mFontStyle protected
Referenced by getFontStyle(), isSetFontStyle(), and setFontStyle().
mFontWeight
CLText::FONT_WEIGHT CLGroup::mFontWeight protected
Referenced by getFontWeight(), isSetFontWeight(), and setFontWeight().
mKey
std::string CLGroup::mKey protected
key for the object.
Referenced by CLGroup(), getKey(), and ~CLGroup().
mStartHead
std::string CLGroup::mStartHead protected
Referenced by getStartHead(), isSetStartHead(), setStartHead(), and toSBML().
mTextAnchor
CLText::TEXT_ANCHOR CLGroup::mTextAnchor protected
Referenced by getTextAnchor(), isSetTextAnchor(), and setTextAnchor().
mVTextAnchor
CLText::TEXT_ANCHOR CLGroup::mVTextAnchor protected
Referenced by getVTextAnchor(), isSetVTextAnchor(), and setVTextAnchor().
The documentation for this class was generated from the following files:
CLGroup.h
CLGroup.cpp