COPASI API: CSteadyStateTask Class Reference
CSteadyStateTask Class Reference
#include <CSteadyStateTask.h>
Public Member Functions
CSteadyStateTask (const CDataContainer *pParent, const CTaskEnum::Task &type=CTaskEnum::Task::steadyState)
CSteadyStateTask (const CSteadyStateTask &src, const CDataContainer *pParent)
const CEigen & getEigenValues () const
const CEigen & getEigenValuesReduced () const
const CMatrix< C_FLOAT64 > & getJacobian () const
const CDataArray * getJacobianAnnotated () const
const CMatrix< C_FLOAT64 > & getJacobianReduced () const
const CDataArray * getJacobianXAnnotated () const
const CSteadyStateMethod::ReturnCode & getResult () const
const CVectorCore< C_FLOAT64 > & getState () const
virtual const CTaskEnum::Method * getValidMethods () const override
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream) override
void load (CReadConfig &configBuffer)
virtual void print (std::ostream *ostream) const override
virtual bool process (const bool &useInitialValues) override
virtual bool restore (const bool &updateModel=true) override
virtual bool updateMatrices () override
virtual ~CSteadyStateTask ()
Public Member Functions inherited from CCopasiTask
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiTask (const CCopasiTask &src, const CDataContainer *pParent)
CCopasiTask (const CDataContainer *pParent, const CTaskEnum::Task &taskType, const std::string &type="Task")
void cleanup ()
virtual void clearCallBack ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const CProcessReportLevel & getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CMathContainer * getMathContainer () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CReport & getReport () const
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
CTaskEnum::Task getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReportLevel callBack)
void setIgnoreProblemData (const bool &ignoreProblemData)
void setMathContainer (CMathContainer *pContainer)
bool setMethodType (const CTaskEnum::Method &type)
void setScheduled (const bool &scheduled)
void setType (const CTaskEnum::Task &type)
virtual void setUpdateModel (const bool &updateModel)
virtual CData toData () const
virtual ~CCopasiTask ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Private Member Functions
void cleanup ()
CSteadyStateTask ()
void initObjects ()
Private Attributes
CEigen mEigenValues
CMatrix< C_FLOAT64 > mEigenvaluesMatrix
CEigen mEigenValuesX
CMatrix< C_FLOAT64 > mEigenvaluesXMatrix
CMatrix< C_FLOAT64 > mJacobian
CMatrix< C_FLOAT64 > mJacobianReduced
CDataArray * mpEigenvaluesJacobianAnn
CDataArray * mpEigenvaluesJacobianXAnn
CDataArray * mpJacobianAnn
CDataArray * mpJacobianXAnn
CSteadyStateMethod::ReturnCode mResult
CVector< C_FLOAT64 > mSteadyState
Friends
std::ostream & operator<< (std::ostream &os, const CSteadyStateTask &A)
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01 , STREAM = 0x02 , FINISH = 0x04 , REPORT = 0x10 ,
PLOT = 0x20 , TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0 , OUTPUT_BEFORE = INITIALIZE , OUTPUT_DURING = STREAM , OUTPUT_AFTER = FINISH ,
OUTPUT = REPORT | PLOT | STREAM , OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH , OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH , ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiTask
static CCopasiTask * fromData (const CData &data, CUndoObjectInterface *pParent)
static bool isValidMethod (const CTaskEnum::Method &method, const CTaskEnum::Method *validMethods)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CCopasiTask
bool isTaskValid () const
virtual void signalMathContainerChanged ()
virtual void signalMethodChanged ()
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
bool mIgnoreProblemData
CVector< C_FLOAT64 > mInitialState
std::string mKey
unsigned C_INT32 mOutputCounter
CMathContainer * mpContainer
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CProcessReportLevel mProcessReport
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
CTaskEnum::Task mType
bool mUpdateModel
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CSteadyStateTask() [1/3]
CSteadyStateTask::CSteadyStateTask () private
Default constructor
CSteadyStateTask() [2/3]
CSteadyStateTask::CSteadyStateTask (const CDataContainer * pParent, const CTaskEnum::Task & type = CTaskEnum::Task::steadyState)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Task & type (default: steadyState)
References CMethodFactory::create(), CCopasiTask::getType(), initObjects(), CCopasiTask::mpMethod, and CTaskEnum::Newton.
CSteadyStateTask() [3/3]
CSteadyStateTask::CSteadyStateTask (const CSteadyStateTask & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CSteadyStateTask & src
const CDataContainer * pParent (default: NULL)
References initObjects().
~CSteadyStateTask()
CSteadyStateTask::~CSteadyStateTask () virtual
Destructor
Member Function Documentation
cleanup()
void CSteadyStateTask::cleanup () private
cleanup()
getEigenValues()
const CEigen & CSteadyStateTask::getEigenValues () const
Retrieves a the eigenvalues of the steady state.
Returns
const CEigen & eigenValues
References mEigenValues.
getEigenValuesReduced()
const CEigen & CSteadyStateTask::getEigenValuesReduced () const
Retrieves a the eigenvalues of the steady state.
Returns
const CEigen & eigenValues
References mEigenValuesX.
Referenced by CLNATask::process().
getJacobian()
const CMatrix< C_FLOAT64 > & CSteadyStateTask::getJacobian () const
Retrieves a the jacobian of the steady state.
Returns
const CMatrix< C_FLOAT64 > jacobian
References mJacobian.
Referenced by CMCAMethod::createLinkMatrix().
getJacobianAnnotated()
const CDataArray * CSteadyStateTask::getJacobianAnnotated () const
References mpJacobianAnn.
getJacobianReduced()
const CMatrix< C_FLOAT64 > & CSteadyStateTask::getJacobianReduced () const
Retrieves a the jacobian of the steady state.
Returns
const CMatrix< C_FLOAT64 > jacobian
References mJacobianReduced.
getJacobianXAnnotated()
const CDataArray * CSteadyStateTask::getJacobianXAnnotated () const
References mpJacobianXAnn.
getResult()
const CSteadyStateMethod::ReturnCode& CSteadyStateTask::getResult () const inline
Converts the eigenvalues vector to matrix
Parameters
CEigen &eigenvalues
Returns
CMatrix<C_FLOAT64> &matrix
References mResult.
Referenced by CLNATask::process(), and CMCAMethod::setSteadyStateTask().
getState()
const CVectorCore< C_FLOAT64 > & CSteadyStateTask::getState () const
Retrieves a pointer to steady state.
Returns
const CVectorCore< C_FLOAT64 > & steadyState
References mSteadyState.
getValidMethods()
const CTaskEnum::Method * CSteadyStateTask::getValidMethods () const override virtual
Retrieve the list of valid methods
Returns
const CTaskEnum::Method * pValidMethods
Reimplemented from CCopasiTask.
References CTaskEnum::Newton, and CTaskEnum::UnsetMethod.
initialize()
bool CSteadyStateTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) override virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
References CMathContainer::getState(), CSteadyStateProblem::initialize(), CSteadyStateMethod::initialize(), CCopasiTask::initialize(), CSteadyStateMethod::isValidProblem(), CCopasiTask::mpContainer, CCopasiTask::mpMethod, CCopasiTask::mpProblem, mSteadyState, and updateMatrices().
Referenced by CFitProblem::initialize(), CTimeSensTask::initialize(), and CTrajectoryTask::initialize().
initObjects()
void CSteadyStateTask::initObjects () private
References mEigenvaluesMatrix, mEigenvaluesXMatrix, mJacobian, mJacobianReduced, mpEigenvaluesJacobianAnn, mpEigenvaluesJacobianXAnn, mpJacobianAnn, mpJacobianXAnn, CDataArray::Objects, CDataArray::setDescription(), CDataArray::setDimensionDescription(), CDataArray::setMode(), and CDataArray::Vector.
Referenced by CSteadyStateTask().
load()
void CSteadyStateTask::load (CReadConfig & configBuffer)
Loads parameters for this solver with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
configbuffer reference to a CReadConfig object.
References CReadConfig::getVariable(), CReadConfig::LOOP, CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CCopasiTask::mScheduled.
Referenced by CDataModel::loadModel().
print()
void CSteadyStateTask::print (std::ostream * ostream) const override virtual
This is the output method for any object. The default implementation provided with CDataObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CDataObject.
process()
bool CSteadyStateTask::process (const bool & useInitialValues) override virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
References COutputInterface::AFTER, CMathContainer::applyInitialValues(), CMatrix< CType >::array(), COutputInterface::BEFORE, C_FLOAT64, C_INT32, CEigen::calcEigenValues(), CSteadyStateMethod::doJacobian(), CMathContainer::getCountFixedEventTargets(), CEigen::getI(), CEigen::getR(), CSteadyStateMethod::getStabilityResolution(), CMathContainer::getState(), CMathContainer::isAutonomous(), CSteadyStateProblem::isJacobianRequested(), CSteadyStateProblem::isStabilityAnalysisRequested(), CMathContainer::isStateValid(), mEigenValues, mEigenvaluesMatrix, mEigenValuesX, mEigenvaluesXMatrix, mJacobian, mJacobianReduced, CCopasiTask::mpContainer, CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiTask::mProcessReport, mResult, mSteadyState, CSteadyStateMethod::notFound, CCopasiTask::output(), CSteadyStateMethod::process(), CMathContainer::pushAllTransientValues(), CMathContainer::setState(), CMatrix< CType >::size(), CVectorCore< CType >::size(), CEigen::stabilityAnalysis(), CMathContainer::updateSimulatedValues(), and CMathContainer::updateTransientDataValues().
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), CLNATask::process(), CMCATask::process(), CTimeSensTask::processStart(), and CTrajectoryTask::processStart().
restore()
bool CSteadyStateTask::restore (const bool & updateModel = true) override virtual
Perform necessary cleanup procedures
Reimplemented from CCopasiTask.
References CMathContainer::getState(), CMathContainer::isStateValid(), CCopasiTask::mInitialState, CCopasiTask::mpContainer, mResult, mSteadyState, CCopasiTask::mUpdateModel, CSteadyStateMethod::notFound, CCore::ParticleNumbers, CMathContainer::pushInitialState(), CCopasiTask::setCallBack(), CMathContainer::setInitialState(), CMathContainer::setState(), CMathContainer::updateInitialValues(), and CMathContainer::updateSimulatedValues().
Referenced by CFitProblem::restore().
updateMatrices()
bool CSteadyStateTask::updateMatrices () override virtual
Resizes result matrices and updates array annotations for a specific task. This is used when we need to know about the data structures of a task result without actually performing the task, e.g. when selecting objects for output. For now we assume that this functionality is also performed when initialize() is called.
Reimplemented from CCopasiTask.
References CVectorCore< CType >::array(), CMathContainer::getCountFixedEventTargets(), CMathObject::getDataObject(), CMathContainer::getMathObject(), CDataObject::getObjectParent(), CMathContainer::getState(), mEigenvaluesMatrix, mEigenvaluesXMatrix, mJacobian, mJacobianReduced, CCopasiTask::mpContainer, mpJacobianAnn, mpJacobianXAnn, CDataArray::resize(), CMatrix< CType >::resize(), CDataArray::setAnnotation(), and CVectorCore< CType >::size().
Referenced by initialize().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CSteadyStateTask & A) friend
Member Data Documentation
mEigenValues
CEigen CSteadyStateTask::mEigenValues private
The Eigenvalues of the Jacobian of the system
Referenced by getEigenValues(), and process().
mEigenvaluesMatrix
CMatrix<C_FLOAT64> CSteadyStateTask::mEigenvaluesMatrix private
The Eigenvalues matrix of the Jacobian of the system
Referenced by initObjects(), process(), and updateMatrices().
mEigenValuesX
CEigen CSteadyStateTask::mEigenValuesX private
The Eigenvalues of the Jacobian of the reduced system
Referenced by getEigenValuesReduced(), and process().
mEigenvaluesXMatrix
CMatrix<C_FLOAT64> CSteadyStateTask::mEigenvaluesXMatrix private
The Eigenvalues matrix of the Jacobian of the reduced system
Referenced by initObjects(), process(), and updateMatrices().
mJacobian
CMatrix< C_FLOAT64 > CSteadyStateTask::mJacobian private
The jacobian of the steady state.
Referenced by getJacobian(), initObjects(), process(), and updateMatrices().
mJacobianReduced
CMatrix< C_FLOAT64 > CSteadyStateTask::mJacobianReduced private
The jacobian of the steady state.
Referenced by getJacobianReduced(), initObjects(), process(), and updateMatrices().
mpEigenvaluesJacobianAnn
CDataArray* CSteadyStateTask::mpEigenvaluesJacobianAnn private
Referenced by initObjects().
mpEigenvaluesJacobianXAnn
CDataArray* CSteadyStateTask::mpEigenvaluesJacobianXAnn private
Referenced by initObjects().
mpJacobianAnn
CDataArray* CSteadyStateTask::mpJacobianAnn private
Referenced by getJacobianAnnotated(), initObjects(), and updateMatrices().
mpJacobianXAnn
CDataArray* CSteadyStateTask::mpJacobianXAnn private
Referenced by getJacobianXAnnotated(), initObjects(), and updateMatrices().
mResult
CSteadyStateMethod::ReturnCode CSteadyStateTask::mResult private
The result of the steady state analysis.
Referenced by getResult(), process(), and restore().
mSteadyState
CVector< C_FLOAT64 > CSteadyStateTask::mSteadyState private
A pointer to the found steady state.
Referenced by getState(), initialize(), process(), and restore().
The documentation for this class was generated from the following files:
CSteadyStateTask.h
CSteadyStateTask.cpp