COPASI API: CCallParameters< Type > Class Template Reference
CCallParameters< Type > Class Template Reference
#include <CCallParameters.h>
Classes
union UType
Public Types
typedef std::vector< UType >::const_iterator const_iterator
Public Member Functions
const_iterator begin () const
CCallParameters (const CCallParameters &src)
CCallParameters (const size_t &size=0)
void clear ()
const_iterator end () const
UType & operator[] (const size_t &index)
const UType & operator[] (const size_t &index) const
void push_back (CCallParameters< Type > *vector)
void push_back (const Type *value)
void resize (const size_t &size)
size_t size () const
~CCallParameters ()
Detailed Description
template<typename Type>
class CCallParameters< Type >
CFunctionParameterMap
Created for Copasi by Stefan Hoops (C) Stefan Hoops 2002 CCallParameterPointers
This is what is actually passed to a function. Some of the void* can be pointers to vector<const CDataObject*>
Member Typedef Documentation
const_iterator
template<typename Type > typedef std::vector< UType >::const_iterator CCallParameters< Type >::const_iterator
Constructor & Destructor Documentation
CCallParameters() [1/2]
template<typename Type > CCallParameters< Type >::CCallParameters (const size_t & size = 0) inline
CCallParameters() [2/2]
template<typename Type > CCallParameters< Type >::CCallParameters (const CCallParameters< Type > & src) inline
~CCallParameters()
template<typename Type > CCallParameters< Type >::~CCallParameters () inline
Member Function Documentation
begin()
template<typename Type > const_iterator CCallParameters< Type >::begin () const inline
Referenced by CEvaluationNodeCall::buildParameters(), CFunction::calcValue(), CMassAction::calcValue(), CMathExpression::CMathExpression(), and CMathExpression::createMassActionPart().
clear()
template<typename Type > void CCallParameters< Type >::clear () inline
Referenced by CFunctionParameterMap::clearCallParameter(), and CFunctionParameterMap::clearCallParameters().
end()
template<typename Type > const_iterator CCallParameters< Type >::end () const inline
Referenced by CMassAction::calcValue(), CMathExpression::CMathExpression(), CMathExpression::createMassActionPart(), and CCallParameters< Type >::resize().
operator[]() [1/2]
template<typename Type > UType& CCallParameters< Type >::operator[] (const size_t & index) inline
operator[]() [2/2]
template<typename Type > const UType& CCallParameters< Type >::operator[] (const size_t & index) const inline
push_back() [1/2]
template<typename Type > void CCallParameters< Type >::push_back (CCallParameters< Type > * vector) inline
push_back() [2/2]
template<typename Type > void CCallParameters< Type >::push_back (const Type * value) inline
Referenced by CFunctionParameterMap::addCallParameter(), and CFunctionParameterMap::getObjects().
resize()
template<typename Type > void CCallParameters< Type >::resize (const size_t & size) inline
References CCallParameters< Type >::end(), and CCallParameters< Type >::size().
Referenced by CFunctionParameterMap::initCallParameters().
size()
template<typename Type > size_t CCallParameters< Type >::size () const inline
Referenced by CFunctionParameterMap::checkCallParameters(), CMathExpression::CMathExpression(), CMathExpression::createMassActionPart(), CFunctionParameterMap::getObjects(), CModel::prepareElasticity(), and CCallParameters< Type >::resize().
The documentation for this class was generated from the following file:
CCallParameters.h