COPASI API: CTableauMatrix Class Reference
CTableauMatrix Class Reference
#include <CTableauMatrix.h>
Public Member Functions
void addLine (const CTableauLine *src, const bool &check=true)
std::list< const CTableauLine * >::iterator begin ()
std::list< const CTableauLine * >::const_iterator begin () const
CTableauMatrix ()
CTableauMatrix (const std::vector< std::vector< double > > &stoi, const size_t &reversibleNumber)
std::list< const CTableauLine * >::iterator end ()
std::list< const CTableauLine * >::const_iterator end () const
void removeLine (const std::list< const CTableauLine * >::iterator line)
size_t size () const
~CTableauMatrix ()
Private Member Functions
bool isValid (const CTableauLine *src)
Private Attributes
std::list< const CTableauLine * >::iterator mFirstIrreversible
std::list< const CTableauLine * > mLine
Friends
std::ostream & operator<< (std::ostream &, const CTableauMatrix &)
Detailed Description
CTableauMatrix class. Used to calculate elementary flux modes
Created for Copasi by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Constructor & Destructor Documentation
CTableauMatrix() [1/2]
CTableauMatrix::CTableauMatrix ()
Default constructor
CTableauMatrix class. Used to calculate elementary flux modes
Created for Copasi by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
CTableauMatrix() [2/2]
CTableauMatrix::CTableauMatrix (const std::vector< std::vector< double > > & stoi, const size_t & reversibleNumber)
Specific constructor The first reversibleNumber lines of stoi must be reversible reactions. Note: stoi is actually the transpose of the stoichiometry matrix
Parameters
const std::vector < std::vector < double > > & stoi
const size_t & reversibleNumber
~CTableauMatrix()
CTableauMatrix::~CTableauMatrix ()
Destructor
References mLine, and pdelete.
Member Function Documentation
addLine()
void CTableauMatrix::addLine (const CTableauLine * src, const bool & check = true)
Add a line to the matrix
Parameters
const CTableauLine * src
const bool & check (Default: true)
References CTableauLine::isReversible(), isValid(), mFirstIrreversible, mLine, and pdelete.
Referenced by CEFMAlgorithm::calculateNextTableau().
begin() [1/2]
std::list< const CTableauLine * >::iterator CTableauMatrix::begin ()
Retrieves the first line from the matrix
Returns
list< const CTableauLine * >::iterator begin
References mLine.
Referenced by CEFMAlgorithm::buildFluxModes(), CEFMAlgorithm::calculateCombinations(), CEFMAlgorithm::calculateNextTableau(), and CEFMAlgorithm::CSpeciesOrderNode::update().
begin() [2/2]
std::list< const CTableauLine * >::const_iterator CTableauMatrix::begin () const
Retrieves the first line from the matrix
Returns
list< const CTableauLine * >::const_iterator begin
References mLine.
end() [1/2]
std::list< const CTableauLine * >::iterator CTableauMatrix::end ()
Retrieves the last line from the matrix
Returns
list< const CTableauLine * >::iterator end
References mLine.
Referenced by CEFMAlgorithm::buildFluxModes(), CEFMAlgorithm::calculateCombinations(), CEFMAlgorithm::calculateNextTableau(), and CEFMAlgorithm::CSpeciesOrderNode::update().
end() [2/2]
std::list< const CTableauLine * >::const_iterator CTableauMatrix::end () const
Retrieves the last line from the matrix
Returns
list< const CTableauLine * >::const_iterator end
References mLine.
isValid()
bool CTableauMatrix::isValid (const CTableauLine * src) private
Check whether the new line fullfills the constraints
Parameters
const CTableauLine * src
References CTableauLine::getScore(), mLine, and removeLine().
Referenced by addLine().
removeLine()
void CTableauMatrix::removeLine (const std::list< const CTableauLine * >::iterator line)
Remove the indexed line of the matrix
Parameters
list< const CTableauLine * >::const_iterator line
References mFirstIrreversible, and mLine.
Referenced by CEFMAlgorithm::calculateNextTableau(), and isValid().
size()
size_t CTableauMatrix::size () const
Retrieve the number of tableau lines
Returns
size_t size
References mLine.
Referenced by CEFMAlgorithm::calculateNextTableau().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CTableauMatrix & m) friend
Member Data Documentation
mFirstIrreversible
std::list< const CTableauLine * >::iterator CTableauMatrix::mFirstIrreversible private
Iterator pointing to the first irreversible reaction
Referenced by addLine(), and removeLine().
mLine
std::list< const CTableauLine * > CTableauMatrix::mLine private
Vector containing the lines of the Matrix @associates <{CTableauLine}> @supplierCardinality 0..*
Referenced by addLine(), begin(), end(), isValid(), removeLine(), size(), and ~CTableauMatrix().
The documentation for this class was generated from the following files:
CTableauMatrix.h
CTableauMatrix.cpp