COPASI API: CMetab Class Reference
CMetab Class Reference
#include <CMetab.h>
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculate () override
void cleanup ()
CMetab (const CMetab &src, const CDataContainer *pParent)
CMetab (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
virtual CIssue compile () override
void compileIsInitialValueChangeAllowed ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const override
const CCompartment * getCompartment () const
const C_FLOAT64 & getConcentration () const
C_FLOAT64 getConcentrationRate () const
CDataObject * getConcentrationRateReference () const
CDataObject * getConcentrationReference () const
size_t getCountOfDependentReactions () const
const C_FLOAT64 & getInitialConcentration () const
CDataObject * getInitialConcentrationReference () const
CDataObject * getIntensiveNoiseReference () const
const CMoiety * getMoiety () const
virtual std::string getObjectDisplayName () const override
const C_FLOAT64 & getTransitionTime () const
CDataObject * getTransitionTimeReference () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual void * getValuePointer () const override
void initCompartment (const CCompartment *pCompartment=NULL)
bool isDependent () const
const bool & isInitialValueChangeAllowed (CCore::Framework framework) const
C_INT32 load (CReadConfig &configbuffer)
CMetab & operator= (const CMetabOld &rhs)
bool setCompartment (const std::string &compName)
void setConcentration (const C_FLOAT64 concentration)
void setDependsOnMoiety (const CMoiety *pMoiety)
void setInitialConcentration (const C_FLOAT64 &initialConcentration)
virtual bool setObjectParent (const CDataContainer *pParent) override
void setTransitionTime (const C_FLOAT64 &transitionTime)
virtual CData toData () const override
~CMetab ()
Public Member Functions inherited from CModelEntity
CModelEntity (const CModelEntity &src, const CDataContainer *pParent)
CModelEntity (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const std::string &type="ModelEntity", const CFlags< Flag > &flag=CFlags< Flag >::None)
std::string getDefaultNoiseExpression () const
std::string getExpression () const
CExpression * getExpressionPtr ()
const CExpression * getExpressionPtr () const
std::string getInitialExpression () const
CExpression * getInitialExpressionPtr ()
const CExpression * getInitialExpressionPtr () const
const C_FLOAT64 & getInitialValue () const
CDataObject * getInitialValueReference () const
virtual const std::string & getKey () const override
CModel * getModel () const
std::string getNoiseExpression () const
CExpression * getNoiseExpressionPtr ()
const CExpression * getNoiseExpressionPtr () const
CDataObject * getNoiseReference () const
const C_FLOAT64 & getRate () const
CDataObject * getRateReference () const
const std::string & getSBMLId () const
const CModelEntity::Status & getStatus () const
virtual const std::string & getUnitExpression () const
const C_FLOAT64 & getValue () const
CDataObject * getValueReference () const
const bool & hasNoise () const
bool isFixed () const
const bool & isUsed () const
CIssue setExpression (const std::string &expression)
bool setExpressionPtr (CExpression *pExpression)
void setHasNoise (const bool &hasNoise)
CIssue setInitialExpression (const std::string &expression)
bool setInitialExpressionPtr (CExpression *pExpression)
virtual void setInitialValue (const C_FLOAT64 &initialValue)
bool setNoiseExpression (const std::string &expression)
bool setNoiseExpressionPtr (CExpression *pExpression)
void setRate (const C_FLOAT64 &rate)
void setSBMLId (const std::string &id) const
bool setStatus (const CModelEntity::Status &status)
virtual CIssue setUnitExpression (std::string unitExpression)
void setUsed (const bool &used)
virtual void setValue (const C_FLOAT64 &value)
~CModelEntity ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static C_FLOAT64 convertToConcentration (const C_FLOAT64 &number, const CCompartment &compartment)
static C_FLOAT64 convertToNumber (const C_FLOAT64 &concentration, const CCompartment &compartment)
static CMetab * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CModelEntity
static CModelEntity * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Protected Member Functions
CMetab (const CMetab &src)
Protected Member Functions inherited from CModelEntity
CModelEntity (const CModelEntity &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
CDataObjectReference< C_FLOAT64 > * mpConcRateReference
CDataObjectReference< C_FLOAT64 > * mpConcReference
CDataObjectReference< C_FLOAT64 > * mpIConcReference
CDataObjectReference< C_FLOAT64 > * mpIntensiveNoiseReference
CDataObjectReference< C_FLOAT64 > * mpTTReference
Protected Attributes inherited from CModelEntity
bool mHasNoise
C_FLOAT64 mIValue
C_FLOAT64 mNoise
CExpression * mpExpression
CExpression * mpInitialExpression
CDataObjectReference< C_FLOAT64 > * mpIValueReference
CModel * mpModel
CExpression * mpNoiseExpression
CDataObjectReference< C_FLOAT64 > * mpNoiseReference
CDataObjectReference< C_FLOAT64 > * mpRateReference
CDataObjectReference< C_FLOAT64 > * mpValueReference
C_FLOAT64 mRate
std::string mSBMLId
std::string mUnitExpression
C_FLOAT64 mValue
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Protected Attributes inherited from CAnnotation
std::string mKey
Private Member Functions
void initObjects ()
Private Attributes
C_FLOAT64 mConc
C_FLOAT64 mConcRate
C_FLOAT64 mIConc
C_FLOAT64 mIntensiveNoise
bool mIsInitialConcentrationChangeAllowed
bool mIsInitialParticleNumberChangeAllowed
const CCompartment * mpCompartment
const CMoiety * mpMoiety
C_FLOAT64 mTT
Friends
void CMoiety::add (C_FLOAT64 value, CMetab *pMetabolite)
std::ostream & operator<< (std::ostream &os, const CMetab &d)
Additional Inherited Members
Public Types inherited from CModelEntity
enum class Status {
FIXED = 0 , ASSIGNMENT , REACTIONS , ODE ,
TIME , __SIZE
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Static Public Attributes inherited from CModelEntity
static const CEnumAnnotation< std::string, Status > StatusName
static const CEnumAnnotation< std::string, Status > XMLStatus
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Constructor & Destructor Documentation
CMetab() [1/3]
CMetab::CMetab (const CMetab & src) protected
Referenced by fromData().
CMetab() [2/3]
CMetab::CMetab (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CDataContainer * pParent (default: NULL)
References CONSTRUCTOR_TRACE, CDataObject::getObjectParent(), initCompartment(), initObjects(), CModelEntity::REACTIONS, setConcentration(), setInitialConcentration(), and CModelEntity::setStatus().
CMetab() [3/3]
CMetab::CMetab (const CMetab & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CMetab & src
const CDataContainer * pParent (default: NULL)
References CONSTRUCTOR_TRACE, initCompartment(), initObjects(), and mpCompartment.
~CMetab()
CMetab::~CMetab ()
Destructor.
References DESTRUCTOR_TRACE, CRootContainer::getKeyFactory(), CAnnotation::mKey, and CKeyFactory::remove().
Member Function Documentation
applyData()
bool CMetab::applyData (const CData & data, CUndoData::CChangeSet & changes) override virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CModelEntity.
References CModelEntity::applyData(), CData::getProperty(), CData::INITIAL_INTENSIVE_VALUE, CData::isSetProperty(), mIConc, and CDataValue::toDouble().
calculate()
void CMetab::calculate (void) override virtual
Calculate the value or the rate depending whether we have an ASIGNMENT or ODE
Reimplemented from CModelEntity.
References CModelEntity::ASSIGNMENT, CExpression::calcValue(), CModelEntity::FIXED, CMoiety::getDependentNumber(), CModel::getQuantity2NumberFactor(), CModelEntity::getStatus(), CModelEntity::getValue(), isDependent(), mConc, mpCompartment, CModelEntity::mpExpression, CModelEntity::mpModel, mpMoiety, CModelEntity::mRate, CModelEntity::mValue, CModelEntity::ODE, and CModelEntity::REACTIONS.
cleanup()
void CMetab::cleanup ()
Cleanup
compile()
CIssue CMetab::compile () override virtual
Compile the model value.
Returns
CIssue firstWorstIssue
Reimplemented from CModelEntity.
References CDataContainer::add(), CValidity::add(), CModelEntity::ASSIGNMENT, CExpression::calcValue(), CValidity::clear(), CExpression::compile(), convertToNumber(), CExpression::createInitialExpression(), CIssue::ExpressionEmpty, CModelEntity::FIXED, CModelEntity::getExpression(), CValidity::getFirstWorstIssue(), CEvaluationTree::getInfix(), CModelEntity::getNoiseExpression(), CDataObject::getObjectAncestor(), CDataObject::getObjectDataModel(), CDataObject::getPrerequisites(), CModelEntity::getStatus(), CDataObject::getValidity(), initCompartment(), mConcRate, CModelEntity::mHasNoise, mIConc, mIntensiveNoise, CModelEntity::mIValue, mpCompartment, CModelEntity::mpExpression, CModelEntity::mpInitialExpression, CModelEntity::mpNoiseExpression, CDataObject::mPrerequisits, CModelEntity::mRate, mTT, CObjectInterface::mValidity, CModelEntity::ODE, pdelete, CModelEntity::REACTIONS, CDataObject::setObjectName(), and CIssue::Warning.
compileIsInitialValueChangeAllowed()
void CMetab::compileIsInitialValueChangeAllowed ()
Determine whether changing the initial concentration is allowed
References CDataObject::Container, CModel::getMathContainer(), mIsInitialConcentrationChangeAllowed, mIsInitialParticleNumberChangeAllowed, mpCompartment, mpIConcReference, CModelEntity::mpIValueReference, and CModelEntity::mpModel.
convertToConcentration()
C_FLOAT64 CMetab::convertToConcentration (const C_FLOAT64 & number, const CCompartment & compartment) static
Converts the number to concentration
Parameters
const C_FLOAT64 & number
const CCompartment & compartment
const CModel & model
Returns
C_FLOAT64 concentration
References CModelEntity::getInitialValue(), CModelEntity::getModel(), and CModel::getNumber2QuantityFactor().
convertToNumber()
C_FLOAT64 CMetab::convertToNumber (const C_FLOAT64 & concentration, const CCompartment & compartment) static
Converts the concentration to number
Parameters
const C_FLOAT64 & concentration
const CCompartment & compartment
const CModel & model
Returns
C_FLOAT64 number
References CModelEntity::getInitialValue(), CModelEntity::getModel(), and CModel::getQuantity2NumberFactor().
Referenced by compile(), and operator=().
createUndoData()
void CMetab::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const override virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CModelEntity.
References CUndoData::addProperty(), CUndoData::CHANGE, CModelEntity::createUndoData(), CData::getProperty(), CData::INITIAL_INTENSIVE_VALUE, CUndoData::isChangedProperty(), mIConc, and CData::OBJECT_PARENT_CN.
fromData()
CMetab * CMetab::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CMetab * pDataObject
References CMetab(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getChildObjectUnits()
std::string CMetab::getChildObjectUnits (const CDataObject * pObject) const override virtual
Retrieve the units of the child object.
Returns
const & CUnit units
Reimplemented from CModelEntity.
References CModelEntity::getChildObjectUnits(), CModelEntity::getInitialValueReference(), CModel::getQuantityUnit(), CModel::getTimeUnit(), CDataObject::getUnits(), mpCompartment, mpConcRateReference, mpConcReference, mpIConcReference, CModelEntity::mpModel, and mpTTReference.
Referenced by CModelParameter::getUnit().
getCompartment()
const CCompartment * CMetab::getCompartment () const
References mpCompartment.
Referenced by CSBMLExporter::addInitialAssignmentsToModel(), CModelAdd::addMetabolites(), CChemEqInterface::addModifier(), addParticleNumberToInitialValueMap(), CMathObject::compile(), CTimeSeries::compile(), CMathEvent::CAssignment::compile(), CChemEqInterface::completeCompartments(), SEDMLUtils::createAmountMV(), CMathObject::createExtensiveValueExpression(), CSBMLExporter::createInitialAssignment(), CMathObject::createIntensiveRateExpression(), CCopasiSpringLayout::createLayout(), CModelExpansion::createLinearArray(), CSBMLExporter::createMetabolite(), CModelExpansion::createRectangularArray(), CSBMLExporter::createRule(), CMetabNameInterface::createUniqueDisplayName(), CCSPMethod::cspstep(), CMetabNameInterface::doesExist(), CModelExpansion::duplicateMetab(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportMetabolites(), CODEExporter::exportModelEntityExpression(), CChemEqInterface::getCompartment(), CMathContainer::getCompartment(), CMetabNameInterface::getDisplayName(), SBMLImporter::importEvent(), SBMLImporter::importInitialAssignments(), CChemEqInterface::init(), CCopasiSpringLayout::initFromLayout(), CMathContainer::initializeAtolVector(), CModel::initializeAtolVector(), MetaboliteHandler::processStart(), CCopasiSpringLayout::randomize(), CModelExpansion::replaceInMetab(), CSBMLExporter::replaceSpeciesReferences(), CCopasiXML::saveModel(), setCompartment(), and CReaction::setScalingFactor().
getConcentration()
const C_FLOAT64 & CMetab::getConcentration () const
References mConc.
getConcentrationRate()
C_FLOAT64 CMetab::getConcentrationRate () const
Return rate of production of this metaboLite
References mConcRate.
getConcentrationRateReference()
CDataObject * CMetab::getConcentrationRateReference () const
Retrieve object referencing the concentration
Returns
CDataObject * concentrationRateReference
References mpConcRateReference.
Referenced by CDataModel::findObjectByDisplayName(), CMathContainer::initializeMathObjects(), and SEDMLUtils::resolveVariable().
getConcentrationReference()
CDataObject * CMetab::getConcentrationReference () const
Retrieve object referencing the concentration
Returns
CConcentrationReference * concentrationReference
References mpConcReference.
Referenced by CMathObject::compileValue(), SEDMLUtils::createAmountMV(), CMathObject::createExtensiveValueExpression(), CExpression::createInitialExpression(), CMathObject::createIntensiveRateExpression(), CDataModel::findObjectByDisplayName(), CModel::getCorrespondingTransientObject(), CReactionInterface::getUnit(), CReactionInterface::getUnitVector(), CMathContainer::initializeMathObjects(), CModel::prepareElasticity(), CSBMLExporter::replaceSpeciesReferences(), SEDMLUtils::resolveVariable(), and VariableInfo::VariableInfo().
getCountOfDependentReactions()
size_t CMetab::getCountOfDependentReactions () const
Retrieve the count of structural dependent reactions
Returns
const size_t countOfDependentReactions
References CModel::appendDirectDependents(), and CModelEntity::mpModel.
getInitialConcentration()
const C_FLOAT64 & CMetab::getInitialConcentration () const
References mIConc.
Referenced by CModelAdd::addMetabolites(), CSBMLExporter::createMetabolite(), CModelExpansion::duplicateMetab(), CODEExporter::exportExpression(), and CODEExporter::exportMetabolites().
getInitialConcentrationReference()
CDataObject * CMetab::getInitialConcentrationReference () const
Retrieve object referencing the initial concentration
Returns
CConcentrationReference * initialConcentrationReference
References mpIConcReference.
Referenced by CMathObject::compileInitialValue(), CMathObject::createExtensiveValueExpression(), CExpression::createInitialExpression(), CDataModel::findObjectByDisplayName(), CModel::getCorrespondingTransientObject(), getInitialCNForSBase(), CModelParameter::getUnit(), CMathContainer::initializeMathObjects(), and CModelParameterSet::saveToStream().
getIntensiveNoiseReference()
CDataObject * CMetab::getIntensiveNoiseReference () const
Retrieve object referencing the concentration
Returns
CDataObject * concentrationRateReference
References mpIntensiveNoiseReference.
Referenced by CMathContainer::initializeMathObjects().
getMoiety()
const CMoiety * CMetab::getMoiety () const
Retrieve a pointer to the moiety the species depends on
Returns
const CMoiety * pMoiety;
References mpMoiety.
Referenced by CMathObject::compileValue().
getObjectDisplayName()
std::string CMetab::getObjectDisplayName () const override virtual
Retrieve the display name of the object
Parameters
bool regular (default: true)
bool richtext (default: false)
Returns
std::string objectDisplayName
Reimplemented from CDataObject.
References CMetabNameInterface::getDisplayName(), CDataObject::getObjectAncestor(), and CDataObject::getObjectDisplayName().
Referenced by CReaction::createFunctionFromExpression(), CSBMLExporter::createMetabolite(), and CDataModel::findObjectByDisplayName().
getTransitionTime()
const C_FLOAT64 & CMetab::getTransitionTime () const
Retrieves the transition time
Returns
"const C_FLOAT64 &" transitionTime
References mTT.
getTransitionTimeReference()
CDataObject * CMetab::getTransitionTimeReference () const
Retrieve object referencing the Transition Time
Returns
CDataObject * transitionTimeReference
References mpTTReference.
Referenced by CModel::appendAllDependents(), and CMathContainer::initializeMathObjects().
getUnits()
const std::string CMetab::getUnits () const override virtual
Retrieve the units of the object.
Returns
std::string units
Reimplemented from CDataContainer.
getValueObject()
const CDataObject * CMetab::getValueObject () const override virtual
Retrieve the object representing the value;
Reimplemented from CModelEntity.
References mpConcReference.
getValuePointer()
void * CMetab::getValuePointer () const override virtual
Retrieve a pointer to the value;
Reimplemented from CModelEntity.
References C_FLOAT64, and mConc.
initCompartment()
void CMetab::initCompartment (const CCompartment * pCompartment = NULL)
References CDataObject::getObjectAncestor(), mpCompartment, and CDataObject::mPrerequisits.
Referenced by CMetab(), compile(), and setObjectParent().
initObjects()
void CMetab::initObjects () private
Initialize the contained CDataObjects
References CDataContainer::addObjectReference(), mConc, mConcRate, mIConc, mIntensiveNoise, mpConcRateReference, mpConcReference, mpIConcReference, mpIntensiveNoiseReference, CModelEntity::mpIValueReference, CModelEntity::mpRateReference, mpTTReference, CModelEntity::mpValueReference, mTT, CDataObject::setObjectName(), and CDataObject::ValueDbl.
Referenced by CMetab().
isDependent()
bool CMetab::isDependent () const
Retrieve whether the metabolite dependent
Returns
bool dependent
References mpMoiety.
Referenced by calculate(), CODEExporter::exportExpression(), CODEExporter::exportMetabolites(), CODEExporter::exportODEs(), CODEExporterBM::exportSingleMetabolite(), CODEExporterC::exportSingleMetabolite(), CODEExporterXPPAUT::exportSingleMetabolite(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CODEExporter::preprocess(), CODEExporterC::preprocess(), and CStateTemplate::reorder().
isInitialValueChangeAllowed()
const bool & CMetab::isInitialValueChangeAllowed (CCore::Framework framework) const
Check whether changing the initial concentration is allowed
Returns
const bool & allowed
References CCore::Concentration, mIsInitialConcentrationChangeAllowed, and mIsInitialParticleNumberChangeAllowed.
load()
C_INT32 CMetab::load (CReadConfig & configbuffer)
Loads an object with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
pconfigbuffer reference to a CReadConfig object.
Returns
Fail
References C_INT32, CDataObject::getObjectName(), CReadConfig::getVariable(), METAB_MOIETY, mIConc, CModelEntity::REACTIONS, CReadConfig::SEARCH, setConcentration(), setInitialConcentration(), CDataObject::setObjectName(), CModelEntity::setStatus(), and CCopasiMessage::WARNING.
operator=()
CMetab & CMetab::operator= (const CMetabOld & rhs)
Assignment operator.
References C_FLOAT64, convertToNumber(), CDataObject::getObjectName(), mConcRate, CMetabOld::mIConc, mpCompartment, CModelEntity::mRate, CMetabOld::mStatus, mTT, CModelEntity::setInitialValue(), CDataObject::setObjectName(), and CModelEntity::setStatus().
setCompartment()
bool CMetab::setCompartment (const std::string & compName)
moves the species to the compartment with the given name, removes it from the old compartment (if there was one), and updates references to the species if needed
References CCompartment::addMetabolite(), CDataObject::getCN(), getCompartment(), CModel::getCompartments(), CCompartment::getMetabolites(), CDataObject::getObjectName(), CRegisteredCommonName::handle(), CModel::initializeMetabolites(), CRegisteredCommonName::isEnabled(), CModelEntity::mpModel, CDataVectorN< CType >::remove(), CModel::setCompileFlag(), and CRegisteredCommonName::setEnabled().
setConcentration()
void CMetab::setConcentration (const C_FLOAT64 concentration)
References CModelEntity::isFixed(), and mConc.
Referenced by CMetab(), and load().
setDependsOnMoiety()
void CMetab::setDependsOnMoiety (const CMoiety * pMoiety)
Set whether the metabolite is dependent, i.e., calculated by a moiety
Parameters
const CMoiety * pMoiety
References mpMoiety.
Referenced by CMoiety::add().
setInitialConcentration()
void CMetab::setInitialConcentration (const C_FLOAT64 & initialConcentration)
References mIConc.
Referenced by CMetab(), CModel::createMetabolite(), CReactionInterface::createUndoData(), load(), and CModelParameterSpecies::updateModel().
setObjectParent()
bool CMetab::setObjectParent (const CDataContainer * pParent) override virtual
Sets the parent of the metabolite;
Parameters
const CDataContainer * pParent
Returns
bool success
Reimplemented from CModelEntity.
References CModelEntity::FIXED, CModelEntity::getExpression(), CModelEntity::getStatus(), initCompartment(), CModelEntity::REACTIONS, CModelEntity::setExpression(), CModelEntity::setObjectParent(), and CModelEntity::setStatus().
setTransitionTime()
void CMetab::setTransitionTime (const C_FLOAT64 & transitionTime)
Set transition time
Parameters
const C_FLOAT64 & transitionTime
References mTT.
toData()
CData CMetab::toData () const override virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CModelEntity.
References CData::addProperty(), CData::INITIAL_INTENSIVE_VALUE, mIConc, and CModelEntity::toData().
Friends And Related Function Documentation
CMoiety::add
void CMoiety::add (C_FLOAT64 value, CMetab * pMetabolite) friend
operator<<
std::ostream& operator<< (std::ostream & os, const CMetab & d) friend
ostream operator
Member Data Documentation
mConc
C_FLOAT64 CMetab::mConc private
Concentration of the metabolite as double.
Referenced by calculate(), getConcentration(), getValuePointer(), initObjects(), and setConcentration().
mConcRate
C_FLOAT64 CMetab::mConcRate private
The rate of concentration change
Referenced by compile(), getConcentrationRate(), initObjects(), and operator=().
mIConc
C_FLOAT64 CMetab::mIConc private
Initial concentration of the metabolite as double
Referenced by applyData(), compile(), createUndoData(), getInitialConcentration(), initObjects(), load(), setInitialConcentration(), and toData().
mIntensiveNoise
C_FLOAT64 CMetab::mIntensiveNoise private
The intensive noise
Referenced by compile(), and initObjects().
mIsInitialConcentrationChangeAllowed
bool CMetab::mIsInitialConcentrationChangeAllowed private
Referenced by compileIsInitialValueChangeAllowed(), and isInitialValueChangeAllowed().
mIsInitialParticleNumberChangeAllowed
bool CMetab::mIsInitialParticleNumberChangeAllowed private
Referenced by compileIsInitialValueChangeAllowed(), and isInitialValueChangeAllowed().
mpCompartment
const CCompartment* CMetab::mpCompartment private
pointer to the compartment the metabolite is located in. The metab needs to know about volumes.
Referenced by calculate(), CMetab(), compile(), compileIsInitialValueChangeAllowed(), getChildObjectUnits(), getCompartment(), initCompartment(), and operator=().
mpConcRateReference
CDataObjectReference< C_FLOAT64 >* CMetab::mpConcRateReference protected
Referenced by getChildObjectUnits(), getConcentrationRateReference(), and initObjects().
mpConcReference
CDataObjectReference< C_FLOAT64 >* CMetab::mpConcReference protected
Referenced by getChildObjectUnits(), getConcentrationReference(), getValueObject(), and initObjects().
mpIConcReference
CDataObjectReference< C_FLOAT64 >* CMetab::mpIConcReference protected
Referenced by compileIsInitialValueChangeAllowed(), getChildObjectUnits(), getInitialConcentrationReference(), and initObjects().
mpIntensiveNoiseReference
CDataObjectReference< C_FLOAT64 >* CMetab::mpIntensiveNoiseReference protected
Referenced by getIntensiveNoiseReference(), and initObjects().
mpMoiety
const CMoiety* CMetab::mpMoiety private
If dependent the moiety the metabolite is calculated from
Referenced by calculate(), getMoiety(), isDependent(), and setDependsOnMoiety().
mpTTReference
CDataObjectReference< C_FLOAT64 >* CMetab::mpTTReference protected
Referenced by getChildObjectUnits(), getTransitionTimeReference(), and initObjects().
mTT
C_FLOAT64 CMetab::mTT private
Transition time of the metabolite
Referenced by compile(), getTransitionTime(), initObjects(), operator=(), and setTransitionTime().
The documentation for this class was generated from the following files:
CMetab.h
CMetab.cpp