COPASI API: CObjectInterface Class Reference
CObjectInterface Class Reference abstract
#include <CObjectInterface.h>
Public Types
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
virtual void calculateValue ()=0
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual CCommonName getCN () const =0
virtual const CDataObject * getDataObject () const =0
virtual const CObjectInterface * getObject (const CCommonName &cn) const =0
virtual std::string getObjectDisplayName () const =0
virtual const CObjectInterface::ObjectSet & getPrerequisites () const =0
virtual const CValidity & getValidity () const =0
virtual void * getValuePointer () const =0
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const =0
virtual void print (std::ostream *ostream) const =0
virtual void validityChanged (const CValidity &changedValidity)=0
virtual ~CObjectInterface ()
Static Public Member Functions
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Protected Attributes
CValidity mValidity
Member Typedef Documentation
ContainerList
typedef std::vector< const CDataContainer * > CObjectInterface::ContainerList
ObjectSet
typedef std::set< const CObjectInterface * > CObjectInterface::ObjectSet
Constructor & Destructor Documentation
CObjectInterface() [1/2]
CObjectInterface::CObjectInterface ()
Constructor
CObjectInterface() [2/2]
CObjectInterface::CObjectInterface (const CObjectInterface & src)
Copy Constructor
~CObjectInterface()
CObjectInterface::~CObjectInterface () virtual
Destructor
Member Function Documentation
calculateValue()
virtual void CObjectInterface::calculateValue () pure virtual
Calculate the objects value.
Implemented in COptProblem, COptItem, CMathObject, CCopasiTimer, and CDataObject.
Referenced by CMathContainer::applyUpdateSequence().
DataObject()
const CDataObject * CObjectInterface::DataObject (const CObjectInterface * pInterface) static
References getDataObject().
Referenced by CCopasiParameterGroup::applyData(), CSBMLExporter::checkForUnsupportedObjectReferences(), CModelParameter::compile(), CModelParameterReactionParameter::compile(), CEvaluationNodeObject::compile(), CEventAssignment::compile(), CTimeSeries::compile(), COptItem::compile(), CExperimentObjectMap::compile(), CSlider::compile(), CReaction::compileFunctionParameters(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CMathContainer::copyBranch(), CDataArray::createDisplayName(), CDerive::deriveBranch(), SBMLImporter::doMapping(), CModelExpansion::duplicateEvent(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportExpression(), CSEDMLExporter::exportPlotItem(), CSEDMLExporter::exportReport(), CSBMLExporter::findModelEntityDependencies(), CExperimentObjectMap::CDataColumn::getDefaultScale(), CMathDependencyGraph::getDOTNodeId(), CModelExpansion::ElementsMap::getDuplicateFromCN(), CEvaluationNodeObject::getMMLString(), COptItem::getObjectDisplayName(), COptItem::getStartValue(), CSensItem::getVariablesPointerList(), CSBMLExporter::hasVolumeAssignment(), SBMLImporter::isConstantFlux(), CSBMLExporter::isEventSBMLCompatible(), SBMLImporter::isMassActionExpression(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CSlider::isValid(), CEvaluationNodeObject::mapObject(), CReportDefinition::preCompileTable(), CTimeSensMethod::printUpdateSeq(), SBMLImporter::renameMassActionParameters(), CSBMLExporter::replace_local_parameters(), CSBMLExporter::replaceSpeciesReferences(), CReaction::resolveCN(), CSBMLExporter::restore_local_parameters(), SBMLImporter::setCorrectUsage(), SBMLImporter::setInitialValues(), COptItem::setObjectCN(), CReaction::setParameterCNs(), CEvaluationNodeObject::toAST(), CModelParameter::updateModel(), CArrayElementReference::updateObjectName(), and CReaction::variable2object().
getCN()
virtual CCommonName CObjectInterface::getCN () const pure virtual
Retrieve the CN of the object
Returns
CCommonName
Implemented in CCopasiParameter, CMathObject, CDataObject, CArrayElementReference, CModelParameterSet, and CMathContainer.
Referenced by CEvaluationNodeObject::compile(), COutputAssistant::createDefaultOutput(), and CModel::createEventsForTimeseries().
getDataObject()
virtual const CDataObject* CObjectInterface::getDataObject () const pure virtual
Retrieve a pointer to the data object
Returns
const CDataObject * dataObject
Implemented in CMathObject, and CDataObject.
Referenced by CModel::createEventsForTimeseries(), CMathContainer::createNodeFromObject(), DataObject(), CEvaluationNodeObject::getUnit(), CScanMethod::init(), and CMathContainer::relocateObject().
getObject()
virtual const CObjectInterface* CObjectInterface::getObject (const CCommonName & cn) const pure virtual
Retrieve a descendant object by its CN.
Parameters
const CCommonName & cn
Returns
const CObjectInterface * pObject
Implemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, CMathObject, CDataObject, CDataContainer, CCopasiParameterGroup, CReaction, CMathContainer, and CDataArray.
Referenced by CScanItem::CScanItem(), CMathDependencyGraph::exportDOTFormat(), CExpression::getNodeObject(), CDataContainer::getObject(), and GetObjectFromCN().
getObjectDisplayName()
virtual std::string CObjectInterface::getObjectDisplayName () const pure virtual
Retrieve the display name of the object
Parameters
bool regular (default: true)
bool richtext (default: false)
Returns
std::string objectDisplayName
Implemented in CCopasiParameter, COptItem, CMetab, CMathObject, CDataObjectReference< CType >, CDataObjectReference< C_FLOAT64 >, CDataObjectReference< std::string >, CDataObject, CArrayElementReference, CFittingPoint, CReaction, CEvent, CCopasiReportSeparator, CDataString, and CDataArray.
Referenced by CFitProblem::calculateStatistics(), COptItem::checkIsInitialValue(), COptItem::compile(), CMathDependencyGraph::getDOTNodeId(), COptItem::getObjectDisplayName(), and CSensItem::getSingleObjectDisplayName().
GetObjectFromCN()
CObjectInterface * CObjectInterface::GetObjectFromCN (const ContainerList & listOfContainer, const CCommonName & objName) static
References getObject(), CDataContainer::getObject(), CDataObject::getObjectDataModel(), CCommonName::getObjectType(), CCommonName::getPrimary(), CCommonName::getRemainder(), and CRootContainer::getRoot().
Referenced by ResultData::applyToModelStateFromOptTask(), CModelParameter::compile(), CModelParameterReactionParameter::compile(), COptItem::compile(), CSlider::compile(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CDataHandler::generateObjectsFromName(), CReport::generateObjectsFromName(), CExperimentObjectMap::CDataColumn::getDefaultScale(), CObjectLists::getEventTargets(), CExpression::getNodeObject(), CMathContainer::getObject(), CDataObject::getObjectFromCN(), CMathContainer::getObjectFromCN(), COptProblem::getSubTask(), CFitProblem::initialize(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CReportDefinition::preCompileTable(), CReaction::setScalingCompartmentCN(), and CReaction::setScalingFactor().
getPrerequisites()
virtual const CObjectInterface::ObjectSet& CObjectInterface::getPrerequisites () const pure virtual
Retrieve the prerequisites, i.e., the objects which need to be evaluated before this.
Returns
const CObjectInterface::ObjectSet & prerequisites
Implemented in CMathObject, CMathExpression, and CDataObject.
Referenced by CMathDependencyGraph::addObject(), and COptProblem::initialize().
getValidity()
virtual const CValidity& CObjectInterface::getValidity () const pure virtual
Get the aggregation of any issues associated with this object
Returns
const CValidity & validity
Implemented in CMathObject, and CDataObject.
getValuePointer()
virtual void* CObjectInterface::getValuePointer () const pure virtual
Retrieve a pointer to the value of the object
Implemented in CCopasiParameter, COptProblem, COptItem, CModelEntity, CMetab, CMathObject, CCopasiTimer, CDataMatrixReference< CType >, CDataVectorReference< CType >, CDataObjectReference< CType >, CDataObjectReference< C_FLOAT64 >, CDataObjectReference< std::string >, CDataObject, and CArrayElementReference.
Referenced by COptProblem::adjustStartValue(), ResultData::applyToModelStateFromOptTask(), CEvaluationNodeObject::compile(), CMathObject::compile(), COptItem::compile(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CMathContainer::createNodeFromObject(), CScanItem::CScanItem(), getValue(), CFitProblem::initialize(), and CEvaluationNodeObject::mapObject().
isPrerequisiteForContext()
virtual bool CObjectInterface::isPrerequisiteForContext (const CObjectInterface * pObject, const CCore::SimulationContextFlag & context, const CObjectInterface::ObjectSet & changedObjects) const pure virtual
Check whether a given object is a prerequisite for a context.
Parameters
const CObjectInterface * pObject
const CMath::SimulationContextFlag & context
const CObjectInterface::ObjectSet & changedObjects
Returns
bool isPrerequisiteForContext
Implemented in CMathObject, CDataObject, CDependentNumberReference, and CTotalNumberReference.
Referenced by CMathDependencyNode::updateCalculatedState(), CMathDependencyNode::updateDependentState(), CMathDependencyNode::updateIgnoredState(), and CMathDependencyNode::updatePrerequisiteState().
print()
virtual void CObjectInterface::print (std::ostream * ostream) const pure virtual
This is the output method for any object. The default implementation provided with CDataObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Implemented in CCopasiParameter, CSteadyStateTask, CMCAProblem, CSensProblem, CFitProblem, COptProblem, CMathObject, CLNAProblem, CCopasiTimer, CDataVectorReference< CType >, CDataObjectReference< CType >, CDataObjectReference< C_FLOAT64 >, CDataObjectReference< std::string >, CDataObject, CArrayElementReference, CCopasiTask::CResult, CCopasiTask::CDescription, CCopasiProblem, CCopasiParameterGroup, CCopasiMethod, CEigen, CSensTask, COscillationProblem, COptPopulationMethod, CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLReferenceGlyph, CLGlyphWithCurve, CLGraphicalObject, CLTextGlyph, CLCompartmentGlyph, CLMetabGlyph, CLayout, CCrossSectionProblem, CDataString, CDataArray, and CAnalyticsProblem.
validityChanged()
virtual void CObjectInterface::validityChanged (const CValidity & changedValidity) pure virtual
This method is called whenever the validity object changes.
Parameters
const CValidity & changedValidity
Implemented in CMathObject, and CDataObject.
Referenced by CValidity::add(), CValidity::clear(), CValidity::operator=(), CValidity::operator|=(), and CValidity::remove().
Member Data Documentation
mValidity
CValidity CObjectInterface::mValidity mutable protected
Referenced by CDataObject::addIssue(), CEvaluationTree::calculate(), CDataVector< CType >::clear(), CMassAction::compile(), CModelEntity::compile(), CReaction::compile(), CMathExpression::compile(), CMetab::compile(), CEventAssignment::compile(), CEvent::compile(), CExpression::compile(), CReaction::compileFunctionParameters(), CEvaluationTree::compileNodes(), CMathObject::getValidity(), CCopasiParameter::operator=(), CCopasiParameterGroup::operator=(), CEvaluationTree::parse(), CDataObject::removeIssue(), CModelEntity::setExpression(), CUnitDefinition::setExpression(), CEvaluationTree::setInfix(), CFunction::setInfix(), CMassAction::setInfix(), CExpression::setInfix(), CModelEntity::setInitialExpression(), CModelEntity::setUnitExpression(), and CEvaluationTree::updateTree().
The documentation for this class was generated from the following files:
CObjectInterface.h
CObjectInterface.cpp