COPASI API: blas.h File Reference
blas.h File Reference
Functions
int caxpy_ (integer *n, complex *ca, complex *cx, integer *incx, complex *cy, integer *incy)
int ccopy_ (integer *n, complex *cx, integer *incx, complex *cy, integer *incy)
VOID cdotc_ (complex *ret_val, integer *n, complex *cx, integer *incx, complex *cy, integer *incy)
VOID cdotu_ (complex *ret_val, integer *n, complex *cx, integer *incx, complex *cy, integer *incy)
int cgbmv_ (char *trans, integer *m, integer *n, integer *kl, integer *ku, complex *alpha, complex *a, integer *lda, complex *x, integer *incx, complex *beta, complex *y, integer *incy)
int cgemm_ (char *transa, char *transb, integer *m, integer *n, integer *k, complex *alpha, complex *a, integer *lda, complex *b, integer *ldb, complex *beta, complex *c, integer *ldc)
int cgemv_ (char *trans, integer *m, integer *n, complex *alpha, complex *a, integer *lda, complex *x, integer *incx, complex *beta, complex *y, integer *incy)
int cgerc_ (integer *m, integer *n, complex *alpha, complex *x, integer *incx, complex *y, integer *incy, complex *a, integer *lda)
int cgeru_ (integer *m, integer *n, complex *alpha, complex *x, integer *incx, complex *y, integer *incy, complex *a, integer *lda)
int chbmv_ (char *uplo, integer *n, integer *k, complex *alpha, complex *a, integer *lda, complex *x, integer *incx, complex *beta, complex *y, integer *incy)
int chemm_ (char *side, char *uplo, integer *m, integer *n, complex *alpha, complex *a, integer *lda, complex *b, integer *ldb, complex *beta, complex *c, integer *ldc)
int chemv_ (char *uplo, integer *n, complex *alpha, complex *a, integer *lda, complex *x, integer *incx, complex *beta, complex *y, integer *incy)
int cher2_ (char *uplo, integer *n, complex *alpha, complex *x, integer *incx, complex *y, integer *incy, complex *a, integer *lda)
int cher2k_ (char *uplo, char *trans, integer *n, integer *k, complex *alpha, complex *a, integer *lda, complex *b, integer *ldb, real *beta, complex *c, integer *ldc)
int cher_ (char *uplo, integer *n, real *alpha, complex *x, integer *incx, complex *a, integer *lda)
int cherk_ (char *uplo, char *trans, integer *n, integer *k, real *alpha, complex *a, integer *lda, real *beta, complex *c, integer *ldc)
int chpmv_ (char *uplo, integer *n, complex *alpha, complex *ap, complex *x, integer *incx, complex *beta, complex *y, integer *incy)
int chpr2_ (char *uplo, integer *n, complex *alpha, complex *x, integer *incx, complex *y, integer *incy, complex *ap)
int chpr_ (char *uplo, integer *n, real *alpha, complex *x, integer *incx, complex *ap)
int crotg_ (complex *ca, complex *cb, real *c, complex *s)
int cscal_ (integer *n, complex *ca, complex *cx, integer *incx)
int csscal_ (integer *n, real *sa, complex *cx, integer *incx)
int cswap_ (integer *n, complex *cx, integer *incx, complex *cy, integer *incy)
int csymm_ (char *side, char *uplo, integer *m, integer *n, complex *alpha, complex *a, integer *lda, complex *b, integer *ldb, complex *beta, complex *c, integer *ldc)
int csyr2k_ (char *uplo, char *trans, integer *n, integer *k, complex *alpha, complex *a, integer *lda, complex *b, integer *ldb, complex *beta, complex *c, integer *ldc)
int csyrk_ (char *uplo, char *trans, integer *n, integer *k, complex *alpha, complex *a, integer *lda, complex *beta, complex *c, integer *ldc)
int ctbmv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, complex *a, integer *lda, complex *x, integer *incx)
int ctbsv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, complex *a, integer *lda, complex *x, integer *incx)
int ctpmv_ (char *uplo, char *trans, char *diag, integer *n, complex *ap, complex *x, integer *incx)
int ctpsv_ (char *uplo, char *trans, char *diag, integer *n, complex *ap, complex *x, integer *incx)
int ctrmm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, complex *alpha, complex *a, integer *lda, complex *b, integer *ldb)
int ctrmv_ (char *uplo, char *trans, char *diag, integer *n, complex *a, integer *lda, complex *x, integer *incx)
int ctrsm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, complex *alpha, complex *a, integer *lda, complex *b, integer *ldb)
int ctrsv_ (char *uplo, char *trans, char *diag, integer *n, complex *a, integer *lda, complex *x, integer *incx)
doublereal dasum_ (integer *n, doublereal *dx, integer *incx)
int daxpy_ (integer *n, doublereal *da, doublereal *dx, integer *incx, doublereal *dy, integer *incy)
doublereal dcabs1_ (doublecomplex *z)
int dcopy_ (integer *n, doublereal *dx, integer *incx, doublereal *dy, integer *incy)
doublereal ddot_ (integer *n, doublereal *dx, integer *incx, doublereal *dy, integer *incy)
int dgbmv_ (char *trans, integer *m, integer *n, integer *kl, integer *ku, doublereal *alpha, doublereal *a, integer *lda, doublereal *x, integer *incx, doublereal *beta, doublereal *y, integer *incy)
int dgemm_ (char *transa, char *transb, integer *m, integer *n, integer *k, doublereal *alpha, doublereal *a, integer *lda, doublereal *b, integer *ldb, doublereal *beta, doublereal *c, integer *ldc)
int dgemv_ (char *trans, integer *m, integer *n, doublereal *alpha, doublereal *a, integer *lda, doublereal *x, integer *incx, doublereal *beta, doublereal *y, integer *incy)
int dger_ (integer *m, integer *n, doublereal *alpha, doublereal *x, integer *incx, doublereal *y, integer *incy, doublereal *a, integer *lda)
doublereal dnrm2_ (integer *n, doublereal *x, integer *incx)
int drot_ (integer *n, doublereal *dx, integer *incx, doublereal *dy, integer *incy, doublereal *c, doublereal *s)
int drotg_ (doublereal *da, doublereal *db, doublereal *c, doublereal *s)
int dsbmv_ (char *uplo, integer *n, integer *k, doublereal *alpha, doublereal *a, integer *lda, doublereal *x, integer *incx, doublereal *beta, doublereal *y, integer *incy)
int dscal_ (integer *n, doublereal *da, doublereal *dx, integer *incx)
int dspmv_ (char *uplo, integer *n, doublereal *alpha, doublereal *ap, doublereal *x, integer *incx, doublereal *beta, doublereal *y, integer *incy)
int dspr2_ (char *uplo, integer *n, doublereal *alpha, doublereal *x, integer *incx, doublereal *y, integer *incy, doublereal *ap)
int dspr_ (char *uplo, integer *n, doublereal *alpha, doublereal *x, integer *incx, doublereal *ap)
int dswap_ (integer *n, doublereal *dx, integer *incx, doublereal *dy, integer *incy)
int dsymm_ (char *side, char *uplo, integer *m, integer *n, doublereal *alpha, doublereal *a, integer *lda, doublereal *b, integer *ldb, doublereal *beta, doublereal *c, integer *ldc)
int dsymv_ (char *uplo, integer *n, doublereal *alpha, doublereal *a, integer *lda, doublereal *x, integer *incx, doublereal *beta, doublereal *y, integer *incy)
int dsyr2_ (char *uplo, integer *n, doublereal *alpha, doublereal *x, integer *incx, doublereal *y, integer *incy, doublereal *a, integer *lda)
int dsyr2k_ (char *uplo, char *trans, integer *n, integer *k, doublereal *alpha, doublereal *a, integer *lda, doublereal *b, integer *ldb, doublereal *beta, doublereal *c, integer *ldc)
int dsyr_ (char *uplo, integer *n, doublereal *alpha, doublereal *x, integer *incx, doublereal *a, integer *lda)
int dsyrk_ (char *uplo, char *trans, integer *n, integer *k, doublereal *alpha, doublereal *a, integer *lda, doublereal *beta, doublereal *c, integer *ldc)
int dtbmv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, doublereal *a, integer *lda, doublereal *x, integer *incx)
int dtbsv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, doublereal *a, integer *lda, doublereal *x, integer *incx)
int dtpmv_ (char *uplo, char *trans, char *diag, integer *n, doublereal *ap, doublereal *x, integer *incx)
int dtpsv_ (char *uplo, char *trans, char *diag, integer *n, doublereal *ap, doublereal *x, integer *incx)
int dtrmm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, doublereal *alpha, doublereal *a, integer *lda, doublereal *b, integer *ldb)
int dtrmv_ (char *uplo, char *trans, char *diag, integer *n, doublereal *a, integer *lda, doublereal *x, integer *incx)
int dtrsm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, doublereal *alpha, doublereal *a, integer *lda, doublereal *b, integer *ldb)
int dtrsv_ (char *uplo, char *trans, char *diag, integer *n, doublereal *a, integer *lda, doublereal *x, integer *incx)
doublereal dzasum_ (integer *n, doublecomplex *zx, integer *incx)
doublereal dznrm2_ (integer *n, doublecomplex *x, integer *incx)
integer icamax_ (integer *n, complex *cx, integer *incx)
integer idamax_ (integer *n, doublereal *dx, integer *incx)
integer isamax_ (integer *n, real *sx, integer *incx)
integer izamax_ (integer *n, doublecomplex *zx, integer *incx)
logical lsame_ (char *ca, char *cb)
doublereal sasum_ (integer *n, real *sx, integer *incx)
int saxpy_ (integer *n, real *sa, real *sx, integer *incx, real *sy, integer *incy)
doublereal scasum_ (integer *n, complex *cx, integer *incx)
doublereal scnrm2_ (integer *n, complex *x, integer *incx)
int scopy_ (integer *n, real *sx, integer *incx, real *sy, integer *incy)
doublereal sdot_ (integer *n, real *sx, integer *incx, real *sy, integer *incy)
int sgbmv_ (char *trans, integer *m, integer *n, integer *kl, integer *ku, real *alpha, real *a, integer *lda, real *x, integer *incx, real *beta, real *y, integer *incy)
int sgemm_ (char *transa, char *transb, integer *m, integer *n, integer *k, real *alpha, real *a, integer *lda, real *b, integer *ldb, real *beta, real *c, integer *ldc)
int sgemv_ (char *trans, integer *m, integer *n, real *alpha, real *a, integer *lda, real *x, integer *incx, real *beta, real *y, integer *incy)
int sger_ (integer *m, integer *n, real *alpha, real *x, integer *incx, real *y, integer *incy, real *a, integer *lda)
doublereal snrm2_ (integer *n, real *x, integer *incx)
int srot_ (integer *n, real *sx, integer *incx, real *sy, integer *incy, real *c, real *s)
int srotg_ (real *sa, real *sb, real *c, real *s)
int ssbmv_ (char *uplo, integer *n, integer *k, real *alpha, real *a, integer *lda, real *x, integer *incx, real *beta, real *y, integer *incy)
int sscal_ (integer *n, real *sa, real *sx, integer *incx)
int sspmv_ (char *uplo, integer *n, real *alpha, real *ap, real *x, integer *incx, real *beta, real *y, integer *incy)
int sspr2_ (char *uplo, integer *n, real *alpha, real *x, integer *incx, real *y, integer *incy, real *ap)
int sspr_ (char *uplo, integer *n, real *alpha, real *x, integer *incx, real *ap)
int sswap_ (integer *n, real *sx, integer *incx, real *sy, integer *incy)
int ssymm_ (char *side, char *uplo, integer *m, integer *n, real *alpha, real *a, integer *lda, real *b, integer *ldb, real *beta, real *c, integer *ldc)
int ssymv_ (char *uplo, integer *n, real *alpha, real *a, integer *lda, real *x, integer *incx, real *beta, real *y, integer *incy)
int ssyr2_ (char *uplo, integer *n, real *alpha, real *x, integer *incx, real *y, integer *incy, real *a, integer *lda)
int ssyr2k_ (char *uplo, char *trans, integer *n, integer *k, real *alpha, real *a, integer *lda, real *b, integer *ldb, real *beta, real *c, integer *ldc)
int ssyr_ (char *uplo, integer *n, real *alpha, real *x, integer *incx, real *a, integer *lda)
int ssyrk_ (char *uplo, char *trans, integer *n, integer *k, real *alpha, real *a, integer *lda, real *beta, real *c, integer *ldc)
int stbmv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, real *a, integer *lda, real *x, integer *incx)
int stbsv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, real *a, integer *lda, real *x, integer *incx)
int stpmv_ (char *uplo, char *trans, char *diag, integer *n, real *ap, real *x, integer *incx)
int stpsv_ (char *uplo, char *trans, char *diag, integer *n, real *ap, real *x, integer *incx)
int strmm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, real *alpha, real *a, integer *lda, real *b, integer *ldb)
int strmv_ (char *uplo, char *trans, char *diag, integer *n, real *a, integer *lda, real *x, integer *incx)
int strsm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, real *alpha, real *a, integer *lda, real *b, integer *ldb)
int strsv_ (char *uplo, char *trans, char *diag, integer *n, real *a, integer *lda, real *x, integer *incx)
int xerbla_ (char *srname, integer *info)
int zaxpy_ (integer *n, doublecomplex *za, doublecomplex *zx, integer *incx, doublecomplex *zy, integer *incy)
int zcopy_ (integer *n, doublecomplex *zx, integer *incx, doublecomplex *zy, integer *incy)
VOID zdotc_ (doublecomplex *ret_val, integer *n, doublecomplex *zx, integer *incx, doublecomplex *zy, integer *incy)
VOID zdotu_ (doublecomplex *ret_val, integer *n, doublecomplex *zx, integer *incx, doublecomplex *zy, integer *incy)
int zdscal_ (integer *n, doublereal *da, doublecomplex *zx, integer *incx)
int zgbmv_ (char *trans, integer *m, integer *n, integer *kl, integer *ku, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx, doublecomplex *beta, doublecomplex *y, integer *incy)
int zgemm_ (char *transa, char *transb, integer *m, integer *n, integer *k, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb, doublecomplex *beta, doublecomplex *c, integer *ldc)
int zgemv_ (char *trans, integer *m, integer *n, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx, doublecomplex *beta, doublecomplex *y, integer *incy)
int zgerc_ (integer *m, integer *n, doublecomplex *alpha, doublecomplex *x, integer *incx, doublecomplex *y, integer *incy, doublecomplex *a, integer *lda)
int zgeru_ (integer *m, integer *n, doublecomplex *alpha, doublecomplex *x, integer *incx, doublecomplex *y, integer *incy, doublecomplex *a, integer *lda)
int zhbmv_ (char *uplo, integer *n, integer *k, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx, doublecomplex *beta, doublecomplex *y, integer *incy)
int zhemm_ (char *side, char *uplo, integer *m, integer *n, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb, doublecomplex *beta, doublecomplex *c, integer *ldc)
int zhemv_ (char *uplo, integer *n, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx, doublecomplex *beta, doublecomplex *y, integer *incy)
int zher2_ (char *uplo, integer *n, doublecomplex *alpha, doublecomplex *x, integer *incx, doublecomplex *y, integer *incy, doublecomplex *a, integer *lda)
int zher2k_ (char *uplo, char *trans, integer *n, integer *k, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb, doublereal *beta, doublecomplex *c, integer *ldc)
int zher_ (char *uplo, integer *n, doublereal *alpha, doublecomplex *x, integer *incx, doublecomplex *a, integer *lda)
int zherk_ (char *uplo, char *trans, integer *n, integer *k, doublereal *alpha, doublecomplex *a, integer *lda, doublereal *beta, doublecomplex *c, integer *ldc)
int zhpmv_ (char *uplo, integer *n, doublecomplex *alpha, doublecomplex *ap, doublecomplex *x, integer *incx, doublecomplex *beta, doublecomplex *y, integer *incy)
int zhpr2_ (char *uplo, integer *n, doublecomplex *alpha, doublecomplex *x, integer *incx, doublecomplex *y, integer *incy, doublecomplex *ap)
int zhpr_ (char *uplo, integer *n, doublereal *alpha, doublecomplex *x, integer *incx, doublecomplex *ap)
int zrotg_ (doublecomplex *ca, doublecomplex *cb, doublereal *c, doublecomplex *s)
int zscal_ (integer *n, doublecomplex *za, doublecomplex *zx, integer *incx)
int zswap_ (integer *n, doublecomplex *zx, integer *incx, doublecomplex *zy, integer *incy)
int zsymm_ (char *side, char *uplo, integer *m, integer *n, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb, doublecomplex *beta, doublecomplex *c, integer *ldc)
int zsyr2k_ (char *uplo, char *trans, integer *n, integer *k, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb, doublecomplex *beta, doublecomplex *c, integer *ldc)
int zsyrk_ (char *uplo, char *trans, integer *n, integer *k, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *beta, doublecomplex *c, integer *ldc)
int ztbmv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx)
int ztbsv_ (char *uplo, char *trans, char *diag, integer *n, integer *k, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx)
int ztpmv_ (char *uplo, char *trans, char *diag, integer *n, doublecomplex *ap, doublecomplex *x, integer *incx)
int ztpsv_ (char *uplo, char *trans, char *diag, integer *n, doublecomplex *ap, doublecomplex *x, integer *incx)
int ztrmm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb)
int ztrmv_ (char *uplo, char *trans, char *diag, integer *n, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx)
int ztrsm_ (char *side, char *uplo, char *transa, char *diag, integer *m, integer *n, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb)
int ztrsv_ (char *uplo, char *trans, char *diag, integer *n, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx)
Function Documentation
caxpy_()
int caxpy_ (integer * n, complex * ca, complex * cx, integer * incx, complex * cy, integer * incy)
ccopy_()
int ccopy_ (integer * n, complex * cx, integer * incx, complex * cy, integer * incy)
cdotc_()
VOID cdotc_ (complex * ret_val, integer * n, complex * cx, integer * incx, complex * cy, integer * incy)
cdotu_()
VOID cdotu_ (complex * ret_val, integer * n, complex * cx, integer * incx, complex * cy, integer * incy)
cgbmv_()
int cgbmv_ (char * trans, integer * m, integer * n, integer * kl, integer * ku, complex * alpha, complex * a, integer * lda, complex * x, integer * incx, complex * beta, complex * y, integer * incy)
cgemm_()
int cgemm_ (char * transa, char * transb, integer * m, integer * n, integer * k, complex * alpha, complex * a, integer * lda, complex * b, integer * ldb, complex * beta, complex * c, integer * ldc)
cgemv_()
int cgemv_ (char * trans, integer * m, integer * n, complex * alpha, complex * a, integer * lda, complex * x, integer * incx, complex * beta, complex * y, integer * incy)
cgerc_()
int cgerc_ (integer * m, integer * n, complex * alpha, complex * x, integer * incx, complex * y, integer * incy, complex * a, integer * lda)
cgeru_()
int cgeru_ (integer * m, integer * n, complex * alpha, complex * x, integer * incx, complex * y, integer * incy, complex * a, integer * lda)
chbmv_()
int chbmv_ (char * uplo, integer * n, integer * k, complex * alpha, complex * a, integer * lda, complex * x, integer * incx, complex * beta, complex * y, integer * incy)
chemm_()
int chemm_ (char * side, char * uplo, integer * m, integer * n, complex * alpha, complex * a, integer * lda, complex * b, integer * ldb, complex * beta, complex * c, integer * ldc)
chemv_()
int chemv_ (char * uplo, integer * n, complex * alpha, complex * a, integer * lda, complex * x, integer * incx, complex * beta, complex * y, integer * incy)
cher2_()
int cher2_ (char * uplo, integer * n, complex * alpha, complex * x, integer * incx, complex * y, integer * incy, complex * a, integer * lda)
cher2k_()
int cher2k_ (char * uplo, char * trans, integer * n, integer * k, complex * alpha, complex * a, integer * lda, complex * b, integer * ldb, real * beta, complex * c, integer * ldc)
cher_()
int cher_ (char * uplo, integer * n, real * alpha, complex * x, integer * incx, complex * a, integer * lda)
cherk_()
int cherk_ (char * uplo, char * trans, integer * n, integer * k, real * alpha, complex * a, integer * lda, real * beta, complex * c, integer * ldc)
chpmv_()
int chpmv_ (char * uplo, integer * n, complex * alpha, complex * ap, complex * x, integer * incx, complex * beta, complex * y, integer * incy)
chpr2_()
int chpr2_ (char * uplo, integer * n, complex * alpha, complex * x, integer * incx, complex * y, integer * incy, complex * ap)
chpr_()
int chpr_ (char * uplo, integer * n, real * alpha, complex * x, integer * incx, complex * ap)
crotg_()
int crotg_ (complex * ca, complex * cb, real * c, complex * s)
cscal_()
int cscal_ (integer * n, complex * ca, complex * cx, integer * incx)
csscal_()
int csscal_ (integer * n, real * sa, complex * cx, integer * incx)
cswap_()
int cswap_ (integer * n, complex * cx, integer * incx, complex * cy, integer * incy)
csymm_()
int csymm_ (char * side, char * uplo, integer * m, integer * n, complex * alpha, complex * a, integer * lda, complex * b, integer * ldb, complex * beta, complex * c, integer * ldc)
csyr2k_()
int csyr2k_ (char * uplo, char * trans, integer * n, integer * k, complex * alpha, complex * a, integer * lda, complex * b, integer * ldb, complex * beta, complex * c, integer * ldc)
csyrk_()
int csyrk_ (char * uplo, char * trans, integer * n, integer * k, complex * alpha, complex * a, integer * lda, complex * beta, complex * c, integer * ldc)
ctbmv_()
int ctbmv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, complex * a, integer * lda, complex * x, integer * incx)
ctbsv_()
int ctbsv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, complex * a, integer * lda, complex * x, integer * incx)
ctpmv_()
int ctpmv_ (char * uplo, char * trans, char * diag, integer * n, complex * ap, complex * x, integer * incx)
ctpsv_()
int ctpsv_ (char * uplo, char * trans, char * diag, integer * n, complex * ap, complex * x, integer * incx)
ctrmm_()
int ctrmm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, complex * alpha, complex * a, integer * lda, complex * b, integer * ldb)
ctrmv_()
int ctrmv_ (char * uplo, char * trans, char * diag, integer * n, complex * a, integer * lda, complex * x, integer * incx)
ctrsm_()
int ctrsm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, complex * alpha, complex * a, integer * lda, complex * b, integer * ldb)
ctrsv_()
int ctrsv_ (char * uplo, char * trans, char * diag, integer * n, complex * a, integer * lda, complex * x, integer * incx)
dasum_()
doublereal dasum_ (integer * n, doublereal * dx, integer * incx)
daxpy_()
int daxpy_ (integer * n, doublereal * da, doublereal * dx, integer * incx, doublereal * dy, integer * incy)
dcabs1_()
doublereal dcabs1_ (doublecomplex * z)
dcopy_()
int dcopy_ (integer * n, doublereal * dx, integer * incx, doublereal * dy, integer * incy)
Referenced by CLSODAR::operator()().
ddot_()
doublereal ddot_ (integer * n, doublereal * dx, integer * incx, doublereal * dy, integer * incy)
Referenced by initp3_(), CTruncatedNewton::linder_(), CTruncatedNewton::lmqnbc_(), CTruncatedNewton::modlnp_(), mslv_(), ndia3_(), and CTruncatedNewton::setucr_().
dgbmv_()
int dgbmv_ (char * trans, integer * m, integer * n, integer * kl, integer * ku, doublereal * alpha, doublereal * a, integer * lda, doublereal * x, integer * incx, doublereal * beta, doublereal * y, integer * incy)
dgemm_()
int dgemm_ (char * transa, char * transb, integer * m, integer * n, integer * k, doublereal * alpha, doublereal * a, integer * lda, doublereal * b, integer * ldb, doublereal * beta, doublereal * c, integer * ldc)
Referenced by CLNAMethod::calculateCovarianceMatrixFull(), CLNAMethod::calculateCovarianceMatrixReduced(), CSSAMethod::decomposeJacobian(), dgemm::eval(), COptMethodLevenbergMarquardt::hessian(), CLinkMatrix::leftMultiply(), and CLinkMatrix::rightMultiply().
dgemv_()
int dgemv_ (char * trans, integer * m, integer * n, doublereal * alpha, doublereal * a, integer * lda, doublereal * x, integer * incx, doublereal * beta, doublereal * y, integer * incy)
dger_()
int dger_ (integer * m, integer * n, doublereal * alpha, doublereal * x, integer * incx, doublereal * y, integer * incy, doublereal * a, integer * lda)
dnrm2_()
doublereal dnrm2_ (integer * n, doublereal * x, integer * incx)
drot_()
int drot_ (integer * n, doublereal * dx, integer * incx, doublereal * dy, integer * incy, doublereal * c, doublereal * s)
drotg_()
int drotg_ (doublereal * da, doublereal * db, doublereal * c, doublereal * s)
dsbmv_()
int dsbmv_ (char * uplo, integer * n, integer * k, doublereal * alpha, doublereal * a, integer * lda, doublereal * x, integer * incx, doublereal * beta, doublereal * y, integer * incy)
dscal_()
int dscal_ (integer * n, doublereal * da, doublereal * dx, integer * incx)
dspmv_()
int dspmv_ (char * uplo, integer * n, doublereal * alpha, doublereal * ap, doublereal * x, integer * incx, doublereal * beta, doublereal * y, integer * incy)
dspr2_()
int dspr2_ (char * uplo, integer * n, doublereal * alpha, doublereal * x, integer * incx, doublereal * y, integer * incy, doublereal * ap)
dspr_()
int dspr_ (char * uplo, integer * n, doublereal * alpha, doublereal * x, integer * incx, doublereal * ap)
dswap_()
int dswap_ (integer * n, doublereal * dx, integer * incx, doublereal * dy, integer * incy)
dsymm_()
int dsymm_ (char * side, char * uplo, integer * m, integer * n, doublereal * alpha, doublereal * a, integer * lda, doublereal * b, integer * ldb, doublereal * beta, doublereal * c, integer * ldc)
dsymv_()
int dsymv_ (char * uplo, integer * n, doublereal * alpha, doublereal * a, integer * lda, doublereal * x, integer * incx, doublereal * beta, doublereal * y, integer * incy)
dsyr2_()
int dsyr2_ (char * uplo, integer * n, doublereal * alpha, doublereal * x, integer * incx, doublereal * y, integer * incy, doublereal * a, integer * lda)
dsyr2k_()
int dsyr2k_ (char * uplo, char * trans, integer * n, integer * k, doublereal * alpha, doublereal * a, integer * lda, doublereal * b, integer * ldb, doublereal * beta, doublereal * c, integer * ldc)
dsyr_()
int dsyr_ (char * uplo, integer * n, doublereal * alpha, doublereal * x, integer * incx, doublereal * a, integer * lda)
dsyrk_()
int dsyrk_ (char * uplo, char * trans, integer * n, integer * k, doublereal * alpha, doublereal * a, integer * lda, doublereal * beta, doublereal * c, integer * ldc)
dtbmv_()
int dtbmv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, doublereal * a, integer * lda, doublereal * x, integer * incx)
dtbsv_()
int dtbsv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, doublereal * a, integer * lda, doublereal * x, integer * incx)
dtpmv_()
int dtpmv_ (char * uplo, char * trans, char * diag, integer * n, doublereal * ap, doublereal * x, integer * incx)
dtpsv_()
int dtpsv_ (char * uplo, char * trans, char * diag, integer * n, doublereal * ap, doublereal * x, integer * incx)
dtrmm_()
int dtrmm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, doublereal * alpha, doublereal * a, integer * lda, doublereal * b, integer * ldb)
dtrmv_()
int dtrmv_ (char * uplo, char * trans, char * diag, integer * n, doublereal * a, integer * lda, doublereal * x, integer * incx)
dtrsm_()
int dtrsm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, doublereal * alpha, doublereal * a, integer * lda, doublereal * b, integer * ldb)
dtrsv_()
int dtrsv_ (char * uplo, char * trans, char * diag, integer * n, doublereal * a, integer * lda, doublereal * x, integer * incx)
dzasum_()
doublereal dzasum_ (integer * n, doublecomplex * zx, integer * incx)
dznrm2_()
doublereal dznrm2_ (integer * n, doublecomplex * x, integer * incx)
icamax_()
integer icamax_ (integer * n, complex * cx, integer * incx)
idamax_()
integer idamax_ (integer * n, doublereal * dx, integer * incx)
isamax_()
integer isamax_ (integer * n, real * sx, integer * incx)
izamax_()
integer izamax_ (integer * n, doublecomplex * zx, integer * incx)
lsame_()
logical lsame_ (char * ca, char * cb)
sasum_()
doublereal sasum_ (integer * n, real * sx, integer * incx)
saxpy_()
int saxpy_ (integer * n, real * sa, real * sx, integer * incx, real * sy, integer * incy)
scasum_()
doublereal scasum_ (integer * n, complex * cx, integer * incx)
scnrm2_()
doublereal scnrm2_ (integer * n, complex * x, integer * incx)
scopy_()
int scopy_ (integer * n, real * sx, integer * incx, real * sy, integer * incy)
sdot_()
doublereal sdot_ (integer * n, real * sx, integer * incx, real * sy, integer * incy)
sgbmv_()
int sgbmv_ (char * trans, integer * m, integer * n, integer * kl, integer * ku, real * alpha, real * a, integer * lda, real * x, integer * incx, real * beta, real * y, integer * incy)
sgemm_()
int sgemm_ (char * transa, char * transb, integer * m, integer * n, integer * k, real * alpha, real * a, integer * lda, real * b, integer * ldb, real * beta, real * c, integer * ldc)
sgemv_()
int sgemv_ (char * trans, integer * m, integer * n, real * alpha, real * a, integer * lda, real * x, integer * incx, real * beta, real * y, integer * incy)
sger_()
int sger_ (integer * m, integer * n, real * alpha, real * x, integer * incx, real * y, integer * incy, real * a, integer * lda)
snrm2_()
doublereal snrm2_ (integer * n, real * x, integer * incx)
srot_()
int srot_ (integer * n, real * sx, integer * incx, real * sy, integer * incy, real * c, real * s)
srotg_()
int srotg_ (real * sa, real * sb, real * c, real * s)
ssbmv_()
int ssbmv_ (char * uplo, integer * n, integer * k, real * alpha, real * a, integer * lda, real * x, integer * incx, real * beta, real * y, integer * incy)
sscal_()
int sscal_ (integer * n, real * sa, real * sx, integer * incx)
sspmv_()
int sspmv_ (char * uplo, integer * n, real * alpha, real * ap, real * x, integer * incx, real * beta, real * y, integer * incy)
sspr2_()
int sspr2_ (char * uplo, integer * n, real * alpha, real * x, integer * incx, real * y, integer * incy, real * ap)
sspr_()
int sspr_ (char * uplo, integer * n, real * alpha, real * x, integer * incx, real * ap)
sswap_()
int sswap_ (integer * n, real * sx, integer * incx, real * sy, integer * incy)
ssymm_()
int ssymm_ (char * side, char * uplo, integer * m, integer * n, real * alpha, real * a, integer * lda, real * b, integer * ldb, real * beta, real * c, integer * ldc)
ssymv_()
int ssymv_ (char * uplo, integer * n, real * alpha, real * a, integer * lda, real * x, integer * incx, real * beta, real * y, integer * incy)
ssyr2_()
int ssyr2_ (char * uplo, integer * n, real * alpha, real * x, integer * incx, real * y, integer * incy, real * a, integer * lda)
ssyr2k_()
int ssyr2k_ (char * uplo, char * trans, integer * n, integer * k, real * alpha, real * a, integer * lda, real * b, integer * ldb, real * beta, real * c, integer * ldc)
ssyr_()
int ssyr_ (char * uplo, integer * n, real * alpha, real * x, integer * incx, real * a, integer * lda)
ssyrk_()
int ssyrk_ (char * uplo, char * trans, integer * n, integer * k, real * alpha, real * a, integer * lda, real * beta, real * c, integer * ldc)
stbmv_()
int stbmv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, real * a, integer * lda, real * x, integer * incx)
stbsv_()
int stbsv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, real * a, integer * lda, real * x, integer * incx)
stpmv_()
int stpmv_ (char * uplo, char * trans, char * diag, integer * n, real * ap, real * x, integer * incx)
stpsv_()
int stpsv_ (char * uplo, char * trans, char * diag, integer * n, real * ap, real * x, integer * incx)
strmm_()
int strmm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, real * alpha, real * a, integer * lda, real * b, integer * ldb)
strmv_()
int strmv_ (char * uplo, char * trans, char * diag, integer * n, real * a, integer * lda, real * x, integer * incx)
strsm_()
int strsm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, real * alpha, real * a, integer * lda, real * b, integer * ldb)
strsv_()
int strsv_ (char * uplo, char * trans, char * diag, integer * n, real * a, integer * lda, real * x, integer * incx)
xerbla_()
int xerbla_ (char * srname, integer * info)
zaxpy_()
int zaxpy_ (integer * n, doublecomplex * za, doublecomplex * zx, integer * incx, doublecomplex * zy, integer * incy)
zcopy_()
int zcopy_ (integer * n, doublecomplex * zx, integer * incx, doublecomplex * zy, integer * incy)
zdotc_()
VOID zdotc_ (doublecomplex * ret_val, integer * n, doublecomplex * zx, integer * incx, doublecomplex * zy, integer * incy)
zdotu_()
VOID zdotu_ (doublecomplex * ret_val, integer * n, doublecomplex * zx, integer * incx, doublecomplex * zy, integer * incy)
zdscal_()
int zdscal_ (integer * n, doublereal * da, doublecomplex * zx, integer * incx)
zgbmv_()
int zgbmv_ (char * trans, integer * m, integer * n, integer * kl, integer * ku, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx, doublecomplex * beta, doublecomplex * y, integer * incy)
zgemm_()
int zgemm_ (char * transa, char * transb, integer * m, integer * n, integer * k, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * b, integer * ldb, doublecomplex * beta, doublecomplex * c, integer * ldc)
zgemv_()
int zgemv_ (char * trans, integer * m, integer * n, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx, doublecomplex * beta, doublecomplex * y, integer * incy)
zgerc_()
int zgerc_ (integer * m, integer * n, doublecomplex * alpha, doublecomplex * x, integer * incx, doublecomplex * y, integer * incy, doublecomplex * a, integer * lda)
zgeru_()
int zgeru_ (integer * m, integer * n, doublecomplex * alpha, doublecomplex * x, integer * incx, doublecomplex * y, integer * incy, doublecomplex * a, integer * lda)
zhbmv_()
int zhbmv_ (char * uplo, integer * n, integer * k, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx, doublecomplex * beta, doublecomplex * y, integer * incy)
zhemm_()
int zhemm_ (char * side, char * uplo, integer * m, integer * n, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * b, integer * ldb, doublecomplex * beta, doublecomplex * c, integer * ldc)
zhemv_()
int zhemv_ (char * uplo, integer * n, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx, doublecomplex * beta, doublecomplex * y, integer * incy)
zher2_()
int zher2_ (char * uplo, integer * n, doublecomplex * alpha, doublecomplex * x, integer * incx, doublecomplex * y, integer * incy, doublecomplex * a, integer * lda)
zher2k_()
int zher2k_ (char * uplo, char * trans, integer * n, integer * k, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * b, integer * ldb, doublereal * beta, doublecomplex * c, integer * ldc)
zher_()
int zher_ (char * uplo, integer * n, doublereal * alpha, doublecomplex * x, integer * incx, doublecomplex * a, integer * lda)
zherk_()
int zherk_ (char * uplo, char * trans, integer * n, integer * k, doublereal * alpha, doublecomplex * a, integer * lda, doublereal * beta, doublecomplex * c, integer * ldc)
zhpmv_()
int zhpmv_ (char * uplo, integer * n, doublecomplex * alpha, doublecomplex * ap, doublecomplex * x, integer * incx, doublecomplex * beta, doublecomplex * y, integer * incy)
zhpr2_()
int zhpr2_ (char * uplo, integer * n, doublecomplex * alpha, doublecomplex * x, integer * incx, doublecomplex * y, integer * incy, doublecomplex * ap)
zhpr_()
int zhpr_ (char * uplo, integer * n, doublereal * alpha, doublecomplex * x, integer * incx, doublecomplex * ap)
zrotg_()
int zrotg_ (doublecomplex * ca, doublecomplex * cb, doublereal * c, doublecomplex * s)
zscal_()
int zscal_ (integer * n, doublecomplex * za, doublecomplex * zx, integer * incx)
zswap_()
int zswap_ (integer * n, doublecomplex * zx, integer * incx, doublecomplex * zy, integer * incy)
zsymm_()
int zsymm_ (char * side, char * uplo, integer * m, integer * n, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * b, integer * ldb, doublecomplex * beta, doublecomplex * c, integer * ldc)
zsyr2k_()
int zsyr2k_ (char * uplo, char * trans, integer * n, integer * k, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * b, integer * ldb, doublecomplex * beta, doublecomplex * c, integer * ldc)
zsyrk_()
int zsyrk_ (char * uplo, char * trans, integer * n, integer * k, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * beta, doublecomplex * c, integer * ldc)
ztbmv_()
int ztbmv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx)
ztbsv_()
int ztbsv_ (char * uplo, char * trans, char * diag, integer * n, integer * k, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx)
ztpmv_()
int ztpmv_ (char * uplo, char * trans, char * diag, integer * n, doublecomplex * ap, doublecomplex * x, integer * incx)
ztpsv_()
int ztpsv_ (char * uplo, char * trans, char * diag, integer * n, doublecomplex * ap, doublecomplex * x, integer * incx)
ztrmm_()
int ztrmm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * b, integer * ldb)
ztrmv_()
int ztrmv_ (char * uplo, char * trans, char * diag, integer * n, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx)
ztrsm_()
int ztrsm_ (char * side, char * uplo, char * transa, char * diag, integer * m, integer * n, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * b, integer * ldb)
ztrsv_()
int ztrsv_ (char * uplo, char * trans, char * diag, integer * n, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx)