COPASI API: CPlotItem Class Reference
CPlotItem Class Reference
#include <CPlotItem.h>
Public Types
enum class LineStyle {
Solid = 0 , Dotted , Dashed , DotDash ,
DotDotDash , None , __SIZE
}
enum class LineType {
Lines = 0 , Points , Symbols , LinesAndSymbols ,
__SIZE
}
enum class SymbolType {
SmallCross = 0 , LargeCross , Circle , Square ,
Diamond , xCross , Plus , Star ,
TriangleUp , TriangleDown , TriangleLeft , TriangleRight ,
hDash , vDash , None , __SIZE
}
enum Type {
unset = 0 , curve2d , histoItem1d , bandedGraph ,
surface , plot2d , simWiz , spectogram
}
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
void addChannel (const CPlotDataChannelSpec &channel)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
void cleanup ()
CPlotItem (const CPlotItem &src, const CDataContainer *pParent)
CPlotItem (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const Type &type=curve2d)
const COutputInterface::Activity & getActivity () const
std::vector< CPlotDataChannelSpec > & getChannels ()
const std::vector< CPlotDataChannelSpec > & getChannels () const
size_t getNumChannels () const
const std::string & getTitle () const
const CPlotItem::Type & getType () const
void setActivity (const COutputInterface::Activity &activity)
void setTitle (const std::string &title)
void setType (CPlotItem::Type type)
virtual CData toData () const
virtual ~CPlotItem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual bool elevateChildren ()
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CPlotItem * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes
static const CEnumAnnotation< std::string, LineStyle > LineStyleNames
static const CEnumAnnotation< std::string, LineType > LineTypeNames
static const std::string RecordingActivityName []
static const CEnumAnnotation< std::string, SymbolType > SymbolNames
static const std::string TypeName []
static const char * XMLRecordingActivity []
static const char * XMLType []
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions
CPlotItem (const CPlotItem &src)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Private Member Functions
void initObjects ()
Private Attributes
std::vector< CPlotDataChannelSpec > channels
COutputInterface::Activity mActivity
std::string * mpXMLActivity
Type mType
Additional Inherited Members
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Member Enumeration Documentation
LineStyle
enum CPlotItem::LineStyle strong
Enumerator
Solid
Dotted
Dashed
DotDash
DotDotDash
None
__SIZE
LineType
enum CPlotItem::LineType strong
Enumerator
Lines
Points
Symbols
LinesAndSymbols
__SIZE
SymbolType
enum CPlotItem::SymbolType strong
Enumerator
SmallCross
LargeCross
Circle
Square
Diamond
xCross
Plus
Star
TriangleUp
TriangleDown
TriangleLeft
TriangleRight
hDash
vDash
None
__SIZE
Type
enum CPlotItem::Type
Enumeration of the sub types of curve types known to COPASI.
Enumerator
unset
curve2d
histoItem1d
bandedGraph
surface
plot2d
simWiz
spectogram
Constructor & Destructor Documentation
CPlotItem() [1/3]
CPlotItem::CPlotItem (const CPlotItem & src) protected
Referenced by CPlotSpecification::createItem(), and fromData().
CPlotItem() [2/3]
CPlotItem::CPlotItem (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT, const Type & type = curve2d)
References CDataObject::setObjectName(), and setType().
CPlotItem() [3/3]
CPlotItem::CPlotItem (const CPlotItem & src, const CDataContainer * pParent)
References mType, and setType().
~CPlotItem()
CPlotItem::~CPlotItem () virtual
Destructor
Member Function Documentation
addChannel()
void CPlotItem::addChannel (const CPlotDataChannelSpec & channel)
References channels.
Referenced by SEDMLImporter::addCurveToCopasiPlot(), SEDMLImporter::addSurfaceToCopasiPlot(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), and COutputAssistant::createPlot().
applyData()
bool CPlotItem::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Reimplemented in CPlotSpecification.
References fatalError.
cleanup()
void CPlotItem::cleanup ()
Referenced by CPlotSpecification::cleanup().
fromData()
CPlotItem * CPlotItem::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CPlotItem * pDataObject
References CPlotItem(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, CData::PLOT_ITEM_TYPE, CDataValue::toString(), and CDataValue::toUint().
getActivity()
const COutputInterface::Activity & CPlotItem::getActivity () const
References COutputInterface::AFTER, bandedGraph, COutputInterface::BEFORE, curve2d, COutputInterface::DURING, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), histoItem1d, mActivity, mpXMLActivity, mType, spectogram, surface, toEnum(), and XMLRecordingActivity.
getChannels() [1/2]
std::vector< CPlotDataChannelSpec > & CPlotItem::getChannels ()
References channels.
Referenced by CSEDMLExporter::exportPlotItem(), ChannelSpecHandler::processEnd(), and CCopasiXML::savePlotList().
getChannels() [2/2]
const std::vector< CPlotDataChannelSpec > & CPlotItem::getChannels () const
References channels.
getNumChannels()
size_t CPlotItem::getNumChannels () const
References channels.
Referenced by CCopasiXML::savePlotList().
getTitle()
const std::string & CPlotItem::getTitle () const
References CDataObject::getObjectName().
getType()
const CPlotItem::Type & CPlotItem::getType () const
Retrieve the type of the method
References mType.
Referenced by CSEDMLExporter::exportPlotItem(), CSEDMLExporter::exportStyleForItem(), and CCopasiXML::savePlotList().
initObjects()
void CPlotItem::initObjects () private
Initialize the contained CDataObjects
setActivity()
void CPlotItem::setActivity (const COutputInterface::Activity & activity)
References bandedGraph, curve2d, histoItem1d, mActivity, mpXMLActivity, mType, spectogram, surface, and XMLRecordingActivity.
Referenced by COutputAssistant::createDefaultOutput().
setTitle()
void CPlotItem::setTitle (const std::string & title)
References CDataObject::setObjectName().
setType()
void CPlotItem::setType (CPlotItem::Type type)
References COutputInterface::AFTER, CCopasiParameterGroup::assertParameter(), bandedGraph, COutputInterface::BEFORE, CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameterGroup::clear(), curve2d, CCopasiParameter::DOUBLE, COutputInterface::DURING, histoItem1d, mActivity, mpXMLActivity, mType, plot2d, spectogram, CCopasiParameter::STRING, surface, toEnum(), CCopasiParameter::UDOUBLE, CCopasiParameter::UINT, unset, and XMLRecordingActivity.
Referenced by CPlotItem(), and PlotSpecificationHandler::processStart().
toData()
CData CPlotItem::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CCopasiParameterGroup.
Reimplemented in CPlotSpecification.
References fatalError.
Member Data Documentation
channels
std::vector<CPlotDataChannelSpec> CPlotItem::channels private
Referenced by addChannel(), getChannels(), and getNumChannels().
LineStyleNames
const CEnumAnnotation< std::string, CPlotItem::LineStyle > CPlotItem::LineStyleNames static
String literals for the GUI to display type names of line types known to COPASI.
LineTypeNames
const CEnumAnnotation< std::string, CPlotItem::LineType > CPlotItem::LineTypeNames static
mActivity
COutputInterface::Activity CPlotItem::mActivity private
The recording activity for items of type curve2d and histoItem1d
Referenced by getActivity(), setActivity(), and setType().
mpXMLActivity
std::string* CPlotItem::mpXMLActivity private
A pointer to the string containing the XML representation of the activity
Referenced by getActivity(), setActivity(), and setType().
mType
Type CPlotItem::mType private
The type of the method
Referenced by CPlotItem(), getActivity(), getType(), setActivity(), and setType().
RecordingActivityName
const std::string CPlotItem::RecordingActivityName static
Initial value:
=
{
  "",
  "Before",
  "During",
  "",
  "After"
}
String literals for the GUI to display recording activity names of plots known to COPASI.
SymbolNames
const CEnumAnnotation< std::string, CPlotItem::SymbolType > CPlotItem::SymbolNames static
String literals for the GUI to display type names of symbol known to COPASI.
TypeName
const std::string CPlotItem::TypeName static
Initial value:
=
{
  "Unset",
  "2D Curve",
  "Histogram",
  "Banded Graph",
  "Surface",
  "2D Plot",
  "SimWiz",
  "Spectogram",
  ""
}
String literals for the GUI to display plot item names of methods known to COPASI.
XMLRecordingActivity
const char * CPlotItem::XMLRecordingActivity static
Initial value:
=
{
  "NotSet",
  "before",
  "during",
  "before&during",
  "after",
  "before&after",
  "during&after",
  "before&during&after",
  NULL
}
XML recording activity names of plots known to COPASI.
Referenced by getActivity(), setActivity(), and setType().
XMLType
const char * CPlotItem::XMLType static
Initial value:
=
{
  "Unset",
  "Curve2D",
  "Histogram1DItem",
  "BandedGraph",
  "Surface",
  "Plot2D",
  "SimWiz",
  "Spectogram",
  NULL
}
XML sub type names of methods known to COPASI.
Referenced by PlotItemHandler::processStart(), PlotSpecificationHandler::processStart(), and CCopasiXML::savePlotList().
The documentation for this class was generated from the following files:
CPlotItem.h
CPlotItem.cpp