COPASI API: CInternalSolver Class Reference
CInternalSolver Class Reference
#include <CInternalSolver.h>
Classes
struct State
Public Member Functions
C_INT dintdy_ (double *t, const C_INT *k, double *yh, C_INT *nyh, double *dky, C_INT *iflag)
void enablePrint (const bool &print=true)
void resetState (const State &state)
void saveState (State &state) const
void setOstream (std::ostream &os)
~CInternalSolver ()
Protected Member Functions
CInternalSolver ()
C_INT dprja_ (C_INT *neq, double *y, double *yh, C_INT *nyh, double *ewt, double *ftem, double *savf, double *wm, C_INT *iwm, evalF f, evalJ jac)
C_INT drchek_ (const C_INT *job, evalG g, C_INT *neq, double *y, double *yh, C_INT *nyh, double *g0, double *g1, double *gx, C_INT *jroot, C_INT *irt)
C_INT droots_ (C_INT *ng, double *hmin, C_INT *jflag, double *x0, double *x1, double *g0, double *g1, double *gx, double *x, C_INT *jroot)
C_INT dsolsy_ (double *wm, C_INT *iwm, double *x, double *tem)
C_INT dstoda_ (C_INT *neq, double *y, double *yh, C_INT *nyh, double *yh1, double *ewt, double *savf, double *acor, double *wm, C_INT *iwm, evalF f, evalJ jac, PJAC *pjac, SLVS *slvs)
Protected Attributes
dls001 mdls001_
dlsa01 mdlsa01_
dlsr01 mdlsr01_
Cxerrwd mxerrwd
Constructor & Destructor Documentation
CInternalSolver()
CInternalSolver::CInternalSolver () protected
~CInternalSolver()
CInternalSolver::~CInternalSolver ()
Member Function Documentation
dintdy_()
C_INT CInternalSolver::dintdy_ (double * t, const C_INT * k, double * yh, C_INT * nyh, double * dky, C_INT * iflag)
References C_INT, d_sign(), dls001_1, mxerrwd, and pow_di.
Referenced by drchek_(), and CLsodaMethod2::evalRoot().
dprja_()
C_INT CInternalSolver::dprja_ (C_INT * neq, double * y, double * yh, C_INT * nyh, double * ewt, double * ftem, double * savf, double * wm, C_INT * iwm, evalF f, evalJ jac) protected
References C_INT, and dls001_1.
Referenced by CLSODA::CLSODA(), and CLSODAR::CLSODAR().
drchek_()
C_INT CInternalSolver::drchek_ (const C_INT * job, evalG g, C_INT * neq, double * y, double * yh, C_INT * nyh, double * g0, double * g1, double * gx, C_INT * jroot, C_INT * irt) protected
References C_INT, dintdy_(), dls001_1, dlsr01_1, and max.
droots_()
C_INT CInternalSolver::droots_ (C_INT * ng, double * hmin, C_INT * jflag, double * x0, double * x1, double * g0, double * g1, double * gx, double * x, C_INT * jroot) protected
References C_INT, d_sign(), and dlsr01_2.
dsolsy_()
C_INT CInternalSolver::dsolsy_ (double * wm, C_INT * iwm, double * x, double * tem) protected
References C_INT, dgesl_, and dls001_1.
Referenced by CLSODA::CLSODA(), and CLSODAR::CLSODAR().
dstoda_()
C_INT CInternalSolver::dstoda_ (C_INT * neq, double * y, double * yh, C_INT * nyh, double * yh1, double * ewt, double * savf, double * acor, double * wm, C_INT * iwm, evalF f, evalJ jac, PJAC * pjac, SLVS * slvs) protected
References C_INT, dcfode_(), dls001_3, and dlsa01_1.
enablePrint()
void CInternalSolver::enablePrint (const bool & print = true)
References Cxerrwd::enablePrint(), and mxerrwd.
resetState()
void CInternalSolver::resetState (const State & state)
References CInternalSolver::State::mdls001, mdls001_, CInternalSolver::State::mdlsa01, mdlsa01_, CInternalSolver::State::mdlsr01, and mdlsr01_.
Referenced by CLsodaMethod2::resetState(), CTimeSensLsodaMethod::resetState(), CLsodaMethod::resetState(), and CRadau5Method::resetState().
saveState()
void CInternalSolver::saveState (CInternalSolver::State & state) const
References CInternalSolver::State::mdls001, mdls001_, CInternalSolver::State::mdlsa01, mdlsa01_, CInternalSolver::State::mdlsr01, and mdlsr01_.
Referenced by CLsodaMethod2::saveState(), CTimeSensLsodaMethod::saveState(), CLsodaMethod::saveState(), and CRadau5Method::saveState().
setOstream()
void CInternalSolver::setOstream (std::ostream & os)
References mxerrwd, and Cxerrwd::setOstream().
Referenced by CLayoutEngine::CLayoutEngine(), CLyapWolfMethod::start(), CTimeSensLsodaMethod::start(), CLsodaMethod::start(), CLsodaMethod2::start(), and CRadau5Method::start().
Member Data Documentation
mdls001_
dls001 CInternalSolver::mdls001_ protected
Referenced by resetState(), and saveState().
mdlsa01_
dlsa01 CInternalSolver::mdlsa01_ protected
Referenced by resetState(), and saveState().
mdlsr01_
dlsr01 CInternalSolver::mdlsr01_ protected
Referenced by resetState(), and saveState().
mxerrwd
Cxerrwd CInternalSolver::mxerrwd protected
Referenced by dintdy_(), enablePrint(), CLSODA::operator()(), CLSODAR::operator()(), and setOstream().
The documentation for this class was generated from the following files:
CInternalSolver.h
CInternalSolver.cpp
dintdy.cpp
dprja.cpp
drcheck.cpp
dsolsy.cpp
dstoda.cpp