COPASI API: CMIRIAMInfo Class Reference
CMIRIAMInfo Class Reference
#include <CModelMIRIAMInfo.h>
Public Member Functions
bool addDefaultCreatedDT ()
CCreator * addDefaultCreator (bool force=false)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CMIRIAMInfo ()
CBiologicalDescription * createBiologicalDescription ()
CCreator * createCreator (const std::string &objectName)
CModification * createModification (const std::string &objectName)
CReference * createReference (const std::string &objectName)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
bool empty () const
CDataVector< CBiologicalDescription > & getBiologicalDescriptions ()
const CDataVector< CBiologicalDescription > & getBiologicalDescriptions () const
const std::string getCreatedDT () const
CDataVector< CCreator > & getCreators ()
const CDataVector< CCreator > & getCreators () const
virtual const std::string & getKey () const
CDataVector< CModification > & getModifications ()
const CDataVector< CModification > & getModifications () const
CRDFGraph * getRDFGraph ()
CDataVector< CReference > & getReferences ()
const CDataVector< CReference > & getReferences () const
void load (CDataContainer *pObject)
void loadBiologicalDescriptions ()
void loadCreators ()
void loadModifications ()
void loadReferences ()
bool removeBiologicalDescription (CBiologicalDescription *pBiologicalDescription)
bool removeCreator (CCreator *pCreator)
bool removeModification (CModification *pModified)
bool removeReference (CReference *pReference)
bool save ()
void setCreatedDT (const std::string &dt)
virtual CData toData () const
~CMIRIAMInfo ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Private Attributes
CDataVector< CBiologicalDescription > mBiologicalDescriptions
CRDFTriplet mCreated
CRDFObject mCreatedObj
CDataVector< CCreator > mCreators
CDataVector< CModification > mModifications
CAnnotation * mpAnnotation
CDataContainer * mpObject
CRDFGraph * mpRDFGraph
CDataVector< CReference > mReferences
CRDFTriplet mTriplet
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CMIRIAMInfo()
CMIRIAMInfo::CMIRIAMInfo ()
~CMIRIAMInfo()
CMIRIAMInfo::~CMIRIAMInfo ()
References CAnnotation::freeMiriamInfo(), mpObject, mpRDFGraph, and pdelete.
Member Function Documentation
addDefaultCreatedDT()
bool CMIRIAMInfo::addDefaultCreatedDT ()
References empty(), getCreatedDT(), setCreatedDT(), and UTCTimeStamp().
Referenced by CDataModel::commonAfterLoad().
addDefaultCreator()
CCreator * CMIRIAMInfo::addDefaultCreator (bool force = false)
SMethod to add a creator based on user preferences. If the preferences or not set NULL is returned
Returns
CCreator * pCreator
References createCreator(), CDataVector< CType >::empty(), empty(), CRootContainer::getConfiguration(), getCreatedDT(), CConfigurationFile::getCurrentAuthorEmail(), CConfigurationFile::getCurrentAuthorFamilyName(), CConfigurationFile::getCurrentAuthorGivenName(), CConfigurationFile::getCurrentAuthorOrganization(), mCreators, CCreator::setEmail(), CCreator::setFamilyName(), CCreator::setGivenName(), and CCreator::setORG().
Referenced by CDataModel::commonAfterLoad().
applyData()
bool CMIRIAMInfo::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CDataContainer::applyData(), CData::DATE, CData::getProperty(), CData::isSetProperty(), save(), setCreatedDT(), and CDataValue::toString().
createBiologicalDescription()
CBiologicalDescription * CMIRIAMInfo::createBiologicalDescription ()
References CDataVector< CType >::add(), CRDFGraph::addTriplet(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), mBiologicalDescriptions, mpRDFGraph, CRDFObject::RESOURCE, CRDFObject::setResource(), and CRDFObject::setType().
Referenced by CBiologicalDescription::fromData(), and SBMLImporter::importMIRIAM().
createCreator()
CCreator * CMIRIAMInfo::createCreator (const std::string & objectName)
References CDataVector< CType >::add(), CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_creator, CRDFGraph::generatedNodeId(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mCreators, mpRDFGraph, CRDFObject::setBlankNodeId(), and CRDFObject::setType().
Referenced by addDefaultCreator(), and CCreator::fromData().
createModification()
CModification * CMIRIAMInfo::createModification (const std::string & objectName)
References CDataVector< CType >::add(), CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_modified, CRDFGraph::generatedNodeId(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mModifications, mpRDFGraph, CRDFObject::setBlankNodeId(), CModification::setDate(), and CRDFObject::setType().
Referenced by CModification::fromData().
createReference()
CReference * CMIRIAMInfo::createReference (const std::string & objectName)
References CDataVector< CType >::add(), CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_bibliographicCitation, CRDFGraph::generatedNodeId(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mpRDFGraph, mReferences, CRDFObject::setBlankNodeId(), and CRDFObject::setType().
Referenced by CReference::fromData().
createUndoData()
void CMIRIAMInfo::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CUndoData::addProperty(), CUndoData::CHANGE, CDataContainer::createUndoData(), CData::DATE, getCreatedDT(), and CData::getProperty().
empty()
bool CMIRIAMInfo::empty () const
References CRDFGraph::empty(), and mpRDFGraph.
Referenced by addDefaultCreatedDT(), addDefaultCreator(), and CSBMLExporter::updateMIRIAMAnnotation().
getBiologicalDescriptions() [1/2]
CDataVector< CBiologicalDescription > & CMIRIAMInfo::getBiologicalDescriptions ()
References mBiologicalDescriptions.
Referenced by SBMLImporter::importMIRIAM(), and CSBMLExporter::updateMIRIAMAnnotation().
getBiologicalDescriptions() [2/2]
const CDataVector< CBiologicalDescription > & CMIRIAMInfo::getBiologicalDescriptions () const
References mBiologicalDescriptions.
getCreatedDT()
const std::string CMIRIAMInfo::getCreatedDT () const
References CRDFPredicate::dcterms_W3CDTF, CRDFNode::getFieldValue(), mCreated, and CRDFTriplet::pObject.
Referenced by addDefaultCreatedDT(), addDefaultCreator(), createUndoData(), toData(), and CSBMLExporter::updateMIRIAMAnnotation().
getCreators() [1/2]
CDataVector< CCreator > & CMIRIAMInfo::getCreators ()
References mCreators.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
getCreators() [2/2]
const CDataVector< CCreator > & CMIRIAMInfo::getCreators () const
References mCreators.
getKey()
const std::string & CMIRIAMInfo::getKey () const virtual
Reimplemented from CDataObject.
References CDataObject::getKey(), CAnnotation::getKey(), and mpAnnotation.
getModifications() [1/2]
CDataVector< CModification > & CMIRIAMInfo::getModifications ()
References mModifications.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
getModifications() [2/2]
const CDataVector< CModification > & CMIRIAMInfo::getModifications () const
References mModifications.
getRDFGraph()
CRDFGraph * CMIRIAMInfo::getRDFGraph ()
References mpRDFGraph.
getReferences() [1/2]
CDataVector< CReference > & CMIRIAMInfo::getReferences ()
References mReferences.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
getReferences() [2/2]
const CDataVector< CReference > & CMIRIAMInfo::getReferences () const
References mReferences.
load()
void CMIRIAMInfo::load (CDataContainer * pObject)
References CDataContainer::add(), CAnnotation::castObject(), CRDFGraph::createAboutNode(), CRDFPredicate::dcterms_created, CRDFNode::getDescendantsWithPredicate(), CDataObject::getKey(), CAnnotation::getMiriamAnnotation(), CDataObject::getObjectParent(), CRDFNode::getPath(), CRDFParser::graphFromXml(), loadBiologicalDescriptions(), loadCreators(), loadModifications(), loadReferences(), mCreated, mpAnnotation, mpObject, mpRDFGraph, mTriplet, pdelete, and CRDFTriplet::pObject.
Referenced by CDataModel::commonAfterLoad(), SBMLImporter::importMIRIAM(), and CSBMLExporter::updateMIRIAMAnnotation().
loadBiologicalDescriptions()
void CMIRIAMInfo::loadBiologicalDescriptions ()
References CDataVector< CType >::add(), CRDFPredicate::bqbiol_encodes, CRDFPredicate::bqbiol_hasPart, CRDFPredicate::bqbiol_hasProperty, CRDFPredicate::bqbiol_hasTaxon, CRDFPredicate::bqbiol_hasVersion, CRDFPredicate::bqbiol_is, CRDFPredicate::bqbiol_isEncodedBy, CRDFPredicate::bqbiol_isHomologTo, CRDFPredicate::bqbiol_isPartOf, CRDFPredicate::bqbiol_isPropertyOf, CRDFPredicate::bqbiol_isVersionOf, CRDFPredicate::bqbiol_occursIn, CRDFPredicate::bqmodel_hasInstance, CRDFPredicate::bqmodel_is, CRDFPredicate::bqmodel_isDerivedFrom, CRDFPredicate::bqmodel_isInstanceOf, CDataVector< CType >::cleanup(), CRDFPredicate::copasi_encodes, CRDFPredicate::copasi_hasPart, CRDFPredicate::copasi_hasVersion, CRDFPredicate::copasi_is, CRDFPredicate::copasi_isDescribedBy, CRDFPredicate::copasi_isEncodedBy, CRDFPredicate::copasi_isHomologTo, CRDFPredicate::copasi_isPartOf, CRDFPredicate::copasi_isVersionOf, CRDFPredicate::copasi_occursIn, CRDFPredicate::end, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), CMIRIAMResources::isCitation(), mBiologicalDescriptions, mTriplet, CRDFTriplet::pObject, and CRDFPredicate::unknown.
Referenced by load().
loadCreators()
void CMIRIAMInfo::loadCreators ()
References CDataVector< CType >::add(), CDataVector< CType >::cleanup(), CRDFPredicate::dc_creator, CRDFPredicate::dcterms_creator, CRDFPredicate::end, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), mCreators, mTriplet, and CRDFTriplet::pObject.
Referenced by load().
loadModifications()
void CMIRIAMInfo::loadModifications ()
References CDataVector< CType >::add(), CDataVector< CType >::cleanup(), CRDFPredicate::dcterms_modified, CRDFNode::getDescendantsWithPredicate(), mModifications, mTriplet, and CRDFTriplet::pObject.
Referenced by load().
loadReferences()
void CMIRIAMInfo::loadReferences ()
References CDataVector< CType >::add(), CRDFPredicate::bqbiol_isDescribedBy, CRDFPredicate::bqmodel_isDescribedBy, CDataVector< CType >::cleanup(), CRDFPredicate::dcterms_bibliographicCitation, CRDFPredicate::end, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), mReferences, mTriplet, and CRDFTriplet::pObject.
Referenced by load().
removeBiologicalDescription()
bool CMIRIAMInfo::removeBiologicalDescription (CBiologicalDescription * pBiologicalDescription)
References CBiologicalDescription::getTriplet(), mBiologicalDescriptions, mpRDFGraph, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CDataVector< CType >::remove(), and CRDFGraph::removeTriplet().
Referenced by CBiologicalDescription::destruct().
removeCreator()
bool CMIRIAMInfo::removeCreator (CCreator * pCreator)
References CCreator::getTriplet(), CRDFPredicate::getURI(), mCreators, mpRDFGraph, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CDataVector< CType >::remove(), and CRDFGraph::removeTriplet().
Referenced by CCreator::destruct().
removeModification()
bool CMIRIAMInfo::removeModification (CModification * pModified)
References CModification::getTriplet(), CRDFPredicate::getURI(), mModifications, mpRDFGraph, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CDataVector< CType >::remove(), and CRDFGraph::removeTriplet().
Referenced by CModification::destruct().
removeReference()
bool CMIRIAMInfo::removeReference (CReference * pReference)
References CReference::getTriplet(), CRDFPredicate::getURI(), mpRDFGraph, mReferences, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CDataVector< CType >::remove(), and CRDFGraph::removeTriplet().
Referenced by CReference::destruct().
save()
bool CMIRIAMInfo::save ()
References CRDFGraph::clean(), CAnnotation::getKey(), mpAnnotation, mpRDFGraph, CAnnotation::setMiriamAnnotation(), CRDFGraph::updateNamespaces(), and CRDFWriter::xmlFromGraph().
Referenced by CBiologicalDescription::applyData(), CCreator::applyData(), applyData(), CModification::applyData(), CReference::applyData(), CDataModel::commonAfterLoad(), CBiologicalDescription::destruct(), CCreator::destruct(), CModification::destruct(), CReference::destruct(), and SBMLImporter::importMIRIAM().
setCreatedDT()
void CMIRIAMInfo::setCreatedDT (const std::string & dt)
References CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_created, CRDFPredicate::dcterms_W3CDTF, CRDFGraph::generatedNodeId(), CRDFNode::getPath(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mCreated, mpRDFGraph, mTriplet, CRDFTriplet::pObject, CRDFObject::setBlankNodeId(), CRDFNode::setFieldValue(), and CRDFObject::setType().
Referenced by addDefaultCreatedDT(), and applyData().
toData()
CData CMIRIAMInfo::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::addProperty(), CData::DATE, getCreatedDT(), and CDataContainer::toData().
Member Data Documentation
mBiologicalDescriptions
CDataVector<CBiologicalDescription> CMIRIAMInfo::mBiologicalDescriptions private
Referenced by createBiologicalDescription(), getBiologicalDescriptions(), loadBiologicalDescriptions(), and removeBiologicalDescription().
mCreated
CRDFTriplet CMIRIAMInfo::mCreated private
Referenced by getCreatedDT(), load(), and setCreatedDT().
mCreatedObj
CRDFObject CMIRIAMInfo::mCreatedObj private
mCreators
CDataVector<CCreator> CMIRIAMInfo::mCreators private
Referenced by addDefaultCreator(), createCreator(), getCreators(), loadCreators(), and removeCreator().
mModifications
CDataVector<CModification> CMIRIAMInfo::mModifications private
Referenced by createModification(), getModifications(), loadModifications(), and removeModification().
mpAnnotation
CAnnotation* CMIRIAMInfo::mpAnnotation private
Referenced by getKey(), load(), and save().
mpObject
CDataContainer* CMIRIAMInfo::mpObject private
Referenced by load(), and ~CMIRIAMInfo().
mpRDFGraph
CRDFGraph* CMIRIAMInfo::mpRDFGraph private
Referenced by createBiologicalDescription(), createCreator(), createModification(), createReference(), empty(), getRDFGraph(), load(), removeBiologicalDescription(), removeCreator(), removeModification(), removeReference(), save(), setCreatedDT(), and ~CMIRIAMInfo().
mReferences
CDataVector<CReference> CMIRIAMInfo::mReferences private
Referenced by createReference(), getReferences(), loadReferences(), and removeReference().
mTriplet
CRDFTriplet CMIRIAMInfo::mTriplet private
Referenced by load(), loadBiologicalDescriptions(), loadCreators(), loadModifications(), loadReferences(), and setCreatedDT().
The documentation for this class was generated from the following files:
CModelMIRIAMInfo.h
CModelMIRIAMInfo.cpp