COPASI API: CBaseUnit Class Reference
CBaseUnit Class Reference
#include <CBaseUnit.h>
Public Types
enum Kind {
dimensionless = 0 , meter , gram , second ,
ampere , kelvin , item , candela ,
avogadro , undefined
}
enum Scale {
yocto = -24 , zepto = -21 , atto = -18 , femto = -15 ,
pico = -12 , nano = -9 , micro = -6 , milli = -3 ,
centi = -2 , deci = -1 , zero = 0 , hecto = 2 ,
kilo = 3 , mega = 6 , giga = 9 , tera = 12 ,
peta = 15 , exa = 18 , zetta = 21 , yotta = 24
}
Static Public Member Functions
static Kind fromSymbol (const std::string &symbol)
static const std::string getSymbol (Kind kind)
static std::string prefixFromScale (int scale)
static Scale scaleFromPrefix (const std::string &prefix)
Static Private Attributes
static const char * Name []
Member Enumeration Documentation
Kind
enum CBaseUnit::Kind
Enumerator
dimensionless
meter
gram
second
ampere
kelvin
item
candela
avogadro
undefined
Scale
enum CBaseUnit::Scale
Enumerator
yocto
zepto
atto
femto
pico
nano
micro
milli
centi
deci
zero
hecto
kilo
mega
giga
tera
peta
exa
zetta
yotta
Member Function Documentation
fromSymbol()
CBaseUnit::Kind CBaseUnit::fromSymbol (const std::string & symbol) static
References ampere, avogadro, candela, dimensionless, gram, item, kelvin, meter, second, and undefined.
Referenced by CUnit::getExponentOfSymbol().
getSymbol()
const std::string CBaseUnit::getSymbol (Kind kind) static
References ampere, avogadro, candela, dimensionless, gram, item, kelvin, meter, second, and undefined.
Referenced by CUnit::CUnit(), and CUnit::getSymbolComponents().
prefixFromScale()
std::string CBaseUnit::prefixFromScale (int scale) static
References atto, centi, deci, exa, femto, giga, hecto, kilo, mega, micro, milli, nano, peta, pico, tera, yocto, yotta, zepto, zero, and zetta.
Referenced by CUnit::buildExpression().
scaleFromPrefix()
CBaseUnit::Scale CBaseUnit::scaleFromPrefix (const std::string & prefix) static
References atto, centi, deci, exa, femto, giga, hecto, kilo, mega, micro, milli, nano, peta, pico, tera, yocto, yotta, zepto, zero, and zetta.
Referenced by addSymbolComponentToUnitDefinition().
Member Data Documentation
Name
const char * CBaseUnit::Name static private
Initial value:
=
{
  "dimensionless",
  "meter",
  "gram",
  "second",
  "Ampere",
  "Kelvin",
  "item",
  "Candela",
  "Avogadro",
  NULL
}
The documentation for this class was generated from the following files:
CBaseUnit.h
CBaseUnit.cpp