COPASI API: CNL2SOL.cpp File Reference
CNL2SOL.cpp File Reference
#include <cfloat>
#include <climits>
#include <cmath>
#include "copasi/copasi.h"
#include "CNL2SOL.h"
Functions
doublereal d1mach_ (integer *i)
int da7sst_ (integer *iv, integer *liv, integer *lv, doublereal *v)
int dd7mlp_ (integer *n, doublereal *x, doublereal *y, doublereal *z__, integer *k)
doublereal dd7tpr_ (integer *p, doublereal *x, doublereal *y)
int dd7upd_ (doublereal *d__, doublereal *dr, integer *iv, integer *liv, integer *lv, integer *n, integer *nd, integer *nn, integer *n2, integer *p, doublereal *v)
int df7dhb_ (doublereal *b, doublereal *d__, doublereal *g, integer *irt, integer *iv, integer *liv, integer *lv, integer *p, doublereal *v, doublereal *x)
int dg7itb_ (doublereal *b, doublereal *d__, doublereal *g, integer *iv, integer *liv, integer *lv, integer *p, integer *ps, doublereal *v, doublereal *x, doublereal *y)
int dg7qsb_ (doublereal *b, doublereal *d__, doublereal *dihdi, doublereal *g, integer *ipiv, integer *ipiv1, integer *ipiv2, integer *ka, doublereal *l, integer *lv, integer *p, integer *p0, integer *pc, doublereal *step, doublereal *td, doublereal *tg, doublereal *v, doublereal *w, doublereal *x, doublereal *x0)
int dg7qts_ (doublereal *d__, doublereal *dig, doublereal *dihdi, integer *ka, doublereal *l, integer *p, doublereal *step, doublereal *v, doublereal *w)
int dh2rfa_ (integer *n, doublereal *a, doublereal *b, doublereal *x, doublereal *y, doublereal *z__)
doublereal dh2rfg_ (doublereal *a, doublereal *b, doublereal *x, doublereal *y, doublereal *z__)
int divset_ (integer *alg, integer *iv, integer *liv, integer *lv, doublereal *v)
int dl7itv_ (integer *n, doublereal *x, doublereal *l, doublereal *y)
int dl7ivm_ (integer *n, doublereal *x, doublereal *l, doublereal *y)
int dl7msb_ (doublereal *b, doublereal *d__, doublereal *g, integer *ierr, integer *ipiv, integer *ipiv1, integer *ipiv2, integer *ka, doublereal *lmat, integer *lv, integer *p, integer *p0, integer *pc, doublereal *qtr, doublereal *rmat, doublereal *step, doublereal *td, doublereal *tg, doublereal *v, doublereal *w, doublereal *wlm, doublereal *x, doublereal *x0)
int dl7mst_ (doublereal *d__, doublereal *g, integer *ierr, integer *ipivot, integer *ka, integer *p, doublereal *qtr, doublereal *r__, doublereal *step, doublereal *v, doublereal *w)
int dl7sqr_ (integer *n, doublereal *a, doublereal *l)
int dl7srt_ (integer *n1, integer *n, doublereal *l, doublereal *a, integer *irc)
doublereal dl7svn_ (integer *p, doublereal *l, doublereal *x, doublereal *y)
int dl7tvm_ (integer *n, doublereal *x, doublereal *l, doublereal *y)
int dl7vml_ (integer *n, doublereal *x, doublereal *l, doublereal *y)
int dparck_ (integer *alg, doublereal *d__, integer *iv, integer *liv, integer *lv, integer *n, doublereal *v)
int dq7apl_ (integer *nn, integer *n, integer *p, doublereal *j, doublereal *r__, integer *ierr)
int dq7rad_ (integer *n, integer *nn, integer *p, doublereal *qtr, logical *qtrset, doublereal *rmat, doublereal *w, doublereal *y)
int dq7rsh_ (integer *k, integer *p, logical *havqtr, doublereal *qtr, doublereal *r__, doublereal *w)
doublereal dr7mdc_ (integer *k)
int dr7tvm_ (integer *n, integer *p, doublereal *y, doublereal *d__, doublereal *u, doublereal *x)
doublereal drldst_ (integer *p, doublereal *d__, doublereal *x, doublereal *x0)
int drn2gb_ (doublereal *b, doublereal *d__, doublereal *dr, integer *iv, integer *liv, integer *lv, integer *n, integer *nd, integer *n1, integer *n2, integer *p, doublereal *r__, doublereal *rd, doublereal *v, doublereal *x)
int ds7bqn_ (doublereal *b, doublereal *d__, doublereal *dst, integer *ipiv, integer *ipiv1, integer *ipiv2, integer *kb, doublereal *l, integer *lv, integer *ns, integer *p, integer *p1, doublereal *step, doublereal *td, doublereal *tg, doublereal *v, doublereal *w, doublereal *x, doublereal *x0)
int ds7dmp_ (integer *n, doublereal *x, doublereal *y, doublereal *z__, integer *k)
int ds7ipr_ (integer *p, integer *ip, doublereal *h__)
int ds7lup_ (doublereal *a, doublereal *cosmin, integer *p, doublereal *size, doublereal *step, doublereal *u, doublereal *w, doublereal *wchmtd, doublereal *wscale, doublereal *y)
int ds7lvm_ (integer *p, doublereal *y, doublereal *s, doublereal *x)
int dv2axy_ (integer *p, doublereal *w, doublereal *a, doublereal *x, doublereal *y)
doublereal dv2nrm_ (integer *p, doublereal *x)
int dv7cpy_ (integer *p, doublereal *y, doublereal *x)
int dv7dfl_ (integer *alg, integer *lv, doublereal *v)
int dv7ipr_ (integer *n, integer *ip, doublereal *x)
int dv7scl_ (integer *n, doublereal *x, doublereal *a, doublereal *y)
int dv7scp_ (integer *p, doublereal *y, doublereal *s)
int dv7shf_ (integer *n, integer *k, doublereal *x)
int dv7vmp_ (integer *n, doublereal *x, doublereal *y, doublereal *z__, integer *k)
integer i1mach_ (integer *i)
int i7copy_ (integer *p, integer *y, integer *x)
integer i7mdcn_ (integer *k)
int i7pnvr_ (integer *n, integer *x, integer *y)
int i7shft_ (integer *n, integer *k, integer *x)
doublereal pow_dd (doublereal *ap, doublereal *bp)
int s_copy (char *a, char *b, ftnlen la, ftnlen lb)
logical stopx_ (integer *idummy)
Function Documentation
d1mach_()
doublereal d1mach_ (integer * i)
Referenced by dr7mdc_().
da7sst_()
int da7sst_ (integer * iv, integer * liv, integer * lv, doublereal * v)
References FALSE_, and TRUE_.
Referenced by dg7itb_().
dd7mlp_()
int dd7mlp_ (integer * n, doublereal * x, doublereal * y, doublereal * z__, integer * k)
Referenced by dl7msb_().
dd7tpr_()
doublereal dd7tpr_ (integer * p, doublereal * x, doublereal * y)
References dr7mdc_().
Referenced by dg7itb_(), dg7qsb_(), dg7qts_(), dl7ivm_(), dl7msb_(), dl7mst_(), dl7svn_(), dq7apl_(), dq7rad_(), dr7tvm_(), drn2gb_(), ds7bqn_(), ds7lup_(), and ds7lvm_().
dd7upd_()
int dd7upd_ (doublereal * d__, doublereal * dr, integer * iv, integer * liv, integer * lv, integer * n, integer * nd, integer * nn, integer * n2, integer * p, doublereal * v)
References abs, and dv7scp_().
Referenced by drn2gb_().
df7dhb_()
int df7dhb_ (doublereal * b, doublereal * d__, doublereal * g, integer * irt, integer * iv, integer * liv, integer * lv, integer * p, doublereal * v, doublereal * x)
References abs, dv7cpy_(), and dv7scp_().
Referenced by dg7itb_().
dg7itb_()
int dg7itb_ (doublereal * b, doublereal * d__, doublereal * g, integer * iv, integer * liv, integer * lv, integer * p, integer * ps, doublereal * v, doublereal * x, doublereal * y)
References da7sst_(), dd7tpr_(), df7dhb_(), dg7qsb_(), dl7msb_(), dl7sqr_(), dl7tvm_(), dl7vml_(), dparck_(), dq7rsh_(), drldst_(), ds7dmp_(), ds7ipr_(), ds7lup_(), ds7lvm_(), dv2axy_(), dv2nrm_(), dv7cpy_(), dv7ipr_(), dv7scp_(), dv7vmp_(), i7copy_(), i7pnvr_(), i7shft_(), and stopx_().
Referenced by drn2gb_().
dg7qsb_()
int dg7qsb_ (doublereal * b, doublereal * d__, doublereal * dihdi, doublereal * g, integer * ipiv, integer * ipiv1, integer * ipiv2, integer * ka, doublereal * l, integer * lv, integer * p, integer * p0, integer * pc, doublereal * step, doublereal * td, doublereal * tg, doublereal * v, doublereal * w, doublereal * x, doublereal * x0)
References dd7tpr_(), dg7qts_(), ds7bqn_(), ds7ipr_(), dv7cpy_(), dv7ipr_(), dv7scp_(), and dv7vmp_().
Referenced by dg7itb_().
dg7qts_()
int dg7qts_ (doublereal * d__, doublereal * dig, doublereal * dihdi, integer * ka, doublereal * l, integer * p, doublereal * step, doublereal * v, doublereal * w)
References dd7tpr_(), dl7itv_(), dl7ivm_(), dl7srt_(), dl7svn_(), dr7mdc_(), and dv2nrm_().
Referenced by dg7qsb_().
dh2rfa_()
int dh2rfa_ (integer * n, doublereal * a, doublereal * b, doublereal * x, doublereal * y, doublereal * z__)
Referenced by dq7rsh_().
dh2rfg_()
doublereal dh2rfg_ (doublereal * a, doublereal * b, doublereal * x, doublereal * y, doublereal * z__)
Referenced by dq7rsh_().
divset_()
int divset_ (integer * alg, integer * iv, integer * liv, integer * lv, doublereal * v)
References dv7dfl_(), and i7mdcn_().
Referenced by CNL2SOL::divset_N(), CNL2SOL::dn2fb_(), dparck_(), and drn2gb_().
dl7itv_()
int dl7itv_ (integer * n, doublereal * x, doublereal * l, doublereal * y)
Referenced by dg7qts_(), dl7mst_(), and ds7bqn_().
dl7ivm_()
int dl7ivm_ (integer * n, doublereal * x, doublereal * l, doublereal * y)
References dd7tpr_().
Referenced by dg7qts_(), dl7mst_(), and ds7bqn_().
dl7msb_()
int dl7msb_ (doublereal * b, doublereal * d__, doublereal * g, integer * ierr, integer * ipiv, integer * ipiv1, integer * ipiv2, integer * ka, doublereal * lmat, integer * lv, integer * p, integer * p0, integer * pc, doublereal * qtr, doublereal * rmat, doublereal * step, doublereal * td, doublereal * tg, doublereal * v, doublereal * w, doublereal * wlm, doublereal * x, doublereal * x0)
References dd7mlp_(), dd7tpr_(), dl7mst_(), dl7tvm_(), dq7rsh_(), ds7bqn_(), dv2axy_(), dv7cpy_(), dv7ipr_(), dv7scp_(), and dv7vmp_().
Referenced by dg7itb_().
dl7mst_()
int dl7mst_ (doublereal * d__, doublereal * g, integer * ierr, integer * ipivot, integer * ka, integer * p, doublereal * qtr, doublereal * r__, doublereal * step, doublereal * v, doublereal * w)
References dd7tpr_(), dl7itv_(), dl7ivm_(), dl7svn_(), dr7mdc_(), dv2nrm_(), and dv7cpy_().
Referenced by dl7msb_().
dl7sqr_()
int dl7sqr_ (integer * n, doublereal * a, doublereal * l)
Referenced by dg7itb_().
dl7srt_()
int dl7srt_ (integer * n1, integer * n, doublereal * l, doublereal * a, integer * irc)
Referenced by dg7qts_().
dl7svn_()
doublereal dl7svn_ (integer * p, doublereal * l, doublereal * x, doublereal * y)
References dd7tpr_(), dv2axy_(), and dv2nrm_().
Referenced by dg7qts_(), and dl7mst_().
dl7tvm_()
int dl7tvm_ (integer * n, doublereal * x, doublereal * l, doublereal * y)
Referenced by dg7itb_(), and dl7msb_().
dl7vml_()
int dl7vml_ (integer * n, doublereal * x, doublereal * l, doublereal * y)
Referenced by dg7itb_(), and drn2gb_().
dparck_()
int dparck_ (integer * alg, doublereal * d__, integer * iv, integer * liv, integer * lv, integer * n, doublereal * v)
References divset_(), dr7mdc_(), dv7cpy_(), dv7dfl_(), max, and s_copy().
Referenced by dg7itb_().
dq7apl_()
int dq7apl_ (integer * nn, integer * n, integer * p, doublereal * j, doublereal * r__, integer * ierr)
References abs, dd7tpr_(), dv2axy_(), and nn.
Referenced by drn2gb_().
dq7rad_()
int dq7rad_ (integer * n, integer * nn, integer * p, doublereal * qtr, logical * qtrset, doublereal * rmat, doublereal * w, doublereal * y)
References dd7tpr_(), dr7mdc_(), dv2axy_(), dv2nrm_(), dv7scl_(), and nn.
Referenced by drn2gb_().
dq7rsh_()
int dq7rsh_ (integer * k, integer * p, logical * havqtr, doublereal * qtr, doublereal * r__, doublereal * w)
References dh2rfa_(), dh2rfg_(), and dv7cpy_().
Referenced by dg7itb_(), dl7msb_(), and ds7bqn_().
dr7mdc_()
doublereal dr7mdc_ (integer * k)
References d1mach_().
Referenced by dd7tpr_(), dg7qts_(), dl7mst_(), dparck_(), dq7rad_(), ds7bqn_(), dv2nrm_(), and dv7dfl_().
dr7tvm_()
int dr7tvm_ (integer * n, integer * p, doublereal * y, doublereal * d__, doublereal * u, doublereal * x)
References dd7tpr_(), and min.
Referenced by drn2gb_().
drldst_()
doublereal drldst_ (integer * p, doublereal * d__, doublereal * x, doublereal * x0)
Referenced by dg7itb_().
drn2gb_()
int drn2gb_ (doublereal * b, doublereal * d__, doublereal * dr, integer * iv, integer * liv, integer * lv, integer * n, integer * nd, integer * n1, integer * n2, integer * p, doublereal * r__, doublereal * rd, doublereal * v, doublereal * x)
References dd7tpr_(), dd7upd_(), dg7itb_(), divset_(), dl7vml_(), dq7apl_(), dq7rad_(), dr7tvm_(), dv2nrm_(), dv7cpy_(), dv7scp_(), and nn.
Referenced by CNL2SOL::dn2fb_().
ds7bqn_()
int ds7bqn_ (doublereal * b, doublereal * d__, doublereal * dst, integer * ipiv, integer * ipiv1, integer * ipiv2, integer * kb, doublereal * l, integer * lv, integer * ns, integer * p, integer * p1, doublereal * step, doublereal * td, doublereal * tg, doublereal * v, doublereal * w, doublereal * x, doublereal * x0)
References dd7tpr_(), dl7itv_(), dl7ivm_(), dq7rsh_(), dr7mdc_(), dv2axy_(), dv2nrm_(), dv7cpy_(), dv7ipr_(), dv7scp_(), dv7shf_(), and i7shft_().
Referenced by dg7qsb_(), and dl7msb_().
ds7dmp_()
int ds7dmp_ (integer * n, doublereal * x, doublereal * y, doublereal * z__, integer * k)
Referenced by dg7itb_().
ds7ipr_()
int ds7ipr_ (integer * p, integer * ip, doublereal * h__)
References abs.
Referenced by dg7itb_(), and dg7qsb_().
ds7lup_()
int ds7lup_ (doublereal * a, doublereal * cosmin, integer * p, doublereal * size, doublereal * step, doublereal * u, doublereal * w, doublereal * wchmtd, doublereal * wscale, doublereal * y)
References dd7tpr_(), ds7lvm_(), and dv2nrm_().
Referenced by dg7itb_().
ds7lvm_()
int ds7lvm_ (integer * p, doublereal * y, doublereal * s, doublereal * x)
References dd7tpr_().
Referenced by dg7itb_(), and ds7lup_().
dv2axy_()
int dv2axy_ (integer * p, doublereal * w, doublereal * a, doublereal * x, doublereal * y)
Referenced by dg7itb_(), dl7msb_(), dl7svn_(), dq7apl_(), dq7rad_(), and ds7bqn_().
dv2nrm_()
doublereal dv2nrm_ (integer * p, doublereal * x)
References dr7mdc_().
Referenced by dg7itb_(), dg7qts_(), dl7mst_(), dl7svn_(), dq7rad_(), drn2gb_(), ds7bqn_(), and ds7lup_().
dv7cpy_()
int dv7cpy_ (integer * p, doublereal * y, doublereal * x)
Referenced by df7dhb_(), dg7itb_(), dg7qsb_(), dl7msb_(), dl7mst_(), dparck_(), dq7rsh_(), drn2gb_(), and ds7bqn_().
dv7dfl_()
int dv7dfl_ (integer * alg, integer * lv, doublereal * v)
References dr7mdc_().
Referenced by divset_(), and dparck_().
dv7ipr_()
int dv7ipr_ (integer * n, integer * ip, doublereal * x)
Referenced by dg7itb_(), dg7qsb_(), dl7msb_(), and ds7bqn_().
dv7scl_()
int dv7scl_ (integer * n, doublereal * x, doublereal * a, doublereal * y)
Referenced by dq7rad_().
dv7scp_()
int dv7scp_ (integer * p, doublereal * y, doublereal * s)
Referenced by dd7upd_(), df7dhb_(), dg7itb_(), dg7qsb_(), dl7msb_(), CNL2SOL::dn2fb_(), drn2gb_(), and ds7bqn_().
dv7shf_()
int dv7shf_ (integer * n, integer * k, doublereal * x)
Referenced by ds7bqn_().
dv7vmp_()
int dv7vmp_ (integer * n, doublereal * x, doublereal * y, doublereal * z__, integer * k)
Referenced by dg7itb_(), dg7qsb_(), and dl7msb_().
i1mach_()
integer i1mach_ (integer * i)
References max.
Referenced by i7mdcn_().
i7copy_()
int i7copy_ (integer * p, integer * y, integer * x)
Referenced by dg7itb_().
i7mdcn_()
integer i7mdcn_ (integer * k)
References i1mach_().
Referenced by divset_().
i7pnvr_()
int i7pnvr_ (integer * n, integer * x, integer * y)
Referenced by dg7itb_().
i7shft_()
int i7shft_ (integer * n, integer * k, integer * x)
Referenced by dg7itb_(), and ds7bqn_().
pow_dd()
doublereal pow_dd (doublereal * ap, doublereal * bp)
s_copy()
int s_copy (char * a, char * b, ftnlen la, ftnlen lb)
Referenced by dparck_().
stopx_()
logical stopx_ (integer * idummy)
References FALSE_.
Referenced by dg7itb_().