COPASI API: CMathHistoryCore Class Reference
CMathHistoryCore Class Reference
#include <CMathHistory.h>
Public Member Functions
C_FLOAT64 * array ()
const C_FLOAT64 * array () const
CMathHistoryCore (const size_t &rows=0, const size_t &cols=0, const size_t &colsAllocated=0, C_FLOAT64 *pArray=NULL)
const size_t & cols () const
const size_t & colsAllocated () const
const CVectorCore< C_FLOAT64 > & getRow (const size_t &row)
void initialize (const CMathHistoryCore &src)
void initialize (const size_t &rows, const size_t &cols, const size_t &colsAllocated, C_FLOAT64 *pArray)
CMathHistoryCore & operator= (const CMathHistoryCore &rhs)
C_FLOAT64 * operator[] (const size_t &row)
const size_t & rows () const
void setRow (const size_t &row, const CVectorCore< C_FLOAT64 > &values)
const size_t & size () const
virtual ~CMathHistoryCore ()
Protected Attributes
size_t mCols
size_t mColsAllocated
size_t mRows
Protected Attributes inherited from CVectorCore< C_FLOAT64 >
C_FLOAT64 * mpBuffer
size_t mSize
Private Member Functions
CMathHistoryCore (const CMathHistoryCore &src)
Additional Inherited Members
Protected Types inherited from CVectorCore< C_FLOAT64 >
typedef C_FLOAT64 elementType
Protected Member Functions inherited from CVectorCore< C_FLOAT64 >
bool applyPivot (const CVectorCore< size_t > &pivot)
C_FLOAT64 * array ()
const C_FLOAT64 * array () const
C_FLOAT64 * begin ()
const C_FLOAT64 * begin () const
CVectorCore (const size_t &size=0, C_FLOAT64 *buffer=NULL)
C_FLOAT64 * end ()
const C_FLOAT64 * end () const
void initialize (const CVectorCore< C_FLOAT64 > &src)
void initialize (const size_t &size, const C_FLOAT64 *vector)
C_FLOAT64 & operator() (const size_t &row)
const C_FLOAT64 & operator() (const size_t &row) const
CVectorCore< C_FLOAT64 > & operator= (const C_FLOAT64 &value)
CVectorCore< C_FLOAT64 > & operator= (const CVectorCore< C_FLOAT64 > &rhs)
bool operator== (const CVectorCore< C_FLOAT64 > &rhs) const
C_FLOAT64 & operator[] (const size_t &row)
const C_FLOAT64 & operator[] (const size_t &row) const
size_t size () const
virtual ~CVectorCore ()
Constructor & Destructor Documentation
CMathHistoryCore() [1/2]
CMathHistoryCore::CMathHistoryCore (const size_t & rows = 0, const size_t & cols = 0, const size_t & colsAllocated = 0, C_FLOAT64 * pArray = NULL)
References cols(), and colsAllocated().
CMathHistoryCore() [2/2]
CMathHistoryCore::CMathHistoryCore (const CMathHistoryCore & src) private
~CMathHistoryCore()
CMathHistoryCore::~CMathHistoryCore () virtual
Member Function Documentation
array() [1/2]
C_FLOAT64 * CMathHistoryCore::array ()
References CVectorCore< C_FLOAT64 >::mpBuffer.
Referenced by CMathHistory::copy(), and CMathContainer::relocate().
array() [2/2]
const C_FLOAT64 * CMathHistoryCore::array () const
References CVectorCore< C_FLOAT64 >::mpBuffer.
cols()
const size_t & CMathHistoryCore::cols () const
References mCols.
Referenced by CMathHistory::CMathHistory(), CMathHistoryCore(), CMathHistory::copy(), initialize(), CMathHistory::resize(), and CMathContainer::setHistory().
colsAllocated()
const size_t & CMathHistoryCore::colsAllocated () const
References mColsAllocated.
Referenced by CMathHistory::CMathHistory(), CMathHistoryCore(), CMathHistory::copy(), initialize(), and CMathHistory::resize().
getRow()
const CVectorCore< C_FLOAT64 > & CMathHistoryCore::getRow (const size_t & row)
References CVectorCore< CType >::initialize(), mCols, mColsAllocated, and CVectorCore< C_FLOAT64 >::mpBuffer.
Referenced by CMathContainer::updateHistoryValues().
initialize() [1/2]
void CMathHistoryCore::initialize (const CMathHistoryCore & src)
Initialize the core vector to reference an other core vector.
Parameters
const CMathHistoryCore & src
References CVectorCore< CType >::initialize(), mCols, mColsAllocated, and mRows.
initialize() [2/2]
void CMathHistoryCore::initialize (const size_t & rows, const size_t & cols, const size_t & colsAllocated, C_FLOAT64 * pArray)
Initialize the core history to reference an externally allocated array
Parameters
const size_t & rows
const size_t & cols
const size_t & colsAllocated
C_FLOAT64 * pArray
References cols(), colsAllocated(), CVectorCore< CType >::initialize(), mCols, mColsAllocated, mRows, and rows().
Referenced by CMathContainer::relocate().
operator=()
CMathHistoryCore & CMathHistoryCore::operator= (const CMathHistoryCore & rhs)
References mCols, mColsAllocated, and mRows.
operator[]()
C_FLOAT64 * CMathHistoryCore::operator[] (const size_t & row)
References mColsAllocated, and CVectorCore< C_FLOAT64 >::mpBuffer.
rows()
const size_t & CMathHistoryCore::rows () const
References mRows.
Referenced by CMathHistory::CMathHistory(), CMathHistory::copy(), initialize(), CMathHistory::resize(), and CMathContainer::setHistory().
setRow()
void CMathHistoryCore::setRow (const size_t & row, const CVectorCore< C_FLOAT64 > & values)
References CVectorCore< CType >::initialize(), mCols, mColsAllocated, and CVectorCore< C_FLOAT64 >::mpBuffer.
size()
const size_t & CMathHistoryCore::size () const
References CVectorCore< C_FLOAT64 >::mSize.
Referenced by CMathHistory::copy(), and CMathContainer::setHistory().
Member Data Documentation
mCols
size_t CMathHistoryCore::mCols protected
Number of columns in the matrix
Referenced by cols(), CMathHistory::copy(), getRow(), initialize(), operator=(), CMathHistory::resize(), and setRow().
mColsAllocated
size_t CMathHistoryCore::mColsAllocated protected
Number of columns allocated
Referenced by colsAllocated(), CMathHistory::copy(), getRow(), initialize(), operator=(), operator[](), CMathHistory::resize(), and setRow().
mRows
size_t CMathHistoryCore::mRows protected
Number of rows in the matrix.
Referenced by CMathHistory::copy(), initialize(), operator=(), CMathHistory::resize(), and rows().
The documentation for this class was generated from the following files:
CMathHistory.h
CMathHistory.cpp