COPASI API: CDataVectorS< CType > Class Template Reference
CDataVectorS< CType > Class Template Reference
#include <CDataVector.h>
Public Types
typedef std::vector< CType * >::const_iterator const_iterator
typedef std::vector< CType * >::iterator iterator
typedef std::vector< CType * >::value_type value_type
Public Types inherited from CDataVector< CType >
typedef CDataObjectMap::const_type_iterator< CType > const_name_iterator
typedef CDataObjectMap::type_iterator< CType > name_iterator
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
CDataVectorS (const CDataVectorS< CType > &src, const CDataContainer *pParent)
CDataVectorS (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
virtual void load (CReadConfig &configbuffer, size_t size)
virtual ~CDataVectorS ()
Public Member Functions inherited from CDataVector< CType >
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool add (const CType &src)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
iterator begin ()
const_iterator begin () const
name_iterator beginName ()
const_name_iterator beginName () const
CDataVector (const CDataVector< CType > &src, const CDataContainer *pParent)
CDataVector (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void cleanup ()
virtual void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
void deepCopy (const CDataVector< CType > &source)
virtual bool empty () const
iterator end ()
const_iterator end () const
name_iterator endName ()
const_name_iterator endName () const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &name) const
virtual CUndoObjectInterface * insert (const CData &data)
bool operator!= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const std::vector< CType * > &rhs)
CType & operator[] (const size_t &index)
const CType & operator[] (const size_t &index) const
virtual bool remove (CDataObject *pObject)
virtual void remove (const size_t &index)
virtual void resize (const size_t &newSize)
virtual size_t size () const
virtual void swap (const size_t &indexFrom, const size_t &indexTo)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CDataVector ()
Public Member Functions inherited from CDataContainer
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Additional Inherited Members
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataVector< CType >
CDataVector (const CDataVector< CType > &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Member Typedef Documentation
const_iterator
template<class CType > typedef std::vector< CType * >::const_iterator CDataVectorS< CType >::const_iterator
iterator
template<class CType > typedef std::vector< CType * >::iterator CDataVectorS< CType >::iterator
value_type
template<class CType > typedef std::vector< CType * >::value_type CDataVectorS< CType >::value_type
Constructor & Destructor Documentation
CDataVectorS() [1/2]
template<class CType > CDataVectorS< CType >::CDataVectorS (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT) inline
Default constructor
Parameters
const std::string & name (Default: "NoName")
const CDataContainer * pParent (Default: NULL)
CDataVectorS() [2/2]
template<class CType > CDataVectorS< CType >::CDataVectorS (const CDataVectorS< CType > & src, const CDataContainer * pParent) inline
Copy constructor
Parameters
const CDataVectorS < CType > & src
const CDataContainer * pParent (Default: NULL)
~CDataVectorS()
template<class CType > virtual CDataVectorS< CType >::~CDataVectorS () inline virtual
Destructor
Member Function Documentation
load()
template<class CType > virtual void CDataVectorS< CType >::load (CReadConfig & configbuffer, size_t size) inline virtual
Loads an object with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
CReadConfig & configbuffer
const size_t & size
References CDataVector< CType >::cleanup(), CCopasiMessage::EXCEPTION, MCopasiBase, CDataVector< CType >::resize(), and CDataVector< CType >::size().
Referenced by CModel::load().
The documentation for this class was generated from the following files:
CDataModel.h
CDataVector.h