COPASI API: CMathContext Class Reference
CMathContext Class Reference
#include <CMathContext.h>
Public Types
typedef CPointerContext< CMathContainer > Base
Public Types inherited from CPointerContext< CMathContainer >
typedef CContext< CMathContainer * > Base
Public Member Functions
CMathContext ()=delete
CMathContext (const bool &parallel)
CMathContext (const CMathContext &src)=delete
void sync ()
~CMathContext ()
Public Member Functions inherited from CPointerContext< CMathContainer >
CPointerContext ()=delete
CPointerContext (const bool &parallel)
CPointerContext (const CPointerContext &src)=delete
void setMaster (CMathContainer *pMaster)
~CPointerContext ()
Public Member Functions inherited from CContext< Data >
Data & active ()
const Data & active () const
Data * beginThread ()
const Data * beginThread () const
CContext (const bool &parallel=true)
CContext (const CContext &src)
Data * endThread ()
const Data * endThread () const
int globalIndex (const Data *data) const
void init ()
bool isMaster (const Data *data) const
bool isThread (const Data *data) const
int localIndex (const Data *data) const
Data & master ()
const Data & master () const
CContext & operator= (const CContext &rhs)
bool operator== (const CContext &rhs) const
void release ()
const size_t & size () const
~CContext ()
Member Typedef Documentation
Base
typedef CPointerContext< CMathContainer > CMathContext::Base
Constructor & Destructor Documentation
CMathContext() [1/3]
CMathContext::CMathContext () delete
CMathContext() [2/3]
CMathContext::CMathContext (const CMathContext & src) delete
CMathContext() [3/3]
CMathContext::CMathContext (const bool & parallel)
~CMathContext()
CMathContext::~CMathContext ()
Member Function Documentation
sync()
void CMathContext::sync ()
Set the pointer to container used for calculations
References CContext< Data >::beginThread(), CMathContainer::copy(), CContext< Data >::endThread(), and CContext< Data >::master().
Referenced by COptMethod::initialize().
The documentation for this class was generated from the following files:
CMathContext.h
CMathContext.cpp