COPASI API: CTrajectoryMethodDsaLsodar::CPartition Class Reference
CTrajectoryMethodDsaLsodar::CPartition Class Reference
Public Types
typedef std::multimap< size_t, size_t * > speciesToReactionsMap
Public Member Functions
CPartition ()
CPartition (const CPartition &src)
void intialize (const CMathContainer *pContainer, const C_FLOAT64 &lowerThreshold, const C_FLOAT64 &upperThreshold)
bool rePartition (const CVectorCore< C_FLOAT64 > &state)
~CPartition ()
Public Attributes
CVector< const CMathReaction * > mDeterministicReactions
size_t mFirstReactionSpeciesIndex
bool mHasDeterministic
bool mHasStochastic
C_FLOAT64 mLowerThreshold
CVector< size_t > mNumLowSpecies
size_t mNumReactionSpecies
const CMathContainer * mpContainer
const C_FLOAT64 * mpFirstReactionValue
speciesToReactionsMap mSpeciesToReactions
CVector< const CMathReaction * > mStochasticReactions
CVector< bool > mStochasticSpecies
C_FLOAT64 mUpperThreshold
Member Typedef Documentation
speciesToReactionsMap
typedef std::multimap< size_t, size_t * > CTrajectoryMethodDsaLsodar::CPartition::speciesToReactionsMap
Constructor & Destructor Documentation
CPartition() [1/2]
CTrajectoryMethodDsaLsodar::CPartition::CPartition ()
Default constructor
CTrajectoryMethodDsaLsodar
This class implements an hybrid algorithm for the simulation of a biochemical system over time.
CPartition() [2/2]
CTrajectoryMethodDsaLsodar::CPartition::CPartition (const CPartition & src)
Copy constructor
Parameters
const CPartition & src
~CPartition()
CTrajectoryMethodDsaLsodar::CPartition::~CPartition ()
Destructor
Member Function Documentation
intialize()
void CTrajectoryMethodDsaLsodar::CPartition::intialize (const CMathContainer * pContainer, const C_FLOAT64 & lowerThreshold, const C_FLOAT64 & upperThreshold)
References CVectorCore< CType >::array(), C_FLOAT64, CMathContainer::getCountDependentSpecies(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getCountIndependentSpecies(), CMathContainer::getCountODEs(), CMathReaction::getNumberBalance(), CMathContainer::getReactions(), CMathContainer::getState(), CTrajectoryMethodDsaLsodar::mFirstReactionSpeciesIndex, CCopasiMethod::mpContainer, and CVectorCore< CType >::size().
Referenced by CTrajectoryMethodDsaLsodar::start().
rePartition()
bool CTrajectoryMethodDsaLsodar::CPartition::rePartition (const CVectorCore< C_FLOAT64 > & state)
References CVectorCore< CType >::array(), C_FLOAT64, and CTrajectoryMethodDsaLsodar::mFirstReactionSpeciesIndex.
Referenced by CTrajectoryMethodDsaLsodar::doSingleStep().
Member Data Documentation
mDeterministicReactions
CVector< const CMathReaction * > CTrajectoryMethodDsaLsodar::CPartition::mDeterministicReactions
A vector containing pointers to stochastic reaction dependencies
Referenced by CTrajectoryMethodDsaLsodar::evalF().
mFirstReactionSpeciesIndex
size_t CTrajectoryMethodDsaLsodar::CPartition::mFirstReactionSpeciesIndex
The index of the first species determined by reactions in the state
Referenced by CTrajectoryMethodDsaLsodar::evalF().
mHasDeterministic
bool CTrajectoryMethodDsaLsodar::CPartition::mHasDeterministic
A Boolean flag indicating whether the system has deterministic reactions
mHasStochastic
bool CTrajectoryMethodDsaLsodar::CPartition::mHasStochastic
A Boolean flag indicating whether the system has stochastic reactions
Referenced by CTrajectoryMethodDsaLsodar::doSingleStep().
mLowerThreshold
C_FLOAT64 CTrajectoryMethodDsaLsodar::CPartition::mLowerThreshold
The threshold for switching to stochastic treatment
mNumLowSpecies
CVector< size_t > CTrajectoryMethodDsaLsodar::CPartition::mNumLowSpecies
A vector containing the number of low species for each reaction
mNumReactionSpecies
size_t CTrajectoryMethodDsaLsodar::CPartition::mNumReactionSpecies
The number of species determined by reactions
Referenced by CTrajectoryMethodDsaLsodar::evalF().
mpContainer
const CMathContainer* CTrajectoryMethodDsaLsodar::CPartition::mpContainer
A pointer to the math container;
mpFirstReactionValue
const C_FLOAT64* CTrajectoryMethodDsaLsodar::CPartition::mpFirstReactionValue
A pointer to the first species determined by reactions
Referenced by CTrajectoryMethodDsaLsodar::evalF().
mSpeciesToReactions
speciesToReactionsMap CTrajectoryMethodDsaLsodar::CPartition::mSpeciesToReactions
A map from a species index to the indexes of the reactions it participates in
mStochasticReactions
CVector< const CMathReaction * > CTrajectoryMethodDsaLsodar::CPartition::mStochasticReactions
A vector containing pointers to stochastic reaction dependencies
Referenced by CTrajectoryMethodDsaLsodar::calculatePropensities(), CTrajectoryMethodDsaLsodar::calculateTotalPropensity(), and CTrajectoryMethodDsaLsodar::doSingleStep().
mStochasticSpecies
CVector< bool > CTrajectoryMethodDsaLsodar::CPartition::mStochasticSpecies
A vector indicating whether a species is treated stochastically or not.
mUpperThreshold
C_FLOAT64 CTrajectoryMethodDsaLsodar::CPartition::mUpperThreshold
The threshold for switching to deterministic treatment
The documentation for this class was generated from the following files:
CTrajectoryMethodDsaLsodar.h
CTrajectoryMethodDsaLsodar.cpp