COPASI API: CPraxis Class Reference
CPraxis Class Reference
#include <CPraxis.h>
Public Member Functions
CPraxis ()
C_FLOAT64 operator() (C_FLOAT64 t0, C_FLOAT64 h0, C_INT32 n, C_INT32 prin, C_FLOAT64 x[], FPraxis *f)
~CPraxis ()
Private Member Functions
C_FLOAT64 flin (C_INT32 n, C_INT32 j, C_FLOAT64 l, FPraxis *f, C_FLOAT64 x[], C_INT32 &nf, C_FLOAT64 v[], C_FLOAT64 q0[], C_FLOAT64 q1[], C_FLOAT64 &qd0, C_FLOAT64 &qd1, C_FLOAT64 &qa, C_FLOAT64 &qb, C_FLOAT64 &qc)
void minfit (C_INT32 n, C_FLOAT64 tol, C_FLOAT64 a[], C_FLOAT64 q[])
void minny (C_INT32 n, C_INT32 j, C_INT32 nits, C_FLOAT64 &d2, C_FLOAT64 &x1, C_FLOAT64 &f1, bool fk, FPraxis *f, C_FLOAT64 x[], C_FLOAT64 t, C_FLOAT64 h, C_FLOAT64 v[], C_FLOAT64 q0[], C_FLOAT64 q1[], C_INT32 &nl, C_INT32 &nf, C_FLOAT64 dmin, C_FLOAT64 ldt, C_FLOAT64 &fx, C_FLOAT64 &qa, C_FLOAT64 &qb, C_FLOAT64 &qc, C_FLOAT64 &qd0, C_FLOAT64 &qd1)
void prC_INT322 (C_INT32 n, C_FLOAT64 x[], C_INT32 prin, C_FLOAT64 fx, C_INT32 nf, C_INT32 nl)
void quad (C_INT32 n, FPraxis *f, C_FLOAT64 x[], C_FLOAT64 t, C_FLOAT64 h, C_FLOAT64 v[], C_FLOAT64 q0[], C_FLOAT64 q1[], C_INT32 &nl, C_INT32 &nf, C_FLOAT64 dmin, C_FLOAT64 ldt, C_FLOAT64 &fx, C_FLOAT64 &qf1, C_FLOAT64 &qa, C_FLOAT64 &qb, C_FLOAT64 &qc, C_FLOAT64 &qd0, C_FLOAT64 &qd1)
C_FLOAT64 r8_hypot (C_FLOAT64 x, C_FLOAT64 y)
C_FLOAT64 r8_uniform_01 (C_INT32 &seed)
void r8mat_prC_INT32 (C_INT32 m, C_INT32 n, C_FLOAT64 a[], std::string title)
void r8mat_prC_INT32_some (C_INT32 m, C_INT32 n, C_FLOAT64 a[], C_INT32 ilo, C_INT32 jlo, C_INT32 ihi, C_INT32 jhi, std::string title)
void r8mat_transpose_in_place (C_INT32 n, C_FLOAT64 a[])
void r8vec_copy (C_INT32 n, C_FLOAT64 a1[], C_FLOAT64 a2[])
C_FLOAT64 r8vec_max (C_INT32 n, C_FLOAT64 r8vec[])
C_FLOAT64 r8vec_min (C_INT32 n, C_FLOAT64 r8vec[])
C_FLOAT64 r8vec_norm (C_INT32 n, C_FLOAT64 a[])
void r8vec_prC_INT32 (C_INT32 n, C_FLOAT64 a[], std::string title)
void svsort (C_INT32 n, C_FLOAT64 d[], C_FLOAT64 v[])
void timestamp ()
Private Attributes
CRandom * mpRandom
Constructor & Destructor Documentation
CPraxis()
CPraxis::CPraxis ()
References CRandom::createGenerator(), and mpRandom.
~CPraxis()
CPraxis::~CPraxis ()
References mpRandom.
Member Function Documentation
flin()
C_FLOAT64 CPraxis::flin (C_INT32 n, C_INT32 j, C_FLOAT64 l, FPraxis * f, C_FLOAT64 x[], C_INT32 & nf, C_FLOAT64 v[], C_FLOAT64 q0[], C_FLOAT64 q1[], C_FLOAT64 & qd0, C_FLOAT64 & qd1, C_FLOAT64 & qa, C_FLOAT64 & qb, C_FLOAT64 & qc) private
References C_FLOAT64, and C_INT32.
Referenced by minny().
minfit()
void CPraxis::minfit (C_INT32 n, C_FLOAT64 tol, C_FLOAT64 a[], C_FLOAT64 q[]) private
References C_FLOAT64, C_INT32, and r8_hypot().
Referenced by operator()().
minny()
void CPraxis::minny (C_INT32 n, C_INT32 j, C_INT32 nits, C_FLOAT64 & d2, C_FLOAT64 & x1, C_FLOAT64 & f1, bool fk, FPraxis * f, C_FLOAT64 x[], C_FLOAT64 t, C_FLOAT64 h, C_FLOAT64 v[], C_FLOAT64 q0[], C_FLOAT64 q1[], C_INT32 & nl, C_INT32 & nf, C_FLOAT64 dmin, C_FLOAT64 ldt, C_FLOAT64 & fx, C_FLOAT64 & qa, C_FLOAT64 & qb, C_FLOAT64 & qc, C_FLOAT64 & qd0, C_FLOAT64 & qd1) private
References C_FLOAT64, C_INT32, dmin, flin(), and r8vec_norm().
Referenced by operator()(), and quad().
operator()()
C_FLOAT64 CPraxis::operator() (C_FLOAT64 t0, C_FLOAT64 h0, C_INT32 n, C_INT32 prin, C_FLOAT64 x[], FPraxis * f)
References C_FLOAT64, C_INT32, dmin, CRandom::getRandomCC(), minfit(), minny(), mpRandom, prC_INT322(), quad(), r8mat_prC_INT32(), r8mat_transpose_in_place(), r8vec_copy(), r8vec_max(), r8vec_min(), r8vec_norm(), r8vec_prC_INT32(), and svsort().
prC_INT322()
void CPraxis::prC_INT322 (C_INT32 n, C_FLOAT64 x[], C_INT32 prin, C_FLOAT64 fx, C_INT32 nf, C_INT32 nl) private
References r8vec_prC_INT32().
Referenced by operator()().
quad()
void CPraxis::quad (C_INT32 n, FPraxis * f, C_FLOAT64 x[], C_FLOAT64 t, C_FLOAT64 h, C_FLOAT64 v[], C_FLOAT64 q0[], C_FLOAT64 q1[], C_INT32 & nl, C_INT32 & nf, C_FLOAT64 dmin, C_FLOAT64 ldt, C_FLOAT64 & fx, C_FLOAT64 & qf1, C_FLOAT64 & qa, C_FLOAT64 & qb, C_FLOAT64 & qc, C_FLOAT64 & qd0, C_FLOAT64 & qd1) private
References C_FLOAT64, C_INT32, dmin, and minny().
Referenced by operator()().
r8_hypot()
C_FLOAT64 CPraxis::r8_hypot (C_FLOAT64 x, C_FLOAT64 y) private
References C_FLOAT64.
Referenced by minfit().
r8_uniform_01()
C_FLOAT64 CPraxis::r8_uniform_01 (C_INT32 & seed) private
References C_FLOAT64, and C_INT32.
r8mat_prC_INT32()
void CPraxis::r8mat_prC_INT32 (C_INT32 m, C_INT32 n, C_FLOAT64 a[], std::string title) private
References r8mat_prC_INT32_some().
Referenced by operator()().
r8mat_prC_INT32_some()
void CPraxis::r8mat_prC_INT32_some (C_INT32 m, C_INT32 n, C_FLOAT64 a[], C_INT32 ilo, C_INT32 jlo, C_INT32 ihi, C_INT32 jhi, std::string title) private
References C_INT32, and INCX.
Referenced by r8mat_prC_INT32().
r8mat_transpose_in_place()
void CPraxis::r8mat_transpose_in_place (C_INT32 n, C_FLOAT64 a[]) private
References C_FLOAT64, and C_INT32.
Referenced by operator()().
r8vec_copy()
void CPraxis::r8vec_copy (C_INT32 n, C_FLOAT64 a1[], C_FLOAT64 a2[]) private
References C_INT32.
Referenced by operator()().
r8vec_max()
C_FLOAT64 CPraxis::r8vec_max (C_INT32 n, C_FLOAT64 r8vec[]) private
References C_FLOAT64, and C_INT32.
Referenced by operator()().
r8vec_min()
C_FLOAT64 CPraxis::r8vec_min (C_INT32 n, C_FLOAT64 r8vec[]) private
References C_FLOAT64, and C_INT32.
Referenced by operator()().
r8vec_norm()
C_FLOAT64 CPraxis::r8vec_norm (C_INT32 n, C_FLOAT64 a[]) private
References C_FLOAT64, and C_INT32.
Referenced by minny(), and operator()().
r8vec_prC_INT32()
void CPraxis::r8vec_prC_INT32 (C_INT32 n, C_FLOAT64 a[], std::string title) private
References C_INT32.
Referenced by operator()(), and prC_INT322().
svsort()
void CPraxis::svsort (C_INT32 n, C_FLOAT64 d[], C_FLOAT64 v[]) private
References C_FLOAT64, and C_INT32.
Referenced by operator()().
timestamp()
void CPraxis::timestamp () private
Member Data Documentation
mpRandom
CRandom* CPraxis::mpRandom private
Referenced by CPraxis(), operator()(), and ~CPraxis().
The documentation for this class was generated from the following files:
CPraxis.h
CPraxis.cpp