COPASI API: CModification Class Reference
CModification Class Reference
#include <CModified.h>
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CModification (const CModification &src, const CDataContainer *pParent)
CModification (const CRDFTriplet &triplet, const std::string &objectName="", const CDataContainer *pParent=NO_PARENT)
CModification (const std::string &objectName, const CDataContainer *pParent=NO_PARENT)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual void destruct ()
const std::string & getDate () const
virtual const std::string & getKey () const
const CRDFTriplet & getTriplet () const
void setDate (const std::string &date)
virtual CData toData () const
~CModification ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CModification * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Private Attributes
std::string mKey
CRDFPredicate::Path mNodePath
CRDFTriplet mTriplet
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Detailed Description
CModified: Stores Modification dates.
Constructor & Destructor Documentation
CModification() [1/3]
CModification::CModification (const std::string & objectName, const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & objectName
const CDataContainer * pParent (default: NULL)
CModification() [2/3]
CModification::CModification (const CRDFTriplet & triplet, const std::string & objectName = "", const CDataContainer * pParent = NO_PARENT)
Specific constructor
Parameters
const CRDFTriplet & triplet
const std::string & objectName (default: "")
const CDataContainer * pParent (default: NULL)
References CRDFNode::getPath(), mNodePath, mTriplet, and CRDFTriplet::pObject.
CModification() [3/3]
CModification::CModification (const CModification & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CModification & src
const CDataContainer * pParent (default: NULL)
~CModification()
CModification::~CModification ()
Destructor
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
applyData()
bool CModification::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CDataContainer::applyData(), CData::DATE, CDataObject::getObjectAncestor(), CData::getProperty(), CData::isSetProperty(), CMIRIAMInfo::save(), setDate(), and CDataValue::toString().
createUndoData()
void CModification::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CUndoData::addProperty(), CUndoData::CHANGE, CDataContainer::createUndoData(), CData::DATE, CUndoData::empty(), getDate(), CData::getProperty(), CData::OBJECT_HASH, CData::OBJECT_INDEX, CUndoData::removeProperty(), and toData().
destruct()
void CModification::destruct () virtual
Destruct the object
Reimplemented from CDataObject.
References CDataObject::destruct(), CDataObject::getObjectAncestor(), CMIRIAMInfo::removeModification(), and CMIRIAMInfo::save().
fromData()
CModification * CModification::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CModification * pDataObject
References CMIRIAMInfo::createModification(), CDataObject::getObjectAncestor(), CData::getProperty(), CData::OBJECT_NAME, CDataContainer::remove(), and CDataValue::toString().
getDate()
const std::string & CModification::getDate () const
References CRDFPredicate::dcterms_W3CDTF, CRDFNode::getFieldValue(), mTriplet, and CRDFTriplet::pObject.
Referenced by createUndoData(), toData(), and CSBMLExporter::updateMIRIAMAnnotation().
getKey()
const std::string & CModification::getKey () const virtual
Reimplemented from CDataObject.
References mKey.
getTriplet()
const CRDFTriplet & CModification::getTriplet () const
References mTriplet.
Referenced by CMIRIAMInfo::removeModification().
setDate()
void CModification::setDate (const std::string & date)
References CRDFPredicate::dcterms_W3CDTF, mNodePath, mTriplet, CRDFTriplet::pObject, and CRDFNode::setFieldValue().
Referenced by applyData(), and CMIRIAMInfo::createModification().
toData()
CData CModification::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::addProperty(), CData::DATE, getDate(), CData::hash(), CData::OBJECT_HASH, CData::OBJECT_INDEX, CData::removeProperty(), and CDataContainer::toData().
Referenced by createUndoData().
Member Data Documentation
mKey
std::string CModification::mKey private
The key of the object needed for the copasi tables.
Referenced by getKey(), and ~CModification().
mNodePath
CRDFPredicate::Path CModification::mNodePath private
The predicate path to the node.
Referenced by CModification(), and setDate().
mTriplet
CRDFTriplet CModification::mTriplet private
Triplet in the RDF graph representing the reference.
Referenced by CModification(), getDate(), getTriplet(), and setDate().
The documentation for this class was generated from the following files:
CModified.h
CModified.cpp