COPASI API: CRDFNode Class Reference
CRDFNode Class Reference
#include <CRDFNode.h>
Public Member Functions
CRDFTriplet addEdge (const CRDFPredicate &predicate, CRDFNode *pObject)
bool addTripletToGraph (const CRDFTriplet &triplet) const
CRDFNode (CRDFGraph &graph)
std::set< CRDFTriplet > getDescendantsWithPredicate (const CRDFPredicate &predicate) const
const std::string & getFieldValue (const CRDFPredicate::ePredicateType &predicate) const
const std::string & getId () const
CRDFObject & getObject ()
const CRDFObject & getObject () const
CRDFPredicate::Path getPath () const
const CRDFSubject & getSubject () const
bool hasAncestor (const CRDFNode *pNode) const
bool isBagNode () const
bool isBlankNode () const
bool isObjectNode () const
bool isReadOnly () const
bool isSubjectNode () const
bool removeEdge (const CRDFPredicate &predicate, CRDFNode *pObject)
bool removeTripletFromGraph (const CRDFTriplet &triplet) const
bool setFieldValue (const CMIRIAMResourceObject &value, const CRDFPredicate::ePredicateType &predicate, const CRDFPredicate::Path &nodePath)
bool setFieldValue (const std::string &value, const CRDFPredicate::ePredicateType &predicate, const CRDFPredicate::Path &nodePath)
void setId (const std::string &id)
void setObject (const CRDFObject &object)
void setSubject (const CRDFSubject &subject)
~CRDFNode ()
Private Member Functions
CRDFNode ()
CRDFNode (const CRDFNode &CRDFNode)
CRDFNode * createMissingAncestors (const CRDFPredicate::Path &nodePath, const CRDFPredicate::ePredicateType &predicate, CRDFPredicate::sAllowedLocation const *&pLocation)
CRDFNode * createMissingAncestors (const CRDFPredicate::Path &predicatePath, const size_t &level)
CRDFNode & operator= (const CRDFNode &rhs)
Private Attributes
CRDFGraph & mGraph
std::string mId
bool mIsBlankNode
CRDFObject * mpObject
CRDFSubject * mpSubject
Constructor & Destructor Documentation
CRDFNode() [1/3]
CRDFNode::CRDFNode () private
Default Constructor
CRDFNode() [2/3]
CRDFNode::CRDFNode (const CRDFNode & CRDFNode) private
CRDFNode() [3/3]
CRDFNode::CRDFNode (CRDFGraph & graph)
Specific Constructor
Parameters
CRDFGraph & graph
~CRDFNode()
CRDFNode::~CRDFNode ()
Destructor
References mpObject, mpSubject, and pdelete.
Member Function Documentation
addEdge()
CRDFTriplet CRDFNode::addEdge (const CRDFPredicate & predicate, CRDFNode * pObject)
Add a property edge to the node.
Parameters
const CRDFPredicate & edge
CRDFNode * pObject
Returns
CRDFTriplet triplet
References CRDFGraph::addTriplet(), addTripletToGraph(), CRDFGraph::getTriplets(), isBagNode(), mGraph, CRDFPredicate::rdf_li, CRDFPredicate::rdf_type, CRDFObject::RESOURCE, CRDFObject::setResource(), and CRDFObject::setType().
Referenced by CRDFGraph::addTriplet(), CRDFGraphConverter::convert(), CRDFGraph::moveTriplet(), and CBiologicalDescription::setPredicate().
addTripletToGraph()
bool CRDFNode::addTripletToGraph (const CRDFTriplet & triplet) const
This method is for internal use only. The method is declared public since friend declarations may not refer to public methods.
Parameters
const CRDFTriplet & triplet
Returns
bool success.
References CRDFGraph::addTriplet(), and mGraph.
Referenced by addEdge().
createMissingAncestors() [1/2]
CRDFNode * CRDFNode::createMissingAncestors (const CRDFPredicate::Path & nodePath, const CRDFPredicate::ePredicateType & predicate, CRDFPredicate::sAllowedLocation const *& pLocation) private
References C_INVALID_INDEX, CRDFPredicate::getAllowedLocationList(), CRDFPredicate::getSubPathIndex(), and isSubjectNode().
Referenced by setFieldValue().
createMissingAncestors() [2/2]
CRDFNode * CRDFNode::createMissingAncestors (const CRDFPredicate::Path & predicatePath, const size_t & level) private
References CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFGraph::generatedNodeId(), getDescendantsWithPredicate(), getSubject(), CRDFPredicate::getURI(), mGraph, CRDFTriplet::pObject, and CRDFObject::setType().
getDescendantsWithPredicate()
std::set< CRDFTriplet > CRDFNode::getDescendantsWithPredicate (const CRDFPredicate & predicate) const
References CRDFGraph::getPredicatePath(), CRDFGraph::getTriplets(), and mGraph.
Referenced by CRDFGraphConverter::convert(), createMissingAncestors(), CReference::CReference(), getFieldValue(), CMIRIAMInfo::load(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), CMIRIAMInfo::loadModifications(), CMIRIAMInfo::loadReferences(), setFieldValue(), CReference::setId(), CReference::setResource(), and CSBMLExporter::updateMIRIAMAnnotation().
getFieldValue()
const std::string & CRDFNode::getFieldValue (const CRDFPredicate::ePredicateType & predicate) const
Retrieve the string representation of the property predicate
Parameters
const CRDFPredicate::ePredicateType & predicate
Returns
const std::string & fieldValue
References CRDFObject::BLANK_NODE, CRDFObject::getBlankNodeID(), getDescendantsWithPredicate(), CRDFLiteral::getLexicalData(), CRDFObject::getLiteral(), CRDFObject::getResource(), CRDFObject::getType(), CRDFObject::LITERAL, and CRDFObject::RESOURCE.
Referenced by CMIRIAMInfo::getCreatedDT(), CModification::getDate(), CReference::getDescription(), CCreator::getEmail(), CCreator::getFamilyName(), CCreator::getGivenName(), and CCreator::getORG().
getId()
const std::string & CRDFNode::getId () const
Retrieve the Id of the node
Returns
const std::string & id
References mId.
getObject() [1/2]
CRDFObject & CRDFNode::getObject ()
Retrieve the object data of the node. It is recommended to call isObjectNode before retrieving the object.
Returns
CRDFObject & object
References mpObject.
Referenced by CRDFGraph::addTriplet(), CMIRIAMResourceObject::CMIRIAMResourceObject(), CRDFGraph::destroyUnreferencedNode(), operator<<(), setFieldValue(), CBiologicalDescription::setId(), CReference::setId(), CMIRIAMResourceObject::setNode(), CBiologicalDescription::setResource(), and CReference::setResource().
getObject() [2/2]
const CRDFObject & CRDFNode::getObject () const
Retrieve the object data of the node. It is recommended to call isObjectNode before retrieving the object.
Returns
const CRDFObject & object
References mpObject.
getPath()
CRDFPredicate::Path CRDFNode::getPath () const
Retrieve a predicate path to the node.
Returns
CRDFPredicate::Path path
References CRDFGraph::getPredicatePath(), and mGraph.
Referenced by CCreator::CCreator(), CModification::CModification(), CRDFGraphConverter::convert(), CReference::CReference(), CMIRIAMInfo::load(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), CMIRIAMInfo::loadReferences(), and CMIRIAMInfo::setCreatedDT().
getSubject()
const CRDFSubject & CRDFNode::getSubject () const
Retrieve the subject data of the node. It is recommended to call isSubjectNode before retrieving the subject.
Returns
const CRDFSubject & subject
References mpSubject.
Referenced by CRDFGraphConverter::convert(), CMIRIAMInfo::createBiologicalDescription(), CMIRIAMInfo::createCreator(), createMissingAncestors(), CMIRIAMInfo::createModification(), CMIRIAMInfo::createReference(), CRDFGraph::guessGraphRoot(), operator<<(), CMIRIAMInfo::setCreatedDT(), and setFieldValue().
hasAncestor()
bool CRDFNode::hasAncestor (const CRDFNode * pNode) const
Check whether the given node is in the path, i.e., has the given node as an ancestor
Parameters
const CRDFNode * pNode
Returns
bool hasAncestor
References CRDFGraph::getParentSubjects(), and mGraph.
isBagNode()
bool CRDFNode::isBagNode () const
Check whether this is a bag node
Returns
isBagNode
References CRDFGraph::getTriplets(), mGraph, and CRDFPredicate::rdf_type.
Referenced by addEdge(), CRDFGraphConverter::convert(), removeEdge(), and CRDFGraph::removeEmptyNodes().
isBlankNode()
bool CRDFNode::isBlankNode () const
Check whether this is a blank node
Returns
bool isBlankNode
References mIsBlankNode.
isObjectNode()
bool CRDFNode::isObjectNode () const
Check whether this is a object node
Returns
bool isObjectNode
References mpObject.
Referenced by CRDFGraph::addTriplet().
isReadOnly()
bool CRDFNode::isReadOnly () const
Check whether the node is read only
Returns
bool isReadOnly
References CRDFGraph::getPredicatePath(), CRDFPredicate::isReadOnly(), and mGraph.
isSubjectNode()
bool CRDFNode::isSubjectNode () const
Check whether this is a subject node
Returns
bool isSubjectNode
References mpSubject.
Referenced by CRDFGraph::addTriplet(), createMissingAncestors(), and CRDFGraph::guessGraphRoot().
operator=()
CRDFNode& CRDFNode::operator= (const CRDFNode & rhs) private
removeEdge()
bool CRDFNode::removeEdge (const CRDFPredicate & predicate, CRDFNode * pObject)
Remove a property edge from the node.
Parameters
const CRDFPredicate & edge
CRDFNode * pObject
Returns
true, if an element was deleted, false otherwise
References CRDFGraph::getTriplets(), isBagNode(), mGraph, CRDFPredicate::rdf_li, removeEdge(), and removeTripletFromGraph().
Referenced by CBiologicalDescription::clearInvalidEntries(), CRDFGraphConverter::convert(), CRDFGraph::moveTriplet(), removeEdge(), CRDFGraph::removeTriplet(), and CBiologicalDescription::setPredicate().
removeTripletFromGraph()
bool CRDFNode::removeTripletFromGraph (const CRDFTriplet & triplet) const
This method is for internal use only. The method is declared public since friend declarations may not refer to public methods.
Parameters
const CRDFTriplet & triplet
Returns
true, if an element was deleted, false otherwise
References mGraph, and CRDFGraph::removeTriplet().
Referenced by removeEdge(), and setFieldValue().
setFieldValue() [1/2]
bool CRDFNode::setFieldValue (const CMIRIAMResourceObject & value, const CRDFPredicate::ePredicateType & predicate, const CRDFPredicate::Path & nodePath)
Set the field value for the property predicate
Parameters
const CMIRIAMResource & value
const CRDFPredicate::ePredicateType & predicate
const CRDFPredicate::Path & nodePath
Returns
bool success
References CRDFGraph::addTriplet(), createMissingAncestors(), CMIRIAMResourceObject::getNode(), getSubject(), CMIRIAMResourceObject::getURI(), CRDFPredicate::getURI(), CMIRIAMResourceObject::isValid(), mGraph, CRDFObject::RESOURCE, setFieldValue(), and CRDFObject::setType().
Referenced by CReference::clearInvalidEntries(), CMIRIAMInfo::setCreatedDT(), CModification::setDate(), CReference::setDescription(), CCreator::setEmail(), CCreator::setFamilyName(), setFieldValue(), CCreator::setGivenName(), CReference::setId(), CCreator::setORG(), and CReference::setResource().
setFieldValue() [2/2]
bool CRDFNode::setFieldValue (const std::string & value, const CRDFPredicate::ePredicateType & predicate, const CRDFPredicate::Path & nodePath)
Set the field value for the property predicate
Parameters
const std::string & value
const CRDFPredicate::ePredicateType & predicate
const CRDFPredicate::Path & nodePath
Returns
bool success
References CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, createMissingAncestors(), fatalError, CRDFGraph::generatedNodeId(), getDescendantsWithPredicate(), CRDFObject::getLiteral(), getObject(), getSubject(), CRDFObject::getType(), CRDFPredicate::getURI(), CRDFObject::LITERAL, mGraph, CRDFLiteral::PLAIN, CRDFTriplet::pObject, removeTripletFromGraph(), CRDFObject::RESOURCE, CRDFLiteral::setLexicalData(), CRDFObject::setResource(), CRDFLiteral::setType(), CRDFObject::setType(), and CRDFPredicate::sAllowedLocation::Type.
setId()
void CRDFNode::setId (const std::string & id)
Set the Id of the node
Parameters
const std::string & id
References mId.
setObject()
void CRDFNode::setObject (const CRDFObject & object)
Set the object data of the node
Parameters
const CRDFObject & object
References CRDFObject::BLANK_NODE, CRDFSubject::BLANK_NODE, CRDFObject::getBlankNodeID(), CRDFObject::getType(), mId, mIsBlankNode, mpObject, mpSubject, pdelete, CRDFSubject::setBlankNodeId(), and CRDFSubject::setType().
Referenced by CRDFGraph::addTriplet().
setSubject()
void CRDFNode::setSubject (const CRDFSubject & subject)
Set the subject data of the node
Parameters
const CRDFSubject & subject
References CRDFObject::BLANK_NODE, CRDFSubject::BLANK_NODE, CRDFSubject::getBlankNodeID(), CRDFSubject::getType(), mId, mIsBlankNode, mpObject, mpSubject, pdelete, CRDFObject::setBlankNodeId(), and CRDFObject::setType().
Referenced by CRDFGraph::addTriplet(), and CRDFGraph::createAboutNode().
Member Data Documentation
mGraph
CRDFGraph& CRDFNode::mGraph private
The graph in which the node is located.
Referenced by addEdge(), addTripletToGraph(), createMissingAncestors(), getDescendantsWithPredicate(), getPath(), hasAncestor(), isBagNode(), isReadOnly(), removeEdge(), removeTripletFromGraph(), and setFieldValue().
mId
std::string CRDFNode::mId private
The Id of the node
Referenced by getId(), setId(), setObject(), and setSubject().
mIsBlankNode
bool CRDFNode::mIsBlankNode private
Stores whether this is a blank node
Referenced by isBlankNode(), setObject(), and setSubject().
mpObject
CRDFObject* CRDFNode::mpObject mutable private
A pointer to the object if of type OBJECT or BOTH
Referenced by getObject(), isObjectNode(), setObject(), setSubject(), and ~CRDFNode().
mpSubject
CRDFSubject* CRDFNode::mpSubject mutable private
A pointer to the subject if of type SUBJECT or BOTH
Referenced by getSubject(), isSubjectNode(), setObject(), setSubject(), and ~CRDFNode().
The documentation for this class was generated from the following files:
CRDFNode.h
CRDFGraph.cpp
CRDFNode.cpp