COPASI API: CDataVectorN< CType > Class Template Reference
CDataVectorN< CType > Class Template Reference
#include <CDataVector.h>
Public Types
typedef CDataObjectMap::const_type_iterator< CType > const_name_iterator
typedef CDataObjectMap::type_iterator< CType > name_iterator
Public Types inherited from CDataVector< CType >
typedef CDataObjectMap::const_type_iterator< CType > const_name_iterator
typedef CDataObjectMap::type_iterator< CType > name_iterator
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool add (const CType &src)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CDataVectorN (const CDataVectorN< CType > &src, const CDataContainer *pParent)
CDataVectorN (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
void createUniqueName (std::string &name) const
virtual size_t getIndex (const std::string &name) const
virtual const CObjectInterface * getObject (const CCommonName &name) const
CDataVectorN< CType > & operator= (const std::vector< CType * > &rhs)
CType & operator[] (const size_t &index)
const CType & operator[] (const size_t &index) const
CType & operator[] (const std::string &name)
const CType & operator[] (const std::string &name) const
virtual void remove (const std::string &name)
virtual CData toData () const
virtual ~CDataVectorN ()
Public Member Functions inherited from CDataVector< CType >
iterator begin ()
const_iterator begin () const
name_iterator beginName ()
const_name_iterator beginName () const
CDataVector (const CDataVector< CType > &src, const CDataContainer *pParent)
CDataVector (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void cleanup ()
virtual void clear ()
void deepCopy (const CDataVector< CType > &source)
virtual bool empty () const
iterator end ()
const_iterator end () const
name_iterator endName ()
const_name_iterator endName () const
virtual size_t getIndex (const CDataObject *pObject) const
virtual CUndoObjectInterface * insert (const CData &data)
bool operator!= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const std::vector< CType * > &rhs)
CType & operator[] (const size_t &index)
const CType & operator[] (const size_t &index) const
virtual bool remove (CDataObject *pObject)
virtual void remove (const size_t &index)
virtual void resize (const size_t &newSize)
virtual size_t size () const
virtual void swap (const size_t &indexFrom, const size_t &indexTo)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CDataVector ()
Public Member Functions inherited from CDataContainer
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Private Member Functions
virtual bool isInsertAllowed (const CType *src)
Additional Inherited Members
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataVector< CType >
CDataVector (const CDataVector< CType > &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Member Typedef Documentation
const_name_iterator
template<class CType > typedef CDataObjectMap::const_type_iterator< CType > CDataVectorN< CType >::const_name_iterator
name_iterator
template<class CType > typedef CDataObjectMap::type_iterator< CType > CDataVectorN< CType >::name_iterator
Constructor & Destructor Documentation
CDataVectorN() [1/2]
template<class CType > CDataVectorN< CType >::CDataVectorN (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT) inline
Default constructor
Parameters
const std::string & name (Default: "NoName")
const CDataContainer * pParent (Default: NULL)
CDataVectorN() [2/2]
template<class CType > CDataVectorN< CType >::CDataVectorN (const CDataVectorN< CType > & src, const CDataContainer * pParent) inline
Copy constructor
Parameters
const CDataVectorN < CType > & src
const CDataContainer * pParent (Default: NULL)
~CDataVectorN()
template<class CType > virtual CDataVectorN< CType >::~CDataVectorN () inline virtual
Destructor
Member Function Documentation
add() [1/2]
template<class CType > virtual bool CDataVectorN< CType >::add (CDataObject * pObject, const bool & adopt = true) inline virtual
Add an object to the end of the vector, if adobt is true the vector. becomes the parent of the object.
Parameters
CType * src
const bool & adopt (Default: false)
Returns
bool success
Reimplemented from CDataVector< CType >.
References CDataContainer::add(), CCopasiMessage::ERROR, CDataVectorN< CType >::isInsertAllowed(), and MCDataVector.
add() [2/2]
template<class CType > virtual bool CDataVectorN< CType >::add (const CType & src) inline virtual
Add a copy of the object to the end of the vector.
Parameters
const CType & src
Returns
bool success.
Reimplemented from CDataVector< CType >.
Reimplemented in CUnitDefinitionDB.
References CDataContainer::add(), CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CDataVectorN< CType >::isInsertAllowed(), MCDataVector, and MCopasiBase.
Referenced by CFunctionDB::add(), CFunctionParameters::add(), CUnitDefinitionDB::add(), CModelAdd::addEvents(), CCompartment::addMetabolite(), CDataModel::addReport(), SEDMLImporter::assignReportDefinitions(), CModel::createCompartment(), CModel::createEvent(), CModel::createEventsForTimeseries(), CModel::createModelValue(), CKinFunction::createParameters(), CFitProblem::createParameterSet(), CModel::createReaction(), CModelExpansion::duplicateEvent(), SBMLImporter::importEvent(), CFunctionDB::load(), CDataModel::loadModelParameterSets(), FunctionHandler::processEnd(), LayoutHandler::processEnd(), PlotSpecificationHandler::processEnd(), AssignmentHandler::processStart(), CompartmentHandler::processStart(), EventHandler::processStart(), ModelParameterSetHandler::processStart(), ModelValueHandler::processStart(), ReactionHandler::processStart(), and ReportDefinitionHandler::processStart().
applyData()
template<class CType > virtual bool CDataVectorN< CType >::applyData (const CData & data, CUndoData::CChangeSet & changes) inline virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataVector< CType >.
References CDataVector< CType >::end(), CCommonName::escape(), CDataVectorN< CType >::getIndex(), CDataVectorN< CType >::getObject(), CData::getProperty(), CDataVector< CType >::insert(), CData::OBJECT_NAME, CDataVectorN< CType >::operator[](), CDataValue::toDataVector(), and CData::VECTOR_CONTENT.
Referenced by CEvent::applyData().
createUndoData()
template<class CType > virtual void CDataVectorN< CType >::createUndoData (CUndoData & undoData, const CUndoData::Type & , const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const inline virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataVector< CType >.
References CUndoData::addPostProcessData(), CUndoData::addPreProcessData(), CUndoData::addProperty(), CDataVector< CType >::beginName(), CUndoData::CHANGE, CUndoData::empty(), CDataVector< CType >::end(), CDataVector< CType >::endName(), CDataVector< CType >::getIndex(), CUndoData::getNewData(), CUndoData::getOldData(), CUndoData::INSERT, CData::OBJECT_INDEX, CData::OBJECT_NAME, CUndoData::REMOVE, and CData::VECTOR_CONTENT.
Referenced by CEvent::createUndoData().
createUniqueName()
template<class CType > void CDataVectorN< CType >::createUniqueName (std::string & name) const inline
References C_INVALID_INDEX, CDataVectorN< CType >::getIndex(), and CDataObject::sanitizeObjectName().
Referenced by CDataModel::loadModelParameterSets().
getIndex()
template<class CType > virtual size_t CDataVectorN< CType >::getIndex (const std::string & name) const inline virtual
Retrieve the index of the named object in the vector. If an object with the given name is not found C_INVALID_INDEX is returned.
Parameters
const std::string & name
Returns
size_t index
References C_INVALID_INDEX, CDataObject::sanitizeObjectName(), CDataVector< CType >::size(), and unQuote().
Referenced by CFunctionParameters::add(), CFunctionDB::addAndAdaptName(), CDataModel::addDefaultReports(), CDataModel::addDefaultTasks(), CModelAdd::addEvents(), CDataVectorN< CType >::applyData(), SEDMLImporter::assignReportDefinitions(), CFunction::completeFunctionList(), SEDMLUtils::createAmountMV(), SBMLImporter::createCCompartmentFromCompartment(), SBMLImporter::createCMetabFromSpecies(), SBMLImporter::createCModelValueFromParameter(), CModel::createCompartment(), SBMLImporter::createCReactionFromReaction(), CModel::createEvent(), CModel::createMetabolite(), CModel::createModelValue(), CChemEqInterface::createNonExistingMetabs(), CKinFunction::createParameters(), CFitProblem::createParameterSet(), CModel::createReaction(), CReactionInterface::createUndoData(), CDataVectorN< CType >::createUniqueName(), COptProblem::elevateChildren(), CFunctionDB::findFunction(), CFunctionDB::findLoadFunction(), CDataModel::findObjectByDisplayName(), CFunctionParameters::findParameterByName(), CCopasiXML::fixBuild55(), CCopasiXML::fixBuild81(), CReactionInterface::getConcentrationRateUnit(), CMetabNameInterface::getMetabolite(), CReactionInterface::getUnit(), CRootContainer::getUnitDefFromSymbol(), CReactionInterface::getUnitVector(), SBMLImporter::importEvent(), SEDMLImporter::importTask(), CDataVectorN< CType >::isInsertAllowed(), CCopasiXML::mergeUnitDefinitions(), CUnitDefinition::operator=(), COPASIHandler::processEnd(), AssignmentHandler::processStart(), FunctionHandler::processStart(), ReportDefinitionHandler::processStart(), CDataVectorN< CType >::remove(), SEDMLImporter::updateCopasiTaskForSimulation(), CUnitDefinition::updateSIUnitDefinitions(), and CReactionInterface::writeBackToReaction().
getObject()
template<class CType > virtual const CObjectInterface* CDataVectorN< CType >::getObject (const CCommonName & name) const inline virtual
Retrieve a pointer to the named object.
Parameters
const std::string & name
Returns
const CObjectInterface * pObject
Reimplemented from CDataVector< CType >.
References CDataObjectMap::equal_range(), CCommonName::getElementName(), CDataVector< CType >::getObject(), CDataContainer::getObjects(), and CCommonName::getRemainder().
Referenced by CDataVectorN< CType >::applyData().
isInsertAllowed()
template<class CType > virtual bool CDataVectorN< CType >::isInsertAllowed (const CType * src) inline private virtual
Check whether an insert of the given src into the vector is allowed to avoid naming conflicts.
Parameters
const CType * src
Returns
bool insertAllowed
References C_INVALID_INDEX, CDataObjectMap::equal_range(), CDataVectorN< CType >::getIndex(), and CDataContainer::getObjects().
Referenced by CDataVectorN< CType >::add().
operator=()
template<class CType > CDataVectorN< CType >& CDataVectorN< CType >::operator= (const std::vector< CType * > & rhs) inline
Assignment operator.
Parameters
const std::vector< CType * > & rhs
Returns
CDataVectorN< CType > & lhs
References CDataVector< CType >::operator=().
operator[]() [1/4]
template<class CType > CType& CDataVectorN< CType >::operator[] (const size_t & index) inline
Retrieve the indexed object.
Parameters
const size_t & index
Returns
value_type & object
References CDataVector< CType >::operator[]().
Referenced by CDataVectorN< CType >::applyData().
operator[]() [2/4]
template<class CType > const CType& CDataVectorN< CType >::operator[] (const size_t & index) const inline
Retrieve the indexed object.
Parameters
const size_t & index
Returns
const value_type & object
References CDataVector< CType >::operator[]().
operator[]() [3/4]
template<class CType > CType& CDataVectorN< CType >::operator[] (const std::string & name) inline
Retrieve the named object.
Parameters
const std::string & name
Returns
value_type & object
References CDataObjectMap::equal_range(), CCopasiMessage::EXCEPTION, CDataContainer::getObjects(), and MCDataVector.
operator[]() [4/4]
template<class CType > const CType& CDataVectorN< CType >::operator[] (const std::string & name) const inline
Retrieve the named object.
Parameters
const std::string & name
Returns
const value_type & object
References CDataObjectMap::equal_range(), CCopasiMessage::EXCEPTION, CDataContainer::getObjects(), and MCDataVector.
remove()
template<class CType > virtual void CDataVectorN< CType >::remove (const std::string & name) inline virtual
Remove the object with the given name from the vector.
Parameters
const std::string & name
Reimplemented in CUnitDefinitionDB.
References C_INVALID_INDEX, CCopasiMessage::ERROR, CDataVectorN< CType >::getIndex(), MCDataVector, and CDataVector< CType >::remove().
Referenced by COPASIHandler::processEnd(), CFunctionParameters::remove(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInMetab(), and CMetab::setCompartment().
toData()
template<class CType > virtual CData CDataVectorN< CType >::toData () const inline virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataVector< CType >.
References CData::addProperty(), CDataVector< CType >::beginName(), CDataVector< CType >::endName(), and CData::VECTOR_CONTENT.
Referenced by CEvent::toData().
The documentation for this class was generated from the following files:
CDataModel.h
CDataVector.h