COPASI API: CCopasiException Class Reference
CCopasiException Class Reference
#include <CCopasiException.h>
Public Member Functions
CCopasiException (const CCopasiMessage &message)
const CCopasiMessage & getMessage () const
~CCopasiException ()
Private Member Functions
CCopasiException ()
Private Attributes
const CCopasiMessage mMessage
Detailed Description
CCopasiException class. A more elaborate class description.
Constructor & Destructor Documentation
CCopasiException() [1/2]
CCopasiException::CCopasiException (void) private
Default consructor.
CCopasiException() [2/2]
CCopasiException::CCopasiException (const CCopasiMessage & message)
Specific consructor. Creates a exception with a message.
Parameters
const CCopasiMessage & message
~CCopasiException()
CCopasiException::~CCopasiException (void)
Destructor.
Member Function Documentation
getMessage()
const CCopasiMessage & CCopasiException::getMessage () const
Retrieves the Message associated with the exception
Returns
const CCopasiMessage & message
References mMessage.
Referenced by CModel::load(), main(), CLyapTask::process(), CTimeSensTask::process(), CTSSATask::process(), CAnalyticsTask::process(), CCrossSectionTask::process(), CTrajectoryTask::processTrajectory(), and CTrajectoryTask::processValues().
Member Data Documentation
mMessage
const CCopasiMessage CCopasiException::mMessage private
Referenced by getMessage().
The documentation for this class was generated from the following files:
CCopasiException.h
CCopasiException.cpp