COPASI API: CEvaluationNodeNumber Class Reference
CEvaluationNodeNumber Class Reference
#include <CEvaluationNodeNumber.h>
Public Member Functions
CEvaluationNodeNumber (const C_FLOAT64 &number)
CEvaluationNodeNumber (const CEvaluationNodeNumber &src)
CEvaluationNodeNumber (const SubType &subType, const Data &data)
virtual std::string getCCodeString (const std::vector< std::string > &children) const
virtual std::string getMMLString (const std::vector< std::string > &children, bool expand, const std::vector< std::vector< std::string > > &variables) const
ASTNode * toAST (const CDataModel *pDataModel) const
virtual ~CEvaluationNodeNumber ()
Public Member Functions inherited from CEvaluationNode
void addChildren (const std::vector< CEvaluationNode * > &children)
std::string buildBerkeleyMadonnaString () const
std::string buildCCodeString () const
std::string buildDisplayString () const
std::string buildInfix () const
std::string buildMMLString (bool expand, const std::vector< std::vector< std::string > > &variables) const
std::string buildXPPString () const
virtual void calculate ()
CEvaluationNode ()
CEvaluationNode (const CEvaluationNode &src)
virtual CIssue compile ()
CEvaluationNode * copyBranch () const
CEvaluationNode * copyNode (CEvaluationNode *child1, CEvaluationNode *child2) const
CEvaluationNode * copyNode (const std::vector< CEvaluationNode * > &children) const
const CEvaluationNode * findTopMinus (const std::vector< CFunctionAnalyzer::CValue > &callParameters) const
virtual std::string getBerkeleyMadonnaString (const std::vector< std::string > &children) const
virtual std::string getDisplayString (const std::vector< std::string > &children) const
virtual std::string getInfix (const std::vector< std::string > &children) const
const CEvaluationTree * getTree () const
virtual CValidatedUnit getUnit (const CMathContainer &container, const std::vector< CValidatedUnit > &units) const
const C_FLOAT64 * getValuePointer () const
const ValueType & getValueType () const
virtual std::string getXPPString (const std::vector< std::string > &children) const
virtual bool isBoolean () const
const MainType & mainType () const
bool operator!= (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &rhs)
bool operator< (const CEvaluationNode &right) const
bool operator== (const CEvaluationNode &right) const
void printRecursively () const
void printRecursively (std::ostream &os, int indent=0) const
void setTree (const CEvaluationTree *pTree)
virtual CValidatedUnit setUnit (const CMathContainer &container, const std::map< CEvaluationNode *, CValidatedUnit > &currentUnits, std::map< CEvaluationNode *, CValidatedUnit > &targetUnits) const
virtual CIssue setValueType (const ValueType &valueType)
virtual CEvaluationNode * simplifyNode (const std::vector< CEvaluationNode * > &children) const
CEvaluationNode * splitBranch (const CEvaluationNode *splitnode, bool left) const
const SubType & subType () const
virtual ~CEvaluationNode ()
Public Member Functions inherited from CCopasiNode< std::string >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual Data & getData ()
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Static Public Member Functions
static CEvaluationNode * fromAST (const ASTNode *pASTNode, const std::vector< CEvaluationNode * > &children)
Static Public Member Functions inherited from CEvaluationNode
static CEvaluationNode * create (const MainType &mainType, const SubType &subType, const std::string &data)
static bool isKeyword (const std::string &str)
Private Member Functions
CEvaluationNodeNumber ()
Additional Inherited Members
Public Types inherited from CEvaluationNode
enum class MainType {
INVALID , NUMBER , CONSTANT , OPERATOR ,
OBJECT , FUNCTION , CALL , STRUCTURE ,
CHOICE , VARIABLE , WHITESPACE , LOGICAL ,
MV_FUNCTION , VECTOR , DELAY , UNIT ,
__SIZE
}
enum class SubType {
DEFAULT , DELAY , IF , VECTOR ,
CN , DOUBLE , FUNCTION , LOG ,
OPEN , PI , POWER , EXPRESSION ,
POINTER , EXPONENTIALE , INTEGER , LOG10 ,
MULTIPLY , OR , VECTOROPEN , COMMA ,
DIVIDE , ENOTATION , EXP , True ,
XOR , RATIONALE , AND , CLOSE ,
False , MODULUS , SIN , VECTORCLOSE ,
COS , EQ , Infinity , PLUS ,
NaN , MINUS , NE , TAN ,
REMAINDER , GT , SEC , CSC ,
GE , COT , LT , LE ,
SINH , COSH , TANH , SECH ,
CSCH , COTH , ARCSIN , ARCCOS ,
ARCTAN , ARCSEC , ARCCSC , ARCCOT ,
ARCSINH , ARCCOSH , ARCTANH , ARCSECH ,
ARCCSCH , ARCCOTH , SQRT , ABS ,
FLOOR , CEIL , FACTORIAL , NOT ,
RUNIFORM , RNORMAL , MAX , MIN ,
RGAMMA , RPOISSON , SIGN , AVOGADRO ,
INVALID , __SIZE
}
enum class ValueType { Unknown , Boolean , Number , __SIZE }
Public Types inherited from CCopasiNode< std::string >
typedef std::string Data
Static Public Attributes inherited from CEvaluationNode
static const CEnumAnnotation< std::string, MainType > MainTypeName
static const CEnumAnnotation< std::string, SubType > SubTypeName
Protected Member Functions inherited from CEvaluationNode
CEvaluationNode (const MainType &type, const SubType &subType, const Data &data)
Protected Member Functions inherited from CCopasiNode< std::string >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CEvaluationNode
MainType mMainType
class CEvaluationNode::CPrecedence mPrecedence
const CEvaluationTree * mpTree
const C_FLOAT64 * mpValue
SubType mSubType
C_FLOAT64 mValue
ValueType mValueType
Protected Attributes inherited from CCopasiNode< std::string >
Data mData
Detailed Description
This is class for nodes presenting numbers used in an evaluation trees
Constructor & Destructor Documentation
CEvaluationNodeNumber() [1/4]
CEvaluationNodeNumber::CEvaluationNodeNumber () private
Default constructor
References CEvaluationNode::mPrecedence, and PRECEDENCE_NUMBER.
Referenced by fromAST().
CEvaluationNodeNumber() [2/4]
CEvaluationNodeNumber::CEvaluationNodeNumber (const SubType & subType, const Data & data)
Specific constructor
Parameters
const SubType & subType
const Data & data
References CEvaluationNode::DOUBLE, CEvaluationNode::ENOTATION, fatalError, CEvaluationNode::INTEGER, CEvaluationNode::INVALID, CCopasiNode< std::string >::mData, CEvaluationNode::mPrecedence, CEvaluationNode::mValue, CEvaluationNode::mValueType, CEvaluationNode::Number, PRECEDENCE_NUMBER, CEvaluationNode::RATIONALE, strToDouble(), and CEvaluationNode::subType().
CEvaluationNodeNumber() [3/4]
CEvaluationNodeNumber::CEvaluationNodeNumber (const C_FLOAT64 & number)
Specific constructor
Parameters
const C_FLOAT64 & number
References CCopasiNode< std::string >::mData, CEvaluationNode::mPrecedence, CEvaluationNode::mValue, CEvaluationNode::mValueType, CEvaluationNode::Number, and PRECEDENCE_NUMBER.
CEvaluationNodeNumber() [4/4]
CEvaluationNodeNumber::CEvaluationNodeNumber (const CEvaluationNodeNumber & src)
Copy constructor
Parameters
const CEvaluationNodeNumber & src
~CEvaluationNodeNumber()
CEvaluationNodeNumber::~CEvaluationNodeNumber () virtual
Destructor
Member Function Documentation
fromAST()
CEvaluationNode * CEvaluationNodeNumber::fromAST (const ASTNode * pASTNode, const std::vector< CEvaluationNode * > & children) static
Creates a new CEvaluationNodeCall from an ASTNode and the given children
Parameters
const ASTNode* pNode
const std::vector< CEvaluationNode * > & children
Returns
CEvaluationNode * pCretedNode
References abs, CCopasiNode< _Data >::addChild(), CEvaluationNodeNumber(), CEvaluationNode::DOUBLE, CEvaluationNode::ENOTATION, CEvaluationNode::Infinity, CEvaluationNode::INTEGER, CEvaluationNode::INVALID, CEvaluationNode::MINUS, CEvaluationNode::NaN, CEvaluationNode::RATIONALE, and CEvaluationNode::subType().
Referenced by CEvaluationTree::fromAST().
getCCodeString()
std::string CEvaluationNodeNumber::getCCodeString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in C.
Returns
string representing a double value
Reimplemented from CEvaluationNode.
References CEvaluationNode::mpValue.
getMMLString()
std::string CEvaluationNodeNumber::getMMLString (const std::vector< std::string > & children, bool expand, const std::vector< std::vector< std::string > > & variables) const virtual
Build the MathML string
Parameters
const std::vector< std::string > & children
bool expand = true
const std::vector< std::vector< std::string > > & variables
Returns
std::string MMLString
Reimplemented from CEvaluationNode.
References CCopasiNode< std::string >::mData.
toAST()
ASTNode * CEvaluationNodeNumber::toAST (const CDataModel * pDataModel) const virtual
Create a new ASTNode corresponding to this NumberNode.
Returns
ASTNode* return a pointer to the newly created node;
Reimplemented from CEvaluationNode.
References CEvaluationNode::DOUBLE, CEvaluationNode::ENOTATION, CEvaluationNode::INTEGER, CEvaluationNode::INVALID, CCopasiNode< std::string >::mData, CEvaluationNode::mpValue, CEvaluationNode::RATIONALE, strToDouble(), and CEvaluationNode::subType().
The documentation for this class was generated from the following files:
CEvaluationNodeNumber.h
CEvaluationNodeNumber.cpp