COPASI API: CDataHandler.cpp File Reference
CDataHandler.cpp File Reference
#include "copasi/copasi.h"
#include "CDataHandler.h"
#include "copasi/core/CDataTimer.h"
#include "copasi/core/CDataContainer.h"
#include "copasi/core/CRootContainer.h"
#include "copasi/CopasiDataModel/CDataModel.h"
#include "copasi/utilities/CCopasiMessage.h"
#include "copasi/utilities/CDirEntry.h"
#include "copasi/utilities/utility.h"
#include "copasi/commandline/CLocaleString.h"
#include <copasi/math/CMathObject.h>
Functions
C_FLOAT64 getValue (const CObjectInterface *pInt)
Function Documentation
getValue()
C_FLOAT64 getValue (const CObjectInterface * pInt)
References C_FLOAT64, C_INT32, CObjectInterface::getValuePointer(), and CDataObject::hasFlag().
Referenced by CDataHandler::storeDataAfter(), CDataHandler::storeDataBefore(), and CDataHandler::storeDataDuring().