COPASI API: CLeastSquareSolution Class Reference
CLeastSquareSolution Class Reference
#include <CLeastSquareSolution.h>
Classes
struct ResultInfo
Static Public Member Functions
static ResultInfo solve (const CMatrix< C_FLOAT64 > &aMatrix, const CVectorCore< C_FLOAT64 > &bVector, const CVectorCore< C_FLOAT64 > &absoluteTolerances, const CVector< C_FLOAT64 * > &compartmentVolumes, const C_FLOAT64 &quantity2NumberFactor, CVector< C_FLOAT64 > &xVector)
static size_t solve (const CMatrix< C_FLOAT64 > &aMatrix, const CVectorCore< C_FLOAT64 > &bVector, CVector< C_FLOAT64 > &xVector)
Member Function Documentation
solve() [1/2]
CLeastSquareSolution::ResultInfo CLeastSquareSolution::solve (const CMatrix< C_FLOAT64 > & aMatrix, const CVectorCore< C_FLOAT64 > & bVector, const CVectorCore< C_FLOAT64 > & absoluteTolerances, const CVector< C_FLOAT64 * > & compartmentVolumes, const C_FLOAT64 & quantity2NumberFactor, CVector< C_FLOAT64 > & xVector) static
Computes the minimum-norm solution to a linear least squares problem: minimize || aMatrix * xVector - bVector ||
Parameters
const CMatrix< C_FLOAT64 > & aMatrix
const CVectorCore< C_FLOAT64 > & bVector
const CVectorCore< C_FLOAT64 > & absoluteTolerances
const CVector< C_FLOAT64 * > & compartmentVolumes
const C_FLOAT64 & quantity2NumberFactor
CVector< C_FLOAT64 > & xVector
Returns
ResultInfo info
References CLeastSquareSolution::ResultInfo::absoluteError, CVectorCore< CType >::array(), CVectorCore< CType >::begin(), C_FLOAT64, CVectorCore< CType >::end(), dgemm::eval(), max, CLeastSquareSolution::ResultInfo::rank, CLeastSquareSolution::ResultInfo::relativeError, and solve().
solve() [2/2]
size_t CLeastSquareSolution::solve (const CMatrix< C_FLOAT64 > & aMatrix, const CVectorCore< C_FLOAT64 > & bVector, CVector< C_FLOAT64 > & xVector) static
Computes the minimum-norm solution to a linear least squares problem: minimize || aMatrix * xVector - bVector ||
Parameters
const CMatrix< C_FLOAT64 > & aMatrix
const CVectorCore< C_FLOAT64 > & bVector
CVector< C_FLOAT64 > & xVector
Returns
ResultInfo info
References CMatrix< CType >::array(), CVectorCore< CType >::array(), CVectorCore< CType >::begin(), C_FLOAT64, C_INT, dgelsy_(), max, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), CVector< CType >::resize(), CMatrix< CType >::size(), and CVectorCore< CType >::size().
Referenced by CNewtonMethod::doNewtonStep(), solve(), and CNewtonMethod::targetFunctionDistance().
The documentation for this class was generated from the following files:
CLeastSquareSolution.h
CLeastSquareSolution.cpp