COPASI API: CMathEvent::CTrigger Class Reference
CMathEvent::CTrigger Class Reference
#include <CMathEvent.h>
Classes
class CRootProcessor
Public Member Functions
void allocate (const CEvent *pDataEvent, const CMathContainer &container)
void allocateDiscontinuous (const size_t &nRoots, const CMathContainer &container)
bool compile (const CEvent *pDataEvent, CMathContainer &container)
void copy (const CTrigger &src, CMathContainer &container)
CTrigger ()
CTrigger (const CTrigger &src)
const CVector< CRootProcessor > & getRoots () const
void initialize (CMath::sPointers &pointers)
bool isTrue () const
void relocate (const CMathContainer *pContainer, const std::vector< CMath::sRelocate > &relocations)
void setExpression (const std::string &infix, CMathContainer &container)
~CTrigger ()
Static Private Member Functions
static CEvaluationNode * compile (const CEvaluationNode *pNode, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static CEvaluationNode * compileAND (const CEvaluationNode *pNode, const std::vector< CEvaluationNode * > &children, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static CEvaluationNode * compileEQ (const CEvaluationNode *pNode, const std::vector< CEvaluationNode * > &children, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static CEvaluationNode * compileFUNCTION (const CEvaluationNode *pNode, const std::vector< CEvaluationNode * > &children, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static CEvaluationNode * compileLE (const CEvaluationNode *pNode, const std::vector< CEvaluationNode * > &children, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static CEvaluationNode * compileNE (const CEvaluationNode *pNode, const std::vector< CEvaluationNode * > &children, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static CEvaluationNode * compileNOT (const CEvaluationNode *pNode, const std::vector< CEvaluationNode * > &children, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static CEvaluationNode * compileVARIABLE (const CEvaluationNode *pNode, const std::vector< CEvaluationNode * > &children, const CMath::Variables< CEvaluationNode * > &variables, CMathEvent::CTrigger::CRootProcessor *&pRoot, CMathContainer &container)
static size_t countRoots (const CEvaluationNode *pNode, const CMath::Variables< size_t > &variables)
static size_t countRootsDefault (const std::vector< size_t > &children)
static size_t countRootsEQ (const CEvaluationNode *pNode, const std::vector< size_t > &children)
static size_t countRootsFUNCTION (const CEvaluationNode *pNode, const std::vector< size_t > &children)
static size_t countRootsVARIABLE (const CEvaluationNode *pNode, const CMath::Variables< size_t > &variables)
Private Attributes
std::string mInfix
CMathObject * mpInitialTrigger
CMathObject * mpTrigger
CVector< CRootProcessor > mRoots
Friends
std::ostream & operator<< (std::ostream &os, const CTrigger &o)
Constructor & Destructor Documentation
CTrigger() [1/2]
CMathEvent::CTrigger::CTrigger ()
Default constructor
CTrigger() [2/2]
CMathEvent::CTrigger::CTrigger (const CTrigger & src)
Copy constructor
~CTrigger()
CMathEvent::CTrigger::~CTrigger ()
Destructor
Member Function Documentation
allocate()
void CMathEvent::CTrigger::allocate (const CEvent * pDataEvent, const CMathContainer & container)
References CEvaluationTree::compile(), CExpression::compile(), CEvaluationTree::getRoot(), CEvent::getTriggerExpression(), CFunction::getVariables(), CFunction::setInfix(), CExpression::setInfix(), CExpression::setIsBoolean(), and CFunctionParameters::size().
Referenced by CMathEvent::allocate().
allocateDiscontinuous()
void CMathEvent::CTrigger::allocateDiscontinuous (const size_t & nRoots, const CMathContainer & container)
compile() [1/2]
CEvaluationNode * CMathEvent::CTrigger::compile (const CEvaluationNode * pNode, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References CNodeIteratorMode::After, CEvaluationNode::AND, CNodeIteratorMode::Before, C_INVALID_INDEX, CEvaluationNode::CALL, CEvaluationNode::CONSTANT, CNodeContextIterator< Node, Context >::context(), CMathContainer::copyBranch(), CEvaluationNode::DEFAULT, CNodeContextIterator< Node, Context >::end(), CEvaluationNode::EQ, CEvaluationNode::EXPRESSION, CEvaluationNode::False, CEvaluationNode::FUNCTION, CEvaluationNode::GE, CEvaluationNodeVariable::getIndex(), CEvaluationNode::GT, CEvaluationNode::LE, CEvaluationNode::LOGICAL, CEvaluationNode::LT, CEvaluationNode::NaN, CEvaluationNode::NE, CNodeContextIterator< Node, Context >::next(), CEvaluationNode::NOT, CEvaluationNode::OR, CNodeContextIterator< Node, Context >::parentContextPtr(), CNodeContextIterator< Node, Context >::processingMode(), CNodeContextIterator< Node, Context >::setProcessingModes(), CNodeContextIterator< Node, Context >::skipChildren(), CEvaluationNode::True, CEvaluationNode::VARIABLE, and CEvaluationNode::XOR.
compile() [2/2]
bool CMathEvent::CTrigger::compile (const CEvent * pDataEvent, CMathContainer & container)
References CExpression::compile(), CMathEvent::compile(), CEvaluationTree::getRoot(), CEvent::getTriggerExpression(), CEvent::getTriggerExpressionPtr(), CMathEvent::CTrigger::CRootProcessor::setDataObject(), CExpression::setInfix(), and CExpression::setIsBoolean().
Referenced by CMathEvent::compile().
compileAND()
CEvaluationNode * CMathEvent::CTrigger::compileAND (const CEvaluationNode * pNode, const std::vector< CEvaluationNode * > & children, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References CCopasiNode< _Data >::addChild(), CEvaluationNode::AND, CEvaluationNode::OR, CEvaluationNode::subType(), and CEvaluationNode::XOR.
compileEQ()
CEvaluationNode * CMathEvent::CTrigger::compileEQ (const CEvaluationNode * pNode, const std::vector< CEvaluationNode * > & children, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References CCopasiNode< _Data >::addChild(), CEvaluationNode::AND, CEvaluationNode::EQ, CEvaluationNode::GE, CCopasiNode< _Data >::getChild(), and CEvaluationNode::isBoolean().
compileFUNCTION()
CEvaluationNode * CMathEvent::CTrigger::compileFUNCTION (const CEvaluationNode * pNode, const std::vector< CEvaluationNode * > & children, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References CMathEvent::compile().
compileLE()
CEvaluationNode * CMathEvent::CTrigger::compileLE (const CEvaluationNode * pNode, const std::vector< CEvaluationNode * > & children, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References CCopasiNode< _Data >::addChild(), CMathEvent::CTrigger::CRootProcessor::compile(), CMathEvent::CTrigger::CRootProcessor::createTriggerExpressionNode(), CEvaluationNode::GE, CEvaluationNode::GT, CEvaluationNode::LE, CEvaluationNode::LT, CEvaluationNode::MINUS, and CEvaluationNode::subType().
compileNE()
CEvaluationNode * CMathEvent::CTrigger::compileNE (const CEvaluationNode * pNode, const std::vector< CEvaluationNode * > & children, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References CCopasiNode< _Data >::addChild(), CEvaluationNode::EQ, and CEvaluationNode::NOT.
compileNOT()
CEvaluationNode * CMathEvent::CTrigger::compileNOT (const CEvaluationNode * pNode, const std::vector< CEvaluationNode * > & children, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References CCopasiNode< _Data >::addChild(), and CEvaluationNode::NOT.
compileVARIABLE()
CEvaluationNode * CMathEvent::CTrigger::compileVARIABLE (const CEvaluationNode * pNode, const std::vector< CEvaluationNode * > & children, const CMath::Variables< CEvaluationNode * > & variables, CMathEvent::CTrigger::CRootProcessor *& pRoot, CMathContainer & container) static private
References C_INVALID_INDEX, CCopasiNode< _Data >::getData(), and CEvaluationNode::NaN.
copy()
void CMathEvent::CTrigger::copy (const CTrigger & src, CMathContainer & container)
Copy an existing object
Parameters
const CTrigger & src
CMathContainer & container
References CMathEvent::CTrigger::CRootProcessor::copy(), and mRoots.
Referenced by CMathEvent::copy().
countRoots()
size_t CMathEvent::CTrigger::countRoots (const CEvaluationNode * pNode, const CMath::Variables< size_t > & variables) static private
References CNodeIteratorMode::After, CNodeIteratorMode::Before, CEvaluationNode::CALL, CNodeContextIterator< Node, Context >::context(), CEvaluationNode::DEFAULT, CNodeContextIterator< Node, Context >::end(), CEvaluationNode::EQ, CEvaluationNode::EXPRESSION, CEvaluationNode::FUNCTION, CEvaluationNode::GE, CEvaluationNode::GT, CEvaluationNode::LE, CEvaluationNode::LOGICAL, CEvaluationNode::LT, CEvaluationNode::NE, CNodeContextIterator< Node, Context >::next(), CNodeContextIterator< Node, Context >::parentContextPtr(), CNodeContextIterator< Node, Context >::processingMode(), CNodeContextIterator< Node, Context >::setProcessingModes(), CNodeContextIterator< Node, Context >::skipChildren(), and CEvaluationNode::VARIABLE.
countRootsDefault()
size_t CMathEvent::CTrigger::countRootsDefault (const std::vector< size_t > & children) static private
countRootsEQ()
size_t CMathEvent::CTrigger::countRootsEQ (const CEvaluationNode * pNode, const std::vector< size_t > & children) static private
References CCopasiNode< _Data >::getChild(), and CEvaluationNode::isBoolean().
countRootsFUNCTION()
size_t CMathEvent::CTrigger::countRootsFUNCTION (const CEvaluationNode * pNode, const std::vector< size_t > & children) static private
countRootsVARIABLE()
size_t CMathEvent::CTrigger::countRootsVARIABLE (const CEvaluationNode * pNode, const CMath::Variables< size_t > & variables) static private
References C_INVALID_INDEX.
getRoots()
const CVector< CMathEvent::CTrigger::CRootProcessor > & CMathEvent::CTrigger::getRoots () const
Referenced by CMathContainer::addAnalysisEvent(), CMathContainer::allocate(), CMathContainer::analyzeRoots(), CMathContainer::ignoreDiscontinuityEvent(), CMathContainer::removeAnalysisEvent(), and CMathContainer::replaceDiscontinuousNode().
initialize()
void CMathEvent::CTrigger::initialize (CMath::sPointers & pointers)
References CMath::Event, CMath::EventTrigger, CMathEvent::CTrigger::CRootProcessor::initialize(), CMathObject::initialize(), CMath::sPointers::pEventTriggers, CMath::sPointers::pEventTriggersObject, CMath::sPointers::pInitialEventTriggers, CMath::sPointers::pInitialEventTriggersObject, and CMath::Undefined.
Referenced by CMathEvent::initialize().
isTrue()
bool CMathEvent::CTrigger::isTrue () const
Check whether the root state is true
Returns
bool isTrue
References C_FLOAT64.
Referenced by CMathEvent::fire().
relocate()
void CMathEvent::CTrigger::relocate (const CMathContainer * pContainer, const std::vector< CMath::sRelocate > & relocations)
The objects and values are relocated
Parameters
const CMathContainer * pContainer
const std::vector< CMath::sRelocate > & relocations
References CMathEvent::CTrigger::CRootProcessor::relocate(), and CMathContainer::relocateObject().
Referenced by CMathEvent::relocate().
setExpression()
void CMathEvent::CTrigger::setExpression (const std::string & infix, CMathContainer & container)
Set the trigger expression
Parameters
const std::string & infix
CMathContainer & container
References CMathEvent::compile(), CMathEvent::CTrigger::CRootProcessor::mpRoot, and CMathEvent::CTrigger::CRootProcessor::mpRootState.
Referenced by CMathEvent::setTriggerExpression().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CTrigger & o) friend
Member Data Documentation
mInfix
std::string CMathEvent::CTrigger::mInfix private
mpInitialTrigger
CMathObject* CMathEvent::CTrigger::mpInitialTrigger private
mpTrigger
CMathObject* CMathEvent::CTrigger::mpTrigger private
mRoots
CVector< CRootProcessor > CMathEvent::CTrigger::mRoots private
Referenced by copy().
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp