COPASI API: CObjectLists Class Reference
CObjectLists Class Reference
#include <CObjectLists.h>
Public Types
enum ListType {
EMPTY_LIST = 0 , SINGLE_OBJECT , METABS , METAB_INITIAL_CONCENTRATIONS ,
METAB_INITIAL_NUMBERS , METAB_CONCENTRATIONS , METAB_NUMBERS , NON_CONST_METAB_CONCENTRATIONS ,
NON_CONST_METAB_NUMBERS , CONST_METAB_CONCENTRATIONS , CONST_METAB_NUMBERS , ODE_METAB_CONCENTRATIONS ,
ODE_METAB_NUMBERS , REACTION_METAB_CONCENTRATIONS , REACTION_METAB_NUMBERS , ASS_METAB_CONCENTRATIONS ,
ASS_METAB_NUMBERS , METAB_CONC_RATES , METAB_PART_RATES , METAB_TRANSITION_TIME ,
REACTIONS , REACTION_CONC_FLUXES , REACTION_PART_FLUXES , GLOBAL_PARAMETERS ,
GLOBAL_PARAMETER_INITIAL_VALUES , GLOBAL_PARAMETER_VALUES , NON_CONST_GLOBAL_PARAMETER_VALUES , CONST_GLOBAL_PARAMETER_INITIAL_VALUES ,
ODE_GLOBAL_PARAMETER_VALUES , ASS_GLOBAL_PARAMETER_VALUES , GLOBAL_PARAMETER_RATES , COMPARTMENTS ,
COMPARTMENT_INITIAL_VOLUMES , COMPARTMENT_VOLUMES , NON_CONST_COMPARTMENT_VOLUMES , CONST_COMPARTMENT_VOLUMES ,
ODE_COMPARTMENT_VOLUMES , ASS_COMPARTMENT_VOLUMES , COMPARTMENT_RATES , ALL_INITIAL_VALUES ,
ALL_LOCAL_PARAMETER_VALUES , ALL_PARAMETER_VALUES , ALL_PARAMETER_AND_INITIAL_VALUES , ALL_VARIABLES ,
ALL_ODE_VARIABLES , REDUCED_JACOBIAN_EV_RE , REDUCED_JACOBIAN_EV_IM
}
Static Public Member Functions
static bool existsFixedMetab (const CModel *model)
static std::set< const CModelEntity * > getEventTargets (const CModel *pModel)
static std::vector< const CDataObject * > getListOfConstObjects (ListType t, const CModel *model)
static std::vector< CDataObject * > getListOfObjects (ListType t, const CModel *model)
Static Public Attributes
static const std::string ListTypeName []
Private Types
typedef std::vector< const CDataObject * > ObjectList
Member Typedef Documentation
ObjectList
typedef std::vector< const CDataObject * > CObjectLists::ObjectList private
Member Enumeration Documentation
ListType
enum CObjectLists::ListType
Enumerator
EMPTY_LIST
SINGLE_OBJECT
METABS
METAB_INITIAL_CONCENTRATIONS
METAB_INITIAL_NUMBERS
METAB_CONCENTRATIONS
METAB_NUMBERS
NON_CONST_METAB_CONCENTRATIONS
NON_CONST_METAB_NUMBERS
CONST_METAB_CONCENTRATIONS
CONST_METAB_NUMBERS
ODE_METAB_CONCENTRATIONS
ODE_METAB_NUMBERS
REACTION_METAB_CONCENTRATIONS
REACTION_METAB_NUMBERS
ASS_METAB_CONCENTRATIONS
ASS_METAB_NUMBERS
METAB_CONC_RATES
METAB_PART_RATES
METAB_TRANSITION_TIME
REACTIONS
REACTION_CONC_FLUXES
REACTION_PART_FLUXES
GLOBAL_PARAMETERS
GLOBAL_PARAMETER_INITIAL_VALUES
GLOBAL_PARAMETER_VALUES
NON_CONST_GLOBAL_PARAMETER_VALUES
CONST_GLOBAL_PARAMETER_INITIAL_VALUES
ODE_GLOBAL_PARAMETER_VALUES
ASS_GLOBAL_PARAMETER_VALUES
GLOBAL_PARAMETER_RATES
COMPARTMENTS
COMPARTMENT_INITIAL_VOLUMES
COMPARTMENT_VOLUMES
NON_CONST_COMPARTMENT_VOLUMES
CONST_COMPARTMENT_VOLUMES
ODE_COMPARTMENT_VOLUMES
ASS_COMPARTMENT_VOLUMES
COMPARTMENT_RATES
ALL_INITIAL_VALUES
ALL_LOCAL_PARAMETER_VALUES
ALL_PARAMETER_VALUES
ALL_PARAMETER_AND_INITIAL_VALUES
ALL_VARIABLES
ALL_ODE_VARIABLES
REDUCED_JACOBIAN_EV_RE
REDUCED_JACOBIAN_EV_IM
Member Function Documentation
existsFixedMetab()
bool CObjectLists::existsFixedMetab (const CModel * model) static
References CModelEntity::FIXED, CModel::getMetabolites(), and CDataVector< CType >::size().
getEventTargets()
std::set< const CModelEntity * > CObjectLists::getEventTargets (const CModel * pModel) static
Create a set of all entities which are event targets
Returns
std::set< const CModelEntity * > eventTargets
References CDataVector< CType >::begin(), CDataVector< CType >::end(), CModel::getEvents(), CObjectInterface::GetObjectFromCN(), and CDataContainer::insert().
Referenced by CMathContainer::allocate(), getListOfConstObjects(), CMathContainer::initializeObjects(), and CModel::isStateVariable().
getListOfConstObjects()
std::vector< const CDataObject * > CObjectLists::getListOfConstObjects (ListType t, const CModel * model) static
References CDataArray::addElementReference(), ALL_INITIAL_VALUES, ALL_LOCAL_PARAMETER_VALUES, ALL_PARAMETER_AND_INITIAL_VALUES, ALL_PARAMETER_VALUES, ALL_VARIABLES, ASS_COMPARTMENT_VOLUMES, ASS_GLOBAL_PARAMETER_VALUES, ASS_METAB_CONCENTRATIONS, ASS_METAB_NUMBERS, CModelEntity::ASSIGNMENT, CDataVector< CType >::begin(), COMPARTMENT_INITIAL_VOLUMES, COMPARTMENT_RATES, COMPARTMENT_VOLUMES, COMPARTMENTS, CONST_COMPARTMENT_VOLUMES, CONST_GLOBAL_PARAMETER_INITIAL_VALUES, CONST_METAB_CONCENTRATIONS, CONST_METAB_NUMBERS, CDataArray::dimensionality(), EMPTY_LIST, CDataVector< CType >::end(), CModelEntity::FIXED, CModel::getCompartments(), getEventTargets(), CModel::getMetabolites(), CModel::getModelValues(), CDataContainer::getObject(), CDataVector< CType >::getObject(), CDataObject::getObjectParent(), CModel::getReactions(), CCopasiParameter::getValueReference(), GLOBAL_PARAMETER_INITIAL_VALUES, GLOBAL_PARAMETER_RATES, GLOBAL_PARAMETER_VALUES, GLOBAL_PARAMETERS, METAB_CONC_RATES, METAB_CONCENTRATIONS, METAB_INITIAL_CONCENTRATIONS, METAB_INITIAL_NUMBERS, METAB_NUMBERS, METAB_PART_RATES, METAB_TRANSITION_TIME, METABS, NON_CONST_COMPARTMENT_VOLUMES, NON_CONST_GLOBAL_PARAMETER_VALUES, NON_CONST_METAB_CONCENTRATIONS, NON_CONST_METAB_NUMBERS, CModelEntity::ODE, ODE_COMPARTMENT_VOLUMES, ODE_GLOBAL_PARAMETER_VALUES, ODE_METAB_CONCENTRATIONS, ODE_METAB_NUMBERS, CFunctionParameter::PARAMETER, REACTION_CONC_FLUXES, REACTION_METAB_CONCENTRATIONS, REACTION_METAB_NUMBERS, REACTION_PART_FLUXES, CModelEntity::REACTIONS, REACTIONS, REDUCED_JACOBIAN_EV_IM, REDUCED_JACOBIAN_EV_RE, SINGLE_OBJECT, CDataArray::size(), and CFunctionParameters::size().
Referenced by CMathContainer::allocate(), getListOfObjects(), and CMathContainer::initializeObjects().
getListOfObjects()
std::vector< CDataObject * > CObjectLists::getListOfObjects (ListType t, const CModel * model) static
References getListOfConstObjects().
Referenced by CSensItem::getVariablesPointerList().
Member Data Documentation
ListTypeName
const std::string CObjectLists::ListTypeName static
Referenced by CSensItem::getListTypeDisplayName().
The documentation for this class was generated from the following files:
CObjectLists.h
CObjectLists.cpp