COPASI API: CMathHistory Class Reference
CMathHistory Class Reference
#include <CMathHistory.h>
Public Member Functions
CMathHistory (const CMathHistory &src)
CMathHistory (const CMathHistoryCore &src)
CMathHistory (const size_t &rows=0, const size_t &cols=0, const size_t &colsAllocated=0)
CMathHistory & operator= (const CMathHistory &rhs)
CMathHistory & operator= (const CMathHistoryCore &rhs)
void resize (const size_t &rows, const size_t &cols, const size_t &colsAllocated)
virtual ~CMathHistory ()
Public Member Functions inherited from CMathHistoryCore
C_FLOAT64 * array ()
const C_FLOAT64 * array () const
CMathHistoryCore (const size_t &rows=0, const size_t &cols=0, const size_t &colsAllocated=0, C_FLOAT64 *pArray=NULL)
const size_t & cols () const
const size_t & colsAllocated () const
const CVectorCore< C_FLOAT64 > & getRow (const size_t &row)
void initialize (const CMathHistoryCore &src)
void initialize (const size_t &rows, const size_t &cols, const size_t &colsAllocated, C_FLOAT64 *pArray)
CMathHistoryCore & operator= (const CMathHistoryCore &rhs)
C_FLOAT64 * operator[] (const size_t &row)
const size_t & rows () const
void setRow (const size_t &row, const CVectorCore< C_FLOAT64 > &values)
const size_t & size () const
virtual ~CMathHistoryCore ()
Protected Member Functions
void copy (const CMathHistoryCore &src)
Protected Member Functions inherited from CVectorCore< C_FLOAT64 >
bool applyPivot (const CVectorCore< size_t > &pivot)
C_FLOAT64 * array ()
const C_FLOAT64 * array () const
C_FLOAT64 * begin ()
const C_FLOAT64 * begin () const
CVectorCore (const size_t &size=0, C_FLOAT64 *buffer=NULL)
C_FLOAT64 * end ()
const C_FLOAT64 * end () const
void initialize (const CVectorCore< C_FLOAT64 > &src)
void initialize (const size_t &size, const C_FLOAT64 *vector)
C_FLOAT64 & operator() (const size_t &row)
const C_FLOAT64 & operator() (const size_t &row) const
CVectorCore< C_FLOAT64 > & operator= (const C_FLOAT64 &value)
CVectorCore< C_FLOAT64 > & operator= (const CVectorCore< C_FLOAT64 > &rhs)
bool operator== (const CVectorCore< C_FLOAT64 > &rhs) const
C_FLOAT64 & operator[] (const size_t &row)
const C_FLOAT64 & operator[] (const size_t &row) const
size_t size () const
virtual ~CVectorCore ()
Additional Inherited Members
Protected Types inherited from CVectorCore< C_FLOAT64 >
typedef C_FLOAT64 elementType
Protected Attributes inherited from CMathHistoryCore
size_t mCols
size_t mColsAllocated
size_t mRows
Protected Attributes inherited from CVectorCore< C_FLOAT64 >
C_FLOAT64 * mpBuffer
size_t mSize
Constructor & Destructor Documentation
CMathHistory() [1/3]
CMathHistory::CMathHistory (const size_t & rows = 0, const size_t & cols = 0, const size_t & colsAllocated = 0)
References CMathHistoryCore::cols(), CMathHistoryCore::colsAllocated(), resize(), and CMathHistoryCore::rows().
CMathHistory() [2/3]
CMathHistory::CMathHistory (const CMathHistoryCore & src)
References copy().
CMathHistory() [3/3]
CMathHistory::CMathHistory (const CMathHistory & src)
References copy().
~CMathHistory()
CMathHistory::~CMathHistory () virtual
References CVectorCore< C_FLOAT64 >::mpBuffer, and pdelete.
Member Function Documentation
copy()
void CMathHistory::copy (const CMathHistoryCore & src) protected
References CMathHistoryCore::array(), C_FLOAT64, CMathHistoryCore::cols(), CMathHistoryCore::colsAllocated(), CMathHistoryCore::mCols, CMathHistoryCore::mColsAllocated, CVectorCore< C_FLOAT64 >::mpBuffer, CMathHistoryCore::mRows, CVectorCore< C_FLOAT64 >::mSize, resize(), CMathHistoryCore::rows(), and CMathHistoryCore::size().
Referenced by CMathHistory(), and operator=().
operator=() [1/2]
CMathHistory & CMathHistory::operator= (const CMathHistory & rhs)
References copy().
operator=() [2/2]
CMathHistory & CMathHistory::operator= (const CMathHistoryCore & rhs)
References copy().
resize()
void CMathHistory::resize (const size_t & rows, const size_t & cols, const size_t & colsAllocated)
References C_FLOAT64, CMathHistoryCore::cols(), CMathHistoryCore::colsAllocated(), CCopasiMessage::EXCEPTION, max, CMathHistoryCore::mCols, CMathHistoryCore::mColsAllocated, MCopasiBase, CVectorCore< C_FLOAT64 >::mpBuffer, CMathHistoryCore::mRows, CVectorCore< C_FLOAT64 >::mSize, pdelete, and CMathHistoryCore::rows().
Referenced by CMathHistory(), copy(), CMathContainer::createDelays(), and CMathContainer::relocate().
The documentation for this class was generated from the following files:
CMathHistory.h
CMathHistory.cpp