COPASI API: CAnalyticsTask Class Reference
CAnalyticsTask Class Reference
#include <CAnalyticsTask.h>
Public Member Functions
CAnalyticsTask (const CAnalyticsTask &src, const CDataContainer *pParent=NULL)
CAnalyticsTask (const CDataContainer *pParent, const CTaskEnum::Task &type=CTaskEnum::Task::analytics)
void createEvent ()
virtual const CTaskEnum::Method * getValidMethods () const override
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream) override
virtual bool process (const bool &useInitialValues) override
void removeEvent ()
virtual bool restore (const bool &updateModel=true) override
~CAnalyticsTask ()
Public Member Functions inherited from CTrajectoryTask
CTrajectoryTask (const CDataContainer *pParent, const CTaskEnum::Task &type=CTaskEnum::Task::timeCourse)
CTrajectoryTask (const CTrajectoryTask &src, const CDataContainer *pParent)
const CTimeSeries & getTimeSeries () const
void load (CReadConfig &configBuffer)
bool processStart (const bool &useInitialValues)
bool processStep (const C_FLOAT64 &nextTime, const bool &final=false)
virtual bool processTrajectory (const bool &useInitialValues)
virtual bool processValues (const bool &useInitialValues)
~CTrajectoryTask ()
Public Member Functions inherited from CCopasiTask
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiTask (const CCopasiTask &src, const CDataContainer *pParent)
CCopasiTask (const CDataContainer *pParent, const CTaskEnum::Task &taskType, const std::string &type="Task")
void cleanup ()
virtual void clearCallBack ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const CProcessReportLevel & getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CMathContainer * getMathContainer () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CReport & getReport () const
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
CTaskEnum::Task getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReportLevel callBack)
void setIgnoreProblemData (const bool &ignoreProblemData)
void setMathContainer (CMathContainer *pContainer)
bool setMethodType (const CTaskEnum::Method &type)
void setScheduled (const bool &scheduled)
void setType (const CTaskEnum::Task &type)
virtual void setUpdateModel (const bool &updateModel)
virtual CData toData () const
virtual bool updateMatrices ()
virtual ~CCopasiTask ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Private Types
enum STATE { TRANSIENT = 0 , MAIN , FINISH }
Private Member Functions
CAnalyticsTask ()
void computeSelectedStatistics (std::vector< C_FLOAT64 >, std::vector< C_FLOAT64 >)
void eventCallBack (void *pData, void *pCaller)
void finish ()
void initObjects ()
C_FLOAT64 relativeDifferenceOfStates (const CVectorCore< C_FLOAT64 > &s1, const CVectorCore< C_FLOAT64 > &s2)
void setEventCallback (const bool &set)
Private Attributes
C_FLOAT64 mAverageFreq
C_FLOAT64 mAveragePeriod
C_FLOAT64 mFreq
size_t mhProgress
size_t mIndex
C_FLOAT64 mLastFreq
C_FLOAT64 mLastPeriod
size_t mMaxNumCrossings
size_t mNumCrossings
size_t mOutputStartNumCrossings
CAnalyticsProblem * mpAnalyticsProblem
C_FLOAT64 mPeriod
C_INT mPeriodicity
CMathEvent * mpEvent
CCallbackInterface * mpEventCallback
CDataObject * mpObjectRate
CDataObject * mpObjectSelected
CDataArray * mpResultAnnotation
C_FLOAT64 mPreviousCrossingTime
C_FLOAT64 mProgressFactor
C_FLOAT64 mProgressMax
C_FLOAT64 mProgressValue
const CDataObject * mpSelectedObject
CDataArray * mpStatValAnn
C_FLOAT64 mStartTime
STATE mState
std::vector< CVector< C_FLOAT64 > > mStatesRing
size_t mStatesRingCounter
C_FLOAT64 mStatTime
C_FLOAT64 mStatVal
std::vector< C_FLOAT64 > mTimes
std::vector< C_FLOAT64 > mValues
std::vector< CVector< C_FLOAT64 > > mValuesSeries
CStatistics * pStats
CStatistics * pStatsTime
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01 , STREAM = 0x02 , FINISH = 0x04 , REPORT = 0x10 ,
PLOT = 0x20 , TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0 , OUTPUT_BEFORE = INITIALIZE , OUTPUT_DURING = STREAM , OUTPUT_AFTER = FINISH ,
OUTPUT = REPORT | PLOT | STREAM , OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH , OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH , ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiTask
static CCopasiTask * fromData (const CData &data, CUndoObjectInterface *pParent)
static bool isValidMethod (const CTaskEnum::Method &method, const CTaskEnum::Method *validMethods)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Static Public Attributes inherited from CTrajectoryTask
static const CTaskEnum::Method ValidMethods []
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CTrajectoryTask
virtual void signalMathContainerChanged ()
virtual void signalMethodChanged ()
Protected Member Functions inherited from CCopasiTask
bool isTaskValid () const
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CTrajectoryTask
CVectorCore< C_FLOAT64 > mContainerState
C_FLOAT64 mOutputStartTime
C_FLOAT64 * mpContainerStateTime
bool(* mpLess)(const C_FLOAT64 &, const C_FLOAT64 &)
bool(* mpLessOrEqual)(const C_FLOAT64 &, const C_FLOAT64 &)
CSteadyStateTask * mpSteadyState
CTrajectoryMethod * mpTrajectoryMethod
CTrajectoryProblem * mpTrajectoryProblem
CTimeSeries mTimeSeries
bool mTimeSeriesRequested
bool mUpdateMoieties
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
bool mIgnoreProblemData
CVector< C_FLOAT64 > mInitialState
std::string mKey
unsigned C_INT32 mOutputCounter
CMathContainer * mpContainer
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CProcessReportLevel mProcessReport
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
CTaskEnum::Task mType
bool mUpdateModel
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Member Enumeration Documentation
STATE
enum CAnalyticsTask::STATE private
describes the internal state of the calculation
Enumerator
TRANSIENT
MAIN
FINISH
Constructor & Destructor Documentation
CAnalyticsTask() [1/3]
CAnalyticsTask::CAnalyticsTask () private
Default constructor
CAnalyticsTask() [2/3]
CAnalyticsTask::CAnalyticsTask (const CDataContainer * pParent, const CTaskEnum::Task & type = CTaskEnum::Task::analytics)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Task & type (default: analytics)
CAnalyticsTask class.
This class implements a cross section task.
References CMethodFactory::create(), CTaskEnum::deterministic, CCopasiTask::getType(), initObjects(), and CCopasiTask::mpMethod.
CAnalyticsTask() [3/3]
CAnalyticsTask::CAnalyticsTask (const CAnalyticsTask & src, const CDataContainer * pParent = NULL)
Copy constructor
Parameters
const CAnalyticsTask & src
const CDataContainer * pParent (default: NULL)
References initObjects().
~CAnalyticsTask()
CAnalyticsTask::~CAnalyticsTask ()
Destructor
References mpEventCallback, and pdelete.
Member Function Documentation
computeSelectedStatistics()
void CAnalyticsTask::computeSelectedStatistics (std::vector< C_FLOAT64 > mValues, std::vector< C_FLOAT64 > mTimes) private
Compute the max or min of the values contained in the first parameter vector
References C_INT32, CDataObject::getObjectDisplayName(), CAnalyticsProblem::isPositiveDirection(), mpAnalyticsProblem, CCopasiTask::mpContainer, mpSelectedObject, mStatTime, mStatVal, mTimes, mValues, mValuesSeries, pdelete, pStats, pStatsTime, CMathContainer::setState(), and CDataObject::ValueDbl.
Referenced by finish().
createEvent()
void CAnalyticsTask::createEvent ()
References CMathContainer::addAnalysisEvent(), CVectorCore< CType >::array(), CEvent::Callback, CEvent::compile(), CMathObject::getCN(), CMathContainer::getMathObject(), CMathContainer::getModel(), CMathContainer::getRate(), CAnalyticsProblem::getSelectedObject(), CAnalyticsProblem::getSingleObjectCN(), CMathContainer::getState(), CAnalyticsProblem::getThreshold(), CAnalyticsProblem::isPositiveDirection(), mIndex, mpAnalyticsProblem, CCopasiTask::mpContainer, mpEvent, mpSelectedObject, CEvent::setDelayAssignment(), setEventCallback(), CEvent::setPersistentTrigger(), CEvent::setTriggerExpression(), and CEvent::setType().
Referenced by initialize().
eventCallBack()
void CAnalyticsTask::eventCallBack (void * pData, void * pCaller) private
This is the member function that is called by the static call back function It checks if an event describes the cut plane and does all the necessary analysis and output in this case
References CVectorCore< CType >::array(), C_FLOAT64, FINISH, CMathContainer::getCountFixedEventTargets(), CAnalyticsProblem::getFlagLimitConvergence(), CAnalyticsProblem::getFlagLimitOutConvergence(), CAnalyticsProblem::getFlagLimitOutCrossings(), CAnalyticsProblem::getFlagLimitOutTime(), CMathContainer::getState(), MAIN, mAverageFreq, mAveragePeriod, CTrajectoryTask::mContainerState, mFreq, mhProgress, mIndex, mLastFreq, mLastPeriod, mMaxNumCrossings, mNumCrossings, mOutputStartNumCrossings, CTrajectoryTask::mOutputStartTime, mpAnalyticsProblem, CCopasiTask::mpContainer, CTrajectoryTask::mpContainerStateTime, mPeriod, mPeriodicity, mPreviousCrossingTime, CCopasiTask::mProcessReport, mProgressFactor, mProgressValue, mStartTime, mState, mStatesRing, mStatesRingCounter, mTimes, CTrajectoryTask::mUpdateMoieties, mValues, mValuesSeries, CProcessReportLevel::progressItem(), relativeDifferenceOfStates(), RING_SIZE, CMathContainer::setState(), TRANSIENT, and CMathContainer::updateSimulatedValues().
Referenced by setEventCallback().
finish()
void CAnalyticsTask::finish () private
should be called by all code paths that finish the task. -finishes progress reporting -finishes output -resets call back function
References COutputInterface::AFTER, CVectorCore< CType >::array(), computeSelectedStatistics(), COutputInterface::DURING, CProcessReportLevel::finishItem(), CMathContainer::getState(), mhProgress, mIndex, CCopasiTask::mpContainer, CTrajectoryTask::mpContainerStateTime, CCopasiTask::mProcessReport, mTimes, mValues, and CCopasiTask::output().
Referenced by process().
getValidMethods()
const CTaskEnum::Method * CAnalyticsTask::getValidMethods () const override virtual
Retrieve the list of valid methods
Returns
const CTaskEnum::Method * pValidMethods
Reimplemented from CTrajectoryTask.
References CTaskEnum::deterministic, CTaskEnum::UnsetMethod, and CTrajectoryTask::ValidMethods.
initialize()
bool CAnalyticsTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) override virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CTrajectoryTask.
References createEvent(), CTrajectoryTask::initialize(), mpAnalyticsProblem, CCopasiTask::mpMethod, CCopasiTask::mpProblem, mStatesRing, mStatesRingCounter, and RING_SIZE.
initObjects()
void CAnalyticsTask::initObjects () private
initialize the object references
References CDataContainer::addObjectReference(), mAverageFreq, mAveragePeriod, mFreq, mLastFreq, mLastPeriod, mPeriod, mPeriodicity, CDataObject::ValueDbl, and CDataObject::ValueInt.
Referenced by CAnalyticsTask().
process()
bool CAnalyticsTask::process (const bool & useInitialValues) override virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CTrajectoryTask.
References CProcessReportLevel::addItem(), CVectorCore< CType >::array(), C_FLOAT64, CCopasiMessage::EXCEPTION, finish(), CAnalyticsProblem::getCrossingsLimit(), CTrajectoryProblem::getDuration(), CAnalyticsProblem::getFlagLimitCrossings(), CAnalyticsProblem::getFlagLimitOutCrossings(), CAnalyticsProblem::getFlagLimitOutTime(), CCopasiException::getMessage(), CAnalyticsProblem::getOutCrossingsLimit(), CTrajectoryProblem::getOutputStartTime(), CMathContainer::getState(), mAverageFreq, mAveragePeriod, CTrajectoryTask::mContainerState, MCTrajectoryMethod, mFreq, mhProgress, min, mIndex, mLastFreq, mLastPeriod, mMaxNumCrossings, mNumCrossings, mOutputStartNumCrossings, CTrajectoryTask::mOutputStartTime, mpAnalyticsProblem, CCopasiTask::mpContainer, CTrajectoryTask::mpContainerStateTime, mPeriod, mPeriodicity, mPreviousCrossingTime, CCopasiTask::mProcessReport, mProgressFactor, mProgressMax, mProgressValue, mStartTime, mState, mStatesRingCounter, mTimes, CTrajectoryTask::mUpdateMoieties, mValues, mValuesSeries, CTrajectoryTask::processStart(), CTrajectoryTask::processStep(), CMathContainer::pushAllTransientValues(), CProcessReportLevel::setName(), CMathContainer::setState(), TRANSIENT, CMathContainer::updateSimulatedValues(), and CMathContainer::updateTransientDataValues().
relativeDifferenceOfStates()
C_FLOAT64 CAnalyticsTask::relativeDifferenceOfStates (const CVectorCore< C_FLOAT64 > & s1, const CVectorCore< C_FLOAT64 > & s2) private
References CVectorCore< CType >::array(), C_FLOAT64, CMathContainer::getCountFixedEventTargets(), CCopasiTask::mpContainer, and CVectorCore< CType >::size().
Referenced by eventCallBack().
removeEvent()
void CAnalyticsTask::removeEvent ()
References fatalError, CCopasiTask::mpContainer, mpEvent, CMathContainer::removeAnalysisEvent(), and setEventCallback().
Referenced by restore().
restore()
bool CAnalyticsTask::restore (const bool & updateModel = true) override virtual
Perform necessary cleanup procedures
Reimplemented from CCopasiTask.
References removeEvent(), and CCopasiTask::restore().
setEventCallback()
void CAnalyticsTask::setEventCallback (const bool & set) private
Set or unset the event callback
Parameters
const bool & set
References eventCallBack(), mpEvent, mpEventCallback, and CMathEvent::setCallback().
Referenced by createEvent(), and removeEvent().
Member Data Documentation
mAverageFreq
C_FLOAT64 CAnalyticsTask::mAverageFreq private
Referenced by eventCallBack(), initObjects(), and process().
mAveragePeriod
C_FLOAT64 CAnalyticsTask::mAveragePeriod private
Referenced by eventCallBack(), initObjects(), and process().
mFreq
C_FLOAT64 CAnalyticsTask::mFreq private
Referenced by eventCallBack(), initObjects(), and process().
mhProgress
size_t CAnalyticsTask::mhProgress private
handle for progress reporting
Referenced by eventCallBack(), finish(), and process().
mIndex
size_t CAnalyticsTask::mIndex private
Index of the selected object for the task
Referenced by createEvent(), eventCallBack(), finish(), and process().
mLastFreq
C_FLOAT64 CAnalyticsTask::mLastFreq private
Referenced by eventCallBack(), initObjects(), and process().
mLastPeriod
C_FLOAT64 CAnalyticsTask::mLastPeriod private
Referenced by eventCallBack(), initObjects(), and process().
mMaxNumCrossings
size_t CAnalyticsTask::mMaxNumCrossings private
Referenced by eventCallBack(), and process().
mNumCrossings
size_t CAnalyticsTask::mNumCrossings private
Referenced by eventCallBack(), and process().
mOutputStartNumCrossings
size_t CAnalyticsTask::mOutputStartNumCrossings private
Referenced by eventCallBack(), and process().
mpAnalyticsProblem
CAnalyticsProblem* CAnalyticsTask::mpAnalyticsProblem private
A pointer to the trajectory Problem
Referenced by computeSelectedStatistics(), createEvent(), eventCallBack(), initialize(), and process().
mPeriod
C_FLOAT64 CAnalyticsTask::mPeriod private
Referenced by eventCallBack(), initObjects(), and process().
mPeriodicity
C_INT CAnalyticsTask::mPeriodicity private
Referenced by eventCallBack(), initObjects(), and process().
mpEvent
CMathEvent* CAnalyticsTask::mpEvent private
Pointer to the event representing the cut plane
Referenced by createEvent(), removeEvent(), and setEventCallback().
mpEventCallback
CCallbackInterface* CAnalyticsTask::mpEventCallback private
A pointer to the callback register with the event.
Referenced by setEventCallback(), and ~CAnalyticsTask().
mpObjectRate
CDataObject* CAnalyticsTask::mpObjectRate private
mpObjectSelected
CDataObject* CAnalyticsTask::mpObjectSelected private
mpResultAnnotation
CDataArray* CAnalyticsTask::mpResultAnnotation private
mPreviousCrossingTime
C_FLOAT64 CAnalyticsTask::mPreviousCrossingTime private
Referenced by eventCallBack(), and process().
mProgressFactor
C_FLOAT64 CAnalyticsTask::mProgressFactor private
this holds the current value for the progress reporting
Referenced by eventCallBack(), and process().
mProgressMax
C_FLOAT64 CAnalyticsTask::mProgressMax private
this holds the max value for the progress reporting
Referenced by process().
mProgressValue
C_FLOAT64 CAnalyticsTask::mProgressValue private
this holds the current value for the progress reporting
Referenced by eventCallBack(), and process().
mpSelectedObject
const CDataObject* CAnalyticsTask::mpSelectedObject private
Referenced by computeSelectedStatistics(), and createEvent().
mpStatValAnn
CDataArray* CAnalyticsTask::mpStatValAnn private
mStartTime
C_FLOAT64 CAnalyticsTask::mStartTime private
time at which the simulation starts.
Referenced by eventCallBack(), and process().
mState
STATE CAnalyticsTask::mState private
Referenced by eventCallBack(), and process().
mStatesRing
std::vector< CVector< C_FLOAT64 > > CAnalyticsTask::mStatesRing private
Referenced by eventCallBack(), and initialize().
mStatesRingCounter
size_t CAnalyticsTask::mStatesRingCounter private
Referenced by eventCallBack(), initialize(), and process().
mStatTime
C_FLOAT64 CAnalyticsTask::mStatTime private
Referenced by computeSelectedStatistics().
mStatVal
C_FLOAT64 CAnalyticsTask::mStatVal private
This holds the result
Referenced by computeSelectedStatistics().
mTimes
std::vector< C_FLOAT64 > CAnalyticsTask::mTimes private
Referenced by computeSelectedStatistics(), eventCallBack(), finish(), and process().
mValues
std::vector< C_FLOAT64 > CAnalyticsTask::mValues private
Referenced by computeSelectedStatistics(), eventCallBack(), finish(), and process().
mValuesSeries
std::vector< CVector< C_FLOAT64 > > CAnalyticsTask::mValuesSeries private
Referenced by computeSelectedStatistics(), eventCallBack(), and process().
pStats
CStatistics* CAnalyticsTask::pStats private
Referenced by computeSelectedStatistics().
pStatsTime
CStatistics* CAnalyticsTask::pStatsTime private
Referenced by computeSelectedStatistics().
The documentation for this class was generated from the following files:
CAnalyticsTask.h
CAnalyticsTask.cpp