COPASI API: CDataObject Class Reference
CDataObject Class Reference
#include <CDataObject.h>
Public Types
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
virtual const CDataObject * getValueObject () const
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const override
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Member Functions
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
void refreshAggregateValidity ()
Private Attributes
CValidity mAggregateValidity
std::string mObjectDisplayName
CFlags< Flag > mObjectFlag
std::string mObjectName
std::string mObjectType
CDataObjectReference< std::string > * mpObjectDisplayName
CDataObjectReference< std::string > * mpObjectName
CDataContainer * mpObjectParent
std::set< const CValidity * > mReferencedValidities
Friends
std::ostream & operator<< (std::ostream &os, const CDataObject &o)
Member Typedef Documentation
DataObjectSet
typedef std::set< const CDataObject * > CDataObject::DataObjectSet
Member Enumeration Documentation
Flag
enum CDataObject::Flag
Enumerator
Container
Vector
Matrix
NameVector
Reference
ValueBool
ValueInt
ValueInt64
ValueDbl
NonUniqueName
StaticString
ValueString
Separator
DisplayName
ModelEntity
Array
DataModel
Root
Gui
__SIZE
Constructor & Destructor Documentation
CDataObject() [1/3]
CDataObject::CDataObject () protected
Class CDataObject
This class is the base class for all global accessible objects in COPASI.
Copyright Stefan Hoops 2002
Referenced by fromData().
CDataObject() [2/3]
CDataObject::CDataObject (const std::string & name, const CDataContainer * pParent = static_cast< CDataContainer * >((void *) 0), const std::string & type = "CN", const CFlags< Flag > & flag = CFlags< Flag >::None) protected
References CDataContainer::add(), addReference(), Container, hasFlag(), CRegisteredCommonName::isEnabled(), mpObjectParent, CRegisteredCommonName::setEnabled(), and setObjectName().
CDataObject() [3/3]
CDataObject::CDataObject (const CDataObject & src, const CDataContainer * pParent = NULL)
References CDataContainer::add(), addReference(), INHERIT_PARENT, and mpObjectParent.
~CDataObject()
CDataObject::~CDataObject () virtual
References CValidity::clear(), mAggregateValidity, mpObjectDisplayName, mpObjectName, mpObjectParent, mReferences, and CDataContainer::remove().
Member Function Documentation
addIssue()
void CDataObject::addIssue (const CIssue & issue)
References CValidity::add(), and CObjectInterface::mValidity.
addReference()
void CDataObject::addReference (const CDataContainer * pReference)
References mReferences.
Referenced by CDataContainer::add(), CDataObject(), and setObjectParent().
applyData()
bool CDataObject::applyData (const CData & data, CUndoData::CChangeSet & changes) override virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Implements CUndoObjectInterface.
Reimplemented in CCopasiParameter, CModelEntity, CMetab, CDataContainer, CArrayElementReference, CUnitDefinition, CSlider, CCopasiTask, CCopasiParameterGroup, CReportDefinition, CPlotSpecification, CPlotItem, CFittingPoint, CReaction, CMoiety, CModelValue, CModelParameterSet, CModel, CMetabOld, CEvent, CEventAssignment, CCompartment, CReference, CModification, CMIRIAMInfo, CCreator, CBiologicalDescription, CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLReferenceGlyph, CLLocalStyle, CLLocalRenderInformation, CLLineEnding, CLGraphicalObject, CLGradientStop, CLGradientBase, CLTextGlyph, CLCompartmentGlyph, CLMetabGlyph, CLGlobalStyle, CLGlobalRenderInformation, CLColorDefinition, CLayout, CFunctionParameter, CFunction, CEvaluationTree, CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, and CDataModel.
References CData::addProperty(), CDataContainer::getObject(), getObjectDataModel(), CData::getProperty(), CDataContainer::insert(), CData::isSetProperty(), mpObjectParent, CData::OBJECT_INDEX, CData::OBJECT_NAME, CData::OBJECT_POINTER, CData::OBJECT_REFERENCE_CN, CData::OBJECT_REFERENCE_INDEX, CData::OBJECT_REFERENCES, CData::OBJECT_UUID, setObjectName(), CUndoObjectInterface::setUuid(), CDataValue::toDataVector(), CDataValue::toSizeT(), CDataValue::toString(), and CUndoObjectInterface::updateIndex().
Referenced by CReportDefinition::applyData(), CCopasiParameterGroup::applyData(), CArrayElementReference::applyData(), and CDataContainer::applyData().
calculateValue()
void CDataObject::calculateValue () override virtual
Calculate the objects value.
Implements CObjectInterface.
Reimplemented in COptProblem, COptItem, and CCopasiTimer.
Referenced by CHybridMethod::partitionSystem(), CHybridMethod::setupPriorityQueue(), and CHybridMethod::updatePriorityQueue().
createUndoData()
void CDataObject::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const override virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Implements CUndoObjectInterface.
Reimplemented in CCopasiParameter, CModelEntity, CMetab, CDataContainer, CUnitDefinition, CCopasiTask, CCopasiParameterGroup, CReportDefinition, CReaction, CModelValue, CModelParameterSet, CModel, CEvent, CEventAssignment, CCompartment, CReference, CModification, CMIRIAMInfo, CCreator, CBiologicalDescription, CFunction, CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, and CDataVector< CLGraphicalObject >.
References CUndoData::addProperty(), CData::addProperty(), C_INVALID_INDEX, CUndoData::CHANGE, getCN(), CDataContainer::getIndex(), CData::getProperty(), mObjectFlag, mObjectName, mObjectType, mpObjectParent, mReferences, CData::OBJECT_FLAG, CData::OBJECT_INDEX, CData::OBJECT_NAME, CData::OBJECT_PARENT_CN, CData::OBJECT_REFERENCE_CN, CData::OBJECT_REFERENCE_INDEX, CData::OBJECT_REFERENCES, and CData::OBJECT_TYPE.
Referenced by CReportDefinition::createUndoData(), and CDataContainer::createUndoData().
destruct()
void CDataObject::destruct () override virtual
Destruct the object
Implements CUndoObjectInterface.
Reimplemented in CModelParameterSet, CReference, CModification, CCreator, and CBiologicalDescription.
Referenced by CBiologicalDescription::destruct(), CCreator::destruct(), CModification::destruct(), and CReference::destruct().
fromData()
CDataObject * CDataObject::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CDataObject * pDataObject
References CDataObject(), CData::getProperty(), NO_PARENT, CData::OBJECT_FLAG, CData::OBJECT_NAME, CData::OBJECT_TYPE, CUndoObjectInterface::setUuid(), and CDataValue::toString().
getCN()
CCommonName CDataObject::getCN () const override virtual
Retrieve the CN of the object
Returns
CCommonName
Implements CObjectInterface.
Reimplemented in CCopasiParameter, CArrayElementReference, CModelParameterSet, and CMathContainer.
References C_INVALID_INDEX, DataModel, CCommonName::escape(), getCN(), CDataContainer::getIndex(), hasFlag(), mObjectName, mObjectType, mpObjectParent, NameVector, and Vector.
Referenced by CModelParameterSet::add(), SEDMLImporter::addCurveToCopasiPlot(), CCompartment::addMetabolite(), CReaction::addParameterObject(), addParticleNumberToInitialValueMap(), SEDMLImporter::addSurfaceToCopasiPlot(), CReportDefinition::addTableElement(), addToInitialValueMap(), CCompartment::applyData(), applyValueToParameterSet(), CEventAssignment::CEventAssignment(), CFixLocalReactionParameters::changeModel(), CSBMLExporter::checkForUnsupportedObjectReferences(), CModelParameterSet::CModelParameterSet(), CEvaluationNodeCall::compile(), CEvaluationNodeObject::compile(), CEventAssignment::compile(), CMathEvent::CAssignment::compile(), CModel::convert2NonReversible(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), SEDMLUtils::createAmountMV(), SBMLImporter::createCModelFromSBMLDocument(), SBMLImporter::createCReactionFromReaction(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), CModel::createEventsForTimeseries(), CModelParameterSet::createFromModel(), CExpression::createInitialExpression(), CSBMLExporter::createKineticExpression(), CSBMLExporter::createMassActionExpression(), COutputAssistant::createPlot(), CScanProblem::createScanItem(), CReactionInterface::createUndoData(), CCopasiTask::createUndoData(), createUndoData(), CDerive::deriveBranch(), SBMLImporter::divideByObject(), CModelExpansion::duplicateEvent(), CSEDMLExporter::exportReport(), CExpressionGenerator::generate(), CMathContainer::getCN(), CModelParameterSet::getCN(), CArrayElementReference::getCN(), getCN(), CMathObject::getCN(), CCopasiParameter::getCN(), CModelEntity::getDefaultNoiseExpression(), CReaction::getDefaultNoiseExpression(), CModelExpansion::ElementsMap::getDuplicateFromCN(), getInitialCNForSBase(), CMathContainer::getObject(), CEvent::getOriginFor(), CMetabNameInterface::getSpeciesCN(), SBMLImporter::importEvent(), SEDMLImporter::importReport(), CDataModel::loadModelParameterSets(), CReaction::loadOneRole(), CEvaluationTree::mapObjectNodes(), CModelMerging::mergeInExpression(), CSBMLExporter::multiplyByObject(), CModel::prepareElasticity(), COPASIHandler::processEnd(), AssignmentHandler::processStart(), CModelParameter::refreshFromModel(), SBMLImporter::renameMassActionParameters(), SBMLImporter::replace_time_with_initial_time(), CModelExpansion::replaceInEvent(), CModelExpansion::replaceInExpression(), CModelExpansion::replaceInMetab(), SBMLImporter::replaceObjectNames(), CSBMLExporter::replaceSpeciesReferences(), CCopasiXML::saveModel(), SBMLImporter::sbmlId2CopasiCN(), CDataArray::setAnnotation(), CMetab::setCompartment(), CDataArray::setCopasiVector(), CSEDMLExporter::setCurrentTime(), setObjectName(), setObjectParent(), CReaction::setScalingCompartment(), CReaction::setScalingFactor(), CAnalyticsProblem::setSingleObjectCN(), CCrossSectionProblem::setSingleObjectCN(), CSlider::setSliderObject(), COptProblem::setSubtaskType(), CCopasiTask::toData(), toData(), CModelExpansion::updateExpression(), CReaction::variable2object(), and CReactionInterface::writeBackToReaction().
getDataObject()
const CDataObject * CDataObject::getDataObject () const override virtual
Retrieve a pointer to the data object
Returns
const DATA_OBJECT * dataObject
Implements CObjectInterface.
Referenced by CModel::appendAllDependents(), CModel::appendDirectDependents(), CODEExporter::exportObjectNodesFromModel(), CMathContainer::getInitialValuePointer(), and CMathContainer::getValuePointer().
getKey()
const std::string & CDataObject::getKey () const virtual
Reimplemented in CCopasiParameter, CModelEntity, CUnitDefinition, CSlider, CCopasiTask, CReportDefinitionVector, CReportDefinition, COutputDefinitionVector, CReaction, CMoiety, CModelParameterSet, CModel, CEvent, CEventAssignment, CReference, CModification, CMIRIAMInfo, CCreator, CBiologicalDescription, CLText, CLStyle, CLRenderInformationBase, CLRenderCurve, CLRectangle, CLPolygon, CLLineEnding, CLImage, CLGroup, CLGraphicalObject, CLGradientStop, CLGradientBase, CLEllipse, CLColorDefinition, CLayout, CFunctionParameter, and CFunction.
Referenced by addToInitialValueMap(), CModel::buildStoi(), CLayout::CLayout(), CTimeSeries::compile(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), SBMLImporter::doMapping(), CModelExpansion::duplicateEvent(), CODEExporter::exportExpression(), CODEExporter::exportKineticFunction(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportReacParamsAndFuncs(), CLayout::exportToDotFile(), getFunctionForKey(), CMIRIAMInfo::getKey(), getQuantityParameterOrValue(), SBMLImporter::importEvent(), CODEExporterC::KineticFunction2ODEmember(), CMIRIAMInfo::load(), CModelMerging::mergeInExpression(), CODEExporterC::preprocess(), COPASIHandler::processEnd(), ParameterHandler::processStart(), SliderHandler::processStart(), SBMLImporter::restoreFunctionDB(), CCopasiXML::saveModel(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), CLLayoutRenderer::update_associations(), CSBMLExporter::updateMIRIAMAnnotation(), and CMMLOutput::writeDifferentialEquations().
getObject()
const CObjectInterface * CDataObject::getObject (const CCommonName & cn) const override virtual
Retrieve a descendant object by its CN.
Parameters
const CCommonName & cn
Returns
const CObjectInterface * pObject
Implements CObjectInterface.
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, CDataContainer, CCopasiParameterGroup, CReaction, CMathContainer, and CDataArray.
References DisplayName, getObjectDisplayName(), mObjectDisplayName, mObjectName, mpObjectDisplayName, mpObjectName, and mpObjectParent.
Referenced by CDataArray::getObject(), CDataContainer::getObject(), CMathObject::getObject(), CDataVector< CType >::getObject(), and SEDMLUtils::resolveXPath().
getObjectAncestor()
CDataContainer * CDataObject::getObjectAncestor (const std::string & type) const
References getObjectParent(), and getObjectType().
Referenced by CReaction::addParameterObject(), CModel::appendAllDependents(), CDataContainer::appendDeletedDependentData(), CModel::appendDirectDependents(), CBiologicalDescription::applyData(), CCreator::applyData(), CModification::applyData(), CReference::applyData(), CEventAssignment::applyData(), CEvent::applyData(), CReaction::applyData(), CExperimentSet::calculateStatistics(), CFixLocalReactionParameters::changeModel(), CReaction::compile(), CEvaluationNodeObject::compile(), CMetab::compile(), CReaction::compileFunctionParameters(), CScanItem::CScanItem(), CDerive::deriveBranch(), CBiologicalDescription::destruct(), CCreator::destruct(), CModification::destruct(), CReference::destruct(), CModelExpansion::duplicateEvent(), CFitProblem::elevateChildren(), CBiologicalDescription::fromData(), CCreator::fromData(), CModification::fromData(), CReference::fromData(), CReaction::getChildObjectUnits(), CMathDependencyGraph::getDOTNodeId(), CReaction::getKineticLawUnit(), CEvent::getObjectDisplayName(), CReaction::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), CMetab::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), COptProblem::getSubTask(), SEDMLUtils::getXPathForObjectAndType(), CChemEqInterface::init(), CReactionInterface::init(), CMetab::initCompartment(), CMoiety::initConversionFactor(), CFitProblem::initialize(), CModelEntity::initObjects(), CReaction::loadOneRole(), CReaction::setHasNoise(), CReaction::setNoiseExpression(), CReaction::setNoiseExpressionPtr(), CEventAssignment::setObjectParent(), CEvent::setObjectParent(), CModelParameterSet::setObjectParent(), CModelEntity::setObjectParent(), CReaction::setParameterObjects(), COptProblem::setSubtaskType(), CModelParameter::updateModel(), CReactionInterface::writeBackToReaction(), CChemEqInterface::writeToChemEq(), and CReaction::~CReaction().
getObjectDataModel()
CDataModel * CDataObject::getObjectDataModel () const
Returns a pointer to the CDataModel the element belongs to. If there is no instance of CDataModel in the ancestor tree, NULL is returned.
References DataModel, getObjectParent(), and hasFlag().
Referenced by CFitProblem::addFitConstraint(), CFitProblem::addFitItem(), COptProblem::addOptConstraint(), COptProblem::addOptItem(), addParticleNumberToInitialValueMap(), CDataContainer::appendDeletedDependentData(), applyData(), CExperiment::calculateStatistics(), CDataModel::changeModelParameter(), CModelEntity::compile(), CEvaluationNodeObject::compile(), CMetab::compile(), CEventAssignment::compile(), COptItem::compile(), CSlider::compile(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), CModel::createEventsForTimeseries(), CModelExpansion::duplicateEvent(), CFitProblem::elevateChildren(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportModelValuesExpressions(), CExperimentObjectMap::CDataColumn::getDefaultScale(), CExperiment::getFileName(), CReaction::getFirstCModelOrDefault(), CMathContainer::getObject(), CLRenderResolver::getObjectDataModel(), CFittingPoint::getObjectDisplayName(), getObjectFromCN(), CMathContainer::getObjectFromCN(), CObjectInterface::GetObjectFromCN(), CReaction::getReactionScheme(), CScanProblem::getSubTask(), CSensProblem::getSubTask(), CMCAProblem::getSubTask(), CReactionInterface::getUnit(), CReactionInterface::getUnitVector(), SEDMLUtils::getXPathForObject(), SEDMLImporter::importOutputs(), CNewtonMethod::initialize(), CScanTask::initialize(), CTimeSensTask::initialize(), CTrajectoryTask::initialize(), CCopasiTask::initialize(), CSensMethod::initialize(), CLsodaMethod::initializeParameter(), CCopasiTask::initObjects(), CScanTask::initSubtask(), CSlider::isValid(), CModel::load(), CReaction::loadOneRole(), CModelMerging::mergeInExpression(), CILDMModifiedMethod::printResult(), CTSSAProblem::printResult(), CCopasiXML::saveModel(), CReaction::setReactionScheme(), CReaction::setScalingCompartmentCN(), CReaction::setScalingFactor(), CSlider::setSliderObject(), CModelEntity::setStatus(), CLNAProblem::setSteadyStateRequested(), CMCAProblem::setSteadyStateRequested(), COptProblem::setSubtaskType(), and CSlider::writeToObject().
getObjectDisplayName()
std::string CDataObject::getObjectDisplayName () const override virtual
Retrieve the display name of the object
Parameters
bool regular (default: true)
bool richtext (default: false)
Returns
std::string objectDisplayName
Implements CObjectInterface.
Reimplemented in CCopasiParameter, COptItem, CMetab, CDataObjectReference< CType >, CDataObjectReference< C_FLOAT64 >, CDataObjectReference< std::string >, CArrayElementReference, CFittingPoint, CReaction, CEvent, CCopasiReportSeparator, CDataString, and CDataArray.
References getObjectDisplayName(), getObjectName(), getObjectType(), hasFlag(), mpObjectParent, NameVector, Reference, and Vector.
Referenced by SEDMLImporter::addCurveToCopasiPlot(), SEDMLImporter::addSurfaceToCopasiPlot(), CTimeSeries::compile(), CExperiment::compile(), CAnalyticsTask::computeSelectedStatistics(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), CDataArray::createDisplayName(), CModel::createEventsForTimeseries(), CMMLOutput::createParameterMapping(), COutputAssistant::createPlot(), CExpressionGenerator::escapeDisplayName(), CSEDMLExporter::exportReport(), SEDMLUtils::findIdByNameAndType(), CDataModel::findObjectByDisplayName(), CEvaluationNodeObject::getDisplayString(), CMathMl::getMMLName(), getObject(), CDataArray::getObjectDisplayName(), CEvent::getObjectDisplayName(), CReaction::getObjectDisplayName(), CFittingPoint::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), getObjectDisplayName(), CDataObjectReference< CType >::getObjectDisplayName(), CMathObject::getObjectDisplayName(), CMetab::getObjectDisplayName(), COptItem::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), CEvent::getOriginFor(), SEDMLUtils::getXPathForObject(), CTimeSensMethod::printUpdateSeq(), CModelParameterSet::saveToStream(), CDataArray::setAnnotation(), CArrayElementReference::updateObjectName(), VariableInfo::VariableInfo(), and CMMLOutput::writeDifferentialEquations().
getObjectFromCN()
const CObjectInterface * CDataObject::getObjectFromCN (const CCommonName & cn) const
References getObjectDataModel(), and CObjectInterface::GetObjectFromCN().
Referenced by CCopasiTask::applyData(), CSBMLExporter::checkForUnsupportedObjectReferences(), CReaction::compileFunctionParameters(), CDataArray::createDisplayName(), SBMLImporter::doMapping(), CODEExporter::exportExpression(), CSEDMLExporter::exportPlotItem(), CSEDMLExporter::exportReport(), CSBMLExporter::findModelEntityDependencies(), CEvaluationTree::getNodeObject(), COptItem::getObjectDisplayName(), CSensItem::getSingleObjectDisplayName(), COptItem::getStartValue(), CSensItem::getVariablesPointerList(), SBMLImporter::isConstantFlux(), SBMLImporter::isMassActionExpression(), CSlider::isValid(), CHybridMethodODE45::partitionSystem(), SBMLImporter::renameMassActionParameters(), CSBMLExporter::replace_local_parameters(), CSBMLExporter::replaceSpeciesReferences(), CSBMLExporter::restore_local_parameters(), SBMLImporter::setCorrectUsage(), COptItem::setObjectCN(), CReaction::setParameterCNs(), CEvaluationNodeObject::toAST(), CModelParameter::updateModel(), CArrayElementReference::updateObjectName(), and CReaction::variable2object().
getObjectName()
const std::string & CDataObject::getObjectName () const
References mObjectName.
Referenced by CUnitDefinitionDB::add(), CFunctionDB::addAndAdaptName(), CModelAdd::addCompartments(), CModelAdd::addEvents(), CExperimentSet::addExperiment(), CModelAdd::addMetabolites(), CModelAdd::addModelValues(), CChemEqInterface::addModifier(), addParticleNumberToInitialValueMap(), CModelAdd::addReactions(), CReportDefinition::addTableElement(), addToInitialValueMap(), CModel::appendAllDependents(), SBMLImporter::areEqualFunctions(), CSBMLExporter::assignSBMLIdsToReactions(), CModel::buildMoieties(), CFitProblem::calculateStatistics(), CEvaluationTree::calls(), CFixLocalReactionParameters::changeModel(), CDataModel::changeModelParameter(), CSBMLExporter::checkForInitialAssignments(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), CSBMLExporter::checkForPiecewiseFunctions(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CFunctionAnalyzer::checkKineticFunction(), CModelAnalyzer::checkReaction(), CReaction::compile(), CEventAssignment::compile(), CMathObject::compileFlux(), CReaction::compileFunctionParameters(), CEvaluationTree::compileNodes(), CChemEqInterface::completeCompartments(), CReactionInterface::connectFromScratch(), CReactionInterface::connectNonMetabolites(), CDataObjectMap::contains(), CModel::convert2NonReversible(), CLRenderFlattener::convertGlobalToLocalStyle(), CMathExpression::convertToInitialExpression(), CMathExpression::copy(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), SEDMLUtils::createAmountMV(), CSBMLExporter::createAvogadroIfNeeded(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCMetabFromSpecies(), CSBMLExporter::createCompartment(), SBMLImporter::createCReactionFromReaction(), COutputAssistant::createDefaultOutput(), CSBMLExporter::createEvent(), SBMLImporter::createExpressionFromFunction(), CSBMLExporter::createFunctionDefinition(), CSBMLExporter::createFunctionDefinitions(), CReaction::createFunctionFromExpression(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createKineticExpression(), CSBMLExporter::createKineticLaw(), CModelExpansion::createLinearArray(), CFunction::createListOfParametersForMathML(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CMMLOutput::createParameterMapping(), CKinFunction::createParameters(), CFitProblem::createParameterSets(), CSBMLExporter::createReaction(), CModelExpansion::createRectangularArray(), CSBMLExporter::createRule(), CSBMLExporter::createSBMLDocument(), CReactionInterface::createUndoData(), CReaction::createUndoData(), CMetabNameInterface::createUniqueDisplayName(), CCSPMethod::CSPOutput(), CDerive::deriveBranch(), CMetabNameInterface::doesExist(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CExperimentObjectMap::elevateChildren(), CFitProblem::elevateChildren(), CDataObjectMap::erase(), CSEDMLExporter::exportAlgorithm(), CODEExporter::exportCompartments(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportExpression(), CODEExporter::exportKineticFunction(), CODEExporter::exportMetabolites(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValues(), CSEDMLExporter::exportNthPlot(), CSEDMLExporter::exportPlotItem(), CODEExporter::exportReacParamsAndFuncs(), CSEDMLExporter::exportReport(), CODEExporter::exportSimulatedObject(), CODEExporter::exportSingleFunction(), CODEExporterC::exportSingleFunction(), CODEExporterC::exportTitleData(), CLayout::exportToSBML(), SBMLImporter::findCorrespondingFunction(), SBMLImporter::findFunctionCalls(), CModel::findMoiety(), CReaction::getChildObjectUnits(), CArrayElementReference::getCN(), CFitItem::getCrossValidations(), CEvaluationNodeCall::getData(), CReactionInterface::getDeletedParameters(), CMetabNameInterface::getDisplayName(), CMathDependencyGraph::getDOTNodeId(), CFitItem::getExperiments(), CEFMTask::getFluxModeDescription(), CReactionInterface::getFunction(), CReactionInterface::getFunctionName(), CExperimentObjectMap::getLastNotIgnoredColumn(), CMathMl::getMMLName(), CLGraphicalObject::getModelObjectDisplayName(), CLGraphicalObject::getModelObjectName(), CModelParameter::getName(), CModelParameterSet::getName(), CExperimentObjectMap::getName(), CCopasiParameterGroup::getName(), CDataVectorReference< CType >::getObject(), CDataMatrixReference< CType >::getObject(), CReaction::getObject(), CDataContainer::getObject(), CDataArray::getObjectDisplayName(), CEvent::getObjectDisplayName(), CReaction::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), getObjectDisplayName(), CDataObjectReference< CType >::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), CPlotItem::getTitle(), CCopasiParameterGroup::getUniqueParameterName(), SEDMLUtils::getXPathForObjectAndType(), SBMLImporter::importFunctionDefinitions(), CChemEqInterface::init(), CReactionInterface::init(), CScanTask::initialize(), CCopasiTask::initialize(), CReaction::initializeParameterMapping(), CReaction::initializeParameters(), CStatistics::initObjects(), CFunction::initVariables(), CDataObjectMap::insert(), CSBMLExporter::isEventAssignmentSBMLCompatible(), CSBMLExporter::isEventSBMLCompatible(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CSBMLExporter::isModelSBMLCompatible(), CCopasiTask::isTaskValid(), ParameterGroupHandler::isUniqueParameter(), CEFMMethod::isValidProblem(), CMetab::load(), CMetabOld::load(), CReactionInterface::loadMappingAndValues(), CDataModel::loadModelParameterSets(), CReaction::loadOld(), CReaction::loadOneRole(), CModelMerging::mergeInExpression(), CCopasiXML::mergeUnitDefinitions(), CODEExporter::modifyTreeForMassAction(), CDataModel::openCombineArchive(), CCopasiParameter::operator=(), CCopasiParameterGroup::operator=(), CLGraphicalObject::operator=(), CMetab::operator=(), CUnitDefinition::operator=(), CFunctionParameters::operator==(), CODEExporter::preprocess(), CODEExporterC::preprocess(), printNameForKey(), CExperiment::printResult(), CCSPMethod::printResult(), CILDMMethod::printResult(), CILDMModifiedMethod::printResult(), CFitProblem::printResult(), CMoietiesProblem::printResult(), FunctionHandler::processEnd(), ParameterGroupHandler::processEnd(), PlotItemHandler::processEnd(), PlotSpecificationHandler::processEnd(), KineticLawHandler::processStart(), SourceParameterHandler::processStart(), CExperiment::read(), SBMLImporter::removeUnusedFunctions(), CSBMLExporter::replace_local_parameters(), CModelExpansion::replaceInExpression(), CModelExpansion::replaceInMetab(), CSBMLExporter::replaceSpeciesReferences(), CSBMLExporter::restore_local_parameters(), CCopasiXML::saveFunctionList(), CCopasiXML::saveLayoutList(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameterSets(), CCopasiXMLInterface::saveParameter(), CCopasiXML::savePlotList(), CCopasiXML::saveReportList(), CCopasiXML::saveTaskList(), CCopasiXML::saveUnitDefinitionList(), CMetab::setCompartment(), CSEDMLExporter::setCurrentTime(), CODEExporterC::setExportNameOfFunction(), CReaction::setFunctionFromExpressionTree(), CSBMLExporter::setFunctionSBMLIds(), CChemEqElement::setMetabolite(), CModelMerging::simpleCall(), CEvaluationNodeObject::toAST(), CReaction::toData(), CModelExpansion::updateExpression(), CModelParameter::updateModel(), VariableInfo::VariableInfo(), CReactionInterface::writeBackToReaction(), CMMLOutput::writeDifferentialEquations(), CFunction::writeMathML(), and CMMLOutput::writeRHS().
getObjectParent()
CDataContainer * CDataObject::getObjectParent () const
References mpObjectParent.
Referenced by CSBMLExporter::addInitialAssignmentsToModel(), CCompartment::addMetabolite(), CReportDefinition::addTableElement(), CModel::appendAllDependents(), applyAttributeChange(), SBMLImporter::applyStoichiometricExpressions(), CLyapWolfMethod::calculate(), CEFMAlgorithm::calculateFluxModes(), CCopasiProblem::CCopasiProblem(), CUndoData::change(), CUnitDefinitionDB::changeSymbol(), CSBMLExporter::checkForUnsupportedObjectReferences(), CMetab::CMetab(), CMathExpression::compile(), CEventAssignment::compile(), CTimeSeries::compile(), CExpression::compile(), CMathObject::compileDependentMass(), CMathObject::compileFlux(), CMathObject::compileInitialValue(), CEvaluationTree::compileNodes(), CMathObject::compileNoise(), CMathObject::compileParticleFlux(), CMathObject::compilePropensity(), CMathObject::compileRate(), CMathObject::compileReactionNoise(), CMathObject::compileReactionParticleNoise(), CMathObject::compileTotalMass(), CMathObject::compileTransitionTime(), CMathObject::compileValue(), CMethodFactory::copy(), CProblemFactory::copy(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), CMethodFactory::create(), CProblemFactory::create(), CModel::createEventsForTimeseries(), CExpression::createInitialExpression(), CMathEvent::createUpdateSequences(), CCSPMethod::cspstep(), CTimeSensMethod::CTimeSensMethod(), CTrajectoryMethod::CTrajectoryMethod(), CDerive::deriveBranch(), SBMLImporter::doMapping(), CLLayoutRenderer::draw_layout(), elevate(), CHybridNextReactionLSODAMethod::LSODA::evalF(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportExpression(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportSimulatedObject(), CModelExpansion::expressionContainsObject(), CSBMLExporter::findModelEntityDependencies(), CArrayElementReference::getCN(), CCopasiParameter::getCN(), CMathContainer::getCompartment(), CModel::getCorrespondingTransientObject(), CExperimentObjectMap::CDataColumn::getDefaultScale(), CMathDependencyGraph::getDOTNodeId(), CModelParameterSet::getIndex(), CObjectLists::getListOfConstObjects(), CMathMl::getMMLName(), CDataVectorReference< CType >::getObject(), CDataMatrixReference< CType >::getObject(), CReaction::getObject(), getObjectAncestor(), getObjectDataModel(), CDataArray::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), CDataObjectReference< CType >::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), CArrayElementReference::getValuePointer(), CLGraphicalObject::hasValidModelReference(), CSBMLExporter::hasVolumeAssignment(), CScanMethod::init(), CBitPatternMethod::initialize(), CBitPatternTreeMethod::initialize(), CEFMAlgorithm::initialize(), CEFMMethod::initialize(), CSSAMethod::initialize(), COptMethod::initialize(), COptMethodSS::initialize(), COptProblem::initialize(), CMathContainer::initializeAtolVector(), CTimeSensMethod::initializeDerivativesCalculations(), SBMLImporter::isConstantFlux(), CReaction::isLocalParameter(), SBMLImporter::isMassActionExpression(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CModel::isStateVariable(), CMIRIAMInfo::load(), CScanMethod::loop(), CModelMerging::mergeInExpression(), CUnitDefinition::operator=(), CLyapProblem::printResult(), CTrajectoryProblem::printResult(), CEFMProblem::printResult(), CLNAProblem::printResult(), CMCAProblem::printResult(), CSteadyStateMethod::process(), CCopasiParameterGroup::removeParameter(), CSBMLExporter::replace_local_parameters(), CModelExpansion::replaceInExpression(), CSBMLExporter::replaceSpeciesReferences(), CUnitDefinitionDB::replaceSymbol(), SEDMLUtils::resolveVariable(), SEDMLUtils::resolveXPath(), SBMLImporter::setCorrectUsage(), CEventAssignment::setObjectParent(), CEvent::setObjectParent(), CUnitDefinition::setSymbol(), CUnitDefinition::setup(), CEvaluationNodeObject::toAST(), CInfo::update(), CModelExpansion::updateExpression(), CSteadyStateTask::updateMatrices(), CModelParameter::updateModel(), VariableInfo::VariableInfo(), and CUnitDefinition::~CUnitDefinition().
getObjectType()
const std::string & CDataObject::getObjectType () const
References mObjectType.
Referenced by CReportDefinition::addTableElement(), CLStyle::appliesTo(), CEvent::CEvent(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CModelEntity::CModelEntity(), CReaction::CReaction(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createRule(), SBMLImporter::doMapping(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportExpression(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportSimulatedObject(), CCopasiParameter::getCN(), CMathMl::getMMLName(), CDataContainer::getObject(), getObjectAncestor(), CDataArray::getObjectDisplayName(), CCopasiReportSeparator::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), getObjectDisplayName(), CDataObjectReference< CType >::getObjectDisplayName(), CLLocalRenderInformation::getStyleForGraphicalObject(), SEDMLUtils::getXPathForObjectAndType(), CSBMLExporter::hasVolumeAssignment(), SBMLImporter::importEvent(), CSBMLExporter::isEventAssignmentSBMLCompatible(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CModelExpansion::replaceInExpression(), SEDMLUtils::resolveVariable(), CModelEntity::setStatus(), CModelExpansion::updateExpression(), and VariableInfo::VariableInfo().
getPrerequisites()
const CObjectInterface::ObjectSet & CDataObject::getPrerequisites () const override virtual
Retrieve the prerequisites, i.e., the objects which need to be evaluated before this.
Returns
const CObjectInterface::ObjectSet & prerequisites
Implements CObjectInterface.
Reimplemented in CMathExpression.
References mPrerequisits.
Referenced by CModelEntity::compile(), CMetab::compile(), CEventAssignment::compile(), CEvent::compile(), isPrerequisiteForContext(), and CEvaluationTree::mapObjectNodes().
getUnits()
const std::string CDataObject::getUnits () const virtual
Retrieve the units of the object.
Returns
std::string units
Reimplemented in CMetab, CDataContainer, CModelValue, CModel, and CCompartment.
References CDataContainer::getChildObjectUnits(), and mpObjectParent.
Referenced by CMetab::getChildObjectUnits(), CModelParameterGroup::getObjectUnit(), CEvaluationNodeObject::getUnit(), CReactionInterface::getUnit(), and CReactionInterface::getUnitVector().
getValidity()
const CValidity & CDataObject::getValidity () const override virtual
Get the aggregation of any issues associated with this object
Returns
const CValidity & validity
Implements CObjectInterface.
References mAggregateValidity.
Referenced by CDataContainer::add(), CDataModel::commonAfterLoad(), CModelEntity::compile(), CMetab::compile(), CMathObject::compileExpression(), CMathObject::createConvertedExpression(), CExpression::createInitialExpression(), COPASIHandler::processEnd(), and CDataContainer::remove().
getValueObject()
const CDataObject * CDataObject::getValueObject () const virtual
Reimplemented in CModelEntity, CMetab, CDataMatrixReference< CType >, CDataVectorReference< CType >, CDataObjectReference< CType >, CDataObjectReference< C_FLOAT64 >, CDataObjectReference< std::string >, CDataContainer, and CArrayElementReference.
Referenced by CEvaluationNodeObject::compile(), CReaction::compileFunctionParameters(), and CEvaluationNodeObject::mapObject().
getValuePointer()
void * CDataObject::getValuePointer () const override virtual
Retrieve a pointer to the value of the object
Implements CObjectInterface.
Reimplemented in CCopasiParameter, COptProblem, COptItem, CModelEntity, CMetab, CCopasiTimer, CDataMatrixReference< CType >, CDataVectorReference< CType >, CDataObjectReference< CType >, CDataObjectReference< C_FLOAT64 >, CDataObjectReference< std::string >, and CArrayElementReference.
Referenced by CFunctionParameterMap::addCallParameter(), addToInitialValueMap(), CSBMLExporter::checkForUnsupportedObjectReferences(), CMathObject::compileInitialValue(), CMathContainer::fetchInitialState(), CMathContainer::fetchState(), COptItem::getObjectDisplayName(), CMathContainer::getQuantity2NumberFactor(), COptItem::getStartValue(), CDataContainer::getValueObject(), CMathContainer::getValueObject(), CMathContainer::initializeAtolVector(), CMathContainer::map(), CMathContainer::pushAllTransientValues(), CMathContainer::pushInitialState(), CMathContainer::pushState(), CFunctionParameterMap::setCallParameter(), CSlider::sync(), CModelParameter::updateModel(), and CSlider::writeToObject().
hasFlag()
bool CDataObject::hasFlag (const Flag & flag) const
References CFlags< Enum >::isSet(), and mObjectFlag.
Referenced by CFunctionParameterMap::addCallParameter(), addToInitialValueMap(), CDataObject(), CSBMLExporter::checkForUnsupportedObjectReferences(), CEvaluationNodeObject::compile(), COptItem::compile(), CExperiment::compile(), CExperimentObjectMap::compile(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), SBMLImporter::doMapping(), CODEExporter::exportExpression(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportSimulatedObject(), CSBMLExporter::findModelEntityDependencies(), CDataHandler::generateObjectsFromName(), getCN(), CReaction::getObject(), CDataContainer::getObject(), getObjectDataModel(), getObjectDisplayName(), getValue(), CSensItem::getVariablesPointerList(), SBMLImporter::isConstantFlux(), SBMLImporter::isMassActionExpression(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CEvaluationNodeObject::mapObject(), CModelMerging::mergeInExpression(), CMathContainer::removeDataObject(), CSBMLExporter::replaceSpeciesReferences(), CFunctionParameterMap::setCallParameter(), COptItem::setObjectCN(), setObjectName(), CSlider::setSliderObject(), CEvaluationNodeObject::toAST(), and CSlider::writeToObject().
isPrerequisiteForContext()
bool CDataObject::isPrerequisiteForContext (const CObjectInterface * pObject, const CCore::SimulationContextFlag & context, const CObjectInterface::ObjectSet & changedObjects) const override virtual
Check whether a given object is a prerequisite for a context.
Parameters
const CObjectInterface * pObject
const CCore::SimulationContextFlag & context
const CObjectInterface::ObjectSet & changedObjects
Returns
bool isPrerequisiteForContext
Implements CObjectInterface.
Reimplemented in CDependentNumberReference, and CTotalNumberReference.
References getPrerequisites().
prerequisitsContains()
bool CDataObject::prerequisitsContains (const DataObjectSet & objects) const
References mPrerequisits.
print()
void CDataObject::print (std::ostream * ostream) const override virtual
This is the output method for any object. The default implementation provided with CDataObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Implements CObjectInterface.
Reimplemented in CCopasiParameter, CSteadyStateTask, CMCAProblem, CSensProblem, CFitProblem, COptProblem, CLNAProblem, CCopasiTimer, CDataVectorReference< CType >, CDataObjectReference< CType >, CDataObjectReference< C_FLOAT64 >, CDataObjectReference< std::string >, CArrayElementReference, CCopasiTask::CResult, CCopasiTask::CDescription, CCopasiProblem, CCopasiParameterGroup, CCopasiMethod, CEigen, CSensTask, COscillationProblem, COptPopulationMethod, CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLReferenceGlyph, CLGlyphWithCurve, CLGraphicalObject, CLTextGlyph, CLCompartmentGlyph, CLMetabGlyph, CLayout, CCrossSectionProblem, CDataString, CDataArray, and CAnalyticsProblem.
refreshAggregateValidity()
void CDataObject::refreshAggregateValidity () private
References CValidity::clear(), mAggregateValidity, mReferencedValidities, and mReferences.
Referenced by validityChanged(), and validityRemoved().
removeIssue()
void CDataObject::removeIssue (const CIssue & issue)
References CObjectInterface::mValidity, and CValidity::remove().
removeReference()
void CDataObject::removeReference (const CDataContainer * pReference)
References mReferences.
Referenced by CDataContainer::remove(), and setObjectParent().
sanitizeObjectName()
void CDataObject::sanitizeObjectName (std::string & name) static
Referenced by CDataVectorN< CType >::createUniqueName(), CDataVectorN< CType >::getIndex(), CCopasiParameterGroup::getParameter(), CRegisteredCommonName::sanitizeObjectNames(), and setObjectName().
setObjectName()
bool CDataObject::setObjectName (const std::string & name)
Set the name of the object. Note: An attempt set the name to "" results in the name being set to "No Name".
Parameters
const std::string & name
Returns
success
References CCommonName::escape(), getCN(), CDataContainer::getObject(), CRegisteredCommonName::handle(), hasFlag(), CRegisteredCommonName::isEnabled(), isNumber(), mObjectName, mpObjectParent, mReferences, NameVector, sanitizeObjectName(), and StaticString.
Referenced by CFunctionDB::addAndAdaptName(), CExperimentSet::addExperiment(), applyData(), CDataObject(), CEventAssignment::CEventAssignment(), CLayout::CLayout(), CModelEntity::compile(), CMetab::compile(), CLRenderFlattener::convertGlobalToLocalStyle(), CMathExpression::convertToInitialExpression(), CPlotItem::CPlotItem(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCModelFromSBMLDocument(), SBMLImporter::createCReactionFromReaction(), CReaction::createFunctionFromExpression(), COutputDefinitionVector::createPlotSpec(), CReportDefinitionVector::createReportDefinition(), CFitProblem::elevateChildren(), CEvaluationTree::fromData(), CModel::fromData(), CCopasiTask::fromData(), CReactionInterface::getFunction(), CCompartment::initObjects(), CMetab::initObjects(), CModel::initObjects(), CCompartment::load(), CMetab::load(), CMetabOld::load(), CModel::load(), CReaction::load(), CFunctionParameter::load(), CFunction::load(), CConfigurationFile::CXML::load(), CDataModel::loadModelParameterSets(), CCopasiParameter::operator=(), CCopasiParameterGroup::operator=(), CLGraphicalObject::operator=(), CMetab::operator=(), CUnitDefinition::operator=(), CDataString::operator=(), CompartmentHandler::processStart(), EventHandler::processStart(), FunctionHandler::processStart(), LayoutHandler::processStart(), MetaboliteHandler::processStart(), MethodHandler::processStart(), ModelHandler::processStart(), ModelParameterSetHandler::processStart(), ModelValueHandler::processStart(), ParameterDescriptionHandler::processStart(), PlotSpecificationHandler::processStart(), ReactionHandler::processStart(), ReportDefinitionHandler::processStart(), SourceParameterHandler::processStart(), SBMLImporter::renameMassActionParameters(), CModelExpansion::replaceInMetab(), CEvent::setDelayExpressionPtr(), CEventAssignment::setExpressionPtr(), CModelEntity::setExpressionPtr(), CReaction::setFunctionFromExpressionTree(), CModelEntity::setInitialExpressionPtr(), CChemEqElement::setMetabolite(), CModelEntity::setNoiseExpressionPtr(), CReaction::setNoiseExpressionPtr(), CEvent::setPriorityExpressionPtr(), CModelEntity::setStatus(), CEventAssignment::setTargetCN(), CPlotItem::setTitle(), CEvent::setTriggerExpressionPtr(), CFunction::splitFunction(), and CArrayElementReference::updateObjectName().
setObjectParent()
bool CDataObject::setObjectParent (const CDataContainer * pParent) virtual
Reimplemented in CCopasiParameter, CModelEntity, CMetab, CReaction, CMoiety, CModelParameterSet, CModel, CEvent, and CEventAssignment.
References addReference(), getCN(), CRegisteredCommonName::handle(), CRegisteredCommonName::isEnabled(), mpObjectParent, CDataContainer::remove(), and removeReference().
Referenced by CDataContainer::add(), CDataModel::commonAfterLoad(), CEvent::setDelayExpressionPtr(), CEventAssignment::setExpressionPtr(), CModelEntity::setExpressionPtr(), CModelEntity::setInitialExpressionPtr(), CModelEntity::setNoiseExpressionPtr(), CReaction::setNoiseExpressionPtr(), CEventAssignment::setObjectParent(), CEvent::setObjectParent(), CModel::setObjectParent(), CModelParameterSet::setObjectParent(), CMoiety::setObjectParent(), CReaction::setObjectParent(), CModelEntity::setObjectParent(), CCopasiParameter::setObjectParent(), CEvent::setPriorityExpressionPtr(), CEvent::setTriggerExpressionPtr(), CDataContainer::~CDataContainer(), and CMathContainer::~CMathContainer().
toData()
CData CDataObject::toData () const override virtual
Retrieve the data describing the object
Returns
CData data
Implements CUndoObjectInterface.
Reimplemented in CCopasiParameter, CModelEntity, CMetab, CDataContainer, CArrayElementReference, CUnitDefinition, CSlider, CCopasiTask, CCopasiParameterGroup, CReportDefinition, CPlotSpecification, CPlotItem, CFittingPoint, CReaction, CMoiety, CModelValue, CModelParameterSet, CModel, CMetabOld, CEvent, CEventAssignment, CCompartment, CReference, CModification, CMIRIAMInfo, CCreator, CBiologicalDescription, CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLReferenceGlyph, CLLocalStyle, CLLocalRenderInformation, CLLineEnding, CLGraphicalObject, CLGradientStop, CLGradientBase, CLTextGlyph, CLCompartmentGlyph, CLMetabGlyph, CLGlobalStyle, CLGlobalRenderInformation, CLColorDefinition, CLayout, CFunctionParameter, CFunction, CEvaluationTree, CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, CDataVectorN< CReportDefinition >, CDataVector< CType >, CDataVector< CLGlobalRenderInformation >, CDataVector< CModification >, CDataVector< CLMetabGlyph >, CDataVector< CLCompartmentGlyph >, CDataVector< CSlider >, CDataVector< CLReferenceGlyph >, CDataVector< CBiologicalDescription >, CDataVector< CLGlobalStyle >, CDataVector< CReference >, CDataVector< CLGradientStop >, CDataVector< CMoiety >, CDataVector< CLMetabReferenceGlyph >, CDataVector< CDataModel >, CDataVector< CChemEqElement >, CDataVector< CEvent >, CDataVector< CLReactionGlyph >, CDataVector< CLColorDefinition >, CDataVector< CMetab >, CDataVector< CLLocalRenderInformation >, CDataVector< CLGradientBase >, CDataVector< CPlotItem >, CDataVector< CDataObject >, CDataVector< CLTextGlyph >, CDataVector< CLLineEnding >, CDataVector< CFittingPoint >, CDataVector< CLLocalStyle >, CDataVector< CCreator >, CDataVector< CLGeneralGlyph >, CDataVector< CLGraphicalObject >, and CDataModel.
References CData::addProperty(), C_INVALID_INDEX, getCN(), CDataContainer::getIndex(), CUndoObjectInterface::getUuid(), mObjectFlag, mObjectName, mObjectType, mpObjectParent, mReferences, CData::OBJECT_FLAG, CData::OBJECT_INDEX, CData::OBJECT_NAME, CData::OBJECT_PARENT_CN, CData::OBJECT_REFERENCE_CN, CData::OBJECT_REFERENCE_INDEX, CData::OBJECT_REFERENCES, CData::OBJECT_TYPE, and CData::OBJECT_UUID.
Referenced by CReportDefinition::toData(), CArrayElementReference::toData(), and CDataContainer::toData().
validityChanged()
void CDataObject::validityChanged (const CValidity & changedValidity) override virtual
This method is called whenever the validity of the object or a contained object changes.
Parameters
const CValidity & changedValidity
Implements CObjectInterface.
References CValidity::empty(), mReferencedValidities, and refreshAggregateValidity().
Referenced by CDataContainer::add().
validityRemoved()
void CDataObject::validityRemoved (const CValidity & changedValidity)
This method is called whenever the validity of a contained object is removed.
Parameters
const CValidity & changedValidity
References mReferencedValidities, and refreshAggregateValidity().
Referenced by CDataContainer::remove().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CDataObject & o) friend
Member Data Documentation
mAggregateValidity
CValidity CDataObject::mAggregateValidity private
Referenced by getValidity(), refreshAggregateValidity(), and ~CDataObject().
mObjectDisplayName
std::string CDataObject::mObjectDisplayName mutable private
Referenced by getObject().
mObjectFlag
CFlags< Flag > CDataObject::mObjectFlag private
Referenced by createUndoData(), hasFlag(), and toData().
mObjectName
std::string CDataObject::mObjectName private
Referenced by createUndoData(), getCN(), getObject(), getObjectName(), setObjectName(), and toData().
mObjectType
std::string CDataObject::mObjectType private
Referenced by createUndoData(), getCN(), getObjectType(), and toData().
mpObjectDisplayName
CDataObjectReference< std::string >* CDataObject::mpObjectDisplayName mutable private
Referenced by getObject(), and ~CDataObject().
mpObjectName
CDataObjectReference< std::string >* CDataObject::mpObjectName mutable private
Referenced by getObject(), and ~CDataObject().
mpObjectParent
CDataContainer* CDataObject::mpObjectParent private
Referenced by applyData(), CDataObject(), createUndoData(), getCN(), getObject(), getObjectDisplayName(), getObjectParent(), getUnits(), setObjectName(), setObjectParent(), toData(), and ~CDataObject().
mPrerequisits
ObjectSet CDataObject::mPrerequisits protected
Referenced by CModelEntity::compile(), CReaction::compile(), CMetab::compile(), CEventAssignment::compile(), CEvent::compile(), COptItem::compile(), CEvaluationTree::compileNodes(), getPrerequisites(), CMetab::initCompartment(), COptProblem::initialize(), CEvaluationTree::mapObjectNodes(), prerequisitsContains(), CReaction::setFunction(), and COptItem::updatePrerequisites().
mReferencedValidities
std::set< const CValidity * > CDataObject::mReferencedValidities private
Referenced by refreshAggregateValidity(), validityChanged(), and validityRemoved().
mReferences
std::set< CDataContainer * > CDataObject::mReferences protected
Referenced by addReference(), createUndoData(), refreshAggregateValidity(), removeReference(), setObjectName(), toData(), and ~CDataObject().
The documentation for this class was generated from the following files:
CDataObject.h
CDataObject.cpp