COPASI API: CReportTable Class Reference
CReportTable Class Reference
#include <CReportBody.h>
Public Member Functions
void cleanup ()
CReportTable ()
std::vector< CCommonName > * getObjectNameVector ()
const std::string & getSeparator ()
bool printTitle ()
void setObjectNameVector (std::vector< CCommonName > *objectVector)
void setPrintTitle (bool printTitle)
void setSeparator (const std::string separator)
~CReportTable ()
Private Attributes
std::vector< CCommonName > * mpObjectNameVector
bool mPrintTitle
std::string mSeparator
Constructor & Destructor Documentation
CReportTable()
CReportTable::CReportTable ()
Default constructor.
~CReportTable()
CReportTable::~CReportTable ()
Destructor.
References cleanup().
Member Function Documentation
cleanup()
void CReportTable::cleanup ()
cleanup
References mpObjectNameVector, and pdelete.
Referenced by ~CReportTable().
getObjectNameVector()
std::vector<CCommonName>* CReportTable::getObjectNameVector () inline
gets the Object tag of the Table tag
References mpObjectNameVector.
getSeparator()
const std::string& CReportTable::getSeparator () inline
gets the Separator attribute of the Table tag
References mSeparator.
printTitle()
bool CReportTable::printTitle () inline
gets the printTitle of the Table tag
References mPrintTitle.
Referenced by setPrintTitle().
setObjectNameVector()
void CReportTable::setObjectNameVector (std::vector< CCommonName > * objectVector) inline
sets the Object tag of the Table tag
References mpObjectNameVector.
setPrintTitle()
void CReportTable::setPrintTitle (bool printTitle) inline
sets the print Title of the Table tag
References mPrintTitle, and printTitle().
setSeparator()
void CReportTable::setSeparator (const std::string separator) inline
sets the separator attribute of the Table tag
References mSeparator.
Member Data Documentation
mpObjectNameVector
std::vector<CCommonName>* CReportTable::mpObjectNameVector private
Referenced by cleanup(), getObjectNameVector(), and setObjectNameVector().
mPrintTitle
bool CReportTable::mPrintTitle private
Referenced by printTitle(), and setPrintTitle().
mSeparator
std::string CReportTable::mSeparator private
Referenced by getSeparator(), and setSeparator().
The documentation for this class was generated from the following files:
CReportBody.h
CReportBody.cpp