COPASI API: CEvaluationLexer Class Reference
CEvaluationLexer Class Reference
#include <CEvaluationLexer.h>
Public Member Functions
CEvaluationLexer (std::istream &arg_yyin, std::ostream &arg_yyout)
CEvaluationLexer (std::istream *arg_yyin=0, std::ostream *arg_yyout=0)
virtual void switch_streams (std::istream &new_in, std::ostream &new_out)
virtual void switch_streams (std::istream *new_in=0, std::ostream *new_out=0)
yy_buffer_state * yy_create_buffer (std::istream &s, int size)
yy_buffer_state * yy_create_buffer (std::istream *s, int size)
void yy_delete_buffer (yy_buffer_state *b)
void yy_switch_to_buffer (yy_buffer_state *new_buffer)
virtual int yylex ()
void yypop_buffer_state ()
void yypush_buffer_state (yy_buffer_state *new_buffer)
void yyrestart (std::istream &s)
void yyrestart (std::istream *s)
virtual int yywrap ()
virtual ~ CEvaluationLexer ()
Public Member Functions inherited from FlexLexer
int debug () const
int lineno () const
void set_debug (int flag)
int YYLeng () const
int yylex (std::istream &new_in, std::ostream &new_out)
int yylex (std::istream *new_in, std::ostream *new_out=0)
const char * YYText () const
virtual ~FlexLexer ()
Public Member Functions inherited from CEvaluationParserBase
CEvaluationParserBase ()
size_t getErrorPosition ()
std::vector< CEvaluationNode * > * getNodeList ()
CEvaluationNode * getRootNode ()
const CEvaluationNode::ValueType & getValueType () const
virtual int yyparse ()
virtual ~ CEvaluationParserBase ()
Protected Member Functions
virtual void LexerError (const char *msg)
virtual int LexerInput (char *buf, int max_size)
virtual void LexerOutput (const char *buf, int size)
void yy_flush_buffer (yy_buffer_state *b)
int yy_get_next_buffer ()
yy_state_type yy_get_previous_state ()
void yy_init_buffer (yy_buffer_state *b, std::istream &s)
void yy_load_buffer_state ()
void yy_pop_state ()
void yy_push_state (int new_state)
int yy_top_state ()
yy_state_type yy_try_NUL_trans (yy_state_type current_state)
void yyensure_buffer_stack (void)
int yyinput ()
void yyunput (int c, char *buf_ptr)
Protected Attributes
yy_buffer_state ** yy_buffer_stack
size_t yy_buffer_stack_max
size_t yy_buffer_stack_top
char * yy_c_buf_p
int yy_did_buffer_switch_on_eof
int yy_full_lp
char * yy_full_match
int * yy_full_state
char yy_hold_char
int yy_init
char * yy_last_accepting_cpos
yy_state_type yy_last_accepting_state
int yy_looking_for_trail_begin
int yy_lp
int yy_more_flag
int yy_more_len
int yy_more_offset
int yy_n_chars
int yy_prev_more_offset
int yy_start
int * yy_start_stack
int yy_start_stack_depth
int yy_start_stack_ptr
yy_state_type * yy_state_buf
yy_state_type * yy_state_ptr
std::istream yyin
std::ostream yyout
Protected Attributes inherited from FlexLexer
int yy_flex_debug
int yyleng
int yylineno
char * yytext
Protected Attributes inherited from CEvaluationParserBase
CEvaluationNode * mpNode
std::vector< CEvaluationNode * > * mpNodeList
size_t mPosition
CEvaluationNode * mpRootNode
CEvaluationNode::ValueType mValueType
Private Member Functions
void ctor_common ()
Constructor & Destructor Documentation
CEvaluationLexer() [1/2]
CEvaluationLexer::CEvaluationLexer (std::istream & arg_yyin, std::ostream & arg_yyout)
References ctor_common().
CEvaluationLexer() [2/2]
CEvaluationLexer::CEvaluationLexer (std::istream * arg_yyin = 0, std::ostream * arg_yyout = 0)
References ctor_common().
~ CEvaluationLexer()
virtual CEvaluationLexer::~ CEvaluationLexer () virtual
Member Function Documentation
ctor_common()
void CEvaluationLexer::ctor_common () private
References yyFlexLexer::yy_buffer_stack, yyFlexLexer::yy_buffer_stack_max, yyFlexLexer::yy_buffer_stack_top, yyFlexLexer::yy_c_buf_p, yyFlexLexer::yy_did_buffer_switch_on_eof, FlexLexer::yy_flex_debug, yyFlexLexer::yy_init, yyFlexLexer::yy_looking_for_trail_begin, yyFlexLexer::yy_more_flag, yyFlexLexer::yy_more_len, yyFlexLexer::yy_more_offset, yyFlexLexer::yy_prev_more_offset, yyFlexLexer::yy_start, yyFlexLexer::yy_start_stack, yyFlexLexer::yy_start_stack_depth, yyFlexLexer::yy_start_stack_ptr, yyFlexLexer::yy_state_buf, and FlexLexer::yylineno.
Referenced by CEvaluationLexer().
LexerError()
void CEvaluationLexer::LexerError (const char * msg) protected virtual
References YY_EXIT_FAILURE.
LexerInput()
int CEvaluationLexer::LexerInput (char * buf, int max_size) protected virtual
LexerOutput()
void CEvaluationLexer::LexerOutput (const char * buf, int size) protected virtual
References yyFlexLexer::yyout.
switch_streams() [1/2]
void CEvaluationLexer::switch_streams (std::istream & new_in, std::ostream & new_out) virtual
Implements FlexLexer.
References YY_BUF_SIZE, yyFlexLexer::yy_create_buffer(), YY_CURRENT_BUFFER, yyFlexLexer::yy_delete_buffer(), yyFlexLexer::yy_switch_to_buffer(), and yyFlexLexer::yyout.
switch_streams() [2/2]
void CEvaluationLexer::switch_streams (std::istream * new_in = 0, std::ostream * new_out = 0) virtual
Implements FlexLexer.
References yyFlexLexer::switch_streams(), yyFlexLexer::yyin, and yyFlexLexer::yyout.
yy_create_buffer() [1/2]
YY_BUFFER_STATE CEvaluationLexer::yy_create_buffer (std::istream & file, int size) virtual
Allocate and initialize an input buffer state.
Parameters
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
Returns
the allocated buffer state.
Implements FlexLexer.
References yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yyFlexLexer::yy_init_buffer(), yy_buffer_state::yy_is_our_buffer, and yyalloc.
yy_create_buffer() [2/2]
YY_BUFFER_STATE CEvaluationLexer::yy_create_buffer (std::istream * file, int size) virtual
Delegate creation of buffers to the new version that takes an istream reference.
Parameters
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
Returns
the allocated buffer state.
Implements FlexLexer.
References yyFlexLexer::yy_create_buffer().
yy_delete_buffer()
void CEvaluationLexer::yy_delete_buffer (yy_buffer_state * b) virtual
Destroy the buffer.
Parameters
b a buffer created with yy_create_buffer()
Implements FlexLexer.
References yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_buffer_state::yy_is_our_buffer, and yyfree.
yy_flush_buffer()
void CEvaluationLexer::yy_flush_buffer (yy_buffer_state * b) protected
Discard all buffered characters. On the next scan, YY_INPUT will be called.
Parameters
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, yyFlexLexer::yy_load_buffer_state(), and yy_buffer_state::yy_n_chars.
yy_get_next_buffer()
int CEvaluationLexer::yy_get_next_buffer () protected
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyFlexLexer::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyFlexLexer::yy_n_chars, YY_READ_BUF_SIZE, yyFlexLexer::yyin, yyrealloc, yyFlexLexer::yyrestart(), and yytext_ptr.
yy_get_previous_state()
yy_state_type CEvaluationLexer::yy_get_previous_state () protected
References yyFlexLexer::yy_c_buf_p, YY_MORE_ADJ, yyFlexLexer::yy_start, and yytext_ptr.
yy_init_buffer()
void CEvaluationLexer::yy_init_buffer (yy_buffer_state * b, std::istream & s) protected
References yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yyFlexLexer::yy_flush_buffer(), yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
yy_load_buffer_state()
void CEvaluationLexer::yy_load_buffer_state () protected
References yyFlexLexer::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyFlexLexer::yy_hold_char, yyFlexLexer::yy_n_chars, yyFlexLexer::yyin, and yytext_ptr.
yy_pop_state()
void CEvaluationLexer::yy_pop_state () protected
References BEGIN, YY_FATAL_ERROR, yyFlexLexer::yy_start_stack, and yyFlexLexer::yy_start_stack_ptr.
yy_push_state()
void CEvaluationLexer::yy_push_state (int new_state) protected
References BEGIN, YY_FATAL_ERROR, YY_START, yyFlexLexer::yy_start_stack, yyFlexLexer::yy_start_stack_depth, YY_START_STACK_INCR, yyFlexLexer::yy_start_stack_ptr, yyalloc, and yyrealloc.
yy_switch_to_buffer()
void CEvaluationLexer::yy_switch_to_buffer (yy_buffer_state * new_buffer) virtual
Switch to a different input buffer.
Parameters
new_buffer The new input buffer.
Implements FlexLexer.
References yyFlexLexer::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyFlexLexer::yy_did_buffer_switch_on_eof, yyFlexLexer::yy_hold_char, yyFlexLexer::yy_load_buffer_state(), yyFlexLexer::yy_n_chars, and yyFlexLexer::yyensure_buffer_stack().
yy_top_state()
int CEvaluationLexer::yy_top_state () protected
References yyFlexLexer::yy_start_stack, and yyFlexLexer::yy_start_stack_ptr.
yy_try_NUL_trans()
yy_state_type CEvaluationLexer::yy_try_NUL_trans (yy_state_type current_state) protected
References yyFlexLexer::yy_c_buf_p.
yyensure_buffer_stack()
void CEvaluationLexer::yyensure_buffer_stack (void) protected
References yyFlexLexer::yy_buffer_stack, yyFlexLexer::yy_buffer_stack_max, yyFlexLexer::yy_buffer_stack_top, YY_FATAL_ERROR, yyalloc, and yyrealloc.
yyinput()
int CEvaluationLexer::yyinput () protected
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yyFlexLexer::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyFlexLexer::yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yyFlexLexer::yy_get_next_buffer(), yyFlexLexer::yy_hold_char, yyFlexLexer::yy_n_chars, YY_NEW_FILE, yyFlexLexer::yyin, yyFlexLexer::yyinput(), yyFlexLexer::yyrestart(), yytext_ptr, and yyFlexLexer::yywrap().
yylex()
int CEvaluationLexer::yylex () virtual
The main scanner function which does all the work.
Implements FlexLexer.
References YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and YY_USER_INIT.
yypop_buffer_state()
void CEvaluationLexer::yypop_buffer_state (void)
Removes and deletes the top of the stack, if present. The next element becomes the new top.
References yyFlexLexer::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyFlexLexer::yy_delete_buffer(), yyFlexLexer::yy_did_buffer_switch_on_eof, and yyFlexLexer::yy_load_buffer_state().
yypush_buffer_state()
void CEvaluationLexer::yypush_buffer_state (yy_buffer_state * new_buffer)
Pushes the new state onto the stack. The new state becomes the current state. This function will allocate the stack if necessary.
Parameters
new_buffer The new state.
References yyFlexLexer::yy_buffer_stack_top, yyFlexLexer::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyFlexLexer::yy_did_buffer_switch_on_eof, yyFlexLexer::yy_hold_char, yyFlexLexer::yy_load_buffer_state(), yyFlexLexer::yy_n_chars, and yyFlexLexer::yyensure_buffer_stack().
yyrestart() [1/2]
void CEvaluationLexer::yyrestart (std::istream & input_file) virtual
Immediately switch to a different input stream.
Parameters
input_file A readable stream.
Note
This function does not reset the start condition to INITIAL .
Implements FlexLexer.
References YY_BUF_SIZE, yyFlexLexer::yy_create_buffer(), YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyFlexLexer::yy_init_buffer(), yyFlexLexer::yy_load_buffer_state(), yyFlexLexer::yyensure_buffer_stack(), and yyFlexLexer::yyin.
yyrestart() [2/2]
void CEvaluationLexer::yyrestart (std::istream * input_file) virtual
Delegate to the new version that takes an istream reference.
Parameters
input_file A readable stream.
Note
This function does not reset the start condition to INITIAL .
Implements FlexLexer.
References yyFlexLexer::yyin, and yyFlexLexer::yyrestart().
yyunput()
void CEvaluationLexer::yyunput (int c, char * buf_ptr) protected
References yyFlexLexer::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, YY_FATAL_ERROR, yyFlexLexer::yy_hold_char, yyFlexLexer::yy_n_chars, and yytext_ptr.
yywrap()
virtual int CEvaluationLexer::yywrap () inline virtual
Member Data Documentation
yy_buffer_stack
yy_buffer_state** CEvaluationLexer::yy_buffer_stack protected
Stack as an array.
yy_buffer_stack_max
size_t CEvaluationLexer::yy_buffer_stack_max protected
capacity of stack.
yy_buffer_stack_top
size_t CEvaluationLexer::yy_buffer_stack_top protected
index of top of stack.
yy_c_buf_p
char* CEvaluationLexer::yy_c_buf_p protected
yy_did_buffer_switch_on_eof
int CEvaluationLexer::yy_did_buffer_switch_on_eof protected
yy_full_lp
int CEvaluationLexer::yy_full_lp protected
yy_full_match
char* CEvaluationLexer::yy_full_match protected
yy_full_state
int* CEvaluationLexer::yy_full_state protected
yy_hold_char
char CEvaluationLexer::yy_hold_char protected
yy_init
int CEvaluationLexer::yy_init protected
yy_last_accepting_cpos
char* CEvaluationLexer::yy_last_accepting_cpos protected
yy_last_accepting_state
yy_state_type CEvaluationLexer::yy_last_accepting_state protected
yy_looking_for_trail_begin
int CEvaluationLexer::yy_looking_for_trail_begin protected
yy_lp
int CEvaluationLexer::yy_lp protected
yy_more_flag
int CEvaluationLexer::yy_more_flag protected
yy_more_len
int CEvaluationLexer::yy_more_len protected
yy_more_offset
int CEvaluationLexer::yy_more_offset protected
yy_n_chars
int CEvaluationLexer::yy_n_chars protected
yy_prev_more_offset
int CEvaluationLexer::yy_prev_more_offset protected
yy_start
int CEvaluationLexer::yy_start protected
yy_start_stack
int* CEvaluationLexer::yy_start_stack protected
yy_start_stack_depth
int CEvaluationLexer::yy_start_stack_depth protected
yy_start_stack_ptr
int CEvaluationLexer::yy_start_stack_ptr protected
yy_state_buf
yy_state_type* CEvaluationLexer::yy_state_buf protected
yy_state_ptr
yy_state_type* CEvaluationLexer::yy_state_ptr protected
yyin
std::istream CEvaluationLexer::yyin protected
yyout
std::ostream CEvaluationLexer::yyout protected
The documentation for this class was generated from the following files:
CEvaluationLexer.h
CEvaluationLexer_lex.cpp