COPASI API: CConfigurationFile Class Reference
CConfigurationFile Class Reference
#include <CConfigurationFile.h>
Classes
class CXML
Public Member Functions
CConfigurationFile (const CConfigurationFile &src, const CDataContainer *pParent)
CConfigurationFile (const std::string &name="Configuration", const CDataContainer *pParent=NO_PARENT)
bool displayPopulations () const
virtual bool elevateChildren ()
bool enableAdditionalOptimizationParameters () const
const std::string getApplicationFont () const
CCheckForUpdates & getCheckForUpdates ()
const std::string & getCurrentAuthorEmail () const
const std::string & getCurrentAuthorFamilyName () const
const std::string & getCurrentAuthorGivenName () const
const std::string & getCurrentAuthorOrganization () const
bool getDisableJIT () const
C_INT32 getDoublePrecision () const
const std::string getProxyPassword () const
C_INT32 getProxyPort () const
const std::string getProxyServer () const
const std::string getProxyUser () const
CRecentFiles & getRecentFiles ()
CMIRIAMResources & getRecentMIRIAMResources ()
CRecentFiles & getRecentSBMLFiles ()
CRecentFiles & getRecentSEDMLFiles ()
const std::string getWorkingDirectory () const
virtual bool load ()
bool normalizePerExperiment () const
const CConfigurationFile & operator= (const CConfigurationFile &rhs)
const CConfigurationFile & operator= (const CCopasiParameterGroup &rhs)
bool resizeToContents () const
virtual bool save ()
void setApplicationFont (const std::string &applicationFont)
void setCurrentAuthorEmail (const std::string &CurrentAuthorEmail)
void setCurrentAuthorFamilyName (const std::string &CurrentAuthorFamilyName)
void setCurrentAuthorGivenName (const std::string &CurrentAuthorGivenName)
void setCurrentAuthorOrganization (const std::string &CurrentAuthorOrganization)
void setDisableJIT (bool disableJIT)
void setDisplayPopulations (bool flag)
void setDoublePrecision (C_INT32 precision)
void setEnableAdditionalOptimizationParameters (bool enableAdditionalOptimizationParameters)
void setNormalizePerExperiment (bool flag)
void setProxyPassword (const std::string &proxyPassword)
void setProxyPort (C_INT32 proxyPort)
void setProxyServer (const std::string &proxyServer)
void setProxyUser (const std::string &proxyUser)
void setRecentMIRIAMResources (const CMIRIAMResources &miriamResources)
void setResizeToContents (bool flag)
void setUseAdvancedEditing (bool useAdvancedEditing)
void setUseAdvancedSliders (bool useAdvancedSliders)
void setUseOpenGL (bool useOpenGL)
void setValidateUnits (bool validateUnits)
void setWorkingDirectory (const std::string &workingDirectory)
bool showItemIssues (CIssue::eKind kind) const
bool useAdvancedEditing () const
bool useAdvancedSliders () const
bool useOpenGL () const
bool validateUnits () const
virtual ~CConfigurationFile ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Private Member Functions
void initializeParameter ()
Private Attributes
std::string * mpApplicationFont
CCheckForUpdates * mpCheckForUpdates
std::string * mpCurrentAuthorEmail
std::string * mpCurrentAuthorFamilyName
std::string * mpCurrentAuthorGivenName
std::string * mpCurrentAuthorOrganization
bool * mpDisableJIT
CCopasiParameterGroup * mpDisplayIssueKinds
CCopasiParameterGroup * mpDisplayIssueSeverity
bool * mpDisplayPopulations
bool * mpEnableAdditionalOptimizationParameters
bool * mpNormalizePerExperiment
C_INT32 * mpPrecision
std::string * mpProxyPass
C_INT32 * mpProxyPort
std::string * mpProxyServer
std::string * mpProxyUser
CRecentFiles * mpRecentFiles
CMIRIAMResources * mpRecentMIRIAMResources
CRecentFiles * mpRecentSBMLFiles
CRecentFiles * mpRecentSEDMLFiles
bool * mpResizeToContents
bool * mpUseAdvancedEditing
bool * mpUseAdvancedSliders
bool * mpUseOpenGL
bool * mpValidateUnits
std::string * mpWorkingDirectory
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CConfigurationFile() [1/2]
CConfigurationFile::CConfigurationFile (const std::string & name = "Configuration", const CDataContainer * pParent = NO_PARENT)
Default constructor
Parameters
const std::string & name (default: Configuration)
const CDataContainer * pParent (default: NULL)
References initializeParameter().
CConfigurationFile() [2/2]
CConfigurationFile::CConfigurationFile (const CConfigurationFile & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CConfigurationFile & src
const CDataContainer * pParent (default: NULL)
References initializeParameter().
~CConfigurationFile()
CConfigurationFile::~CConfigurationFile () virtual
Destructor
Member Function Documentation
displayPopulations()
bool CConfigurationFile::displayPopulations () const
Returns
a flag on whether populations should be displayed during optimization / parameter estimation
References mpDisplayPopulations.
elevateChildren()
bool CConfigurationFile::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
References CCopasiParameterGroup::getGroup(), mpCheckForUpdates, mpRecentFiles, mpRecentMIRIAMResources, mpRecentSBMLFiles, mpRecentSEDMLFiles, and CMIRIAMResourceObject::setMIRIAMResources().
Referenced by initializeParameter().
enableAdditionalOptimizationParameters()
bool CConfigurationFile::enableAdditionalOptimizationParameters () const
Returns
a flag on whether to enable additional parameters in optimization methods
References mpEnableAdditionalOptimizationParameters.
Referenced by setEnableAdditionalOptimizationParameters().
getApplicationFont()
const std::string CConfigurationFile::getApplicationFont () const
Retrieve the application font.
Returns
const std::string & applicationFont
References mpApplicationFont.
getCheckForUpdates()
CCheckForUpdates & CConfigurationFile::getCheckForUpdates ()
Returns
auto update settings
References mpCheckForUpdates.
getCurrentAuthorEmail()
const std::string & CConfigurationFile::getCurrentAuthorEmail () const
Retrieve the Current Author Email
Returns
const std::string & CurrentAuthorEmail
References mpCurrentAuthorEmail.
Referenced by CMIRIAMInfo::addDefaultCreator().
getCurrentAuthorFamilyName()
const std::string & CConfigurationFile::getCurrentAuthorFamilyName () const
Retrieve the Current Author Familyname
Returns
const std::string & CurrentAuthorFamilyName
References mpCurrentAuthorFamilyName.
Referenced by CMIRIAMInfo::addDefaultCreator().
getCurrentAuthorGivenName()
const std::string & CConfigurationFile::getCurrentAuthorGivenName () const
Retrieve the Current Author GivenName
Returns
const std::string & CurrentAuthorGivenName
References mpCurrentAuthorGivenName.
Referenced by CMIRIAMInfo::addDefaultCreator().
getCurrentAuthorOrganization()
const std::string & CConfigurationFile::getCurrentAuthorOrganization () const
Retrieve the Current Author Organization
Returns
const std::string & CurrentAuthorOrganization
References mpCurrentAuthorOrganization.
Referenced by CMIRIAMInfo::addDefaultCreator().
getDisableJIT()
bool CConfigurationFile::getDisableJIT () const
Return whether JIT is disabled
Returns
bool disbaleJIT
References mpDisableJIT.
Referenced by CJitCompiler::JitEnabled().
getDoublePrecision()
C_INT32 CConfigurationFile::getDoublePrecision () const
Returns
the double precision to be used when converting to string
References mpPrecision.
getProxyPassword()
const std::string CConfigurationFile::getProxyPassword () const
Retrieve the proxy user password
References mpProxyPass.
getProxyPort()
C_INT32 CConfigurationFile::getProxyPort () const
Retrieve the proxy port
References mpProxyPort.
getProxyServer()
const std::string CConfigurationFile::getProxyServer () const
Retrieve the proxy server
References mpProxyServer.
getProxyUser()
const std::string CConfigurationFile::getProxyUser () const
Retrieve the proxy user name
References mpProxyUser.
getRecentFiles()
CRecentFiles & CConfigurationFile::getRecentFiles ()
Retrieve the list of recent files
Returns
CRecentFiles & recentFiles
References mpRecentFiles.
getRecentMIRIAMResources()
CMIRIAMResources & CConfigurationFile::getRecentMIRIAMResources ()
Retrieve the list of recent MIRIAM Resources
Returns
CMIRIAMResources & recentMIRIAMResources
References mpRecentMIRIAMResources.
Referenced by CMIRIAMResources::isCitation().
getRecentSBMLFiles()
CRecentFiles & CConfigurationFile::getRecentSBMLFiles ()
Retrieve the list of recent SBML files
Returns
CRecentFiles & recentSBMLFiles
References mpRecentSBMLFiles.
getRecentSEDMLFiles()
CRecentFiles & CConfigurationFile::getRecentSEDMLFiles ()
Retrieve the list of recent SEDML files
Returns
CRecentFiles & recentSEDMLFiles
References mpRecentSEDMLFiles.
getWorkingDirectory()
const std::string CConfigurationFile::getWorkingDirectory () const
Retrieve the working directory
Returns
const std::string & workingDirectory
References mpWorkingDirectory.
initializeParameter()
void CConfigurationFile::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
References CIssue::__SIZE, CCopasiParameterGroup::assertGroup(), CCopasiParameterGroup::assertParameter(), CCopasiParameter::basic, CCopasiParameterGroup::beginIndex(), CCopasiParameter::BOOL, CCopasiParameter::editable, elevateChildren(), CCopasiParameterGroup::endIndex(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getUserInterfaceFlag(), CCopasiParameter::getValue(), CCopasiParameter::INT, CIssue::kindNames, mpApplicationFont, mpCurrentAuthorEmail, mpCurrentAuthorFamilyName, mpCurrentAuthorGivenName, mpCurrentAuthorOrganization, mpDisableJIT, mpDisplayIssueKinds, mpDisplayIssueSeverity, mpDisplayPopulations, mpEnableAdditionalOptimizationParameters, mpNormalizePerExperiment, mpPrecision, mpProxyPass, mpProxyPort, mpProxyServer, mpProxyUser, mpResizeToContents, mpUseAdvancedEditing, mpUseAdvancedSliders, mpUseOpenGL, mpValidateUnits, mpWorkingDirectory, CCopasiParameterGroup::removeParameter(), CCopasiParameter::setUserInterfaceFlag(), CIssue::severityNames, CCopasiParameter::STRING, and toEnum().
Referenced by CConfigurationFile(), load(), and operator=().
load()
bool CConfigurationFile::load () virtual
Load the configuration file.
Returns
bool success
References CConfigurationFile::CXML::getConfiguration(), CCopasiParameterGroup::getGroup(), CMIRIAMResources::getResourceList(), COptions::getValue(), initializeParameter(), CMIRIAMResources::initializeParameter(), mpRecentMIRIAMResources, CDirEntry::Separator, and CCopasiParameterGroup::size().
Referenced by CRootContainer::initializeChildren().
normalizePerExperiment()
bool CConfigurationFile::normalizePerExperiment () const
Returns
a flag on whether weights in Parameter Estimation should be normalized per experiment
References mpNormalizePerExperiment.
operator=() [1/2]
const CConfigurationFile & CConfigurationFile::operator= (const CConfigurationFile & rhs)
References operator=().
operator=() [2/2]
const CConfigurationFile & CConfigurationFile::operator= (const CCopasiParameterGroup & rhs)
Assignment operator
Parameters
const CCopasiParameterGroup & rhs
Returns
const CConfigurationFile & self
References initializeParameter(), and CCopasiParameterGroup::operator=().
Referenced by operator=().
resizeToContents()
bool CConfigurationFile::resizeToContents () const
Returns
a flag on whether the GUI should resize tables to contents
References mpResizeToContents.
save()
bool CConfigurationFile::save () virtual
Save the configuration file.
Returns
bool success
References CDirEntry::dirName(), COptions::getValue(), and CConfigurationFile::CXML::setConfiguration().
Referenced by CRootContainer::~CRootContainer().
setApplicationFont()
void CConfigurationFile::setApplicationFont (const std::string & applicationFont)
Set the applications font.
Parameters
const std::string & applicationFont
References mpApplicationFont.
setCurrentAuthorEmail()
void CConfigurationFile::setCurrentAuthorEmail (const std::string & CurrentAuthorEmail)
Set the Current Author Email.
Parameters
const std::string & CurrentAuthorEmail
References mpCurrentAuthorEmail.
setCurrentAuthorFamilyName()
void CConfigurationFile::setCurrentAuthorFamilyName (const std::string & CurrentAuthorFamilyName)
Set the Current Author Familyname.
Parameters
const std::string & CurrentAuthorFamilyName
References mpCurrentAuthorFamilyName.
setCurrentAuthorGivenName()
void CConfigurationFile::setCurrentAuthorGivenName (const std::string & CurrentAuthorGivenName)
Set the Current Author Given Name.
Parameters
const std::string & CurrentAuthorGivenName
References mpCurrentAuthorGivenName.
setCurrentAuthorOrganization()
void CConfigurationFile::setCurrentAuthorOrganization (const std::string & CurrentAuthorOrganization)
Set the Current Author Organization.
Parameters
const std::string & CurrentAuthorOrganization
References mpCurrentAuthorOrganization.
setDisableJIT()
void CConfigurationFile::setDisableJIT (bool disableJIT)
Sets the whether JIT compilation is diable
Parameters
bool disableJIT
References mpDisableJIT.
setDisplayPopulations()
void CConfigurationFile::setDisplayPopulations (bool flag)
Set whether weights in Parameter Estimation should be normalized per experiment
References mpDisplayPopulations.
setDoublePrecision()
void CConfigurationFile::setDoublePrecision (C_INT32 precision)
sets the double precision to be used when converting numbers to string
References mpPrecision.
setEnableAdditionalOptimizationParameters()
void CConfigurationFile::setEnableAdditionalOptimizationParameters (bool enableAdditionalOptimizationParameters)
Set whether to enable additional parameters in optimization methods
References enableAdditionalOptimizationParameters(), and mpEnableAdditionalOptimizationParameters.
setNormalizePerExperiment()
void CConfigurationFile::setNormalizePerExperiment (bool flag)
Set whether weights in Parameter Estimation should be normalized per experiment
References mpNormalizePerExperiment.
setProxyPassword()
void CConfigurationFile::setProxyPassword (const std::string & proxyPassword)
Set the proxy user password.
Parameters
proxyPassword the proxy password
References mpProxyPass.
setProxyPort()
void CConfigurationFile::setProxyPort (C_INT32 proxyPort)
Set the proxy port.
Parameters
proxyPort the proxy port
References mpProxyPort.
setProxyServer()
void CConfigurationFile::setProxyServer (const std::string & proxyServer)
Set the proxy server.
Parameters
proxyServer the proxy server
References mpProxyServer.
setProxyUser()
void CConfigurationFile::setProxyUser (const std::string & proxyUser)
Set the proxy user name.
Parameters
proxyUser the proxy username
References mpProxyUser.
setRecentMIRIAMResources()
void CConfigurationFile::setRecentMIRIAMResources (const CMIRIAMResources & miriamResources)
References mpRecentMIRIAMResources.
setResizeToContents()
void CConfigurationFile::setResizeToContents (bool flag)
Set whether the GUI should resize tables to contents
References mpResizeToContents.
setUseAdvancedEditing()
void CConfigurationFile::setUseAdvancedEditing (bool useAdvancedEditing)
Set whether the advanced expression editing (i.e manually entering copasiobjects) is to be used (true), or not
References mpUseAdvancedEditing, and useAdvancedEditing().
setUseAdvancedSliders()
void CConfigurationFile::setUseAdvancedSliders (bool useAdvancedSliders)
Set whether the sliders should react to keyboard input / mouse interaction.
References mpUseAdvancedSliders, and useAdvancedSliders().
setUseOpenGL()
void CConfigurationFile::setUseOpenGL (bool useOpenGL)
Set whether the openGL based rendering is to be used (true), or the Qt based one.
References mpUseOpenGL, and useOpenGL().
setValidateUnits()
void CConfigurationFile::setValidateUnits (bool validateUnits)
Set whether unit validation should always be performed or not.
Parameters
bool validateUnits
References mpValidateUnits, and validateUnits().
setWorkingDirectory()
void CConfigurationFile::setWorkingDirectory (const std::string & workingDirectory)
Set the working directory.
Parameters
const std::string & workingDirectory
References mpWorkingDirectory.
showItemIssues()
bool CConfigurationFile::showItemIssues (CIssue::eKind kind) const
Show item issues
Returns
a flag indicating whether an icon and tooltip should be displayed for items.
References CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), and mpDisplayIssueKinds.
useAdvancedEditing()
bool CConfigurationFile::useAdvancedEditing () const
Returns
a flag on whether to use the advanced expression editing (i.e manually entering copasiobjects)
References mpUseAdvancedEditing.
Referenced by setUseAdvancedEditing().
useAdvancedSliders()
bool CConfigurationFile::useAdvancedSliders () const
Returns
a flag on whether the sliders should react to keyboard input / mouse interaction.
References mpUseAdvancedSliders.
Referenced by setUseAdvancedSliders().
useOpenGL()
bool CConfigurationFile::useOpenGL () const
Returns
a flag on whether to use the open GL based rendering, or the Qt based one
References mpUseOpenGL.
Referenced by setUseOpenGL().
validateUnits()
bool CConfigurationFile::validateUnits () const
Always perform unit validation
Returns
a flag indicating whether unit validation should always be performed
References mpValidateUnits.
Referenced by setValidateUnits().
Member Data Documentation
mpApplicationFont
std::string* CConfigurationFile::mpApplicationFont private
A pointer to the application font
Referenced by getApplicationFont(), initializeParameter(), and setApplicationFont().
mpCheckForUpdates
CCheckForUpdates* CConfigurationFile::mpCheckForUpdates private
A pointer to the update check configuration
Referenced by elevateChildren(), and getCheckForUpdates().
mpCurrentAuthorEmail
std::string* CConfigurationFile::mpCurrentAuthorEmail private
A pointer to the Email of the current author.
Referenced by getCurrentAuthorEmail(), initializeParameter(), and setCurrentAuthorEmail().
mpCurrentAuthorFamilyName
std::string* CConfigurationFile::mpCurrentAuthorFamilyName private
A pointer to the Familyname of the current author.
Referenced by getCurrentAuthorFamilyName(), initializeParameter(), and setCurrentAuthorFamilyName().
mpCurrentAuthorGivenName
std::string* CConfigurationFile::mpCurrentAuthorGivenName private
A pointer to the Given name of the current author.
Referenced by getCurrentAuthorGivenName(), initializeParameter(), and setCurrentAuthorGivenName().
mpCurrentAuthorOrganization
std::string* CConfigurationFile::mpCurrentAuthorOrganization private
A pointer to the Organization of the current author.
Referenced by getCurrentAuthorOrganization(), initializeParameter(), and setCurrentAuthorOrganization().
mpDisableJIT
bool* CConfigurationFile::mpDisableJIT private
A pointer indicating whether to disable JIT compilation even if it is available
Referenced by getDisableJIT(), initializeParameter(), and setDisableJIT().
mpDisplayIssueKinds
CCopasiParameterGroup* CConfigurationFile::mpDisplayIssueKinds private
A pointer to a group indicating which kinds of issues should be displayed.
Referenced by initializeParameter(), and showItemIssues().
mpDisplayIssueSeverity
CCopasiParameterGroup* CConfigurationFile::mpDisplayIssueSeverity private
A pointer indicating the severity level of issues to be displayed.
Referenced by initializeParameter().
mpDisplayPopulations
bool* CConfigurationFile::mpDisplayPopulations private
A pointer indicating whether to display the population visualization window
Referenced by displayPopulations(), initializeParameter(), and setDisplayPopulations().
mpEnableAdditionalOptimizationParameters
bool* CConfigurationFile::mpEnableAdditionalOptimizationParameters private
A pointer to a flag indicating whether to enable additional parameters in optimization methods
Referenced by enableAdditionalOptimizationParameters(), initializeParameter(), and setEnableAdditionalOptimizationParameters().
mpNormalizePerExperiment
bool* CConfigurationFile::mpNormalizePerExperiment private
A pointer indicating whether to experiments should be normalized by default
Referenced by initializeParameter(), normalizePerExperiment(), and setNormalizePerExperiment().
mpPrecision
C_INT32* CConfigurationFile::mpPrecision private
a pointer to the double precision requested when converting numbers to string
Referenced by getDoublePrecision(), initializeParameter(), and setDoublePrecision().
mpProxyPass
std::string* CConfigurationFile::mpProxyPass private
A pointer to the proxy password.
Referenced by getProxyPassword(), initializeParameter(), and setProxyPassword().
mpProxyPort
C_INT32* CConfigurationFile::mpProxyPort private
A pointer to the proxy port.
Referenced by getProxyPort(), initializeParameter(), and setProxyPort().
mpProxyServer
std::string* CConfigurationFile::mpProxyServer private
A pointer to the proxy server.
Referenced by getProxyServer(), initializeParameter(), and setProxyServer().
mpProxyUser
std::string* CConfigurationFile::mpProxyUser private
A pointer to the proxy user name.
Referenced by getProxyUser(), initializeParameter(), and setProxyUser().
mpRecentFiles
CRecentFiles* CConfigurationFile::mpRecentFiles private
A pointer to the list of recent files
Referenced by elevateChildren(), and getRecentFiles().
mpRecentMIRIAMResources
CMIRIAMResources* CConfigurationFile::mpRecentMIRIAMResources private
A pointer to the list of MIRIAM Resources
Referenced by elevateChildren(), getRecentMIRIAMResources(), load(), and setRecentMIRIAMResources().
mpRecentSBMLFiles
CRecentFiles* CConfigurationFile::mpRecentSBMLFiles private
A pointer to the list of recent files
Referenced by elevateChildren(), and getRecentSBMLFiles().
mpRecentSEDMLFiles
CRecentFiles* CConfigurationFile::mpRecentSEDMLFiles private
A pointer to the list of recent files
Referenced by elevateChildren(), and getRecentSEDMLFiles().
mpResizeToContents
bool* CConfigurationFile::mpResizeToContents private
A pointer indicating whether the GUI should resize tables to contents
Referenced by initializeParameter(), resizeToContents(), and setResizeToContents().
mpUseAdvancedEditing
bool* CConfigurationFile::mpUseAdvancedEditing private
A pointer indicating whether to use the advanced editing
Referenced by initializeParameter(), setUseAdvancedEditing(), and useAdvancedEditing().
mpUseAdvancedSliders
bool* CConfigurationFile::mpUseAdvancedSliders private
A pointer indicating whether the sliders should react to keyboard input / mouse interaction.
Referenced by initializeParameter(), setUseAdvancedSliders(), and useAdvancedSliders().
mpUseOpenGL
bool* CConfigurationFile::mpUseOpenGL private
A pointer indicating whether to use the OpenGL rendering, or the Qt based one
Referenced by initializeParameter(), setUseOpenGL(), and useOpenGL().
mpValidateUnits
bool* CConfigurationFile::mpValidateUnits private
A pointer indicating whether units will always be validated
Referenced by initializeParameter(), setValidateUnits(), and validateUnits().
mpWorkingDirectory
std::string* CConfigurationFile::mpWorkingDirectory private
A pointer to the last used working directory of the GUI.
Referenced by getWorkingDirectory(), initializeParameter(), and setWorkingDirectory().
The documentation for this class was generated from the following files:
CConfigurationFile.h
CConfigurationFile.cpp