COPASI API: CMathEvent::CAssignment Class Reference
CMathEvent::CAssignment Class Reference
#include <CMathEvent.h>
Public Member Functions
CAssignment ()
CAssignment (const CAssignment &src)
bool compile (const CEventAssignment *pDataAssignment, CMathContainer &container)
void copy (const CAssignment &src, CMathContainer &container)
const CMathObject * getAssignment () const
const CMathObject * getTarget () const
void initialize (CMath::sPointers &pointers)
const bool & isStateValue () const
void relocate (const CMathContainer *pContainer, const std::vector< CMath::sRelocate > &relocations)
void setAssignment (CMathObject *pAssignment)
void setIsStateValue (bool isStateValue)
void setTarget (CMathObject *pTarget)
~CAssignment ()
Private Attributes
bool mIsStateValue
CMathObject * mpAssignment
CMathObject * mpTarget
Friends
std::ostream & operator<< (std::ostream &os, const CAssignment &o)
Constructor & Destructor Documentation
CAssignment() [1/2]
CMathEvent::CAssignment::CAssignment ()
Default constructor
CAssignment() [2/2]
CMathEvent::CAssignment::CAssignment (const CAssignment & src)
Copy constructor
~CAssignment()
CMathEvent::CAssignment::~CAssignment ()
Destructor
Member Function Documentation
compile()
bool CMathEvent::CAssignment::compile (const CEventAssignment * pDataAssignment, CMathContainer & container)
References CExpression::compile(), CMath::EventTarget, CMath::Fixed, CDataObject::getCN(), CMetab::getCompartment(), CEventAssignment::getExpression(), CEventAssignment::getExpressionPtr(), CMathContainer::getMathObject(), CMathContainer::getQuantity2NumberFactor(), CEventAssignment::getTargetObject(), CModelEntity::getValueReference(), pointerToString(), CExpression::setInfix(), CMathObject::setSimulationType(), and CMath::Species.
Referenced by CMathEvent::compile().
copy()
void CMathEvent::CAssignment::copy (const CAssignment & src, CMathContainer & container)
Copy an existing object
Parameters
const CAssignment & src
CMathContainer & container
Referenced by CMathEvent::copy().
getAssignment()
const CMathObject * CMathEvent::CAssignment::getAssignment () const
Referenced by CMathEvent::compile(), and CMathEvent::createUpdateSequences().
getTarget()
const CMathObject * CMathEvent::CAssignment::getTarget () const
Referenced by CMathContainer::addAnalysisEvent(), CMathEvent::compile(), CMathEvent::createUpdateSequences(), and CMathContainer::removeAnalysisEvent().
initialize()
void CMathEvent::CAssignment::initialize (CMath::sPointers & pointers)
References CMath::Event, CMath::EventAssignment, CMathObject::initialize(), CMath::sPointers::pEventAssignments, CMath::sPointers::pEventAssignmentsObject, and CMath::Undefined.
Referenced by CMathEvent::initialize().
isStateValue()
const bool & CMathEvent::CAssignment::isStateValue () const
Referenced by CMathEvent::setTargetValues().
relocate()
void CMathEvent::CAssignment::relocate (const CMathContainer * pContainer, const std::vector< CMath::sRelocate > & relocations)
The objects and values are relocated
Parameters
const CMathContainer * pContainer
const std::vector< CMath::sRelocate > & relocations
References CMathContainer::relocateObject().
Referenced by CMathEvent::relocate().
setAssignment()
void CMathEvent::CAssignment::setAssignment (CMathObject * pAssignment)
Referenced by CMathEvent::addAssignment().
setIsStateValue()
void CMathEvent::CAssignment::setIsStateValue (bool isStateValue)
Referenced by CMathEvent::createUpdateSequences().
setTarget()
void CMathEvent::CAssignment::setTarget (CMathObject * pTarget)
Referenced by CMathEvent::addAssignment().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CAssignment & o) friend
Member Data Documentation
mIsStateValue
bool CMathEvent::CAssignment::mIsStateValue private
mpAssignment
CMathObject* CMathEvent::CAssignment::mpAssignment private
mpTarget
CMathObject* CMathEvent::CAssignment::mpTarget private
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp