COPASI API: CCopasiParameterGroup Class Reference
CCopasiParameterGroup Class Reference
#include <CCopasiParameterGroup.h>
Public Types
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual bool elevateChildren ()
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Protected Member Functions
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Private Attributes
CCopasiParameterGroup * mpElementTemplates {NULL }
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiParameterGroup &o)
bool operator== (const CCopasiParameterGroup &lhs, const CCopasiParameterGroup &rhs)
Additional Inherited Members
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Detailed Description
CCopasiParameterGroup class. This class is used to describe parameters. This class is intended to be used with integration or optimization methods or reactions.
Created for COPASI by Stefan Hoops 2002
Member Typedef Documentation
const_name_iterator
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > CCopasiParameterGroup::const_name_iterator
elements
typedef std::vector< CCopasiParameter * > CCopasiParameterGroup::elements
index_iterator
typedef elements::iterator CCopasiParameterGroup::index_iterator
name_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > CCopasiParameterGroup::name_iterator
Constructor & Destructor Documentation
CCopasiParameterGroup() [1/3]
CCopasiParameterGroup::CCopasiParameterGroup () protected
Default constructor
CCopasiParameterGroup class. This class is used to describe parameters. This class is intended to be used with integration or optimization methods or reactions.
Created for COPASI by Stefan Hoops 2002
Referenced by addGroup(), addParameter(), CScanProblem::createScanItem(), getElementTemplates(), operator=(), and CMIRIAMResources::updateMIRIAMResourcesFromFile().
CCopasiParameterGroup() [2/3]
CCopasiParameterGroup::CCopasiParameterGroup (const CCopasiParameterGroup & src, const CDataContainer * pParent = NULL)
Copy constructor
Parameters
const CCopasiParameterGroup & src
const CDataContainer * pParent (default: NULL)
References operator=().
CCopasiParameterGroup() [3/3]
CCopasiParameterGroup::CCopasiParameterGroup (const std::string & name, const CDataContainer * pParent = NO_PARENT, const std::string & objectType = "ParameterGroup")
Specific constructor
Parameters
const string & name
const CDataContainer * pParent (default: NULL)
const std::string & objectType (default: "ParameterGroup")
~CCopasiParameterGroup()
CCopasiParameterGroup::~CCopasiParameterGroup () virtual
Destructor
References mpElementTemplates, and pdelete.
Member Function Documentation
addGroup()
bool CCopasiParameterGroup::addGroup (const std::string & name)
Add a subgroup to the group
Parameters
const std::string & name
Returns
bool success
References addParameter(), and CCopasiParameterGroup().
Referenced by CSensProblem::addVariables(), assertGroup(), and CScanProblem::initializeParameter().
addParameter() [1/4]
void CCopasiParameterGroup::addParameter (CCopasiParameter * pParameter)
Add a parameter
Parameters
CCopasiParameter * pParameter
References CDataContainer::add(), CCopasiParameter::getUserInterfaceFlag(), CCopasiParameter::mpValue, CCopasiParameter::mUserInterfaceFlag, and CCopasiParameter::setUserInterfaceFlag().
addParameter() [2/4]
bool CCopasiParameterGroup::addParameter (const CCopasiParameter & parameter)
Add a parameter
Parameters
const CCopasiParameter & parameter
Returns
bool success
References CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), CCopasiParameter::getType(), CCopasiParameter::GROUP, and NO_PARENT.
Referenced by CFitItem::addCrossValidation(), CMIRIAMResource::addDeprecatedURL(), CExperimentSet::addExperiment(), CFitItem::addExperiment(), CRecentFiles::addFile(), CFitProblem::addFitConstraint(), CFitProblem::addFitItem(), addGroup(), CMIRIAMResources::addMIRIAMResource(), COptProblem::addOptConstraint(), COptProblem::addOptItem(), addParameter(), CTimeSensProblem::addParameterCN(), CScanProblem::addScanItem(), CTimeSensProblem::addTargetCN(), assertParameter(), SBMLImporter::createCReactionFromReaction(), CScanProblem::createScanItem(), CReactionInterface::createUndoData(), CHybridMethodODE45::initializeParameter(), CHybridNextReactionLSODAMethod::initializeParameter(), CReaction::initializeParameters(), PlotItemHandler::processEnd(), PlotSpecificationHandler::processEnd(), ConstantHandler::processStart(), and CMIRIAMResources::updateMIRIAMResourcesFromFile().
addParameter() [3/4]
bool CCopasiParameterGroup::addParameter (const std::string & name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag & flag = CCopasiParameter::UserInterfaceFlag::All)
Add a parameter to the group
Parameters
const std::string & name
const CCopasiParameter::Type type
const CCopasiParameter::UserInterfaceFlag & flag (default: CCopasiParameter::UserInterfaceFlag::All))
Returns
bool success
References addParameter(), CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), CCopasiParameter::GROUP, and CCopasiParameter::setUserInterfaceFlag().
addParameter() [4/4]
template<class CType > bool CCopasiParameterGroup::addParameter (const std::string & name, const CCopasiParameter::Type type, const CType & value, const CCopasiParameter::UserInterfaceFlag & flag = CCopasiParameter::UserInterfaceFlag::All) inline
Add a parameter to the group
Parameters
const std::string & name
const CCopasiParameter::Type type
const CType & value
const CCopasiParameter::UserInterfaceFlag & flag (default: CCopasiParameter::UserInterfaceFlag::All)
Returns
bool success
References addParameter(), CCopasiParameter::basic, CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), CCopasiParameter::GROUP, CCopasiParameter::isValidValue(), CCopasiParameter::mpValue, NO_PARENT, CCopasiParameter::setDefault(), CCopasiParameter::setUserInterfaceFlag(), and CCopasiParameter::setValue().
applyData()
bool CCopasiParameterGroup::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CCopasiParameter.
Reimplemented in CPlotSpecification, and CPlotItem.
References CDataObject::applyData(), CCopasiParameter::applyData(), CObjectInterface::DataObject(), getObject(), getParameter(), CData::getProperty(), insert(), CData::isSetProperty(), CData::OBJECT_INDEX, CData::OBJECT_NAME, CData::OBJECT_TYPE, CData::PARAMETER_VALUE, size(), and CDataValue::toDataVector().
Referenced by CCopasiTask::applyData().
assertGroup()
CCopasiParameterGroup * CCopasiParameterGroup::assertGroup (const std::string & name, const CCopasiParameter::UserInterfaceFlag & flag = CCopasiParameter::UserInterfaceFlag::All)
Assert that a group with the given name is present. If not the group is created as empty group.
Parameters
const std::string & name
const CCopasiParameter::UserInterfaceFlag & flag (default: CCopasiParameter::UserInterfaceFlag::All)
Returns
CCopasiParameterGroup * pGroup
References addGroup(), getGroup(), CCopasiParameter::getUserInterfaceFlag(), removeParameter(), setUserInterfaceFlag(), and CCopasiParameter::unsupported.
Referenced by CConfigurationFile::CXML::CXML(), CExperimentObjectMap::elevateChildren(), CRecentFiles::initializeParameter(), CConfigurationFile::initializeParameter(), CMIRIAMResource::initializeParameter(), CMIRIAMResources::initializeParameter(), COptProblem::initializeParameter(), CExperiment::initializeParameter(), CFitItem::initializeParameter(), CFitProblem::initializeParameter(), CSensProblem::initializeParameter(), CTimeSensProblem::initializeParameter(), CHybridMethodODE45::initializeParameter(), and CExperimentObjectMap::setNumCols().
assertParameter()
template<class CType > CType* CCopasiParameterGroup::assertParameter (const std::string & name, const CCopasiParameter::Type type, const CType & defaultValue, const CCopasiParameter::UserInterfaceFlag & flag = CCopasiParameter::UserInterfaceFlag::All) inline
Assert that a parameter with the given name and type is present. If not the parameter is created with the default value.
Parameters
const std::string & name
const CCopasiParameter::Type type
const CType & Value
const CCopasiParameter::UserInterfaceFlag & flag (default: CCopasiParameter::UserInterfaceFlag::All)
Returns
CCopasiParameter * pParameter
References addParameter(), getParameter(), CCopasiParameter::getType(), CCopasiParameter::getUserInterfaceFlag(), CCopasiParameter::getValue(), removeParameter(), CCopasiParameter::setUserInterfaceFlag(), and CCopasiParameter::unsupported.
Referenced by SEDMLImporter::applyStyleToCopasiItem(), CLNAProblem::CLNAProblem(), CMCAProblem::CMCAProblem(), COptMethod::COptMethod(), COptMethodCoranaWalk::COptMethodCoranaWalk(), COptMethodDE::COptMethodDE(), COptMethodEP::COptMethodEP(), COptMethodGA::COptMethodGA(), COptMethodGASR::COptMethodGASR(), COptMethodHookeJeeves::COptMethodHookeJeeves(), COptMethodLevenbergMarquardt::COptMethodLevenbergMarquardt(), COptMethodNelderMead::COptMethodNelderMead(), COptMethodNL2SOL::COptMethodNL2SOL(), COptMethodPraxis::COptMethodPraxis(), COptMethodPS::COptMethodPS(), COptMethodSA::COptMethodSA(), COptMethodSRES::COptMethodSRES(), COptMethodSS::COptMethodSS(), COptMethodSteepestDescent::COptMethodSteepestDescent(), CRandomSearch::CRandomSearch(), COutputAssistant::createDefaultOutput(), CSensProblem::createParametersInGroup(), COutputAssistant::createPlot(), CSensMethod::CSensMethod(), CSteadyStateProblem::CSteadyStateProblem(), CExperimentObjectMap::elevateChildren(), CFitProblem::elevateChildren(), CScanItem::ensureParameterGroupHasAllElements(), CScanItemLinear::ensureParameterGroupHasAllElements(), CScanItemRandom::ensureParameterGroupHasAllElements(), CAnalyticsProblem::initializeParameter(), CCheckForUpdates::initializeParameter(), CRecentFiles::initializeParameter(), CConfigurationFile::initializeParameter(), CCrossSectionProblem::initializeParameter(), CLyapProblem::initializeParameter(), CLyapWolfMethod::initializeParameter(), CMIRIAMResource::initializeParameter(), CMIRIAMResources::initializeParameter(), COptItem::initializeParameter(), COptProblem::initializeParameter(), CExperiment::initializeParameter(), CExperimentObjectMap::CDataColumn::initializeParameter(), CCrossValidationSet::initializeParameter(), CFitProblem::initializeParameter(), CScanProblem::initializeParameter(), CSensProblem::initializeParameter(), CMCAMethod::initializeParameter(), CNewtonMethod::initializeParameter(), CSteadyStateMethod::initializeParameter(), CTimeSensLsodaMethod::initializeParameter(), CHybridMethod::initializeParameter(), CHybridMethodODE45::initializeParameter(), CHybridNextReactionRKMethod::initializeParameter(), CLsodaMethod::initializeParameter(), CLsodaMethod2::initializeParameter(), CRadau5Method::initializeParameter(), CStochasticRungeKuttaRI5::initializeParameter(), CStochDirectMethod::initializeParameter(), CStochMethod::initializeParameter(), CTauLeapMethod::initializeParameter(), CTrajAdaptiveSA::initializeParameter(), CTrajectoryMethodDsaLsodar::initializeParameter(), CTrajectoryProblem::initializeParameter(), CCSPMethod::initializeParameter(), CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), CTSSAProblem::initializeParameter(), CExperimentObjectMap::CDataColumn::setObjectCN(), CExperimentObjectMap::CDataColumn::setScale(), and CPlotItem::setType().
beginIndex()
CCopasiParameterGroup::index_iterator CCopasiParameterGroup::beginIndex () const
Retrieve the begin of unsorted iterator Note: the swap function may be used to change the order
Returns
index_iterator begin
References CCopasiParameter::mpValue.
Referenced by CRecentFiles::addFile(), CMIRIAMResources::createDisplayNameMap(), CMIRIAMResources::createURIMap(), elevate(), CMIRIAMResources::elevateChildren(), CExperimentObjectMap::elevateChildren(), CExperimentSet::elevateChildren(), CMIRIAMResource::extractId(), CExperimentObjectMap::fixBuild55(), CScanProblem::fixBuild81(), CExperimentObjectMap::getLastNotIgnoredColumn(), getObject(), CConfigurationFile::initializeParameter(), CHybridNextReactionLSODAMethod::initializeParameter(), CReaction::initializeParameters(), CHybridMethodODE45::partitionSystem(), setUserInterfaceFlag(), size(), CExperimentSet::sort(), CHybridNextReactionLSODAMethod::start(), and swap().
beginName()
CCopasiParameterGroup::const_name_iterator CCopasiParameterGroup::beginName () const
Retrieve the start iterator going through the parameters sorted by name
Returns
const_name_iterator begin
References CDataObjectMap::begin(), and CDataContainer::mObjects.
Referenced by CReaction::createUndoData(), and CReaction::toData().
clear()
void CCopasiParameterGroup::clear ()
Clear all parameters and subgroups
References CCopasiParameter::mpValue, and pdelete.
Referenced by CTimeSensProblem::clearParameterCNs(), CScanProblem::clearScanItems(), CTimeSensProblem::clearTargetCNs(), CExperiment::elevateChildren(), CExperimentObjectMap::elevateChildren(), CSSAMethod::initialize(), COptProblem::initialize(), CConfigurationFile::CXML::load(), CExperiment::operator=(), CSensProblem::removeVariables(), CExperimentObjectMap::setNumCols(), and CPlotItem::setType().
createUndoData()
void CCopasiParameterGroup::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CCopasiParameter.
References CUndoData::addPostProcessData(), CUndoData::addPreProcessData(), CUndoData::addProperty(), CData::begin(), C_INT32, CUndoData::CHANGE, CCopasiParameter::createUndoData(), CUndoData::empty(), CData::end(), getIndex(), CUndoData::getNewData(), CUndoData::getOldData(), CData::getProperty(), CUndoObjectInterface::insert(), CDataContainer::insert(), CUndoData::INSERT, CCopasiParameter::mpValue, CData::OBJECT_INDEX, CData::OBJECT_NAME, CData::PARAMETER_VALUE, CUndoData::REMOVE, and CDataValue::toDataVector().
Referenced by CCopasiTask::createUndoData().
elevateChildren()
bool CCopasiParameterGroup::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented in CFitProblem, CFitItem, COptProblem, CEFMProblem, CTSSAProblem, CTSSAMethod, CTrajectoryProblem, CTrajectoryMethodDsaLsodar, CTrajAdaptiveSA, CTauLeapMethod, CStochMethod, CStochDirectMethod, CStochasticRungeKuttaRI5, CRadau5Method, CLsodaMethod2, CLsodaMethod, CHybridMethodODE45, CHybridMethod, CTimeSensProblem, CTimeSensLsodaMethod, CSteadyStateMethod, CNewtonMethod, CMCAMethod, CExperimentSet, CExperimentObjectMap, CExperimentObjectMap::CDataColumn, CExperiment, COscillationProblem, COptMethodSS, CMIRIAMResources, CLyapWolfMethod, CLyapProblem, CLNAMethod, and CConfigurationFile.
Referenced by TaskHandler::processEnd().
endIndex()
CCopasiParameterGroup::index_iterator CCopasiParameterGroup::endIndex () const
Retrieve the end of unsorted iterator Note: the swap function may be used to change the order
Returns
index_iterator end
References CCopasiParameter::mpValue.
Referenced by CRecentFiles::addFile(), CMIRIAMResources::createDisplayNameMap(), CMIRIAMResources::createURIMap(), elevate(), CMIRIAMResources::elevateChildren(), CExperimentObjectMap::elevateChildren(), CExperimentSet::elevateChildren(), CMIRIAMResource::extractId(), CExperimentObjectMap::fixBuild55(), CScanProblem::fixBuild81(), CExperimentObjectMap::getLastNotIgnoredColumn(), getObject(), CConfigurationFile::initializeParameter(), CHybridNextReactionLSODAMethod::initializeParameter(), CReaction::initializeParameters(), CHybridMethodODE45::partitionSystem(), setUserInterfaceFlag(), size(), CExperimentSet::sort(), CHybridNextReactionLSODAMethod::start(), and swap().
endName()
CCopasiParameterGroup::const_name_iterator CCopasiParameterGroup::endName () const
Retrieve the end iterator going through the parameters sorted by name
Returns
const_name_iterator end
References CDataObjectMap::end(), and CDataContainer::mObjects.
Referenced by CReaction::createUndoData(), and CReaction::toData().
getElementTemplates() [1/2]
CCopasiParameterGroup & CCopasiParameterGroup::getElementTemplates ()
References CCopasiParameterGroup(), mpElementTemplates, and NO_PARENT.
Referenced by CHybridMethodODE45::initializeParameter().
getElementTemplates() [2/2]
const CCopasiParameterGroup & CCopasiParameterGroup::getElementTemplates () const
References mpElementTemplates.
getGroup() [1/4]
CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const size_t & index)
Retrieve a subgroup from the group
Parameters
const size_t & index
Returns
CCopasiParameterGroup * parameter
References getParameter().
getGroup() [2/4]
const CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const size_t & index) const
Retrieve a subgroup from the group
Parameters
const size_t & index
Returns
const CCopasiParameterGroup * parameter
References getParameter().
getGroup() [3/4]
CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const std::string & name)
Retrieve a subgroup from the group
Parameters
const std::string & name
Returns
CCopasiParameterGroup * group
References getParameter().
Referenced by assertGroup(), CConfigurationFile::elevateChildren(), CExperiment::elevateChildren(), CFitProblem::elevateChildren(), CExperimentObjectMap::getDefaultScale(), CExperimentSet::getExperiment(), CMIRIAMResources::getMIRIAMResource(), CExperimentObjectMap::getName(), CExperimentObjectMap::getObjectCN(), CExperimentObjectMap::getRole(), CExperimentObjectMap::getScale(), CConfigurationFile::load(), CExperimentObjectMap::setObjectCN(), CExperimentObjectMap::setRole(), and CExperimentObjectMap::setScale().
getGroup() [4/4]
const CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const std::string & name) const
Retrieve a subgroup from the group
Parameters
const std::string & name
Returns
const CCopasiParameterGroup * group
References getParameter().
getIndex() [1/2]
size_t CCopasiParameterGroup::getIndex (const CDataObject * pObject) const virtual
Reimplemented from CDataContainer.
References CDataContainer::getIndex(), and CCopasiParameter::mpValue.
Referenced by createUndoData(), operator=(), CFitProblem::restore(), and updateIndex().
getIndex() [2/2]
size_t CCopasiParameterGroup::getIndex (const std::string & name) const
Retrieve the index of a parameter or subgroup with a given name
Parameters
const std::string & name
Returns
size_t index
References C_INVALID_INDEX, and CCopasiParameter::mpValue.
getKey() [1/2]
std::string CCopasiParameterGroup::getKey (const size_t & index) const
Retrieve the key of a parameter or subgroup
Parameters
const size_t & index
Returns
std::string key
References CCopasiParameter::getKey(), and getParameter().
getKey() [2/2]
std::string CCopasiParameterGroup::getKey (const std::string & name) const
Retrieve the key of a parameter or subgroup
Parameters
const std::string & name
Returns
std::string key
References CCopasiParameter::getKey(), and getParameter().
Referenced by CCopasiXML::saveModel().
getName()
const std::string & CCopasiParameterGroup::getName (const size_t & index) const virtual
Retrieve the name of a parameter or subgroup
Parameters
const size_t & index
Returns
std::string name
Reimplemented in CExperimentObjectMap.
References CDataObject::getObjectName(), and getParameter().
Referenced by CExperiment::readColumnNames(), and CCopasiXML::saveModel().
getObject()
const CObjectInterface * CCopasiParameterGroup::getObject (const CCommonName & cn) const virtual
Retrieve a descendant object by its CN.
Parameters
const CCommonName & cn
Returns
const CObjectInterface * pObject
Reimplemented from CDataContainer.
References beginIndex(), C_INVALID_INDEX, endIndex(), CDataContainer::getObject(), CCommonName::getObjectName(), CCommonName::getRemainder(), and strToUnsignedInt().
Referenced by applyData(), and COutputAssistant::createDefaultOutput().
getParameter() [1/4]
CCopasiParameter * CCopasiParameterGroup::getParameter (const size_t & index)
Retrieve a parameter or subgroup from the group
Parameters
const size_t & index
Returns
CCopasiParameter * parameter
References CCopasiParameter::mpValue, and size().
getParameter() [2/4]
const CCopasiParameter * CCopasiParameterGroup::getParameter (const size_t & index) const
Retrieve a parameter or subgroup from the group
Parameters
const size_t & index
Returns
const CCopasiParameter * parameter
References CCopasiParameter::mpValue, and size().
getParameter() [3/4]
CCopasiParameter * CCopasiParameterGroup::getParameter (std::string name)
Retrieve a parameter or subgroup from the group
Parameters
const std::string & name
Returns
CCopasiParameter * parameter
References CDataObjectMap::equal_range(), CDataContainer::getObjects(), and CDataObject::sanitizeObjectName().
Referenced by CExperimentSet::addExperiment(), CSensProblem::addVariables(), SEDMLImporter::applyAlgorithm(), CReaction::applyData(), applyData(), assertParameter(), CSensProblem::changeVariables(), CModelAnalyzer::checkReaction(), CModel::convert2NonReversible(), CReactionInterface::createUndoData(), CScanItemLinear::CScanItemLinear(), CTSSATask::CTSSATask(), CModelExpansion::duplicateReaction(), COptProblem::elevateChildren(), CFitItem::elevateChildren(), CFitProblem::elevateChildren(), CSEDMLExporter::exportAlgorithm(), CSEDMLExporter::exportNthScanItem(), CODEExporter::exportReacParamsAndFuncs(), CScanProblem::fixBuild81(), CPlotItem::getActivity(), CReactionInterface::getDeletedParameters(), getGroup(), getKey(), getName(), CUndoData::getObject(), CTimeSensProblem::getParameterCN(), CReaction::getParameterValue(), CScanProblem::getScanItem(), CTimeSensProblem::getTargetCN(), getType(), getValue(), CSensProblem::getVariables(), COptMethodDE::initialize(), COptMethodEP::initialize(), COptMethodGA::initialize(), COptMethodGASR::initialize(), COptMethodLevenbergMarquardt::initialize(), COptMethodPS::initialize(), COptMethodSA::initialize(), COptMethodSRES::initialize(), COptMethodSS::initialize(), COptPopulationMethod::initialize(), CRandomSearch::initialize(), CTSSATask::initialize(), CCheckForUpdates::initializeParameter(), CConfigurationFile::initializeParameter(), CLyapWolfMethod::initializeParameter(), CExperiment::initializeParameter(), CExperimentObjectMap::CDataColumn::initializeParameter(), CScanProblem::initializeParameter(), CMCAMethod::initializeParameter(), CNewtonMethod::initializeParameter(), CSteadyStateMethod::initializeParameter(), CHybridMethod::initializeParameter(), CHybridMethodODE45::initializeParameter(), CHybridNextReactionLSODAMethod::initializeParameter(), CHybridNextReactionRKMethod::initializeParameter(), CLsodaMethod::initializeParameter(), CStochMethod::initializeParameter(), CTauLeapMethod::initializeParameter(), CReaction::initializeParameters(), CReactionInterface::loadMappingAndValues(), PlotItemHandler::processEnd(), PlotSpecificationHandler::processEnd(), TaskHandler::processEnd(), ConstantHandler::processStart(), PlotItemHandler::processStart(), PlotSpecificationHandler::processStart(), removeParameter(), CTimeSensProblem::removeParameterCN(), CTimeSensProblem::removeTargetCN(), SBMLImporter::sbmlId2CopasiCN(), CReaction::setParameterValue(), setValue(), CConfigurationFile::showItemIssues(), CHybridNextReactionLSODAMethod::start(), CProvenanceXMLWriter::updateCurrentSessionProvenance(), CProvenanceXMLWriter::updateOrigionOfProvenance(), and CReactionInterface::writeBackToReaction().
getParameter() [4/4]
const CCopasiParameter * CCopasiParameterGroup::getParameter (std::string name) const
Retrieve a parameter or subgroup from the group
Parameters
const std::string & name
Returns
const CCopasiParameter * parameter
References CDataObjectMap::equal_range(), CDataContainer::getObjects(), and CDataObject::sanitizeObjectName().
getType() [1/2]
CCopasiParameter::Type CCopasiParameterGroup::getType (const size_t & index) const
Retrieve the type of a parameter or subgroup
Parameters
const size_t & index
Returns
CCopasiParameter::Type
References getParameter(), CCopasiParameter::getType(), and CCopasiParameter::INVALID.
getType() [2/2]
CCopasiParameter::Type CCopasiParameterGroup::getType (const std::string & name) const
Retrieve the type of a parameter or subgroup
Parameters
const std::string & name
Returns
CCopasiParameter::Type
References getParameter(), CCopasiParameter::getType(), and CCopasiParameter::INVALID.
getUniqueParameterName()
std::string CCopasiParameterGroup::getUniqueParameterName (const CCopasiParameter * pParameter) const
Retrieve a unique name for the given parameter
Parameters
const CCopasiParameter * pParameter
Returns
std::string uniqueParameterName
References C_INVALID_INDEX, CDataObject::getObjectName(), and CCopasiParameter::mpValue.
Referenced by CCopasiParameter::getCN(), and CCopasiParameter::getObjectDisplayName().
getValue() [1/4]
template<class CType > CType& CCopasiParameterGroup::getValue (const size_t & index) inline
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const size_t & index
Returns
CType & Value
References __FatalError, getParameter(), and CCopasiParameter::getValue().
getValue() [2/4]
template<class CType > const CType& CCopasiParameterGroup::getValue (const size_t & index) const inline
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const size_t & index
Returns
const CType & Value
References __FatalError, getParameter(), and CCopasiParameter::getValue().
getValue() [3/4]
template<class CType > CType& CCopasiParameterGroup::getValue (const std::string & name) inline
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const std::string & name
Returns
CType & Value
References __FatalError, getParameter(), and CCopasiParameter::getValue().
getValue() [4/4]
template<class CType > const CType& CCopasiParameterGroup::getValue (const std::string & name) const inline
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const std::string & name
Returns
const CType & Value
References __FatalError, getParameter(), and CCopasiParameter::getValue().
Referenced by CFitItem::addCrossValidation(), CFitItem::addExperiment(), CSensProblem::copyParameterGroupToSensItem(), CScanItem::createScanItemFromParameterGroup(), CScanItem::CScanItem(), CScanItemLinear::CScanItemLinear(), CScanItemRandom::CScanItemRandom(), CExperiment::elevateChildren(), CFitProblem::elevateChildren(), CSEDMLExporter::exportStyleForItem(), CFitItem::getCrossValidation(), CFitItem::getCrossValidations(), CFitItem::getExperiment(), CFitItem::getExperiments(), CScanTask::initSubtask(), CSEDMLExporter::PlotItemStyleComparer::operator()(), and CCopasiXML::saveModel().
haveTemplate()
bool CCopasiParameterGroup::haveTemplate () const
References mpElementTemplates, and size().
insert()
CUndoObjectInterface * CCopasiParameterGroup::insert (const CData & data) virtual
Create and insert an undo object based on the given data. This method needs to be re-implemented in container which support INSERT and REMOVE
Parameters
const CData & data
Returns
CUndoObjectInterface * pUndoObject
Reimplemented from CDataContainer.
References CDataContainer::add(), CCopasiParameter::fromData(), CData::getProperty(), min, CCopasiParameter::mpValue, CData::OBJECT_INDEX, size(), and CDataValue::toSizeT().
Referenced by applyData(), and CFitProblem::initialize().
operator=()
CCopasiParameterGroup & CCopasiParameterGroup::operator= (const CCopasiParameterGroup & rhs)
Assignment operator
Parameters
const CCopasiParameterGroup & rhs
Returns
CCopasiParameterGroup & lhs
References CDataContainer::add(), CDataObjectMap::begin(), CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), CDataObjectMap::end(), getIndex(), CDataObject::getObjectName(), CDataContainer::getObjects(), CCopasiParameter::GROUP, CDataContainer::insert(), min, mpElementTemplates, CCopasiParameter::mpValue, CCopasiParameter::mUserInterfaceFlag, CObjectInterface::mValidity, NO_PARENT, pdelete, removeParameter(), and CDataObject::setObjectName().
Referenced by CCopasiParameterGroup(), CCopasiMethod::operator=(), CConfigurationFile::operator=(), CMIRIAMResources::operator=(), and CExperimentObjectMap::operator=().
print()
void CCopasiParameterGroup::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CDataObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiParameter.
Reimplemented in CMCAProblem, CSensProblem, CFitProblem, COptProblem, CLNAProblem, CCopasiProblem, CCopasiMethod, COscillationProblem, COptPopulationMethod, CCrossSectionProblem, and CAnalyticsProblem.
remove()
bool CCopasiParameterGroup::remove (CDataObject * pObject) virtual
Removes the pointer to the object, from the vector
Parameters
CDataObject * pObject
Returns
bool success
Reimplemented from CDataContainer.
References CCopasiParameter::mpValue, and CDataContainer::remove().
removeParameter() [1/3]
bool CCopasiParameterGroup::removeParameter (CCopasiParameter * pParameter)
Remove a parameter or subgroup from the group
Parameters
const size_t & index
Returns
bool success
References CDataObject::getObjectParent().
removeParameter() [2/3]
bool CCopasiParameterGroup::removeParameter (const size_t & index)
Remove a parameter or subgroup from the group
Parameters
const size_t & index
Returns
bool success
References CCopasiParameter::mpValue, removeParameter(), and size().
removeParameter() [3/3]
bool CCopasiParameterGroup::removeParameter (const std::string & name)
Remove a parameter or subgroup from the group
Parameters
const std::string & name
Returns
bool success
References getParameter().
Referenced by assertGroup(), assertParameter(), CExperiment::elevateChildren(), CTSSAProblem::elevateChildren(), COptProblem::elevateChildren(), CFitItem::elevateChildren(), CFitProblem::elevateChildren(), CConfigurationFile::initializeParameter(), CLyapWolfMethod::initializeParameter(), CExperiment::initializeParameter(), CFitProblem::initializeParameter(), CMCAMethod::initializeParameter(), CNewtonMethod::initializeParameter(), CSteadyStateMethod::initializeParameter(), CHybridMethod::initializeParameter(), CHybridNextReactionLSODAMethod::initializeParameter(), CHybridNextReactionRKMethod::initializeParameter(), CLsodaMethod::initializeParameter(), CStochMethod::initializeParameter(), CTauLeapMethod::initializeParameter(), CReaction::initializeParameters(), operator=(), CFitItem::removeCrossValidation(), CExperimentSet::removeExperiment(), CFitItem::removeExperiment(), COptProblem::removeOptConstraint(), COptProblem::removeOptItem(), removeParameter(), CTimeSensProblem::removeParameterCN(), CScanProblem::removeScanItem(), CTimeSensProblem::removeTargetCN(), CSensProblem::removeVariables(), CExperimentObjectMap::CDataColumn::setObjectCN(), and CExperimentObjectMap::CDataColumn::setScale().
setUserInterfaceFlag()
void CCopasiParameterGroup::setUserInterfaceFlag (const UserInterfaceFlag & flag) virtual
Reimplemented from CCopasiParameter.
References beginIndex(), endIndex(), CCopasiParameter::mUserInterfaceFlag, and CCopasiParameter::setUserInterfaceFlag().
Referenced by assertGroup(), and CRecentFiles::initializeParameter().
setValue() [1/2]
template<class CType > bool CCopasiParameterGroup::setValue (const size_t & index, const CType & value) inline
Set the value of a parameter or subgroup.
Parameters
const size_t & index
const CType & value
Returns
bool success
References getParameter(), and CCopasiParameter::setValue().
setValue() [2/2]
template<class CType > bool CCopasiParameterGroup::setValue (const std::string & name, const CType & value) inline
Set the value of a parameter or subgroup.
Parameters
const std::string & name
const CType & value
Returns
bool success
References getParameter(), and CCopasiParameter::setValue().
Referenced by SEDMLImporter::addCurveToCopasiPlot(), SEDMLImporter::addSurfaceToCopasiPlot(), SEDMLImporter::applyStyleToCopasiItem(), CSensProblem::copySensItemToParameterGroup(), COutputAssistant::createDefaultOutput(), COutputAssistant::createPlot(), CFitProblem::elevateChildren(), SEDMLImporter::importTask(), COptMethodDE::initialize(), COptMethodGA::initialize(), COptMethodGASR::initialize(), COptMethodPS::initialize(), COptMethodSRES::initialize(), COptMethodSS::initialize(), CLyapWolfMethod::initializeParameter(), CMCAMethod::initializeParameter(), CNewtonMethod::initializeParameter(), CSteadyStateMethod::initializeParameter(), CHybridMethod::initializeParameter(), CHybridNextReactionLSODAMethod::initializeParameter(), CHybridNextReactionRKMethod::initializeParameter(), CStochMethod::initializeParameter(), CTauLeapMethod::initializeParameter(), CTSSAMethod::initializeParameter(), CSteadyStateProblem::load(), CNewtonMethod::load(), CExperiment::operator=(), COptMethodSS::optimise(), TaskHandler::processEnd(), CScanProblem::setContinueFromCurrentState(), CScanProblem::setContinueOnError(), CSteadyStateProblem::setJacobianRequested(), CPlotSpecification::setLogX(), CPlotSpecification::setLogY(), CScanProblem::setOutputInSubtask(), CSteadyStateProblem::setStabilityAnalysisRequested(), CLNAProblem::setSteadyStateRequested(), CMCAProblem::setSteadyStateRequested(), CScanProblem::setSubtask(), CCSPMethod::start(), and TestOptimization().
size()
size_t CCopasiParameterGroup::size (const UserInterfaceFlag & require = UserInterfaceFlag::None, const UserInterfaceFlag & exclude = UserInterfaceFlag::None) const
The size of the parameter group @ return size_t size
References beginIndex(), endIndex(), CCopasiParameter::mpValue, and CFlags< eUserInterfaceFlag >::None.
Referenced by CFitItem::addCrossValidation(), CFitItem::addExperiment(), CRecentFiles::addFile(), applyData(), CFitProblem::calculateStatistics(), CModelAnalyzer::checkReaction(), CExperimentObjectMap::compile(), CModel::createEventsForTimeseries(), CExperiment::elevateChildren(), CODEExporter::exportReacParamsAndFuncs(), CFitItem::getCrossValidation(), CFitItem::getCrossValidationCount(), CFitItem::getCrossValidations(), CFitItem::getExperiment(), CExperimentSet::getExperimentCount(), CFitItem::getExperimentCount(), CFitItem::getExperiments(), CMIRIAMResources::getMIRIAMResource(), CScanProblem::getNumberOfScanItems(), CSensProblem::getNumberOfVariables(), CTimeSensProblem::getNumParameters(), CTimeSensProblem::getNumTargets(), CUndoData::getObject(), COptProblem::getOptConstraintSize(), COptProblem::getOptItemSize(), getParameter(), haveTemplate(), insert(), CTSSAMethod::isValidProblem(), CExperimentSet::keyToIndex(), CConfigurationFile::load(), CHybridMethodODE45::partitionSystem(), CExperiment::read(), removeParameter(), CFitProblem::restore(), CCopasiXML::saveModel(), CExperimentObjectMap::setNumCols(), and CExperiment::updateFittedPoints().
swap() [1/2]
bool CCopasiParameterGroup::swap (const size_t & iFrom, const size_t & iTo)
Swap two parameters Note: This has effect on the index_iterator and index access methods.
Parameters
const size_t & iFrom
const size_t & iTo
Returns
bool success
References beginIndex().
Referenced by CExperimentSet::sort(), and COptProblem::swapOptItem().
swap() [2/2]
bool CCopasiParameterGroup::swap (index_iterator & from, index_iterator & to)
Swap two parameters Note: This has effect on the iterator and index access methods.
Parameters
index_iterator & from
index_iterator & to
Returns
bool success
References beginIndex(), and endIndex().
toData()
CData CCopasiParameterGroup::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CCopasiParameter.
Reimplemented in CPlotSpecification, and CPlotItem.
References CData::addProperty(), CCopasiParameter::mpValue, CData::PARAMETER_VALUE, and CCopasiParameter::toData().
Referenced by CCopasiTask::createUndoData(), and CCopasiTask::toData().
updateIndex()
void CCopasiParameterGroup::updateIndex (const size_t & index, const CUndoObjectInterface * pUndoObject) virtual
Update the index of a contained object This method needs to be re-implemented in container which care about the order of contained objects
Parameters
const size_t & index
const CUndoObjectInterface * pUndoObject
Reimplemented from CUndoObjectInterface.
References C_INVALID_INDEX, getIndex(), min, and CCopasiParameter::mpValue.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CCopasiParameterGroup & o) friend
Output stream operator
Parameters
ostream & os
const CCopasiParameterGroup & o
Returns
ostream & os
operator==
bool operator== (const CCopasiParameterGroup & lhs, const CCopasiParameterGroup & rhs) friend
Comparison operator
Parameters
const CCopasiParameterGroup & lhs
const CCopasiParameterGroup & rhs
Returns
bool equal
Member Data Documentation
mpElementTemplates
CCopasiParameterGroup* CCopasiParameterGroup::mpElementTemplates {NULL } private
Referenced by getElementTemplates(), haveTemplate(), operator=(), and ~CCopasiParameterGroup().
The documentation for this class was generated from the following files:
CCopasiParameterGroup.h
CCopasiParameterGroup.cpp