COPASI API: CArrayInterface Class Reference
CArrayInterface Class Reference abstract
#include <CArray.h>
Public Types
typedef C_FLOAT64 data_type
typedef std::vector< size_t > index_type
Public Member Functions
virtual size_t dimensionality () const =0
virtual const data_type & operator[] (const index_type &index) const =0
virtual data_type & operator[] (const index_type &index)=0
virtual const index_type & size () const =0
virtual ~CArrayInterface ()
Detailed Description
This abstract class defines the interface for an n-dimensional array of floats
Member Typedef Documentation
data_type
typedef C_FLOAT64 CArrayInterface::data_type
index_type
typedef std::vector< size_t > CArrayInterface::index_type
Constructor & Destructor Documentation
~CArrayInterface()
virtual CArrayInterface::~CArrayInterface () inline virtual
Member Function Documentation
dimensionality()
virtual size_t CArrayInterface::dimensionality () const pure virtual
Implemented in CVectorInterface< VectorType >, CMatrixInterface< MatrixType >, CMatrixInterface< CMatrix< C_FLOAT64 > >, and CArray.
Referenced by CDataArray::resize().
operator[]() [1/2]
virtual const data_type& CArrayInterface::operator[] (const index_type & index) const pure virtual
Implemented in CVectorInterface< VectorType >, CMatrixInterface< MatrixType >, CMatrixInterface< CMatrix< C_FLOAT64 > >, and CArray.
operator[]() [2/2]
virtual data_type& CArrayInterface::operator[] (const index_type & index) pure virtual
Implemented in CVectorInterface< VectorType >, CMatrixInterface< MatrixType >, CMatrixInterface< CMatrix< C_FLOAT64 > >, and CArray.
size()
virtual const index_type& CArrayInterface::size () const pure virtual
Implemented in CVectorInterface< VectorType >, CMatrixInterface< MatrixType >, CMatrixInterface< CMatrix< C_FLOAT64 > >, and CArray.
Referenced by CDataArray::resizeOneDimension(), and CDataArray::size().
The documentation for this class was generated from the following file:
CArray.h