COPASI API: CCopasiParameter Class Reference
CCopasiParameter Class Reference
#include <CCopasiParameter.h>
Public Types
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
virtual void print (std::ostream *ostream) const override
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual CData toData () const override
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
void assignDefault (const void *pDefault)
void assignValidValues (const void *pValidValues)
void assignValue (const void *pValue)
CCopasiParameter ()
void createValue ()
template<class CType >
bool inValidValues (const CType &value) const
Private Attributes
CCopasiParameter::Type mType
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiParameter &o)
bool operator== (const CCopasiParameter &lhs, const CCopasiParameter &rhs)
Detailed Description
CCopasiParameter class. This class is used to describe parameters. This class is intended to be used with integration or optimization methods or reactions.
Created for COPASI by Stefan Hoops 2002
Member Typedef Documentation
UserInterfaceFlag
typedef CFlags< eUserInterfaceFlag > CCopasiParameter::UserInterfaceFlag
Member Enumeration Documentation
eUserInterfaceFlag
enum CCopasiParameter::eUserInterfaceFlag strong
Enumerator
editable
basic
unsupported
__SIZE
Type
enum CCopasiParameter::Type strong
Enumerator
DOUBLE
UDOUBLE
INT
UINT
BOOL
GROUP
STRING
CN
KEY
FILE
EXPRESSION
INVALID
__SIZE
Constructor & Destructor Documentation
CCopasiParameter() [1/4]
CCopasiParameter::CCopasiParameter (const CCopasiParameter & src) protected
CCopasiParameter() [2/4]
CCopasiParameter::CCopasiParameter () private
Default constructor
Referenced by CCopasiParameterGroup::addParameter(), fromData(), and CCopasiParameterGroup::operator=().
CCopasiParameter() [3/4]
CCopasiParameter::CCopasiParameter (const CCopasiParameter & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CCopasiParameter & src
const CDataContainer * pParent (default: NULL)
References assignDefault(), assignValidValues(), assignValue(), mpDefault, mpValidValues, and mpValue.
CCopasiParameter() [4/4]
CCopasiParameter::CCopasiParameter (const std::string & name, const Type & type, const void * pValue = NULL, const CDataContainer * pParent = NO_PARENT, const std::string & objectType = "Parameter")
Specific constructor
Parameters
const string & name
const CCopasiParameter::Type & type
const void * pValue (default: NULL)
const CDataContainer * pParent (default: NULL)
const std::string & objectType (default: "Parameter")
References assignValue().
~CCopasiParameter()
CCopasiParameter::~CCopasiParameter () virtual
Destructor
References deleteValidValues(), deleteValue(), CRootContainer::getKeyFactory(), CRootContainer::getRoot(), mKey, mpDefault, mpValidValues, mpValue, mpValueReference, mType, pdelete, and CKeyFactory::remove().
Member Function Documentation
allocateValidValues()
void CCopasiParameter::allocateValidValues (const Type & type, void *& pValidValues) static
References BOOL, CN, DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, STRING, UDOUBLE, and UINT.
Referenced by assignValidValues().
allocateValue()
void CCopasiParameter::allocateValue (const Type & type, void *& pValue) static
References BOOL, C_FLOAT64, C_INT32, CN, DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, STRING, UDOUBLE, and UINT.
Referenced by assignDefault(), and createValue().
applyData()
bool CCopasiParameter::applyData (const CData & data, CUndoData::CChangeSet & changes) override virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
Reimplemented in CCopasiParameterGroup, CPlotSpecification, and CPlotItem.
References CDataContainer::applyData(), assignValue(), createValue(), deleteValidValues(), deleteValue(), CData::getProperty(), CData::isSetProperty(), mpDefault, mpValidValues, mpValue, mType, CData::PARAMETER_TYPE, CData::PARAMETER_VALUE, CDataValue::raw(), CEnumAnnotation< Type, Enum >::toEnum(), CDataValue::toString(), and TypeName.
Referenced by CReaction::applyData(), and CCopasiParameterGroup::applyData().
assignDefault()
void CCopasiParameter::assignDefault (const void * pDefault) private
References allocateValue(), assignValue(), deleteValue(), mpDefault, and mType.
Referenced by CCopasiParameter(), operator=(), and setDefault().
assignValidValues()
void CCopasiParameter::assignValidValues (const void * pValidValues) private
References allocateValidValues(), BOOL, CN, deleteValidValues(), DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, mpValidValues, mType, STRING, UDOUBLE, and UINT.
Referenced by CCopasiParameter(), operator=(), and setValidValues().
assignValue() [1/2]
void CCopasiParameter::assignValue (const Type & type, void *& pValue, const void * pNewValue) static
References BOOL, C_FLOAT64, C_INT32, CN, DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, STRING, UDOUBLE, and UINT.
Referenced by applyData(), assignDefault(), assignValue(), CCopasiParameter(), and operator=().
assignValue() [2/2]
void CCopasiParameter::assignValue (const void * pValue) private
References assignValue(), createValue(), mpValue, and mType.
createUndoData()
void CCopasiParameter::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const override virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
Reimplemented in CCopasiParameterGroup.
References CUndoData::addProperty(), BOOL, C_FLOAT64, C_INT32, CUndoData::CHANGE, CN, CDataContainer::createUndoData(), DOUBLE, EXPRESSION, FILE, CData::getProperty(), GROUP, INT, INVALID, KEY, mpValue, mType, CData::PARAMETER_TYPE, CData::PARAMETER_VALUE, STRING, TypeName, UDOUBLE, and UINT.
Referenced by CCopasiParameterGroup::createUndoData().
createValue()
void CCopasiParameter::createValue () private
Create or copy the value
Parameters
const void * pValue
References CDataContainer::addObjectReference(), allocateValue(), BOOL, C_FLOAT64, C_INT32, CN, deleteValue(), DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, mpValue, mpValueReference, mType, pdelete, STRING, UDOUBLE, UINT, CDataObject::ValueBool, CDataObject::ValueDbl, CDataObject::ValueInt, and CDataObject::ValueString.
Referenced by applyData(), and assignValue().
deleteValidValues()
void CCopasiParameter::deleteValidValues (const Type & type, void *& pValidValues) static
References BOOL, CN, DOUBLE, EXPRESSION, fatalError, FILE, GROUP, INT, INVALID, KEY, STRING, UDOUBLE, and UINT.
Referenced by applyData(), assignValidValues(), operator=(), and ~CCopasiParameter().
deleteValue()
void CCopasiParameter::deleteValue (const Type & type, void *& pValue) static
References BOOL, C_FLOAT64, C_INT32, CN, DOUBLE, EXPRESSION, fatalError, FILE, GROUP, INT, INVALID, KEY, STRING, UDOUBLE, and UINT.
Referenced by applyData(), assignDefault(), createValue(), operator=(), and ~CCopasiParameter().
fromData()
CCopasiParameter * CCopasiParameter::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CCopasiParameter * pDataObject
References CCopasiParameter(), CData::getProperty(), GROUP, CData::OBJECT_NAME, CData::PARAMETER_TYPE, CEnumAnnotation< Type, Enum >::toEnum(), CDataValue::toString(), and TypeName.
Referenced by CCopasiParameterGroup::insert().
getCN()
CCommonName CCopasiParameter::getCN () const override virtual
Retrieve the CN of the math container The math container provides values for the numerical values of model objects. For the CN mechanism to work properly it has to pretend to be the model.
Returns
CCommonName
Reimplemented from CDataObject.
References CCommonName::escape(), CDataObject::getCN(), CDataObject::getObjectParent(), CDataObject::getObjectType(), and CCopasiParameterGroup::getUniqueParameterName().
Referenced by CFixLocalReactionParameters::changeModel(), CSBMLExporter::createKineticLaw(), CReactionInterface::createUndoData(), CFitProblem::elevateChildren(), CSensProblem::initDebugProblem(), CReaction::initializeParameters(), CSBMLExporter::replace_local_parameters(), SBMLImporter::sbmlId2CopasiCN(), CReaction::setParameterValue(), and CEvaluationNodeObject::toAST().
getDefault()
template<class CType > const CType& CCopasiParameter::getDefault () const inline
References mpDefault.
getKey()
const std::string & CCopasiParameter::getKey () const override virtual
Return the key of this model
Returns
string key
Reimplemented from CDataObject.
References mKey.
Referenced by CODEExporter::exportKineticFunction(), CODEExporterBM::exportSingleParameter(), CODEExporterC::exportSingleParameter(), CODEExporterXPPAUT::exportSingleParameter(), CCopasiParameterGroup::getKey(), CODEExporterC::KineticFunction2ODEmember(), CODEExporter::preprocess(), ParameterGroupHandler::processEnd(), and ParameterHandler::processStart().
getObjectDisplayName()
std::string CCopasiParameter::getObjectDisplayName () const override virtual
Overload display name. Special treatment for reaction parameters to provide a shorter display.
Reimplemented from CDataObject.
Reimplemented in COptItem.
References CDataObject::DisplayName, CDataObject::getObjectAncestor(), CDataObject::getObjectDisplayName(), getObjectDisplayName(), CDataObject::getObjectName(), CDataObject::getObjectParent(), getType(), CCopasiParameterGroup::getUniqueParameterName(), and GROUP.
Referenced by getObjectDisplayName(), and CFitProblem::printResult().
getType()
const CCopasiParameter::Type & CCopasiParameter::getType (void) const
Retrieve the type of the parameter.
Returns
CCopasiParameter::Type & type
References mType.
Referenced by CCopasiParameterGroup::addParameter(), SEDMLImporter::applyAlgorithm(), CCopasiParameterGroup::assertParameter(), getObjectDisplayName(), CSEDMLExporter::getParameterValueAsString(), CScanProblem::getScanItem(), CCopasiParameterGroup::getType(), COPASIHandler::processEnd(), ParameterGroupHandler::processEnd(), and CCopasiXMLInterface::saveParameter().
getUserInterfaceFlag()
const CCopasiParameter::UserInterfaceFlag & CCopasiParameter::getUserInterfaceFlag () const
References mUserInterfaceFlag.
Referenced by CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::assertGroup(), CCopasiParameterGroup::assertParameter(), CRecentFiles::initializeParameter(), and CConfigurationFile::initializeParameter().
getValidValues() [1/2]
template<class CType > std::vector< std::pair < CType, CType > >& CCopasiParameter::getValidValues () inline
Retrieve the list of valid values. Note the returned object is only valid if haveValidValues returns true;
Returns
std::vector< std::pair < CType, CType > > & validValues
References mpValidValues.
getValidValues() [2/2]
template<class CType > const std::vector< std::pair < CType, CType > >& CCopasiParameter::getValidValues () const inline
Retrieve the list of valid values. Note the returned object is only valid if haveValidValues returns true;
Returns
const std::vector< std::pair < CType, CType > > & validValues
References mpValidValues.
getValidValuesPointer()
void * CCopasiParameter::getValidValuesPointer () const
References mpValidValues.
Referenced by compareValues().
getValue() [1/2]
template<class CType > CType& CCopasiParameter::getValue () inline
References mpValue.
getValue() [2/2]
template<class CType > const CType& CCopasiParameter::getValue () const inline
References mpValue.
Referenced by SEDMLImporter::applyAlgorithm(), CCopasiParameterGroup::assertParameter(), CFixLocalReactionParameters::changeModel(), CFunctionAnalyzer::constructCallParametersActualValues(), CTSSATask::CTSSATask(), COptProblem::elevateChildren(), CFitItem::elevateChildren(), CSEDMLExporter::exportNthScanItem(), CODEExporter::exportReacParamsAndFuncs(), CScanProblem::fixBuild81(), CPlotItem::getActivity(), CTimeSensProblem::getParameterCN(), CReaction::getParameterValue(), CSEDMLExporter::getParameterValueAsString(), CTimeSensProblem::getTargetCN(), CCopasiParameterGroup::getValue(), CTSSATask::initialize(), CConfigurationFile::initializeParameter(), CLyapWolfMethod::initializeParameter(), CExperiment::initializeParameter(), CExperimentObjectMap::CDataColumn::initializeParameter(), CMCAMethod::initializeParameter(), CNewtonMethod::initializeParameter(), CSteadyStateMethod::initializeParameter(), CHybridMethod::initializeParameter(), CHybridNextReactionLSODAMethod::initializeParameter(), CHybridNextReactionRKMethod::initializeParameter(), CLsodaMethod::initializeParameter(), CStochMethod::initializeParameter(), CTauLeapMethod::initializeParameter(), CReactionInterface::loadMappingAndValues(), COPASIHandler::processEnd(), TaskHandler::processEnd(), CModelParameter::refreshFromModel(), CTimeSensProblem::removeParameterCN(), CTimeSensProblem::removeTargetCN(), CSBMLExporter::replace_local_parameters(), CCopasiXMLInterface::saveParameter(), CConfigurationFile::showItemIssues(), CProvenanceXMLWriter::updateCurrentSessionProvenance(), and CProvenanceXMLWriter::updateOrigionOfProvenance().
getValuePointer()
void * CCopasiParameter::getValuePointer () const override virtual
Retrieve a pointer to the value of the object
Reimplemented from CDataObject.
Reimplemented in COptProblem, and COptItem.
References mpValue.
Referenced by CDataModel::changeModelParameter(), and compareValues().
getValueReference()
CDataObject * CCopasiParameter::getValueReference () const
Retrieve the object which represents the value of the parameter
Returns
CDataObject * pValueReference
References mpValueReference.
Referenced by CModel::convert2NonReversible(), CObjectLists::getListOfConstObjects(), and CModelParameterGroup::getObjectUnit().
hasValidValues()
bool CCopasiParameter::hasValidValues () const
Check whether valid values are specified
Returns
bool haveValidValues
References mpValidValues.
Referenced by inValidValues().
inValidValues()
template<class CType > bool CCopasiParameter::inValidValues (const CType & value) const inline private
References hasValidValues(), and mpValidValues.
Referenced by isValidValue().
isBasic()
bool CCopasiParameter::isBasic () const
References basic, CFlags< Enum >::isSet(), and mUserInterfaceFlag.
isDefault()
bool CCopasiParameter::isDefault () const
References BOOL, C_FLOAT64, C_INT32, CN, DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, mpDefault, mpValue, mType, STRING, UDOUBLE, and UINT.
isEditable()
bool CCopasiParameter::isEditable () const
References editable, CFlags< Enum >::isSet(), and mUserInterfaceFlag.
isUnsupported()
bool CCopasiParameter::isUnsupported () const
References CFlags< Enum >::isSet(), mUserInterfaceFlag, and unsupported.
Referenced by setObjectParent().
isValidValue() [1/8]
bool CCopasiParameter::isValidValue (const bool & value) const
Check whether the value corresponds to the type
Parameters
const bool & value
Returns
bool isValidValue
References BOOL, inValidValues(), and mType.
isValidValue() [2/8]
bool CCopasiParameter::isValidValue (const C_FLOAT64 & value) const
Check whether the value corresponds to the type
Parameters
const C_FLOAT64 & value
Returns
bool isValidValue
References DOUBLE, inValidValues(), mType, and UDOUBLE.
Referenced by CCopasiParameterGroup::addParameter(), setDefault(), setValidValues(), and setValue().
isValidValue() [3/8]
bool CCopasiParameter::isValidValue (const C_INT32 & value) const
Check whether the value corresponds to the type
Parameters
const C_INT32 & value
Returns
bool isValidValue
References INT, inValidValues(), and mType.
isValidValue() [4/8]
bool CCopasiParameter::isValidValue (const CCommonName & value) const
Check whether the value corresponds to the type
Parameters
const CRegisteredCommonName & value
Returns
bool isValidValue
References CN, and mType.
isValidValue() [5/8]
template<class CType > bool CCopasiParameter::isValidValue (const CType &) const inline
All other value types are not supported
isValidValue() [6/8]
bool CCopasiParameter::isValidValue (const std::string & value) const
Check whether the value corresponds to the type
Parameters
const std::string & value
Returns
bool isValidValue
References EXPRESSION, FILE, inValidValues(), CKeyFactory::isValidKey(), KEY, mType, and STRING.
isValidValue() [7/8]
bool CCopasiParameter::isValidValue (const std::vector< CCopasiParameter * > & value) const
Check whether the value corresponds to the type
Parameters
const CCopasiParameterGroup::parameterGroup & value
Returns
bool isValidValue
References GROUP, and mType.
isValidValue() [8/8]
bool CCopasiParameter::isValidValue (const unsigned C_INT32 & value) const
Check whether the value corresponds to the type
Parameters
const unsigned C_INT32 & value
Returns
bool isValidValue
References inValidValues(), mType, and UINT.
operator=()
CCopasiParameter & CCopasiParameter::operator= (const CCopasiParameter & rhs)
Assignment operator
Parameters
const CCopasiParameter & rhs
Returns
CCopasiParameter & lhs
References assignDefault(), assignValidValues(), assignValue(), deleteValidValues(), deleteValue(), CDataObject::getObjectName(), GROUP, mpDefault, mpValidValues, mpValue, mType, mUserInterfaceFlag, CObjectInterface::mValidity, and CDataObject::setObjectName().
print()
void CCopasiParameter::print (std::ostream * ostream) const override virtual
This is the output method for any object. The default implementation provided with CDataObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CDataObject.
Reimplemented in CMCAProblem, CSensProblem, CFitProblem, COptProblem, CLNAProblem, CCopasiProblem, CCopasiParameterGroup, CCopasiMethod, COscillationProblem, COptPopulationMethod, CCrossSectionProblem, and CAnalyticsProblem.
setDefault() [1/2]
template<class CType > bool CCopasiParameter::setDefault (const CType & defaultValue) inline
Set the value of the parameter
Parameters
const const CType & defaultValue
Returns
bool isValidValue
References assignDefault(), and isValidValue().
Referenced by CCopasiParameterGroup::addParameter().
setDefault() [2/2]
bool CCopasiParameter::setDefault (const std::vector< CCopasiParameter * > & defaultValue)
Set the value of the parameter when the origin is a parameter group. This function is currently not implemented and creates a fatalError when called.
Parameters
const CCopasiParameter::parameterGroup& defaultValue
Returns
bool false
References fatalError.
setObjectParent()
bool CCopasiParameter::setObjectParent (const CDataContainer * pParent) override virtual
Reimplemented from CDataObject.
References isUnsupported(), mUserInterfaceFlag, CDataObject::setObjectParent(), and unsupported.
setUserInterfaceFlag()
void CCopasiParameter::setUserInterfaceFlag (const UserInterfaceFlag & flag) virtual
Reimplemented in CCopasiParameterGroup.
References mUserInterfaceFlag.
Referenced by CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::assertParameter(), CCheckForUpdates::initializeParameter(), CConfigurationFile::initializeParameter(), and CCopasiParameterGroup::setUserInterfaceFlag().
setValidValues() [1/2]
template<class CType , class Enum > bool CCopasiParameter::setValidValues (const CEnumAnnotation< CType, Enum > & validValues) inline
References assignValidValues(), and isValidValue().
setValidValues() [2/2]
template<class CType > bool CCopasiParameter::setValidValues (const std::vector< std::pair< CType, CType > > & validValues) inline
Set the valid values
Parameters
const std::vector< std::pair < CType, CType > > & validValues
Returns
success
References assignValidValues(), and isValidValue().
Referenced by CNewtonMethod::initializeParameter(), and CHybridMethodODE45::initializeParameter().
setValue() [1/2]
template<class CType > bool CCopasiParameter::setValue (const CType & value) inline
Set the value of the parameter
Parameters
const const CType & value
Returns
bool isValidValue
References isValidValue(), and mpValue.
Referenced by CCopasiParameterGroup::addParameter(), SEDMLImporter::applyAlgorithm(), CScanProblem::fixBuild81(), COPASIHandler::processEnd(), ParameterTextHandler::processEnd(), CReaction::setParameterValue(), CCopasiParameterGroup::setValue(), and CModelParameter::updateModel().
setValue() [2/2]
bool CCopasiParameter::setValue (const std::vector< CCopasiParameter * > & value)
Set the value of the parameter when the origin is a parameter group. This function is currently not implemented and creates a fatalError when called.
Parameters
const CCopasiParameter::parameterGroup& value
Returns
bool false
References fatalError.
toData()
CData CCopasiParameter::toData () const override virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
Reimplemented in CCopasiParameterGroup, CPlotSpecification, and CPlotItem.
References CData::addProperty(), BOOL, C_FLOAT64, C_INT32, CN, DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, mpValue, mType, CData::PARAMETER_TYPE, CData::PARAMETER_VALUE, STRING, CDataContainer::toData(), TypeName, UDOUBLE, and UINT.
Referenced by CReactionInterface::createUndoData(), and CCopasiParameterGroup::toData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CCopasiParameter & o) friend
Output stream operator
Parameters
ostream & os
const CCopasiParameter & A
Returns
ostream & os
operator==
bool operator== (const CCopasiParameter & lhs, const CCopasiParameter & rhs) friend
Comparison operator
Parameters
const CCopasiParameter & lhs
const CCopasiParameter & rhs
Returns
bool equal
Member Data Documentation
mKey
std::string CCopasiParameter::mKey protected
The key of the parameter.
Referenced by getKey(), CExperiment::initializeParameter(), and ~CCopasiParameter().
mpDefault
void* CCopasiParameter::mpDefault protected
Referenced by applyData(), assignDefault(), CCopasiParameter(), getDefault(), isDefault(), operator=(), and ~CCopasiParameter().
mpValidValues
void* CCopasiParameter::mpValidValues protected
A pointer to the valid values;
Referenced by applyData(), assignValidValues(), CCopasiParameter(), getValidValues(), getValidValuesPointer(), hasValidValues(), inValidValues(), operator=(), and ~CCopasiParameter().
mpValue
void* CCopasiParameter::mpValue protected
A pointer to the value of the parameter.
Referenced by CCopasiParameterGroup::addParameter(), applyData(), assignValue(), CCopasiParameterGroup::beginIndex(), CCopasiParameter(), CCopasiParameterGroup::clear(), CProcessReportItem::CProcessReportItem(), CCopasiParameterGroup::createUndoData(), createUndoData(), createValue(), CExperimentSet::elevateChildren(), CCopasiParameterGroup::endIndex(), CCopasiParameterGroup::getIndex(), CCopasiParameterGroup::getParameter(), CCopasiParameterGroup::getUniqueParameterName(), getValue(), getValuePointer(), CCopasiParameterGroup::insert(), isDefault(), operator=(), CCopasiParameterGroup::operator=(), CCopasiParameterGroup::remove(), CCopasiParameterGroup::removeParameter(), CExperimentObjectMap::setNumCols(), setValue(), CCopasiParameterGroup::size(), CCopasiParameterGroup::toData(), toData(), CCopasiParameterGroup::updateIndex(), ~CCopasiParameter(), and CProcessReportItem::~CProcessReportItem().
mpValueReference
CDataObject* CCopasiParameter::mpValueReference mutable protected
A pointer to the object reference for the value
Referenced by createValue(), getValueReference(), and ~CCopasiParameter().
mType
CCopasiParameter::Type CCopasiParameter::mType private
CCopasiParameter The type of the parameter
Referenced by applyData(), assignDefault(), assignValidValues(), assignValue(), createUndoData(), createValue(), getType(), isDefault(), isValidValue(), operator=(), toData(), and ~CCopasiParameter().
mUserInterfaceFlag
UserInterfaceFlag CCopasiParameter::mUserInterfaceFlag protected
Referenced by CCopasiParameterGroup::addParameter(), getUserInterfaceFlag(), isBasic(), isEditable(), isUnsupported(), operator=(), CCopasiParameterGroup::operator=(), setObjectParent(), setUserInterfaceFlag(), and CCopasiParameterGroup::setUserInterfaceFlag().
TypeName
const CEnumAnnotation< std::string, CCopasiParameter::Type > CCopasiParameter::TypeName static
String literals for the GUI to display type names of parameters known to COPASI.
CCopasiParameter class. This class is used to describe method parameters. This class is intended to be used with integration or optimization methods.
Created for COPASI by Stefan Hoops 2002
Referenced by applyData(), createUndoData(), fromData(), and toData().
XMLType
const CEnumAnnotation< std::string, CCopasiParameter::Type > CCopasiParameter::XMLType static
XML type names of parameters known to COPASI.
Referenced by ParameterHandler::processStart(), ParameterTextHandler::processStart(), and CCopasiXMLInterface::saveParameter().
The documentation for this class was generated from the following files:
CCopasiParameter.h
CCopasiParameter.cpp