COPASI API: ResultData Class Reference
ResultData Class Reference
#include <CParameterEstimationUtils.h>
Public Member Functions
bool appliesTo (CDataModel *dataModel)
void applyToModelState (int row, const std::vector< std::string > &priorities)
void applyToModelStateFromOptTask (int row, COptTask *task, const std::vector< std::string > &priorities)
std::vector< std::string > getAllExperiments ()
FittingItem * getBestItem (const std::vector< FittingItem * > &items, const std::vector< std::string > &priorities)
double getBestValueFor (const std::string &name, CheckPoint *data, const std::vector< std::string > &priorities)
CFitTask * getFitTask ()
size_t getIndex (const std::vector< FittingItem * > &items, const FittingItem *item)
std::vector< FittingItem * > getItems (const std::string &displayName)
COptTask * getOptTask ()
int numCheckPoints ()
int numFittingItems ()
ResultData ()
ResultData (const std::vector< FittingItem * > &fittingItems, const std::vector< CheckPoint * > &checkPoints, CDataModel *dataModel=NULL, bool isOptimization=false)
void setOptItemStartValues (int row, COptTask *optTask)
void setTaskStartValues (int row)
void updateFitItems ()
void updateFitItemsFromOptItems (COptTask *optTask)
~ResultData ()
Public Attributes
std::vector< CheckPoint * > mCheckPoints
std::vector< FittingItem * > mFittingItems
bool mIsOptimization
CDataModel * mpDataModel
Constructor & Destructor Documentation
ResultData() [1/2]
ResultData::ResultData ()
~ResultData()
ResultData::~ResultData ()
References mCheckPoints, and mFittingItems.
ResultData() [2/2]
ResultData::ResultData (const std::vector< FittingItem * > & fittingItems, const std::vector< CheckPoint * > & checkPoints, CDataModel * dataModel = NULL, bool isOptimization = false)
Member Function Documentation
appliesTo()
bool ResultData::appliesTo (CDataModel * dataModel)
References getFitTask(), COptItem::getObjectDisplayName(), COptProblem::getOptItemList(), COptProblem::getOptItemSize(), getOptTask(), CCopasiTask::getProblem(), mFittingItems, mIsOptimization, and sanitizeName().
applyToModelState()
void ResultData::applyToModelState (int row, const std::vector< std::string > & priorities)
References applyToModelStateFromOptTask(), getFitTask(), getOptTask(), and mIsOptimization.
applyToModelStateFromOptTask()
void ResultData::applyToModelStateFromOptTask (int row, COptTask * task, const std::vector< std::string > & priorities)
References CMathContainer::applyUpdateSequence(), C_FLOAT64, getBestValueFor(), CMathContainer::getInitialDependencies(), CMathContainer::getInitialStateObjects(), CCopasiProblem::getMathContainer(), CObjectInterface::GetObjectFromCN(), COptProblem::getOptItemList(), CCopasiTask::getProblem(), CMathDependencyGraph::getUpdateSequence(), CObjectInterface::getValuePointer(), mCheckPoints, mpDataModel, CMathContainer::pushInitialState(), and CCore::UpdateMoieties.
Referenced by applyToModelState().
getAllExperiments()
std::vector< std::string > ResultData::getAllExperiments ()
References mFittingItems.
getBestItem()
FittingItem * ResultData::getBestItem (const std::vector< FittingItem * > & items, const std::vector< std::string > & priorities)
Referenced by getBestValueFor().
getBestValueFor()
double ResultData::getBestValueFor (const std::string & name, CheckPoint * data, const std::vector< std::string > & priorities)
References getBestItem(), getIndex(), getItems(), mFittingItems, and CheckPoint::mParameters.
Referenced by applyToModelStateFromOptTask().
getFitTask()
CFitTask * ResultData::getFitTask ()
References CDataModel::getTaskList(), mpDataModel, and CDataVector< CType >::size().
Referenced by appliesTo(), applyToModelState(), setTaskStartValues(), and updateFitItems().
getIndex()
size_t ResultData::getIndex (const std::vector< FittingItem * > & items, const FittingItem * item)
Referenced by getBestValueFor().
getItems()
std::vector< FittingItem * > ResultData::getItems (const std::string & displayName)
References mFittingItems, and sanitizeName().
Referenced by getBestValueFor().
getOptTask()
COptTask * ResultData::getOptTask ()
References CDataModel::getTaskList(), mpDataModel, and CDataVector< CType >::size().
Referenced by appliesTo(), applyToModelState(), setTaskStartValues(), and updateFitItems().
numCheckPoints()
int ResultData::numCheckPoints ()
References mCheckPoints.
numFittingItems()
int ResultData::numFittingItems ()
References mFittingItems.
setOptItemStartValues()
void ResultData::setOptItemStartValues (int row, COptTask * optTask)
References COptProblem::getOptItemList(), CCopasiTask::getProblem(), mCheckPoints, CheckPoint::mParameters, mpDataModel, and COptItem::setStartValue().
Referenced by setTaskStartValues().
setTaskStartValues()
void ResultData::setTaskStartValues (int row)
References getFitTask(), getOptTask(), mIsOptimization, and setOptItemStartValues().
updateFitItems()
void ResultData::updateFitItems ()
References getFitTask(), getOptTask(), mIsOptimization, and updateFitItemsFromOptItems().
updateFitItemsFromOptItems()
void ResultData::updateFitItemsFromOptItems (COptTask * optTask)
References COptItem::getLowerBoundValue(), COptItem::getObjectDisplayName(), COptProblem::getOptItemList(), CCopasiTask::getProblem(), COptItem::getStartValue(), COptItem::getUpperBoundValue(), mFittingItems, FittingItem::mLowerBound, FittingItem::mName, FittingItem::mStartValue, FittingItem::mUpperBound, and sanitizeName().
Referenced by updateFitItems().
Member Data Documentation
mCheckPoints
std::vector<CheckPoint*> ResultData::mCheckPoints
Referenced by applyToModelStateFromOptTask(), numCheckPoints(), setOptItemStartValues(), and ~ResultData().
mFittingItems
std::vector<FittingItem*> ResultData::mFittingItems
Referenced by appliesTo(), getAllExperiments(), getBestValueFor(), getItems(), numFittingItems(), updateFitItemsFromOptItems(), and ~ResultData().
mIsOptimization
bool ResultData::mIsOptimization
Referenced by appliesTo(), applyToModelState(), setTaskStartValues(), and updateFitItems().
mpDataModel
CDataModel* ResultData::mpDataModel
Referenced by applyToModelStateFromOptTask(), getFitTask(), getOptTask(), and setOptItemStartValues().
The documentation for this class was generated from the following files:
CParameterEstimationUtils.h
CParameterEstimationUtils.cpp