COPASI API: CTransposeView< Matrix > Class Template Reference
CTransposeView< Matrix > Class Template Reference
#include <CMatrix.h>
Public Types
typedef Matrix::elementType elementType
Public Member Functions
CTransposeView (const Matrix &A)
size_t numCols () const
size_t numRows () const
elementType operator() (const size_t &row, const size_t &col) const
~CTransposeView ()
Private Attributes
const Matrix & mA
Friends
std::ostream & operator<< (std::ostream &os, const CTransposeView< Matrix > &A)
Member Typedef Documentation
elementType
template<class Matrix > typedef Matrix::elementType CTransposeView< Matrix >::elementType
Constructor & Destructor Documentation
CTransposeView()
template<class Matrix > CTransposeView< Matrix >::CTransposeView (const Matrix & A) inline
~CTransposeView()
template<class Matrix > CTransposeView< Matrix >::~CTransposeView () inline
Member Function Documentation
numCols()
template<class Matrix > size_t CTransposeView< Matrix >::numCols () const inline
The number of columns of the matrix
Returns
size_t cols
References CTransposeView< Matrix >::mA.
Referenced by CEFMAlgorithm::initialize(), and CSSAMethod::initialize().
numRows()
template<class Matrix > size_t CTransposeView< Matrix >::numRows () const inline
The number of rows of the matrix.
Returns
size_t rows
References CTransposeView< Matrix >::mA.
Referenced by CEFMAlgorithm::initialize(), and CSSAMethod::initialize().
operator()()
template<class Matrix > elementType CTransposeView< Matrix >::operator() (const size_t & row, const size_t & col) const inline
Retrieve a matrix element using the indexing style of the matrix.
Parameters
const size_t & row
const size_t & col
Returns
elementType element
References CTransposeView< Matrix >::mA.
Friends And Related Function Documentation
operator<<
template<class Matrix > std::ostream& operator<< (std::ostream & os, const CTransposeView< Matrix > & A) friend
Output stream operator
Parameters
ostream & os
const CTransposeView< Matrix > & A
Returns
ostream & os
Member Data Documentation
mA
template<class Matrix > const Matrix& CTransposeView< Matrix >::mA private
Referenced by CTransposeView< Matrix >::numCols(), CTransposeView< Matrix >::numRows(), and CTransposeView< Matrix >::operator()().
The documentation for this class was generated from the following file:
CMatrix.h