COPASI API: CMathEventQueue::CAction Class Reference
CMathEventQueue::CAction Class Reference
#include <CMathEventQueue.h>
Public Types
enum Type { Calculation = 0 , Assignment , Callback }
Public Member Functions
CAction (CMathEvent *pEvent, CMathEventQueue *pProcessQueue)
CAction (const CAction &src)
CAction (const CVector< C_FLOAT64 > &values, CMathEvent *pEvent, CMathEventQueue *pProcessQueue)
CMathEvent * getEvent () const
const C_FLOAT64 & getPriority () const
const Type & getType () const
CMath::StateChange process ()
~CAction ()
Private Member Functions
CAction ()
Private Attributes
CMathEvent * mpEvent
const C_FLOAT64 * mpPriority
CMathEventQueue * mpProcessQueue
Type mType
CVector< C_FLOAT64 > mValues
Friends
std::ostream & operator<< (std::ostream &os, const CAction &o)
Member Enumeration Documentation
Type
enum CMathEventQueue::CAction::Type
Possible action item types
Enumerator
Calculation
Assignment
Callback
Constructor & Destructor Documentation
CAction() [1/4]
CMathEventQueue::CAction::CAction () private
Default constructor (hidden)
CAction() [2/4]
CMathEventQueue::CAction::CAction (const CAction & src)
Copy constructor
Parameters
const CAction & src
CAction() [3/4]
CMathEventQueue::CAction::CAction (CMathEvent * pEvent, CMathEventQueue * pProcessQueue)
Specific constructor
Parameters
CMathEventN * pEvent
CMathEventQueue * pProcessQueue
References CEvent::Assignment, C_FLOAT64, Calculation, Callback, CEvent::Callback, CEvent::Discontinuity, CMathEvent::getPriority(), CMathEvent::getType(), CMathObject::getValuePointer(), mpPriority, and mType.
CAction() [4/4]
CMathEventQueue::CAction::CAction (const CVector< C_FLOAT64 > & values, CMathEvent * pEvent, CMathEventQueue * pProcessQueue)
Specific constructor
Parameters
const CVector< C_FLOAT64 > & values
CMathEventN * pEvent
CMathEventQueue * pProcessQueue
References C_FLOAT64, CMathEvent::getPriority(), CMathObject::getValuePointer(), and mpPriority.
~CAction()
CMathEventQueue::CAction::~CAction ()
Destructor (hidden)
Member Function Documentation
getEvent()
CMathEvent * CMathEventQueue::CAction::getEvent () const
Retrieve the event id
Returns
CMathEventN * pEvent
getPriority()
const C_FLOAT64 & CMathEventQueue::CAction::getPriority () const
Retrieve the priority
getType()
const CMathEventQueue::CAction::Type & CMathEventQueue::CAction::getType () const
Retrieve the type of action
Returns
const Type & type
process()
CMath::StateChange CMathEventQueue::CAction::process ()
Process the action
Returns
CMath::StateChange stateChanged
References CFlags< eStateChange >::None.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CAction & o) friend
Member Data Documentation
mpEvent
CMathEvent* CMathEventQueue::CAction::mpEvent private
The event associated with this action
mpPriority
const C_FLOAT64* CMathEventQueue::CAction::mpPriority private
A pointer to the priority value
Referenced by CAction().
mpProcessQueue
CMathEventQueue* CMathEventQueue::CAction::mpProcessQueue private
A pointer to the process queue to which a subsequent assignment must be added if the entry is a calculation.
mType
Type CMathEventQueue::CAction::mType private
The type of action item
Referenced by CAction().
mValues
CVector< C_FLOAT64 > CMathEventQueue::CAction::mValues private
The new value if the entry is an assignment.
The documentation for this class was generated from the following files:
CMathEventQueue.h
CMathEventQueue.cpp