COPASI API: CLPoint Class Reference
CLPoint Class Reference
#include <CLBase.h>
Public Member Functions
CLPoint ()
CLPoint (const C_FLOAT64 &x, const C_FLOAT64 &y, const C_FLOAT64 &z=0.0)
CLPoint (const Point &p)
C_FLOAT64 dot (const CLPoint &rhs) const
Point getSBMLPoint () const
C_FLOAT64 & getX ()
const C_FLOAT64 & getX () const
C_FLOAT64 & getY ()
const C_FLOAT64 & getY () const
C_FLOAT64 & getZ ()
const C_FLOAT64 & getZ () const
bool isEmpty () const
virtual void moveBy (const CLPoint &p)
CLPoint operator* (const double &rhs) const
CLPoint operator+ (const CLPoint &rhs) const
CLPoint operator- (const CLPoint &rhs) const
bool operator< (const CLPoint &rhs) const
bool operator== (const CLPoint &rhs) const
void scale (const double &scaleFactor)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
void setZ (const C_FLOAT64 &z)
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
C_FLOAT64 mX
C_FLOAT64 mY
C_FLOAT64 mZ
Protected Attributes inherited from CLBase
std::string mTag
Friends
std::ostream & operator<< (std::ostream &os, const CLPoint &p)
Detailed Description
This class describes a Point in a layout It is 2-dimensional at the moment
Constructor & Destructor Documentation
CLPoint() [1/3]
CLPoint::CLPoint () inline
Referenced by operator*(), operator+(), and operator-().
CLPoint() [2/3]
CLPoint::CLPoint (const C_FLOAT64 & x, const C_FLOAT64 & y, const C_FLOAT64 & z = 0.0) inline
CLPoint() [3/3]
CLPoint::CLPoint (const Point & p)
constructor from libsbml object
Member Function Documentation
dot()
C_FLOAT64 CLPoint::dot (const CLPoint & rhs) const inline
References mX, mY, and mZ.
Referenced by CCopasiSpringLayout::finalizeState().
getSBMLPoint()
Point CLPoint::getSBMLPoint () const
convert to sbml point
References mX, mY, and mZ.
getX() [1/2]
C_FLOAT64& CLPoint::getX () inline
References mX.
getX() [2/2]
const C_FLOAT64& CLPoint::getX () const inline
References mX.
Referenced by CCopasiSpringLayout::borderProjection(), CLLayoutRenderer::calculate_intersection(), CLayout::calculateAndAssignBounds(), CLayout::calculateBoundingBox(), CLCurve::calculateBoundingBox(), CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::distance(), CLLayoutRenderer::draw_cap(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_polygon(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), CCopasiSpringLayout::finalizeState(), CLBoundingBox::getCenter(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CLBoundingBox::getSBMLBoundingBox(), CLGraphicalObject::getX(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::map_arrow_head(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), randomlyPlaceGlyphInCompartmentGlyph(), CCopasiXML::savePosition(), and CLLineEnding::toSBML().
getY() [1/2]
C_FLOAT64& CLPoint::getY () inline
References mY.
getY() [2/2]
const C_FLOAT64& CLPoint::getY () const inline
References mY.
Referenced by CCopasiSpringLayout::borderProjection(), CLLayoutRenderer::calculate_intersection(), CLayout::calculateAndAssignBounds(), CLayout::calculateBoundingBox(), CLCurve::calculateBoundingBox(), CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::distance(), CLLayoutRenderer::draw_cap(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_polygon(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), CCopasiSpringLayout::finalizeState(), CLBoundingBox::getCenter(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CLBoundingBox::getSBMLBoundingBox(), CLGraphicalObject::getY(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::map_arrow_head(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), randomlyPlaceGlyphInCompartmentGlyph(), and CCopasiXML::savePosition().
getZ() [1/2]
C_FLOAT64& CLPoint::getZ () inline
References mZ.
getZ() [2/2]
const C_FLOAT64& CLPoint::getZ () const inline
References mZ.
Referenced by CLLayoutRenderer::calculate_intersection(), CLayout::calculateAndAssignBounds(), CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::draw_cap(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_polygon(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_text(), CLLayoutRenderer::is_curve_segment_visible(), and CLLayoutRenderer::map_arrow_head().
isEmpty()
bool CLPoint::isEmpty () const inline
References mX, mY, and mZ.
Referenced by CLBoundingBox::isEmpty(), and CLayout::moveBy().
moveBy()
virtual void CLPoint::moveBy (const CLPoint & p) inline virtual
Reimplemented from CLBase.
References mX, mY, and mZ.
Referenced by CLBoundingBox::moveBy(), and CLCurve::moveBy().
operator*()
CLPoint CLPoint::operator* (const double & rhs) const inline
References CLPoint().
operator+()
CLPoint CLPoint::operator+ (const CLPoint & rhs) const inline
References CLPoint(), mX, mY, and mZ.
operator-()
CLPoint CLPoint::operator- (const CLPoint & rhs) const inline
References CLPoint(), mX, mY, and mZ.
operator<()
bool CLPoint::operator< (const CLPoint & rhs) const inline
References mX, mY, and mZ.
operator==()
bool CLPoint::operator== (const CLPoint & rhs) const inline
References mX, mY, and mZ.
scale()
void CLPoint::scale (const double & scaleFactor) inline
References mX, and mY.
Referenced by CCopasiSpringLayout::finalizeState(), CLBoundingBox::scale(), and CLLineSegment::scale().
setX()
void CLPoint::setX (const C_FLOAT64 & x) inline
References mX.
Referenced by CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), PointHandler::processStart(), and CLGraphicalObject::setX().
setY()
void CLPoint::setY (const C_FLOAT64 & y) inline
References mY.
Referenced by CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), PointHandler::processStart(), and CLGraphicalObject::setY().
setZ()
void CLPoint::setZ (const C_FLOAT64 & z) inline
References mZ.
Referenced by CLLayoutRenderer::is_curve_segment_visible(), and PointHandler::processStart().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CLPoint & p) friend
insert operator
Member Data Documentation
mX
C_FLOAT64 CLPoint::mX protected
Referenced by dot(), getSBMLPoint(), getX(), isEmpty(), moveBy(), operator+(), operator-(), operator<(), operator==(), scale(), and setX().
mY
C_FLOAT64 CLPoint::mY protected
Referenced by dot(), getSBMLPoint(), getY(), isEmpty(), moveBy(), operator+(), operator-(), operator<(), operator==(), scale(), and setY().
mZ
C_FLOAT64 CLPoint::mZ protected
Referenced by dot(), getSBMLPoint(), getZ(), isEmpty(), moveBy(), operator+(), operator-(), operator<(), operator==(), and setZ().
The documentation for this class was generated from the following files:
CLBase.h
CLBase.cpp