COPASI API: CNL2SOL Class Reference
CNL2SOL Class Reference
#include <CNL2SOL.h>
Public Member Functions
CNL2SOL ()
int divset_N (integer *alg, integer *iv, integer *liv, integer *lv, doublereal *v)
int dn2fb_ (integer *n, integer *p, doublereal *x, doublereal *b, FNL2SOL *calcr, integer *iv, integer *liv, integer *lv, doublereal *v, integer *ui, doublereal *ur, U_fp uf)
~CNL2SOL ()
Constructor & Destructor Documentation
CNL2SOL()
CNL2SOL::CNL2SOL ()
~CNL2SOL()
CNL2SOL::~CNL2SOL ()
Member Function Documentation
divset_N()
int CNL2SOL::divset_N (integer * alg, integer * iv, integer * liv, integer * lv, doublereal * v)
References divset_().
Referenced by COptMethodNL2SOL::optimise().
dn2fb_()
int CNL2SOL::dn2fb_ (integer * n, integer * p, doublereal * x, doublereal * b, FNL2SOL * calcr, integer * iv, integer * liv, integer * lv, doublereal * v, integer * ui, doublereal * ur, U_fp uf)
References divset_(), drn2gb_(), and dv7scp_().
Referenced by COptMethodNL2SOL::optimise().
The documentation for this class was generated from the following files:
CNL2SOL.h
CNL2SOL.cpp