COPASI API: CScanItemLinear Class Reference
CScanItemLinear Class Reference
#include <CScanMethod.h>
Public Member Functions
CScanItemLinear (CCopasiParameterGroup *si)
virtual bool isValidScanItem (const bool &continueFromCurrentState)
virtual void step ()
virtual ~CScanItemLinear ()
Public Member Functions inherited from CScanItem
size_t getNumSteps () const
const CObjectInterface * getObject () const
bool isFinished () const
virtual bool isNesting () const
void reset ()
void restoreValue () const
void storeValue ()
virtual ~CScanItem ()
Protected Member Functions
virtual void ensureParameterGroupHasAllElements (CCopasiParameterGroup *pg)
Protected Member Functions inherited from CScanItem
CScanItem (CCopasiParameterGroup *si)
Private Attributes
C_FLOAT64 mFaktor
bool mLog
C_FLOAT64 mMax
C_FLOAT64 mMin
bool mUseValues
std::vector< C_FLOAT64 > mValues
Additional Inherited Members
Static Public Member Functions inherited from CScanItem
static CScanItem * createScanItemFromParameterGroup (CCopasiParameterGroup *si, CRandom *rg)
Protected Attributes inherited from CScanItem
bool mFlagFinished
size_t mIndex
size_t mNumSteps
const CObjectInterface * mpObject
C_FLOAT64 * mpObjectValue
C_FLOAT64 mStoreValue
Constructor & Destructor Documentation
CScanItemLinear()
CScanItemLinear::CScanItemLinear (CCopasiParameterGroup * si)
References C_FLOAT64, ensureParameterGroupHasAllElements(), CCopasiParameterGroup::getParameter(), CCopasiParameterGroup::getValue(), mFaktor, mLog, mMax, mMin, CScanItem::mNumSteps, mUseValues, mValues, ResultParser::saveToDouble(), and ResultParser::split().
~CScanItemLinear()
virtual CScanItemLinear::~CScanItemLinear () inline virtual
Member Function Documentation
ensureParameterGroupHasAllElements()
void CScanItemLinear::ensureParameterGroupHasAllElements (CCopasiParameterGroup * pg) protected virtual
Reimplemented from CScanItem.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, CCopasiParameter::DOUBLE, and CCopasiParameter::STRING.
Referenced by CScanItemLinear().
isValidScanItem()
bool CScanItemLinear::isValidScanItem (const bool & continueFromCurrentState) virtual
perform checks. This is used in the method::isValidProblem() method. It returns false for an invalid ScanItem and generates a CCopasiMessage
Reimplemented from CScanItem.
References CCopasiMessage::ERROR, CScanItem::isValidScanItem(), max, mFaktor, and mLog.
step()
void CScanItemLinear::step () virtual
Implements CScanItem.
References C_FLOAT64, mFaktor, CScanItem::mFlagFinished, CScanItem::mIndex, mLog, mMin, CScanItem::mNumSteps, CScanItem::mpObjectValue, mUseValues, and mValues.
Member Data Documentation
mFaktor
C_FLOAT64 CScanItemLinear::mFaktor private
Referenced by CScanItemLinear(), isValidScanItem(), and step().
mLog
bool CScanItemLinear::mLog private
Referenced by CScanItemLinear(), isValidScanItem(), and step().
mMax
C_FLOAT64 CScanItemLinear::mMax private
Referenced by CScanItemLinear().
mMin
C_FLOAT64 CScanItemLinear::mMin private
Referenced by CScanItemLinear(), and step().
mUseValues
bool CScanItemLinear::mUseValues private
Referenced by CScanItemLinear(), and step().
mValues
std::vector<C_FLOAT64> CScanItemLinear::mValues private
Referenced by CScanItemLinear(), and step().
The documentation for this class was generated from the following files:
CScanMethod.h
CScanMethod.cpp