COPASI API: CTruncatedNewton Class Reference
CTruncatedNewton Class Reference
#include <CTruncatedNewton.h>
Public Member Functions
CTruncatedNewton ()
int getptc_ (C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *)
int gtims_ (C_FLOAT64 *v, C_FLOAT64 *gv, C_INT *n, C_FLOAT64 *x, C_FLOAT64 *g, C_FLOAT64 *w, C_INT *, FTruncatedNewton *sfun, C_INT *first, C_FLOAT64 *delta, C_FLOAT64 *accrcy, C_FLOAT64 *xnorm)
int initpc_ (C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_INT *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *)
int linder_ (C_INT *, FTruncatedNewton *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *, C_FLOAT64 *, C_INT *, C_INT *, COptLog *)
int lmqn_ (C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, FTruncatedNewton *, C_INT *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, COptLog *)
int lmqnbc_ (C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, FTruncatedNewton *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, COptLog *)
int modlnp_ (C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_INT *, C_INT *, C_INT *, C_INT *, C_INT *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, FTruncatedNewton *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, COptLog *)
int msolve_ (C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *)
int setpar_ (C_INT *)
int setucr_ (C_FLOAT64 *, C_INT *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, FTruncatedNewton *, C_FLOAT64 *, C_FLOAT64 *)
int tn_ (C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, FTruncatedNewton *, C_INT *, COptLog *)
int tnbc_ (C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, FTruncatedNewton *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *, COptLog *)
~CTruncatedNewton ()
Private Attributes
subscr_ * mpsubscr_
Constructor & Destructor Documentation
CTruncatedNewton()
CTruncatedNewton::CTruncatedNewton ()
References mpsubscr_.
~CTruncatedNewton()
CTruncatedNewton::~CTruncatedNewton ()
References mpsubscr_.
Member Function Documentation
getptc_()
int CTruncatedNewton::getptc_ (C_FLOAT64 * big, C_FLOAT64 * , C_FLOAT64 * rtsmll, C_FLOAT64 * reltol, C_FLOAT64 * fabstol, C_FLOAT64 * tnytol, C_FLOAT64 * fpresn, C_FLOAT64 * eta, C_FLOAT64 * rmu, C_FLOAT64 * xbnd, C_FLOAT64 * u, C_FLOAT64 * fu, C_FLOAT64 * gu, C_FLOAT64 * xmin, C_FLOAT64 * fmin, C_FLOAT64 * gmin, C_FLOAT64 * xw, C_FLOAT64 * fw, C_FLOAT64 * gw, C_FLOAT64 * a, C_FLOAT64 * b, C_FLOAT64 * oldf, C_FLOAT64 * b1, C_FLOAT64 * scxbnd, C_FLOAT64 * e, C_FLOAT64 * step, C_FLOAT64 * factor, C_INT * braktd, C_FLOAT64 * gtest1, C_FLOAT64 * gtest2, C_FLOAT64 * tol, C_INT * ientry, C_INT * itest)
References C_FLOAT64, C_INT, FALSE_, and TRUE_.
Referenced by linder_().
gtims_()
int CTruncatedNewton::gtims_ (C_FLOAT64 * v, C_FLOAT64 * gv, C_INT * n, C_FLOAT64 * x, C_FLOAT64 * g, C_FLOAT64 * w, C_INT * , FTruncatedNewton * sfun, C_INT * first, C_FLOAT64 * delta, C_FLOAT64 * accrcy, C_FLOAT64 * xnorm)
References C_FLOAT64, C_INT, FALSE_, and subscr_2.
initpc_()
int CTruncatedNewton::initpc_ (C_FLOAT64 * diagb, C_FLOAT64 * emat, C_INT * n, C_FLOAT64 * w, C_INT * , C_INT * modet, C_INT * upd1, C_FLOAT64 * yksk, C_FLOAT64 * , C_FLOAT64 * yrsr, C_INT * lreset)
References initp3_(), and subscr_2.
Referenced by modlnp_().
linder_()
int CTruncatedNewton::linder_ (C_INT * n, FTruncatedNewton * sfun, C_FLOAT64 * small, C_FLOAT64 * epsmch, C_FLOAT64 * reltol, C_FLOAT64 * fabstol, C_FLOAT64 * tnytol, C_FLOAT64 * eta, C_FLOAT64 * , C_FLOAT64 * xbnd, C_FLOAT64 * p, C_FLOAT64 * gtp, C_FLOAT64 * x, C_FLOAT64 * f, C_FLOAT64 * alpha, C_FLOAT64 * g, C_INT * nftotl, C_INT * iflag, C_FLOAT64 * w, C_INT * , C_INT * lsprnt, COptLog * log)
References C_FLOAT64, C_INT, ddot_(), getptc_(), and lsout_().
lmqn_()
int CTruncatedNewton::lmqn_ (C_INT * ifail, C_INT * n, C_FLOAT64 * x, C_FLOAT64 * f, C_FLOAT64 * g, C_FLOAT64 * w, C_INT * lw, FTruncatedNewton * sfun, C_INT * msglvl, C_INT * maxit, C_INT * maxfun, C_FLOAT64 * eta, C_FLOAT64 * stepmx, C_FLOAT64 * accrcy, C_FLOAT64 * xtol, COptLog * log)
References C_FLOAT64, C_INT, chkucp_(), modlnp_(), setpar_(), setucr_(), subscr_1, and TRUE_.
Referenced by tn_().
lmqnbc_()
int CTruncatedNewton::lmqnbc_ (C_INT * ifail, C_INT * n, C_FLOAT64 * x, C_FLOAT64 * f, C_FLOAT64 * g, C_FLOAT64 * w, C_INT * lw, FTruncatedNewton * sfun, C_FLOAT64 * low, C_FLOAT64 * up, C_INT * ipivot, C_INT * msglvl, C_INT * maxit, C_INT * maxfun, C_FLOAT64 * eta, C_FLOAT64 * stepmx, C_FLOAT64 * accrcy, C_FLOAT64 * xtol, COptLog * log)
References C_FLOAT64, C_INT, chkucp_(), crash_(), ddot_(), COptLog::enterLogEntry(), FALSE_, setpar_(), setucr_(), subscr_1, TRUE_, and ztime_().
Referenced by tnbc_().
modlnp_()
int CTruncatedNewton::modlnp_ (C_INT * modet, C_FLOAT64 * zsol, C_FLOAT64 * gv, C_FLOAT64 * r__, C_FLOAT64 * v, C_FLOAT64 * diagb, C_FLOAT64 * emat, C_FLOAT64 * x, C_FLOAT64 * g, C_FLOAT64 * zk, C_INT * n, C_FLOAT64 * w, C_INT * lw, C_INT * , C_INT * maxit, C_INT * nfeval, C_INT * , C_INT * nlincg, C_INT * upd1, C_FLOAT64 * yksk, C_FLOAT64 * gsk, C_FLOAT64 * yrsr, C_INT * lreset, FTruncatedNewton * sfun, C_INT * bounds, C_INT * ipivot, C_FLOAT64 * accrcy, C_FLOAT64 * gtp, C_FLOAT64 * gnorm, C_FLOAT64 * xnorm, COptLog * log)
References C_FLOAT64, C_INT, ddot_(), COptLog::enterLogEntry(), initpc_(), msolve_(), TRUE_, and ztime_().
Referenced by lmqn_().
msolve_()
int CTruncatedNewton::msolve_ (C_FLOAT64 * g, C_FLOAT64 * y, C_INT * n, C_FLOAT64 * w, C_INT * , C_INT * upd1, C_FLOAT64 * yksk, C_FLOAT64 * gsk, C_FLOAT64 * yrsr, C_INT * lreset, C_INT * first)
References mslv_(), and subscr_2.
Referenced by modlnp_().
setpar_()
int CTruncatedNewton::setpar_ (C_INT * n)
References C_INT, and subscr_3.
Referenced by lmqn_(), and lmqnbc_().
setucr_()
int CTruncatedNewton::setucr_ (C_FLOAT64 * , C_INT * nftotl, C_INT * niter, C_INT * n, C_FLOAT64 * f, C_FLOAT64 * fnew, C_FLOAT64 * fm, C_FLOAT64 * gtg, C_FLOAT64 * oldf, FTruncatedNewton * sfun, C_FLOAT64 * g, C_FLOAT64 * x)
References ddot_().
Referenced by lmqn_(), and lmqnbc_().
tn_()
int CTruncatedNewton::tn_ (C_INT * ierror, C_INT * n, C_FLOAT64 * x, C_FLOAT64 * f, C_FLOAT64 * g, C_FLOAT64 * w, C_INT * lw, FTruncatedNewton * sfun, C_INT * logverbosity, COptLog * log)
References C_FLOAT64, C_INT, lmqn_(), and mchpr1_().
tnbc_()
int CTruncatedNewton::tnbc_ (C_INT * ierror, C_INT * n, C_FLOAT64 * x, C_FLOAT64 * f, C_FLOAT64 * g, C_FLOAT64 * w, C_INT * lw, FTruncatedNewton * sfun, C_FLOAT64 * low, C_FLOAT64 * up, C_INT * ipivot, C_INT * logverbosity, COptLog * log)
References C_FLOAT64, C_INT, lmqnbc_(), and mchpr1_().
Referenced by COptMethodTruncatedNewton::optimise().
Member Data Documentation
mpsubscr_
subscr_* CTruncatedNewton::mpsubscr_ private
Referenced by CTruncatedNewton(), and ~CTruncatedNewton().
The documentation for this class was generated from the following files:
CTruncatedNewton.h
CTruncatedNewton.cpp