COPASI API: CAnnotation Class Reference
CAnnotation Class Reference
#include <CAnnotation.h>
Public Types
typedef std::map< std::string, std::string > UnsupportedAnnotation
Public Member Functions
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual const std::string & getKey () const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Protected Attributes
std::string mKey
Static Private Member Functions
static bool isValidXML (const std::string &xml)
Private Attributes
std::string mMiriamAnnotation
std::string mNotes
UnsupportedAnnotation mUnsupportedAnnotations
std::string mXMLId
Static Private Attributes
static std::map< CDataContainer *, CMIRIAMInfo * > Container2Info
Member Typedef Documentation
UnsupportedAnnotation
typedef std::map< std::string, std::string > CAnnotation::UnsupportedAnnotation
Constructor & Destructor Documentation
CAnnotation() [1/2]
CAnnotation::CAnnotation ()
Default constructor
CAnnotation() [2/2]
CAnnotation::CAnnotation (const CAnnotation & src)
Copy constructor
Parameters
const CAnnotation & src
~CAnnotation()
CAnnotation::~CAnnotation () virtual
Destructor
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
addUnsupportedAnnotation()
bool CAnnotation::addUnsupportedAnnotation (const std::string & name, const std::string & xml)
Add an unsupported annotation
Parameters
const std::string & name
const std::string & xml
Returns
bool success
References CCopasiMessage::ERROR, isValidXML(), MCAnnotation, and mUnsupportedAnnotations.
Referenced by SBMLImporter::importNotes().
allocateMiriamInfo()
CMIRIAMInfo * CAnnotation::allocateMiriamInfo (CDataContainer * pParent) static
Allocat a MIRIAM Info object for the given CDataContainer * pParent. The ownership is with the parent
Parameters
CDataContainer * pParent
Returns
CMIRIAMInfo * pMiriamInfo
References Container2Info.
Referenced by CDataContainer::getObject().
applyData()
bool CAnnotation::applyData (const CData & data, CUndoData::CChangeSet & changes)
Apply the provided data to the annotation
Parameters
const CData & data
Returns
bool success
References CData::getProperty(), CData::isSetProperty(), mMiriamAnnotation, mNotes, and CDataValue::toString().
Referenced by CFunction::applyData(), CEvent::applyData(), CModelParameterSet::applyData(), CReaction::applyData(), CUnitDefinition::applyData(), and CModelEntity::applyData().
castObject() [1/2]
CAnnotation * CAnnotation::castObject (CDataObject * pObject) static
Referenced by CDataContainer::getObject(), SBMLImporter::importMIRIAM(), CMIRIAMInfo::load(), and CSBMLExporter::updateMIRIAMAnnotation().
castObject() [2/2]
const CAnnotation * CAnnotation::castObject (const CDataObject * pObject) static
createUndoData()
void CAnnotation::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
References CUndoData::addProperty(), CUndoData::CHANGE, CData::getProperty(), CUndoData::INSERT, mMiriamAnnotation, mNotes, and CUndoData::REMOVE.
Referenced by CFunction::createUndoData(), CEvent::createUndoData(), CModelParameterSet::createUndoData(), CReaction::createUndoData(), CUnitDefinition::createUndoData(), and CModelEntity::createUndoData().
freeMiriamInfo()
void CAnnotation::freeMiriamInfo (CDataContainer * pParent) static
Free if possible an existing MIRIAM Info object for the given CDataContainer * pParent.
Returns
CMIRIAMInfo * pMiriamInfo
References Container2Info.
Referenced by CMIRIAMInfo::~CMIRIAMInfo().
getKey()
const std::string & CAnnotation::getKey () const virtual
Retrieve the key
Returns
std::string key
Reimplemented in CModelEntity, CUnitDefinition, CReaction, CModelParameterSet, CModel, CEvent, and CFunction.
References mKey.
Referenced by CFunction::getKey(), CMIRIAMInfo::getKey(), CEvent::getKey(), CReaction::getKey(), CUnitDefinition::getKey(), CModelEntity::getKey(), SBMLImporter::importMIRIAM(), and CMIRIAMInfo::save().
getMiriamAnnotation()
const std::string & CAnnotation::getMiriamAnnotation () const
Retrieve the RDF/XML representation of the MIRIAM annotation
Returns
const std::string & miriamAnnotation
References mMiriamAnnotation.
Referenced by CEvent::CEvent(), CFunction::CFunction(), CModelEntity::CModelEntity(), CModelParameterSet::CModelParameterSet(), CReaction::CReaction(), CUnitDefinition::CUnitDefinition(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), SBMLImporter::importMIRIAM(), CMIRIAMInfo::load(), CCopasiXML::saveAnnotation(), and CSBMLExporter::updateMIRIAMAnnotation().
getNotes()
const std::string & CAnnotation::getNotes () const
Retrieve the XHTML notes
Returns
const std::string & notes
References mNotes.
Referenced by CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CModel::initObjects(), CCopasiXML::saveAnnotation(), and CSBMLExporter::setSBMLNotes().
getUnsupportedAnnotations() [1/2]
CAnnotation::UnsupportedAnnotation & CAnnotation::getUnsupportedAnnotations ()
Retrieve the unsupported annotations in xml format.
Returns
std::map< std::string, std::string > & unsupportedAnnotations
References mUnsupportedAnnotations.
Referenced by CompartmentHandler::processEnd(), EventHandler::processEnd(), FunctionHandler::processEnd(), MetaboliteHandler::processEnd(), ModelHandler::processEnd(), ModelValueHandler::processEnd(), ReactionHandler::processEnd(), UnitDefinitionHandler::processEnd(), CCopasiXML::saveAnnotation(), and CSBMLExporter::setSBMLNotes().
getUnsupportedAnnotations() [2/2]
const CAnnotation::UnsupportedAnnotation & CAnnotation::getUnsupportedAnnotations () const
References mUnsupportedAnnotations.
initMiriamAnnotation()
void CAnnotation::initMiriamAnnotation (const std::string & newId)
References mMiriamAnnotation, and mXMLId.
Referenced by CEvent::CEvent(), CFunction::CFunction(), CModelEntity::CModelEntity(), CModelParameterSet::CModelParameterSet(), CReaction::CReaction(), and CUnitDefinition::CUnitDefinition().
isValidXML()
bool CAnnotation::isValidXML (const std::string & xml) static private
References BUFFER_SIZE, CCopasiMessage::getLastMessage(), CExpatTemplate< CType >::parse(), and CCopasiMessage::size().
Referenced by addUnsupportedAnnotation(), and replaceUnsupportedAnnotation().
operator==()
bool CAnnotation::operator== (const CAnnotation & rhs) const
Comparison operator
Parameters
const CAnnotation & rhs
Returns
bool equal
References CRDFUtilities::fixLocalFileAboutReference(), mMiriamAnnotation, mNotes, and mXMLId.
removeUnsupportedAnnotation()
bool CAnnotation::removeUnsupportedAnnotation (const std::string & name)
Remove an unsupported annotation
Parameters
const std::string & name
Returns
bool success
References mUnsupportedAnnotations.
replaceUnsupportedAnnotation()
bool CAnnotation::replaceUnsupportedAnnotation (const std::string & name, const std::string & xml)
Replace an unsupported annotation
Parameters
const std::string & name
const std::string & xml
Returns
bool success
References CCopasiMessage::ERROR, isValidXML(), MCAnnotation, and mUnsupportedAnnotations.
setMiriamAnnotation()
void CAnnotation::setMiriamAnnotation (const std::string & miriamAnnotation, const std::string & newId, const std::string & oldId)
Set the RDF/XML representation of the MIRIAM annotation
Parameters
const std::string & miriamAnnotation
const std::string & newId
const std::string & oldId
References CRDFUtilities::fixLocalFileAboutReference(), mMiriamAnnotation, and mXMLId.
Referenced by CEvent::CEvent(), CFunction::CFunction(), CModelEntity::CModelEntity(), CModelParameterSet::CModelParameterSet(), CReaction::CReaction(), CUnitDefinition::CUnitDefinition(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), SBMLImporter::importMIRIAM(), CompartmentHandler::processEnd(), EventHandler::processEnd(), FunctionHandler::processEnd(), MetaboliteHandler::processEnd(), ModelHandler::processEnd(), ModelParameterSetHandler::processEnd(), ModelValueHandler::processEnd(), ReactionHandler::processEnd(), UnitDefinitionHandler::processEnd(), and CMIRIAMInfo::save().
setNotes()
void CAnnotation::setNotes (const std::string & notes)
Set the XHTML Notes
Parameters
const std::string & notes
References mNotes.
Referenced by CModelVersion::CModelVersion(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), SBMLImporter::importNotes(), CModel::load(), CompartmentHandler::processEnd(), EventHandler::processEnd(), FunctionHandler::processEnd(), MetaboliteHandler::processEnd(), ModelHandler::processEnd(), ModelValueHandler::processEnd(), ReactionHandler::processEnd(), and UnitDefinitionHandler::processEnd().
toData()
CData CAnnotation::toData () const
Retrieve the data describing the annotation
Returns
CData data
References CData::addProperty(), mMiriamAnnotation, and mNotes.
Referenced by CFunction::toData(), CEvent::toData(), CModelParameterSet::toData(), CReaction::toData(), CUnitDefinition::toData(), and CModelEntity::toData().
Member Data Documentation
Container2Info
std::map< CDataContainer *, CMIRIAMInfo * > CAnnotation::Container2Info static private
Referenced by allocateMiriamInfo(), and freeMiriamInfo().
mKey
std::string CAnnotation::mKey protected
Key of the model entity. It is stored here, but constructed in the derived classes.
Referenced by CEvent::CEvent(), CFunction::CFunction(), CModelEntity::CModelEntity(), CReaction::CReaction(), CUnitDefinition::CUnitDefinition(), getKey(), CModel::getKey(), CUnitDefinition::setup(), ~CAnnotation(), CCompartment::~CCompartment(), CEvent::~CEvent(), CFunction::~CFunction(), CMetab::~CMetab(), CModel::~CModel(), CReaction::~CReaction(), and CUnitDefinition::~CUnitDefinition().
mMiriamAnnotation
std::string CAnnotation::mMiriamAnnotation private
MIRIAM compliant annotation in RDF/XML format
Referenced by applyData(), createUndoData(), getMiriamAnnotation(), initMiriamAnnotation(), operator==(), setMiriamAnnotation(), and toData().
mNotes
std::string CAnnotation::mNotes private
Notes in XHTML format
Referenced by applyData(), createUndoData(), getNotes(), operator==(), setNotes(), and toData().
mUnsupportedAnnotations
UnsupportedAnnotation CAnnotation::mUnsupportedAnnotations private
The annotations which are not supported by COPASI. Note, the name is enforced to be unique.
Referenced by addUnsupportedAnnotation(), getUnsupportedAnnotations(), removeUnsupportedAnnotation(), and replaceUnsupportedAnnotation().
mXMLId
std::string CAnnotation::mXMLId private
The XMLId used in the about statement
Referenced by initMiriamAnnotation(), operator==(), and setMiriamAnnotation().
The documentation for this class was generated from the following files:
CAnnotation.h
CAnnotation.cpp