COPASI API: CData Class Reference
CData Class Reference
#include <CData.h>
Public Types
typedef std::map< std::string, CDataValue >::const_iterator const_iterator
enum Property {
EXPRESSION = 0 , INITIAL_EXPRESSION , INITIAL_VALUE , INITIAL_INTENSIVE_VALUE ,
SIMULATION_TYPE , SPATIAL_DIMENSION , ADD_NOISE , NOISE_EXPRESSION ,
CHEMICAL_EQUATION , KINETIC_LAW , KINETIC_LAW_UNIT_TYPE , KINETIC_LAW_VARIABLE_MAPPING ,
LOCAL_REACTION_PARAMETERS , SCALING_COMPARTMENT , OBJECT_UUID , OBJECT_NAME ,
OBJECT_PARENT_CN , OBJECT_TYPE , OBJECT_FLAG , OBJECT_HASH ,
OBJECT_INDEX , OBJECT_REFERENCES , OBJECT_REFERENCE , OBJECT_REFERENCE_CN ,
OBJECT_REFERENCE_INDEX , OBJECT_POINTER , EVALUATION_TREE_TYPE , TASK_TYPE ,
TASK_SCHEDULED , TASK_UPDATE_MODEL , TASK_REPORT , TASK_REPORT_TARGET ,
TASK_REPORT_APPEND , TASK_REPORT_CONFIRM_OVERWRITE , PROBLEM , METHOD ,
METHOD_TYPE , PLOT_TYPE , PLOT_ITEM_TYPE , PARAMETER_TYPE ,
PARAMETER_ROLE , PARAMETER_USED , PARAMETER_VALUE , UNIT ,
VOLUME_UNIT , AREA_UNIT , LENGTH_UNIT , TIME_UNIT ,
QUANTITY_UNIT , MODEL_TYPE , AVOGADRO_NUMBER , DIMENSIONALITY ,
ARRAY_ELEMENT_INDEX , REPORT_SEPARATOR , REPORT_IS_TABLE , REPORT_SHOW_TITLE ,
REPORT_PRECISION , NOTES , MIRIAM_RDF_XML , MIRIAM_PREDICATE ,
MIRIAM_RESOURCE , MIRIAM_DESCRIPTION , MIRIAM_ID , DATE ,
GIVEN_NAME , FAMILY_NAME , EMAIL , ORGANIZATION ,
FRAMEWORK , VALUE , DELAY_ASSIGNMENT , FIRE_AT_INITIALTIME ,
PERSISTENT_TRIGGER , TRIGGER_EXPRESSION , DELAY_EXPRESSION , PRIORITY_EXPRESSION ,
ASSIGNMENTS , VECTOR_CONTENT , UNIT_SYMBOL , UNIT_EXPRESSION ,
__SIZE
}
typedef CDataValue::Type Type
Public Member Functions
bool addProperty (const Property &property, const CDataValue &value)
bool addProperty (const std::string &name, const CDataValue &value)
bool appendData (const CData &data)
const_iterator begin () const
CData ()
CData (const CData &src)
void clear ()
bool empty () const
const_iterator end () const
CDataValue & getProperty (const Property &property)
const CDataValue & getProperty (const Property &property) const
CDataValue & getProperty (const std::string &name)
const CDataValue & getProperty (const std::string &name) const
std::string hash () const
bool isSetProperty (const Property &property) const
bool isSetProperty (const std::string &name) const
bool operator!= (const CData &rhs) const
CData & operator= (const CData &rhs)
bool operator== (const CData &rhs) const
bool removeProperty (const Property &property)
bool removeProperty (const std::string &name)
~CData ()
Static Public Attributes
static const CEnumAnnotation< std::string, Property > PropertyName
Friends
std::ostream & operator<< (std::ostream &os, const CData &o)
std::istream & operator>> (std::istream &is, const CData &i)
Member Typedef Documentation
const_iterator
typedef std::map< std::string, CDataValue >::const_iterator CData::const_iterator
Type
typedef CDataValue::Type CData::Type
Member Enumeration Documentation
Property
enum CData::Property
Enumerator
EXPRESSION
INITIAL_EXPRESSION
INITIAL_VALUE
INITIAL_INTENSIVE_VALUE
SIMULATION_TYPE
SPATIAL_DIMENSION
ADD_NOISE
NOISE_EXPRESSION
CHEMICAL_EQUATION
KINETIC_LAW
KINETIC_LAW_UNIT_TYPE
KINETIC_LAW_VARIABLE_MAPPING
LOCAL_REACTION_PARAMETERS
SCALING_COMPARTMENT
OBJECT_UUID
OBJECT_NAME
OBJECT_PARENT_CN
OBJECT_TYPE
OBJECT_FLAG
OBJECT_HASH
OBJECT_INDEX
OBJECT_REFERENCES
OBJECT_REFERENCE
OBJECT_REFERENCE_CN
OBJECT_REFERENCE_INDEX
OBJECT_POINTER
EVALUATION_TREE_TYPE
TASK_TYPE
TASK_SCHEDULED
TASK_UPDATE_MODEL
TASK_REPORT
TASK_REPORT_TARGET
TASK_REPORT_APPEND
TASK_REPORT_CONFIRM_OVERWRITE
PROBLEM
METHOD
METHOD_TYPE
PLOT_TYPE
PLOT_ITEM_TYPE
PARAMETER_TYPE
PARAMETER_ROLE
PARAMETER_USED
PARAMETER_VALUE
UNIT
VOLUME_UNIT
AREA_UNIT
LENGTH_UNIT
TIME_UNIT
QUANTITY_UNIT
MODEL_TYPE
AVOGADRO_NUMBER
DIMENSIONALITY
ARRAY_ELEMENT_INDEX
REPORT_SEPARATOR
REPORT_IS_TABLE
REPORT_SHOW_TITLE
REPORT_PRECISION
NOTES
MIRIAM_RDF_XML
MIRIAM_PREDICATE
MIRIAM_RESOURCE
MIRIAM_DESCRIPTION
MIRIAM_ID
DATE
GIVEN_NAME
FAMILY_NAME
EMAIL
ORGANIZATION
FRAMEWORK
VALUE
DELAY_ASSIGNMENT
FIRE_AT_INITIALTIME
PERSISTENT_TRIGGER
TRIGGER_EXPRESSION
DELAY_EXPRESSION
PRIORITY_EXPRESSION
ASSIGNMENTS
VECTOR_CONTENT
UNIT_SYMBOL
UNIT_EXPRESSION
__SIZE
Constructor & Destructor Documentation
CData() [1/2]
CData::CData ()
CData() [2/2]
CData::CData (const CData & src)
~CData()
CData::~CData ()
Member Function Documentation
addProperty() [1/2]
bool CData::addProperty (const Property & property, const CDataValue & value)
References addProperty(), and PropertyName.
addProperty() [2/2]
bool CData::addProperty (const std::string & name, const CDataValue & value)
References end().
Referenced by CUndoData::addMetaDataProperty(), addProperty(), CUndoData::addProperty(), CEvent::applyData(), CDataObject::applyData(), CReactionInterface::createUndoData(), CCompartment::createUndoData(), CEvent::createUndoData(), CModel::createUndoData(), CModelParameter::createUndoData(), CModelParameterSpecies::createUndoData(), CReaction::createUndoData(), CDataObject::createUndoData(), CUndoData::CUndoData(), CDataVector< CType >::toData(), CDataVectorN< CType >::toData(), CFunctionParameter::toData(), CBiologicalDescription::toData(), CCreator::toData(), CMIRIAMInfo::toData(), CModification::toData(), CReference::toData(), CAnnotation::toData(), CCompartment::toData(), CEventAssignment::toData(), CEvent::toData(), CModel::toData(), CModelParameter::toData(), CModelParameterSpecies::toData(), CModelParameterGroup::toData(), CModelValue::toData(), CReaction::toData(), CReportDefinition::toData(), CCopasiParameterGroup::toData(), CCopasiTask::toData(), CUnitDefinition::toData(), CArrayElementReference::toData(), CDataObject::toData(), CMetab::toData(), CModelEntity::toData(), and CCopasiParameter::toData().
appendData()
bool CData::appendData (const CData & data)
References begin(), and end().
Referenced by CUndoData::appendMetaData(), CFunction::toData(), CEvent::toData(), CModelParameterSet::toData(), CReaction::toData(), CUnitDefinition::toData(), and CModelEntity::toData().
begin()
CData::const_iterator CData::begin () const
Referenced by appendData(), CUndoData::appendData(), CCopasiParameterGroup::createUndoData(), and CUndoData::CUndoData().
clear()
void CData::clear ()
Referenced by CUndoData::clear().
empty()
bool CData::empty () const
Referenced by CUndoData::getParent().
end()
CData::const_iterator CData::end () const
Referenced by addProperty(), appendData(), CUndoData::appendData(), CCopasiParameterGroup::createUndoData(), CUndoData::CUndoData(), getProperty(), isSetProperty(), and removeProperty().
getProperty() [1/4]
CDataValue & CData::getProperty (const Property & property)
References getProperty(), and PropertyName.
getProperty() [2/4]
const CDataValue & CData::getProperty (const Property & property) const
References getProperty(), and PropertyName.
getProperty() [3/4]
CDataValue & CData::getProperty (const std::string & name)
References end(), and CDataValue::INVALID.
getProperty() [4/4]
const CDataValue & CData::getProperty (const std::string & name) const
References end(), and CDataValue::INVALID.
Referenced by CDataVector< CType >::applyData(), CDataVectorN< CType >::applyData(), CFunctionParameter::applyData(), CBiologicalDescription::applyData(), CCreator::applyData(), CMIRIAMInfo::applyData(), CModification::applyData(), CReference::applyData(), CAnnotation::applyData(), CCompartment::applyData(), CEventAssignment::applyData(), CEvent::applyData(), CModel::applyData(), CModelParameter::applyData(), CModelParameterGroup::applyData(), CModelValue::applyData(), CReaction::applyData(), CReportDefinition::applyData(), CCopasiParameterGroup::applyData(), CCopasiTask::applyData(), CUnitDefinition::applyData(), CArrayElementReference::applyData(), CDataObject::applyData(), CMetab::applyData(), CModelEntity::applyData(), CCopasiParameter::applyData(), CUndoData::change(), CReactionInterface::createUndoData(), CBiologicalDescription::createUndoData(), CCreator::createUndoData(), CMIRIAMInfo::createUndoData(), CModification::createUndoData(), CReference::createUndoData(), CAnnotation::createUndoData(), CCompartment::createUndoData(), CEventAssignment::createUndoData(), CEvent::createUndoData(), CModel::createUndoData(), CModelParameter::createUndoData(), CModelParameterSpecies::createUndoData(), CModelParameterGroup::createUndoData(), CModelValue::createUndoData(), CReaction::createUndoData(), CReportDefinition::createUndoData(), CCopasiParameterGroup::createUndoData(), CCopasiTask::createUndoData(), CUnitDefinition::createUndoData(), CDataObject::createUndoData(), CMetab::createUndoData(), CModelEntity::createUndoData(), CCopasiParameter::createUndoData(), CUndoData::CUndoData(), CCommonName::fromData(), CDataModel::fromData(), CArrayElementReference::fromData(), CDataContainer::fromData(), CDataObject::fromData(), CEvaluationTree::fromData(), CFunctionParameter::fromData(), CLayout::fromData(), CLMetabGlyph::fromData(), CLCompartmentGlyph::fromData(), CLTextGlyph::fromData(), CLGradientBase::fromData(), CLGraphicalObject::fromData(), CLReferenceGlyph::fromData(), CLMetabReferenceGlyph::fromData(), CLGeneralGlyph::fromData(), CLReactionGlyph::fromData(), CCreator::fromData(), CModification::fromData(), CReference::fromData(), CChemEqElement::fromData(), CCompartment::fromData(), CEventAssignment::fromData(), CEvent::fromData(), CMetab::fromData(), CMetabOld::fromData(), CModel::fromData(), CModelParameter::fromData(), CModelParameterSet::fromData(), CModelValue::fromData(), CMoiety::fromData(), CReaction::fromData(), CFittingPoint::fromData(), CPlotItem::fromData(), CPlotSpecification::fromData(), CReportDefinition::fromData(), CCopasiParameter::fromData(), CCopasiTask::fromData(), CSlider::fromData(), CUnitDefinition::fromData(), CUndoData::getMetaDataProperty(), CUndoData::getObject(), CUndoData::getObjectDisplayName(), CUndoData::getObjectType(), CUndoData::getParent(), getProperty(), CDataVector< CType >::insert(), CModelParameterGroup::insert(), CModelParameterSet::insert(), CCopasiParameterGroup::insert(), CUndoData::insert(), CUndoData::operator<(), CUndoData::remove(), CEvent::toData(), and CModelParameterSpecies::toData().
hash()
std::string CData::hash () const
References Cmd5::digest().
Referenced by CBiologicalDescription::toData(), CCreator::toData(), CModification::toData(), and CReference::toData().
isSetProperty() [1/2]
bool CData::isSetProperty (const Property & property) const
References isSetProperty(), and PropertyName.
isSetProperty() [2/2]
bool CData::isSetProperty (const std::string & name) const
References end().
Referenced by CFunctionParameter::applyData(), CBiologicalDescription::applyData(), CCreator::applyData(), CMIRIAMInfo::applyData(), CModification::applyData(), CReference::applyData(), CAnnotation::applyData(), CCompartment::applyData(), CEventAssignment::applyData(), CEvent::applyData(), CModel::applyData(), CModelParameter::applyData(), CModelParameterGroup::applyData(), CModelValue::applyData(), CReaction::applyData(), CReportDefinition::applyData(), CCopasiParameterGroup::applyData(), CCopasiTask::applyData(), CUnitDefinition::applyData(), CArrayElementReference::applyData(), CDataObject::applyData(), CMetab::applyData(), CModelEntity::applyData(), CCopasiParameter::applyData(), CArrayElementReference::fromData(), CUndoData::getObject(), CDataVector< CType >::insert(), CUndoData::isSetMetaDataProperty(), isSetProperty(), and CUndoData::isSetProperty().
operator!=()
bool CData::operator!= (const CData & rhs) const
operator=()
CData & CData::operator= (const CData & rhs)
operator==()
bool CData::operator== (const CData & rhs) const
removeProperty() [1/2]
bool CData::removeProperty (const Property & property)
References PropertyName, and removeProperty().
removeProperty() [2/2]
bool CData::removeProperty (const std::string & name)
References end().
Referenced by CUndoData::addProperty(), CUndoData::CUndoData(), CUndoData::removeMetaDataProperty(), removeProperty(), CUndoData::removeProperty(), CBiologicalDescription::toData(), CCreator::toData(), CModification::toData(), and CReference::toData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CData & o) friend
operator>>
std::istream& operator>> (std::istream & is, const CData & i) friend
Member Data Documentation
PropertyName
const CEnumAnnotation< std::string, CData::Property > CData::PropertyName static
Referenced by CUndoData::addProperty(), addProperty(), getProperty(), CUndoData::isChangedProperty(), CUndoData::isSetProperty(), isSetProperty(), CUndoData::removeProperty(), and removeProperty().
The documentation for this class was generated from the following files:
CData.h
CData.cpp