COPASI API: CMethodFactory Class Reference
CMethodFactory Class Reference
#include <CMethodFactory.h>
Static Public Member Functions
static CCopasiMethod * copy (const CCopasiMethod *pSrc, const CDataContainer *pParent)
static CCopasiMethod * create (const CTaskEnum::Task &taskType, const CTaskEnum::Method &methodType, const CDataContainer *pParent)
Member Function Documentation
copy()
CCopasiMethod * CMethodFactory::copy (const CCopasiMethod * pSrc, const CDataContainer * pParent) static
Copy a COPASI method
Parameters
const const CCopasiMethod * pSrc
const CDataContainer * pParent
References CTaskEnum::adaptiveSA, CTaskEnum::CoranaWalk, CTaskEnum::crossSectionMethod, CTaskEnum::deterministic, CTaskEnum::DifferentialEvolution, CTaskEnum::directMethod, CTaskEnum::DsaLsodar, CTaskEnum::EFMAlgorithm, CTaskEnum::EFMBitPatternAlgorithm, CTaskEnum::EFMBitPatternTreeAlgorithm, CTaskEnum::EvolutionaryProgram, CTaskEnum::GeneticAlgorithm, CTaskEnum::GeneticAlgorithmSR, CCopasiTask::getMathContainer(), CDataObject::getObjectParent(), CCopasiMethod::getSubType(), CTaskEnum::HookeJeeves, CTaskEnum::Householder, CTaskEnum::hybrid, CTaskEnum::hybridLSODA, CTaskEnum::hybridODE45, CTaskEnum::LevenbergMarquardt, CTaskEnum::linearNoiseApproximation, CTaskEnum::lyapWolf, CTaskEnum::mcaMethodReder, CTaskEnum::NelderMead, CTaskEnum::Newton, CTaskEnum::NL2SOL, CTaskEnum::ParticleSwarm, CTaskEnum::Praxis, CTaskEnum::RADAU5, CTaskEnum::RandomSearch, CTaskEnum::scanMethod, CTaskEnum::ScatterSearch, CTaskEnum::sensMethod, CCopasiMethod::setMathContainer(), CTaskEnum::SimulatedAnnealing, CTaskEnum::SRES, CTaskEnum::Statistics, CTaskEnum::SteepestDescent, CTaskEnum::stochastic, CTaskEnum::stochasticRunkeKuttaRI5, CTaskEnum::tauLeap, CTaskEnum::timeSensLsoda, CTaskEnum::TruncatedNewton, CTaskEnum::tssCSP, CTaskEnum::tssILDM, CTaskEnum::tssILDMModified, and CTaskEnum::UnsetMethod.
Referenced by CCopasiTask::CCopasiTask().
create()
CCopasiMethod * CMethodFactory::create (const CTaskEnum::Task & taskType, const CTaskEnum::Method & methodType, const CDataContainer * pParent) static
Create a COPASI method
Parameters
const CTaskEnum::Task & taskType
const CTaskEnum::Method & methodType
const CDataContainer * pParent
References CTaskEnum::adaptiveSA, CTaskEnum::CoranaWalk, CTaskFactory::create(), CTaskEnum::crossSectionMethod, CTaskEnum::deterministic, CTaskEnum::DifferentialEvolution, CTaskEnum::directMethod, CTaskEnum::DsaLsodar, CTaskEnum::EFMAlgorithm, CTaskEnum::EFMBitPatternAlgorithm, CTaskEnum::EFMBitPatternTreeAlgorithm, CTaskEnum::EvolutionaryProgram, CTaskEnum::GeneticAlgorithm, CTaskEnum::GeneticAlgorithmSR, CCopasiTask::getMathContainer(), CDataObject::getObjectParent(), CCopasiTask::getType(), CCopasiTask::getValidMethods(), CTaskEnum::HookeJeeves, CTaskEnum::Householder, CTaskEnum::hybrid, CTaskEnum::hybridLSODA, CTaskEnum::hybridODE45, CCopasiTask::isValidMethod(), CTaskEnum::LevenbergMarquardt, CTaskEnum::linearNoiseApproximation, CTaskEnum::lyapWolf, CTaskEnum::mcaMethodReder, CTaskEnum::NelderMead, CTaskEnum::Newton, CTaskEnum::NL2SOL, CTaskEnum::ParticleSwarm, CTaskEnum::Praxis, CTaskEnum::RADAU5, CTaskEnum::RandomSearch, CTaskEnum::scanMethod, CTaskEnum::ScatterSearch, CTaskEnum::sensMethod, CCopasiMethod::setMathContainer(), CTaskEnum::SimulatedAnnealing, CTaskEnum::SRES, CTaskEnum::Statistics, CTaskEnum::SteepestDescent, CTaskEnum::stochastic, CTaskEnum::stochasticRunkeKuttaRI5, CTaskEnum::tauLeap, CTaskEnum::timeSensLsoda, CTaskEnum::TruncatedNewton, CTaskEnum::tssCSP, CTaskEnum::tssILDM, CTaskEnum::tssILDMModified, and CTaskEnum::UnsetMethod.
Referenced by CAnalyticsTask::CAnalyticsTask(), CCrossSectionTask::CCrossSectionTask(), CEFMTask::CEFMTask(), CFitTask::CFitTask(), CLNATask::CLNATask(), CLyapTask::CLyapTask(), CMCATask::CMCATask(), CMoietiesTask::CMoietiesTask(), COptTask::COptTask(), COscillationTask::COscillationTask(), CCopasiTask::createUndoData(), CScanTask::CScanTask(), CSensTask::CSensTask(), CSteadyStateTask::CSteadyStateTask(), CTimeSensTask::CTimeSensTask(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), COptMethodSS::initialize(), CTSSAMethod::initializeParameter(), CTrajectoryTask::load(), and CCopasiTask::setMethodType().
The documentation for this class was generated from the following files:
CMethodFactory.h
CMethodFactory.cpp