COPASI API: CEvaluationParser_yacc.cpp File Reference
CEvaluationParser_yacc.cpp File Reference
#include "copasi/copasi.h"
#include "copasi/function/CEvaluationNode.h"
#include "copasi/function/CEvaluationLexer.h"
#include <limits.h>
#include <stdio.h>
Classes
union yyalloc
Macros
#define YY_(Msgid) Msgid
#define YY_ASSERT(E) ((void) (0 && (E)))
#define YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_UNUSED
#define YY_CAST(Type, Val) ((Type) (Val))
#define YY_CEVALUATIONPARSER_CEVALUATIONPARSER_TAB_HPP_INCLUDED
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_USELESS_CAST_BEGIN
#define YY_IGNORE_USELESS_CAST_END
#define YY_INITIAL_VALUE(Value) Value
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YY_NULLPTR ((void*)0)
#define YY_REDUCE_PRINT(Rule)
#define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#define YY_STACK_PRINT(Bottom, Top)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YYABORT goto yyabortlab
#define YYACCEPT goto yyacceptlab
#define YYBACKUP(Token, Value)
#define YYBISON 1
#define YYBISON_VERSION "3.5"
#define yychar CEvaluationParserchar
#define yyclearin (yychar = YYEMPTY)
#define YYCOPY(Dst, Src, Count)
#define YYCOPY_NEEDED 1
#define yydebug CEvaluationParserdebug
#define YYDEBUG 1
#define YYDPRINTF(Args)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYERRCODE 256
#define yyerrok (yyerrstatus = 0)
#define yyerror CEvaluationParsererror
#define yyerror(__str)
#define YYERROR goto yyerrorlab
#define YYERROR_VERBOSE 0
#define YYFINAL 31
#define YYFPRINTF fprintf
#define YYFREE free
#define YYINITDEPTH 200
#define YYLAST 527
#define yylval CEvaluationParserlval
#define yylval mpNode
#define YYMALLOC malloc
#define YYMAXDEPTH 10000
#define YYMAXUTOK 286
#define yynerrs CEvaluationParsernerrs
#define YYNNTS 9
#define YYNRULES 69
#define YYNSTATES 162
#define YYNTOKENS 32
#define YYPACT_NINF (-50)
#define yypact_value_is_default(Yyn) ((Yyn) == YYPACT_NINF)
#define yyparse yyparse
#define yyparse CEvaluationParserBase::yyparse
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define YYPTRDIFF_MAXIMUM LONG_MAX
#define YYPTRDIFF_T long
#define YYPULL 1
#define YYPURE 0
#define YYPUSH 0
#define YYRECOVERING() (!!yyerrstatus)
#define YYSIZE_MAXIMUM
#define YYSIZE_T unsigned
#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))
#define YYSKELETON_NAME "yacc.c"
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYSTACK_BYTES(N)
#define YYSTACK_FREE YYFREE
#define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYSTYPE CEvaluationNode *
#define YYTABLE_NINF (-54)
#define yytable_value_is_error(Yyn) 0
#define YYTERROR 1
#define YYTOKENTYPE
#define YYTRANSLATE(YYX) (0 <= (YYX) && (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYUNDEFTOK 2
#define YYUSE(E) ((void) (E))
Typedefs
typedef int yy_state_fast_t
typedef yytype_uint8 yy_state_t
typedef short yytype_int16
typedef signed char yytype_int8
typedef unsigned short yytype_uint16
typedef unsigned char yytype_uint8
Enumerations
enum yytokentype {
TOKEN_NUMBER = 258 , TOKEN_VARIABLE = 259 , TOKEN_UNIT = 260 , TOKEN_CALL = 261 ,
TOKEN_FUNCTION = 262 , TOKEN_FUNCTION_2 = 263 , TOKEN_SIGN = 264 , TOKEN_OPERATOR_POWER = 265 ,
TOKEN_OPERATOR_MULTIPLY = 266 , TOKEN_OPERATOR_MODULUS = 267 , TOKEN_OPERATOR_REMAINDER = 268 , TOKEN_OPERATOR_PLUS = 269 ,
TOKEN_LOGICAL_CHOICE = 270 , TOKEN_LOGICAL_VALUE = 271 , TOKEN_LOGICAL_NOT = 272 , TOKEN_LOGICAL_OR = 273 ,
TOKEN_LOGICAL_XOR = 274 , TOKEN_LOGICAL_AND = 275 , TOKEN_LOGICAL_EQ = 276 , TOKEN_LOGICAL_NE = 277 ,
TOKEN_LOGICAL_GT = 278 , TOKEN_LOGICAL_GE = 279 , TOKEN_LOGICAL_LT = 280 , TOKEN_LOGICAL_LE = 281 ,
TOKEN_STRUCTURE_OPEN = 282 , TOKEN_STRUCTURE_VECTOR_OPEN = 283 , TOKEN_STRUCTURE_COMMA = 284 , TOKEN_STRUCTURE_CLOSE = 285 ,
TOKEN_STRUCTURE_VECTOR_CLOSE = 286 , TOKEN_NUMBER = 258 , TOKEN_MULTIPLY = 259 , TOKEN_PLUS = 260 ,
TOKEN_NAME = 261 , TOKEN_BEGIN_PRODUCTS = 262 , TOKEN_BEGIN_MODIFIERS = 263 , TOKEN_BEGIN_COMPARTMENT = 264 ,
TOKEN_END_COMPARTMENT = 265 , SCALE = 258 , KIND = 259 , SI_UNIT = 260 ,
USER_DEFINED_UNIT = 261 , NUMBER = 262 , POWER_OF_TEN = 263 , MULTIPLY = 264 ,
DIVIDE = 265 , START_PARENS = 266 , END_PARENS = 267 , EXPONENT = 268 ,
SUPERSCRIPT_2 = 269 , SUPERSCRIPT_3 = 270
}
Functions
void free (void *)
void * malloc (unsigned)
Variables
int CEvaluationParserchar
int CEvaluationParserdebug = 1
CEvaluationNode * CEvaluationParserlval
int CEvaluationParsernerrs
CEvaluationNode * mpNode
Macro Definition Documentation
YY_
#define YY_ (Msgid) Msgid
YY_ASSERT
#define YY_ASSERT (E) ((void) (0 && (E)))
YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_PURE
YY_ATTRIBUTE_UNUSED
#define YY_ATTRIBUTE_UNUSED
YY_CAST
#define YY_CAST (Type, Val) ((Type) (Val))
YY_CEVALUATIONPARSER_CEVALUATIONPARSER_TAB_HPP_INCLUDED
#define YY_CEVALUATIONPARSER_CEVALUATIONPARSER_TAB_HPP_INCLUDED
YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
YY_IGNORE_USELESS_CAST_BEGIN
#define YY_IGNORE_USELESS_CAST_BEGIN
YY_IGNORE_USELESS_CAST_END
#define YY_IGNORE_USELESS_CAST_END
YY_INITIAL_VALUE
#define YY_INITIAL_VALUE (Value) Value
YY_LOCATION_PRINT
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
YY_NULLPTR
#define YY_NULLPTR ((void*)0)
YY_REDUCE_PRINT
#define YY_REDUCE_PRINT (Rule)
Value:
  do {\
      if (yydebug)                          \
        yy_reduce_print (yyssp, yyvsp, Rule); \
    } while (0)
YY_REINTERPRET_CAST
#define YY_REINTERPRET_CAST (Type, Val) ((Type) (Val))
YY_STACK_PRINT
#define YY_STACK_PRINT (Bottom, Top)
Value:
  do {\
      if (yydebug)                                                  \
        yy_stack_print ((Bottom), (Top));                           \
    } while (0)
YY_SYMBOL_PRINT
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Value:
  do {\
      if (yydebug)                                                            \
        {\
          YYFPRINTF (stderr, "%s ", Title);                                   \
          yy_symbol_print (stderr,                                            \
                           Type, Value); \
          YYFPRINTF (stderr, "\n");                                           \
        }                                                                     \
    } while (0)
YYABORT
#define YYABORT goto yyabortlab
YYACCEPT
#define YYACCEPT goto yyacceptlab
YYBACKUP
#define YYBACKUP (Token, Value)
Value:
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {\
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {\
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)
YYBISON
#define YYBISON 1
YYBISON_VERSION
#define YYBISON_VERSION "3.5"
yychar
#define yychar CEvaluationParserchar
yyclearin
#define yyclearin (yychar = YYEMPTY)
YYCOPY
#define YYCOPY (Dst, Src, Count)
Value:
  do                                        \
    {\
      YYPTRDIFF_T yyi;                      \
      for (yyi = 0; yyi < (Count); yyi++)   \
        (Dst)[yyi] = (Src)[yyi];            \
    }                                       \
  while (0)
YYCOPY_NEEDED
#define YYCOPY_NEEDED 1
yydebug
#define yydebug CEvaluationParserdebug
YYDEBUG
#define YYDEBUG 1
YYDPRINTF
#define YYDPRINTF (Args)
Value:
  do {\
      if (yydebug)                                  \
        YYFPRINTF Args;                             \
    } while (0)
YYEMPTY
#define YYEMPTY (-2)
YYEOF
#define YYEOF 0
YYERRCODE
#define YYERRCODE 256
yyerrok
#define yyerrok (yyerrstatus = 0)
yyerror [1/2]
#define yyerror CEvaluationParsererror
yyerror [2/2]
#define yyerror (__str)
Value:
  if (yychar != YYERRCODE) correctErrorPosition(); \
  CCopasiMessage(CCopasiMessage::ERROR, MCFunction + 1, mPosition)
YYERROR
#define YYERROR goto yyerrorlab
YYERROR_VERBOSE
#define YYERROR_VERBOSE 0
YYFINAL
#define YYFINAL 31
YYFPRINTF
#define YYFPRINTF fprintf
YYFREE
#define YYFREE free
YYINITDEPTH
#define YYINITDEPTH 200
YYLAST
#define YYLAST 527
yylval [1/2]
#define yylval CEvaluationParserlval
yylval [2/2]
#define yylval mpNode
YYMALLOC
#define YYMALLOC malloc
YYMAXDEPTH
#define YYMAXDEPTH 10000
YYMAXUTOK
#define YYMAXUTOK 286
yynerrs
#define yynerrs CEvaluationParsernerrs
YYNNTS
#define YYNNTS 9
YYNRULES
#define YYNRULES 69
YYNSTATES
#define YYNSTATES 162
YYNTOKENS
#define YYNTOKENS 32
YYPACT_NINF
#define YYPACT_NINF (-50)
yypact_value_is_default
#define yypact_value_is_default (Yyn) ((Yyn) == YYPACT_NINF)
yyparse [1/2]
#define yyparse yyparse
yyparse [2/2]
#define yyparse CEvaluationParserBase::yyparse
YYPOPSTACK
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
YYPTRDIFF_MAXIMUM
#define YYPTRDIFF_MAXIMUM LONG_MAX
YYPTRDIFF_T
#define YYPTRDIFF_T long
YYPULL
#define YYPULL 1
YYPURE
#define YYPURE 0
YYPUSH
#define YYPUSH 0
YYRECOVERING
#define YYRECOVERING () (!!yyerrstatus)
YYSIZE_MAXIMUM
#define YYSIZE_MAXIMUM
Value:
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))
YYSIZE_T
#define YYSIZE_T unsigned
YYSIZEOF
#define YYSIZEOF (X) YY_CAST (YYPTRDIFF_T, sizeof (X))
YYSKELETON_NAME
#define YYSKELETON_NAME "yacc.c"
YYSTACK_ALLOC
#define YYSTACK_ALLOC YYMALLOC
YYSTACK_ALLOC_MAXIMUM
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
YYSTACK_BYTES
#define YYSTACK_BYTES (N)
Value:
  ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
   + YYSTACK_GAP_MAXIMUM)
YYSTACK_FREE
#define YYSTACK_FREE YYFREE
YYSTACK_GAP_MAXIMUM
#define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)
YYSTACK_RELOCATE
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
  do                                                                  \
    {\
      YYPTRDIFF_T yynewbytes;                                         \
      YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
      Stack = &yyptr->Stack_alloc;                                    \
      yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
      yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
    }                                                                 \
  while (0)
YYSTYPE
#define YYSTYPE CEvaluationNode *
YYTABLE_NINF
#define YYTABLE_NINF (-54)
yytable_value_is_error
#define yytable_value_is_error (Yyn) 0
YYTERROR
#define YYTERROR 1
YYTOKENTYPE
#define YYTOKENTYPE
YYTRANSLATE
#define YYTRANSLATE (YYX) (0 <= (YYX) && (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
YYUNDEFTOK
#define YYUNDEFTOK 2
YYUSE
#define YYUSE (E) ((void) (E))
Typedef Documentation
yy_state_fast_t
typedef int yy_state_fast_t
yy_state_t
typedef yytype_uint8 yy_state_t
yytype_int16
typedef short yytype_int16
yytype_int8
typedef signed char yytype_int8
yytype_uint16
typedef unsigned short yytype_uint16
yytype_uint8
typedef unsigned char yytype_uint8
Enumeration Type Documentation
yytokentype
enum yytokentype
Enumerator
TOKEN_NUMBER
TOKEN_VARIABLE
TOKEN_UNIT
TOKEN_CALL
TOKEN_FUNCTION
TOKEN_FUNCTION_2
TOKEN_SIGN
TOKEN_OPERATOR_POWER
TOKEN_OPERATOR_MULTIPLY
TOKEN_OPERATOR_MODULUS
TOKEN_OPERATOR_REMAINDER
TOKEN_OPERATOR_PLUS
TOKEN_LOGICAL_CHOICE
TOKEN_LOGICAL_VALUE
TOKEN_LOGICAL_NOT
TOKEN_LOGICAL_OR
TOKEN_LOGICAL_XOR
TOKEN_LOGICAL_AND
TOKEN_LOGICAL_EQ
TOKEN_LOGICAL_NE
TOKEN_LOGICAL_GT
TOKEN_LOGICAL_GE
TOKEN_LOGICAL_LT
TOKEN_LOGICAL_LE
TOKEN_STRUCTURE_OPEN
TOKEN_STRUCTURE_VECTOR_OPEN
TOKEN_STRUCTURE_COMMA
TOKEN_STRUCTURE_CLOSE
TOKEN_STRUCTURE_VECTOR_CLOSE
TOKEN_NUMBER
TOKEN_MULTIPLY
TOKEN_PLUS
TOKEN_NAME
TOKEN_BEGIN_PRODUCTS
TOKEN_BEGIN_MODIFIERS
TOKEN_BEGIN_COMPARTMENT
TOKEN_END_COMPARTMENT
SCALE
KIND
SI_UNIT
USER_DEFINED_UNIT
NUMBER
POWER_OF_TEN
MULTIPLY
DIVIDE
START_PARENS
END_PARENS
EXPONENT
SUPERSCRIPT_2
SUPERSCRIPT_3
Function Documentation
free()
void free (void *)
Referenced by CChemEqParserfree(), CEvaluationfree(), CUnitParserfree(), ensureAllArgsAreBeingUsedInFunctionDefinition(), CLocaleString::fromUtf8(), COptions::getPWD(), COptions::init(), CLocaleString::operator=(), CLocaleString::toUtf8(), CRDFWriter::xmlFromGraph(), and CLocaleString::~CLocaleString().
malloc()
void* malloc (unsigned)
Referenced by CChemEqParseralloc(), CEvaluationalloc(), and CUnitParseralloc().
Variable Documentation
CEvaluationParserchar
int CEvaluationParserchar
CEvaluationParserdebug
int CEvaluationParserdebug = 1
CEvaluationParserlval
CEvaluationNode* CEvaluationParserlval extern
CEvaluationParsernerrs
int CEvaluationParsernerrs
mpNode
CEvaluationNode* mpNode