COPASI API: CEvaluationNodeFunction Class Reference
CEvaluationNodeFunction Class Reference
#include <CEvaluationNodeFunction.h>
Public Member Functions
virtual void calculate () override
CEvaluationNodeFunction (const CEvaluationNodeFunction &src)
CEvaluationNodeFunction (const SubType &subType, const Data &data)
virtual CIssue compile () override
virtual std::string getBerkeleyMadonnaString (const std::vector< std::string > &children) const override
virtual std::string getCCodeString (const std::vector< std::string > &children) const override
virtual std::string getDisplayString (const std::vector< std::string > &children) const override
virtual std::string getInfix (const std::vector< std::string > &children) const override
CEvaluationNode * getLeft ()
const CEvaluationNode * getLeft () const
virtual std::string getMMLString (const std::vector< std::string > &children, bool expand, const std::vector< std::vector< std::string > > &variables) const override
virtual CValidatedUnit getUnit (const CMathContainer &container, const std::vector< CValidatedUnit > &units) const override
virtual std::string getXPPString (const std::vector< std::string > &children) const override
std::string handleNot (const std::string &str) const
std::string handleSign (const std::string &str) const
virtual CValidatedUnit setUnit (const CMathContainer &container, const std::map< CEvaluationNode *, CValidatedUnit > &currentUnits, std::map< CEvaluationNode *, CValidatedUnit > &targetUnits) const override
virtual CEvaluationNode * simplifyNode (const std::vector< CEvaluationNode * > &children) const override
virtual ASTNode * toAST (const CDataModel *pDataModel) const override
virtual ~CEvaluationNodeFunction ()
Public Member Functions inherited from CEvaluationNode
void addChildren (const std::vector< CEvaluationNode * > &children)
std::string buildBerkeleyMadonnaString () const
std::string buildCCodeString () const
std::string buildDisplayString () const
std::string buildInfix () const
std::string buildMMLString (bool expand, const std::vector< std::vector< std::string > > &variables) const
std::string buildXPPString () const
CEvaluationNode ()
CEvaluationNode (const CEvaluationNode &src)
CEvaluationNode * copyBranch () const
CEvaluationNode * copyNode (CEvaluationNode *child1, CEvaluationNode *child2) const
CEvaluationNode * copyNode (const std::vector< CEvaluationNode * > &children) const
const CEvaluationNode * findTopMinus (const std::vector< CFunctionAnalyzer::CValue > &callParameters) const
const CEvaluationTree * getTree () const
const C_FLOAT64 * getValuePointer () const
const ValueType & getValueType () const
virtual bool isBoolean () const
const MainType & mainType () const
bool operator!= (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &rhs)
bool operator< (const CEvaluationNode &right) const
bool operator== (const CEvaluationNode &right) const
void printRecursively () const
void printRecursively (std::ostream &os, int indent=0) const
void setTree (const CEvaluationTree *pTree)
virtual CIssue setValueType (const ValueType &valueType)
CEvaluationNode * splitBranch (const CEvaluationNode *splitnode, bool left) const
const SubType & subType () const
virtual ~CEvaluationNode ()
Public Member Functions inherited from CCopasiNode< std::string >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual Data & getData ()
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Static Public Member Functions
static C_FLOAT64 acoth (C_FLOAT64 value)
static C_FLOAT64 acsch (C_FLOAT64 value)
static C_FLOAT64 arccot (C_FLOAT64 value)
static C_FLOAT64 arccsc (C_FLOAT64 value)
static C_FLOAT64 arcsec (C_FLOAT64 value)
static C_FLOAT64 asech (C_FLOAT64 value)
static C_FLOAT64 copasiNot (C_FLOAT64 value)
static C_FLOAT64 cot (C_FLOAT64 value)
static C_FLOAT64 coth (C_FLOAT64 value)
static C_FLOAT64 csc (C_FLOAT64 value)
static C_FLOAT64 csch (C_FLOAT64 value)
static C_FLOAT64 factorial (C_FLOAT64 value)
static CEvaluationNode * fromAST (const ASTNode *pASTNode, const std::vector< CEvaluationNode * > &children)
static C_FLOAT64 max (C_FLOAT64 x1, C_FLOAT64 x2)
static C_FLOAT64 min (C_FLOAT64 x1, C_FLOAT64 x2)
static C_FLOAT64 minus (C_FLOAT64 value)
static C_FLOAT64 plus (C_FLOAT64 value)
static C_FLOAT64 rgamma (C_FLOAT64 shape, C_FLOAT64 scale)
static C_FLOAT64 rnormal (C_FLOAT64 mean, C_FLOAT64 sd)
static C_FLOAT64 rpoisson (C_FLOAT64 mu)
static C_FLOAT64 runiform (C_FLOAT64 lowerBound, C_FLOAT64 upperBound)
static C_FLOAT64 sec (C_FLOAT64 value)
static C_FLOAT64 sech (C_FLOAT64 value)
static C_FLOAT64 sign (C_FLOAT64 value)
Static Public Member Functions inherited from CEvaluationNode
static CEvaluationNode * create (const MainType &mainType, const SubType &subType, const std::string &data)
static bool isKeyword (const std::string &str)
Private Member Functions
CEvaluationNodeFunction ()
Private Attributes
CEvaluationNode * mpArgNode1
CEvaluationNode * mpArgNode2
CEvaluationNode * mpArgNode3
CEvaluationNode * mpArgNode4
const C_FLOAT64 * mpArgValue1
const C_FLOAT64 * mpArgValue2
const C_FLOAT64 * mpArgValue3
const C_FLOAT64 * mpArgValue4
C_FLOAT64(* mpFunction)(C_FLOAT64 arg1)
C_FLOAT64(* mpFunction2)(C_FLOAT64 arg1, C_FLOAT64 arg2)
C_FLOAT64(* mpFunction4)(C_FLOAT64 arg1, C_FLOAT64 arg2, C_FLOAT64 arg3, C_FLOAT64 arg4)
Static Private Attributes
static CRandom * mpRandom = NULL
Additional Inherited Members
Public Types inherited from CEvaluationNode
enum class MainType {
INVALID , NUMBER , CONSTANT , OPERATOR ,
OBJECT , FUNCTION , CALL , STRUCTURE ,
CHOICE , VARIABLE , WHITESPACE , LOGICAL ,
MV_FUNCTION , VECTOR , DELAY , UNIT ,
__SIZE
}
enum class SubType {
DEFAULT , DELAY , IF , VECTOR ,
CN , DOUBLE , FUNCTION , LOG ,
OPEN , PI , POWER , EXPRESSION ,
POINTER , EXPONENTIALE , INTEGER , LOG10 ,
MULTIPLY , OR , VECTOROPEN , COMMA ,
DIVIDE , ENOTATION , EXP , True ,
XOR , RATIONALE , AND , CLOSE ,
False , MODULUS , SIN , VECTORCLOSE ,
COS , EQ , Infinity , PLUS ,
NaN , MINUS , NE , TAN ,
REMAINDER , GT , SEC , CSC ,
GE , COT , LT , LE ,
SINH , COSH , TANH , SECH ,
CSCH , COTH , ARCSIN , ARCCOS ,
ARCTAN , ARCSEC , ARCCSC , ARCCOT ,
ARCSINH , ARCCOSH , ARCTANH , ARCSECH ,
ARCCSCH , ARCCOTH , SQRT , ABS ,
FLOOR , CEIL , FACTORIAL , NOT ,
RUNIFORM , RNORMAL , MAX , MIN ,
RGAMMA , RPOISSON , SIGN , AVOGADRO ,
INVALID , __SIZE
}
enum class ValueType { Unknown , Boolean , Number , __SIZE }
Public Types inherited from CCopasiNode< std::string >
typedef std::string Data
Static Public Attributes inherited from CEvaluationNode
static const CEnumAnnotation< std::string, MainType > MainTypeName
static const CEnumAnnotation< std::string, SubType > SubTypeName
Protected Member Functions inherited from CEvaluationNode
CEvaluationNode (const MainType &type, const SubType &subType, const Data &data)
Protected Member Functions inherited from CCopasiNode< std::string >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CEvaluationNode
MainType mMainType
class CEvaluationNode::CPrecedence mPrecedence
const CEvaluationTree * mpTree
const C_FLOAT64 * mpValue
SubType mSubType
C_FLOAT64 mValue
ValueType mValueType
Protected Attributes inherited from CCopasiNode< std::string >
Data mData
Detailed Description
This is the class for nodes presenting build-in functions used in an evaluation trees.
Constructor & Destructor Documentation
CEvaluationNodeFunction() [1/3]
CEvaluationNodeFunction::CEvaluationNodeFunction () private
Default constructor
References CEvaluationNode::mPrecedence, and PRECEDENCE_NUMBER.
Referenced by fromAST().
CEvaluationNodeFunction() [2/3]
CEvaluationNodeFunction::CEvaluationNodeFunction (const SubType & subType, const Data & data)
Default constructor
Parameters
const SubType & subType
const Data & data
References CEvaluationNode::ABS, acoth(), acsch(), CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, arccot(), CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, arccsc(), CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, arcsec(), CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, asech(), CEvaluationNode::Boolean, CEvaluationNode::CEIL, copasiNot(), CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, cot(), CEvaluationNode::COTH, coth(), CRandom::createGenerator(), CEvaluationNode::CSC, csc(), CEvaluationNode::CSCH, csch(), CEvaluationNode::EXP, CEvaluationNode::FACTORIAL, factorial(), fatalError, CEvaluationNode::FLOOR, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::MAX, max(), CEvaluationNode::MIN, min(), CEvaluationNode::MINUS, minus(), mpFunction, mpFunction2, mpRandom, CEvaluationNode::mPrecedence, CEvaluationNode::mSubType, CEvaluationNode::mValueType, CEvaluationNode::NOT, CEvaluationNode::Number, CEvaluationNode::PLUS, plus(), PRECEDENCE_FUNCTION, CEvaluationNode::RGAMMA, rgamma(), CEvaluationNode::RNORMAL, rnormal(), CEvaluationNode::RPOISSON, rpoisson(), CEvaluationNode::RUNIFORM, runiform(), CEvaluationNode::SEC, sec(), CEvaluationNode::SECH, sech(), CEvaluationNode::SIGN, sign(), CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, and CEvaluationNode::TANH.
CEvaluationNodeFunction() [3/3]
CEvaluationNodeFunction::CEvaluationNodeFunction (const CEvaluationNodeFunction & src)
Copy constructor
Parameters
const CEvaluationNodeFunction & src
~CEvaluationNodeFunction()
CEvaluationNodeFunction::~CEvaluationNodeFunction () virtual
Destructor
Member Function Documentation
acoth()
static C_FLOAT64 CEvaluationNodeFunction::acoth (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
acsch()
static C_FLOAT64 CEvaluationNodeFunction::acsch (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
arccot()
static C_FLOAT64 CEvaluationNodeFunction::arccot (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
arccsc()
static C_FLOAT64 CEvaluationNodeFunction::arccsc (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
arcsec()
static C_FLOAT64 CEvaluationNodeFunction::arcsec (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
asech()
static C_FLOAT64 CEvaluationNodeFunction::asech (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
calculate()
virtual void CEvaluationNodeFunction::calculate (void) inline override virtual
Calculate the numerical result of the node. It is assumed that all child nodes are up to date.
Reimplemented from CEvaluationNode.
References mpArgValue1, mpArgValue2, mpArgValue3, mpArgValue4, mpFunction, mpFunction2, mpFunction4, and CEvaluationNode::mValue.
compile()
CIssue CEvaluationNodeFunction::compile () override virtual
Compile a node;
Parameters
const CEvaluationTree * pTree
Returns
CIssue issue;
Reimplemented from CEvaluationNode.
References CIssue::Error, CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getValuePointer(), mpArgNode1, mpArgNode2, mpArgNode3, mpArgNode4, mpArgValue1, mpArgValue2, mpArgValue3, mpArgValue4, mpFunction, mpFunction2, CEvaluationNode::mValueType, CEvaluationNode::setValueType(), CIssue::Success, CIssue::TooManyArguments, and CIssue::VariableNotfound.
Referenced by getBerkeleyMadonnaString(), getCCodeString(), getDisplayString(), getInfix(), and getXPPString().
copasiNot()
static C_FLOAT64 CEvaluationNodeFunction::copasiNot (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
cot()
static C_FLOAT64 CEvaluationNodeFunction::cot (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
coth()
static C_FLOAT64 CEvaluationNodeFunction::coth (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
csc()
static C_FLOAT64 CEvaluationNodeFunction::csc (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
csch()
static C_FLOAT64 CEvaluationNodeFunction::csch (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
factorial()
static C_FLOAT64 CEvaluationNodeFunction::factorial (C_FLOAT64 value) inline static
References C_FLOAT64.
Referenced by CEvaluationNodeFunction().
fromAST()
CEvaluationNode * CEvaluationNodeFunction::fromAST (const ASTNode * pASTNode, const std::vector< CEvaluationNode * > & children) static
Creates a new CEvaluationNodeCall from an ASTNode and the given children
Parameters
const ASTNode* pNode
const std::vector< CEvaluationNode * > & children
Returns
CEvaluationNode * pCretedNode
Replaces all root nodes with the corresponding power operator since COPASI does not have the ROOT function.
Replaces all LOG10 (AST_FUNCTION_LOG) nodes that have two children and the base is not 10 with the quotient of two LOG10 nodes with the base as the argument for the divisor LOG10 node.
References CEvaluationNode::ABS, CCopasiNode< _Data >::addChild(), CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, SBMLImporter::areApproximatelyEqual(), CEvaluationNode::CEIL, CEvaluationNodeFunction(), CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CEvaluationNode::DIVIDE, CEvaluationNode::DOUBLE, CEvaluationNode::EXP, CEvaluationNode::FACTORIAL, fatalError, CEvaluationNode::FLOOR, CEvaluationNode::getValuePointer(), CEvaluationNode::INVALID, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::mainType(), CEvaluationNode::NOT, CEvaluationNode::NUMBER, CEvaluationNode::POWER, CEvaluationNode::SEC, CEvaluationNode::SECH, CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, and CEvaluationNode::TANH.
Referenced by CEvaluationTree::fromAST().
getBerkeleyMadonnaString()
std::string CEvaluationNodeFunction::getBerkeleyMadonnaString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes in Berkeley Madonna format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CEvaluationNode::ABS, CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, CEvaluationNode::CEIL, compile(), CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CEvaluationNode::EXP, CEvaluationNode::FACTORIAL, CEvaluationNode::FLOOR, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::MAX, CCopasiNode< std::string >::mData, CEvaluationNode::MIN, CEvaluationNode::MINUS, CEvaluationNode::mSubType, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, CEvaluationNode::RUNIFORM, CEvaluationNode::SEC, CEvaluationNode::SECH, CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, and CEvaluationNode::TANH.
getCCodeString()
std::string CEvaluationNodeFunction::getCCodeString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes in C.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CEvaluationNode::ABS, CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, CEvaluationNode::CEIL, compile(), CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CEvaluationNode::EXP, CEvaluationNode::FACTORIAL, CEvaluationNode::FLOOR, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::MAX, CEvaluationNode::MIN, CEvaluationNode::MINUS, CEvaluationNode::mSubType, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, CEvaluationNode::RUNIFORM, CEvaluationNode::SEC, CEvaluationNode::SECH, CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, and CEvaluationNode::TANH.
getDisplayString()
std::string CEvaluationNodeFunction::getDisplayString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References compile(), handleNot(), handleSign(), CEvaluationNode::MAX, CCopasiNode< std::string >::mData, CEvaluationNode::MIN, CEvaluationNode::MINUS, CEvaluationNode::mSubType, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, and CEvaluationNode::RUNIFORM.
getInfix()
std::string CEvaluationNodeFunction::getInfix (const std::vector< std::string > & children) const override virtual
Retrieve the infix value of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References compile(), handleNot(), handleSign(), CEvaluationNode::MAX, CCopasiNode< std::string >::mData, CEvaluationNode::MIN, CEvaluationNode::MINUS, CEvaluationNode::mSubType, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, and CEvaluationNode::RUNIFORM.
getLeft() [1/2]
CEvaluationNode * CEvaluationNodeFunction::getLeft ()
References mpArgNode1.
getLeft() [2/2]
const CEvaluationNode * CEvaluationNodeFunction::getLeft () const
References mpArgNode1.
getMMLString()
std::string CEvaluationNodeFunction::getMMLString (const std::vector< std::string > & children, bool expand, const std::vector< std::vector< std::string > > & variables) const override virtual
Build the MathML string
Parameters
const std::vector< std::string > & children
bool expand = true
const std::vector< std::vector< std::string > > & variables
Returns
std::string MMLString
Reimplemented from CEvaluationNode.
References CEvaluationNode::ABS, CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, CEvaluationNode::CALL, CEvaluationNode::CEIL, CEvaluationNode::CONSTANT, CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CEvaluationNode::EXP, CEvaluationNode::FACTORIAL, CEvaluationNode::FLOOR, CCopasiNode< _Data >::getChild(), CCopasiNode< std::string >::getParent(), CEvaluationNode::INVALID, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::mainType(), CEvaluationNode::MAX, CCopasiNode< std::string >::mData, CEvaluationNode::MIN, CEvaluationNode::MINUS, mpArgNode1, CEvaluationNode::mSubType, CEvaluationNode::NOT, CEvaluationNode::NUMBER, CEvaluationNode::OPERATOR, CEvaluationNode::PLUS, CEvaluationNode::POWER, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, CEvaluationNode::RUNIFORM, CEvaluationNode::SEC, CEvaluationNode::SECH, CEvaluationNode::SIGN, CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, CEvaluationNode::TANH, and CEvaluationNode::VARIABLE.
getUnit()
CValidatedUnit CEvaluationNodeFunction::getUnit (const CMathContainer & container, const std::vector< CValidatedUnit > & units) const override virtual
Figure out the appropriate CUnit to use, based on the child nodes. This sets the default, appropriate for many cases, as Dimensionless
Parameters
const CMathContainer & container
const std::vector< CValidatedUnit > & units
Returns
CValidatedUnit unit
Reimplemented from CEvaluationNode.
References CEvaluationNode::ABS, CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, CEvaluationNode::CEIL, CValidatedUnit::conflict(), CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CBaseUnit::dimensionless, CEvaluationNode::EXP, CValidatedUnit::exponentiate(), CEvaluationNode::FACTORIAL, CEvaluationNode::FLOOR, CUnit::getComponents(), CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::MAX, CValidatedUnit::merge(), CEvaluationNode::MIN, CEvaluationNode::MINUS, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, CEvaluationNode::RUNIFORM, CEvaluationNode::SEC, CEvaluationNode::SECH, CValidatedUnit::setConflict(), CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, CEvaluationNode::TANH, and CBaseUnit::undefined.
getXPPString()
std::string CEvaluationNodeFunction::getXPPString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes in XPPAUT format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CEvaluationNode::ABS, CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, CEvaluationNode::CEIL, compile(), CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CEvaluationNode::EXP, CEvaluationNode::FACTORIAL, CEvaluationNode::FLOOR, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::MAX, CCopasiNode< std::string >::mData, CEvaluationNode::MIN, CEvaluationNode::MINUS, CEvaluationNode::mSubType, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, CEvaluationNode::RUNIFORM, CEvaluationNode::SEC, CEvaluationNode::SECH, CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, and CEvaluationNode::TANH.
handleNot()
std::string CEvaluationNodeFunction::handleNot (const std::string & str) const
References CEvaluationNode::LOGICAL, CEvaluationNode::mainType(), CCopasiNode< std::string >::mData, and mpArgNode1.
Referenced by getDisplayString(), and getInfix().
handleSign()
std::string CEvaluationNodeFunction::handleSign (const std::string & str) const
References CCopasiNode< std::string >::getParent(), CEvaluationNode::mainType(), CCopasiNode< std::string >::mData, mpArgNode1, CEvaluationNode::OPERATOR, CEvaluationNode::POWER, and CEvaluationNode::subType().
Referenced by getDisplayString(), and getInfix().
max()
C_FLOAT64 CEvaluationNodeFunction::max (C_FLOAT64 x1, C_FLOAT64 x2) static
References max.
Referenced by CEvaluationNodeFunction().
min()
C_FLOAT64 CEvaluationNodeFunction::min (C_FLOAT64 x1, C_FLOAT64 x2) static
References min.
Referenced by CEvaluationNodeFunction().
minus()
static C_FLOAT64 CEvaluationNodeFunction::minus (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
plus()
static C_FLOAT64 CEvaluationNodeFunction::plus (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
rgamma()
C_FLOAT64 CEvaluationNodeFunction::rgamma (C_FLOAT64 shape, C_FLOAT64 scale) static
References CRandom::getRandomGamma(), and mpRandom.
Referenced by CEvaluationNodeFunction().
rnormal()
C_FLOAT64 CEvaluationNodeFunction::rnormal (C_FLOAT64 mean, C_FLOAT64 sd) static
References CRandom::getRandomNormal(), and mpRandom.
Referenced by CEvaluationNodeFunction().
rpoisson()
C_FLOAT64 CEvaluationNodeFunction::rpoisson (C_FLOAT64 mu) static
References CRandom::getRandomPoisson(), and mpRandom.
Referenced by CEvaluationNodeFunction().
runiform()
C_FLOAT64 CEvaluationNodeFunction::runiform (C_FLOAT64 lowerBound, C_FLOAT64 upperBound) static
References CRandom::getRandomOO(), and mpRandom.
Referenced by CEvaluationNodeFunction().
sec()
static C_FLOAT64 CEvaluationNodeFunction::sec (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
sech()
static C_FLOAT64 CEvaluationNodeFunction::sech (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
setUnit()
CValidatedUnit CEvaluationNodeFunction::setUnit (const CMathContainer & container, const std::map< CEvaluationNode *, CValidatedUnit > & currentUnits, std::map< CEvaluationNode *, CValidatedUnit > & targetUnits) const override virtual
Set the unit for the node and return the resulting unit. The child node units are added to the map
Parameters
const CMathContainer & container
const std::map < CEvaluationNode * , CValidatedUnit > & currentUnits
std::map < CEvaluationNode * , CValidatedUnit > & targetUnits
Returns
CValidatedUnit unit
Reimplemented from CEvaluationNode.
References CEvaluationNode::ABS, CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, CEvaluationNode::CEIL, CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CBaseUnit::dimensionless, CEvaluationNode::EXP, CValidatedUnit::exponentiate(), CEvaluationNode::FACTORIAL, CEvaluationNode::FLOOR, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::MAX, CEvaluationNode::MIN, CEvaluationNode::MINUS, mpArgNode1, mpArgNode2, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, CEvaluationNode::RUNIFORM, CEvaluationNode::SEC, CEvaluationNode::SECH, CValidatedUnit::setConflict(), CEvaluationNode::setUnit(), CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, and CEvaluationNode::TANH.
sign()
static C_FLOAT64 CEvaluationNodeFunction::sign (C_FLOAT64 value) inline static
Referenced by CEvaluationNodeFunction().
simplifyNode()
CEvaluationNode * CEvaluationNodeFunction::simplifyNode (const std::vector< CEvaluationNode * > & children) const override virtual
Create a simplified node for an operatorNode with children from vector (if not exist, = NULL), and assign new children
Returns
CEvaluationNode* return a pointer to the simplified node;
Reimplemented from CEvaluationNode.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::copyBranch(), CEvaluationNode::copyNode(), CEvaluationNode::create(), CEvaluationNode::DIVIDE, CEvaluationNode::DOUBLE, CEvaluationNode::FUNCTION, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CEvaluationNode::getValuePointer(), CEvaluationNode::mainType(), CEvaluationNode::MINUS, CEvaluationNode::mSubType, CEvaluationNode::NUMBER, CEvaluationNode::OPERATOR, CEvaluationNode::PLUS, CEvaluationNode::POWER, CEvaluationNode::SQRT, and CEvaluationNode::subType().
toAST()
ASTNode * CEvaluationNodeFunction::toAST (const CDataModel * pDataModel) const override virtual
Create a new ASTNode corresponding to this FunctionNode.
Returns
ASTNode* return a pointer to the newly created node;
Reimplemented from CEvaluationNode.
References CEvaluationNode::ABS, CCopasiNode< _Data >::addChild(), CEvaluationNode::ARCCOS, CEvaluationNode::ARCCOSH, CEvaluationNode::ARCCOT, CEvaluationNode::ARCCOTH, CEvaluationNode::ARCCSC, CEvaluationNode::ARCCSCH, CEvaluationNode::ARCSEC, CEvaluationNode::ARCSECH, CEvaluationNode::ARCSIN, CEvaluationNode::ARCSINH, CEvaluationNode::ARCTAN, CEvaluationNode::ARCTANH, CEvaluationNode::CEIL, CEvaluationNode::COS, CEvaluationNode::COSH, CEvaluationNode::COT, CEvaluationNode::COTH, CEvaluationNode::CSC, CEvaluationNode::CSCH, CEvaluationNode::EXP, CEvaluationNode::FACTORIAL, CEvaluationNode::FLOOR, CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::INVALID, CEvaluationNode::LOG, CEvaluationNode::LOG10, CEvaluationNode::MAX, CEvaluationNode::MIN, CEvaluationNode::MINUS, CEvaluationNode::NOT, CEvaluationNode::PLUS, CEvaluationNode::RGAMMA, CEvaluationNode::RNORMAL, CEvaluationNode::RPOISSON, CEvaluationNode::RUNIFORM, CEvaluationNode::SEC, CEvaluationNode::SECH, CEvaluationNode::SIN, CEvaluationNode::SINH, CEvaluationNode::SQRT, CEvaluationNode::subType(), CEvaluationNode::TAN, CEvaluationNode::TANH, and CEvaluationNode::toAST().
Member Data Documentation
mpArgNode1
CEvaluationNode* CEvaluationNodeFunction::mpArgNode1 private
Referenced by compile(), getLeft(), getMMLString(), handleNot(), handleSign(), and setUnit().
mpArgNode2
CEvaluationNode* CEvaluationNodeFunction::mpArgNode2 private
Referenced by compile(), and setUnit().
mpArgNode3
CEvaluationNode* CEvaluationNodeFunction::mpArgNode3 private
Referenced by compile().
mpArgNode4
CEvaluationNode* CEvaluationNodeFunction::mpArgNode4 private
Referenced by compile().
mpArgValue1
const C_FLOAT64* CEvaluationNodeFunction::mpArgValue1 private
Referenced by calculate(), and compile().
mpArgValue2
const C_FLOAT64* CEvaluationNodeFunction::mpArgValue2 private
Referenced by calculate(), and compile().
mpArgValue3
const C_FLOAT64* CEvaluationNodeFunction::mpArgValue3 private
Referenced by calculate(), and compile().
mpArgValue4
const C_FLOAT64* CEvaluationNodeFunction::mpArgValue4 private
Referenced by calculate(), and compile().
mpFunction
C_FLOAT64(* CEvaluationNodeFunction::mpFunction) (C_FLOAT64 arg1) private
Referenced by calculate(), CEvaluationNodeFunction(), and compile().
mpFunction2
C_FLOAT64(* CEvaluationNodeFunction::mpFunction2) (C_FLOAT64 arg1, C_FLOAT64 arg2) private
Referenced by calculate(), CEvaluationNodeFunction(), and compile().
mpFunction4
C_FLOAT64(* CEvaluationNodeFunction::mpFunction4) (C_FLOAT64 arg1, C_FLOAT64 arg2, C_FLOAT64 arg3, C_FLOAT64 arg4) private
Referenced by calculate().
mpRandom
CRandom * CEvaluationNodeFunction::mpRandom = NULL static private
Referenced by CEvaluationNodeFunction(), rgamma(), rnormal(), rpoisson(), and runiform().
The documentation for this class was generated from the following files:
CEvaluationNodeFunction.h
CEvaluationNodeFunction.cpp