COPASI API: CRadau5Method Class Reference
CRadau5Method Class Reference
#include <CRadau5Method.h>
Classes
struct Data
struct State
Public Member Functions
CRadau5Method (const CDataContainer *pParent, const CTaskEnum::Method &methodType=CTaskEnum::Method::RADAU5, const CTaskEnum::Task &taskType=CTaskEnum::Task::timeCourse)
CRadau5Method (const CRadau5Method &src, const CDataContainer *pParent)
virtual bool elevateChildren ()
virtual void evalF (const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
virtual void evalJ (const C_FLOAT64 *t, const C_FLOAT64 *y, double *ml, const C_INT *mu, C_FLOAT64 *pd, const C_INT *nRowPD)
virtual void evalR (const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *nr, C_FLOAT64 *r)
virtual void output (const double *t)
virtual void start ()
virtual void stateChange (const CMath::StateChange &change)
virtual Status step (const double &deltaT, const bool &final=false)
~CRadau5Method ()
Public Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType=CTaskEnum::Task::timeCourse)
CTrajectoryMethod (const CTrajectoryMethod &src, const CDataContainer *pParent)
const CVectorCore< C_INT > & getRoots () const
const bool & integrateReducedModel () const
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (CTrajectoryProblem *problem)
~CTrajectoryMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CDataContainer *pParent)
virtual void clearCallBack ()
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
const CTaskEnum::Method & getSubType () const
const CTaskEnum::Task & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
CCopasiMethod & operator= (const CCopasiMethod &rhs)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static void EvalF (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot, C_FLOAT64 *, C_INT *)
static void EvalJ (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, double *ml, const C_INT *mu, C_FLOAT64 *pd, const C_INT *nRowPD)
static void EvalR (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *nr, C_FLOAT64 *r)
static void solout (C_INT *nr, double *xold, double *x, double *y, double *cont, C_INT *lrc, C_INT *n, double *rpar, C_INT *ipar, C_INT *irtrn)
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Types
enum eRootMasking { NONE = 0 , ALL , DISCRETE }
Protected Member Functions
void destroyRootMask ()
Protected Member Functions inherited from CTrajectoryMethod
void output (const bool &useMoieties)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src)
CCopasiMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Static Protected Member Functions
static void EvalM (C_INT *, double *, C_INT *, double *, C_INT *)
Protected Attributes
double H
C_INT idid
C_INT IJAC
C_INT IMAS
C_INT IOUT = 0
C_INT ipar
C_INT ITOL
C_INT LIWORK
C_INT LWORK
Data mData
State mLastRootState
CVector< C_FLOAT64 > mLastSuccessState
C_INT MLJAC
C_INT MLMAS
C_INT mLsodaStatus
eRootMasking mRootMasking
C_FLOAT64 mTime
C_INT MUJAC
C_INT MUMAS
double rpar
Protected Attributes inherited from CTrajectoryMethod
CVectorCore< C_FLOAT64 > mContainerState
C_FLOAT64 * mpContainerStateTime
CTrajectoryProblem * mpProblem
const bool * mpReducedModel
CTrajectoryTask * mpTask
CVectorCore< C_INT > mRootsFound
Protected Attributes inherited from CCopasiMethod
CMathContainer * mpContainer
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CRadau5Method ()
void createRootMask ()
bool hasStateChanged (const CVectorCore< C_FLOAT64 > &startState) const
void initializeParameter ()
void maskRoots (CVectorCore< C_FLOAT64 > &rootValues)
CTrajectoryMethod::Status peekAhead ()
void resetState (State &state)
void saveState (State &state, const CTrajectoryMethod::Status &status) const
void setRootMaskType (const eRootMasking &maskType)
Private Attributes
CVector< C_FLOAT64 > mAtol
CVectorCore< bool > mDiscreteRoots
CVector< C_FLOAT64 > mDWork
std::ostringstream mErrorMsg
CVector< C_INT > mIWork
C_INT mJType
C_INT mNumRoots
C_FLOAT64 * mpAbsoluteTolerance
C_FLOAT64 * mpAtol
bool mPeekAheadMode
C_FLOAT64 * mpInitialStepSize
unsigned C_INT32 * mpMaxInternalSteps
C_FLOAT64 * mpRelativeTolerance
C_FLOAT64 * mpY
const C_FLOAT64 * mpYdot
CRadau5 mRADAU
unsigned C_INT32 mRootCounter
CVector< bool > mRootMask
CVector< C_FLOAT64 > mRtol
State mSavedState
C_FLOAT64 mTargetTime
C_INT mTask
Additional Inherited Members
Public Types inherited from CTrajectoryMethod
enum Status { FAILURE = -1 , NORMAL = 0 , ROOT = 1 }
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Static Protected Attributes inherited from CTrajectoryMethod
static const bool ReducedModel
Member Enumeration Documentation
eRootMasking
enum CRadau5Method::eRootMasking protected
Enumerator
NONE
ALL
DISCRETE
Constructor & Destructor Documentation
CRadau5Method() [1/3]
CRadau5Method::CRadau5Method () private
Constructor.
CRadau5Method() [2/3]
CRadau5Method::CRadau5Method (const CDataContainer * pParent, const CTaskEnum::Method & methodType = CTaskEnum::Method::RADAU5, const CTaskEnum::Task & taskType = CTaskEnum::Task::timeCourse)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Method & methodType (default: RADAU5)
const CTaskEnum::Task & taskType (default: timeCourse)
References CRadau5Method::Data::dim, initializeParameter(), mData, and CRadau5Method::Data::pMethod.
CRadau5Method() [3/3]
CRadau5Method::CRadau5Method (const CRadau5Method & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CRadau5Method & src
const CDataContainer * pParent (default: NULL)
References CRadau5Method::Data::dim, initializeParameter(), mData, and CRadau5Method::Data::pMethod.
~CRadau5Method()
CRadau5Method::~CRadau5Method ()
Destructor.
References CVectorCore< CType >::array(), and CTrajectoryMethod::mRootsFound.
Member Function Documentation
createRootMask()
void CRadau5Method::createRootMask () private
Create a mask which hides all roots being constant and zero.
References ALL, CVectorCore< CType >::begin(), C_FLOAT64, C_INT, CMathContainer::calculateRootDerivatives(), CVectorCore< CType >::end(), CMathContainer::getRootIsDiscrete(), CMathContainer::getRoots(), min, CCopasiMethod::mpContainer, CTrajectoryMethod::mpReducedModel, mRootMask, mRootMasking, CTrajectoryMethod::mRootsFound, CVector< CType >::resize(), CVectorCore< CType >::size(), and CMathContainer::updateRootValues().
Referenced by setRootMaskType().
destroyRootMask()
void CRadau5Method::destroyRootMask () protected
Destroy the mask which hides all roots being constant and zero.
References mRootMask, mRootMasking, and NONE.
Referenced by start().
elevateChildren()
bool CRadau5Method::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
References initializeParameter().
evalF()
void CRadau5Method::evalF (const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) virtual
References CVectorCore< CType >::array(), C_FLOAT64, CRadau5Method::Data::dim, CMathContainer::getRate(), CMathContainer::getState(), mData, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, CTrajectoryMethod::mpReducedModel, mpYdot, and CMathContainer::updateSimulatedValues().
Referenced by EvalF().
EvalF()
void CRadau5Method::EvalF (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot, C_FLOAT64 * , C_INT *) static
This evaluates the derivatives
References evalF(), and CRadau5Method::Data::pMethod.
Referenced by step().
evalJ()
void CRadau5Method::evalJ (const C_FLOAT64 * t, const C_FLOAT64 * y, double * ml, const C_INT * mu, C_FLOAT64 * pd, const C_INT * nRowPD) virtual
Referenced by EvalJ().
EvalJ()
void CRadau5Method::EvalJ (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, double * ml, const C_INT * mu, C_FLOAT64 * pd, const C_INT * nRowPD) static
This evaluates the Jacobian
References evalJ(), and CRadau5Method::Data::pMethod.
Referenced by step().
EvalM()
void CRadau5Method::EvalM (C_INT * , double * , C_INT * , double * , C_INT *) static protected
Referenced by step().
evalR()
void CRadau5Method::evalR (const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * nr, C_FLOAT64 * r) virtual
References CMathContainer::getRoots(), CMathContainer::getState(), maskRoots(), CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, CTrajectoryMethod::mpReducedModel, mRootMasking, NONE, and CMathContainer::updateRootValues().
Referenced by EvalR().
EvalR()
void CRadau5Method::EvalR (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * nr, C_FLOAT64 * r) static
This evaluates the roots
References evalR(), and CRadau5Method::Data::pMethod.
hasStateChanged()
bool CRadau5Method::hasStateChanged (const CVectorCore< C_FLOAT64 > & startState) const private
References CVectorCore< CType >::array(), C_FLOAT64, CMathContainer::getCountFixedEventTargets(), mAtol, CTrajectoryMethod::mContainerState, CCopasiMethod::mpContainer, mpRelativeTolerance, and CVectorCore< CType >::size().
Referenced by peekAhead().
initializeParameter()
void CRadau5Method::initializeParameter () private
Initialize the method parameter
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, mpAbsoluteTolerance, mpInitialStepSize, mpMaxInternalSteps, CTrajectoryMethod::mpReducedModel, mpRelativeTolerance, CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CRadau5Method(), and elevateChildren().
maskRoots()
void CRadau5Method::maskRoots (CVectorCore< C_FLOAT64 > & rootValues) private
Mask roots which are constant and zero.
Parameters
CVectorCore< C_FLOAT64 > & rootValues
References CVectorCore< CType >::array(), C_FLOAT64, mRootMask, and CVectorCore< CType >::size().
Referenced by evalR().
output()
void CRadau5Method::output (const double * t) virtual
References CTrajectoryMethod::mpContainerStateTime, CTrajectoryMethod::mpReducedModel, and CTrajectoryMethod::output().
Referenced by solout().
peekAhead()
CTrajectoryMethod::Status CRadau5Method::peekAhead () private
Peek ahead to detect simultaneous roots.
References ALL, CVectorCore< CType >::array(), C_FLOAT64, C_INT, CRadau5Method::State::ContainerState, CTrajectoryMethod::FAILURE, CMathContainer::getRoots(), hasStateChanged(), max, mLastRootState, mLsodaStatus, CCopasiMethod::mpContainer, mPeekAheadMode, mpRelativeTolerance, mRootCounter, mRootMask, CTrajectoryMethod::mRootsFound, mSavedState, mTargetTime, mTime, CTrajectoryMethod::NORMAL, resetState(), CTrajectoryMethod::ROOT, saveState(), setRootMaskType(), CVectorCore< CType >::size(), CRadau5Method::State::Status, and step().
resetState()
void CRadau5Method::resetState (CRadau5Method::State & state) private
References CRadau5Method::State::ContainerState, CRadau5Method::State::DWork, CRadau5Method::State::IWork, CRadau5Method::State::LsodaState, CTrajectoryMethod::mContainerState, mDWork, mIWork, mLsodaStatus, CTrajectoryMethod::mpContainerStateTime, mRADAU, mRootMask, mRootMasking, CTrajectoryMethod::mRootsFound, mTime, CInternalSolver::resetState(), CTrajectoryMethod::ROOT, CRadau5Method::State::RootMask, CRadau5Method::State::RootMasking, CRadau5Method::State::RootsFound, and CRadau5Method::State::Status.
Referenced by peekAhead(), and step().
saveState()
void CRadau5Method::saveState (CRadau5Method::State & state, const CTrajectoryMethod::Status & status) const private
References CRadau5Method::State::ContainerState, CRadau5Method::State::DWork, CRadau5Method::State::IWork, CRadau5Method::State::LsodaState, CTrajectoryMethod::mContainerState, mDWork, mIWork, CTrajectoryMethod::mpContainerStateTime, mRADAU, mRootMask, mRootMasking, CTrajectoryMethod::mRootsFound, mTime, CRadau5Method::State::RootMask, CRadau5Method::State::RootMasking, CRadau5Method::State::RootsFound, CInternalSolver::saveState(), and CRadau5Method::State::Status.
Referenced by peekAhead(), and start().
setRootMaskType()
void CRadau5Method::setRootMaskType (const eRootMasking & maskType) private
Set the root mask type and update the root mask accordingly
References ALL, CVectorCore< CType >::array(), CVectorCore< CType >::begin(), C_FLOAT64, createRootMask(), DISCRETE, CVectorCore< CType >::end(), CMathContainer::getRootIsDiscrete(), CMathContainer::getRoots(), mDiscreteRoots, min, mNumRoots, CCopasiMethod::mpContainer, CTrajectoryMethod::mpReducedModel, mRootMask, mRootMasking, NONE, CVector< CType >::resize(), and CMathContainer::updateRootValues().
Referenced by peekAhead(), and stateChange().
solout()
void CRadau5Method::solout (C_INT * nr, double * xold, double * x, double * y, double * cont, C_INT * lrc, C_INT * n, double * rpar, C_INT * ipar, C_INT * irtrn) static
This helps to output when automatic step size is selected
References ipar, output(), CRadau5Method::Data::pMethod, and rpar.
Referenced by step().
start()
void CRadau5Method::start () virtual
This instructs the method to prepare for integration
Reimplemented from CTrajectoryMethod.
References CVectorCore< CType >::array(), C_INT, CRadau5Method::State::ContainerState, destroyRootMask(), CRadau5Method::Data::dim, CCopasiMessage::EXCEPTION, CTrajectoryMethod::FAILURE, CTrajectoryProblem::getAutomaticStepSize(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getEvents(), CMathContainer::getRate(), CMathContainer::getRootIsDiscrete(), CMathContainer::getRoots(), H, IJAC, IMAS, CVectorCore< CType >::initialize(), CMathContainer::initializeAtolVector(), IOUT, ipar, ITOL, LIWORK, LWORK, mAtol, CTrajectoryMethod::mContainerState, MCTrajectoryMethod, mData, mDiscreteRoots, mDWork, mErrorMsg, mIWork, mJType, mLastRootState, MLJAC, MLMAS, mLsodaStatus, mNumRoots, mpAbsoluteTolerance, mpAtol, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mPeekAheadMode, mpInitialStepSize, mpMaxInternalSteps, CTrajectoryMethod::mpProblem, CTrajectoryMethod::mpReducedModel, mpRelativeTolerance, mpY, mpYdot, mRADAU, mRootCounter, CTrajectoryMethod::mRootsFound, mRtol, mSavedState, mTargetTime, mTask, mTime, MUJAC, MUMAS, CVector< CType >::resize(), CRadau5Method::State::RootsFound, rpar, saveState(), CInternalSolver::setOstream(), CVectorCore< CType >::size(), and CTrajectoryMethod::start().
stateChange()
void CRadau5Method::stateChange (const CMath::StateChange & change) virtual
Inform the trajectory method that the state has changed outside its control
Parameters
const CMath::StateChange & change
Reimplemented from CTrajectoryMethod.
References CVectorCore< CType >::array(), C_FLOAT64, CRadau5Method::State::ContainerState, CMath::ContinuousSimulation, CMath::EventSimulation, CTrajectoryMethod::FAILURE, CMath::FixedEventTarget, CMathContainer::getCountFixedEventTargets(), CTrajectoryMethod::mContainerState, mLastRootState, mLsodaStatus, mNumRoots, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mPeekAheadMode, CTrajectoryMethod::mpReducedModel, mSavedState, mTime, NONE, setRootMaskType(), CMath::State, CRadau5Method::State::Status, and CMathContainer::updateSimulatedValues().
Referenced by step().
step()
CTrajectoryMethod::Status CRadau5Method::step (const double & deltaT, const bool & final = false) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
const bool & final (default: false)
Returns
Status status
Reimplemented from CTrajectoryMethod.
References CVectorCore< CType >::array(), C_FLOAT64, CRadau5Method::State::ContainerState, CRadau5Method::Data::dim, EvalF(), EvalJ(), EvalM(), CCopasiMessage::EXCEPTION, CTrajectoryMethod::FAILURE, CMathContainer::getCountFixedEventTargets(), CMathContainer::getState(), H, idid, IJAC, IMAS, IOUT, ipar, CMathContainer::isStateValid(), ITOL, LIWORK, LWORK, CTrajectoryMethod::mContainerState, MCTrajectoryMethod, mData, mDWork, mErrorMsg, mIWork, mLastSuccessState, MLJAC, MLMAS, mLsodaStatus, mNumRoots, mpAtol, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mPeekAheadMode, CTrajectoryMethod::mpReducedModel, mpY, mRADAU, CTrajectoryMethod::mRootsFound, mRtol, mSavedState, mTargetTime, mTask, mTime, MUJAC, MUMAS, CTrajectoryMethod::NORMAL, resetState(), rpar, CVectorCore< CType >::size(), solout(), CMath::State, stateChange(), and CRadau5Method::State::Status.
Referenced by peekAhead().
Member Data Documentation
H
double CRadau5Method::H protected
Referenced by start(), and step().
idid
C_INT CRadau5Method::idid protected
Referenced by step().
IJAC
C_INT CRadau5Method::IJAC protected
Referenced by start(), and step().
IMAS
C_INT CRadau5Method::IMAS protected
Referenced by start(), and step().
IOUT
C_INT CRadau5Method::IOUT = 0 protected
Referenced by start(), and step().
ipar
C_INT CRadau5Method::ipar protected
Referenced by solout(), start(), and step().
ITOL
C_INT CRadau5Method::ITOL protected
Referenced by start(), and step().
LIWORK
C_INT CRadau5Method::LIWORK protected
Referenced by start(), and step().
LWORK
C_INT CRadau5Method::LWORK protected
Referenced by start(), and step().
mAtol
CVector< C_FLOAT64 > CRadau5Method::mAtol private
A vector of absolute tolerances.
Referenced by hasStateChanged(), and start().
mData
Data CRadau5Method::mData protected
mData.dim is the dimension of the ODE system. mData.pMethod contains CRadau5Method * this to be used in the static method EvalF
Referenced by CRadau5Method(), evalF(), start(), and step().
mDiscreteRoots
CVectorCore< bool > CRadau5Method::mDiscreteRoots private
A which indicates whether roots change only discretely.
Referenced by setRootMaskType(), and start().
mDWork
CVector< C_FLOAT64 > CRadau5Method::mDWork private
LSODA C_FLOAT64 work area
Referenced by resetState(), saveState(), start(), and step().
mErrorMsg
std::ostringstream CRadau5Method::mErrorMsg private
Stream to capture LSODA error messages
Referenced by start(), and step().
mIWork
CVector< C_INT > CRadau5Method::mIWork private
LSODA C_INT work area
Referenced by resetState(), saveState(), start(), and step().
mJType
C_INT CRadau5Method::mJType private
The way LSODA calculates the jacobian
Referenced by start().
mLastRootState
State CRadau5Method::mLastRootState protected
The last state having a root
Referenced by peekAhead(), start(), and stateChange().
mLastSuccessState
CVector< C_FLOAT64 > CRadau5Method::mLastSuccessState protected
The state after the last successful integration step
Referenced by step().
MLJAC
C_INT CRadau5Method::MLJAC protected
Referenced by start(), and step().
MLMAS
C_INT CRadau5Method::MLMAS protected
Referenced by start(), and step().
mLsodaStatus
C_INT CRadau5Method::mLsodaStatus protected
LSODA state.
Referenced by peekAhead(), resetState(), start(), stateChange(), and step().
mNumRoots
C_INT CRadau5Method::mNumRoots private
Number of roots
Referenced by setRootMaskType(), start(), stateChange(), and step().
mpAbsoluteTolerance
C_FLOAT64* CRadau5Method::mpAbsoluteTolerance private
A pointer to the value of "Absolute Tolerance"
Referenced by initializeParameter(), and start().
mpAtol
C_FLOAT64* CRadau5Method::mpAtol private
A pointer to the absolute tolerances excluding fixed event targets.
Referenced by start(), and step().
mPeekAheadMode
bool CRadau5Method::mPeekAheadMode private
A Boolean indicating whether we are in peekAhead mode
Referenced by peekAhead(), start(), stateChange(), and step().
mpInitialStepSize
C_FLOAT64* CRadau5Method::mpInitialStepSize private
A pointer to the value of "Initial Step Size guess"
Referenced by initializeParameter(), and start().
mpMaxInternalSteps
unsigned C_INT32* CRadau5Method::mpMaxInternalSteps private
A pointer to the value of "Max Internal Steps"
Referenced by initializeParameter(), and start().
mpRelativeTolerance
C_FLOAT64* CRadau5Method::mpRelativeTolerance private
A pointer to the value of "Relative Tolerance"
Referenced by hasStateChanged(), initializeParameter(), peekAhead(), and start().
mpY
C_FLOAT64* CRadau5Method::mpY private
Pointer to the array with left hand side values of the math container.
Referenced by start(), and step().
mpYdot
const C_FLOAT64* CRadau5Method::mpYdot private
Pointer to the array with right hand side values of the math container.
Referenced by evalF(), and start().
mRADAU
CRadau5 CRadau5Method::mRADAU private
The RADAU5 integrator
Referenced by resetState(), saveState(), start(), and step().
mRootCounter
unsigned C_INT32 CRadau5Method::mRootCounter private
Root counter to determine whether the internal step limit is exceeded.
Referenced by peekAhead(), and start().
mRootMask
CVector< bool > CRadau5Method::mRootMask private
A mask which hides all roots being constant and zero.
Referenced by createRootMask(), destroyRootMask(), maskRoots(), peekAhead(), resetState(), saveState(), and setRootMaskType().
mRootMasking
eRootMasking CRadau5Method::mRootMasking protected
A Boolean flag indicating whether we should try masking roots
Referenced by createRootMask(), destroyRootMask(), evalR(), resetState(), saveState(), and setRootMaskType().
mRtol
CVector< C_FLOAT64 > CRadau5Method::mRtol private
A pointer to the relative tolerances excluding fixed event targets.
Referenced by start(), and step().
mSavedState
State CRadau5Method::mSavedState private
Referenced by peekAhead(), start(), stateChange(), and step().
mTargetTime
C_FLOAT64 CRadau5Method::mTargetTime private
Store the targeted end time to determine whether the internal step limit is exceeded.
Referenced by peekAhead(), start(), and step().
mTask
C_INT CRadau5Method::mTask private
The task instructions to the integrator
Referenced by start(), and step().
mTime
C_FLOAT64 CRadau5Method::mTime protected
Current time.
Referenced by peekAhead(), resetState(), saveState(), start(), stateChange(), and step().
MUJAC
C_INT CRadau5Method::MUJAC protected
Referenced by start(), and step().
MUMAS
C_INT CRadau5Method::MUMAS protected
Referenced by start(), and step().
rpar
double CRadau5Method::rpar protected
Referenced by solout(), start(), and step().
The documentation for this class was generated from the following files:
CRadau5Method.h
CRadau5Method.cpp