COPASI API: CDataObjectMap Class Reference
CDataObjectMap Class Reference
#include <CDataObjectMap.h>
Classes
class const_iterator
class const_type_iterator
class iterator
class type_iterator
Public Types
typedef std::map< std::string, std::set< CDataObject * > > data
typedef std::pair< std::set< CDataObject * >::const_iterator, std::set< CDataObject * >::const_iterator > range
Public Member Functions
iterator begin ()
const_iterator begin () const
CDataObjectMap ()
CDataObjectMap (const CDataObjectMap &src)
void clear ()
bool contains (CDataObject *pObject) const
iterator end ()
const_iterator end () const
std::pair< std::set< CDataObject * >::const_iterator, std::set< CDataObject * >::const_iterator > equal_range (const std::string &name) const
bool erase (CDataObject *pObject)
std::pair< std::set< CDataObject * >::iterator, bool > insert (CDataObject *pObject)
void objectRenamed (CDataObject *pObject, const std::string &oldName)
~CDataObjectMap ()
Member Typedef Documentation
data
typedef std::map< std::string, std::set< CDataObject * > > CDataObjectMap::data
range
typedef std::pair< std::set< CDataObject * >::const_iterator, std::set< CDataObject * >::const_iterator > CDataObjectMap::range
Constructor & Destructor Documentation
CDataObjectMap() [1/2]
CDataObjectMap::CDataObjectMap ()
CDataObjectMap() [2/2]
CDataObjectMap::CDataObjectMap (const CDataObjectMap & src)
~CDataObjectMap()
CDataObjectMap::~CDataObjectMap ()
Member Function Documentation
begin() [1/2]
CDataObjectMap::iterator CDataObjectMap::begin ()
Referenced by CDataVector< CType >::beginName(), CCopasiParameterGroup::beginName(), CDataObjectMap::const_iterator::const_iterator(), CDataContainer::getDescendants(), CDataContainer::getValueObject(), CDataObjectMap::iterator::iterator(), CCopasiParameterGroup::operator=(), and CDataContainer::~CDataContainer().
begin() [2/2]
CDataObjectMap::const_iterator CDataObjectMap::begin () const
clear()
void CDataObjectMap::clear ()
contains()
bool CDataObjectMap::contains (CDataObject * pObject) const
References CDataObject::getObjectName().
end() [1/2]
CDataObjectMap::iterator CDataObjectMap::end ()
Referenced by CDataVector< CType >::endName(), CCopasiParameterGroup::endName(), CDataContainer::getDescendants(), CDataContainer::getValueObject(), CCopasiParameterGroup::operator=(), and CDataContainer::~CDataContainer().
end() [2/2]
CDataObjectMap::const_iterator CDataObjectMap::end () const
equal_range()
std::pair< std::set< CDataObject * >::const_iterator, std::set< CDataObject * >::const_iterator > CDataObjectMap::equal_range (const std::string & name) const
Referenced by CMetabNameInterface::doesExist(), CModel::findMetabByName(), CDataArray::getObject(), CDataContainer::getObject(), CDataVectorN< CType >::getObject(), CUndoData::getObject(), CCopasiParameterGroup::getParameter(), CDataVectorN< CType >::isInsertAllowed(), CMetabNameInterface::isUnique(), and CDataVectorN< CType >::operator[]().
erase()
bool CDataObjectMap::erase (CDataObject * pObject)
References CDataObject::getObjectName().
Referenced by CDataContainer::remove().
insert()
std::pair< std::set< CDataObject * >::iterator, bool > CDataObjectMap::insert (CDataObject * pObject)
References CDataObject::getObjectName().
Referenced by CDataContainer::add(), and objectRenamed().
objectRenamed()
void CDataObjectMap::objectRenamed (CDataObject * pObject, const std::string & oldName)
References insert().
Referenced by CDataContainer::objectRenamed().
The documentation for this class was generated from the following files:
CDataObjectMap.h
CDataObjectMap.cpp