COPASI API: CEvaluationNode Class Reference
CEvaluationNode Class Reference
#include <CEvaluationNode.h>
Classes
class CPrecedence
Public Types
enum class MainType {
INVALID , NUMBER , CONSTANT , OPERATOR ,
OBJECT , FUNCTION , CALL , STRUCTURE ,
CHOICE , VARIABLE , WHITESPACE , LOGICAL ,
MV_FUNCTION , VECTOR , DELAY , UNIT ,
__SIZE
}
enum class SubType {
DEFAULT , DELAY , IF , VECTOR ,
CN , DOUBLE , FUNCTION , LOG ,
OPEN , PI , POWER , EXPRESSION ,
POINTER , EXPONENTIALE , INTEGER , LOG10 ,
MULTIPLY , OR , VECTOROPEN , COMMA ,
DIVIDE , ENOTATION , EXP , True ,
XOR , RATIONALE , AND , CLOSE ,
False , MODULUS , SIN , VECTORCLOSE ,
COS , EQ , Infinity , PLUS ,
NaN , MINUS , NE , TAN ,
REMAINDER , GT , SEC , CSC ,
GE , COT , LT , LE ,
SINH , COSH , TANH , SECH ,
CSCH , COTH , ARCSIN , ARCCOS ,
ARCTAN , ARCSEC , ARCCSC , ARCCOT ,
ARCSINH , ARCCOSH , ARCTANH , ARCSECH ,
ARCCSCH , ARCCOTH , SQRT , ABS ,
FLOOR , CEIL , FACTORIAL , NOT ,
RUNIFORM , RNORMAL , MAX , MIN ,
RGAMMA , RPOISSON , SIGN , AVOGADRO ,
INVALID , __SIZE
}
enum class ValueType { Unknown , Boolean , Number , __SIZE }
Public Types inherited from CCopasiNode< std::string >
typedef std::string Data
Public Member Functions
void addChildren (const std::vector< CEvaluationNode * > &children)
std::string buildBerkeleyMadonnaString () const
std::string buildCCodeString () const
std::string buildDisplayString () const
std::string buildInfix () const
std::string buildMMLString (bool expand, const std::vector< std::vector< std::string > > &variables) const
std::string buildXPPString () const
virtual void calculate ()
CEvaluationNode ()
CEvaluationNode (const CEvaluationNode &src)
virtual CIssue compile ()
CEvaluationNode * copyBranch () const
CEvaluationNode * copyNode (CEvaluationNode *child1, CEvaluationNode *child2) const
CEvaluationNode * copyNode (const std::vector< CEvaluationNode * > &children) const
const CEvaluationNode * findTopMinus (const std::vector< CFunctionAnalyzer::CValue > &callParameters) const
virtual std::string getBerkeleyMadonnaString (const std::vector< std::string > &children) const
virtual std::string getCCodeString (const std::vector< std::string > &children) const
virtual std::string getDisplayString (const std::vector< std::string > &children) const
virtual std::string getInfix (const std::vector< std::string > &children) const
virtual std::string getMMLString (const std::vector< std::string > &children, bool expand, const std::vector< std::vector< std::string > > &variables) const
const CEvaluationTree * getTree () const
virtual CValidatedUnit getUnit (const CMathContainer &container, const std::vector< CValidatedUnit > &units) const
const C_FLOAT64 * getValuePointer () const
const ValueType & getValueType () const
virtual std::string getXPPString (const std::vector< std::string > &children) const
virtual bool isBoolean () const
const MainType & mainType () const
bool operator!= (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &rhs)
bool operator< (const CEvaluationNode &right) const
bool operator== (const CEvaluationNode &right) const
void printRecursively () const
void printRecursively (std::ostream &os, int indent=0) const
void setTree (const CEvaluationTree *pTree)
virtual CValidatedUnit setUnit (const CMathContainer &container, const std::map< CEvaluationNode *, CValidatedUnit > &currentUnits, std::map< CEvaluationNode *, CValidatedUnit > &targetUnits) const
virtual CIssue setValueType (const ValueType &valueType)
virtual CEvaluationNode * simplifyNode (const std::vector< CEvaluationNode * > &children) const
CEvaluationNode * splitBranch (const CEvaluationNode *splitnode, bool left) const
const SubType & subType () const
virtual ASTNode * toAST (const CDataModel *pDataModel) const
virtual ~CEvaluationNode ()
Public Member Functions inherited from CCopasiNode< std::string >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual Data & getData ()
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Static Public Member Functions
static CEvaluationNode * create (const MainType &mainType, const SubType &subType, const std::string &data)
static bool isKeyword (const std::string &str)
Static Public Attributes
static const CEnumAnnotation< std::string, MainType > MainTypeName
static const CEnumAnnotation< std::string, SubType > SubTypeName
Protected Member Functions
CEvaluationNode (const MainType &type, const SubType &subType, const Data &data)
Protected Member Functions inherited from CCopasiNode< std::string >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes
MainType mMainType
class CEvaluationNode::CPrecedence mPrecedence
const CEvaluationTree * mpTree
const C_FLOAT64 * mpValue
SubType mSubType
C_FLOAT64 mValue
ValueType mValueType
Protected Attributes inherited from CCopasiNode< std::string >
Data mData
Static Private Attributes
static const char * Keywords []
Detailed Description
This is the base class for nodes used in an evaluation trees
Member Enumeration Documentation
MainType
enum CEvaluationNode::MainType strong
Enumeration of possible node types.
Enumerator
INVALID
NUMBER
CONSTANT
OPERATOR
OBJECT
FUNCTION
CALL
STRUCTURE
CHOICE
VARIABLE
WHITESPACE
LOGICAL
MV_FUNCTION
VECTOR
DELAY
UNIT
__SIZE
SubType
enum CEvaluationNode::SubType strong
Enumerator
DEFAULT
DELAY
IF
VECTOR
CN
DOUBLE
FUNCTION
LOG
OPEN
PI
POWER
EXPRESSION
POINTER
EXPONENTIALE
INTEGER
LOG10
MULTIPLY
OR
VECTOROPEN
COMMA
DIVIDE
ENOTATION
EXP
True
XOR
RATIONALE
AND
CLOSE
False
MODULUS
SIN
VECTORCLOSE
COS
EQ
Infinity
PLUS
NaN
MINUS
NE
TAN
REMAINDER
GT
SEC
CSC
GE
COT
LT
LE
SINH
COSH
TANH
SECH
CSCH
COTH
ARCSIN
ARCCOS
ARCTAN
ARCSEC
ARCCSC
ARCCOT
ARCSINH
ARCCOSH
ARCTANH
ARCSECH
ARCCSCH
ARCCOTH
SQRT
ABS
FLOOR
CEIL
FACTORIAL
NOT
RUNIFORM
RNORMAL
MAX
MIN
RGAMMA
RPOISSON
SIGN
AVOGADRO
INVALID
__SIZE
ValueType
enum CEvaluationNode::ValueType strong
Enumerator
Unknown
Boolean
Number
__SIZE
Constructor & Destructor Documentation
CEvaluationNode() [1/3]
CEvaluationNode::CEvaluationNode ()
Default constructor
References mpValue, and mValue.
Referenced by create().
CEvaluationNode() [2/3]
CEvaluationNode::CEvaluationNode (const MainType & type, const SubType & subType, const Data & data) protected
Specific constructor
Parameters
const MainType & mainType
const SubType & subType
const Data & data
References mpValue, and mValue.
CEvaluationNode() [3/3]
CEvaluationNode::CEvaluationNode (const CEvaluationNode & src)
Copy constructor
Parameters
const CEvaluationNode & src
References mpValue, and mValue.
~CEvaluationNode()
CEvaluationNode::~CEvaluationNode () virtual
Destructor
Member Function Documentation
addChildren()
void CEvaluationNode::addChildren (const std::vector< CEvaluationNode * > & children)
Add the children to the node
Parameters
const std::vector< CEvaluationNode * > & children
References CCopasiNode< std::string >::addChild().
Referenced by CEvaluationNodeCall::fromAST().
buildBerkeleyMadonnaString()
std::string CEvaluationNode::buildBerkeleyMadonnaString () const
Build the Berkeley Madonna string.
Returns
std::string BerkeleyMadonnaString
References CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CNodeContextIterator< Node, Context >::next(), and CNodeContextIterator< Node, Context >::parentContextPtr().
Referenced by CExpression::getBerkeleyMadonnaString(), CODEExporterBM::getDisplayExpressionString(), and CODEExporterBM::getDisplayFunctionString().
buildCCodeString()
std::string CEvaluationNode::buildCCodeString () const
Build the C-code string.
Returns
std::string CCodeString
Build the C-code string.
References CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CNodeContextIterator< Node, Context >::next(), and CNodeContextIterator< Node, Context >::parentContextPtr().
Referenced by CODEExporterC::exportSingleFunction(), CExpression::getCCodeString(), and CODEExporterC::getDisplayExpressionString().
buildDisplayString()
std::string CEvaluationNode::buildDisplayString () const
Build the human readable display string.
Returns
std::string DisplayString
References CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CNodeContextIterator< Node, Context >::next(), and CNodeContextIterator< Node, Context >::parentContextPtr().
Referenced by CExpression::compile().
buildInfix()
std::string CEvaluationNode::buildInfix () const
Build the infix string.
Returns
std::string Infix
References CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CNodeContextIterator< Node, Context >::next(), and CNodeContextIterator< Node, Context >::parentContextPtr().
Referenced by CMathObject::appendDelays(), CExpression::compile(), CMathExpression::convertToInitialExpression(), CMathExpression::relocate(), CMathContainer::replaceDiscontinuousNode(), CEvaluationNodeOperator::simplifyNode(), CExpression::updateInfix(), and CEvaluationTree::updateTree().
buildMMLString()
std::string CEvaluationNode::buildMMLString (bool expand, const std::vector< std::vector< std::string > > & variables) const
Build the MathML string
Parameters
bool expand = true
const std::vector< std::vector< std::string > > & variables
Returns
std::string MMLString
References CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CNodeContextIterator< Node, Context >::next(), and CNodeContextIterator< Node, Context >::parentContextPtr().
Referenced by CFunction::writeMathML(), and CExpression::writeMathML().
buildXPPString()
std::string CEvaluationNode::buildXPPString () const
Build the XPPAUT string.
Returns
std::string XPPString
References CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CNodeContextIterator< Node, Context >::next(), and CNodeContextIterator< Node, Context >::parentContextPtr().
Referenced by CODEExporterXPPAUT::getDisplayExpressionString(), CODEExporterXPPAUT::getDisplayFunctionString(), and CExpression::getXPPString().
calculate()
virtual void CEvaluationNode::calculate (void) inline virtual
Retrieve the value of the node
Returns
const C_FLOAT64 & value Calculate the numerical result of the node. It is assumed that all child nodes are up to date.
Reimplemented in CEvaluationNodeVariable, CEvaluationNodeOperator, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeChoice, and CEvaluationNodeCall.
compile()
CIssue CEvaluationNode::compile () virtual
Compile a node;
Returns
CIssue issue;
Reimplemented in CEvaluationNodeVariable, CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, and CEvaluationNodeCall.
References CIssue::Success.
Referenced by CDerive::compileTree(), CDerive::deriveBranch(), and CEvaluationNodeDelay::fromAST().
copyBranch()
CEvaluationNode * CEvaluationNode::copyBranch () const
Copy the whole branch with this node as root.
Returns
CEvaluationNode*, return a pointer to the root of the newly copied branch
References CNodeContextIterator< Node, Context >::context(), CNodeContextIterator< Node, Context >::end(), CNodeContextIterator< Node, Context >::next(), and CNodeContextIterator< Node, Context >::parentContextPtr().
Referenced by CODEExporter::assembleSubTreeForMassAction(), CMathExpression::copy(), CDerive::copyBranch_var2obj(), SBMLImporter::createCReactionFromReaction(), SBMLImporter::divideByObject(), CODEExporter::exportSingleFunction(), SBMLImporter::isMassActionExpression(), CSBMLExporter::multiplyByObject(), CSBMLExporter::replaceSpeciesReferences(), CReaction::setFunctionFromExpressionTree(), CEvaluationNodeFunction::simplifyNode(), CEvaluationNodeOperator::simplifyNode(), and splitBranch().
copyNode() [1/2]
CEvaluationNode * CEvaluationNode::copyNode (CEvaluationNode * child1, CEvaluationNode * child2) const
Copy a node and assign new children child1 and child2
Returns
CEvaluationNode* return a pointer to the new node
Referenced by CMathContainer::copyBranch(), CMathContainer::replaceDiscontinuousNode(), CSBMLExporter::replaceSpeciesReferences(), simplifyNode(), CEvaluationNodeFunction::simplifyNode(), CEvaluationNodeOperator::simplifyNode(), and splitBranch().
copyNode() [2/2]
CEvaluationNode * CEvaluationNode::copyNode (const std::vector< CEvaluationNode * > & children) const
Copy a node and assign new children in the vector
Returns
CEvaluationNode* return a pointer to the new node
References CCopasiNode< _Data >::addChild(), create(), CCopasiNode< std::string >::getData(), mMainType, and mSubType.
create()
CEvaluationNode * CEvaluationNode::create (const MainType & mainType, const SubType & subType, const std::string & data) static
Creates an evaluation node of type with the given data
Parameters
const MainType & mainType
const SubType & subType
const std::string & data
Returns
CEvaluationNode * evaluationNode
References __SIZE, CALL, CEvaluationNode(), CHOICE, CONSTANT, DELAY, FUNCTION, INVALID, LOGICAL, mainType(), MV_FUNCTION, NUMBER, OBJECT, OPERATOR, STRUCTURE, subType(), UNIT, VARIABLE, VECTOR, and WHITESPACE.
Referenced by CODEExporter::assembleSubTreeForMassAction(), copyNode(), CODEExporter::modifyTreeForMassAction(), CEvaluationNodeFunction::simplifyNode(), CEvaluationNodeOperator::simplifyNode(), and SBMLImporter::variables2objects().
findTopMinus()
const CEvaluationNode * CEvaluationNode::findTopMinus (const std::vector< CFunctionAnalyzer::CValue > & callParameters) const
Find a minus operator in the tree that is suitable for splitting with splitBranch(). Specifically it is a minus operator that is connected with the root node by multiplication or division nodes only. For the division nodes only the left child is considered.
References CNodeIteratorMode::After, CNodeIteratorMode::Before, CNodeContextIterator< Node, Context >::context(), DIVIDE, CNodeContextIterator< Node, Context >::end(), CFunctionAnalyzer::evaluateNode(), CFunctionAnalyzer::CValue::isPositive(), MINUS, MULTIPLY, CNodeContextIterator< Node, Context >::next(), CFunctionAnalyzer::NOOBJECT, OPERATOR, CNodeContextIterator< Node, Context >::parentContextPtr(), CNodeContextIterator< Node, Context >::processingMode(), CNodeContextIterator< Node, Context >::setProcessingModes(), and CNodeContextIterator< Node, Context >::skipChildren().
Referenced by CFunction::splitFunction().
getBerkeleyMadonnaString()
std::string CEvaluationNode::getBerkeleyMadonnaString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in Berkeley Madonna format.
Returns
std::string BerkeleyMadonnaString
Reimplemented in CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, CEvaluationNodeVector, CEvaluationNodeUnit, and CEvaluationNodeConstant.
References CCopasiNode< std::string >::mData.
getCCodeString()
std::string CEvaluationNode::getCCodeString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in C.
Returns
std::string CCodeString
Reimplemented in CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, CEvaluationNodeVector, CEvaluationNodeUnit, CEvaluationNodeNumber, and CEvaluationNodeConstant.
References CCopasiNode< std::string >::mData.
getDisplayString()
std::string CEvaluationNode::getDisplayString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes.
Returns
std::string DisplayString
Reimplemented in CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, and CEvaluationNodeVector.
References CCopasiNode< std::string >::mData.
getInfix()
std::string CEvaluationNode::getInfix (const std::vector< std::string > & children) const virtual
Retrieve the infix value of the node and its eventual child nodes.
Returns
std::string Infix
Reimplemented in CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, and CEvaluationNodeVector.
References CCopasiNode< std::string >::mData.
getMMLString()
std::string CEvaluationNode::getMMLString (const std::vector< std::string > & children, bool expand, const std::vector< std::vector< std::string > > & variables) const virtual
Build the MathML string
Parameters
const std::vector< std::string > & children
bool expand = true
const std::vector< std::vector< std::string > > & variables
Returns
std::string MMLString
Reimplemented in CEvaluationNodeVariable, CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, CEvaluationNodeUnit, CEvaluationNodeNumber, and CEvaluationNodeConstant.
getTree()
const CEvaluationTree * CEvaluationNode::getTree () const
References CCopasiNode< _Data >::getParent(), and mpTree.
Referenced by CEvaluationNodeObject::compile(), and CEvaluationNodeVariable::compile().
getUnit()
CValidatedUnit CEvaluationNode::getUnit (const CMathContainer & container, const std::vector< CValidatedUnit > & units) const virtual
Figure out the appropriate CUnit to use, based on the child nodes. This sets the default, appropriate for many cases, as Dimensionless
Parameters
const CMathContainer & container
const std::vector< CValidatedUnit > & units
Returns
CUnit unit
Reimplemented in CEvaluationNodeVariable, CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, CEvaluationNodeVector, and CEvaluationNodeUnit.
References CBaseUnit::dimensionless.
getValuePointer()
const C_FLOAT64 * CEvaluationNode::getValuePointer () const
Retrieve the pointer to the value of the node
Returns
const C_FLOAT64 * pValue
References mpValue.
Referenced by CDerive::add(), CEvaluationNodeChoice::compile(), CEvaluationNodeDelay::compile(), CEvaluationNodeFunction::compile(), CEvaluationNodeLogical::compile(), CEvaluationNodeOperator::compile(), CEvaluationTree::compileNodes(), CMathExpression::convertToInitialExpression(), CEvaluationNodeFunction::fromAST(), CEvaluationNodeOperator::getUnit(), SBMLImporter::isMassActionExpression(), CDerive::isOne(), CDerive::isZero(), CEvaluationTree::mapObjectNodes(), CEvaluationTree::parse(), CEvaluationNodeOperator::setUnit(), CEvaluationNodeFunction::simplifyNode(), CEvaluationNodeOperator::simplifyNode(), CDerive::subtract(), and CEvaluationTree::updateTree().
getValueType()
const CEvaluationNode::ValueType & CEvaluationNode::getValueType () const
Retrieve the value type of the node
Returns
const ValueType & valueType
References mValueType.
Referenced by CEvaluationNodeChoice::compile(), and CEvaluationNodeLogical::compile().
getXPPString()
std::string CEvaluationNode::getXPPString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in XPPAUT format.
Returns
std::string XPPString
Reimplemented in CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, CEvaluationNodeVector, CEvaluationNodeUnit, and CEvaluationNodeConstant.
References CCopasiNode< std::string >::mData.
isBoolean()
bool CEvaluationNode::isBoolean () const virtual
Check whether the result is Boolean
Returns
bool isBoolean
Reimplemented in CEvaluationNodeCall.
References Boolean, and mValueType.
Referenced by CMathEvent::CTrigger::compileEQ(), CMathEvent::CTrigger::countRootsEQ(), and CEvaluationTree::isBoolean().
isKeyword()
bool CEvaluationNode::isKeyword (const std::string & str) static
Check whether the string is a keyword
Parameters
const std::string & str
Returns
bool isKeyword
References Keywords.
Referenced by CEvaluationNodeCall::getData(), and CEvaluationNodeCall::setData().
mainType()
const CEvaluationNode::MainType & CEvaluationNode::mainType () const
Retrieve the type part of type
Returns
Type type
References mMainType.
Referenced by SBMLImporter::areEqualSubtrees(), CODEExporter::assembleSubTreeForMassAction(), CSBMLExporter::checkForPiecewiseFunctions(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), create(), SBMLImporter::createCReactionFromReaction(), CMathContainer::createDiscontinuityTriggerInfix(), CSBMLExporter::createEvent(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createRule(), SBMLImporter::divideByObject(), CSBMLExporter::exportEventAssignments(), CSBMLExporter::findDirectlyUsedFunctions(), CSBMLExporter::findModelEntityDependencies(), CEvaluationNodeFunction::fromAST(), CEvaluationNodeFunction::getMMLString(), CEvaluationNodeOperator::getMMLString(), CEvaluationNodeFunction::handleNot(), CEvaluationNodeFunction::handleSign(), SBMLImporter::isConstantFlux(), CSBMLExporter::isEventAssignmentSBMLCompatible(), SBMLImporter::isMassAction(), SBMLImporter::isMassActionExpression(), CMathObject::isPrerequisiteForContext(), CSBMLExporter::multiplyByObject(), operator<(), CSBMLExporter::replaceSpeciesReferences(), CSBMLExporter::setFunctionSBMLIds(), CEvaluationNodeFunction::simplifyNode(), CEvaluationNodeOperator::simplifyNode(), CReaction::variables2objects(), and SBMLImporter::variables2objects().
operator!=()
bool CEvaluationNode::operator!= (const CEvaluationNode & right) const
Unequal operator, compares two CEvaluationNode objects and return true if they are equal.
operator<() [1/2]
bool CEvaluationNode::operator< (const CEvaluationNode & rhs)
Comparison operator used to evaluate the precedence of the node. it compares the right precedence of the left node with the left precedence of the right node.
Parameters
const CEvaluationNode & rhs;
Returns
bool isLess
References CEvaluationNode::CPrecedence::left, mPrecedence, and CEvaluationNode::CPrecedence::right.
operator<() [2/2]
bool CEvaluationNode::operator< (const CEvaluationNode & right) const
Less operator, compares two CEvaluationNode objects and return true if the first operand is smaller than the second.
References __SIZE, CALL, CHOICE, CONSTANT, DELAY, FUNCTION, CCopasiNode< _Data >::getChild(), CCopasiNode< std::string >::getChild(), CCopasiNode< std::string >::getData(), CCopasiNode< _Data >::getData(), CCopasiNode< _Data >::getSibling(), INVALID, LOGICAL, mainType(), MV_FUNCTION, NUMBER, OBJECT, OPERATOR, STRUCTURE, subType(), VARIABLE, VECTOR, and WHITESPACE.
operator==()
bool CEvaluationNode::operator== (const CEvaluationNode & right) const
Equals operator, compares two CEvaluationNode objects and return true if they are equal.
References CNodeContextIterator< Node, Context >::end(), and CNodeContextIterator< Node, Context >::next().
printRecursively() [1/2]
void CEvaluationNode::printRecursively () const
Referenced by printRecursively().
printRecursively() [2/2]
void CEvaluationNode::printRecursively (std::ostream & os, int indent = 0) const
References CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), MainTypeName, CCopasiNode< std::string >::mData, mMainType, mSubType, mValue, printRecursively(), and SubTypeName.
setTree()
void CEvaluationNode::setTree (const CEvaluationTree * pTree)
References mpTree.
Referenced by CEvaluationTree::parse(), and CEvaluationTree::setRoot().
setUnit()
CValidatedUnit CEvaluationNode::setUnit (const CMathContainer & container, const std::map< CEvaluationNode *, CValidatedUnit > & currentUnits, std::map< CEvaluationNode *, CValidatedUnit > & targetUnits) const virtual
Set the unit for the node and return the resulting unit. The child node units are added to the map
Parameters
const CMathContainer & container
const std::map < CEvaluationNode * , CValidatedUnit > & currentUnits
std::map < CEvaluationNode * , CValidatedUnit > & targetUnits
Returns
CUnit unit
Reimplemented in CEvaluationNodeOperator, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, and CEvaluationNodeVector.
References CValidatedUnit::conflict(), CCopasiNode< std::string >::getChild(), CValidatedUnit::merge(), and CValidatedUnit::setConflict().
Referenced by CEvaluationNodeVector::setUnit(), CEvaluationNodeCall::setUnit(), CEvaluationNodeChoice::setUnit(), CEvaluationNodeDelay::setUnit(), CEvaluationNodeFunction::setUnit(), CEvaluationNodeLogical::setUnit(), and CEvaluationNodeOperator::setUnit().
setValueType()
CIssue CEvaluationNode::setValueType (const ValueType & valueType) virtual
Set the type the result of the node
Parameters
const ValueType & valueType
Returns
CIssue issue;
Reimplemented in CEvaluationNodeVariable, CEvaluationNodeChoice, and CEvaluationNodeCall.
References CIssue::Error, mValueType, CIssue::Success, and CIssue::ValueTypeMismatch.
Referenced by CEvaluationNodeChoice::compile(), CEvaluationNodeFunction::compile(), CEvaluationNodeLogical::compile(), CEvaluationNodeOperator::compile(), CEvaluationTree::setTree(), CEvaluationNodeCall::setValueType(), CEvaluationNodeChoice::setValueType(), and CEvaluationNodeVariable::setValueType().
simplifyNode()
CEvaluationNode * CEvaluationNode::simplifyNode (const std::vector< CEvaluationNode * > & children) const virtual
Create a simplified node from the original node with children child1 and child2 (if not exist, = NULL)
Returns
CEvaluationNode* return a pointer to the simplified node;
Reimplemented in CEvaluationNodeOperator, and CEvaluationNodeFunction.
References copyNode().
Referenced by CEvaluationNodeOperator::simplifyNode().
splitBranch()
CEvaluationNode * CEvaluationNode::splitBranch (const CEvaluationNode * splitnode, bool left) const
Split the tree in two parts at the given splitnode, starting from *this. Returned is the root node of a copy of the tree, including everything above the split node and either the branch below the left child of the split node or the branch below the right child of the split node. The split node itself is not included either case.
References copyBranch(), copyNode(), CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), and splitBranch().
Referenced by splitBranch(), and CFunction::splitFunction().
subType()
const CEvaluationNode::SubType & CEvaluationNode::subType () const
Retrieve the subtype part of type
Returns
SubType subType
References mSubType.
Referenced by SBMLImporter::areEqualSubtrees(), CEvaluationNodeCall::CEvaluationNodeCall(), CEvaluationNodeChoice::CEvaluationNodeChoice(), CEvaluationNodeConstant::CEvaluationNodeConstant(), CEvaluationNodeDelay::CEvaluationNodeDelay(), CEvaluationNodeFunction::CEvaluationNodeFunction(), CEvaluationNodeNumber::CEvaluationNodeNumber(), CEvaluationNodeObject::CEvaluationNodeObject(), CEvaluationNodeStructure::CEvaluationNodeStructure(), CEvaluationNodeVector::CEvaluationNodeVector(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CMathEvent::CTrigger::compileAND(), CMathEvent::CTrigger::compileLE(), create(), CMathContainer::createDiscontinuityTriggerInfix(), CEvaluationNodeOperator::createModuloTree(), CDerive::deriveBranch(), SBMLImporter::divideByObject(), CEvaluationNodeCall::fromAST(), CEvaluationNodeChoice::fromAST(), CEvaluationNodeConstant::fromAST(), CEvaluationNodeDelay::fromAST(), CEvaluationNodeFunction::fromAST(), CEvaluationNodeLogical::fromAST(), CEvaluationNodeNumber::fromAST(), CEvaluationNodeOperator::fromAST(), CEvaluationNodeConstant::getBerkeleyMadonnaString(), CEvaluationNodeFunction::getBerkeleyMadonnaString(), CEvaluationNodeLogical::getBerkeleyMadonnaString(), CEvaluationNodeConstant::getCCodeString(), CEvaluationNodeFunction::getCCodeString(), CEvaluationNodeLogical::getCCodeString(), CEvaluationNodeOperator::getCCodeString(), CEvaluationNodeConstant::getMMLString(), CEvaluationNodeFunction::getMMLString(), CEvaluationNodeLogical::getMMLString(), CEvaluationNodeOperator::getMMLString(), CEvaluationNodeFunction::getUnit(), CEvaluationNodeConstant::getXPPString(), CEvaluationNodeFunction::getXPPString(), CEvaluationNodeLogical::getXPPString(), CEvaluationNodeOperator::getXPPString(), CEvaluationNodeFunction::handleSign(), SBMLImporter::isMassActionExpression(), CMathObject::isPrerequisiteForContext(), CSBMLExporter::multiplyByObject(), operator<(), CSBMLExporter::replaceSpeciesReferences(), SBMLImporter::separateProductArguments(), CEvaluationNodeFunction::setUnit(), CEvaluationNodeFunction::simplifyNode(), CEvaluationNodeOperator::simplifyNode(), CEvaluationNodeConstant::toAST(), CEvaluationNodeNumber::toAST(), CEvaluationNodeFunction::toAST(), CEvaluationNodeLogical::toAST(), CEvaluationNodeOperator::toAST(), CReaction::variables2objects(), and SBMLImporter::variables2objects().
toAST()
ASTNode * CEvaluationNode::toAST (const CDataModel * pDataModel) const virtual
Create a new invalid ASTNode.
Returns
ASTNode* return a pointer to the newly created node;
Reimplemented in CEvaluationNodeVariable, CEvaluationNodeOperator, CEvaluationNodeObject, CEvaluationNodeLogical, CEvaluationNodeFunction, CEvaluationNodeDelay, CEvaluationNodeChoice, CEvaluationNodeCall, CEvaluationNodeWhiteSpace, CEvaluationNodeVector, CEvaluationNodeUnit, CEvaluationNodeStructure, CEvaluationNodeNumber, and CEvaluationNodeConstant.
Referenced by CSBMLExporter::convertToASTNode(), CEvaluationNodeOperator::createModuloTree(), CEvaluationTree::toAST(), CEvaluationNodeCall::toAST(), CEvaluationNodeChoice::toAST(), CEvaluationNodeDelay::toAST(), CEvaluationNodeFunction::toAST(), CEvaluationNodeLogical::toAST(), CEvaluationNodeObject::toAST(), and CEvaluationNodeOperator::toAST().
Member Data Documentation
Keywords
const char * CEvaluationNode::Keywords static private
A list of reserved key words
Referenced by isKeyword().
MainTypeName
const CEnumAnnotation< std::string, CEvaluationNode::MainType > CEvaluationNode::MainTypeName static
Referenced by printRecursively().
mMainType
MainType CEvaluationNode::mMainType protected
The type the node
Referenced by CEvaluationNodeCall::compile(), copyNode(), mainType(), and printRecursively().
mPrecedence
class CEvaluationNode::CPrecedence CEvaluationNode::mPrecedence protected
Referenced by CEvaluationNodeCall::CEvaluationNodeCall(), CEvaluationNodeChoice::CEvaluationNodeChoice(), CEvaluationNodeConstant::CEvaluationNodeConstant(), CEvaluationNodeDelay::CEvaluationNodeDelay(), CEvaluationNodeFunction::CEvaluationNodeFunction(), CEvaluationNodeLogical::CEvaluationNodeLogical(), CEvaluationNodeNumber::CEvaluationNodeNumber(), CEvaluationNodeObject::CEvaluationNodeObject(), CEvaluationNodeOperator::CEvaluationNodeOperator(), CEvaluationNodeStructure::CEvaluationNodeStructure(), CEvaluationNodeUnit::CEvaluationNodeUnit(), CEvaluationNodeVariable::CEvaluationNodeVariable(), CEvaluationNodeVector::CEvaluationNodeVector(), and operator<().
mpTree
const CEvaluationTree* CEvaluationNode::mpTree protected
Referenced by CEvaluationNodeVariable::calculate(), CEvaluationNodeObject::compile(), CEvaluationNodeVariable::compile(), getTree(), and setTree().
mpValue
const C_FLOAT64* CEvaluationNode::mpValue protected
A pointer to the numerical value of the node
Referenced by CEvaluationNode(), CEvaluationNodeObject::CEvaluationNodeObject(), CEvaluationNodeObject::compile(), CEvaluationNodeNumber::getCCodeString(), CEvaluationNodeObject::getObjectValuePtr(), CEvaluationNodeObject::getUnit(), getValuePointer(), CEvaluationNodeObject::mapObject(), CEvaluationNodeObject::setObjectValuePtr(), and CEvaluationNodeNumber::toAST().
mSubType
SubType CEvaluationNode::mSubType protected
The type the node
Referenced by CEvaluationNodeLogical::calculate(), CEvaluationNodeConstant::CEvaluationNodeConstant(), CEvaluationNodeFunction::CEvaluationNodeFunction(), CEvaluationNodeLogical::CEvaluationNodeLogical(), CEvaluationNodeObject::CEvaluationNodeObject(), CEvaluationNodeOperator::CEvaluationNodeOperator(), CEvaluationNodeCall::compile(), CEvaluationNodeDelay::compile(), CEvaluationNodeLogical::compile(), CEvaluationNodeObject::compile(), copyNode(), CEvaluationNodeDelay::getBerkeleyMadonnaString(), CEvaluationNodeFunction::getBerkeleyMadonnaString(), CEvaluationNodeCall::getCalledTree(), CEvaluationNodeCall::getCCodeString(), CEvaluationNodeDelay::getCCodeString(), CEvaluationNodeFunction::getCCodeString(), CEvaluationNodeObject::getData(), CEvaluationNodeCall::getDisplayString(), CEvaluationNodeDelay::getDisplayString(), CEvaluationNodeFunction::getDisplayString(), CEvaluationNodeOperator::getDisplayString(), CEvaluationNodeCall::getInfix(), CEvaluationNodeDelay::getInfix(), CEvaluationNodeFunction::getInfix(), CEvaluationNodeObject::getInfix(), CEvaluationNodeOperator::getInfix(), CEvaluationNodeCall::getMMLString(), CEvaluationNodeDelay::getMMLString(), CEvaluationNodeFunction::getMMLString(), CEvaluationNodeOperator::getMMLString(), CEvaluationNodeCall::getUnit(), CEvaluationNodeLogical::getUnit(), CEvaluationNodeOperator::getUnit(), CEvaluationNodeDelay::getXPPString(), CEvaluationNodeFunction::getXPPString(), printRecursively(), CEvaluationNodeObject::setData(), CEvaluationNodeObject::setObjectValuePtr(), CEvaluationNodeCall::setUnit(), CEvaluationNodeLogical::setUnit(), CEvaluationNodeOperator::setUnit(), CEvaluationNodeFunction::simplifyNode(), CEvaluationNodeOperator::simplifyNode(), and subType().
mValue
C_FLOAT64 CEvaluationNode::mValue protected
The numerical value of the node
Referenced by CEvaluationNodeCall::calculate(), CEvaluationNodeChoice::calculate(), CEvaluationNodeFunction::calculate(), CEvaluationNodeLogical::calculate(), CEvaluationNodeVariable::calculate(), CEvaluationNode(), CEvaluationNodeConstant::CEvaluationNodeConstant(), CEvaluationNodeDelay::CEvaluationNodeDelay(), CEvaluationNodeNumber::CEvaluationNodeNumber(), CEvaluationNodeUnit::CEvaluationNodeUnit(), CEvaluationNodeObject::compile(), CEvaluationNodeConstant::getBerkeleyMadonnaString(), CEvaluationNodeConstant::getXPPString(), CEvaluationNodeObject::mapObject(), printRecursively(), CEvaluationNodeOperator::s_divide(), CEvaluationNodeOperator::s_invalid(), CEvaluationNodeOperator::s_minus(), CEvaluationNodeOperator::s_modulus(), CEvaluationNodeOperator::s_multiply(), CEvaluationNodeOperator::s_plus(), CEvaluationNodeOperator::s_power(), CEvaluationNodeOperator::s_remainder(), and CEvaluationNodeObject::setObjectValuePtr().
mValueType
ValueType CEvaluationNode::mValueType protected
The value type of the node
Referenced by CEvaluationNodeConstant::CEvaluationNodeConstant(), CEvaluationNodeDelay::CEvaluationNodeDelay(), CEvaluationNodeFunction::CEvaluationNodeFunction(), CEvaluationNodeLogical::CEvaluationNodeLogical(), CEvaluationNodeNumber::CEvaluationNodeNumber(), CEvaluationNodeObject::CEvaluationNodeObject(), CEvaluationNodeOperator::CEvaluationNodeOperator(), CEvaluationNodeUnit::CEvaluationNodeUnit(), CEvaluationNodeCall::compile(), CEvaluationNodeFunction::compile(), getValueType(), isBoolean(), setValueType(), CEvaluationNodeCall::setValueType(), and CEvaluationNodeVariable::setValueType().
SubTypeName
const CEnumAnnotation< std::string, CEvaluationNode::SubType > CEvaluationNode::SubTypeName static
Referenced by printRecursively().
The documentation for this class was generated from the following files:
CEvaluationNode.h
CEvaluationNode.cpp