COPASI API: CEvaluationNodeObject Class Reference
CEvaluationNodeObject Class Reference
#include <CEvaluationNodeObject.h>
Public Member Functions
CEvaluationNodeObject (const bool *pValue)
CEvaluationNodeObject (const C_FLOAT64 *pValue)
CEvaluationNodeObject (const CEvaluationNodeObject &src)
CEvaluationNodeObject (const SubType &subType, const Data &data)
virtual CIssue compile () override
virtual std::string getBerkeleyMadonnaString (const std::vector< std::string > &children) const override
virtual std::string getCCodeString (const std::vector< std::string > &children) const override
virtual const Data & getData () const override
virtual std::string getDisplayString (const std::vector< std::string > &children) const override
virtual std::string getInfix (const std::vector< std::string > &children) const override
virtual std::string getMMLString (const std::vector< std::string > &children, bool expand, const std::vector< std::vector< std::string > > &variables) const override
const CRegisteredCommonName & getObjectCN () const
const CObjectInterface * getObjectInterfacePtr () const
const C_FLOAT64 * getObjectValuePtr () const
virtual CValidatedUnit getUnit (const CMathContainer &container, const std::vector< CValidatedUnit > &units) const override
virtual std::string getXPPString (const std::vector< std::string > &children) const override
bool mapObject (const std::string srcCN, const CDataContainer *pTarget)
virtual bool setData (const Data &data) override
void setObjectValuePtr (C_FLOAT64 *pObjectValue)
virtual ASTNode * toAST (const CDataModel *pDataModel) const override
virtual ~CEvaluationNodeObject ()
Public Member Functions inherited from CEvaluationNode
void addChildren (const std::vector< CEvaluationNode * > &children)
std::string buildBerkeleyMadonnaString () const
std::string buildCCodeString () const
std::string buildDisplayString () const
std::string buildInfix () const
std::string buildMMLString (bool expand, const std::vector< std::vector< std::string > > &variables) const
std::string buildXPPString () const
virtual void calculate ()
CEvaluationNode ()
CEvaluationNode (const CEvaluationNode &src)
CEvaluationNode * copyBranch () const
CEvaluationNode * copyNode (CEvaluationNode *child1, CEvaluationNode *child2) const
CEvaluationNode * copyNode (const std::vector< CEvaluationNode * > &children) const
const CEvaluationNode * findTopMinus (const std::vector< CFunctionAnalyzer::CValue > &callParameters) const
const CEvaluationTree * getTree () const
const C_FLOAT64 * getValuePointer () const
const ValueType & getValueType () const
virtual bool isBoolean () const
const MainType & mainType () const
bool operator!= (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &rhs)
bool operator< (const CEvaluationNode &right) const
bool operator== (const CEvaluationNode &right) const
void printRecursively () const
void printRecursively (std::ostream &os, int indent=0) const
void setTree (const CEvaluationTree *pTree)
virtual CValidatedUnit setUnit (const CMathContainer &container, const std::map< CEvaluationNode *, CValidatedUnit > &currentUnits, std::map< CEvaluationNode *, CValidatedUnit > &targetUnits) const
virtual CIssue setValueType (const ValueType &valueType)
virtual CEvaluationNode * simplifyNode (const std::vector< CEvaluationNode * > &children) const
CEvaluationNode * splitBranch (const CEvaluationNode *splitnode, bool left) const
const SubType & subType () const
virtual ~CEvaluationNode ()
Public Member Functions inherited from CCopasiNode< std::string >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual Data & getData ()
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Static Public Member Functions
static CEvaluationNode * fromAST (const ASTNode *pASTNode, const std::vector< CEvaluationNode * > &children)
Static Public Member Functions inherited from CEvaluationNode
static CEvaluationNode * create (const MainType &mainType, const SubType &subType, const std::string &data)
static bool isKeyword (const std::string &str)
Private Member Functions
CEvaluationNodeObject ()
Private Attributes
const CObjectInterface * mpObject
CRegisteredCommonName mRegisteredObjectCN
Additional Inherited Members
Public Types inherited from CEvaluationNode
enum class MainType {
INVALID , NUMBER , CONSTANT , OPERATOR ,
OBJECT , FUNCTION , CALL , STRUCTURE ,
CHOICE , VARIABLE , WHITESPACE , LOGICAL ,
MV_FUNCTION , VECTOR , DELAY , UNIT ,
__SIZE
}
enum class SubType {
DEFAULT , DELAY , IF , VECTOR ,
CN , DOUBLE , FUNCTION , LOG ,
OPEN , PI , POWER , EXPRESSION ,
POINTER , EXPONENTIALE , INTEGER , LOG10 ,
MULTIPLY , OR , VECTOROPEN , COMMA ,
DIVIDE , ENOTATION , EXP , True ,
XOR , RATIONALE , AND , CLOSE ,
False , MODULUS , SIN , VECTORCLOSE ,
COS , EQ , Infinity , PLUS ,
NaN , MINUS , NE , TAN ,
REMAINDER , GT , SEC , CSC ,
GE , COT , LT , LE ,
SINH , COSH , TANH , SECH ,
CSCH , COTH , ARCSIN , ARCCOS ,
ARCTAN , ARCSEC , ARCCSC , ARCCOT ,
ARCSINH , ARCCOSH , ARCTANH , ARCSECH ,
ARCCSCH , ARCCOTH , SQRT , ABS ,
FLOOR , CEIL , FACTORIAL , NOT ,
RUNIFORM , RNORMAL , MAX , MIN ,
RGAMMA , RPOISSON , SIGN , AVOGADRO ,
INVALID , __SIZE
}
enum class ValueType { Unknown , Boolean , Number , __SIZE }
Public Types inherited from CCopasiNode< std::string >
typedef std::string Data
Static Public Attributes inherited from CEvaluationNode
static const CEnumAnnotation< std::string, MainType > MainTypeName
static const CEnumAnnotation< std::string, SubType > SubTypeName
Protected Member Functions inherited from CEvaluationNode
CEvaluationNode (const MainType &type, const SubType &subType, const Data &data)
Protected Member Functions inherited from CCopasiNode< std::string >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CEvaluationNode
MainType mMainType
class CEvaluationNode::CPrecedence mPrecedence
const CEvaluationTree * mpTree
const C_FLOAT64 * mpValue
SubType mSubType
C_FLOAT64 mValue
ValueType mValueType
Protected Attributes inherited from CCopasiNode< std::string >
Data mData
Detailed Description
This is class for nodes presenting numbers used in an evaluation trees
Constructor & Destructor Documentation
CEvaluationNodeObject() [1/5]
CEvaluationNodeObject::CEvaluationNodeObject () private
Default constructor
References CEvaluationNode::mPrecedence, and PRECEDENCE_NUMBER.
Referenced by fromAST().
CEvaluationNodeObject() [2/5]
CEvaluationNodeObject::CEvaluationNodeObject (const SubType & subType, const Data & data)
Default constructor
Parameters
const SubType & subType
const Data & data
References CEvaluationNode::AVOGADRO, C_FLOAT64, CEvaluationNode::CN, CEvaluationNode::INVALID, CCopasiNode< std::string >::mData, CEvaluationNode::mPrecedence, CEvaluationNode::mpValue, mRegisteredObjectCN, CEvaluationNode::mSubType, CEvaluationNode::mValueType, CEvaluationNode::Number, CEvaluationNode::POINTER, PRECEDENCE_NUMBER, stringToPointer(), and CEvaluationNode::subType().
CEvaluationNodeObject() [3/5]
CEvaluationNodeObject::CEvaluationNodeObject (const C_FLOAT64 * pValue)
Specific constructor
Parameters
const Data & data
References CCopasiNode< std::string >::mData, CEvaluationNode::mPrecedence, CEvaluationNode::mpValue, CEvaluationNode::mValueType, CEvaluationNode::Number, pointerToString(), and PRECEDENCE_NUMBER.
CEvaluationNodeObject() [4/5]
CEvaluationNodeObject::CEvaluationNodeObject (const bool * pValue)
Specific constructor
Parameters
const Data & data
References CEvaluationNode::Boolean, C_FLOAT64, CCopasiNode< std::string >::mData, CEvaluationNode::mPrecedence, CEvaluationNode::mpValue, CEvaluationNode::mValueType, pointerToString(), and PRECEDENCE_NUMBER.
CEvaluationNodeObject() [5/5]
CEvaluationNodeObject::CEvaluationNodeObject (const CEvaluationNodeObject & src)
Copy constructor
Parameters
const CEvaluationNodeObject & src
References CEvaluationNode::mpValue.
~CEvaluationNodeObject()
CEvaluationNodeObject::~CEvaluationNodeObject () virtual
Destructor
Member Function Documentation
compile()
CIssue CEvaluationNodeObject::compile () override virtual
Compile a node;
Parameters
const CEvaluationTree * pTree
Returns
CIssue issue;
Reimplemented from CEvaluationNode.
References CEvaluationNode::AVOGADRO, C_FLOAT64, CEvaluationNode::CN, CObjectInterface::DataObject(), CIssue::Error, CCopasiNode< std::string >::getChild(), CObjectInterface::getCN(), CDataObject::getCN(), getData(), CMathContainer::getDataObject(), CMathContainer::getMathObject(), CDataModel::getModel(), CEvaluationTree::getNodeObject(), CDataObject::getObjectAncestor(), CDataObject::getObjectDataModel(), CEvaluationNode::getTree(), CDataObject::getValueObject(), CObjectInterface::getValuePointer(), CDataObject::hasFlag(), CEvaluationNode::INVALID, CCopasiNode< std::string >::mData, mpObject, CEvaluationNode::mpTree, CEvaluationNode::mpValue, mRegisteredObjectCN, CEvaluationNode::mSubType, CEvaluationNode::mValue, CIssue::ObjectNotFound, CEvaluationNode::POINTER, stringToPointer(), CIssue::StructureInvalid, CIssue::Success, CIssue::TooManyArguments, CDataObject::ValueDbl, and CIssue::ValueNotFound.
Referenced by CDerive::deriveBranch(), and CModel::prepareElasticity().
fromAST()
CEvaluationNode * CEvaluationNodeObject::fromAST (const ASTNode * pASTNode, const std::vector< CEvaluationNode * > & children) static
Creates a new CEvaluationNodeCall from an ASTNode and the given children
Parameters
const ASTNode* pNode
const std::vector< CEvaluationNode * > & children
Returns
CEvaluationNode * pCretedNode
References CEvaluationNode::AVOGADRO, CEvaluationNodeObject(), and CEvaluationNode::CN.
Referenced by CEvaluationTree::fromAST().
getBerkeleyMadonnaString()
std::string CEvaluationNodeObject::getBerkeleyMadonnaString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes in Berkeley Madonna format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CCopasiNode< std::string >::mData.
getCCodeString()
std::string CEvaluationNodeObject::getCCodeString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes in C.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CCopasiNode< std::string >::mData.
getData()
const CEvaluationNode::Data & CEvaluationNodeObject::getData () const override virtual
Retrieve the value of the node.
Returns
const Data & value
Reimplemented from CCopasiNode< std::string >.
References CEvaluationNode::CN, CCopasiNode< std::string >::mData, mRegisteredObjectCN, CEvaluationNode::mSubType, and CEvaluationNode::POINTER.
Referenced by compile(), SBMLImporter::doMapping(), CReaction::object2variable(), SBMLImporter::renameMassActionParameters(), and SBMLImporter::setCorrectUsage().
getDisplayString()
std::string CEvaluationNodeObject::getDisplayString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CDataObject::getObjectDisplayName(), mpObject, and mRegisteredObjectCN.
getInfix()
std::string CEvaluationNodeObject::getInfix (const std::vector< std::string > & children) const override virtual
Retrieve the infix value of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CEvaluationNode::CN, CCopasiNode< std::string >::mData, mRegisteredObjectCN, CEvaluationNode::mSubType, and CEvaluationNode::POINTER.
getMMLString()
std::string CEvaluationNodeObject::getMMLString (const std::vector< std::string > & children, bool expand, const std::vector< std::vector< std::string > > & variables) const override virtual
Build the MathML string
Parameters
const std::vector< std::string > & children
bool expand = true
const std::vector< std::vector< std::string > > & variables
Returns
std::string MMLString
Reimplemented from CEvaluationNode.
References CObjectInterface::DataObject(), CMathMl::getMMLName(), and mpObject.
getObjectCN()
const CRegisteredCommonName & CEvaluationNodeObject::getObjectCN () const
Retrieve the CN of the referred object.
Returns
const CRegisteredCommonName & objectCN
References mRegisteredObjectCN.
Referenced by CSBMLExporter::checkForUnsupportedObjectReferences(), CEvaluationTree::containsCN(), CMathContainer::copyBranch(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), CExpression::createInitialExpression(), CDerive::deriveBranch(), CODEExporter::exportExpression(), CSBMLExporter::findModelEntityDependencies(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CModelMerging::mergeInExpression(), CSBMLExporter::replaceSpeciesReferences(), toAST(), and CModelExpansion::updateExpression().
getObjectInterfacePtr()
const CObjectInterface * CEvaluationNodeObject::getObjectInterfacePtr () const
Retrieve the pointer to the referred object interface
Returns
const CObjectInterface * pObjectInterface
References mpObject.
Referenced by CMathExpression::compile(), CMathContainer::copyBranch(), CDerive::deriveBranch(), CModelExpansion::expressionContainsObject(), CUnitValidator::getUnits(), CEvaluationTree::mapObjectNodes(), CModelExpansion::replaceInExpression(), CUnitValidator::setUnits(), and CModelExpansion::updateExpression().
getObjectValuePtr()
const C_FLOAT64 * CEvaluationNodeObject::getObjectValuePtr () const
Retrieve the pointer to the value of the referred object
Returns
const C_FLOAT64 * pObjectValue
References CEvaluationNode::mpValue.
Referenced by CMathExpression::convertToInitialExpression(), and CMathContainer::copyBranch().
getUnit()
CValidatedUnit CEvaluationNodeObject::getUnit (const CMathContainer & container, const std::vector< CValidatedUnit > & units) const override virtual
Figure out the appropriate CUnit to use, based on the child nodes. This sets the default, appropriate for many cases, as Dimensionless
Parameters
const CMathContainer & container
const std::vector< CUnit > & units
Returns
CUnit unit
Reimplemented from CEvaluationNode.
References CObjectInterface::getDataObject(), CMathContainer::getMathObject(), CDataObject::getUnits(), CValidatedUnit::merge(), and CEvaluationNode::mpValue.
getXPPString()
std::string CEvaluationNodeObject::getXPPString (const std::vector< std::string > & children) const override virtual
Retrieve the display string of the node and its eventual child nodes in XPPAUT format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
References CCopasiNode< std::string >::mData.
mapObject()
bool CEvaluationNodeObject::mapObject (const std::string srcCN, const CDataContainer * pTarget)
Map object whose CN starts with srcSN to children of the target container
Parameters
const std::string srcCN
const CDataContainer * pTarget
Returns
bool success;
References C_FLOAT64, CObjectInterface::DataObject(), CDataContainer::getObject(), CDataObject::getValueObject(), CObjectInterface::getValuePointer(), CDataObject::hasFlag(), mpObject, CEvaluationNode::mpValue, mRegisteredObjectCN, CEvaluationNode::mValue, and CDataObject::ValueDbl.
Referenced by CEvaluationTree::mapObjectNodes().
setData()
bool CEvaluationNodeObject::setData (const Data & data) override virtual
Set the data of the Node.
Parameters
const Data & data
Returns
bool success
References CEvaluationNode::CN, CCopasiNode< std::string >::mData, mRegisteredObjectCN, and CEvaluationNode::mSubType.
Referenced by CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), CExpression::createInitialExpression(), CModelMerging::mergeInExpression(), SBMLImporter::renameMassActionParameters(), CModelExpansion::replaceInExpression(), and CModelExpansion::updateExpression().
setObjectValuePtr()
void CEvaluationNodeObject::setObjectValuePtr (C_FLOAT64 * pObjectValue)
Set the pointer to the value of the referred object
Parameters
C_FLOAT64 * pObjectValue
References CEvaluationNode::CN, CCopasiNode< std::string >::mData, CEvaluationNode::mpValue, CEvaluationNode::mSubType, CEvaluationNode::mValue, CEvaluationNode::POINTER, and pointerToString().
Referenced by CMathExpression::convertToInitialExpression().
toAST()
ASTNode * CEvaluationNodeObject::toAST (const CDataModel * pDataModel) const override virtual
Converts this node to an ASTNode.
Returns
ASTNode the resulting ASTNode.
Reimplemented from CEvaluationNode.
References CObjectInterface::DataObject(), fatalError, CCopasiNode< std::string >::getChild(), CCopasiParameter::getCN(), CModel::getInitialTime(), getObjectCN(), CDataObject::getObjectFromCN(), CDataObject::getObjectName(), CDataObject::getObjectParent(), CModelEntity::getSBMLId(), CReaction::getSBMLId(), CDataObject::hasFlag(), MCSBML, CCopasiNode< std::string >::mData, mRegisteredObjectCN, CDataObject::Reference, CEvaluationNode::toAST(), and CCopasiMessage::WARNING.
Member Data Documentation
mpObject
const CObjectInterface* CEvaluationNodeObject::mpObject private
Pointer to the object
Referenced by compile(), getDisplayString(), getMMLString(), getObjectInterfacePtr(), and mapObject().
mRegisteredObjectCN
CRegisteredCommonName CEvaluationNodeObject::mRegisteredObjectCN private
The registered object name to track eventual renaming.
Referenced by CEvaluationNodeObject(), compile(), getData(), getDisplayString(), getInfix(), getObjectCN(), mapObject(), setData(), and toAST().
The documentation for this class was generated from the following files:
CEvaluationNodeObject.h
CEvaluationNodeObject.cpp