COPASI API: CMathDerive Class Reference
CMathDerive Class Reference
#include <CMathDerive.h>
Public Member Functions
CMathDerive (const CMathContainer *pContainer, size_t fun, size_t var)
const CEvaluationNode * getRootNode ()
just for testing
Private Member Functions
void initOneVar (size_t fun, size_t var)
Private Attributes
const CMathContainer * mpContainer
CEvaluationNode * mpRootNode
Detailed Description
This class contains all the information that is needed to calculate derivatives in a CMathContainer. When initialised (through a constructor) it sets up the expression for symbolic derivatives and also determines whether the derivative is constant (so that it is not reevaluated during simulations)
Constructor & Destructor Documentation
CMathDerive()
CMathDerive::CMathDerive (const CMathContainer * pContainer, size_t fun, size_t var)
References initOneVar().
Member Function Documentation
getRootNode()
const CEvaluationNode * CMathDerive::getRootNode ()
just for testing
References mpRootNode.
initOneVar()
void CMathDerive::initOneVar (size_t fun, size_t var) private
References CDerive::deriveBranch(), CMathObject::getExpressionPtr(), CMathContainer::getMathObject(), CEvaluationTree::getRoot(), CMathContainer::getValues(), max, mpContainer, and CVectorCore< CType >::size().
Referenced by CMathDerive().
Member Data Documentation
mpContainer
const CMathContainer* CMathDerive::mpContainer private
Referenced by initOneVar().
mpRootNode
CEvaluationNode* CMathDerive::mpRootNode private
Referenced by getRootNode().
The documentation for this class was generated from the following files:
CMathDerive.h
CMathDerive.cpp