COPASI API: CLocaleString Class Reference
CLocaleString Class Reference
#include <CLocaleString.h>
Public Types
typedef char lchar
Public Member Functions
const lchar * c_str () const
CLocaleString ()
CLocaleString (const CLocaleString &src)
CLocaleString (const lchar *str)
CLocaleString & operator= (const CLocaleString &rhs)
CLocaleString & operator= (const lchar *str)
std::string toUtf8 () const
~CLocaleString ()
Static Public Member Functions
static CLocaleString fromUtf8 (const std::string &utf8)
Private Attributes
lchar * mpStr
Member Typedef Documentation
lchar
typedef char CLocaleString::lchar
Constructor & Destructor Documentation
CLocaleString() [1/3]
CLocaleString::CLocaleString ()
Referenced by fromUtf8().
CLocaleString() [2/3]
CLocaleString::CLocaleString (const lchar * str)
CLocaleString() [3/3]
CLocaleString::CLocaleString (const CLocaleString & src)
~CLocaleString()
CLocaleString::~CLocaleString ()
References free(), and mpStr.
Member Function Documentation
c_str()
const CLocaleString::lchar * CLocaleString::c_str () const
References mpStr.
Referenced by CModel::createEventsForTimeseries().
fromUtf8()
CLocaleString CLocaleString::fromUtf8 (const std::string & utf8) static
References CLocaleString(), and free().
Referenced by CExperimentSet::compile(), CDirEntry::copy(), CExperimentFileInfo::countLines(), CDirEntry::createDir(), CModel::createEventsForTimeseries(), CDirEntry::createTmpName(), CDirEntry::exist(), CDataModel::exportMathModel(), CSBMLExporter::exportModel(), CSEDMLExporter::exportModelAndTasks(), COptions::getEnvironmentVariable(), CExperiment::guessColumnNumber(), CDataModel::importSEDML(), CReadConfig::initFileBuffer(), CDirEntry::isDir(), CDirEntry::isFile(), CDirEntry::isReadable(), CDirEntry::isWritable(), CCopasiXMLInterface::load(), CDataModel::loadFromFile(), CDataModel::loadModel(), CDirEntry::move(), CReport::open(), CExperiment::readColumnNames(), SBMLImporter::readSBML(), SEDMLImporter::readSEDML(), CDirEntry::remove(), CDirEntry::removeFiles(), CTimeSeries::save(), CCopasiXMLInterface::save(), CDataModel::saveModelParameterSets(), and CModelVersionHierarchy::updateVersionXML().
operator=() [1/2]
CLocaleString & CLocaleString::operator= (const CLocaleString & rhs)
References free(), and mpStr.
operator=() [2/2]
CLocaleString & CLocaleString::operator= (const lchar * str)
References free(), and mpStr.
toUtf8()
std::string CLocaleString::toUtf8 () const
References free(), and mpStr.
Referenced by CDirEntry::createTmpName(), COptions::getCopasiDir(), COptions::getEnvironmentVariable(), COptions::getPWD(), COptions::init(), and CDirEntry::removeFiles().
Member Data Documentation
mpStr
lchar* CLocaleString::mpStr private
Referenced by c_str(), operator=(), toUtf8(), and ~CLocaleString().
The documentation for this class was generated from the following files:
CLocaleString.h
CLocaleString.cpp