COPASI API: CQBaseWidget Class Reference
CQBaseWidget Class Reference abstract
#include <CQBaseWidget.h>
Public Member Functions
CQBaseWidget (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=Qt::WindowFlags())
bool isSliderActive () const
int scaleFactor ()
void setSliderActive (const bool &active)
virtual void sliderMoved (int column, int row)=0
virtual ~CQBaseWidget ()
Protected Slots
void setSlider ()
Protected Attributes
int mScaleFactor
bool mSliderActive
Constructor & Destructor Documentation
CQBaseWidget()
CQBaseWidget::CQBaseWidget (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = Qt::WindowFlags())
References mSliderActive, setSlider(), and setSliderActive().
~CQBaseWidget()
CQBaseWidget::~CQBaseWidget () virtual
Member Function Documentation
isSliderActive()
bool CQBaseWidget::isSliderActive () const
References mSliderActive.
scaleFactor()
int CQBaseWidget::scaleFactor ()
References mScaleFactor.
setSlider
void CQBaseWidget::setSlider () protected slot
References mScaleFactor, mSliderActive, and sliderMoved().
Referenced by CQBaseWidget().
setSliderActive()
void CQBaseWidget::setSliderActive (const bool & active)
References mSliderActive.
Referenced by CQBaseWidget().
sliderMoved()
virtual void CQBaseWidget::sliderMoved (int column, int row) pure virtual
Implemented in CQBarChart.
Referenced by setSlider().
Member Data Documentation
mScaleFactor
int CQBaseWidget::mScaleFactor protected
Referenced by scaleFactor(), and setSlider().
mSliderActive
bool CQBaseWidget::mSliderActive protected
Referenced by CQBaseWidget(), CQBarChart::getColSliderPos(), CQBarChart::getRowSliderPos(), isSliderActive(), setSlider(), CQBarChart::setSlider(), setSliderActive(), and CQBarChart::sliderMoved().
The documentation for this class was generated from the following files:
CQBaseWidget.h
CQBaseWidget.cpp