COPASI API: CMathUpdateSequence Class Reference
CMathUpdateSequence Class Reference
#include <CMathUpdateSequence.h>
Public Types
typedef CObjectInterface *const * const_iterator
typedef CObjectInterface ** iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
void clear ()
CMathUpdateSequence (CMathContainer *pContainer=NULL)
CMathUpdateSequence (const CMathUpdateSequence &src, CMathContainer *pContainer=NULL)
bool empty () const
iterator end ()
const_iterator end () const
void insert (const iterator &loc, const CObjectInterface *pObject)
template<typename InputIterator >
void insert (const iterator &loc, InputIterator first, InputIterator last)
CMathUpdateSequence & operator= (const CMathUpdateSequence &rhs)
CMathUpdateSequence & operator= (const std::vector< CObjectInterface * > &rhs)
void setMathContainer (CMathContainer *pContainer)
const size_t & size () const
virtual ~CMathUpdateSequence ()
Private Attributes
CMathContainer * mpContainer
Additional Inherited Members
Protected Types inherited from CVectorCore< CType >
typedef CType elementType
Protected Member Functions inherited from CVector< CObjectInterface * >
void copy (const CVectorCore< CObjectInterface * > &rhs)
CVector (const CVector< CObjectInterface * > &src)
CVector (const CVectorCore< CObjectInterface * > &src)
CVector (size_t size=0)
CVector< CObjectInterface * > & operator= (const CObjectInterface * &value)
CVector< CObjectInterface * > & operator= (const CVector< CObjectInterface * > &rhs)
CVector< CObjectInterface * > & operator= (const CVectorCore< CObjectInterface * > &rhs)
void resize (size_t size, const bool &copy=false)
virtual ~CVector ()
Protected Member Functions inherited from CVectorCore< CType >
bool applyPivot (const CVectorCore< size_t > &pivot)
CType * array ()
const CType * array () const
CType * begin ()
const CType * begin () const
CVectorCore (const size_t &size=0, CType *buffer=NULL)
CType * end ()
const CType * end () const
void initialize (const CVectorCore< CType > &src)
void initialize (const size_t &size, const CType *vector)
CType & operator() (const size_t &row)
const CType & operator() (const size_t &row) const
CVectorCore< CType > & operator= (const CType &value)
CVectorCore< CType > & operator= (const CVectorCore< CType > &rhs)
bool operator== (const CVectorCore< CType > &rhs) const
CType & operator[] (const size_t &row)
const CType & operator[] (const size_t &row) const
size_t size () const
virtual ~CVectorCore ()
Protected Attributes inherited from CVectorCore< CType >
CType * mpBuffer
size_t mSize
Member Typedef Documentation
const_iterator
typedef CObjectInterface* const* CMathUpdateSequence::const_iterator
iterator
typedef CObjectInterface** CMathUpdateSequence::iterator
Constructor & Destructor Documentation
CMathUpdateSequence() [1/2]
CMathUpdateSequence::CMathUpdateSequence (CMathContainer * pContainer = NULL)
Default Constructor
Parameters
CMathContainer * pContainer (default: NULL)
References setMathContainer().
CMathUpdateSequence() [2/2]
CMathUpdateSequence::CMathUpdateSequence (const CMathUpdateSequence & src, CMathContainer * pContainer = NULL)
Copy Constructor
Parameters
const CMathUpdateSequence & src
CMathContainer * pContainer (default: NULL)
References mpContainer, and setMathContainer().
~CMathUpdateSequence()
CMathUpdateSequence::~CMathUpdateSequence () virtual
Destructor
References CMathContainer::deregisterUpdateSequence(), and mpContainer.
Member Function Documentation
begin() [1/2]
CMathUpdateSequence::iterator CMathUpdateSequence::begin ()
Referenced by CMathContainer::applyUpdateSequence(), CModel::buildInitialRefreshSequence(), CMathContainer::calculateElasticityDependencies(), CMathContainer::calculateJacobianDependencies(), CMathContainer::createApplyInitialValuesSequence(), CODEExporter::exportObjectNodesFromModel(), CMathDependencyGraph::getUpdateSequence(), operator=(), CTimeSensMethod::printUpdateSeq(), CMathContainer::relocateUpdateSequence(), CStochMethod::setupDependencyGraph(), and CStochasticRungeKuttaRI5::start().
begin() [2/2]
CMathUpdateSequence::const_iterator CMathUpdateSequence::begin () const
clear()
void CMathUpdateSequence::clear ()
References CVector< CObjectInterface * >::resize().
Referenced by CMathContainer::allocate(), CScanMethod::init(), COptProblem::initialize(), CSlider::setSliderObject(), CStochDirectMethod::start(), CStochMethod::start(), CTrajAdaptiveSA::start(), and CTrajectoryMethodDsaLsodar::start().
empty()
bool CMathUpdateSequence::empty () const
Referenced by CMathContainer::analyzeRoots(), CMathContainer::areObjectsConstant(), CMathContainer::compile(), CMathEvent::createUpdateSequences(), CMathDependencyGraph::dependsOn(), and CStochasticRungeKuttaRI5::start().
end() [1/2]
CMathUpdateSequence::iterator CMathUpdateSequence::end ()
Referenced by CMathContainer::applyUpdateSequence(), CMathContainer::calculateElasticityDependencies(), CMathContainer::calculateJacobianDependencies(), CMathContainer::createApplyInitialValuesSequence(), CODEExporter::exportObjectNodesFromModel(), CMathDependencyGraph::getUpdateSequence(), operator=(), CTimeSensMethod::printUpdateSeq(), CMathContainer::relocateUpdateSequence(), CStochMethod::setupDependencyGraph(), and CStochasticRungeKuttaRI5::start().
end() [2/2]
CMathUpdateSequence::const_iterator CMathUpdateSequence::end () const
insert() [1/2]
void CMathUpdateSequence::insert (const iterator & loc, const CObjectInterface * pObject)
Referenced by CMathContainer::calculateElasticityDependencies(), CMathContainer::calculateJacobianDependencies(), CMathContainer::createApplyInitialValuesSequence(), CMathDependencyGraph::dependsOn(), CMathDependencyGraph::hasCircularDependencies(), and CStochasticRungeKuttaRI5::start().
insert() [2/2]
template<typename InputIterator > void CMathUpdateSequence::insert (const iterator & loc, InputIterator first, InputIterator last) inline
References C_FLOAT64, CCopasiMessage::EXCEPTION, max, MCopasiBase, and min.
operator=() [1/2]
CMathUpdateSequence & CMathUpdateSequence::operator= (const CMathUpdateSequence & rhs)
Assignment operator
Parameters
const CMathUpdateSequence & rhs
References mpContainer, CVector< CType >::operator=(), and setMathContainer().
operator=() [2/2]
CMathUpdateSequence & CMathUpdateSequence::operator= (const std::vector< CObjectInterface * > & rhs)
Assignment operator
Parameters
const std::vector< CObjectInterface * > & rhs
References begin(), end(), and CVector< CObjectInterface * >::resize().
setMathContainer()
void CMathUpdateSequence::setMathContainer (CMathContainer * pContainer)
Set the math container
Parameters
CMathContainer * pContainer
References CMathContainer::deregisterUpdateSequence(), mpContainer, and CMathContainer::registerUpdateSequence().
Referenced by CMathUpdateSequence(), CMathContainer::deregisterUpdateSequence(), CMathDependencyGraph::getUpdateSequence(), operator=(), and CMathContainer::registerUpdateSequence().
size()
const size_t & CMathUpdateSequence::size () const
Referenced by CMCAMethod::isValidProblem(), and CStochDirectMethod::start().
Member Data Documentation
mpContainer
CMathContainer* CMathUpdateSequence::mpContainer private
Referenced by CMathUpdateSequence(), operator=(), setMathContainer(), and ~CMathUpdateSequence().
The documentation for this class was generated from the following files:
CMathUpdateSequence.h
CMathUpdateSequence.cpp