COPASI API: CVectorCore< CType > Class Template Reference
CVectorCore< CType > Class Template Reference
#include <CVector.h>
Public Types
typedef CType elementType
Public Member Functions
bool applyPivot (const CVectorCore< size_t > &pivot)
CType * array ()
const CType * array () const
CType * begin ()
const CType * begin () const
CVectorCore (const size_t &size=0, CType *buffer=NULL)
CType * end ()
const CType * end () const
void initialize (const CVectorCore< CType > &src)
void initialize (const size_t &size, const CType *vector)
CType & operator() (const size_t &row)
const CType & operator() (const size_t &row) const
CVectorCore< CType > & operator= (const CType &value)
CVectorCore< CType > & operator= (const CVectorCore< CType > &rhs)
bool operator== (const CVectorCore< CType > &rhs) const
CType & operator[] (const size_t &row)
const CType & operator[] (const size_t &row) const
size_t size () const
virtual ~CVectorCore ()
Protected Attributes
CType * mpBuffer
size_t mSize
Private Member Functions
CVectorCore (const CVectorCore< CType > &src)
Friends
std::ostream & operator<< (std::ostream &os, const CVectorCore< CType > &A)
Member Typedef Documentation
elementType
template<class CType > typedef CType CVectorCore< CType >::elementType
Constructor & Destructor Documentation
CVectorCore() [1/2]
template<class CType > CVectorCore< CType >::CVectorCore (const size_t & size = 0, CType * buffer = NULL) inline
Specific constructor
Parameters
const size_t & size (default: 0)
CType * buffer (default: NULL)
CVectorCore() [2/2]
template<class CType > CVectorCore< CType >::CVectorCore (const CVectorCore< CType > & src) inline private
Copy constructor. Note, this is intentionally private as this constructor must not be accessed, i.e., do not declare any class or method as friend.
Parameters
const CVectorCore< CType > & src
~CVectorCore()
template<class CType > virtual CVectorCore< CType >::~CVectorCore () inline virtual
Destructor.
Member Function Documentation
applyPivot()
template<class CType > bool CVectorCore< CType >::applyPivot (const CVectorCore< size_t > & pivot) inline
Reorder the elements according to the provided pivots
Parameters
const CVectorCore<size_t> & pivot
Returns
bool success
References CVectorCore< CType >::mpBuffer, CVectorCore< CType >::mSize, and CVectorCore< CType >::size().
Referenced by CExperiment::read(), and CEigen::stabilityAnalysis().
array() [1/2]
template<class CType > CType* CVectorCore< CType >::array () inline
Retrieve the array of the vector elements. This is suitable for interfacing with clapack routines.
Returns
CType * array
References CVectorCore< CType >::mpBuffer.
Referenced by CStepMatrix::add(), CMathContainer::addAnalysisEvent(), CMathContainer::addAnalysisObject(), CMathContainer::allocate(), CSteadyStateMethod::allPositive(), CMathContainer::analyzeRoots(), CLinkMatrix::applyColumnPivot(), CMathContainer::applyInitialValues(), CLinkMatrix::applyRowPivot(), CStepMatrix::begin(), CLinkMatrix::build(), CSSAMethod::buildExtremeCurrents(), CBitPatternMethod::buildFluxModes(), CBitPatternTreeMethod::buildFluxModes(), CModel::buildRedStoi(), CModel::buildStateTemplate(), CModel::buildUserOrder(), CFitProblem::calcEigen(), CEigen::calcEigenValues(), COptMethodPS::calcFValVariance(), CLyapWolfMethod::calculate(), CFitProblem::calculate(), CTimeSensMethod::calculate_dAssignments_dPar(), CTimeSensMethod::calculate_dAssignments_dState(), CTimeSensMethod::calculate_dInitialState_dPar(), CTimeSensMethod::calculate_dRate_dPar(), CLNAMethod::calculateCovarianceMatrixReduced(), CFitProblem::calculateCrossValidation(), CHybridMethod::calculateDerivative(), CMathContainer::calculateElasticityDependencies(), CMathContainer::calculateJacobian(), CMathContainer::calculateJacobianDependencies(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CTrajectoryMethodDsaLsodar::calculatePropensities(), CMathContainer::calculateRootDerivatives(), CMathContainer::calculateRootJacobian(), CStochasticRungeKuttaRI5::calculateStateVariables(), CExperimentSet::calculateStatistics(), COptProblem::calculateStatistics(), CFitProblem::calculateStatistics(), CTrajectoryMethodDsaLsodar::calculateTotalPropensity(), CMCAMethod::calculateUnscaledConcentrationCC(), CMCAMethod::calculateUnscaledElasticities(), CExperiment::calculateWeights(), CExperiment::CExperiment(), CFluxScore::CFluxScore(), CFixLocalReactionParameters::checkModel(), CHybridMethodODE45::checkRoots(), CRungeKutta::checkRoots(), CStochDirectMethod::checkRoots(), CMCAMethod::checkSummationTheorems(), CLinkMatrix::clearPivoting(), CStepMatrix::compact(), CMathContainer::compile(), CTimeSeries::compile(), CMathEvent::compile(), CExperimentSet::compile(), CMathContainer::compileEvents(), CMathContainer::compileObjects(), CLinkMatrix::completePivotInformation(), CStepMatrix::convertRow(), CVector< CType >::copy(), CPermutation::CPermutation(), CMathContainer::createApplyInitialValuesSequence(), CMathContainer::createDelays(), CMathContainer::createDependencyGraphs(), CAnalyticsTask::createEvent(), CHybridMethodODE45::createRootMask(), CLsodaMethod2::createRootMask(), CStochasticRungeKuttaRI5::createRootMask(), CMathContainer::createSynchronizeInitialValuesSequence(), CMathContainer::createUpdateAllTransientDataValuesSequence(), CMathContainer::createUpdateSequences(), CMathDelay::createUpdateSequences(), CMathEvent::createUpdateSequences(), CMathContainer::createUpdateSimulationValuesSequence(), CMathContainer::createValueChangeProhibited(), COptMethodSRES::creation(), CCSPMethod::cspstep(), CStepMatrix::CStepMatrix(), COptMethodSteepestDescent::descentLine(), CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), CNewtonMethod::doNewtonStep(), CTrajAdaptiveSA::doSingleSSAStep(), CTrajectoryMethodDsaLsodar::doSingleStep(), CTauLeapMethod::doSingleStep(), CStochDirectMethod::doSingleStep(), CTrajAdaptiveSA::doSingleTauLeapStep(), dgemm::eval(), CLyapWolfMethod::evalF(), CTimeSensLsodaMethod::evalF(), CHybridMethodODE45::evalF(), CRadau5Method::evalF(), CTrajectoryMethodDsaLsodar::evalF(), CLsodaMethod2::evalRoot(), CAnalyticsTask::eventCallBack(), CMathContainer::fetchInitialState(), CAnalyticsTask::finish(), CMathContainer::finishResize(), CMathReaction::fire(), CMathReaction::fireMultiple(), CStochMethod::generateReactionIndex(), CBitPatternMethod::getAllUnsetBitIndexes(), CStepMatrix::getAllUnsetBitIndexes(), CStepMatrixColumn::getAllUnsetBitIndexes(), CMathContainer::getInitialValuePointer(), CMathContainer::getMathObject(), CMathContainer::getMathReaction(), CHybridMethodODE45::getReactionToFire(), CModel::getTreesWithDiscontinuities(), CBitPatternMethod::getUnsetBitIndexes(), CBitPatternTreeMethod::getUnsetBitIndexes(), CStepMatrix::getUnsetBitIndexes(), COptMethodSteepestDescent::gradient(), CKeyFactory::HashTable::HashTable(), CTimeSensLsodaMethod::hasStateChanged(), CLsodaMethod::hasStateChanged(), CRadau5Method::hasStateChanged(), COptMethodLevenbergMarquardt::hessian(), CMathContainer::ignoreDiscontinuityEvent(), CPermutation::init(), CExperiment::initExtendedTimeSeries(), CFitProblem::initialize(), CMathReaction::initialize(), CNewtonMethod::initialize(), CSteadyStateMethod::initialize(), CLyapTask::initialize(), CTSSATask::initialize(), CSensMethod::initialize(), CMathContainer::initializeAtolVector(), CModel::initializeAtolVector(), CMathContainer::initializeDiscontinuousCreationPointer(), CMathContainer::initializeEvents(), CMathContainer::initializePointers(), CExperiment::initializeScalingMatrix(), CLyapTask::initObjects(), CTimeSensMethod::initResult(), CHybridMethodODE45::integrateDeterministicPart(), CTrajectoryMethodDsaLsodar::CPartition::intialize(), CMathContainer::isStateValid(), CTimeSensLsodaMethod::maskRoots(), CHybridMethodODE45::maskRoots(), CLsodaMethod::maskRoots(), CRadau5Method::maskRoots(), CMathContainer::move(), COptMethodSRES::mutate(), CILDMMethod::newton(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), CZeroSet::operator&=(), CFluxScore::operator<(), CVectorCore< CType >::operator=(), CZeroSet::operator==(), CZeroSet::operator>=(), CZeroSet::operator|=(), COptMethodLevenbergMarquardt::optimise(), COptMethodNL2SOL::optimise(), COptMethodPraxis::optimise(), COptMethodTruncatedNewton::optimise(), CLyapWolfMethod::orthonormalize(), CTimeSeries::output(), partialSortWithPivot(), CHybridMethodODE45::partitionSystem(), CTimeSensLsodaMethod::peekAhead(), CLsodaMethod::peekAhead(), CLsodaMethod2::peekAhead(), CRadau5Method::peekAhead(), CBitPatternMethod::performRankTest(), CPermutation::pick(), CAnalyticsTask::process(), CMathContainer::processRoots(), CTimeSensTask::processStart(), CTrajectoryTask::processStart(), CMathContainer::pushAllTransientValues(), CMathContainer::pushState(), COptMethodPS::reachedStdDeviation(), CExperiment::read(), CAnalyticsTask::relativeDifferenceOfStates(), CCrossSectionTask::relativeDifferenceOfStates(), CMathDelay::relocate(), CMathEvent::relocate(), CMathReaction::relocate(), CMathContainer::relocate(), CMathContainer::relocateObject(), CMathContainer::relocateUpdateSequence(), CMathContainer::relocateValue(), CMathContainer::relocateVector(), CMathContainer::removeAnalysisEvent(), CStateTemplate::reorder(), CTrajectoryMethodDsaLsodar::CPartition::rePartition(), CMathContainer::resetNoise(), COptProblem::restore(), CMathEventQueue::rootsFound(), CStochDirectMethod::rootValue(), CCopasiXML::saveModel(), CMCAMethod::scaleMCA(), CTSSAMethod::schur(), CTSSAMethod::schur_desc(), COptMethodEP::select(), COptMethodGA::select(), CMathContainer::setCompleteInitialState(), CMathContainer::setInitialState(), CTimeSensLsodaMethod::setRootMaskType(), CLsodaMethod::setRootMaskType(), CRadau5Method::setRootMaskType(), CMathContainer::setState(), CMathEvent::setTargetValues(), CStochMethod::setupDependencyGraph(), CHybridMethod::setupMetab2React(), CStateTemplate::setUserOrder(), CModelParameterCompartment::setValue(), CVersion::setVersion(), COptMethodTruncatedNewton::sFun(), CPermutation::shuffle(), CTimeSensMethod::signalMathContainerChanged(), CTimeSensTask::signalMathContainerChanged(), CTrajectoryMethod::signalMathContainerChanged(), CTrajectoryTask::signalMathContainerChanged(), CLeastSquareSolution::solve(), sortWithPivot(), CStepMatrix::splitColumns(), CEigen::stabilityAnalysis(), CLyapWolfMethod::start(), CMathEventQueue::start(), CTimeSensLsodaMethod::start(), CHybridMethod::start(), CHybridMethodODE45::start(), CLsodaMethod::start(), CLsodaMethod2::start(), CRadau5Method::start(), CStochDirectMethod::start(), CStochMethod::start(), CTauLeapMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethod::start(), CTrajectoryMethodDsaLsodar::start(), CTSSAMethod::start(), CTimeSensLsodaMethod::stateChange(), CLsodaMethod::stateChange(), CLsodaMethod2::stateChange(), CRadau5Method::stateChange(), CStochDirectMethod::stateChange(), CLyapWolfMethod::step(), CLsodaMethod2::step(), CILDMMethod::step(), CILDMModifiedMethod::step(), CTimeSensLsodaMethod::step(), CLsodaMethod::step(), CRadau5Method::step(), CExperiment::storeExtendedTimeSeriesData(), CExperiment::sumOfSquares(), CExperiment::sumOfSquaresStore(), CTSSAMethod::sylvester(), CNewtonMethod::targetFunctionDistance(), CNewtonMethod::targetFunctionRate(), COptProblem::updateContainer(), CMathContainer::updateHistoryValues(), CSteadyStateTask::updateMatrices(), CExperiment::updateModelWithIndependentData(), CHybridMethod::updatePriorityQueue(), CTauLeapMethod::updatePropensities(), CTauLeapMethod::updateSystem(), CHybridMethodODE45::~CHybridMethodODE45(), CLsodaMethod::~CLsodaMethod(), CLsodaMethod2::~CLsodaMethod2(), CMathContainer::~CMathContainer(), CRadau5Method::~CRadau5Method(), CStepMatrix::~CStepMatrix(), CStochDirectMethod::~CStochDirectMethod(), and CTimeSensLsodaMethod::~CTimeSensLsodaMethod().
array() [2/2]
template<class CType > const CType* CVectorCore< CType >::array () const inline
Retrieve the array of the vector elements. This is suitable for interfacing with clapack routines.
Returns
const CType * array
References CVectorCore< CType >::mpBuffer.
begin() [1/2]
template<class CType > CType* CVectorCore< CType >::begin () inline
Retrieve the a pointer to the first vector element.
Returns
CType * pFirst
References CVectorCore< CType >::mpBuffer.
Referenced by COptProblem::adjustStartValuesForIntervals(), CRootFinder::brentRootValue(), CEvaluationTree::buildCalculationSequence(), CStochasticRungeKuttaRI5::buildStage1(), CStochasticRungeKuttaRI5::buildStage2(), CStochasticRungeKuttaRI5::buildStage3(), CEvaluationTree::calculate(), CMathObject::calculateCorrectedPropensity(), CMathObject::calculateExtensiveReactionRate(), CStochasticRungeKuttaRI5::calculateSmallestPhysicalValue(), CStochasticRungeKuttaRI5::calculateStateVariables(), CMathObject::calculateTransitionTime(), CRootFinder::checkRoots(), CMathObject::compileDependentMass(), CMathObject::compilePropensity(), CMathObject::compileTotalMass(), CMathObject::compileTransitionTime(), CMathObject::createExtensiveReactionNoiseExpression(), CMathObject::createExtensiveReactionRateExpression(), CTimeSensLsodaMethod::createRootMask(), CLsodaMethod::createRootMask(), CLsodaMethod2::createRootMask(), CRadau5Method::createRootMask(), CStochasticRungeKuttaRI5::createRootMask(), CMathEvent::createUpdateSequences(), CLsodaMethod2::destroyRootMask(), CStochasticRungeKuttaRI5::destroyRootMask(), CStochDirectMethod::doSingleStep(), CStochasticRungeKuttaRI5::evalNoise(), CStochasticRungeKuttaRI5::evalRate(), CStochasticRungeKuttaRI5::evalRoot(), CMathContainer::fetchState(), CStochasticRungeKuttaRI5::generateRandomNumbers(), CMathContainer::getValuePointer(), CMathContainer::ignoreDiscontinuityEvent(), CScanMethod::init(), CSteadyStateMethod::initialize(), CStochasticRungeKuttaRI5::internalStep(), CSteadyStateMethod::isEquilibrium(), CMathContainer::map(), CMathContainer::pushInitialState(), CMathObject::relocate(), COptProblem::setParameters(), CTimeSensLsodaMethod::setRootMaskType(), CLsodaMethod::setRootMaskType(), CRadau5Method::setRootMaskType(), COptProblem::setSolution(), CFitProblem::setSolution(), CLeastSquareSolution::solve(), CLsodaMethod2::start(), CStochasticRungeKuttaRI5::start(), CNewtonMethod::targetFunctionDistance(), CNewtonMethod::targetFunctionRate(), and CXMLHandlerFactory::~CXMLHandlerFactory().
begin() [2/2]
template<class CType > const CType* CVectorCore< CType >::begin () const inline
Retrieve the a pointer to the first vector element.
Returns
const CType * pFirst
References CVectorCore< CType >::mpBuffer.
end() [1/2]
template<class CType > CType* CVectorCore< CType >::end () inline
Retrieve the a pointer beyond the last vector element.
Returns
CType * pEnd
References CVectorCore< CType >::mpBuffer, and CVectorCore< CType >::mSize.
Referenced by CRootFinder::brentRootValue(), CEvaluationTree::buildCalculationSequence(), CStochasticRungeKuttaRI5::buildStage2(), CStochasticRungeKuttaRI5::buildStage3(), CEvaluationTree::calculate(), CMathObject::calculateCorrectedPropensity(), CMathObject::calculateExtensiveReactionRate(), CStochasticRungeKuttaRI5::calculateSmallestPhysicalValue(), CStochasticRungeKuttaRI5::calculateStateVariables(), CMathObject::calculateTransitionTime(), CRootFinder::checkRoots(), CTimeSensLsodaMethod::createRootMask(), CLsodaMethod::createRootMask(), CLsodaMethod2::createRootMask(), CRadau5Method::createRootMask(), CStochasticRungeKuttaRI5::createRootMask(), CLsodaMethod2::destroyRootMask(), CStochasticRungeKuttaRI5::destroyRootMask(), CStochDirectMethod::doSingleStep(), CMathContainer::fetchState(), CMathContainer::getValuePointer(), CStochasticRungeKuttaRI5::internalStep(), CSteadyStateMethod::isEquilibrium(), CMathContainer::map(), CMathContainer::pushInitialState(), CMathObject::relocate(), COptProblem::setParameters(), CTimeSensLsodaMethod::setRootMaskType(), CLsodaMethod::setRootMaskType(), CRadau5Method::setRootMaskType(), CFitProblem::setSolution(), CLeastSquareSolution::solve(), CLsodaMethod2::start(), CStochasticRungeKuttaRI5::start(), CNewtonMethod::targetFunctionDistance(), CNewtonMethod::targetFunctionRate(), and CXMLHandlerFactory::~CXMLHandlerFactory().
end() [2/2]
template<class CType > const CType* CVectorCore< CType >::end () const inline
Retrieve the a pointer beyond the last vector element.
Returns
const CType * End
References CVectorCore< CType >::mpBuffer, and CVectorCore< CType >::mSize.
initialize() [1/2]
template<class CType > void CVectorCore< CType >::initialize (const CVectorCore< CType > & src) inline
Initialize the core vector to reference an other core vector.
Parameters
const size_t & size
CType * vector
References CVectorCore< CType >::mpBuffer, and CVectorCore< CType >::mSize.
initialize() [2/2]
template<class CType > void CVectorCore< CType >::initialize (const size_t & size, const CType * vector) inline
Initialize the core vector to reference an externally allocated array
Parameters
const size_t & size
CType * vector
References CVectorCore< CType >::mpBuffer, CVectorCore< CType >::mSize, and CVectorCore< CType >::size().
Referenced by CMathContainer::allocate(), CMathContainer::analyzeRoots(), CTimeSensMethod::calculate_dInitialState_dPar(), CTimeSeries::compile(), CMathEvent::compile(), CRootFinder::CRootFinder(), CStochasticRungeKuttaRI5::CStochasticRungeKuttaRI5(), CTimeSeries::CTimeSeries(), CHybridMethodODE45::evalR(), CMathContainer::finishResize(), CMathHistoryCore::getRow(), CMathContainer::ignoreDiscontinuityEvent(), CNewtonMethod::initialize(), CSteadyStateMethod::initialize(), CTSSATask::initialize(), CMathHistoryCore::initialize(), CRungeKutta::initialize(), CRootFinder::initialize(), CTimeSensMethod::initResult(), CMathContainer::move(), CMathEvent::operator=(), CHybridMethodODE45::partitionSystem(), CSteadyStateMethod::process(), CTimeSensTask::processStart(), CTrajectoryTask::processStart(), CTSSATask::processStart(), CMathEvent::relocate(), CMathContainer::relocate(), CMathContainer::relocateVector(), CMathHistoryCore::setRow(), CTimeSensMethod::signalMathContainerChanged(), CTimeSensTask::signalMathContainerChanged(), CTrajectoryMethod::signalMathContainerChanged(), CTrajectoryTask::signalMathContainerChanged(), CLyapWolfMethod::start(), CTimeSensLsodaMethod::start(), CHybridMethod::start(), CHybridMethodODE45::start(), CLsodaMethod::start(), CLsodaMethod2::start(), CRadau5Method::start(), CStochasticRungeKuttaRI5::start(), CStochDirectMethod::start(), CStochMethod::start(), CTauLeapMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethod::start(), CTrajectoryMethodDsaLsodar::start(), CCSPMethod::start(), and CTSSAMethod::start().
operator()() [1/2]
template<class CType > CType& CVectorCore< CType >::operator() (const size_t & row) inline
Retrieve a vector element using Fortan style indexing.
Parameters
const size_t & row
Returns
const CType & element
References CVectorCore< CType >::mpBuffer.
operator()() [2/2]
template<class CType > const CType& CVectorCore< CType >::operator() (const size_t & row) const inline
Retrieve a vector element using Fortan style indexing.
Parameters
const size_t & row
Returns
const CType & element
References CVectorCore< CType >::mpBuffer.
operator=() [1/2]
template<class CType > CVectorCore< CType>& CVectorCore< CType >::operator= (const CType & value) inline
Assignment operator
Parameters
const CType & value
References CVectorCore< CType >::mpBuffer, and CVectorCore< CType >::mSize.
operator=() [2/2]
template<class CType > CVectorCore< CType >& CVectorCore< CType >::operator= (const CVectorCore< CType > & rhs) inline
Assignment operator
Parameters
const CVectorCore <CType> & rhs
Returns
CVector <CType> & lhs
References CVectorCore< CType >::array(), CVectorCore< CType >::mpBuffer, and CVectorCore< CType >::mSize.
operator==()
template<class CType > bool CVectorCore< CType >::operator== (const CVectorCore< CType > & rhs) const inline
References CVectorCore< CType >::mpBuffer, and CVectorCore< CType >::mSize.
operator[]() [1/2]
template<class CType > CType& CVectorCore< CType >::operator[] (const size_t & row) inline
Retrieve an element of the vector
Parameters
const size_t & row
Returns
CType & element
References CVectorCore< CType >::mpBuffer.
Referenced by CXMLHandlerFactory::getHandler().
operator[]() [2/2]
template<class CType > const CType& CVectorCore< CType >::operator[] (const size_t & row) const inline
Retrieve an element of the vector
Parameters
const size_t & row
Returns
const CType & element
References CVectorCore< CType >::mpBuffer.
size()
template<class CType > size_t CVectorCore< CType >::size () const inline
The number of elements stored in the vector.
Returns
size_t size
References CVectorCore< CType >::mSize.
Referenced by CStepMatrix::add(), CMathContainer::addAnalysisObject(), CProcessReport::addItem(), CMathDelay::addValueObject(), CSteadyStateMethod::allPositive(), CMathContainer::analyzeRoots(), CLinkMatrix::applyColumnPivot(), CMathContainer::applyInitialValues(), applyPartialPivot(), CMatrix< CType >::applyPivot(), applyPivot(), CVectorCore< CType >::applyPivot(), CLinkMatrix::applyRowPivot(), CSSAMethod::buildExtremeCurrents(), CBitPatternMethod::buildFluxModes(), CBitPatternTreeMethod::buildFluxModes(), CModel::buildStateTemplate(), CModel::buildUserOrder(), CLyapWolfMethod::calculate(), CLNAMethod::calculateCovarianceMatrixReduced(), CFitProblem::calculateCrossValidation(), CHybridMethod::calculateDerivative(), CMathContainer::calculateElasticityDependencies(), CMathContainer::calculateJacobian(), CMathContainer::calculateJacobianDependencies(), CMathContainer::calculateRootJacobian(), CExperimentSet::calculateStatistics(), COptProblem::calculateStatistics(), CFitProblem::calculateStatistics(), CMCAMethod::calculateUnscaledElasticities(), CExperiment::calculateWeights(), CHybridMethodODE45::checkRoots(), CStochDirectMethod::checkRoots(), CLinkMatrix::clearPivoting(), CMathContainer::compile(), CExperimentSet::compile(), CMathContainer::compileObjects(), CLinkMatrix::completePivotInformation(), CVector< CType >::copy(), CPermutation::CPermutation(), CMathContainer::createApplyInitialValuesSequence(), CMathContainer::createDelays(), CMathContainer::createDependencyGraphs(), CTimeSensLsodaMethod::createRootMask(), CHybridMethodODE45::createRootMask(), CLsodaMethod::createRootMask(), CRadau5Method::createRootMask(), CMathContainer::createUpdateAllTransientDataValuesSequence(), CMathContainer::createUpdateSequences(), CMathDelay::createUpdateSequences(), CMathEvent::createUpdateSequences(), CMathContainer::createUpdateSimulationValuesSequence(), CCSPMethod::CSPImportanceIndex(), CCSPMethod::CSPParticipationIndex(), CCSPMethod::CSPradicalPointer(), CCSPMethod::cspstep(), CVector< CType >::CVector(), CSSAMethod::diag(), CSensMethod::do_target_calculation(), CNewtonMethod::doNewtonStep(), CTauLeapMethod::doSingleStep(), CTrajAdaptiveSA::doSingleTauLeapStep(), dgemm::eval(), CHybridMethodODE45::evalF(), CHybridMethodODE45::evalR(), CStochasticRungeKuttaRI5::evalRoot(), CMathContainer::fetchInitialState(), CProcessReport::finish(), CMathReaction::fire(), CMathReaction::fireMultiple(), CBitPatternMethod::getAllUnsetBitIndexes(), CStepMatrix::getAllUnsetBitIndexes(), CMathContainer::getInitialValuePointer(), CMathContainer::getMathObject(), CZeroSet::getNumberOfBits(), CZeroSet::getNumberOfUnsetBits(), CHybridMethodODE45::getReactionToFire(), CBitPatternMethod::getUnsetBitIndexes(), CBitPatternTreeMethod::getUnsetBitIndexes(), CStepMatrix::getUnsetBitIndexes(), COptMethodSteepestDescent::gradient(), CTimeSensLsodaMethod::hasStateChanged(), CLsodaMethod::hasStateChanged(), CRadau5Method::hasStateChanged(), COptMethodLevenbergMarquardt::hessian(), CMathContainer::ignoreDiscontinuityEvent(), CPermutation::init(), COptMethodLevenbergMarquardt::initialize(), COptMethodNL2SOL::initialize(), CFitProblem::initialize(), CNewtonMethod::initialize(), CSteadyStateMethod::initialize(), CVectorCore< CType >::initialize(), CSensMethod::initialize(), CRootFinder::initialize(), CMathContainer::initializeAtolVector(), CModel::initializeAtolVector(), CMathContainer::initializeDiscontinuousCreationPointer(), CMathContainer::initializeObjects(), CExperiment::initializeScalingMatrix(), CMathDerive::initOneVar(), CTimeSensMethod::initResult(), CHybridMethodODE45::integrateDeterministicPart(), CTrajectoryMethodDsaLsodar::CPartition::intialize(), CMathContainer::isStateValid(), CProcessReport::isValidHandle(), CHybridMethod::isValidProblem(), CStochMethod::isValidProblem(), CTauLeapMethod::isValidProblem(), CTrajAdaptiveSA::isValidProblem(), CTrajectoryMethodDsaLsodar::isValidProblem(), CCopasiMethod::isValidProblem(), CLinkMatrix::leftMultiply(), LUfactor(), CTimeSensLsodaMethod::maskRoots(), CHybridMethodODE45::maskRoots(), CLsodaMethod::maskRoots(), CRadau5Method::maskRoots(), CPermutation::next(), CZeroSet::operator&=(), CFluxScore::operator<(), CZeroSet::operator==(), CZeroSet::operator>=(), CZeroSet::operator|=(), CHybridMethodODE45::partitionSystem(), CTimeSensLsodaMethod::peekAhead(), CLsodaMethod::peekAhead(), CLsodaMethod2::peekAhead(), CRadau5Method::peekAhead(), CBitPatternMethod::performRankTest(), CPermutation::pick(), CExperiment::printResult(), COptProblem::printResult(), CFitProblem::printResult(), CLyapTask::process(), CSteadyStateTask::process(), CMathContainer::processRoots(), CProcessReport::progress(), CMathContainer::pushAllTransientValues(), CMathContainer::pushState(), CExperiment::read(), CAnalyticsTask::relativeDifferenceOfStates(), CCrossSectionTask::relativeDifferenceOfStates(), CMathDelay::relocate(), CMathEvent::relocate(), CMathReaction::relocate(), CMathContainer::relocate(), CMathContainer::relocateObject(), CMathContainer::relocateValue(), CMathContainer::relocateVector(), CMathContainer::removeAnalysisEvent(), CStateTemplate::reorder(), CProcessReport::reset(), CMathContainer::resetNoise(), CVector< CType >::resize(), CMCAMethod::resizeAllMatrices(), CLinkMatrix::rightMultiply(), CMathEventQueue::rootsFound(), CMCAMethod::scaleMCA(), CILDMMethod::setAnnotationM(), CMathContainer::setCompleteInitialState(), CMathContainer::setInitialState(), COptProblem::setParameters(), CFitProblem::setResidualsRequired(), COptProblem::setSolution(), CMathContainer::setState(), CMathEvent::setTargetValues(), CHybridMethod::setupDependencyGraph(), CStochMethod::setupDependencyGraph(), CHybridMethod::setupMetab2React(), CHybridMethod::setupPartition(), CHybridMethod::setupPriorityQueue(), CStateTemplate::setUserOrder(), CMathContainer::setValues(), CCSPMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectorsToNaN(), COptMethodTruncatedNewton::sFun(), CPermutation::shuffle(), CEvaluationTree::size(), CLeastSquareSolution::solve(), CEigen::stabilityAnalysis(), CLyapWolfMethod::start(), CMathEventQueue::start(), CTimeSensLsodaMethod::start(), CHybridMethod::start(), CHybridMethodODE45::start(), CLsodaMethod::start(), CLsodaMethod2::start(), CRadau5Method::start(), CStochasticRungeKuttaRI5::start(), CStochDirectMethod::start(), CStochMethod::start(), CTauLeapMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethodDsaLsodar::start(), CCSPMethod::start(), CStochDirectMethod::stateChange(), CLyapWolfMethod::step(), CLsodaMethod2::step(), CILDMMethod::step(), CTimeSensLsodaMethod::step(), CLsodaMethod::step(), CRadau5Method::step(), CNewtonMethod::targetFunctionDistance(), CSSAMethod::testForMixingStability(), COptProblem::updateContainer(), CMathContainer::updateHistoryValues(), CSteadyStateTask::updateMatrices(), CExperiment::updateModelWithIndependentData(), CHybridMethod::updatePriorityQueue(), and CProcessReport::~CProcessReport().
Friends And Related Function Documentation
operator<<
template<class CType > std::ostream& operator<< (std::ostream & os, const CVectorCore< CType > & A) friend
Output stream operator
Parameters
ostream & os
const CVector< CType > & A
Returns
ostream & os
Member Data Documentation
mpBuffer
template<class CType > CType* CVectorCore< CType >::mpBuffer protected
The array storing the vector elements
Referenced by CVectorCore< CType >::applyPivot(), CVectorCore< CType >::array(), CVectorCore< CType >::begin(), CVectorCore< CType >::end(), CVectorCore< CType >::initialize(), CVectorCore< CType >::operator()(), CVectorCore< CType >::operator=(), CVectorCore< CType >::operator==(), and CVectorCore< CType >::operator[]().
mSize
template<class CType > size_t CVectorCore< CType >::mSize protected
Size of the vector.
Referenced by CVectorCore< CType >::applyPivot(), CVectorCore< CType >::end(), CVectorCore< CType >::initialize(), CVectorCore< CType >::operator=(), CVectorCore< CType >::operator==(), and CVectorCore< CType >::size().
The documentation for this class was generated from the following file:
CVector.h