COPASI API: CXMLHandlerFactory Class Reference
CXMLHandlerFactory Class Reference
#include <CXMLHandlerFactory.h>
Public Member Functions
CXMLHandlerFactory (CXMLParser &parser, CXMLParserData &data)
CXMLHandler * getHandler (const CXMLHandler::Type &type)
~CXMLHandlerFactory ()
Private Member Functions
CXMLHandler * createHandler (const CXMLHandler::Type &type)
CXMLHandlerFactory ()
Private Member Functions inherited from CVector< CXMLHandler * >
CVector (const CVector< CXMLHandler * > &src)
CVector (const CVectorCore< CXMLHandler * > &src)
CVector (size_t size=0)
CVector< CXMLHandler * > & operator= (const CVector< CXMLHandler * > &rhs)
CVector< CXMLHandler * > & operator= (const CVectorCore< CXMLHandler * > &rhs)
CVector< CXMLHandler * > & operator= (const CXMLHandler * &value)
void resize (size_t size, const bool &copy=false)
virtual ~CVector ()
void copy (const CVectorCore< CXMLHandler * > &rhs)
Private Member Functions inherited from CVectorCore< CType >
bool applyPivot (const CVectorCore< size_t > &pivot)
CType * array ()
const CType * array () const
CType * begin ()
const CType * begin () const
CVectorCore (const size_t &size=0, CType *buffer=NULL)
CType * end ()
const CType * end () const
void initialize (const CVectorCore< CType > &src)
void initialize (const size_t &size, const CType *vector)
CType & operator() (const size_t &row)
const CType & operator() (const size_t &row) const
CVectorCore< CType > & operator= (const CType &value)
CVectorCore< CType > & operator= (const CVectorCore< CType > &rhs)
bool operator== (const CVectorCore< CType > &rhs) const
CType & operator[] (const size_t &row)
const CType & operator[] (const size_t &row) const
size_t size () const
virtual ~CVectorCore ()
Private Attributes
CXMLParserData * mpData
CXMLParser * mpParser
Private Attributes inherited from CVectorCore< CType >
CType * mpBuffer
size_t mSize
Additional Inherited Members
Private Types inherited from CVectorCore< CType >
typedef CType elementType
Constructor & Destructor Documentation
CXMLHandlerFactory() [1/2]
CXMLHandlerFactory::CXMLHandlerFactory () private
Constructor
CXMLHandlerFactory() [2/2]
CXMLHandlerFactory::CXMLHandlerFactory (CXMLParser & parser, CXMLParserData & data)
Constructor
Parameters
CXMLParser & parser
CXMLParserData & data
References CVector< CType >::operator=().
~CXMLHandlerFactory()
CXMLHandlerFactory::~CXMLHandlerFactory ()
Destructor
References CVectorCore< CType >::begin(), CVectorCore< CType >::end(), and pdelete.
Member Function Documentation
createHandler()
CXMLHandler * CXMLHandlerFactory::createHandler (const CXMLHandler::Type & type) private
Create the handler of for the given type
References CXMLHandler::AdditionalGraphicalObject, CXMLHandler::Assignment, CXMLHandler::BEFORE, CXMLHandler::BoundingBox, CXMLHandler::CallParameter, CXMLHandler::ChannelSpec, CXMLHandler::CharacterData, CXMLHandler::ColorDefinition, CXMLHandler::Comment, CXMLHandler::Compartment, CXMLHandler::CompartmentGlyph, CXMLHandler::Constant, CXMLHandler::COPASI, CXMLHandler::CubicBezier, CXMLHandler::Curve, CXMLHandler::Dimensions, CXMLHandler::Ellipse, CXMLHandler::Event, CXMLHandler::Function, CXMLHandler::GradientStop, CXMLHandler::Group, CXMLHandler::GUI, CXMLHandler::HANDLER_COUNT, CXMLHandler::Image, CXMLHandler::InitialState, CXMLHandler::KineticLaw, CXMLHandler::Layout, CXMLHandler::LinearGradient, CXMLHandler::LineEnding, CXMLHandler::LineSegment, CXMLHandler::ListOfAdditionalGraphicalObjects, CXMLHandler::ListOfAssignments, CXMLHandler::ListOfCallParameters, CXMLHandler::ListOfChannels, CXMLHandler::ListOfColorDefinitions, CXMLHandler::ListOfCompartmentGlyphs, CXMLHandler::ListOfCompartments, CXMLHandler::ListOfConstants, CXMLHandler::ListOfCurveSegments, CXMLHandler::ListOfElements, CXMLHandler::ListOfEvents, CXMLHandler::ListOfFunctions, CXMLHandler::ListOfGlobalRenderInformation, CXMLHandler::ListOfGradientDefinitions, CXMLHandler::ListOfLayouts, CXMLHandler::ListOfLineEndings, CXMLHandler::ListOfMetabGlyphs, CXMLHandler::ListOfMetaboliteReferenceGlyphs, CXMLHandler::ListOfMetabolites, CXMLHandler::ListOfModelParameterSets, CXMLHandler::ListOfModelValues, CXMLHandler::ListOfModifiers, CXMLHandler::ListOfParameterDescriptions, CXMLHandler::ListOfPlotItems, CXMLHandler::ListOfPlots, CXMLHandler::ListOfProducts, CXMLHandler::ListOfReactionGlyphs, CXMLHandler::ListOfReactions, CXMLHandler::ListOfRenderInformation, CXMLHandler::ListOfReports, CXMLHandler::ListOfSliders, CXMLHandler::ListOfStyles, CXMLHandler::ListOfSubstrates, CXMLHandler::ListOfTasks, CXMLHandler::ListOfTextGlyphs, CXMLHandler::ListOfUnitDefinitions, CXMLHandler::ListOfUnsupportedAnnotations, CXMLHandler::MathML, CXMLHandler::Metabolite, CXMLHandler::MetaboliteGlyph, CXMLHandler::MetaboliteReferenceGlyph, CXMLHandler::Method, CXMLHandler::MiriamAnnotation, CXMLHandler::Model, CXMLHandler::ModelParameter, CXMLHandler::ModelParameterGroup, CXMLHandler::ModelParameterSet, CXMLHandler::ModelValue, CXMLHandler::Modifier, mpData, mpParser, CXMLHandler::Object, CXMLHandler::Parameter, CXMLHandler::ParameterDescription, CXMLHandler::ParameterGroup, CXMLHandler::ParameterText, CXMLHandler::PlotItem, CXMLHandler::PlotSpecification, CXMLHandler::Point, CXMLHandler::Polygon, CXMLHandler::Product, CXMLHandler::RadialGradient, CXMLHandler::Reaction, CXMLHandler::ReactionGlyph, CXMLHandler::Rectangle, CXMLHandler::RenderCurve, CXMLHandler::RenderCurveElement, CXMLHandler::RenderInformation, CXMLHandler::RenderText, CXMLHandler::ReportDefinition, CXMLHandler::ReportSection, CXMLHandler::ReportTarget, CXMLHandler::SBMLMap, CXMLHandler::SBMLReference, CXMLHandler::Slider, CXMLHandler::SourceParameter, CXMLHandler::StateTemplate, CXMLHandler::StateTemplateVariable, CXMLHandler::Style, CXMLHandler::Substrate, CXMLHandler::Table, CXMLHandler::Task, CXMLHandler::TextGlyph, CXMLHandler::UnitDefinition, CXMLHandler::UNKNOWN, and CXMLHandler::UnsupportedAnnotation.
Referenced by getHandler().
getHandler()
CXMLHandler * CXMLHandlerFactory::getHandler (const CXMLHandler::Type & type)
Retrieve the handler of for the given type
References createHandler(), and CVectorCore< CType >::operator[]().
Referenced by CXMLParser::CXMLParser(), and CXMLParser::getHandler().
Member Data Documentation
mpData
CXMLParserData* CXMLHandlerFactory::mpData private
The shared elements between all element handlers of a parser
Referenced by createHandler().
mpParser
CXMLParser* CXMLHandlerFactory::mpParser private
The underlying parser.
Referenced by createHandler().
The documentation for this class was generated from the following files:
CXMLHandlerFactory.h
CXMLHandlerFactory.cpp