COPASI API: CFunction Class Reference
CFunction Class Reference
The class for handling a chemical kinetic function.
#include <CFunction.h>
Public Member Functions
bool addVariable (const std::string &name, CFunctionParameter::Role usage=CFunctionParameter::Role::VARIABLE, const CFunctionParameter::DataType &type=CFunctionParameter::DataType::FLOAT64)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
virtual const C_FLOAT64 & calcValue (const CCallParameters< C_FLOAT64 > &callParameters)
CFunction (const CFunction &src, const CDataContainer *pParent)
CFunction (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const Type &type=Function)
CFunction * createCopy () const
void createListOfParametersForMathML (std::vector< std::vector< std::string > > &env)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getKey () const
const std::string & getSBMLId () const
virtual size_t getVariableIndex (const std::string &name) const
CFunctionParameters & getVariables ()
const CFunctionParameters & getVariables () const
virtual const C_FLOAT64 & getVariableValue (const size_t &index) const
virtual bool isReadOnly () const
const TriLogic & isReversible () const
bool isSuitable (const size_t noSubstrates, const size_t noProducts, const TriLogic reversible)
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
bool operator== (const CFunction &rhs) const
virtual CIssue setInfix (const std::string &infix)
void setReversible (const TriLogic &reversible)
void setSBMLId (const std::string &id)
std::pair< CFunction *, CFunction * > splitFunction (const CEvaluationNode *node, const std::string &name1, const std::string &name2) const
virtual CData toData () const
virtual std::string writeMathML (const std::vector< std::vector< std::string > > &variables, bool expand=true, bool fullExpand=true) const
virtual void writeMathML (std::ostream &out, size_t l=0) const
virtual ~CFunction ()
Public Member Functions inherited from CEvaluationTree
bool calls (std::set< std::string > &list) const
CEvaluationTree (const CEvaluationTree &src, const CDataContainer *pParent)
CEvaluationTree (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const Type &type=Function)
virtual CIssue compile ()
bool containsCN (const DataObjectSet &elements) const
std::string::size_type getErrorPosition () const
const std::string & getInfix () const
const std::vector< CEvaluationNode * > & getNodeList () const
virtual const CObjectInterface * getNodeObject (const CCommonName &CN) const
CEvaluationNode * getRoot ()
const CEvaluationNode * getRoot () const
const CEvaluationTree::Type & getType () const
bool hasCircularDependency () const
bool hasDiscontinuity () const
bool isBoolean () const
bool mapObjectNodes (const CDataContainer *pSrc, const CDataContainer *pTarget)
bool operator== (const CEvaluationTree &rhs) const
virtual bool setRoot (CEvaluationNode *pRootNode)
bool setTree (const ASTNode &pRootNode, bool isFunction)
size_t size () const
virtual ASTNode * toAST (const CDataModel *pDataModel) const
CIssue updateTree ()
virtual ~CEvaluationTree ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static bool completeFunctionList (std::vector< const CFunction * > &list, const size_t &added=0)
static CFunction * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CEvaluationTree
static CEvaluationTree * copy (const CEvaluationTree &src)
static CEvaluationTree * create (CEvaluationTree::Type type)
static CEvaluationNode * fromAST (const ASTNode *pASTNode, bool isFunction)
static CEvaluationTree * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Protected Member Functions
CFunction (const CFunction &src)
CIssue initVariables ()
Protected Member Functions inherited from CEvaluationTree
void buildCalculationSequence ()
void calculate ()
CEvaluationTree (const CEvaluationTree &src)
void clearNodes ()
CIssue compileNodes ()
CIssue parse ()
void setType (const CEvaluationTree::Type &type)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Private Attributes
CCallParameters< C_FLOAT64 >::const_iterator mCallParametersBegin
TriLogic mReversible
std::string mSBMLId
CFunctionParameters mVariables
Friends
std::ostream & operator<< (std::ostream &os, const CFunction &f)
Additional Inherited Members
Public Types inherited from CEvaluationTree
enum Type {
Function = 0 , MassAction , PreDefined , UserDefined ,
Expression , MathExpression
}
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Static Public Attributes inherited from CEvaluationTree
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Attributes inherited from CEvaluationTree
CVector< CEvaluationNode * > mCalculationSequence
std::string mInfix
std::vector< CEvaluationNode * > * mpNodeList
const C_FLOAT64 * mpRootValue
CEvaluationTree::Type mType
C_FLOAT64 mValue
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Protected Attributes inherited from CAnnotation
std::string mKey
Detailed Description
The class for handling a chemical kinetic function.
This class is designed to handle all about a given chemical kinetic function from editing and displaying (with help of MathML) the function to calculating the function value.
Constructor & Destructor Documentation
CFunction() [1/3]
CFunction::CFunction (const CFunction & src) protected
Referenced by createCopy(), and splitFunction().
CFunction() [2/3]
CFunction::CFunction (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT, const Type & type = Function)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CEvaluationTree::Type & type (default: Function)
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CRootContainer::getKeyFactory(), CAnnotation::initMiriamAnnotation(), and CAnnotation::mKey.
CFunction() [3/3]
CFunction::CFunction (const CFunction & src, const CDataContainer * pParent)
Copy constructor
Parameters
const CFunction & src
const CDataContainer * pParent (default: NULL)
References CKeyFactory::add(), CEvaluationTree::compile(), CRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CAnnotation::mKey, and CAnnotation::setMiriamAnnotation().
~CFunction()
CFunction::~CFunction () virtual
Destructor
References CRootContainer::getKeyFactory(), CAnnotation::mKey, and CKeyFactory::remove().
Member Function Documentation
addVariable()
bool CFunction::addVariable (const std::string & name, CFunctionParameter::Role usage = CFunctionParameter::Role::VARIABLE, const CFunctionParameter::DataType & type = CFunctionParameter::DataType::FLOAT64)
Function to add the description of a variable.
Parameters
const string & name
const string & usage (Default: VARIABLE)
const CFunctionParameters::DataType & type (Default: value)
Returns
bool success
References CFunctionParameters::add(), and mVariables.
Referenced by SBMLImporter::createCFunctionFromFunctionTree(), and CReaction::setFunctionFromExpressionTree().
applyData()
bool CFunction::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CEvaluationTree.
References CEvaluationTree::applyData(), and CAnnotation::applyData().
calcValue()
const C_FLOAT64 & CFunction::calcValue (const CCallParameters< C_FLOAT64 > & callParameters) virtual
Function to calculate the value of the function
Parameters
const CCallParameters<C_FLOAT64> & callParameters
Returns
const C_FLOAT64 & result
Reimplemented in CMassAction.
References CCallParameters< Type >::begin(), CEvaluationTree::calculate(), mCallParametersBegin, and CEvaluationTree::mValue.
Referenced by CEvaluationNodeCall::calculate().
completeFunctionList()
bool CFunction::completeFunctionList (std::vector< const CFunction * > & list, const size_t & added = 0) static
Complete the list of evaluation tree such that all called trees are includes.
Parameters
std::vector< const CFunction * > & list
const size_t & added (Default: list.size())
Returns
bool success
References C_INVALID_INDEX, CEvaluationNode::CALL, CRootContainer::getFunctionList(), CDataVectorN< CType >::getIndex(), CEvaluationTree::getNodeList(), and CFunctionDB::loadedFunctions().
Referenced by CFunctionDB::getUsedFunctions().
createCopy()
CFunction * CFunction::createCopy () const
Function to duplicate itself
References CFunction(), CEvaluationTree::getRoot(), mReversible, and CEvaluationTree::setRoot().
createListOfParametersForMathML()
void CFunction::createListOfParametersForMathML (std::vector< std::vector< std::string > > & env)
Function to create a list of the names of the function parameters in MathML format. This list can be passed as the env argument to the writeMathML() method.
Parameters
std::vector<std::vector<std::string> > & env
References CMathMl::fixName(), CDataObject::getObjectName(), getVariables(), and CFunctionParameters::size().
createUndoData()
void CFunction::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CUndoData::CHANGE, CAnnotation::createUndoData(), and CDataContainer::createUndoData().
fromData()
CFunction * CFunction::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CFunction * pDataObject
References CEvaluationTree::fromData(), and pdelete.
getKey()
const std::string & CFunction::getKey () const virtual
Retrieves the key of the EvaluationTree
Returns
const std::string & key
Reimplemented from CAnnotation.
References CAnnotation::getKey().
Referenced by CODEExporter::exportExpression(), CODEExporterC::exportSingleFunction(), SBMLImporter::importMIRIAM(), CODEExporterC::KineticFunction2ODEmember(), CODEExporterC::preprocess(), FunctionHandler::processEnd(), CCopasiXML::saveFunctionList(), CCopasiXML::saveModel(), and CODEExporterC::setExportNameOfFunction().
getSBMLId()
const std::string & CFunction::getSBMLId () const
Returns a reference to the SBML Id.
References mSBMLId.
Referenced by CSBMLExporter::collectIds(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCModelFromSBMLDocument(), CCopasiXML::saveFunctionList(), CSBMLExporter::setFunctionSBMLIds(), and CEvaluationNodeCall::toAST().
getVariableIndex()
size_t CFunction::getVariableIndex (const std::string & name) const virtual
Function to retrieve the index to the value of the named variable.
Parameters
const std::string & name
Returns
size_t index
Reimplemented from CEvaluationTree.
References CFunctionParameters::findParameterByName(), and mVariables.
Referenced by CODEExporter::exportKineticFunction(), and CODEExporter::exportSingleFunction().
getVariables() [1/2]
CFunctionParameters & CFunction::getVariables ()
Function to retrive the definition of the parameters
Returns
CFunctionParameters & variables
References mVariables.
Referenced by CMathEvent::CTrigger::allocate(), SBMLImporter::areEqualFunctions(), CFunctionAnalyzer::checkKineticFunction(), CEvaluationNodeCall::compile(), SBMLImporter::createCReactionFromReaction(), SBMLImporter::createExpressionFromFunction(), CReaction::createFunctionFromExpression(), CSBMLExporter::createKineticExpression(), createListOfParametersForMathML(), CKinFunction::createParameters(), CReaction::createUndoData(), SBMLImporter::doMapping(), CFunctionAnalyzer::evaluateNode(), CODEExporter::exportKineticFunction(), CODEExporterC::exportSingleFunction(), SBMLImporter::findCorrespondingFunction(), CReactionInterface::getDeletedParameters(), CReactionInterface::initMapping(), FunctionHandler::processEnd(), ParameterDescriptionHandler::processStart(), CCopasiXML::saveFunctionList(), CCopasiXML::saveModel(), SBMLImporter::setCorrectUsage(), CReaction::setFunction(), CReaction::setFunctionFromExpressionTree(), CMassAction::setInfix(), CReaction::setParameterValue(), splitFunction(), CReaction::toData(), CReactionInterface::writeBackToReaction(), and writeMathML().
getVariables() [2/2]
const CFunctionParameters & CFunction::getVariables () const
Function to retrive the definition of the parameters
Returns
const CFunctionParameters & variables
References mVariables.
getVariableValue()
const C_FLOAT64 & CFunction::getVariableValue (const size_t & index) const virtual
Function to retrieve the value of the indexed variable.
Note this function is only usable during calcValue, since the values of the call parameters are only defined during that time.
Parameters
const size_t & index
Returns
const C_FLOAT64 & variableValue
Reimplemented from CEvaluationTree.
References mCallParametersBegin.
initVariables()
CIssue CFunction::initVariables () protected
Function to initialize the parameters
Returns
CIssue issue;
References CFunctionParameters::add(), C_INVALID_INDEX, CIssue::Error, CFunctionParameters::findParameterByName(), CFunctionParameter::FLOAT64, CDataObject::getObjectName(), CEvaluationTree::mInfix, CEvaluationTree::mpNodeList, mVariables, CFunctionParameters::remove(), CFunctionParameters::size(), CIssue::StructureInvalid, CIssue::Success, CEvaluationNode::VARIABLE, and CFunctionParameter::VARIABLE.
Referenced by setInfix(), and splitFunction().
isReadOnly()
bool CFunction::isReadOnly () const virtual
Check whether a function is read only
Returns
bool isReadOnly
References CEvaluationTree::MassAction, CEvaluationTree::mType, and CEvaluationTree::PreDefined.
isReversible()
const TriLogic & CFunction::isReversible () const
Function to retrieve whether it is reversible.
References mReversible.
Referenced by CMassAction::calcValue(), CFunctionAnalyzer::checkKineticFunction(), CModelAnalyzer::checkReaction(), CSBMLExporter::createKineticExpression(), CSBMLExporter::createKineticLaw(), CODEExporter::exportKineticFunction(), CReactionInterface::getFunction(), isSuitable(), CODEExporterC::KineticFunction2ODEmember(), CCopasiXML::saveFunctionList(), CReaction::setFunctionFromExpressionTree(), CMassAction::setInfix(), and CMassAction::writeMathML().
isSuitable()
bool CFunction::isSuitable (const size_t noSubstrates, const size_t noProducts, const TriLogic reversible)
Function to determine whether it is suitable for a reaction with the given number of substrates and products and reversibility
References C_INVALID_INDEX, CFunctionParameters::getNumberOfParametersByUsage(), isReversible(), CFunctionParameters::isVector(), mVariables, CFunctionParameter::PRODUCT, CFunctionParameter::SUBSTRATE, TriTrue, TriUnspecified, and CFunctionParameter::VARIABLE.
Referenced by SBMLImporter::createCReactionFromReaction(), and CFunctionDB::suitableFunctions().
load()
void CFunction::load (CReadConfig & configBuffer, CReadConfig::Mode mode = CReadConfig::SEARCH) virtual
Function to load an object with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
CReadConfig & configBuffer
CReadConfig::Mode mode (default: CReadConfig::SEARCH)
Returns
Fail
References C_INT32, fatalError, CReadConfig::getVariable(), mReversible, CReadConfig::SEARCH, setInfix(), CDataObject::setObjectName(), CEvaluationTree::setType(), and CEvaluationTree::UserDefined.
Referenced by CFunctionDB::load().
operator==()
bool CFunction::operator== (const CFunction & rhs) const
Comparison operator
Parameters
const CFunction & rhs
Returns
bool equal
References mVariables.
setInfix()
CIssue CFunction::setInfix (const std::string & infix) virtual
Function to set the infix description of the tree and compile it.
Parameters
const std::string & infix
Returns
CIssue issue
Reimplemented from CEvaluationTree.
Reimplemented in CMassAction.
References CValidity::add(), CEvaluationNode::AVOGADRO, CEvaluationNode::CALL, CEvaluationTree::compileNodes(), CEvaluationNode::DELAY, CIssue::Error, CEvaluationNode::EXPRESSION, CRootContainer::functionDefinitionChanged(), initVariables(), CEvaluationTree::mInfix, CEvaluationTree::mpNodeList, CObjectInterface::mValidity, CEvaluationNode::OBJECT, CEvaluationTree::setInfix(), and CIssue::StructureInvalid.
Referenced by CMathEvent::CTrigger::allocate(), CReaction::createFunctionFromExpression(), CKinFunction::createParameters(), CReactionInterface::getFunction(), SBMLImporter::importFunctionDefinitions(), CRootContainer::initializeChildren(), load(), FunctionHandler::processEnd(), and CMassAction::setInfix().
setReversible()
void CFunction::setReversible (const TriLogic & reversible)
Function to set whether it is reversible.
References mReversible.
Referenced by SBMLImporter::createCReactionFromReaction(), FunctionHandler::processStart(), CReaction::setFunctionFromExpressionTree(), and CMassAction::setInfix().
setSBMLId()
void CFunction::setSBMLId (const std::string & id)
Sets the SBMLId.
References mSBMLId.
Referenced by SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCModelFromSBMLDocument(), SBMLMapHandler::processStart(), and CSBMLExporter::setFunctionSBMLIds().
splitFunction()
std::pair< CFunction *, CFunction * > CFunction::splitFunction (const CEvaluationNode * node, const std::string & name1, const std::string & name2) const
Function to split
Parameters
const CEvaluationNode* node
const std::string & name1
const std::string & name2
References CFunction(), CEvaluationTree::compile(), CFunctionAnalyzer::constructCallParameters(), CEvaluationNode::findTopMinus(), CEvaluationTree::getRoot(), getVariables(), initVariables(), CFunctionParameter::MODIFIER, mReversible, mVariables, CFunctionParameter::PRODUCT, CDataObject::setObjectName(), CEvaluationTree::setRoot(), CFunctionParameters::size(), CEvaluationNode::splitBranch(), CFunctionParameter::SUBSTRATE, TriFalse, and TriTrue.
Referenced by CFunctionAnalyzer::checkKineticFunction(), and CModel::convert2NonReversible().
toData()
CData CFunction::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CEvaluationTree.
References CData::appendData(), CEvaluationTree::toData(), and CAnnotation::toData().
writeMathML() [1/2]
std::string CFunction::writeMathML (const std::vector< std::vector< std::string > > & variables, bool expand = true, bool fullExpand = true) const virtual
Function to write the mathematical formula in format of MathML.
Parameters
std::ostream & out
const std::vector< std::vector< std::string > > & variables
bool expand = true
bool fullExpand
Returns
std::string
Reimplemented in CMassAction.
References CEvaluationNode::buildMMLString(), CMathMl::fixName(), CDataObject::getObjectName(), and CEvaluationTree::getRoot().
writeMathML() [2/2]
void CFunction::writeMathML (std::ostream & out, size_t l = 0) const virtual
This is an overloaded member function, provided for convenience. It behaves essentially like the above function.
Parameters
std::ostream & out
size_t l
References CMathMl::fixName(), CDataObject::getObjectName(), getVariables(), CFunctionParameters::size(), and SPC.
Referenced by CEvaluationNodeCall::getMMLString(), and CMMLOutput::writeRHS().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CFunction & f) friend
Insert operator
Member Data Documentation
mCallParametersBegin
CCallParameters< C_FLOAT64 >::const_iterator CFunction::mCallParametersBegin private
A pointer to the call parameters during calculation.
Referenced by calcValue(), and getVariableValue().
mReversible
TriLogic CFunction::mReversible private
Whether the function is reversible
Referenced by createCopy(), isReversible(), load(), setReversible(), and splitFunction().
mSBMLId
std::string CFunction::mSBMLId private
The id of the corresponding function in an SBML file. This value is either set upon importing an SBML file, or when the object is first exported to an SBML file.
Referenced by getSBMLId(), and setSBMLId().
mVariables
CFunctionParameters CFunction::mVariables private
The description of the variables of the function. It describes which variables need to be passed to the function for evaluation and its eventual type.
Referenced by addVariable(), getVariableIndex(), getVariables(), initVariables(), isSuitable(), operator==(), and splitFunction().
The documentation for this class was generated from the following files:
CFunction.h
CFunction.cpp