COPASI API: CEnumAnnotation< Type, Enum > Class Template Reference
CEnumAnnotation< Type, Enum > Class Template Reference
#include <CEnumAnnotation.h>
Public Types
typedef std::array< Type, static_cast< size_t >Enum::__SIZE) > base
Public Member Functions
std::vector< Type > annotations () const
CEnumAnnotation ()
CEnumAnnotation (const CEnumAnnotation &src)
CEnumAnnotation (typename std::enable_if< !(std::is_same< Type, const char * >::value||std::is_const< Type >::value), const base & >::type src)
base::const_reference operator[] (Enum e) const
base::const_reference operator[] (size_t i) const
Enum toEnum (const char *pAnnotation, Enum enumDefault=Enum::__SIZE) const
Enum toEnum (const Type &annotation, Enum enumDefault=Enum::__SIZE) const
Private Attributes
std::map< Type, Enum > mMap
Member Typedef Documentation
base
template<class Type , class Enum > typedef std::array< Type, static_cast< size_t >Enum::__SIZE) > CEnumAnnotation< Type, Enum >::base
typedef for the base class
Constructor & Destructor Documentation
CEnumAnnotation() [1/3]
template<class Type , class Enum > CEnumAnnotation< Type, Enum >::CEnumAnnotation () inline
Default constructor
CEnumAnnotation() [2/3]
template<class Type , class Enum > CEnumAnnotation< Type, Enum >::CEnumAnnotation (const CEnumAnnotation< Type, Enum > & src) inline
Disable the copy constructor
CEnumAnnotation() [3/3]
template<class Type , class Enum > CEnumAnnotation< Type, Enum >::CEnumAnnotation (typename std::enable_if< !(std::is_same< Type, const char * >::value||std::is_const< Type >::value), const base & >::type src) inline
Specific constructor from the base class
Parameters
const base & src
References CEnumAnnotation< Type, Enum >::mMap.
Member Function Documentation
annotations()
template<class Type , class Enum > std::vector< Type > CEnumAnnotation< Type, Enum >::annotations () const inline
References CEnumAnnotation< Type, Enum >::mMap.
Referenced by CExpressionGenerator::getSupportedOperations().
operator[]() [1/2]
template<class Type , class Enum > base::const_reference CEnumAnnotation< Type, Enum >::operator[] (Enum e) const inline
Operator []
Parameters
Enum e
Returns
const Type & annotation
operator[]() [2/2]
template<class Type , class Enum > base::const_reference CEnumAnnotation< Type, Enum >::operator[] (size_t i) const inline
Operator []
Parameters
size_t i
Returns
const Type & annotation
toEnum() [1/2]
template<class Type , class Enum > Enum CEnumAnnotation< Type, Enum >::toEnum (const char * pAnnotation, Enum enumDefault = Enum::__SIZE) const inline
Conversion from annotation to enum
Parameters
const char * pAnnotation
Enum enumDefault (default: Enum::__SIZE)
References CEnumAnnotation< Type, Enum >::toEnum().
toEnum() [2/2]
template<class Type , class Enum > Enum CEnumAnnotation< Type, Enum >::toEnum (const Type & annotation, Enum enumDefault = Enum::__SIZE) const inline
Conversion from annotation to enum
Parameters
const Type & annotation
Enum enumDefault (default: Enum::__SIZE)
References CEnumAnnotation< Type, Enum >::mMap.
Referenced by CFunctionParameter::applyData(), CModel::applyData(), CModelParameter::applyData(), CReportDefinition::applyData(), CModelEntity::applyData(), CCopasiParameter::applyData(), CModelParameter::fromData(), CCopasiParameter::fromData(), CNewtonMethod::initialize(), CompartmentHandler::processStart(), KineticLawHandler::processStart(), MetaboliteHandler::processStart(), MethodHandler::processStart(), ModelHandler::processStart(), ModelParameterGroupHandler::processStart(), ModelParameterHandler::processStart(), ModelValueHandler::processStart(), ParameterDescriptionHandler::processStart(), ParameterHandler::processStart(), ParameterTextHandler::processStart(), ReportDefinitionHandler::processStart(), TaskHandler::processStart(), CExpressionGenerator::setOperation(), CPlotSpecification::setTaskTypes(), and CEnumAnnotation< Type, Enum >::toEnum().
Member Data Documentation
mMap
template<class Type , class Enum > std::map< Type, Enum > CEnumAnnotation< Type, Enum >::mMap private
Referenced by CEnumAnnotation< Type, Enum >::annotations(), CEnumAnnotation< Type, Enum >::CEnumAnnotation(), and CEnumAnnotation< Type, Enum >::toEnum().
The documentation for this class was generated from the following file:
CEnumAnnotation.h