COPASI API: CLCompartmentGlyph Class Reference
CLCompartmentGlyph Class Reference
#include <CLGlyphs.h>
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CLCompartmentGlyph (const CLCompartmentGlyph &src, const CDataContainer *pParent)
CLCompartmentGlyph (const CompartmentGlyph &sbml, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const CDataContainer *pParent=NO_PARENT)
CLCompartmentGlyph (const std::string &name="CompartmentGlyph", const CDataContainer *pParent=NO_PARENT)
virtual CLGraphicalObject * clone () const
virtual void exportToSBML (CompartmentGlyph *cg, const std::map< const CDataObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
CLCompartmentGlyph & operator= (const CLCompartmentGlyph &rhs)
void print (std::ostream *ostream) const
virtual CData toData () const
Public Member Functions inherited from CLGraphicalObject
CLGraphicalObject (const CLGraphicalObject &src, const CDataContainer *pParent)
CLGraphicalObject (const GraphicalObject &sbml, std::map< std::string, std::string > &layoutmap, const CDataContainer *pParent=NO_PARENT)
CLGraphicalObject (const std::string &name="GraphicalObject", const CDataContainer *pParent=NO_PARENT)
virtual void exportToSBML (GraphicalObject *sbmlobject, const std::map< const CDataObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
CLBoundingBox & getBoundingBox ()
const CLBoundingBox & getBoundingBox () const
const CLDimensions & getDimensions () const
const C_FLOAT64 & getHeight () const
virtual const std::string & getKey () const
CDataObject * getModelObject () const
std::string getModelObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getModelObjectKey () const
std::string getModelObjectName () const
const std::string & getObjectRole () const
const CLPoint & getPosition () const
const C_FLOAT64 & getWidth () const
const C_FLOAT64 & getX () const
const C_FLOAT64 & getY () const
bool hasValidModelReference () const
virtual void moveBy (const CLPoint &p)
CLGraphicalObject & operator= (const CLGraphicalObject &rhs)
void print (std::ostream *ostream) const
void setBoundingBox (const CLBoundingBox &bb)
void setDimensions (const CLDimensions &d)
void setHeight (const C_FLOAT64 &h)
void setModelObjectKey (const std::string &k)
void setObjectRole (const std::string &role)
void setPosition (const CLPoint &p)
void setWidth (const C_FLOAT64 &w)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
~CLGraphicalObject ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CLCompartmentGlyph * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CLGraphicalObject
static CLGraphicalObject * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Member Functions
CLCompartmentGlyph (const CLCompartmentGlyph &src)
Protected Member Functions inherited from CLGraphicalObject
CLGraphicalObject (const CLGraphicalObject &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Friends
std::ostream & operator<< (std::ostream &os, const CLCompartmentGlyph &g)
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Attributes inherited from CLGraphicalObject
CLBoundingBox mBBox
std::string mKey
std::string mModelObjectKey
std::string mObjectRole
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Detailed Description
Graphical representation of a compartment
Constructor & Destructor Documentation
CLCompartmentGlyph() [1/4]
CLCompartmentGlyph::CLCompartmentGlyph (const CLCompartmentGlyph & src) protected
Referenced by clone(), and fromData().
CLCompartmentGlyph() [2/4]
CLCompartmentGlyph::CLCompartmentGlyph (const std::string & name = "CompartmentGlyph", const CDataContainer * pParent = NO_PARENT)
CLCompartmentGlyph() [3/4]
CLCompartmentGlyph::CLCompartmentGlyph (const CLCompartmentGlyph & src, const CDataContainer * pParent)
CLCompartmentGlyph() [4/4]
CLCompartmentGlyph::CLCompartmentGlyph (const CompartmentGlyph & sbml, const std::map< std::string, std::string > & modelmap, std::map< std::string, std::string > & layoutmap, const CDataContainer * pParent = NO_PARENT)
constructor from libsbml object
References CLGraphicalObject::setModelObjectKey().
Member Function Documentation
applyData()
bool CLCompartmentGlyph::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CLGraphicalObject.
References fatalError.
clone()
virtual CLGraphicalObject* CLCompartmentGlyph::clone () const inline virtual
Reimplemented from CLGraphicalObject.
References CLCompartmentGlyph().
exportToSBML()
void CLCompartmentGlyph::exportToSBML (CompartmentGlyph * cg, const std::map< const CDataObject *, SBase * > & copasimodelmap, std::map< std::string, const SBase * > & sbmlIDs) const virtual
This method writes the information of the copasi layout object into the corresponding sbml object
References CLGraphicalObject::exportToSBML(), and CLGraphicalObject::getModelObject().
Referenced by CLGeneralGlyph::exportToSBML(), and CLayout::exportToSBML().
fromData()
CLCompartmentGlyph * CLCompartmentGlyph::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CLCompartmentGlyph * pDataObject
References CLCompartmentGlyph(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
operator=()
CLCompartmentGlyph & CLCompartmentGlyph::operator= (const CLCompartmentGlyph & rhs)
assignment operator
References CLGraphicalObject::operator=().
print()
void CLCompartmentGlyph::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CDataObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CDataObject.
toData()
CData CLCompartmentGlyph::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CLGraphicalObject.
References fatalError.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CLCompartmentGlyph & g) friend
insert operator
The documentation for this class was generated from the following files:
CLGlyphs.h
CLGlyphs.cpp