COPASI API: Expression2PresentationMML Class Reference
Expression2PresentationMML Class Reference
#include <Expression2PresentationMML.h>
Public Member Functions
Expression2PresentationMML (const ASTNode *rootnode)
void setModel (const Model *m)
void setReaction (const Reaction *m)
void setUseReactionNameInLocalParameters (bool b)
void writeMathML (std::ostream &out) const
virtual ~Expression2PresentationMML ()
Protected Member Functions
void writeMathML (std::ostream &out, const ASTNode *node, size_t l) const
virtual void writeMathMLFunction (std::ostream &out, const ASTNode *node, size_t l) const
virtual void writeMathMLName (std::ostream &out, const ASTNode *node, size_t l) const
virtual void writeMathMLNumber (std::ostream &out, const ASTNode *node, size_t l) const
Protected Attributes
const Model * mpModel
const Reaction * mpReaction
const ASTNode * mRootNode
bool mUseReactionNameInLocalParameters
Constructor & Destructor Documentation
Expression2PresentationMML()
Expression2PresentationMML::Expression2PresentationMML (const ASTNode * rootnode)
~Expression2PresentationMML()
virtual Expression2PresentationMML::~Expression2PresentationMML () inline virtual
Member Function Documentation
setModel()
void Expression2PresentationMML::setModel (const Model * m) inline
References mpModel.
setReaction()
void Expression2PresentationMML::setReaction (const Reaction * m) inline
set the reaction to be used as the environment for finding local parameters
References mpReaction.
setUseReactionNameInLocalParameters()
void Expression2PresentationMML::setUseReactionNameInLocalParameters (bool b) inline
If this is set to true (the default) the actual name/id of a reaction is added to the name of local parameter. This may lead to rather long expressions. In cases where the reaction is identifiable by other means it should be set to false for more compact expression display.
References mUseReactionNameInLocalParameters.
writeMathML() [1/2]
void Expression2PresentationMML::writeMathML (std::ostream & out) const
References mRootNode.
Referenced by writeMathML(), and writeMathMLFunction().
writeMathML() [2/2]
void Expression2PresentationMML::writeMathML (std::ostream & out, const ASTNode * node, size_t l) const protected
References SPC, writeMathML(), writeMathMLFunction(), writeMathMLName(), and writeMathMLNumber().
writeMathMLFunction()
void Expression2PresentationMML::writeMathMLFunction (std::ostream & out, const ASTNode * node, size_t l) const protected virtual
References CMathMl::fixName(), SPC, and writeMathML().
Referenced by writeMathML().
writeMathMLName()
void Expression2PresentationMML::writeMathMLName (std::ostream & out, const ASTNode * node, size_t l) const protected virtual
Reimplemented in Expression2PresentationMMLUnits.
References CMathMl::fixName(), mpModel, mpReaction, mUseReactionNameInLocalParameters, and SPC.
Referenced by writeMathML(), and Expression2PresentationMMLUnits::writeMathMLName().
writeMathMLNumber()
void Expression2PresentationMML::writeMathMLNumber (std::ostream & out, const ASTNode * node, size_t l) const protected virtual
Reimplemented in Expression2PresentationMMLUnits.
References SPC.
Referenced by writeMathML(), and Expression2PresentationMMLUnits::writeMathMLNumber().
Member Data Documentation
mpModel
const Model* Expression2PresentationMML::mpModel protected
Referenced by setModel(), Expression2PresentationMMLUnits::setUnitInterface(), and writeMathMLName().
mpReaction
const Reaction* Expression2PresentationMML::mpReaction protected
Referenced by setReaction(), writeMathMLName(), and Expression2PresentationMMLUnits::writeMathMLName().
mRootNode
const ASTNode* Expression2PresentationMML::mRootNode protected
Referenced by writeMathML().
mUseReactionNameInLocalParameters
bool Expression2PresentationMML::mUseReactionNameInLocalParameters protected
Referenced by setUseReactionNameInLocalParameters(), and writeMathMLName().
The documentation for this class was generated from the following files:
Expression2PresentationMML.h
Expression2PresentationMML.cpp