COPASI API: CDataModel.cpp File Reference
CDataModel.cpp File Reference
#include <sbml/SBMLDocument.h>
#include "copasi/copasi.h"
#include "copasi/CopasiDataModel/CDataModel.h"
#include "copasi/CopasiDataModel/CInfo.h"
#include "copasi/core/CDataTimer.h"
#include "copasi/commandline/COptions.h"
#include "copasi/commandline/CConfigurationFile.h"
#include "copasi/commandline/CLocaleString.h"
#include "copasi/function/CFunctionDB.h"
#include "copasi/model/CModel.h"
#include "copasi/model/CMetabNameInterface.h"
#include "copasi/utilities/CTaskFactory.h"
#include "copasi/plot/COutputDefinitionVector.h"
#include "copasi/report/CKeyFactory.h"
#include "copasi/report/CReportDefinitionVector.h"
#include "copasi/sbml/CSBMLExporter.h"
#include "copasi/sbml/SBMLImporter.h"
#include "copasi/sbml/SBMLIncompatibility.h"
#include "copasi/steadystate/CMCAProblem.h"
#include "copasi/lna/CLNAProblem.h"
#include "copasi/trajectory/CTrajectoryProblem.h"
#include "copasi/tss/CODEExporter.h"
#include "copasi/tss/CODEExporterC.h"
#include "copasi/tss/CODEExporterBM.h"
#include "copasi/tss/CODEExporterXPPAUT.h"
#include "copasi/utilities/CCopasiException.h"
#include "copasi/utilities/CCopasiProblem.h"
#include "copasi/core/CDataVector.h"
#include "copasi/utilities/CDirEntry.h"
#include "copasi/xml/CCopasiXML.h"
#include "copasi/undo/CUndoData.h"
#include "copasi/steadystate/CSteadyStateTask.h"
#include "copasi/trajectory/CTrajectoryTask.h"
#include "copasi/layout/CListOfLayouts.h"
#include "copasi/layout/CLayoutInitializer.h"
#include "copasi/core/CRootContainer.h"
#include <combine/combinearchive.h>
#include <combine/knownformats.h>
#include <combine/util.h>
#include <omex/CaContent.h>
#include <copasi/utilities/CCopasiMessage.h>
#include <copasi/utilities/CParameterEstimationUtils.h>
#include <sedml/SedDocument.h>
#include "copasi/sedml/SEDMLImporter.h"
#include "copasi/sedml/CSEDMLExporter.h"
#include "copasi/model/CModelExpansion.h"
#include "copasi/model/CModelParameter.h"
#include "copasi/MIRIAM/CModelMIRIAMInfo.h"
#include <copasi/parameterFitting/CFitProblem.h>
#include <copasi/parameterFitting/CExperimentSet.h>
#include <copasi/parameterFitting/CExperiment.h>
#include <copasi/shinyExport/uiShiny.c>
#include <copasi/shinyExport/serverShiny.c>
Macros
#define USE_LAYOUT 1
Functions
void addMessages (const std::string &title, std::stringstream &messageStream, const std::vector< CCopasiMessage > &messages)
void addMessagesToStream (std::stringstream &msgs, CCopasiMessage::Type &highestError, const std::string &title)
Macro Definition Documentation
USE_LAYOUT
#define USE_LAYOUT 1
Function Documentation
addMessages()
void addMessages (const std::string & title, std::stringstream & messageStream, const std::vector< CCopasiMessage > & messages)
Referenced by CDataModel::openCombineArchive().
addMessagesToStream()
void addMessagesToStream (std::stringstream & msgs, CCopasiMessage::Type & highestError, const std::string & title)
adds copasi message to stringstream, with optional title
References CCopasiMessage::clearDeque(), CCopasiMessage::getAllMessageText(), CCopasiMessage::getHighestSeverity(), and CCopasiMessage::size().
Referenced by CDataModel::exportCombineArchive().