COPASI API: CLImage Class Reference
CLImage Class Reference
#include <CLImage.h>
Public Member Functions
CLImage (CDataContainer *pParent=NULL)
CLImage (const CLImage &source, CDataContainer *pParent=NULL)
CLImage (const Image &source, CDataContainer *pParent=NULL)
const CLRelAbsVector & getHeight () const
const std::string & getImageReference () const
const std::string & getKey () const
const CLRelAbsVector & getWidth () const
CLRelAbsVector & getX ()
const CLRelAbsVector & getX () const
CLRelAbsVector & getY ()
const CLRelAbsVector & getY () const
CLRelAbsVector & getZ ()
const CLRelAbsVector & getZ () const
bool isSetImageReference () const
void setCoordinates (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
void setDimensions (const CLRelAbsVector &width, const CLRelAbsVector &height)
void setHeight (const CLRelAbsVector &height)
void setImageReference (const std::string &ref)
void setWidth (const CLRelAbsVector &width)
void setX (const CLRelAbsVector &coord)
void setY (const CLRelAbsVector &coord)
void setZ (const CLRelAbsVector &coord)
Image * toSBML (unsigned int level, unsigned int version) const
~CLImage ()
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
virtual const CDataObject * getValueObject () const
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const override
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Protected Attributes
CLRelAbsVector mHeight
std::string mHRef
std::string mKey
CLRelAbsVector mWidth
CLRelAbsVector mX
CLRelAbsVector mY
CLRelAbsVector mZ
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLImage & operator= (const CLImage &source)
Additional Inherited Members
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLImage() [1/3]
CLImage::CLImage (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLImage() [2/3]
CLImage::CLImage (const CLImage & source, CDataContainer * pParent = NULL)
Copy Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLImage() [3/3]
CLImage::CLImage (const Image & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
~CLImage()
CLImage::~CLImage ()
Destructor.
Destructor
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
getHeight()
const CLRelAbsVector & CLImage::getHeight () const
Returns the height.
References mHeight.
Referenced by CLLayoutRenderer::draw_image(), and CCopasiXML::saveImageElement().
getImageReference()
const std::string & CLImage::getImageReference () const
Returns the image reference.
References mHRef.
Referenced by CLLayoutRenderer::draw_image(), and CCopasiXML::saveImageElement().
getKey()
const std::string & CLImage::getKey () const virtual
Returns the key string of the object.
Returns the key of the color definition.
Reimplemented from CDataObject.
References mKey.
getWidth()
const CLRelAbsVector & CLImage::getWidth () const
Returns the width.
References mWidth.
Referenced by CLLayoutRenderer::draw_image(), and CCopasiXML::saveImageElement().
getX() [1/2]
CLRelAbsVector & CLImage::getX ()
Returns the x coordinate.
References mX.
Referenced by CLLayoutRenderer::draw_image(), and CCopasiXML::saveImageElement().
getX() [2/2]
const CLRelAbsVector & CLImage::getX () const
Returns the x coordinate.
References mX.
getY() [1/2]
CLRelAbsVector & CLImage::getY ()
Returns the y coordinate.
References mY.
Referenced by CLLayoutRenderer::draw_image(), and CCopasiXML::saveImageElement().
getY() [2/2]
const CLRelAbsVector & CLImage::getY () const
Returns the y coordinate.
References mY.
getZ() [1/2]
CLRelAbsVector & CLImage::getZ ()
Returns the z coordinate.
References mZ.
Referenced by CCopasiXML::saveImageElement().
getZ() [2/2]
const CLRelAbsVector & CLImage::getZ () const
Returns the z coordinate.
References mZ.
isSetImageReference()
bool CLImage::isSetImageReference () const
Returns true if the image reference has been set.
References mHRef.
Referenced by CLLayoutRenderer::draw_image().
operator=()
CLImage& CLImage::operator= (const CLImage & source) private
setCoordinates()
void CLImage::setCoordinates (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z = CLRelAbsVector(0.0, 0.0))
Sets the coordinates.
References mX, mY, and mZ.
Referenced by ImageHandler::processStart().
setDimensions()
void CLImage::setDimensions (const CLRelAbsVector & width, const CLRelAbsVector & height)
Sets the dimensions.
References mHeight, and mWidth.
Referenced by ImageHandler::processStart().
setHeight()
void CLImage::setHeight (const CLRelAbsVector & height)
Sets the height.
References mHeight.
setImageReference()
void CLImage::setImageReference (const std::string & ref)
Sets the reference to the image location.
References mHRef.
Referenced by ImageHandler::processStart().
setWidth()
void CLImage::setWidth (const CLRelAbsVector & width)
Sets the width.
References mWidth.
setX()
void CLImage::setX (const CLRelAbsVector & coord)
Sets the x coordinate.
References mX.
setY()
void CLImage::setY (const CLRelAbsVector & coord)
Sets the y coordinate.
References mY.
setZ()
void CLImage::setZ (const CLRelAbsVector & coord)
Sets the z coordinate.
References mZ.
toSBML()
Image * CLImage::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLTransformation2D::addSBMLAttributes(), mHeight, mHRef, mWidth, mX, mY, mZ, and CLRelAbsVector::toSBML().
Member Data Documentation
mHeight
CLRelAbsVector CLImage::mHeight protected
Referenced by getHeight(), setDimensions(), setHeight(), and toSBML().
mHRef
std::string CLImage::mHRef protected
Referenced by getImageReference(), isSetImageReference(), setImageReference(), and toSBML().
mKey
std::string CLImage::mKey protected
key for the object.
Referenced by CLImage(), getKey(), and ~CLImage().
mWidth
CLRelAbsVector CLImage::mWidth protected
Referenced by getWidth(), setDimensions(), setWidth(), and toSBML().
mX
CLRelAbsVector CLImage::mX protected
Referenced by getX(), setCoordinates(), setX(), and toSBML().
mY
CLRelAbsVector CLImage::mY protected
Referenced by getY(), setCoordinates(), setY(), and toSBML().
mZ
CLRelAbsVector CLImage::mZ protected
Referenced by getZ(), setCoordinates(), setZ(), and toSBML().
The documentation for this class was generated from the following files:
CLImage.h
CLImage.cpp