COPASI API: CLsodaMethod Class Reference
CLsodaMethod Class Reference
#include <CLsodaMethod.h>
Classes
struct Data
struct State
Public Member Functions
CLsodaMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType=CTaskEnum::Method::deterministic, const CTaskEnum::Task &taskType=CTaskEnum::Task::timeCourse)
CLsodaMethod (const CLsodaMethod &src, const CDataContainer *pParent)
virtual bool elevateChildren ()
virtual void evalF (const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
virtual void evalJ (const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *ml, const C_INT *mu, C_FLOAT64 *pd, const C_INT *nRowPD)
virtual void evalR (const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *nr, C_FLOAT64 *r)
virtual void start ()
virtual void stateChange (const CMath::StateChange &change)
virtual Status step (const double &deltaT, const bool &final=false)
~CLsodaMethod ()
Public Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType=CTaskEnum::Task::timeCourse)
CTrajectoryMethod (const CTrajectoryMethod &src, const CDataContainer *pParent)
const CVectorCore< C_INT > & getRoots () const
const bool & integrateReducedModel () const
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (CTrajectoryProblem *problem)
~CTrajectoryMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CDataContainer *pParent)
virtual void clearCallBack ()
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
const CTaskEnum::Method & getSubType () const
const CTaskEnum::Task & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
CCopasiMethod & operator= (const CCopasiMethod &rhs)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static void EvalF (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
static void EvalJ (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *ml, const C_INT *mu, C_FLOAT64 *pd, const C_INT *nRowPD)
static void EvalR (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *nr, C_FLOAT64 *r)
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Types
enum eRootMasking { NONE = 0 , ALL , DISCRETE }
Protected Member Functions
void destroyRootMask ()
Protected Member Functions inherited from CTrajectoryMethod
void output (const bool &useMoieties)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src)
CCopasiMethod (const CDataContainer *pParent, const CTaskEnum::Method &methodType, const CTaskEnum::Task &taskType)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
Data mData
State mLastRootState
CVector< C_FLOAT64 > mLastSuccessState
C_INT mLsodaStatus
eRootMasking mRootMasking
C_FLOAT64 mTime
Protected Attributes inherited from CTrajectoryMethod
CVectorCore< C_FLOAT64 > mContainerState
C_FLOAT64 * mpContainerStateTime
CTrajectoryProblem * mpProblem
const bool * mpReducedModel
CTrajectoryTask * mpTask
CVectorCore< C_INT > mRootsFound
Protected Attributes inherited from CCopasiMethod
CMathContainer * mpContainer
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLsodaMethod ()
void createRootMask ()
bool hasStateChanged (const CVectorCore< C_FLOAT64 > &startState) const
void initializeParameter ()
void maskRoots (CVectorCore< C_FLOAT64 > &rootValues)
CTrajectoryMethod::Status peekAhead ()
void resetState (State &state)
void saveState (State &state, const CTrajectoryMethod::Status &status) const
void setRootMaskType (const eRootMasking &maskType)
Private Attributes
CVector< C_FLOAT64 > mAtol
CVectorCore< bool > mDiscreteRoots
CVector< C_FLOAT64 > mDWork
std::ostringstream mErrorMsg
CVector< C_INT > mIWork
C_INT mJType
CLSODA mLSODA
CLSODAR mLSODAR
C_INT mNumRoots
C_FLOAT64 * mpAbsoluteTolerance
C_FLOAT64 * mpAtol
bool mPeekAheadMode
unsigned C_INT32 * mpMaxInternalSteps
C_FLOAT64 * mpMaxInternalStepSize
C_FLOAT64 * mpRelativeTolerance
C_FLOAT64 * mpY
const C_FLOAT64 * mpYdot
unsigned C_INT32 mRootCounter
CVector< C_INT > mRootMask
State mSavedState
C_FLOAT64 mTargetTime
C_INT mTask
Additional Inherited Members
Public Types inherited from CTrajectoryMethod
enum Status { FAILURE = -1 , NORMAL = 0 , ROOT = 1 }
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Static Protected Attributes inherited from CTrajectoryMethod
static const bool ReducedModel
Member Enumeration Documentation
eRootMasking
enum CLsodaMethod::eRootMasking protected
Enumerator
NONE
ALL
DISCRETE
Constructor & Destructor Documentation
CLsodaMethod() [1/3]
CLsodaMethod::CLsodaMethod () private
Constructor.
CLsodaMethod() [2/3]
CLsodaMethod::CLsodaMethod (const CDataContainer * pParent, const CTaskEnum::Method & methodType = CTaskEnum::Method::deterministic, const CTaskEnum::Task & taskType = CTaskEnum::Task::timeCourse)
Specific constructor
Parameters
const CDataContainer * pParent
const CTaskEnum::Method & methodType (default: deterministic)
const CTaskEnum::Task & taskType (default: timeCourse)
References CLsodaMethod::Data::dim, initializeParameter(), mData, and CLsodaMethod::Data::pMethod.
CLsodaMethod() [3/3]
CLsodaMethod::CLsodaMethod (const CLsodaMethod & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CLsodaMethod & src
const CDataContainer * pParent (default: NULL)
References CLsodaMethod::Data::dim, initializeParameter(), mData, and CLsodaMethod::Data::pMethod.
~CLsodaMethod()
CLsodaMethod::~CLsodaMethod ()
Destructor.
References CVectorCore< CType >::array(), and CTrajectoryMethod::mRootsFound.
Member Function Documentation
createRootMask()
void CLsodaMethod::createRootMask () private
Create a mask which hides all roots being constant and zero.
References ALL, CVectorCore< CType >::begin(), C_FLOAT64, C_INT, CMathContainer::calculateRootDerivatives(), CVectorCore< CType >::end(), CMathContainer::getRootIsDiscrete(), CMathContainer::getRoots(), min, CCopasiMethod::mpContainer, CTrajectoryMethod::mpReducedModel, mRootMask, mRootMasking, CTrajectoryMethod::mRootsFound, CVector< CType >::resize(), CVectorCore< CType >::size(), and CMathContainer::updateRootValues().
Referenced by setRootMaskType().
destroyRootMask()
void CLsodaMethod::destroyRootMask () protected
Destroy the mask which hides all roots being constant and zero.
References mRootMask, mRootMasking, and NONE.
Referenced by start().
elevateChildren()
bool CLsodaMethod::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Reimplemented in CTrajectoryMethodDsaLsodar.
References initializeParameter().
Referenced by CTrajectoryMethodDsaLsodar::elevateChildren().
evalF()
void CLsodaMethod::evalF (const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) virtual
Reimplemented in CTrajectoryMethodDsaLsodar, and CHybridNextReactionLSODAMethod::LSODA.
References C_FLOAT64, CLsodaMethod::Data::dim, CMathContainer::getRate(), CMathContainer::getState(), mData, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, CTrajectoryMethod::mpReducedModel, mpYdot, and CMathContainer::updateSimulatedValues().
Referenced by EvalF().
EvalF()
void CLsodaMethod::EvalF (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) static
This evaluates the derivatives
References evalF(), and CLsodaMethod::Data::pMethod.
Referenced by step().
evalJ()
void CLsodaMethod::evalJ (const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * ml, const C_INT * mu, C_FLOAT64 * pd, const C_INT * nRowPD) virtual
Referenced by EvalJ().
EvalJ()
void CLsodaMethod::EvalJ (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * ml, const C_INT * mu, C_FLOAT64 * pd, const C_INT * nRowPD) static
This evaluates the Jacobian
References evalJ(), and CLsodaMethod::Data::pMethod.
Referenced by step().
evalR()
void CLsodaMethod::evalR (const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * nr, C_FLOAT64 * r) virtual
Reimplemented in CTrajectoryMethodDsaLsodar.
References CMathContainer::getRoots(), CMathContainer::getState(), maskRoots(), CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, CTrajectoryMethod::mpReducedModel, mRootMasking, NONE, and CMathContainer::updateRootValues().
Referenced by EvalR().
EvalR()
void CLsodaMethod::EvalR (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * nr, C_FLOAT64 * r) static
This evaluates the roots
References evalR(), and CLsodaMethod::Data::pMethod.
Referenced by step().
hasStateChanged()
bool CLsodaMethod::hasStateChanged (const CVectorCore< C_FLOAT64 > & startState) const private
References CVectorCore< CType >::array(), C_FLOAT64, CMathContainer::getCountFixedEventTargets(), mAtol, CTrajectoryMethod::mContainerState, CCopasiMethod::mpContainer, mpRelativeTolerance, and CVectorCore< CType >::size().
Referenced by peekAhead(), and step().
initializeParameter()
void CLsodaMethod::initializeParameter () private
Initialize the method parameter
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CModel::getCompartments(), CDataModel::getModel(), CDataObject::getObjectDataModel(), CCopasiParameterGroup::getParameter(), CModel::getQuantity2NumberFactor(), CCopasiParameter::getValue(), max, mpAbsoluteTolerance, mpMaxInternalSteps, mpMaxInternalStepSize, CTrajectoryMethod::mpReducedModel, mpRelativeTolerance, CCopasiParameterGroup::removeParameter(), CDataVector< CType >::size(), CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CLsodaMethod(), and elevateChildren().
maskRoots()
void CLsodaMethod::maskRoots (CVectorCore< C_FLOAT64 > & rootValues) private
Mask roots which are constant and zero.
Parameters
CVectorCore< C_FLOAT64 > & rootValues
References CVectorCore< CType >::array(), C_FLOAT64, C_INT, mRootMask, and CVectorCore< CType >::size().
Referenced by evalR().
peekAhead()
CTrajectoryMethod::Status CLsodaMethod::peekAhead () private
Peek ahead to detect simultaneous roots.
References ALL, CVectorCore< CType >::array(), C_FLOAT64, C_INT, CLsodaMethod::State::ContainerState, CTrajectoryMethod::FAILURE, CMathContainer::getRoots(), hasStateChanged(), max, mLastRootState, mLsodaStatus, CCopasiMethod::mpContainer, mPeekAheadMode, mpRelativeTolerance, mRootCounter, mRootMask, CTrajectoryMethod::mRootsFound, mSavedState, mTargetTime, mTime, CTrajectoryMethod::NORMAL, resetState(), CTrajectoryMethod::ROOT, saveState(), setRootMaskType(), CVectorCore< CType >::size(), CLsodaMethod::State::Status, and step().
Referenced by step().
resetState()
void CLsodaMethod::resetState (CLsodaMethod::State & state) private
References CLsodaMethod::State::ContainerState, CLsodaMethod::State::DWork, CLsodaMethod::State::IWork, CLsodaMethod::State::LsodaState, CTrajectoryMethod::mContainerState, mDWork, mIWork, mLSODAR, mLsodaStatus, CTrajectoryMethod::mpContainerStateTime, mRootMask, mRootMasking, CTrajectoryMethod::mRootsFound, mTime, CInternalSolver::resetState(), CTrajectoryMethod::ROOT, CLsodaMethod::State::RootMask, CLsodaMethod::State::RootMasking, CLsodaMethod::State::RootsFound, and CLsodaMethod::State::Status.
Referenced by peekAhead(), and step().
saveState()
void CLsodaMethod::saveState (CLsodaMethod::State & state, const CTrajectoryMethod::Status & status) const private
References CLsodaMethod::State::ContainerState, CLsodaMethod::State::DWork, CLsodaMethod::State::IWork, CLsodaMethod::State::LsodaState, CTrajectoryMethod::mContainerState, mDWork, mIWork, mLSODAR, CTrajectoryMethod::mpContainerStateTime, mRootMask, mRootMasking, CTrajectoryMethod::mRootsFound, mTime, CLsodaMethod::State::RootMask, CLsodaMethod::State::RootMasking, CLsodaMethod::State::RootsFound, CInternalSolver::saveState(), and CLsodaMethod::State::Status.
Referenced by peekAhead(), start(), and step().
setRootMaskType()
void CLsodaMethod::setRootMaskType (const eRootMasking & maskType) private
Set the root mask type and update the root mask accordingly
References ALL, CVectorCore< CType >::array(), CVectorCore< CType >::begin(), C_FLOAT64, C_INT, createRootMask(), DISCRETE, CVectorCore< CType >::end(), CMathContainer::getRootIsDiscrete(), CMathContainer::getRoots(), mDiscreteRoots, min, mNumRoots, CCopasiMethod::mpContainer, CTrajectoryMethod::mpReducedModel, mRootMask, mRootMasking, NONE, CVector< CType >::resize(), and CMathContainer::updateRootValues().
Referenced by peekAhead(), stateChange(), and step().
start()
void CLsodaMethod::start () virtual
This instructs the method to prepare for integration
Reimplemented from CTrajectoryMethod.
Reimplemented in CTrajectoryMethodDsaLsodar.
References CVectorCore< CType >::array(), C_INT, CLsodaMethod::State::ContainerState, destroyRootMask(), CLsodaMethod::Data::dim, CTrajectoryMethod::FAILURE, CTrajectoryProblem::getAutomaticStepSize(), CMathContainer::getCountFixedEventTargets(), CMathContainer::getRate(), CMathContainer::getRootIsDiscrete(), CMathContainer::getRoots(), CVectorCore< CType >::initialize(), CMathContainer::initializeAtolVector(), mAtol, CTrajectoryMethod::mContainerState, mData, mDiscreteRoots, mDWork, mErrorMsg, mIWork, mJType, mLastRootState, mLSODA, mLSODAR, mLsodaStatus, mNumRoots, mpAbsoluteTolerance, mpAtol, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mPeekAheadMode, mpMaxInternalSteps, mpMaxInternalStepSize, CTrajectoryMethod::mpProblem, CTrajectoryMethod::mpReducedModel, mpY, mpYdot, mRootCounter, CTrajectoryMethod::mRootsFound, mSavedState, mTargetTime, mTask, mTime, CVector< CType >::resize(), CLsodaMethod::State::RootsFound, saveState(), CInternalSolver::setOstream(), CVectorCore< CType >::size(), CTrajectoryMethod::start(), and CLsodaMethod::State::Status.
Referenced by CTSSAMethod::integrationMethodStart(), CHybridNextReactionLSODAMethod::start(), and CTrajectoryMethodDsaLsodar::start().
stateChange()
void CLsodaMethod::stateChange (const CMath::StateChange & change) virtual
Inform the trajectory method that the state has changed outside its control
Parameters
const CMath::StateChange & change
Reimplemented from CTrajectoryMethod.
Reimplemented in CTrajectoryMethodDsaLsodar.
References CVectorCore< CType >::array(), C_FLOAT64, CLsodaMethod::State::ContainerState, CMath::ContinuousSimulation, CMath::EventSimulation, CTrajectoryMethod::FAILURE, CMath::FixedEventTarget, CMathContainer::getCountFixedEventTargets(), CTrajectoryMethod::mContainerState, mLastRootState, mLsodaStatus, mNumRoots, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mPeekAheadMode, CTrajectoryMethod::mpReducedModel, mSavedState, mTime, NONE, setRootMaskType(), CMath::State, CLsodaMethod::State::Status, and CMathContainer::updateSimulatedValues().
Referenced by CTrajectoryMethodDsaLsodar::fireReaction(), CHybridNextReactionLSODAMethod::stateChange(), CTrajectoryMethodDsaLsodar::stateChange(), and step().
step()
CTrajectoryMethod::Status CLsodaMethod::step (const double & deltaT, const bool & final = false) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
const bool & final (default: false)
Returns
Status status
Reimplemented from CTrajectoryMethod.
Reimplemented in CTrajectoryMethodDsaLsodar.
References ALL, CVectorCore< CType >::array(), C_FLOAT64, C_INT, CLsodaMethod::State::ContainerState, CLsodaMethod::Data::dim, DISCRETE, EvalF(), EvalJ(), EvalR(), CCopasiMessage::EXCEPTION, CTrajectoryMethod::FAILURE, CMathContainer::getCountFixedEventTargets(), CMathContainer::getRoots(), CMathContainer::getState(), hasStateChanged(), CMathContainer::isStateValid(), CTrajectoryMethod::mContainerState, MCTrajectoryMethod, mData, mDWork, mErrorMsg, mIWork, mJType, mLastRootState, mLastSuccessState, mLSODA, mLSODAR, mLsodaStatus, mNumRoots, mpAtol, CCopasiMethod::mpContainer, CTrajectoryMethod::mpContainerStateTime, mPeekAheadMode, mpMaxInternalSteps, CTrajectoryMethod::mpReducedModel, mpRelativeTolerance, mpY, mRootCounter, mRootMask, mRootMasking, CTrajectoryMethod::mRootsFound, mSavedState, mTargetTime, mTask, mTime, NONE, CTrajectoryMethod::NORMAL, peekAhead(), resetState(), CTrajectoryMethod::ROOT, CLsodaMethod::State::RootsFound, saveState(), setRootMaskType(), CVectorCore< CType >::size(), CMath::State, stateChange(), CLsodaMethod::State::Status, and CMathContainer::updateSimulatedValues().
Referenced by CHybridNextReactionLSODAMethod::integrateDeterministicPart(), CTrajectoryMethodDsaLsodar::integrateDeterministicPart(), CTSSAMethod::integrationStep(), and peekAhead().
Member Data Documentation
mAtol
CVector< C_FLOAT64 > CLsodaMethod::mAtol private
A vector of absolute tolerances.
Referenced by hasStateChanged(), and start().
mData
Data CLsodaMethod::mData protected
mData.dim is the dimension of the ODE system. mData.pMethod contains CLsodaMethod * this to be used in the static method EvalF
Referenced by CLsodaMethod(), evalF(), CTrajectoryMethodDsaLsodar::evalF(), start(), and step().
mDiscreteRoots
CVectorCore< bool > CLsodaMethod::mDiscreteRoots private
A which indicates whether roots change only discretely.
Referenced by setRootMaskType(), and start().
mDWork
CVector< C_FLOAT64 > CLsodaMethod::mDWork private
LSODA C_FLOAT64 work area
Referenced by resetState(), saveState(), start(), and step().
mErrorMsg
std::ostringstream CLsodaMethod::mErrorMsg private
Stream to capture LSODA error messages
Referenced by start(), and step().
mIWork
CVector< C_INT > CLsodaMethod::mIWork private
LSODA C_INT work area
Referenced by resetState(), saveState(), start(), and step().
mJType
C_INT CLsodaMethod::mJType private
The way LSODA calculates the jacobian
Referenced by start(), and step().
mLastRootState
State CLsodaMethod::mLastRootState protected
The last state having a root
Referenced by peekAhead(), start(), stateChange(), and step().
mLastSuccessState
CVector< C_FLOAT64 > CLsodaMethod::mLastSuccessState protected
The state after the last successful integration step
Referenced by step().
mLSODA
CLSODA CLsodaMethod::mLSODA private
The LSODA integrator
Referenced by start(), and step().
mLSODAR
CLSODAR CLsodaMethod::mLSODAR private
The LSODA integrator
Referenced by resetState(), saveState(), start(), and step().
mLsodaStatus
C_INT CLsodaMethod::mLsodaStatus protected
LSODA state.
Referenced by peekAhead(), resetState(), start(), stateChange(), and step().
mNumRoots
C_INT CLsodaMethod::mNumRoots private
Number of roots
Referenced by setRootMaskType(), start(), stateChange(), and step().
mpAbsoluteTolerance
C_FLOAT64* CLsodaMethod::mpAbsoluteTolerance private
A pointer to the value of "Absolute Tolerance"
Referenced by initializeParameter(), and start().
mpAtol
C_FLOAT64* CLsodaMethod::mpAtol private
A pointer to the absolute tolerances excluding fixed event targets.
Referenced by start(), and step().
mPeekAheadMode
bool CLsodaMethod::mPeekAheadMode private
A Boolean indicating whether we are in peekAhead mode
Referenced by peekAhead(), start(), stateChange(), and step().
mpMaxInternalSteps
unsigned C_INT32* CLsodaMethod::mpMaxInternalSteps private
A pointer to the value of "Max Internal Steps"
Referenced by initializeParameter(), start(), and step().
mpMaxInternalStepSize
C_FLOAT64* CLsodaMethod::mpMaxInternalStepSize private
A pointer to the value of "Max Internal Step Size"
Referenced by initializeParameter(), and start().
mpRelativeTolerance
C_FLOAT64* CLsodaMethod::mpRelativeTolerance private
A pointer to the value of "Relative Tolerance"
Referenced by hasStateChanged(), initializeParameter(), peekAhead(), and step().
mpY
C_FLOAT64* CLsodaMethod::mpY private
Pointer to the array with left hand side values of the math container.
Referenced by start(), and step().
mpYdot
const C_FLOAT64* CLsodaMethod::mpYdot private
Pointer to the array with right hand side values of the math container.
Referenced by evalF(), and start().
mRootCounter
unsigned C_INT32 CLsodaMethod::mRootCounter private
Root counter to determine whether the internal step limit is exceeded.
Referenced by peekAhead(), start(), and step().
mRootMask
CVector< C_INT > CLsodaMethod::mRootMask private
A mask which hides all roots being constant and zero.
Referenced by createRootMask(), destroyRootMask(), maskRoots(), peekAhead(), resetState(), saveState(), setRootMaskType(), and step().
mRootMasking
eRootMasking CLsodaMethod::mRootMasking protected
A Boolean flag indicating whether we should try masking roots
Referenced by createRootMask(), destroyRootMask(), evalR(), resetState(), saveState(), setRootMaskType(), and step().
mSavedState
State CLsodaMethod::mSavedState private
Referenced by peekAhead(), start(), stateChange(), and step().
mTargetTime
C_FLOAT64 CLsodaMethod::mTargetTime private
Store the targeted end time to determine whether the internal step limit is exceeded.
Referenced by peekAhead(), start(), and step().
mTask
C_INT CLsodaMethod::mTask private
The task instructions to the integrator
Referenced by start(), and step().
mTime
C_FLOAT64 CLsodaMethod::mTime protected
Current time.
Referenced by peekAhead(), resetState(), saveState(), start(), stateChange(), and step().
The documentation for this class was generated from the following files:
CLsodaMethod.h
CLsodaMethod.cpp