COPASI API: decsol.cpp File Reference
decsol.cpp File Reference
#include "decsol.h"
Functions
int dec_ (integer *n, integer *ndim, doublereal *a, integer *ip, integer *ier)
int decb_ (integer *n, integer *ndim, doublereal *a, integer *ml, integer *mu, integer *ip, integer *ier)
int decbc_ (integer *n, integer *ndim, doublereal *ar, doublereal *ai, integer *ml, integer *mu, integer *ip, integer *ier)
int decc_ (integer *n, integer *ndim, doublereal *ar, doublereal *ai, integer *ip, integer *ier)
int dech_ (integer *n, integer *ndim, doublereal *a, integer *lb, integer *ip, integer *ier)
int dechc_ (integer *n, integer *ndim, doublereal *ar, doublereal *ai, integer *lb, integer *ip, integer *ier)
int elmhes_ (integer *nm, integer *n, integer *low, integer *igh, doublereal *a, integer *int__)
int sol_ (integer *n, integer *ndim, doublereal *a, doublereal *b, integer *ip)
int solb_ (integer *n, integer *ndim, doublereal *a, integer *ml, integer *mu, doublereal *b, integer *ip)
int solbc_ (integer *n, integer *ndim, doublereal *ar, doublereal *ai, integer *ml, integer *mu, doublereal *br, doublereal *bi, integer *ip)
int solc_ (integer *n, integer *ndim, doublereal *ar, doublereal *ai, doublereal *br, doublereal *bi, integer *ip)
int solh_ (integer *n, integer *ndim, doublereal *a, integer *lb, doublereal *b, integer *ip)
int solhc_ (integer *n, integer *ndim, doublereal *ar, doublereal *ai, integer *lb, doublereal *br, doublereal *bi, integer *ip)
Function Documentation
dec_()
int dec_ (integer * n, integer * ndim, doublereal * a, integer * ip, integer * ier)
Referenced by decomr_().
decb_()
int decb_ (integer * n, integer * ndim, doublereal * a, integer * ml, integer * mu, integer * ip, integer * ier)
References max, and min.
Referenced by decomr_().
decbc_()
int decbc_ (integer * n, integer * ndim, doublereal * ar, doublereal * ai, integer * ml, integer * mu, integer * ip, integer * ier)
References max, and min.
Referenced by decomc_().
decc_()
int decc_ (integer * n, integer * ndim, doublereal * ar, doublereal * ai, integer * ip, integer * ier)
Referenced by decomc_().
dech_()
int dech_ (integer * n, integer * ndim, doublereal * a, integer * lb, integer * ip, integer * ier)
References min.
Referenced by decomr_().
dechc_()
int dechc_ (integer * n, integer * ndim, doublereal * ar, doublereal * ai, integer * lb, integer * ip, integer * ier)
References min.
Referenced by decomc_().
elmhes_()
int elmhes_ (integer * nm, integer * n, integer * low, integer * igh, doublereal * a, integer * int__)
Referenced by decomr_().
sol_()
int sol_ (integer * n, integer * ndim, doublereal * a, doublereal * b, integer * ip)
Referenced by estrad_(), estrav_(), slvrad_(), slvrar_(), slvrod_(), and slvseu_().
solb_()
int solb_ (integer * n, integer * ndim, doublereal * a, integer * ml, integer * mu, doublereal * b, integer * ip)
References max, and min.
Referenced by estrad_(), estrav_(), slvrad_(), slvrar_(), slvrod_(), and slvseu_().
solbc_()
int solbc_ (integer * n, integer * ndim, doublereal * ar, doublereal * ai, integer * ml, integer * mu, doublereal * br, doublereal * bi, integer * ip)
References max, and min.
Referenced by slvrad_(), and slvrai_().
solc_()
int solc_ (integer * n, integer * ndim, doublereal * ar, doublereal * ai, doublereal * br, doublereal * bi, integer * ip)
Referenced by slvrad_(), and slvrai_().
solh_()
int solh_ (integer * n, integer * ndim, doublereal * a, integer * lb, doublereal * b, integer * ip)
References min.
Referenced by estrad_(), estrav_(), slvrad_(), slvrar_(), and slvseu_().
solhc_()
int solhc_ (integer * n, integer * ndim, doublereal * ar, doublereal * ai, integer * lb, doublereal * br, doublereal * bi, integer * ip)
References min.
Referenced by slvrad_(), and slvrai_().