COPASI API: CLRenderFlattener Class Reference
CLRenderFlattener Class Reference
#include <CLRenderFlattener.h>
Static Public Member Functions
static CLGlobalRenderInformation * flatten_render_information (const CLGlobalRenderInformation &globalRenderInformation, const CDataVector< CLGlobalRenderInformation > &globalList)
static CLLocalRenderInformation * flatten_render_information (const CLLocalRenderInformation &localRenderInformation, const CDataVector< CLLocalRenderInformation > &localList, const CDataVector< CLGlobalRenderInformation > &globalList)
Static Protected Member Functions
static CLLocalStyle * convertGlobalToLocalStyle (const CLGlobalStyle *pGlobal)
static CLRenderInformationBase * flatten (const CLRenderInformationBase &renderInformation, const CDataVector< CLGlobalRenderInformation > &globalList, const CDataVector< CLLocalRenderInformation > &localList)
Member Function Documentation
convertGlobalToLocalStyle()
CLLocalStyle * CLRenderFlattener::convertGlobalToLocalStyle (const CLGlobalStyle * pGlobal) static protected
Method takes a global style object and converts it to a local style object. The caller is responsible for freeing the memory of the returned object once it is no longer needed.
References CLStyle::getGroup(), CDataObject::getObjectName(), CLStyle::getRoleList(), CLStyle::getTypeList(), CLStyle::setGroup(), CDataObject::setObjectName(), CLStyle::setRoleList(), and CLStyle::setTypeList().
Referenced by flatten().
flatten()
CLRenderInformationBase * CLRenderFlattener::flatten (const CLRenderInformationBase & renderInformation, const CDataVector< CLGlobalRenderInformation > & globalList, const CDataVector< CLLocalRenderInformation > & localList) static protected
Takes a reference to any type of render information and two lists. The first list is a list of global render information objects, the second list is a list of local render information objects. If the object that is passed in is a global render information object, the second list is not considered.
References CLRenderInformationBase::addColorDefinition(), CLRenderInformationBase::addGradientDefinition(), CLRenderInformationBase::addLineEnding(), convertGlobalToLocalStyle(), CCopasiMessage::EXCEPTION, CLRenderInformationBase::getBackgroundColor(), CLColorDefinition::getId(), CLGradientBase::getId(), CLLineEnding::getId(), CLLocalStyle::getKeyList(), CLGlobalRenderInformation::getListOfStyles(), CLLocalRenderInformation::getListOfStyles(), CLRenderInformationBase::getReferenceRenderInformationKey(), CLStyle::getRoleList(), CLGlobalRenderInformation::getStyle(), CLLocalRenderInformation::getStyle(), CLStyle::getTypeList(), CUndoObjectInterface::insert(), CDataContainer::insert(), CLRenderInformationBase::setBackgroundColor(), and CDataVector< CType >::size().
Referenced by flatten_render_information().
flatten_render_information() [1/2]
CLGlobalRenderInformation * CLRenderFlattener::flatten_render_information (const CLGlobalRenderInformation & globalRenderInformation, const CDataVector< CLGlobalRenderInformation > & globalList) static
static method that takes a const reference to a global render information object and resolves all references. The returned object is a new global render information object and the caller is responsible for freeing the memory once it is no longer used. If references can not be resolved, an unresolved_reference_exception is thrown.
References flatten().
flatten_render_information() [2/2]
CLLocalRenderInformation * CLRenderFlattener::flatten_render_information (const CLLocalRenderInformation & localRenderInformation, const CDataVector< CLLocalRenderInformation > & localList, const CDataVector< CLGlobalRenderInformation > & globalList) static
static method that takes a const reference to a local render information object and resolves all references. The returned object is a new local render information object and the caller is responsible for freeing the memory once it is no longer used. If references can not be resolved, an unresolved_reference_exception is thrown.
References flatten().
The documentation for this class was generated from the following files:
CLRenderFlattener.h
CLRenderFlattener.cpp