COPASI API: dgemm Struct Reference
dgemm Struct Reference
#include <dgemm.h>
Public Types
typedef CMatrix< C_FLOAT64 > Matrix
typedef CVectorCore< C_FLOAT64 > Vector
Static Public Member Functions
static bool eval (const C_FLOAT64 &alpha, const Matrix &A, const Matrix &B, const C_FLOAT64 &beta, Matrix &C)
static bool eval (const C_FLOAT64 &alpha, const Matrix &A, const Vector &B, const C_FLOAT64 &beta, Vector &C)
static bool eval (const C_FLOAT64 &alpha, const Vector &A, const Matrix &B, const C_FLOAT64 &beta, Vector &C)
static bool eval (const C_FLOAT64 &alpha, const Vector &A, const Vector &B, const C_FLOAT64 &beta, C_FLOAT64 &C)
Private Member Functions
dgemm ()
Member Typedef Documentation
Matrix
typedef CMatrix< C_FLOAT64 > dgemm::Matrix
Vector
typedef CVectorCore< C_FLOAT64 > dgemm::Vector
Constructor & Destructor Documentation
dgemm()
dgemm::dgemm () private
Member Function Documentation
eval() [1/4]
bool dgemm::eval (const C_FLOAT64 & alpha, const Matrix & A, const Matrix & B, const C_FLOAT64 & beta, dgemm::Matrix & C) static
Compute C:= alpha A B + beta C
Parameters
const C_FLOAT64 & alpha
const Matrix & A
const Matrix & B
const C_FLOAT64 & beta
Matrix & C
Returns
bool success
References CMatrix< CType >::array(), C_FLOAT64, C_INT, dgemm_(), K, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), and CMatrix< CType >::resize().
Referenced by CMathContainer::calculateRootDerivatives(), CMCAMethod::calculateUnscaledConcentrationCC(), CMCAMethod::calculateUnscaledFluxCC(), and CLeastSquareSolution::solve().
eval() [2/4]
bool dgemm::eval (const C_FLOAT64 & alpha, const Matrix & A, const Vector & B, const C_FLOAT64 & beta, dgemm::Vector & C) static
Compute C:= alpha A B + beta C
Parameters
const C_FLOAT64 & alpha
const Matrix & A
const Vector & B
const C_FLOAT64 & beta
Vector & C
Returns
bool success
References CMatrix< CType >::array(), CVectorCore< CType >::array(), C_FLOAT64, C_INT, dgemm_(), K, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), and CVectorCore< CType >::size().
eval() [3/4]
bool dgemm::eval (const C_FLOAT64 & alpha, const Vector & A, const Matrix & B, const C_FLOAT64 & beta, dgemm::Vector & C) static
Compute C:= alpha A B + beta C
Parameters
const C_FLOAT64 & alpha
const Vector & A
const Matrix & B
const C_FLOAT64 & beta
Vector & C
Returns
bool success
References CMatrix< CType >::array(), CVectorCore< CType >::array(), C_FLOAT64, C_INT, dgemm_(), K, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), and CVectorCore< CType >::size().
eval() [4/4]
bool dgemm::eval (const C_FLOAT64 & alpha, const Vector & A, const Vector & B, const C_FLOAT64 & beta, C_FLOAT64 & C) static
Compute C:= alpha A B + beta C
Parameters
const C_FLOAT64 & alpha
const Vector & A
const Vector & B
const C_FLOAT64 & beta
C_FLOAT64 & C
Returns
bool success
References CVectorCore< CType >::array(), C_FLOAT64, C_INT, dgemm_(), K, and CVectorCore< CType >::size().
The documentation for this struct was generated from the following files:
dgemm.h
dgemm.cpp