COPASI API: CModelParameterSet Class Reference
CModelParameterSet Class Reference
#include <CModelParameterSet.h>
Public Member Functions
virtual void add (CModelParameter *pModelParameter)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
void assignSetContent (const CModelParameterSet &src, const bool &createMissing)
const_iterator begin () const
CModelParameterSet (const CModelParameterSet &src, const CDataContainer *pParent, const bool &createMissing=false)
CModelParameterSet (const std::string &name, const CDataContainer *pParent=NO_PARENT)
bool compareWithModel (const CCore::Framework &framework)
virtual void compile ()
void createFromModel ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual void destruct ()
const CompareResult & diff (const CModelParameterSet &other, const CCore::Framework &framework, const bool &createMissing=false)
const_iterator end () const
virtual CCommonName getCN () const
virtual size_t getIndex () const
virtual const std::string & getKey () const
CModel * getModel () const
const CModelParameter * getModelParameter (const std::string &cn) const
virtual std::string getName () const
virtual CUndoObjectInterface * insert (const CData &data)
bool isActive () const
virtual bool refreshFromModel (const bool &modifyExistence)
bool saveToStream (std::ostream &os, const CCore::Framework &framework, const std::string &mode, const std::string &separator)
void setModel (const CModel *pModel)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const
CModelParameterGroup * toGroup ()
const CModelParameterGroup * toGroup () const
virtual CModelParameterSet * toSet ()
virtual const CModelParameterSet * toSet () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual bool updateModel ()
virtual ~CModelParameterSet ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Public Member Functions inherited from CModelParameterGroup
CModelParameter * add (const CModelParameter::Type &type)
void assignGroupContent (const CModelParameterGroup &src, const bool &createMissing)
iterator begin ()
const_iterator begin () const
void clear ()
CModelParameterGroup (CModelParameterGroup *pParent, const CModelParameter::Type &type=CModelParameter::Type::Group)
CModelParameterGroup (const CModelParameterGroup &src, CModelParameterGroup *pParent, const bool &createMissing)
virtual const CompareResult & diff (const CModelParameter &other, const CCore::Framework &framework, const bool &createMissing=false)
iterator end ()
const_iterator end () const
virtual const CModelParameter * getChild (const size_t &index) const
CModelParameter * getModelParameter (const std::string &cn) const
CModelParameter * getModelParameter (const std::string &name, const CModelParameter::Type &type) const
virtual size_t getNumChildren () const
const CValidatedUnit & getObjectUnit (const CModelParameter *pModelParameter) const
void remove (CModelParameter *pModelParameter)
void remove (const size_t &index)
size_t size () const
virtual ~CModelParameterGroup ()
Public Member Functions inherited from CModelParameter
CModelParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type)
CModelParameter (const CModelParameter &src, CModelParameterGroup *pParent)
const CCommonName & getCN () const
const CompareResult & getCompareResult () const
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CModel * getModel () const
CDataObject * getObject () const
CModelParameterGroup * getParent () const
CModelParameterSet * getSet () const
const CModelEntity::Status & getSimulationType () const
const Type & getType () const
CValidatedUnit getUnit (const CCore::Framework &framework) const
virtual const double & getValue (const CCore::Framework &framework) const
bool isInitialExpressionValid () const
bool isReadOnly () const
bool operator< (const CModelParameter &rhs) const
virtual void setCN (const CCommonName &cn)
void setCompareResult (const CompareResult &compareResult)
void setInitialExpression (const std::string &initialExpression)
void setParent (CModelParameterGroup *pParent)
bool setSimulationType (const CModelEntity::Status &simulationType)
virtual void setValue (const C_FLOAT64 &value, const CCore::Framework &framework, bool updateModelIfActive=true)
virtual ~CModelParameter ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Static Public Member Functions
static CModelParameterSet * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Member Functions inherited from CModelParameter
static CModelParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Private Member Functions
void init ()
Private Attributes
std::string mKey
CModelParameterGroup * mpCompartments
CModel * mpModel
CModelParameterGroup * mpModelValues
CModelParameterGroup * mpReactions
CModelParameterGroup * mpSpecies
CModelParameterGroup * mpTimes
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Types inherited from CModelParameterGroup
typedef std::vector< CModelParameter * >::const_iterator const_iterator
typedef std::vector< CModelParameter * >::iterator iterator
Public Types inherited from CModelParameter
enum class CompareResult {
Obsolete , Missing , Modified , Conflict ,
Identical , __SIZE
}
enum class Type {
Model , Compartment , Species , ModelValue ,
ReactionParameter , Reaction , Group , Set ,
unknown , __SIZE
}
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Static Public Attributes inherited from CModelParameter
static const CEnumAnnotation< std::string, CompareResult > CompareResultNames
static const CEnumAnnotation< std::string, Type > TypeNames
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Member Functions inherited from CModelParameterGroup
CModelParameter * copy (const CModelParameter &src, const bool &createMissing)
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Protected Attributes inherited from CModelParameter
CRegisteredCommonName mCN
CompareResult mCompareResult
bool mIsInitialExpressionValid
CExpression * mpInitialExpression
CDataObject * mpObject
CModelParameterGroup * mpParent
CModelEntity::Status mSimulationType
Type mType
double mValue
Protected Attributes inherited from CAnnotation
std::string mKey
Constructor & Destructor Documentation
CModelParameterSet() [1/2]
CModelParameterSet::CModelParameterSet (const std::string & name, const CDataContainer * pParent = NO_PARENT)
Constructor
Parameters
const std::string & name
const CDataContainer * pParent (default: NULL)
References CModelParameterGroup::add(), CDataObject::getCN(), CModelParameter::Group, CAnnotation::initMiriamAnnotation(), mKey, mpCompartments, mpModelValues, mpReactions, mpSpecies, mpTimes, CModelParameter::setCN(), and setObjectParent().
Referenced by fromData().
CModelParameterSet() [2/2]
CModelParameterSet::CModelParameterSet (const CModelParameterSet & src, const CDataContainer * pParent, const bool & createMissing = false)
Copy constructor
Parameters
const CModelParameterSet & src
const CDataContainer * pParent
const bool & createMissing (default: false)
References compile(), getCN(), CAnnotation::getMiriamAnnotation(), getModel(), CModelParameterGroup::getModelParameter(), mKey, mpCompartments, mpModel, mpModelValues, mpReactions, mpSpecies, mpTimes, CAnnotation::setMiriamAnnotation(), and setObjectParent().
~CModelParameterSet()
CModelParameterSet::~CModelParameterSet () virtual
Destructor
References CRootContainer::getKeyFactory(), CModelParameter::Group, mKey, CModelParameter::mType, and CKeyFactory::remove().
Member Function Documentation
add()
void CModelParameterSet::add (CModelParameter * pModelParameter) virtual
Add the given parameter to the group. Note, the parent of the parameter is not updated
Parameters
CModelParameter * pModelParameter
Reimplemented from CModelParameterGroup.
References CModelParameterGroup::add(), CModelParameter::getCN(), getCN(), CDataObject::getCN(), CModelParameter::getType(), CModelParameter::Group, mpCompartments, mpModelValues, mpReactions, mpSpecies, mpTimes, and pdelete.
applyData()
bool CModelParameterSet::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References CAnnotation::applyData(), CModelParameterGroup::applyData(), and CDataContainer::applyData().
assignSetContent()
void CModelParameterSet::assignSetContent (const CModelParameterSet & src, const bool & createMissing)
Assign the content of the source set to this, i.e., copy all contained parameters and groups.
Parameters
const CModelParameterSet & src
const bool & createMissing
References CModelParameterGroup::assignGroupContent(), compile(), getCN(), getModelParameter(), mpCompartments, mpModelValues, mpReactions, mpSpecies, and mpTimes.
Referenced by ModelHandler::processEnd().
begin()
CModelParameterGroup::const_iterator CModelParameterSet::begin () const
Retrieve the const_iterator pointing to the first contained parameter.
Returns
const_iterator begin
References CModelParameterGroup::begin().
Referenced by CCopasiXML::saveModelParameterSets().
compareWithModel()
bool CModelParameterSet::compareWithModel (const CCore::Framework & framework)
Compare the parameter set with the assigned model
References createFromModel(), diff(), CModelParameter::Identical, and mpModel.
compile()
void CModelParameterSet::compile () virtual
Compile the parameter
Reimplemented from CModelParameterGroup.
References CModelParameterGroup::compile().
Referenced by assignSetContent(), CModelParameterSet(), createFromModel(), and updateModel().
createFromModel()
void CModelParameterSet::createFromModel ()
Create the parameter set from the assigned model
References CModelParameterGroup::add(), CModelEntity::ASSIGNMENT, CDataVector< CType >::begin(), C_FLOAT64, CModelParameterGroup::clear(), CModelParameter::Compartment, compile(), CDataVector< CType >::end(), CModelEntity::FIXED, CDataObject::getCN(), CModel::getCompartments(), CModel::getInitialTime(), CModelEntity::getInitialValue(), CModelEntity::getInitialValueReference(), CModel::getMetabolites(), CModel::getModelValues(), CModel::getReactions(), CFunctionParameter::getUsage(), CModelParameter::Model, CModelParameter::ModelValue, mpCompartments, mpModel, mpModelValues, mpReactions, mpSpecies, mpTimes, CFunctionParameter::PARAMETER, CCore::ParticleNumbers, CModelParameter::Reaction, CModelParameter::ReactionParameter, CModelParameter::setCN(), CModelParameter::setInitialExpression(), CModelParameter::setSimulationType(), CModelParameter::setValue(), and CModelParameter::Species.
Referenced by CModel::applyActiveParameterSet(), compareWithModel(), CModel::compile(), and CFitProblem::createParameterSet().
createUndoData()
void CModelParameterSet::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
References CAnnotation::createUndoData(), CModelParameterGroup::createUndoData(), and CDataContainer::createUndoData().
destruct()
void CModelParameterSet::destruct () virtual
Destruct the object
Reimplemented from CDataObject.
diff()
const CModelParameter::CompareResult & CModelParameterSet::diff (const CModelParameterSet & other, const CCore::Framework & framework, const bool & createMissing = false)
Compare the parameter to an other
Parameters
const CModelParameterSet & other
const CCore::Framework & framework
const bool & createMissing = false
References CModelParameterGroup::diff().
Referenced by compareWithModel(), and CDataModel::loadModelParameterSets().
end()
CModelParameterGroup::const_iterator CModelParameterSet::end () const
Retrieve the const_iterator pointing past the last contained parameter.
Returns
const_iterator end
References CModelParameterGroup::end().
Referenced by CCopasiXML::saveModelParameterSets().
fromData()
CModelParameterSet * CModelParameterSet::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CModelParameterSet * pDataObject
References CModelParameterSet(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getCN()
CCommonName CModelParameterSet::getCN () const virtual
Retrieve the CN of the object
Returns
CCommonName
Reimplemented from CDataObject.
References CDataObject::getCN().
Referenced by add(), assignSetContent(), and CModelParameterSet().
getIndex()
size_t CModelParameterSet::getIndex () const virtual
Retrieve the index of the parameter in the vector of children in the parent
Returns
size_t index
Reimplemented from CModelParameter.
References C_INVALID_INDEX, CDataContainer::getIndex(), and CDataObject::getObjectParent().
getKey()
const std::string & CModelParameterSet::getKey () const virtual
Retrieve the unique key of the set.
Returns
const std::string & key
Reimplemented from CAnnotation.
References mKey.
Referenced by CModel::applyActiveParameterSet(), isActive(), ModelParameterSetHandler::processEnd(), and CCopasiXML::saveModelParameterSets().
getModel()
CModel * CModelParameterSet::getModel () const
Retrieve the model the parameter set is storing values for
Returns
CModel * pModel
References mpModel.
Referenced by CModelParameterSet(), CModelParameter::getModel(), and CModelParameterSpecies::getName().
getModelParameter()
const CModelParameter * CModelParameterSet::getModelParameter (const std::string & cn) const
Retrieve a pointer to the parameter with the given CN
Parameters
const std::string & cn
Returns
const CModelParameter * pModelParameter
References CModelParameterGroup::getModelParameter().
Referenced by applyValueToParameterSet(), assignSetContent(), CUndoData::getObject(), and CModelParameter::refreshFromModel().
getName()
std::string CModelParameterSet::getName () const virtual
Retrieve the name of the parameter set
Returns
std::string name
Reimplemented from CModelParameter.
References CDataObject::getObjectName().
init()
void CModelParameterSet::init () private
insert()
CUndoObjectInterface * CModelParameterSet::insert (const CData & data) virtual
Create and insert an undo object based on the given data. This method needs to be re-implemented in container which support INSERT and REMOVE
Parameters
const CData & data
Returns
CUndoObjectInterface * pUndoObject
Reimplemented from CDataContainer.
References CModelParameterGroup::add(), CModelParameter::Compartment, CModelParameter::fromData(), CModelParameterGroup::getModelParameter(), CData::getProperty(), CModelParameterReactionParameter::getReactionCN(), CModelParameter::Group, CModelParameter::Model, CModelParameter::ModelValue, mpCompartments, mpModelValues, mpReactions, mpSpecies, mpTimes, CData::OBJECT_NAME, CData::OBJECT_TYPE, CModelParameter::Reaction, CModelParameter::ReactionParameter, CModelParameter::Set, CModelParameter::setCN(), CModelParameter::Species, toEnum(), CDataValue::toString(), CModelParameter::TypeNames, and CModelParameter::unknown.
Referenced by CModelParameterGroup::applyData().
isActive()
bool CModelParameterSet::isActive () const
Determine whether this is parameter set is currently active, i.e., it is synchronized with the model.
Returns
bool isActive
References CModel::getActiveModelParameterSet(), getKey(), mKey, and mpModel.
Referenced by CModelParameter::setValue(), CModelParameterCompartment::setValue(), and CModelParameterSpecies::setValue().
refreshFromModel()
bool CModelParameterSet::refreshFromModel (const bool & modifyExistence) virtual
Refresh the parameter from the corresponding model object
Parameters
const bool & modifyExistence
Reimplemented from CModelParameterGroup.
References CModelParameterGroup::refreshFromModel().
Referenced by CModel::refreshActiveParameterSet(), CDataModel::saveModel(), and CDataModel::saveModelToString().
saveToStream()
bool CModelParameterSet::saveToStream (std::ostream & os, const CCore::Framework & framework, const std::string & mode, const std::string & separator)
Save the parameter set to a stream
Parameters
std::ostream & os
const CCore::Framework & framework
const std::string & mode (report, ini or table)
const std::string & separator
References CNodeIteratorMode::After, CNodeIteratorMode::Before, C_FLOAT64, CCore::Concentration, CNodeContextIterator< Node, Context >::end(), CMetab::getInitialConcentrationReference(), CModelEntity::getInitialValueReference(), CDataObject::getObjectDisplayName(), CModelParameter::Group, CNodeContextIterator< Node, Context >::level(), CNodeContextIterator< Node, Context >::next(), CModelParameter::Set, and CNodeContextIterator< Node, Context >::setProcessingModes().
setModel()
void CModelParameterSet::setModel (const CModel * pModel)
Set the model the parameter set is storing values for
Parameters
const CModel * pModel
setObjectParent()
bool CModelParameterSet::setObjectParent (const CDataContainer * pParent) virtual
Set the object parent
Parameters
const CDataContainer * pParent
Returns
bool success
Reimplemented from CDataObject.
References CDataObject::getObjectAncestor(), mpModel, and CDataObject::setObjectParent().
Referenced by CModelParameterSet().
toData()
CData CModelParameterSet::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References CData::appendData(), CAnnotation::toData(), CModelParameterGroup::toData(), and CDataContainer::toData().
toGroup() [1/2]
CModelParameterGroup * CModelParameterSet::toGroup ()
Referenced by CModelParameterSpecies::compile(), CModelParameterReactionParameter::compile(), ModelParameterSetHandler::processStart(), and CModelParameterSpecies::setValue().
toGroup() [2/2]
const CModelParameterGroup * CModelParameterSet::toGroup () const
toSet() [1/2]
CModelParameterSet * CModelParameterSet::toSet () virtual
Reimplemented from CModelParameter.
toSet() [2/2]
const CModelParameterSet * CModelParameterSet::toSet () const virtual
Reimplemented from CModelParameter.
updateIndex()
void CModelParameterSet::updateIndex (const size_t & index, const CUndoObjectInterface * pUndoObject) virtual
Update the index of a contained object This method needs to be re-implemented in container which care about the order of contained objects
Parameters
const size_t & index
const CUndoObjectInterface * pUndoObject
Reimplemented from CModelParameterGroup.
References CUndoObjectInterface::updateIndex().
updateModel()
bool CModelParameterSet::updateModel () virtual
Update the corresponding model object with the current parameter settings
Reimplemented from CModelParameterGroup.
References compile(), mpModel, CCore::ParticleNumbers, CModel::updateInitialValues(), and CModelParameterGroup::updateModel().
Referenced by CModel::applyActiveParameterSet(), CDataModel::commonAfterLoad(), and SEDMLImporter::importModel().
Member Data Documentation
mKey
std::string CModelParameterSet::mKey private
The unique key of the set
Referenced by CModelParameterSet(), getKey(), isActive(), and ~CModelParameterSet().
mpCompartments
CModelParameterGroup* CModelParameterSet::mpCompartments private
Referenced by add(), assignSetContent(), CModelParameterSet(), createFromModel(), and insert().
mpModel
CModel* CModelParameterSet::mpModel private
A pointer to the model the parameter set is storing values for
Referenced by CModelParameterSet(), compareWithModel(), createFromModel(), getModel(), isActive(), setObjectParent(), and updateModel().
mpModelValues
CModelParameterGroup* CModelParameterSet::mpModelValues private
Referenced by add(), assignSetContent(), CModelParameterSet(), createFromModel(), and insert().
mpReactions
CModelParameterGroup* CModelParameterSet::mpReactions private
Referenced by add(), assignSetContent(), CModelParameterSet(), createFromModel(), and insert().
mpSpecies
CModelParameterGroup* CModelParameterSet::mpSpecies private
Referenced by add(), assignSetContent(), CModelParameterSet(), createFromModel(), and insert().
mpTimes
CModelParameterGroup* CModelParameterSet::mpTimes private
Referenced by add(), assignSetContent(), CModelParameterSet(), createFromModel(), and insert().
The documentation for this class was generated from the following files:
CModelParameterSet.h
CModelParameterSet.cpp