COPASI API: CModelVersion Class Reference
CModelVersion Class Reference
#include <CModelVersion.h>
Public Member Functions
CModelVersion ()
CModelVersion (const CModelVersion &src)
CModelVersion (const std::string &Version, const std::string &ParentName, const std::string &AuthorGivenName, const std::string &AuthorFamilyName, const std::string &AuthorOrganization, const std::string &AuthorEmail, const std::string &Comments, const std::string &Time)
CModelVersion (XMLInputStream &stream, const XMLToken &current)
const std::string & getName () const
const std::string & getParentName () const
const std::string & getUTCTimeStamp () const
virtual ~CModelVersion ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CAnnotation ()
CAnnotation (const CAnnotation &src)
void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
virtual const std::string & getKey () const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
void initMiriamAnnotation (const std::string &newId)
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
CData toData () const
virtual ~CAnnotation ()
Public Member Functions inherited from CVCard
CVCard (const CVCard &src)
CVCard (const std::string &type="")
CVCard (XMLInputStream &stream, const XMLToken &current)
const std::string & getType () const
void setType (const std::string &type)
virtual ~CVCard ()
Private Attributes
std::string mName
std::string mParentName
std::string mUTCTimeStamp
Friends
class CModelVersionHierarchy
XMLOutputStream & operator<< (XMLOutputStream &xml, const CModelVersion &version)
Additional Inherited Members
Public Types inherited from CAnnotation
typedef std::map< std::string, std::string > UnsupportedAnnotation
Static Public Member Functions inherited from CAnnotation
static CMIRIAMInfo * allocateMiriamInfo (CDataContainer *pParent)
static CAnnotation * castObject (CDataObject *pObject)
static const CAnnotation * castObject (const CDataObject *pObject)
static void freeMiriamInfo (CDataContainer *pParent)
Protected Attributes inherited from CAnnotation
std::string mKey
Constructor & Destructor Documentation
CModelVersion() [1/4]
CModelVersion::CModelVersion ()
CModelVersion() [2/4]
CModelVersion::CModelVersion (XMLInputStream & stream, const XMLToken & current)
References CVCard::CVCard(), mName, mParentName, mUTCTimeStamp, and CAnnotation::setNotes().
CModelVersion() [3/4]
CModelVersion::CModelVersion (const CModelVersion & src)
CModelVersion() [4/4]
CModelVersion::CModelVersion (const std::string & Version, const std::string & ParentName, const std::string & AuthorGivenName, const std::string & AuthorFamilyName, const std::string & AuthorOrganization, const std::string & AuthorEmail, const std::string & Comments, const std::string & Time)
References CAnnotation::setNotes().
~CModelVersion()
CModelVersion::~CModelVersion () virtual
Member Function Documentation
getName()
const std::string & CModelVersion::getName () const
References mName.
Referenced by CModelVersionHierarchy::addVersion(), CModelVersionHierarchy::getParentVersion(), and CModelVersionHierarchy::getVersionDirectory().
getParentName()
const std::string & CModelVersion::getParentName () const
References mParentName.
Referenced by CModelVersionHierarchy::addVersion().
getUTCTimeStamp()
const std::string & CModelVersion::getUTCTimeStamp () const
References mUTCTimeStamp.
Friends And Related Function Documentation
CModelVersionHierarchy
friend class CModelVersionHierarchy friend
operator<<
XMLOutputStream& operator<< (XMLOutputStream & xml, const CModelVersion & version) friend
Member Data Documentation
mName
std::string CModelVersion::mName private
Referenced by CModelVersion(), and getName().
mParentName
std::string CModelVersion::mParentName private
Referenced by CModelVersion(), and getParentName().
mUTCTimeStamp
std::string CModelVersion::mUTCTimeStamp private
Referenced by CModelVersion(), and getUTCTimeStamp().
The documentation for this class was generated from the following files:
CModelVersion.h
CModelVersion.cpp