COPASI API: CValidity Class Reference
CValidity Class Reference
#include <CValidity.h>
Public Types
typedef CFlags< CIssue::eKind > Kind
typedef CFlags< CIssue::eSeverity > Severity
Public Member Functions
void add (const CIssue &issue)
void clear ()
CValidity (CObjectInterface *pObjectInterface=NULL)
CValidity (const CValidity &src, CObjectInterface *pObjectInterface=NULL)
bool empty () const
const Kind & get (const CIssue::eSeverity &severity) const
const CIssue & getFirstWorstIssue () const
CIssue::eSeverity getHighestSeverity (const CValidity::Severity &filterSeverity=CValidity::Severity::All, const CValidity::Kind &filterKind=CValidity::Kind::All) const
const std::string getIssueMessages (const Severity &severityFilter=Severity::All, const Kind &kindFilter=Kind::All) const
CValidity & operator= (const CValidity &rhs)
CValidity & operator|= (const CValidity &rhs)
void remove (const CIssue &issue)
void remove (const CValidity::Severity &severity, const CValidity::Kind &kind)
~CValidity ()
Private Member Functions
const std::string generateIssueMessages (const CIssue::eSeverity &severity) const
Private Attributes
Kind mErrors
CIssue mFirstWorstIssue
Kind mInformation
CObjectInterface * mpObjectInterface
Kind mWarnings
Member Typedef Documentation
Kind
typedef CFlags< CIssue::eKind > CValidity::Kind
Severity
typedef CFlags< CIssue::eSeverity > CValidity::Severity
Constructor & Destructor Documentation
CValidity() [1/2]
CValidity::CValidity (CObjectInterface * pObjectInterface = NULL)
CValidity() [2/2]
CValidity::CValidity (const CValidity & src, CObjectInterface * pObjectInterface = NULL)
~CValidity()
CValidity::~CValidity ()
Member Function Documentation
add()
void CValidity::add (const CIssue & issue)
References CIssue::__SIZE, CIssue::Error, CIssue::getKind(), CIssue::getSeverity(), CIssue::Information, mErrors, mFirstWorstIssue, mInformation, mpObjectInterface, mWarnings, CObjectInterface::validityChanged(), and CIssue::Warning.
Referenced by CDataObject::addIssue(), CModelEntity::compile(), CReaction::compile(), CMathExpression::compile(), CMetab::compile(), CEventAssignment::compile(), CEvent::compile(), CExpression::compile(), CReaction::compileFunctionParameters(), CEvaluationTree::compileNodes(), CEvaluationTree::parse(), CModelEntity::setExpression(), CUnitDefinition::setExpression(), CFunction::setInfix(), CMassAction::setInfix(), CExpression::setInfix(), CModelEntity::setInitialExpression(), CModelEntity::setUnitExpression(), and CEvaluationTree::updateTree().
clear()
void CValidity::clear ()
References mErrors, mFirstWorstIssue, mInformation, mpObjectInterface, mWarnings, CIssue::Success, and CObjectInterface::validityChanged().
Referenced by CDataVector< CType >::clear(), CModelEntity::compile(), CMathExpression::compile(), CMetab::compile(), CEventAssignment::compile(), CEvent::compile(), CDataObject::refreshAggregateValidity(), CEvaluationTree::setInfix(), CMassAction::setInfix(), and CDataObject::~CDataObject().
empty()
bool CValidity::empty () const
References mErrors, mInformation, and mWarnings.
Referenced by CDataObject::validityChanged().
generateIssueMessages()
const std::string CValidity::generateIssueMessages (const CIssue::eSeverity & severity) const private
get()
const CValidity::Kind & CValidity::get (const CIssue::eSeverity & severity) const
References CIssue::Error, CIssue::Information, mErrors, mInformation, mWarnings, and CIssue::Warning.
getFirstWorstIssue()
const CIssue & CValidity::getFirstWorstIssue () const
References mFirstWorstIssue.
Referenced by CEvaluationTree::calculate(), CMassAction::compile(), CModelEntity::compile(), CMetab::compile(), CEventAssignment::compile(), CEvent::compile(), CMathObject::compileExpression(), CEvaluationTree::compileNodes(), CExpression::createInitialExpression(), and CMassAction::setInfix().
getHighestSeverity()
CIssue::eSeverity CValidity::getHighestSeverity (const CValidity::Severity & filterSeverity = CValidity::Severity::All, const CValidity::Kind & filterKind = CValidity::Kind::All) const
References CIssue::Error, CIssue::Information, CFlags< Enum >::isSet(), mErrors, mInformation, mWarnings, CIssue::Success, and CIssue::Warning.
Referenced by CMathObject::createConvertedExpression(), and COPASIHandler::processEnd().
getIssueMessages()
const std::string CValidity::getIssueMessages (const Severity & severityFilter = Severity::All, const Kind & kindFilter = Kind::All) const
References CIssue::Error, CFlags< Enum >::getAnnotations(), CIssue::Information, CFlags< Enum >::isSet(), CIssue::kindDescriptions, mErrors, mInformation, mWarnings, and CIssue::Warning.
Referenced by CDataModel::commonAfterLoad().
operator=()
CValidity & CValidity::operator= (const CValidity & rhs)
References mErrors, mInformation, mpObjectInterface, mWarnings, and CObjectInterface::validityChanged().
operator|=()
CValidity & CValidity::operator|= (const CValidity & rhs)
References mErrors, mFirstWorstIssue, mInformation, mpObjectInterface, mWarnings, and CObjectInterface::validityChanged().
remove() [1/2]
void CValidity::remove (const CIssue & issue)
References CIssue::__SIZE, CIssue::Error, CIssue::getKind(), CIssue::getSeverity(), CIssue::Information, mErrors, mFirstWorstIssue, mInformation, mpObjectInterface, mWarnings, CIssue::Success, CObjectInterface::validityChanged(), and CIssue::Warning.
Referenced by CReaction::compile(), CExpression::compile(), CReaction::compileFunctionParameters(), CEvaluationTree::compileNodes(), CEvaluationTree::parse(), CDataObject::removeIssue(), CModelEntity::setExpression(), CUnitDefinition::setExpression(), CModelEntity::setInitialExpression(), CModelEntity::setUnitExpression(), and CEvaluationTree::updateTree().
remove() [2/2]
void CValidity::remove (const CValidity::Severity & severity, const CValidity::Kind & kind)
References CIssue::Error, CIssue::Information, CFlags< Enum >::isSet(), mErrors, mInformation, mpObjectInterface, mWarnings, CObjectInterface::validityChanged(), and CIssue::Warning.
Member Data Documentation
mErrors
Kind CValidity::mErrors private
Referenced by add(), clear(), empty(), get(), getHighestSeverity(), getIssueMessages(), operator=(), operator|=(), and remove().
mFirstWorstIssue
CIssue CValidity::mFirstWorstIssue private
Referenced by add(), clear(), getFirstWorstIssue(), operator|=(), and remove().
mInformation
Kind CValidity::mInformation private
Referenced by add(), clear(), empty(), get(), getHighestSeverity(), getIssueMessages(), operator=(), operator|=(), and remove().
mpObjectInterface
CObjectInterface* CValidity::mpObjectInterface private
Referenced by add(), clear(), operator=(), operator|=(), and remove().
mWarnings
Kind CValidity::mWarnings private
Referenced by add(), clear(), empty(), get(), getHighestSeverity(), getIssueMessages(), operator=(), operator|=(), and remove().
The documentation for this class was generated from the following files:
CValidity.h
CValidity.cpp