COPASI API: CLDefaultStyles.cpp File Reference
CLDefaultStyles.cpp File Reference
#include "CLDefaultStyles.h"
#include <copasi/utilities/CDirEntry.h>
#include <copasi/commandline/COptions.h>
#include <sbml/packages/render/sbml/GlobalRenderInformation.h>
#include <sbml/xml/XMLInputStream.h>
#include <sbml/xml/XMLNode.h>
Macros
#define USE_LAYOUT 1
#define USE_RENDER 1
Functions
CLGlobalRenderInformation * getDefaultStyle (size_t index)
CDataVector< CLGlobalRenderInformation > * getDefaultStyles ()
size_t getNumDefaultStyles ()
CDataVector< CLGlobalRenderInformation > * loadDefaultStyles ()
Variables
CDataVector< CLGlobalRenderInformation > * DEFAULT_STYLES = NULL
const char * DEFAULT_STYLES_STRING
Macro Definition Documentation
USE_LAYOUT
#define USE_LAYOUT 1
USE_RENDER
#define USE_RENDER 1
Function Documentation
getDefaultStyle()
CLGlobalRenderInformation* getDefaultStyle (size_t index)
This method returns the default render information object with the requested index. If the index isinvalid, NULL is returned.
References DEFAULT_STYLES, and loadDefaultStyles().
Referenced by CSBMLExporter::exportLayout().
getDefaultStyles()
CDataVector<CLGlobalRenderInformation>* getDefaultStyles ()
This method returns a global render information list that contains the default styles which are built into the renderer.
References DEFAULT_STYLES, and loadDefaultStyles().
getNumDefaultStyles()
size_t getNumDefaultStyles ()
This method returns the number of global styles.
References DEFAULT_STYLES, loadDefaultStyles(), and CDataVector< CType >::size().
Referenced by CSBMLExporter::exportLayout().
loadDefaultStyles()
CDataVector<CLGlobalRenderInformation>* loadDefaultStyles ()
This method is used to initialize the default styles. Normally this does not need to be called since it is called automatically. The method returns a point to a ListOfGlobalRenderInformation object. The caller is responsible for freeing the memory associated with the list.
References CDataVector< CType >::add(), DEFAULT_STYLES, DEFAULT_STYLES_STRING, CDirEntry::exist(), COptions::getConfigDir(), and pdelete.
Referenced by getDefaultStyle(), getDefaultStyles(), and getNumDefaultStyles().
Variable Documentation
DEFAULT_STYLES
CDataVector<CLGlobalRenderInformation>* DEFAULT_STYLES = NULL
A pointer to the list of default styles.
Referenced by getDefaultStyle(), getDefaultStyles(), getNumDefaultStyles(), loadDefaultStyles(), and CRootContainer::~CRootContainer().
DEFAULT_STYLES_STRING
const char* DEFAULT_STYLES_STRING
Referenced by loadDefaultStyles().