COPASI API: CFixLocalReactionParameters Class Reference
CFixLocalReactionParameters Class Reference
#include <CFixLocalReactionParameters.h>
Public Member Functions
CFixLocalReactionParameters ()
void fixModel (CModel *pModel)
~CFixLocalReactionParameters ()
Private Member Functions
void changeModel ()
void checkModel ()
Private Attributes
std::multimap< CCopasiParameter *, const CExpression * > mChanges
CModel * mpModel
Constructor & Destructor Documentation
CFixLocalReactionParameters()
CFixLocalReactionParameters::CFixLocalReactionParameters ()
Constructor
~CFixLocalReactionParameters()
CFixLocalReactionParameters::~CFixLocalReactionParameters ()
Constructor
Member Function Documentation
changeModel()
void CFixLocalReactionParameters::changeModel () private
Change the model
References C_FLOAT64, C_INT32, CModel::createModelValue(), CDataObject::getCN(), CCopasiParameter::getCN(), CDataObject::getObjectAncestor(), CDataObject::getObjectName(), CCopasiParameter::getValue(), CReaction::isLocalParameter(), mChanges, MCXML, mpModel, CReaction::setParameterObjects(), and CCopasiMessage::WARNING.
Referenced by fixModel().
checkModel()
void CFixLocalReactionParameters::checkModel () private
Checks whether the model needs to be fixed and builds the listed of needed changes
References CVectorCore< CType >::array(), CDataVector< CType >::begin(), CDataVector< CType >::end(), CStateTemplate::getEntities(), CModel::getReactions(), CModel::getStateTemplate(), mChanges, mpModel, and CStateTemplate::size().
Referenced by fixModel().
fixModel()
void CFixLocalReactionParameters::fixModel (CModel * pModel)
Check and fix the given model if needed
Parameters
CModel * pModel
References changeModel(), checkModel(), mChanges, and mpModel.
Member Data Documentation
mChanges
std::multimap< CCopasiParameter *, const CExpression * > CFixLocalReactionParameters::mChanges private
Referenced by changeModel(), checkModel(), and fixModel().
mpModel
CModel* CFixLocalReactionParameters::mpModel private
The model which needs to be fixed.
Referenced by changeModel(), checkModel(), and fixModel().
The documentation for this class was generated from the following files:
CFixLocalReactionParameters.h
CFixLocalReactionParameters.cpp