COPASI API: CDataObjectMap::const_type_iterator< CType > Class Template Reference
CDataObjectMap::const_type_iterator< CType > Class Template Reference
#include <CDataObjectMap.h>
Public Member Functions
const_type_iterator ()
const_type_iterator (const CDataObjectMap::const_iterator &src)
const_type_iterator (const type_iterator< CType > &src)
bool operator!= (const const_type_iterator &rhs) const
CType * operator* () const
const_type_iterator< CType > & operator++ ()
const_type_iterator< CType > operator++ (int)
CType * operator-> () const
Additional Inherited Members
Protected Member Functions inherited from CDataObjectMap::const_iterator
const_iterator ()
const_iterator (const CDataObjectMap &map, const bool &begin)
const_iterator (const const_iterator &src)
const_iterator (const iterator &src)
bool operator!= (const const_iterator &rhs) const
CDataObject * operator* () const
const_iterator & operator++ ()
const_iterator operator++ (int)
CDataObject * operator-> () const
~const_iterator ()
Protected Attributes inherited from CDataObjectMap::const_iterator
std::map< std::string, std::set< CDataObject * > >::iterator mItName
std::set< CDataObject * >::iterator mItpObject
bool mNameEnd
bool mObjectEnd
const std::map< std::string, std::set< CDataObject * > > * mpMap
Constructor & Destructor Documentation
const_type_iterator() [1/3]
template<class CType > CDataObjectMap::const_type_iterator< CType >::const_type_iterator () inline
const_type_iterator() [2/3]
template<class CType > CDataObjectMap::const_type_iterator< CType >::const_type_iterator (const type_iterator< CType > & src) inline
const_type_iterator() [3/3]
template<class CType > CDataObjectMap::const_type_iterator< CType >::const_type_iterator (const CDataObjectMap::const_iterator & src) inline
References CDataObjectMap::const_type_iterator< CType >::operator++().
Member Function Documentation
operator!=()
template<class CType > bool CDataObjectMap::const_type_iterator< CType >::operator!= (const const_type_iterator< CType > & rhs) const inline
References CDataObjectMap::const_iterator::operator!=().
operator*()
template<class CType > CType* CDataObjectMap::const_type_iterator< CType >::operator* () const inline
References CDataObjectMap::const_iterator::operator*().
operator++() [1/2]
template<class CType > const_type_iterator< CType >& CDataObjectMap::const_type_iterator< CType >::operator++ () inline
References CDataObjectMap::const_iterator::mNameEnd, CDataObjectMap::const_iterator::mObjectEnd, and CDataObjectMap::const_iterator::operator++().
Referenced by CDataObjectMap::const_type_iterator< CType >::const_type_iterator(), and CDataObjectMap::const_type_iterator< CType >::operator++().
operator++() [2/2]
template<class CType > const_type_iterator< CType > CDataObjectMap::const_type_iterator< CType >::operator++ (int) inline
References CDataObjectMap::const_type_iterator< CType >::operator++().
operator->()
template<class CType > CType* CDataObjectMap::const_type_iterator< CType >::operator-> () const inline
References CDataObjectMap::const_iterator::operator->().
The documentation for this class was generated from the following file:
CDataObjectMap.h