COPASI API: CJitExpression Class Reference
CJitExpression Class Reference abstract
#include <CJitExpression.h>
Public Member Functions
double calculateJit ()
CJitExpression ()
CJitExpression (const CJitExpression &src)=delete
virtual void compileJit ()=0
CJitCompiler * getCompiler ()
void release ()
void setCompiler (CJitCompiler *pCompiler)
virtual ~CJitExpression ()
Protected Attributes
CJitCompiler::Function mpJitFunction
Private Attributes
CJitCompiler * mpCompiler
Constructor & Destructor Documentation
CJitExpression() [1/2]
CJitExpression::CJitExpression ()
CJitExpression() [2/2]
CJitExpression::CJitExpression (const CJitExpression & src) delete
~CJitExpression()
CJitExpression::~CJitExpression () virtual
References CJitCompiler::deregisterExpression(), and mpCompiler.
Member Function Documentation
calculateJit()
double CJitExpression::calculateJit ()
References mpJitFunction.
compileJit()
virtual void CJitExpression::compileJit () pure virtual
getCompiler()
CJitCompiler * CJitExpression::getCompiler ()
References mpCompiler.
release()
void CJitExpression::release ()
References mpJitFunction.
setCompiler()
void CJitExpression::setCompiler (CJitCompiler * pCompiler)
References CJitCompiler::deregisterExpression(), mpCompiler, mpJitFunction, and CJitCompiler::registerExpression().
Member Data Documentation
mpCompiler
CJitCompiler* CJitExpression::mpCompiler private
Referenced by getCompiler(), setCompiler(), and ~CJitExpression().
mpJitFunction
CJitCompiler::Function CJitExpression::mpJitFunction protected
Referenced by calculateJit(), release(), and setCompiler().
The documentation for this class was generated from the following files:
CJitExpression.h
CJitExpression.cpp