COPASI API: CSparseMatrixElement Class Reference
CSparseMatrixElement Class Reference
#include <CSparseMatrix.h>
Public Member Functions
const size_t & col () const
CSparseMatrixElement (CSparseMatrix &matrix, const size_t &rowIndex, const size_t &colIndex, const C_FLOAT64 &value)
operator const C_FLOAT64 & () const
const C_FLOAT64 & operator= (const C_FLOAT64 &value)
const size_t & row () const
~CSparseMatrixElement ()
Static Public Member Functions
static bool compareCol (const CSparseMatrixElement *pLhs, const CSparseMatrixElement *pRhs)
static bool compareRow (const CSparseMatrixElement *pLhs, const CSparseMatrixElement *pRhs)
Private Member Functions
CSparseMatrixElement ()
Private Attributes
const size_t & mCol
CSparseMatrix & mMatrix
const size_t & mRow
C_FLOAT64 mValue
Constructor & Destructor Documentation
CSparseMatrixElement() [1/2]
CSparseMatrixElement::CSparseMatrixElement () private
CSparseMatrixElement() [2/2]
CSparseMatrixElement::CSparseMatrixElement (CSparseMatrix & matrix, const size_t & rowIndex, const size_t & colIndex, const C_FLOAT64 & value)
~CSparseMatrixElement()
CSparseMatrixElement::~CSparseMatrixElement ()
Member Function Documentation
col()
const size_t & CSparseMatrixElement::col () const
References mCol.
compareCol()
bool CSparseMatrixElement::compareCol (const CSparseMatrixElement * pLhs, const CSparseMatrixElement * pRhs) static
References mCol.
Referenced by CSparseMatrix::insert(), CSparseMatrix::operator=(), and CSparseMatrix::remove().
compareRow()
bool CSparseMatrixElement::compareRow (const CSparseMatrixElement * pLhs, const CSparseMatrixElement * pRhs) static
References mRow.
Referenced by CSparseMatrix::insert(), CSparseMatrix::operator()(), CSparseMatrix::operator=(), and CSparseMatrix::remove().
operator const C_FLOAT64 &()
CSparseMatrixElement::operator const C_FLOAT64 & () const
operator=()
const C_FLOAT64 & CSparseMatrixElement::operator= (const C_FLOAT64 & value)
References CSparseMatrix::getTreshold(), CSparseMatrix::insert(), mCol, mMatrix, mRow, mValue, and CSparseMatrix::remove().
row()
const size_t & CSparseMatrixElement::row () const
References mRow.
Member Data Documentation
mCol
const size_t& CSparseMatrixElement::mCol private
Referenced by col(), compareCol(), and operator=().
mMatrix
CSparseMatrix& CSparseMatrixElement::mMatrix private
Referenced by operator=().
mRow
const size_t& CSparseMatrixElement::mRow private
Referenced by compareRow(), operator=(), and row().
mValue
C_FLOAT64 CSparseMatrixElement::mValue private
Referenced by operator=().
The documentation for this class was generated from the following files:
CSparseMatrix.h
CSparseMatrix.cpp