COPASI API: CTrajectoryProblem Class Reference
CTrajectoryProblem Class Reference
#include <CTrajectoryProblem.h>
Public Member Functions
CTrajectoryProblem (const CDataContainer *pParent=NO_PARENT)
CTrajectoryProblem (const CTrajectoryProblem &src, const CDataContainer *pParent)
virtual bool elevateChildren ()
bool getAutomaticStepSize () const
const C_FLOAT64 & getDuration () const
const bool & getOutputEvent () const
const C_FLOAT64 & getOutputStartTime () const
bool getStartInSteadyState () const
const unsigned C_INT32 & getStepNumber () const
const C_FLOAT64 & getStepSize () const
bool getUseValues () const
std::set< C_FLOAT64 > getValues () const
const std::string & getValueString () const
void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::NEXT)
virtual void printResult (std::ostream *ostream) const
void setAutomaticStepSize (const bool &automaticStepSize)
void setDuration (const C_FLOAT64 &duration)
void setOutputEvent (const bool &outputEvent)
void setOutputStartTime (const C_FLOAT64 &endTime)
void setStartInSteadyState (bool flag)
void setStepNumber (const unsigned C_INT32 &stepNumber)
void setStepSize (const C_FLOAT64 &stepSize)
void setTimeSeriesRequested (bool flag)
void setUseValues (bool flag)
void setValues (const std::string &values)
void setValues (const std::vector< C_FLOAT64 > &values)
bool timeSeriesRequested () const
~CTrajectoryProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CDataContainer *pParent)
virtual void clearCallBack ()
CCopasiProblem * copy () const
const CProcessReportLevel & getCallBack () const
CMathContainer * getMathContainer () const
virtual CCopasiTask * getSubTask () const
const CTaskEnum::Task & getType () const
virtual bool initialize ()
virtual void print (std::ostream *ostream) const
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReportLevel callBack)
void setMathContainer (CMathContainer *pContainer)
virtual bool setModel (CModel *model)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
void addParameter (CCopasiParameter *pParameter)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CCopasiParameterGroup * assertGroup (const std::string &name, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
template<class CType >
CType * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue, const CCopasiParameter::UserInterfaceFlag &flag=CCopasiParameter::UserInterfaceFlag::All)
index_iterator beginIndex () const
const_name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CDataContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="ParameterGroup")
void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
index_iterator endIndex () const
const_name_iterator endName () const
CCopasiParameterGroup & getElementTemplates ()
const CCopasiParameterGroup & getElementTemplates () const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
virtual size_t getIndex (const CDataObject *pObject) const
size_t getIndex (const std::string &name) const
std::string getKey (const size_t &index) const
std::string getKey (const std::string &name) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter * getParameter (std::string name)
const CCopasiParameter * getParameter (std::string name) const
CCopasiParameter::Type getType (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
template<class CType >
CType & getValue (const size_t &index)
template<class CType >
const CType & getValue (const size_t &index) const
template<class CType >
CType & getValue (const std::string &name)
template<class CType >
const CType & getValue (const std::string &name) const
bool haveTemplate () const
virtual CUndoObjectInterface * insert (const CData &data)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual bool remove (CDataObject *pObject)
bool removeParameter (CCopasiParameter *pParameter)
bool removeParameter (const size_t &index)
bool removeParameter (const std::string &name)
virtual void setUserInterfaceFlag (const UserInterfaceFlag &flag)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const std::string &name, const CType &value)
size_t size (const UserInterfaceFlag &require=UserInterfaceFlag::None, const UserInterfaceFlag &exclude=UserInterfaceFlag::None) const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CDataContainer *pParent)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CDataContainer *pParent=NO_PARENT, const std::string &objectType="Parameter")
virtual CCommonName getCN () const override
template<class CType >
const CType & getDefault () const
virtual const std::string & getKey () const override
virtual std::string getObjectDisplayName () const override
const CCopasiParameter::Type & getType () const
const UserInterfaceFlag & getUserInterfaceFlag () const
template<class CType >
std::vector< std::pair< CType, CType > > & getValidValues ()
template<class CType >
const std::vector< std::pair< CType, CType > > & getValidValues () const
void * getValidValuesPointer () const
template<class CType >
CType & getValue ()
template<class CType >
const CType & getValue () const
virtual void * getValuePointer () const override
CDataObject * getValueReference () const
bool hasValidValues () const
bool isBasic () const
bool isDefault () const
bool isEditable () const
bool isUnsupported () const
bool isValidValue (const bool &value) const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const CCommonName &value) const
template<class CType >
bool isValidValue (const CType &) const
bool isValidValue (const std::string &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
bool isValidValue (const unsigned C_INT32 &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setDefault (const CType &defaultValue)
bool setDefault (const std::vector< CCopasiParameter * > &defaultValue)
virtual bool setObjectParent (const CDataContainer *pParent) override
template<class CType , class Enum >
bool setValidValues (const CEnumAnnotation< CType, Enum > &validValues)
template<class CType >
bool setValidValues (const std::vector< std::pair< CType, CType > > &validValues)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Protected Member Functions
CTrajectoryProblem (const CTaskEnum::Task &type, const CDataContainer *pParent)
CTrajectoryProblem (const CTrajectoryProblem &src)
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src)
CCopasiProblem (const CTaskEnum::Task &type, const CDataContainer *pParent)
virtual void signalMathContainerChanged ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Protected Attributes
bool * mpAutomaticStepSize
C_FLOAT64 * mpDuration
bool * mpOutputEvent
C_FLOAT64 * mpOutputStartTime
bool * mpStartInSteadyState
unsigned C_INT32 * mpStepNumber
C_FLOAT64 * mpStepSize
bool * mpTimeSeriesRequested
bool * mpUseValues
std::string * mpValueString
bool mStepNumberSetLast
Protected Attributes inherited from CCopasiProblem
CMathContainer * mpContainer
CReport * mpReport
CProcessReportLevel mProcessReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
void * mpDefault
void * mpValidValues
void * mpValue
CDataObject * mpValueReference
UserInterfaceFlag mUserInterfaceFlag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
void initializeParameter ()
void initObjects ()
bool sync ()
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef CDataObjectMap::const_type_iterator< CCopasiParameter > const_name_iterator
typedef std::vector< CCopasiParameter * > elements
typedef elements::iterator index_iterator
typedef CDataObjectMap::type_iterator< CCopasiParameter > name_iterator
Public Types inherited from CCopasiParameter
enum class eUserInterfaceFlag { editable , basic , unsupported , __SIZE }
enum class Type {
DOUBLE = 0 , UDOUBLE , INT , UINT ,
BOOL , GROUP , STRING , CN ,
KEY , FILE , EXPRESSION , INVALID ,
__SIZE
}
typedef CFlags< eUserInterfaceFlag > UserInterfaceFlag
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CCopasiParameter
static void allocateValidValues (const Type &type, void *&pValidValues)
static void allocateValue (const Type &type, void *&pValue)
static void assignValue (const Type &type, void *&pValue, const void *pNewValue)
static void deleteValidValues (const Type &type, void *&pValidValues)
static void deleteValue (const Type &type, void *&pValue)
static CCopasiParameter * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CCopasiParameter
static const CEnumAnnotation< std::string, Type > TypeName
static const CEnumAnnotation< std::string, Type > XMLType
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Detailed Description
CTrajectoryProblem class. This class describes the trajectory problem, i.e., it allows to specify for example initial conditions and number of steps.
Created for Copasi by Stefan Hoops 2002
Constructor & Destructor Documentation
CTrajectoryProblem() [1/4]
CTrajectoryProblem::CTrajectoryProblem (const CTrajectoryProblem & src) protected
CTrajectoryProblem() [2/4]
CTrajectoryProblem::CTrajectoryProblem (const CTaskEnum::Task & type, const CDataContainer * pParent) protected
Specific constructor can be used to specify a different task type. only to be used by derived classes
CTrajectoryProblem class. This class describes the trajectory problem, i.e., it allows to specify for example initial conditions and number of steps.
Created for COPASI by Stefan Hoops 2002
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
CTrajectoryProblem() [3/4]
CTrajectoryProblem::CTrajectoryProblem (const CDataContainer * pParent = NO_PARENT)
Default constructor.
Parameters
const CDataContainer * pParent (default: NULL)
Default constructor.
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
CTrajectoryProblem() [4/4]
CTrajectoryProblem::CTrajectoryProblem (const CTrajectoryProblem & src, const CDataContainer * pParent)
Copy constructor.
Parameters
const CTrajectoryProblem & src @paramconst CDataContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CTrajectoryProblem & src
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
~CTrajectoryProblem()
CTrajectoryProblem::~CTrajectoryProblem ()
Destructor.
References DESTRUCTOR_TRACE.
Member Function Documentation
elevateChildren()
bool CTrajectoryProblem::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Reimplemented in CTimeSensProblem.
References C_FLOAT64, mpDuration, mpStepNumber, mpStepSize, and setDuration().
Referenced by CTimeSensProblem::elevateChildren().
getAutomaticStepSize()
bool CTrajectoryProblem::getAutomaticStepSize () const
Retrieve the size a integration step the trajectory method should do.
Returns
bool automaticStepSize
References mpAutomaticStepSize, and mpUseValues.
Referenced by CHybridMethodODE45::integrateDeterministicPart(), CTimeSensTask::process(), CTimeSensTask::processStep(), CTrajectoryTask::processStep(), CTrajectoryTask::processTrajectory(), CTimeSensLsodaMethod::start(), CLsodaMethod::start(), CLsodaMethod2::start(), CRadau5Method::start(), CHybridMethodODE45::step(), CStochasticRungeKuttaRI5::step(), CStochDirectMethod::step(), CStochMethod::step(), CTauLeapMethod::step(), and CTrajAdaptiveSA::step().
getDuration()
const C_FLOAT64 & CTrajectoryProblem::getDuration () const
Retrieve the end time.
Returns
"const C_FLOAT64 &" duration
References mpDuration.
Referenced by CSEDMLExporter::createTimeCourseTask(), CODEExporterBM::exportTitleData(), CODEExporterXPPAUT::exportTitleData(), CHybridMethod::isValidProblem(), CHybridMethodODE45::isValidProblem(), CStochDirectMethod::isValidProblem(), CStochMethod::isValidProblem(), CTauLeapMethod::isValidProblem(), CTrajAdaptiveSA::isValidProblem(), CTrajectoryMethodDsaLsodar::isValidProblem(), CTimeSensTask::process(), CAnalyticsTask::process(), CCrossSectionTask::process(), and CTrajectoryTask::processTrajectory().
getOutputEvent()
const bool & CTrajectoryProblem::getOutputEvent () const
Retrieve whether to do additional output for events.
References mpOutputEvent.
Referenced by CTimeSensTask::processStep(), and CTrajectoryTask::processStep().
getOutputStartTime()
const C_FLOAT64 & CTrajectoryProblem::getOutputStartTime () const
Retrieve the end time.
Returns
"const C_FLOAT64 &" endTime
References mpOutputStartTime.
Referenced by CSEDMLExporter::createTimeCourseTask(), CODEExporter::exportExpression(), CTimeSensTask::process(), CAnalyticsTask::process(), CCrossSectionTask::process(), CTrajectoryTask::processTrajectory(), CTrajectoryTask::processValues(), and SEDMLImporter::updateCopasiTaskForSimulation().
getStartInSteadyState()
bool CTrajectoryProblem::getStartInSteadyState () const
References mpStartInSteadyState.
Referenced by CTimeSensTask::initialize(), CTrajectoryTask::initialize(), CTimeSensTask::processStart(), and CTrajectoryTask::processStart().
getStepNumber()
const unsigned C_INT32 & CTrajectoryProblem::getStepNumber () const
Retrieve the number of time steps the trajectory method should integrate.
Returns
"const unsigned C_INT32 &" stepNumber
References mpStepNumber.
Referenced by CSEDMLExporter::createTimeCourseTask(), CTimeSensTask::initialize(), and CTrajectoryTask::initialize().
getStepSize()
const C_FLOAT64 & CTrajectoryProblem::getStepSize () const
Retrieve the size a integration step the trajectory method should do.
Returns
"const C_FLOAT64 &" stepSize
References mpStepSize.
Referenced by CSEDMLExporter::createTimeCourseTask(), CODEExporterBM::exportTitleData(), CODEExporterXPPAUT::exportTitleData(), CTimeSensTask::process(), and CTrajectoryTask::processTrajectory().
getUseValues()
bool CTrajectoryProblem::getUseValues () const
References mpUseValues.
Referenced by CTrajectoryTask::process().
getValues()
std::set< C_FLOAT64 > CTrajectoryProblem::getValues () const
References mpValueString, ResultParser::saveToDouble(), and ResultParser::split().
Referenced by CTrajectoryTask::processValues().
getValueString()
const std::string & CTrajectoryProblem::getValueString () const
References mpValueString.
initializeParameter()
void CTrajectoryProblem::initializeParameter () private
Initialize the method parameter
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameter::DOUBLE, mpAutomaticStepSize, mpDuration, mpOutputEvent, mpOutputStartTime, mpStartInSteadyState, mpStepNumber, mpStepSize, mpTimeSeriesRequested, mpUseValues, mpValueString, CCopasiParameter::STRING, and CCopasiParameter::UINT.
Referenced by CTrajectoryProblem().
initObjects()
void CTrajectoryProblem::initObjects () private
Referenced by CTrajectoryProblem().
load()
void CTrajectoryProblem::load (CReadConfig & configBuffer, CReadConfig::Mode mode = CReadConfig::NEXT)
Load a trajectory problem
Parameters
CReadConfig & configBuffer
"CReadConfig::Mode mode (Default: CReadConfig::NEXT)
Load a trajectory problem
Parameters
CReadConfig & configBuffer
References CReadConfig::getVariable(), CReadConfig::getVersion(), CReadConfig::LOOP, mpDuration, mpStepNumber, mStepNumberSetLast, and sync().
printResult()
void CTrajectoryProblem::printResult (std::ostream * ostream) const virtual
This is the output method for any result of a problem. The default implementation provided with CCopasiProblem. Does only print "Not implemented." To override this default behavior one needs to re-implement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
References CDataObject::getObjectParent(), CTrajectoryTask::getTimeSeries(), CTimeSeries::save(), and timeSeriesRequested().
setAutomaticStepSize()
void CTrajectoryProblem::setAutomaticStepSize (const bool & automaticStepSize)
Set the size a integration step the trajectory method should do.
Parameters
const bool & automaticStepSize
References mpAutomaticStepSize.
setDuration()
void CTrajectoryProblem::setDuration (const C_FLOAT64 & duration)
Set the end time.
Parameters
const C_FLOAT64 & duration
Set the end time.
Parameters
const C_FLOAT64 & duration @parem bool success
References mpDuration, and sync().
Referenced by CNewtonMethod::doIntegration(), elevateChildren(), and SEDMLImporter::updateCopasiTaskForSimulation().
setOutputEvent()
void CTrajectoryProblem::setOutputEvent (const bool & outputEvent)
Set whether to output events in addition to the normal steps
Parameters
const bool & outputEvent
References mpOutputEvent.
Referenced by CAnalyticsProblem::initializeParameter(), and CCrossSectionProblem::initializeParameter().
setOutputStartTime()
void CTrajectoryProblem::setOutputStartTime (const C_FLOAT64 & endTime)
Set the end time.
Parameters
const C_FLOAT64 & endTime
References mpOutputStartTime.
Referenced by SEDMLImporter::updateCopasiTaskForSimulation().
setStartInSteadyState()
void CTrajectoryProblem::setStartInSteadyState (bool flag)
References mpStartInSteadyState.
Referenced by CNewtonMethod::initialize().
setStepNumber()
void CTrajectoryProblem::setStepNumber (const unsigned C_INT32 & stepNumber)
Set the number of time steps the trajectory method should integrate.
Parameters
const unsigned C_INT32 & stepNumber
References mpStepNumber, mStepNumberSetLast, and sync().
Referenced by CNewtonMethod::doIntegration(), CNewtonMethod::initialize(), and SEDMLImporter::updateCopasiTaskForSimulation().
setStepSize()
void CTrajectoryProblem::setStepSize (const C_FLOAT64 & stepSize)
Set the size a integration step the trajectory method should do.
Parameters
const C_FLOAT64 & stepSize
References mpStepSize, mStepNumberSetLast, and sync().
setTimeSeriesRequested()
void CTrajectoryProblem::setTimeSeriesRequested (bool flag)
References mpTimeSeriesRequested.
setUseValues()
void CTrajectoryProblem::setUseValues (bool flag)
References mpUseValues.
setValues() [1/2]
void CTrajectoryProblem::setValues (const std::string & values)
References mpValueString.
Referenced by setValues().
setValues() [2/2]
void CTrajectoryProblem::setValues (const std::vector< C_FLOAT64 > & values)
References C_FLOAT64, and setValues().
sync()
bool CTrajectoryProblem::sync () private
This function synchronizes step size and number
Returns
bool success
This function synchronizes step size and number
References C_FLOAT64, C_INT32, MCTrajectoryProblem, min, mpDuration, mpStepNumber, mpStepSize, mStepNumberSetLast, and CCopasiMessage::WARNING.
Referenced by load(), setDuration(), setStepNumber(), and setStepSize().
timeSeriesRequested()
bool CTrajectoryProblem::timeSeriesRequested () const
References mpTimeSeriesRequested.
Referenced by CTimeSensTask::initialize(), CTrajectoryTask::initialize(), and printResult().
Member Data Documentation
mpAutomaticStepSize
bool* CTrajectoryProblem::mpAutomaticStepSize protected
Pointer to parameter value indicating automatic step size.
Referenced by getAutomaticStepSize(), initializeParameter(), and setAutomaticStepSize().
mpDuration
C_FLOAT64* CTrajectoryProblem::mpDuration protected
Pointer to parameter value for duration.
Referenced by elevateChildren(), getDuration(), CAnalyticsProblem::getTimeLimit(), CCrossSectionProblem::getTimeLimit(), initializeParameter(), load(), setDuration(), CAnalyticsProblem::setTimeLimit(), CCrossSectionProblem::setTimeLimit(), and sync().
mpOutputEvent
bool* CTrajectoryProblem::mpOutputEvent protected
Pointer to parameter value indicating whether events should be added to the output
Referenced by getOutputEvent(), initializeParameter(), and setOutputEvent().
mpOutputStartTime
C_FLOAT64* CTrajectoryProblem::mpOutputStartTime protected
Pointer to parameter value for output start time
Referenced by getOutputStartTime(), initializeParameter(), and setOutputStartTime().
mpStartInSteadyState
bool* CTrajectoryProblem::mpStartInSteadyState protected
Indicates whether a time course is supposed to start in a steady state realized as a CCopasiParameter
Referenced by getStartInSteadyState(), initializeParameter(), and setStartInSteadyState().
mpStepNumber
unsigned C_INT32* CTrajectoryProblem::mpStepNumber protected
Pointer to parameter value for step number
Referenced by elevateChildren(), getStepNumber(), initializeParameter(), load(), setStepNumber(), and sync().
mpStepSize
C_FLOAT64* CTrajectoryProblem::mpStepSize protected
Pointer to parameter value for step size.
Referenced by elevateChildren(), getStepSize(), initializeParameter(), setStepSize(), and sync().
mpTimeSeriesRequested
bool* CTrajectoryProblem::mpTimeSeriesRequested protected
Pointer to parameter value indicating whether a time series needs to be stored in memory
Referenced by initializeParameter(), setTimeSeriesRequested(), and timeSeriesRequested().
mpUseValues
bool* CTrajectoryProblem::mpUseValues protected
Indicates whether a time course is using a the normal trajectory or a list of values to integrate over
Referenced by getAutomaticStepSize(), getUseValues(), initializeParameter(), and setUseValues().
mpValueString
std::string* CTrajectoryProblem::mpValueString protected
the string with specific values to hit during integration
Referenced by getValues(), getValueString(), initializeParameter(), and setValues().
mStepNumberSetLast
bool CTrajectoryProblem::mStepNumberSetLast protected
Indicate whether the step number or step size was set last.
Referenced by load(), setStepNumber(), setStepSize(), and sync().
The documentation for this class was generated from the following files:
CTrajectoryProblem.h
CTrajectoryProblem.cpp