COPASI API: CReportDefinition Class Reference
CReportDefinition Class Reference
#include <CReportDefinition.h>
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
void cleanup ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
CReportDefinition (const CReportDefinition &src, const CDataContainer *pParent)
CReportDefinition (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT)
std::vector< CRegisteredCommonName > * getBodyAddr ()
const std::vector< CRegisteredCommonName > * getBodyAddr () const
const std::string & getComment () const
std::vector< CRegisteredCommonName > * getFooterAddr ()
const std::vector< CRegisteredCommonName > * getFooterAddr () const
std::vector< CRegisteredCommonName > * getHeaderAddr ()
const std::vector< CRegisteredCommonName > * getHeaderAddr () const
virtual const std::string & getKey () const
const unsigned C_INT32 & getPrecision () const
const CCopasiReportSeparator & getSeparator () const
std::vector< CRegisteredCommonName > * getTableAddr ()
const std::vector< CRegisteredCommonName > * getTableAddr () const
const CTaskEnum::Task & getTaskType () const
bool getTitle () const
bool isTable () const
bool preCompileTable (const CObjectInterface::ContainerList &listOfContainer)
void setComment (const std::string &comment)
void setIsTable (bool table)
void setPrecision (const unsigned C_INT32 &precision)
void setSeparator (const std::string &separator)
bool setTaskType (const CTaskEnum::Task &taskType)
void setTitle (bool title)
virtual CData toData () const
~CReportDefinition ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
virtual const CDataObject * getValueObject () const
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CReportDefinition * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Member Functions
CReportDefinition (const CReportDefinition &src)
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Private Member Functions
void addTableElement (const CDataObject *pObject)
Private Attributes
std::vector< CRegisteredCommonName > mBodyVector
bool mbTitle
std::string mComment
std::vector< CRegisteredCommonName > mFooterVector
std::vector< CRegisteredCommonName > mHeaderVector
std::string mKey
unsigned C_INT32 mPrecision
CCopasiReportSeparator mSeparator
bool mTable
std::vector< CRegisteredCommonName > mTableVector
CTaskEnum::Task mTaskType
Additional Inherited Members
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Constructor & Destructor Documentation
CReportDefinition() [1/3]
CReportDefinition::CReportDefinition (const CReportDefinition & src) protected
Referenced by fromData().
CReportDefinition() [2/3]
CReportDefinition::CReportDefinition (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT)
Default constructor.
CReportDefinition() [3/3]
CReportDefinition::CReportDefinition (const CReportDefinition & src, const CDataContainer * pParent)
Copy constructor.
~CReportDefinition()
CReportDefinition::~CReportDefinition ()
Destructor.
References cleanup().
Member Function Documentation
addTableElement()
void CReportDefinition::addTableElement (const CDataObject * pObject) private
This adds header and body entries for one table element (including separator if necessary)
Parameters
const CDataObject * pObject
References CDataObject::getCN(), CCommonName::getObjectName(), CDataObject::getObjectName(), CDataObject::getObjectParent(), CDataObject::getObjectType(), mBodyVector, mbTitle, mHeaderVector, and mSeparator.
Referenced by preCompileTable().
applyData()
bool CReportDefinition::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataObject.
References CDataObject::applyData(), CData::getProperty(), CData::isSetProperty(), mbTitle, mComment, mPrecision, mSeparator, mTable, mTaskType, CData::NOTES, CData::REPORT_IS_TABLE, CData::REPORT_PRECISION, CData::REPORT_SEPARATOR, CData::REPORT_SHOW_TITLE, CData::TASK_TYPE, CTaskEnum::TaskName, CTaskEnum::timeCourse, CDataValue::toBool(), CEnumAnnotation< Type, Enum >::toEnum(), CDataValue::toString(), and CDataValue::toUint().
cleanup()
void CReportDefinition::cleanup ()
cleanup
References CRootContainer::getKeyFactory(), mBodyVector, mFooterVector, mHeaderVector, mKey, mTableVector, and CKeyFactory::remove().
Referenced by ~CReportDefinition().
createUndoData()
void CReportDefinition::createUndoData (CUndoData & undoData, const CUndoData::Type & type, const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataObject.
References CUndoData::addProperty(), CUndoData::CHANGE, CDataObject::createUndoData(), CData::getProperty(), CDataString::getStaticString(), mbTitle, mComment, mPrecision, mSeparator, mTable, mTaskType, CData::NOTES, CData::REPORT_IS_TABLE, CData::REPORT_PRECISION, CData::REPORT_SEPARATOR, CData::REPORT_SHOW_TITLE, CData::TASK_TYPE, and CTaskEnum::TaskName.
fromData()
CReportDefinition * CReportDefinition::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CReportDefinition * pDataObject
CReportDefinition class. This class describes the Report Definition
Created for COPASI by Mudita Singhal
References CReportDefinition(), CData::getProperty(), NO_PARENT, CData::OBJECT_NAME, and CDataValue::toString().
getBodyAddr() [1/2]
std::vector< CRegisteredCommonName > * CReportDefinition::getBodyAddr ()
gets the body in the report tag
References mBodyVector.
Referenced by CDataModel::addReport(), CReport::compile(), CSEDMLExporter::exportReport(), SEDMLImporter::importReport(), ReportSectionHandler::processStart(), and CCopasiXML::saveReportList().
getBodyAddr() [2/2]
const std::vector< CRegisteredCommonName > * CReportDefinition::getBodyAddr () const
gets the body in the report tag
References mBodyVector.
getComment()
const std::string & CReportDefinition::getComment () const
Returns the comments in the report tag
References mComment.
Referenced by CCopasiXML::saveReportList().
getFooterAddr() [1/2]
std::vector< CRegisteredCommonName > * CReportDefinition::getFooterAddr ()
gets the footer in the report tag
References mFooterVector.
Referenced by CDataModel::addReport(), CReport::compile(), ReportSectionHandler::processStart(), and CCopasiXML::saveReportList().
getFooterAddr() [2/2]
const std::vector< CRegisteredCommonName > * CReportDefinition::getFooterAddr () const
gets the footer in the report tag
References mFooterVector.
getHeaderAddr() [1/2]
std::vector< CRegisteredCommonName > * CReportDefinition::getHeaderAddr ()
gets the header in the report tag
References mHeaderVector.
Referenced by CDataModel::addReport(), CReport::compile(), CSEDMLExporter::exportReport(), SEDMLImporter::importReport(), ReportSectionHandler::processStart(), and CCopasiXML::saveReportList().
getHeaderAddr() [2/2]
const std::vector< CRegisteredCommonName > * CReportDefinition::getHeaderAddr () const
gets the header in the report tag
References mHeaderVector.
getKey()
const std::string & CReportDefinition::getKey () const virtual
Reimplemented from CDataObject.
References mKey.
Referenced by CCopasiXML::saveReportList(), and CCopasiXML::saveTaskList().
getPrecision()
const unsigned C_INT32 & CReportDefinition::getPrecision () const
Retrieve the precsion for floating point numbers;
Returns
const unsigned C_INT32 & precision
References mPrecision.
Referenced by CReport::open(), and CCopasiXML::saveReportList().
getSeparator()
const CCopasiReportSeparator & CReportDefinition::getSeparator () const
References mSeparator.
Referenced by CSEDMLExporter::exportReport(), SEDMLImporter::importReport(), and CCopasiXML::saveReportList().
getTableAddr() [1/2]
std::vector< CRegisteredCommonName > * CReportDefinition::getTableAddr ()
gets the footer in the report tag
References mTableVector.
Referenced by COutputAssistant::createTable(), CSEDMLExporter::exportReport(), TableHandler::processEnd(), and CCopasiXML::saveReportList().
getTableAddr() [2/2]
const std::vector< CRegisteredCommonName > * CReportDefinition::getTableAddr () const
gets the footer in the report tag
References mTableVector.
getTaskType()
const CTaskEnum::Task & CReportDefinition::getTaskType () const
References mTaskType.
Referenced by CCopasiXML::saveReportList().
getTitle()
bool CReportDefinition::getTitle () const
References mbTitle.
Referenced by CCopasiXML::saveReportList().
isTable()
bool CReportDefinition::isTable () const
References mTable.
Referenced by CReport::compile(), CSEDMLExporter::exportReport(), and CCopasiXML::saveReportList().
preCompileTable()
bool CReportDefinition::preCompileTable (const CObjectInterface::ContainerList & listOfContainer)
Convert the table list into a header and body list.
Parameters
const CObjectInterface::ContainerList & listOfContainer (default: CDataContainer::EmptyList)
Returns
bool success
References addTableElement(), CObjectInterface::DataObject(), CObjectInterface::GetObjectFromCN(), mBodyVector, MCCopasiTask, mFooterVector, mHeaderVector, mTableVector, and CCopasiMessage::WARNING.
setComment()
void CReportDefinition::setComment (const std::string & comment)
sets the comments in the report tag
References mComment.
Referenced by CDataModel::addReport(), CReportDefinitionVector::createReportDefinition(), SEDMLImporter::importReport(), and ReportDefinitionHandler::processEnd().
setIsTable()
void CReportDefinition::setIsTable (bool table)
References mTable.
Referenced by CDataModel::addReport(), COutputAssistant::createTable(), SEDMLImporter::importReport(), and ReportDefinitionHandler::processStart().
setPrecision()
void CReportDefinition::setPrecision (const unsigned C_INT32 & precision)
Set the precsion for floating point numbers;
Parameters
const unsigned C_INT32 & precision
References mPrecision.
Referenced by ReportDefinitionHandler::processStart().
setSeparator()
void CReportDefinition::setSeparator (const std::string & separator)
References mSeparator.
Referenced by CDataModel::addReport(), COutputAssistant::createTable(), SEDMLImporter::importReport(), and ReportDefinitionHandler::processStart().
setTaskType()
bool CReportDefinition::setTaskType (const CTaskEnum::Task & taskType)
References mTaskType.
Referenced by CDataModel::addReport(), COutputAssistant::createTable(), and ReportDefinitionHandler::processStart().
setTitle()
void CReportDefinition::setTitle (bool title)
References mbTitle.
Referenced by CDataModel::addReport(), and TableHandler::processStart().
toData()
CData CReportDefinition::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataObject.
References CData::addProperty(), CDataString::getStaticString(), mbTitle, mComment, mPrecision, mSeparator, mTable, mTaskType, CData::NOTES, CData::REPORT_IS_TABLE, CData::REPORT_PRECISION, CData::REPORT_SEPARATOR, CData::REPORT_SHOW_TITLE, CData::TASK_TYPE, CTaskEnum::TaskName, and CDataObject::toData().
Member Data Documentation
mBodyVector
std::vector<CRegisteredCommonName> CReportDefinition::mBodyVector private
Referenced by addTableElement(), cleanup(), getBodyAddr(), and preCompileTable().
mbTitle
bool CReportDefinition::mbTitle private
Referenced by addTableElement(), applyData(), createUndoData(), getTitle(), setTitle(), and toData().
mComment
std::string CReportDefinition::mComment private
Referenced by applyData(), createUndoData(), getComment(), setComment(), and toData().
mFooterVector
std::vector<CRegisteredCommonName> CReportDefinition::mFooterVector private
Referenced by cleanup(), getFooterAddr(), and preCompileTable().
mHeaderVector
std::vector<CRegisteredCommonName> CReportDefinition::mHeaderVector private
Referenced by addTableElement(), cleanup(), getHeaderAddr(), and preCompileTable().
mKey
std::string CReportDefinition::mKey private
Referenced by cleanup(), and getKey().
mPrecision
unsigned C_INT32 CReportDefinition::mPrecision private
Referenced by applyData(), createUndoData(), getPrecision(), setPrecision(), and toData().
mSeparator
CCopasiReportSeparator CReportDefinition::mSeparator private
Referenced by addTableElement(), applyData(), createUndoData(), getSeparator(), setSeparator(), and toData().
mTable
bool CReportDefinition::mTable private
Referenced by applyData(), createUndoData(), isTable(), setIsTable(), and toData().
mTableVector
std::vector<CRegisteredCommonName> CReportDefinition::mTableVector private
Referenced by cleanup(), getTableAddr(), and preCompileTable().
mTaskType
CTaskEnum::Task CReportDefinition::mTaskType private
Referenced by applyData(), createUndoData(), getTaskType(), setTaskType(), and toData().
The documentation for this class was generated from the following files:
CReportDefinition.h
CReportDefinition.cpp