COPASI API: CLEllipse Class Reference
CLEllipse Class Reference
#include <CLEllipse.h>
Public Member Functions
CLEllipse (CDataContainer *pParent=NULL)
CLEllipse (const CLEllipse &source, CDataContainer *pParent=NULL)
CLEllipse (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &cz, const CLRelAbsVector &rx, const CLRelAbsVector &ry, CDataContainer *pParent=NULL)
CLEllipse (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &r, CDataContainer *pParent=NULL)
CLEllipse (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &rx, const CLRelAbsVector &ry, CDataContainer *pParent=NULL)
CLEllipse (const sbmlEllipse &source, CDataContainer *pParent=NULL)
CLRelAbsVector & getCX ()
const CLRelAbsVector & getCX () const
CLRelAbsVector & getCY ()
const CLRelAbsVector & getCY () const
CLRelAbsVector & getCZ ()
const CLRelAbsVector & getCZ () const
const std::string & getKey () const
CLRelAbsVector & getRX ()
const CLRelAbsVector & getRX () const
CLRelAbsVector & getRY ()
const CLRelAbsVector & getRY () const
void setCenter2D (const CLRelAbsVector &cx, const CLRelAbsVector &cy)
void setCenter3D (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &cz)
void setCX (const CLRelAbsVector &cx)
void setCY (const CLRelAbsVector &cy)
void setCZ (const CLRelAbsVector &cz)
void setRadii (const CLRelAbsVector &rx, const CLRelAbsVector &ry)
void setRX (const CLRelAbsVector &rx)
void setRY (const CLRelAbsVector &ry)
sbmlEllipse * toSBML (unsigned int level, unsigned int version) const
~CLEllipse ()
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes) override
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const std::string getUnits () const
virtual const CValidity & getValidity () const override
virtual const CDataObject * getValueObject () const
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
virtual CData toData () const override
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
virtual CUndoObjectInterface * insert (const CData &data)
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Protected Attributes
CLRelAbsVector mCX
CLRelAbsVector mCY
CLRelAbsVector mCZ
std::string mKey
CLRelAbsVector mRX
CLRelAbsVector mRY
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLEllipse & operator= (const CLEllipse &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET , NONZERO , EVENODD , INHERIT }
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLEllipse() [1/6]
CLEllipse::CLEllipse (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and setRadii().
CLEllipse() [2/6]
CLEllipse::CLEllipse (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & r, CDataContainer * pParent = NULL)
Constructor with 2D center and radius.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and setRadii().
CLEllipse() [3/6]
CLEllipse::CLEllipse (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & rx, const CLRelAbsVector & ry, CDataContainer * pParent = NULL)
Constructor with 2D center and radii.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and setRadii().
CLEllipse() [4/6]
CLEllipse::CLEllipse (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & cz, const CLRelAbsVector & rx, const CLRelAbsVector & ry, CDataContainer * pParent = NULL)
Constructor with 3D center and radii.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and setRadii().
CLEllipse() [5/6]
CLEllipse::CLEllipse (const CLEllipse & source, CDataContainer * pParent = NULL)
Copy Constructor
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
CLEllipse() [6/6]
CLEllipse::CLEllipse (const sbmlEllipse & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
~CLEllipse()
CLEllipse::~CLEllipse ()
Destructor.
Destructor
References CRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
Member Function Documentation
getCX() [1/2]
CLRelAbsVector & CLEllipse::getCX ()
Returns the x component of the center.
References mCX.
getCX() [2/2]
const CLRelAbsVector & CLEllipse::getCX () const
Returns the x component of the center.
References mCX.
Referenced by CLLayoutRenderer::draw_ellipse(), CCopasiXML::saveEllipseElement(), and toSBML().
getCY() [1/2]
CLRelAbsVector & CLEllipse::getCY ()
Returns the y component of the center.
References mCY.
getCY() [2/2]
const CLRelAbsVector & CLEllipse::getCY () const
Returns the y component of the center.
References mCY.
Referenced by CLLayoutRenderer::draw_ellipse(), CCopasiXML::saveEllipseElement(), and toSBML().
getCZ() [1/2]
CLRelAbsVector & CLEllipse::getCZ ()
Returns the z component of the center.
References mCZ.
getCZ() [2/2]
const CLRelAbsVector & CLEllipse::getCZ () const
Returns the z component of the center.
References mCZ.
Referenced by CLLayoutRenderer::draw_ellipse(), CCopasiXML::saveEllipseElement(), and toSBML().
getKey()
const std::string & CLEllipse::getKey () const virtual
Returns the key string of the object.
Returns the key of the render information
Reimplemented from CDataObject.
References mKey.
getRX() [1/2]
CLRelAbsVector & CLEllipse::getRX ()
Returns the radius along the x axis.
References mRX.
getRX() [2/2]
const CLRelAbsVector & CLEllipse::getRX () const
Returns the radius along the x axis.
References mRX.
Referenced by CLLayoutRenderer::draw_ellipse(), CCopasiXML::saveEllipseElement(), and toSBML().
getRY() [1/2]
CLRelAbsVector & CLEllipse::getRY ()
Returns the radius along the y axis.
References mRY.
getRY() [2/2]
const CLRelAbsVector & CLEllipse::getRY () const
Returns the radius along the y axis.
References mRY.
Referenced by CLLayoutRenderer::draw_ellipse(), CCopasiXML::saveEllipseElement(), and toSBML().
operator=()
CLEllipse& CLEllipse::operator= (const CLEllipse & source) private
setCenter2D()
void CLEllipse::setCenter2D (const CLRelAbsVector & cx, const CLRelAbsVector & cy)
Sets the 2D center.
References mCX, mCY, and mCZ.
setCenter3D()
void CLEllipse::setCenter3D (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & cz)
Sets the 3D center.
References mCX, mCY, and mCZ.
Referenced by EllipseHandler::processStart().
setCX()
void CLEllipse::setCX (const CLRelAbsVector & cx)
Sets the x component of the center.
References mCX.
setCY()
void CLEllipse::setCY (const CLRelAbsVector & cy)
Sets the y component of the center.
References mCY.
setCZ()
void CLEllipse::setCZ (const CLRelAbsVector & cz)
Sets the z component of the center.
References mCZ.
setRadii()
void CLEllipse::setRadii (const CLRelAbsVector & rx, const CLRelAbsVector & ry)
Sets the radii.
References mRX, and mRY.
Referenced by CLEllipse(), and EllipseHandler::processStart().
setRX()
void CLEllipse::setRX (const CLRelAbsVector & rx)
Sets the radius along the x axis.
References mRX.
setRY()
void CLEllipse::setRY (const CLRelAbsVector & ry)
Sets the radius along the y axis.
References mRY.
toSBML()
Ellipse * CLEllipse::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLGraphicalPrimitive2D::addSBMLAttributes(), getCX(), getCY(), getCZ(), getRX(), getRY(), and CLRelAbsVector::toSBML().
Member Data Documentation
mCX
CLRelAbsVector CLEllipse::mCX protected
Referenced by getCX(), setCenter2D(), setCenter3D(), and setCX().
mCY
CLRelAbsVector CLEllipse::mCY protected
Referenced by getCY(), setCenter2D(), setCenter3D(), and setCY().
mCZ
CLRelAbsVector CLEllipse::mCZ protected
Referenced by getCZ(), setCenter2D(), setCenter3D(), and setCZ().
mKey
std::string CLEllipse::mKey protected
key for the object.
Referenced by CLEllipse(), getKey(), and ~CLEllipse().
mRX
CLRelAbsVector CLEllipse::mRX protected
Referenced by getRX(), setRadii(), and setRX().
mRY
CLRelAbsVector CLEllipse::mRY protected
Referenced by getRY(), setRadii(), and setRY().
The documentation for this class was generated from the following files:
CLEllipse.h
CLEllipse.cpp