COPASI API: CLDefaultStyles.h File Reference
CLDefaultStyles.h File Reference
#include "copasi/copasi.h"
#include "copasi/core/CDataVector.h"
#include "copasi/layout/CLGlobalRenderInformation.h"
Functions
CLGlobalRenderInformation * getDefaultStyle (size_t index)
CDataVector< CLGlobalRenderInformation > * getDefaultStyles ()
size_t getNumDefaultStyles ()
CDataVector< CLGlobalRenderInformation > * loadDefaultStyles ()
Variables
CDataVector< CLGlobalRenderInformation > * DEFAULT_STYLES
Function Documentation
getDefaultStyle()
CLGlobalRenderInformation* getDefaultStyle (size_t index)
This method returns the default render information object with the requested index. If the index isinvalid, NULL is returned.
References DEFAULT_STYLES, and loadDefaultStyles().
Referenced by CSBMLExporter::exportLayout().
getDefaultStyles()
CDataVector<CLGlobalRenderInformation>* getDefaultStyles ()
This method returns a global render information list that contains the default styles which are built into the renderer.
References DEFAULT_STYLES, and loadDefaultStyles().
getNumDefaultStyles()
size_t getNumDefaultStyles ()
This method returns the number of global styles.
References DEFAULT_STYLES, loadDefaultStyles(), and CDataVector< CType >::size().
Referenced by CSBMLExporter::exportLayout().
loadDefaultStyles()
CDataVector<CLGlobalRenderInformation>* loadDefaultStyles ()
This method is used to initialize the default styles. Normally this does not need to be called since it is called automatically. The method returns a point to a ListOfGlobalRenderInformation object. The caller is responsible for freeing the memory associated with the list.
References CDataVector< CType >::add(), DEFAULT_STYLES, DEFAULT_STYLES_STRING, CDirEntry::exist(), COptions::getConfigDir(), and pdelete.
Referenced by getDefaultStyle(), getDefaultStyles(), and getNumDefaultStyles().
Variable Documentation
DEFAULT_STYLES
CDataVector<CLGlobalRenderInformation>* DEFAULT_STYLES extern
A pointer to the list of default styles.
Referenced by getDefaultStyle(), getDefaultStyles(), getNumDefaultStyles(), and loadDefaultStyles().