COPASI API: CLLineEnding Class Reference
CLLineEnding Class Reference
#include <CLLineEnding.h>
Public Member Functions
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CLLineEnding (CDataContainer *pParent=NULL)
CLLineEnding (const CLLineEnding &source, CDataContainer *pParent=NULL)
CLLineEnding (const LineEnding &source, CDataContainer *pParent=NULL)
CLBoundingBox * getBoundingBox ()
const CLBoundingBox * getBoundingBox () const
CLGroup * getGroup ()
const CLGroup * getGroup () const
const std::string & getId () const
bool getIsEnabledRotationalMapping () const
const std::string & getKey () const
void setBoundingBox (const CLBoundingBox *box)
void setEnableRotationalMapping (bool enable)
void setGroup (const CLGroup *group)
void setId (const std::string &id)
virtual CData toData () const
LineEnding * toSBML (unsigned int level, unsigned int version) const
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CLLineEnding * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Attributes
CLBoundingBox mBoundingBox
bool mEnableRotationalMapping
std::string mId
std::string mKey
CLGroup * mpGroup
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Private Member Functions
CLLineEnding & operator= (const CLLineEnding &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET , NONZERO , EVENODD , INHERIT }
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLLineEnding() [1/3]
CLLineEnding::CLLineEnding (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
Referenced by fromData().
CLLineEnding() [2/3]
CLLineEnding::CLLineEnding (const CLLineEnding & source, CDataContainer * pParent = NULL)
Copy Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), mKey, and mpGroup.
CLLineEnding() [3/3]
CLLineEnding::CLLineEnding (const LineEnding & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and mKey.
Member Function Documentation
applyData()
bool CLLineEnding::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References fatalError.
fromData()
CLLineEnding * CLLineEnding::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CLLineEnding * pDataObject
References CLLineEnding(), and NO_PARENT.
getBoundingBox() [1/2]
CLBoundingBox * CLLineEnding::getBoundingBox ()
Returns the bounding box.
References mBoundingBox.
Referenced by CLLayoutRenderer::map_arrow_head(), CCopasiXML::saveLineEnding(), and CLLayoutRenderer::update_textures_and_colors().
getBoundingBox() [2/2]
const CLBoundingBox * CLLineEnding::getBoundingBox () const
Returns the bounding box.
References mBoundingBox.
getGroup() [1/2]
CLGroup * CLLineEnding::getGroup ()
Returns the group object.
References mpGroup.
getGroup() [2/2]
const CLGroup * CLLineEnding::getGroup () const
Returns the group object.
References mpGroup.
Referenced by CLLayoutRenderer::map_arrow_head(), CCopasiXML::saveLineEnding(), and CLLayoutRenderer::update_textures_and_colors().
getId()
const std::string & CLLineEnding::getId () const
Returns the id of the object.
References mId.
Referenced by CLRenderResolver::fill_base_maps(), CLRenderFlattener::flatten(), and CCopasiXML::saveLineEnding().
getIsEnabledRotationalMapping()
bool CLLineEnding::getIsEnabledRotationalMapping () const
Returns whether rotational mapping is enabled or not.
References mEnableRotationalMapping.
Referenced by CLLayoutRenderer::map_arrow_head(), and CCopasiXML::saveLineEnding().
getKey()
const std::string & CLLineEnding::getKey () const virtual
Returns the key string for the line ending.
Reimplemented from CDataObject.
References mKey.
operator=()
CLLineEnding& CLLineEnding::operator= (const CLLineEnding & source) private
setBoundingBox()
void CLLineEnding::setBoundingBox (const CLBoundingBox * box)
Sets the bounding box.
References mBoundingBox.
Referenced by LineEndingHandler::processEnd().
setEnableRotationalMapping()
void CLLineEnding::setEnableRotationalMapping (bool enable)
Sets whether rotational mapping is to be done or not.
References mEnableRotationalMapping.
Referenced by LineEndingHandler::processStart().
setGroup()
void CLLineEnding::setGroup (const CLGroup * pGroup)
Sets the group.
References mpGroup.
Referenced by LineEndingHandler::processEnd().
setId()
void CLLineEnding::setId (const std::string & id)
Sets the id of the object.
References mId.
Referenced by LineEndingHandler::processStart().
toData()
CData CLLineEnding::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References fatalError.
toSBML()
LineEnding * CLLineEnding::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLGraphicalPrimitive2D::addSBMLAttributes(), CLBoundingBox::getDimensions(), CLBoundingBox::getPosition(), CLDimensions::getWidth(), CLPoint::getX(), mBoundingBox, mEnableRotationalMapping, mId, mpGroup, and CLGroup::toSBML().
Referenced by CLRenderInformationBase::addSBMLAttributes().
Member Data Documentation
mBoundingBox
CLBoundingBox CLLineEnding::mBoundingBox protected
Referenced by getBoundingBox(), setBoundingBox(), and toSBML().
mEnableRotationalMapping
bool CLLineEnding::mEnableRotationalMapping protected
Referenced by getIsEnabledRotationalMapping(), setEnableRotationalMapping(), and toSBML().
mId
std::string CLLineEnding::mId protected
The line ending needs an id in addition to the key. The id corresponds to the id in the SBML render extension and it does not have to be globally unique. As a matter of fact, it is sometimes needed that line ending of different render information have the same id.
Referenced by getId(), setId(), and toSBML().
mKey
std::string CLLineEnding::mKey protected
key string for the object.
Referenced by CLLineEnding(), and getKey().
mpGroup
CLGroup* CLLineEnding::mpGroup protected
Referenced by CLLineEnding(), getGroup(), setGroup(), and toSBML().
The documentation for this class was generated from the following files:
CLLineEnding.h
CLLineEnding.cpp