COPASI API: CParameterEstimationUtils.cpp File Reference
CParameterEstimationUtils.cpp File Reference
#include <algorithm>
#include <functional>
#include <cctype>
#include <copasi/CopasiDataModel/CDataModel.h>
#include <copasi/model/CModel.h>
#include <copasi/math/CMathContainer.h>
#include <copasi/parameterFitting/CFitItem.h>
#include <copasi/parameterFitting/CFitProblem.h>
#include <copasi/parameterFitting/CFitTask.h>
#include <copasi/optimization/COptItem.h>
#include <copasi/optimization/COptProblem.h>
#include <copasi/optimization/COptTask.h>
#include <copasi/utilities/CCopasiTask.h>
#include <copasi/utilities/CParameterEstimationUtils.h>
Functions
bool containsOptimization (const std::string &val)
void replaceAllSubStringsInPlace (std::string &str, const std::string &from, const std::string &to)
std::string sanitizeName (const std::string &name)
std::string & sanitizeName (std::string &name)
Function Documentation
containsOptimization()
bool containsOptimization (const std::string & val)
Referenced by ResultParser::readItems().
replaceAllSubStringsInPlace()
void replaceAllSubStringsInPlace (std::string & str, const std::string & from, const std::string & to)
Referenced by sanitizeName().
sanitizeName() [1/2]
std::string sanitizeName (const std::string & name)
References replaceAllSubStringsInPlace().
Referenced by ResultData::appliesTo(), ResultData::getItems(), ResultParser::parseItem(), and ResultData::updateFitItemsFromOptItems().
sanitizeName() [2/2]
std::string& sanitizeName (std::string & name)
References replaceAllSubStringsInPlace().