COPASI API: CLTransformation Class Reference
CLTransformation Class Reference
#include <CLTransformation.h>
Public Member Functions
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Static Public Member Functions
static const double * getIdentityMatrix ()
Static Public Attributes
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Attributes
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Constructor & Destructor Documentation
CLTransformation() [1/2]
CLTransformation::CLTransformation ()
Default constructor. All matrix elements are set to NaN
References mMatrix.
CLTransformation() [2/2]
CLTransformation::CLTransformation (const double matrix[12])
Constructor with values for the matrix.
Constructor with id and values for the matrix.
References mMatrix.
Member Function Documentation
get3DTransformationString()
std::string CLTransformation::get3DTransformationString () const
Returns a string to represent the 3D transformation.
References mMatrix.
Referenced by CCopasiXML::saveTransformationAttributes().
getIdentityMatrix()
const double * CLTransformation::getIdentityMatrix () static
Returns the 3D identity matrix. The matrix contains 12 values.
References IDENTITY3D.
Referenced by CLGroupAttributes::CLGroupAttributes(), and CLLayoutRenderer::draw_curve().
getMatrix()
const double * CLTransformation::getMatrix () const virtual
Returns the matrix.
Returns the matrix. The matrix contains 12 values.
References mMatrix.
Referenced by CLLayoutRenderer::extract_transformation_attributes().
is2DTransformation()
bool CLTransformation::is2DTransformation () const
Checks if the transformation is a 2D transformation, i.e. we have to check some of the values.
References mMatrix.
Referenced by CCopasiXML::saveTransformationAttributes().
isIdentityMatrix()
bool CLTransformation::isIdentityMatrix () const
Returns true if the matrix is the identity matrix.
References IDENTITY3D, and mMatrix.
Referenced by CCopasiXML::saveTransformationAttributes().
isSetMatrix()
bool CLTransformation::isSetMatrix () const
Returns true if the matrix has been set or false otherwise.
References mMatrix.
Referenced by CLLayoutRenderer::extract_transformation_attributes(), and CCopasiXML::saveTransformationAttributes().
parseTransformation()
void CLTransformation::parseTransformation (const std::string & transformationString) virtual
Sets the transformation matrix from the given string. The string has to contain 12 numerical values seperated by ",". Otherwise the matrix is set to the identity matrix.
Reimplemented in CLTransformation2D.
References IDENTITY3D, mMatrix, and setMatrix().
Referenced by CLTransformation2D::parseTransformation().
setMatrix()
void CLTransformation::setMatrix (const double m[12])
Sets the matrix.
References mMatrix.
Referenced by parseTransformation(), and CLTransformation2D::setMatrix().
Member Data Documentation
IDENTITY3D
const double CLTransformation::IDENTITY3D = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0} static
Referenced by CLTransformation2D::CLTransformation2D(), getIdentityMatrix(), isIdentityMatrix(), and parseTransformation().
mMatrix
double CLTransformation::mMatrix[12] protected
Referenced by CLTransformation(), CLTransformation2D::CLTransformation2D(), get3DTransformationString(), getMatrix(), is2DTransformation(), isIdentityMatrix(), isSetMatrix(), parseTransformation(), setMatrix(), CLTransformation2D::updateMatrix2D(), and CLTransformation2D::updateMatrix3D().
The documentation for this class was generated from the following files:
CLTransformation.h
CLTransformation.cpp