COPASI API: CDataVector< CType > Class Template Reference
CDataVector< CType > Class Template Reference
#include <CDataVector.h>
Classes
class const_iterator
class iterator
Public Types
typedef CDataObjectMap::const_type_iterator< CType > const_name_iterator
typedef CDataObjectMap::type_iterator< CType > name_iterator
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Public Member Functions
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool add (const CType &src)
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
iterator begin ()
const_iterator begin () const
name_iterator beginName ()
const_name_iterator beginName () const
CDataVector (const CDataVector< CType > &src, const CDataContainer *pParent)
CDataVector (const std::string &name="NoName", const CDataContainer *pParent=NO_PARENT, const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void cleanup ()
virtual void clear ()
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const
void deepCopy (const CDataVector< CType > &source)
virtual bool empty () const
iterator end ()
const_iterator end () const
name_iterator endName ()
const_name_iterator endName () const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &name) const
virtual CUndoObjectInterface * insert (const CData &data)
bool operator!= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const CDataVector< CType > &rhs)
CDataVector< CType > & operator= (const std::vector< CType * > &rhs)
CType & operator[] (const size_t &index)
const CType & operator[] (const size_t &index) const
virtual bool remove (CDataObject *pObject)
virtual void remove (const size_t &index)
virtual void resize (const size_t &newSize)
virtual size_t size () const
virtual void swap (const size_t &indexFrom, const size_t &indexTo)
virtual CData toData () const
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CDataVector ()
Public Member Functions inherited from CDataContainer
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
virtual const std::string & getKey () const
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual ~CUndoObjectInterface ()
Protected Member Functions
CDataVector (const CDataVector< CType > &src)
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Friends
std::ostream & operator<< (std::ostream &os, const CDataVector< CType > &d)
Additional Inherited Members
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Detailed Description
template<class CType>
class CDataVector< CType >
CCopasiXMLInterface class. The class CCopasiXMLInterface is the interface to various XML document containing COPASI relevant information.
Created for COPASI by Stefan Hoops 2003
Member Typedef Documentation
const_name_iterator
template<class CType > typedef CDataObjectMap::const_type_iterator< CType > CDataVector< CType >::const_name_iterator
name_iterator
template<class CType > typedef CDataObjectMap::type_iterator< CType > CDataVector< CType >::name_iterator
Constructor & Destructor Documentation
CDataVector() [1/3]
template<class CType > CDataVector< CType >::CDataVector (const CDataVector< CType > & src) protected
CDataVector() [2/3]
template<class CType > CDataVector< CType >::CDataVector (const std::string & name = "NoName", const CDataContainer * pParent = NO_PARENT, const CFlags< Flag > & flag = CFlags< Flag >::None) inline
Default constructor
Parameters
const const std::string & name (Default: "NoName")
const CDataContainer * pParent (Default: NULL)
const size_t & flag (Default: flag | CDataObject::Vector)
References CONSTRUCTOR_TRACE.
CDataVector() [3/3]
template<class CType > CDataVector< CType >::CDataVector (const CDataVector< CType > & src, const CDataContainer * pParent) inline
Copy constructor
Parameters
const CDataVector < CType > & src
const CDataContainer * pParent (Default: NULL)
References CDataVector< CType >::begin(), CONSTRUCTOR_TRACE, CCopasiMessage::EXCEPTION, MCopasiBase, and CDataVector< CType >::size().
~CDataVector()
template<class CType > virtual CDataVector< CType >::~CDataVector () inline virtual
Destructor
References CDataVector< CType >::cleanup(), and DESTRUCTOR_TRACE.
Member Function Documentation
add() [1/2]
template<class CType > virtual bool CDataVector< CType >::add (CDataObject * pObject, const bool & adopt = true) inline virtual
Add an object to the end of the vector, if adopt is true the vector. becomes the parent of the object.
Parameters
CType * src
const bool & adopt (Default: false)
Returns
bool success
Reimplemented from CDataContainer.
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, and CDataVectorN< CReportDefinition >.
References CDataContainer::add().
add() [2/2]
template<class CType > virtual bool CDataVector< CType >::add (const CType & src) inline virtual
Add a copy of the object to the end of the vector.
Parameters
const CType & src
Returns
bool success.
Reimplemented in CDataVectorN< CType >, and CDataVectorN< CEvent >.
References CDataContainer::add(), CCopasiMessage::EXCEPTION, and MCopasiBase.
Referenced by CLGroup::addChildElement(), CLRenderInformationBase::addColorDefinition(), CLayout::addCompartmentGlyph(), CRootContainer::addDatamodel(), CChemEq::addElement(), CLayout::addGeneralGlyph(), CListOfLayouts::addGlobalRenderInformation(), CLRenderInformationBase::addGradientDefinition(), CLGradientBase::addGradientStop(), CLRenderInformationBase::addLineEnding(), CLayout::addLocalRenderInformation(), CLayout::addMetaboliteGlyph(), CLReactionGlyph::addMetabReferenceGlyph(), CLayout::addReactionGlyph(), CLGeneralGlyph::addReferenceGlyph(), CLGlobalRenderInformation::addStyle(), CLLocalRenderInformation::addStyle(), CLGeneralGlyph::addSubglyph(), CLayout::addTextGlyph(), CModel::buildMoieties(), CLayout::CLayout(), CLGlobalRenderInformation::CLGlobalRenderInformation(), CLGroup::CLGroup(), CLLocalRenderInformation::CLLocalRenderInformation(), CLRenderInformationBase::CLRenderInformationBase(), CMIRIAMInfo::createBiologicalDescription(), CLRenderInformationBase::createColorDefinition(), CMIRIAMInfo::createCreator(), CLGroup::createCurve(), CMathContainer::createDiscontinuityDataEvent(), CLGroup::createEllipse(), CLGradientBase::createGradientStop(), CLGroup::createGroup(), CLGroup::createImage(), CPlotSpecification::createItem(), CLRenderInformationBase::createLinearGradientDefinition(), CLRenderInformationBase::createLineEnding(), CModel::createMetabolite(), CMIRIAMInfo::createModification(), CLGroup::createPolygon(), CLRenderInformationBase::createRadialGradientDefinition(), CLGroup::createRectangle(), CMIRIAMInfo::createReference(), CLGlobalRenderInformation::createStyle(), CLLocalRenderInformation::createStyle(), CLGroup::createText(), CModel::initializeMetabolites(), CCSPMethod::initializeOutput(), CModel::load(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), loadDefaultStyles(), CMIRIAMInfo::loadModifications(), CMIRIAMInfo::loadReferences(), CDataVector< CType >::operator=(), MetaboliteHandler::processStart(), SliderHandler::processStart(), CCSPMethod::setAnnotationM(), and CExperiment::updateFittedPoints().
applyData()
template<class CType > virtual bool CDataVector< CType >::applyData (const CData & data, CUndoData::CChangeSet & changes) inline virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, and CDataVectorN< CReportDefinition >.
References CDataVector< CType >::end(), CData::getProperty(), CDataVector< CType >::insert(), CData::OBJECT_INDEX, CDataVector< CType >::operator[](), CDataVector< CType >::size(), CDataValue::toDataVector(), and CData::VECTOR_CONTENT.
begin() [1/2]
template<class CType > iterator CDataVector< CType >::begin () inline
Referenced by CMathContainer::allocate(), CModel::appendAllDependents(), CDataModel::appendDependentTasks(), CUnitDefinitionDB::appendDependentUnits(), CModel::appendDirectDependents(), SBMLImporter::applyStoichiometricExpressions(), CLayoutState::applyTo(), CSBMLExporter::assignSBMLIdsToReactions(), CFunctionParameters::begin(), CModel::buildDependencyGraphs(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CSSAMethod::buildKineticMatrix(), CModel::buildMoieties(), CModel::buildRedStoi(), CModel::buildStateTemplate(), CModel::buildStoi(), CModel::buildUserOrder(), CDataVector< CType >::CDataVector(), CModel::changeUnitExpressionSymbols(), CSBMLExporter::checkForInitialAssignments(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), SBMLUnitSupport::checkForSpatialSizeUnits(), CFixLocalReactionParameters::checkModel(), CLayout::CLayout(), CLayoutState::CLayoutState(), CDataModel::commonAfterLoad(), CMathContainer::compile(), CModel::compile(), CReaction::compile(), CEvent::compile(), CMathEvent::compile(), CMathContainer::compileEvents(), CModel::compileEvents(), CMathObject::compilePropensity(), containsKey(), SBMLImporter::createCModelFromSBMLDocument(), CSBMLExporter::createCompartments(), SBMLImporter::createCReactionFromReaction(), COutputAssistant::createDefaultOutput(), CSBMLExporter::createEvents(), CModelParameterSet::createFromModel(), CReaction::createFunctionFromExpression(), CCopasiSpringLayout::createLayout(), CSBMLExporter::createMetabolites(), CSBMLExporter::createParameters(), CSBMLExporter::createReactions(), CDataVector< CType >::createUndoData(), CMathContainer::createValueChangeProhibited(), CDataVector< CType >::deepCopy(), CSBMLExporter::exportEventAssignments(), CDataModel::exportMathModel(), CDataModel::exportMathModelToString(), CSBMLExporter::findAvogadro(), CDataModel::findObjectByDisplayName(), CCopasiXML::fixBuild113(), CRootContainer::functionDefinitionChanged(), CUnitDefinitionDB::getAllValidUnits(), CChemEq::getCompartments(), CObjectLists::getEventTargets(), getFunctionForKey(), CObjectLists::getListOfConstObjects(), CEFMTask::getNetReactionData(), CEvent::getOriginFor(), getQuantityParameterOrValue(), CEFMTask::getSpeciesChanges(), CScanProblem::getSubTask(), CSensProblem::getSubTask(), CModel::getTreesWithDiscontinuities(), CRootContainer::getUnitDefFromSymbol(), CModel::getUnitSymbolUsage(), CFunctionDB::getUsedFunctions(), CModel::getUsedUnits(), CModel::handleUnusedMetabolites(), CSBMLExporter::hasVolumeAssignment(), SBMLImporter::importMIRIAM(), CMathReaction::initialize(), CMathContainer::initializeEvents(), CMathContainer::initializeMathObjects(), CModel::initializeMetabolites(), CSBMLExporter::isEventSBMLCompatible(), CSBMLExporter::isModelSBMLCompatible(), CLNAMethod::isValidProblem(), CMCAMethod::isValidProblem(), CTSSAMethod::isValidProblem(), CCopasiXML::mergeUnitDefinitions(), CDataModel::openCombineArchive(), CDataVector< CType >::operator!=(), CDataVector< CType >::operator=(), CEFMProblem::printResult(), CMoietiesProblem::printResult(), COPASIHandler::processEnd(), CFunctionDB::removeFunction(), CModel::replaceInExpressions(), CRootContainer::replaceSymbol(), CUnitDefinitionDB::replaceSymbol(), CCopasiXML::saveModel(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), SBMLImporter::setInitialValues(), CChemEq::setMultiplicity(), COptProblem::setSubtaskType(), CLayoutState::tagLayout(), CDataVector< CType >::toData(), CExperiment::updateFittedPointValues(), CExperiment::updateFittedPointValuesFromExtendedTimeSeries(), CModel::updateMatrixAnnotations(), and CModel::updateMoietyValues().
begin() [2/2]
template<class CType > const_iterator CDataVector< CType >::begin () const inline
beginName() [1/2]
template<class CType > name_iterator CDataVector< CType >::beginName () inline
References CDataObjectMap::begin(), and CDataContainer::mObjects.
Referenced by CFunctionParameters::begin_name(), CDataVectorN< CType >::createUndoData(), and CDataVectorN< CType >::toData().
beginName() [2/2]
template<class CType > const_name_iterator CDataVector< CType >::beginName () const inline
References CDataObjectMap::begin(), and CDataContainer::mObjects.
cleanup()
template<class CType > virtual void CDataVector< CType >::cleanup () inline virtual
Cleanup
Reimplemented in CReportDefinitionVector, and COutputDefinitionVector.
References CDataVector< CType >::clear(), and CDataContainer::remove().
Referenced by CModel::buildMoieties(), CFunctionDB::cleanup(), CFunctionParameters::cleanup(), CChemEq::cleanup(), CCompartment::cleanup(), CPlotSpecification::cleanup(), CKinFunction::createParameters(), CDataVector< CType >::deepCopy(), CSSAMethod::initialize(), CModel::load(), CDataVectorS< CType >::load(), CDataVectorNS< CType >::load(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), CMIRIAMInfo::loadModifications(), CMIRIAMInfo::loadReferences(), CDataVector< CType >::operator=(), and CDataVector< CType >::~CDataVector().
clear()
template<class CType > virtual void CDataVector< CType >::clear () inline virtual
References CValidity::clear(), CObjectInterface::mValidity, CDataContainer::remove(), and CDataVector< CType >::size().
Referenced by CDataVector< CType >::cleanup(), CModel::clearMoieties(), CMathContainer::compile(), CModel::initializeMetabolites(), CLGeneralGlyph::operator=(), COPASIHandler::processStart(), ModelHandler::processStart(), and CExperiment::updateFittedPoints().
createUndoData()
template<class CType > virtual void CDataVector< CType >::createUndoData (CUndoData & undoData, const CUndoData::Type & , const CData & oldData = CData(), const CCore::Framework & framework = CCore::Framework::ParticleNumbers) const inline virtual
Create the undo data which represents the changes recording the differences between the provided oldData and the current data.
Parameters
CUndoData & undoData
const CUndoData::Type & type
const CData & oldData (default: empty data)
const CCore::Framework & framework (default: CCore::Framework::ParticleNumbers)
Returns
CUndoData undoData
Reimplemented from CDataContainer.
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, and CDataVectorN< CReportDefinition >.
References CUndoData::addPostProcessData(), CUndoData::addPreProcessData(), CUndoData::appendData(), CDataVector< CType >::begin(), CUndoData::CHANGE, CUndoData::empty(), CDataVector< CType >::end(), CUndoData::getNewData(), CUndoData::getOldData(), CUndoData::INSERT, CUndoData::REMOVE, and CData::VECTOR_CONTENT.
deepCopy()
template<class CType > void CDataVector< CType >::deepCopy (const CDataVector< CType > & source) inline
This creates a deep copy of the source, i.e., all objects are copied and the parent of these copies is the current vector.
Parameters
const CDataVector< CType > & source
References CDataVector< CType >::begin(), CDataVector< CType >::cleanup(), CCopasiMessage::EXCEPTION, MCopasiBase, CDataVector< CType >::resize(), and CDataVector< CType >::size().
Referenced by CFunctionParameters::operator=().
empty()
template<class CType > virtual bool CDataVector< CType >::empty () const inline virtual
Returns
a boolean indicating whether vector is empty
Referenced by CMIRIAMInfo::addDefaultCreator(), SEDMLImporter::assignReportDefinitions(), CSBMLExporter::assignSBMLIdsToReactions(), CSBMLExporter::checkForEvents(), CSBMLExporter::checkForInitialAssignments(), CEvent::compile(), CSBMLExporter::createKineticLaw(), CSBMLExporter::createReaction(), CSBMLExporter::hasVolumeAssignment(), and SBMLImporter::setInitialValues().
end() [1/2]
template<class CType > iterator CDataVector< CType >::end () inline
Referenced by CMathContainer::allocate(), CModel::appendAllDependents(), CDataModel::appendDependentTasks(), CUnitDefinitionDB::appendDependentUnits(), CModel::appendDirectDependents(), CDataVector< CType >::applyData(), CDataVectorN< CType >::applyData(), SBMLImporter::applyStoichiometricExpressions(), CLayoutState::applyTo(), CSBMLExporter::assignSBMLIdsToReactions(), CModel::buildDependencyGraphs(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CSSAMethod::buildKineticMatrix(), CModel::buildStateTemplate(), CModel::buildStoi(), CModel::buildUserOrder(), CModel::changeUnitExpressionSymbols(), CSBMLExporter::checkForInitialAssignments(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), SBMLUnitSupport::checkForSpatialSizeUnits(), CFixLocalReactionParameters::checkModel(), CLayout::CLayout(), CLayoutState::CLayoutState(), CDataModel::commonAfterLoad(), CMathContainer::compile(), CModel::compile(), CReaction::compile(), CEvent::compile(), CMathEvent::compile(), CMathContainer::compileEvents(), CModel::compileEvents(), CMathObject::compilePropensity(), containsKey(), SBMLImporter::createCModelFromSBMLDocument(), CSBMLExporter::createCompartments(), SBMLImporter::createCReactionFromReaction(), COutputAssistant::createDefaultOutput(), CSBMLExporter::createEvents(), CModelParameterSet::createFromModel(), CReaction::createFunctionFromExpression(), CCopasiSpringLayout::createLayout(), CSBMLExporter::createMetabolites(), CSBMLExporter::createParameters(), CSBMLExporter::createReactions(), CDataVector< CType >::createUndoData(), CDataVectorN< CType >::createUndoData(), CMathContainer::createValueChangeProhibited(), CFunctionParameters::end(), CSBMLExporter::exportEventAssignments(), CDataModel::exportMathModel(), CDataModel::exportMathModelToString(), CSBMLExporter::findAvogadro(), CDataModel::findObjectByDisplayName(), CCopasiXML::fixBuild113(), CRootContainer::functionDefinitionChanged(), CUnitDefinitionDB::getAllValidUnits(), CChemEq::getCompartments(), CObjectLists::getEventTargets(), getFunctionForKey(), CObjectLists::getListOfConstObjects(), CEFMTask::getNetReactionData(), CEvent::getOriginFor(), getQuantityParameterOrValue(), CEFMTask::getSpeciesChanges(), CScanProblem::getSubTask(), CSensProblem::getSubTask(), CModel::getTreesWithDiscontinuities(), CModel::getUnitSymbolUsage(), CFunctionDB::getUsedFunctions(), CModel::getUsedUnits(), CSBMLExporter::hasVolumeAssignment(), SBMLImporter::importMIRIAM(), CMathReaction::initialize(), CMathContainer::initializeEvents(), CMathContainer::initializeMathObjects(), CModel::initializeMetabolites(), CSBMLExporter::isEventSBMLCompatible(), CSBMLExporter::isModelSBMLCompatible(), CLNAMethod::isValidProblem(), CMCAMethod::isValidProblem(), CTSSAMethod::isValidProblem(), CCopasiXML::mergeUnitDefinitions(), CDataModel::openCombineArchive(), CDataVector< CType >::operator!=(), CDataVector< CType >::operator=(), CEFMProblem::printResult(), CMoietiesProblem::printResult(), COPASIHandler::processEnd(), CFunctionDB::removeFunction(), CModel::replaceInExpressions(), CRootContainer::replaceSymbol(), CUnitDefinitionDB::replaceSymbol(), CCopasiXML::saveModel(), SBMLImporter::setInitialValues(), CChemEq::setMultiplicity(), COptProblem::setSubtaskType(), CLayoutState::tagLayout(), CDataVector< CType >::toData(), CExperiment::updateFittedPointValues(), CExperiment::updateFittedPointValuesFromExtendedTimeSeries(), and CModel::updateMoietyValues().
end() [2/2]
template<class CType > const_iterator CDataVector< CType >::end () const inline
endName() [1/2]
template<class CType > name_iterator CDataVector< CType >::endName () inline
References CDataObjectMap::end(), and CDataContainer::mObjects.
Referenced by CDataVectorN< CType >::createUndoData(), CFunctionParameters::end_name(), and CDataVectorN< CType >::toData().
endName() [2/2]
template<class CType > const_name_iterator CDataVector< CType >::endName () const inline
References CDataObjectMap::end(), and CDataContainer::mObjects.
getIndex()
template<class CType > virtual size_t CDataVector< CType >::getIndex (const CDataObject * pObject) const inline virtual
Retrieve the index of the pointed to object in the vector. If the object is not found C_INVALID_INDEX is returned.
Parameters
const CDataObject * pObject
Returns
size_t index
Reimplemented from CDataContainer.
References CDataContainer::getIndex(), and CDataVector< CType >::size().
Referenced by CReactionInterface::createUndoData(), CDataVectorN< CType >::createUndoData(), getReactionIndex(), CDataVector< CType >::insert(), CDataVector< CType >::remove(), COutputDefinitionVector::removePlotSpec(), CReportDefinitionVector::removeReportDefinition(), and CDataVector< CType >::updateIndex().
getObject()
template<class CType > virtual const CObjectInterface* CDataVector< CType >::getObject (const CCommonName & name) const inline virtual
Retrieve a the CDataObject with the given name.
Parameters
const CCommonName &name
Returns
const CObjectInterface * object
Reimplemented from CDataContainer.
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, and CDataVectorN< CReportDefinition >.
References CCommonName::getElementIndex(), CDataContainer::getObject(), CDataObject::getObject(), CCommonName::getRemainder(), and CDataVector< CType >::size().
Referenced by COutputAssistant::createDefaultOutput(), CObjectLists::getListOfConstObjects(), and CDataVectorN< CType >::getObject().
insert()
template<class CType > virtual CUndoObjectInterface* CDataVector< CType >::insert (const CData & data) inline virtual
Create and insert an undo object based on the given data. This method needs to be re-implemented in container which support INSERT and REMOVE
Parameters
const CData & data
Returns
CUndoObjectInterface * pUndoObject
Reimplemented from CDataContainer.
References CDataContainer::add(), C_INVALID_INDEX, CDataVector< CType >::getIndex(), CData::getProperty(), CData::isSetProperty(), min, CData::OBJECT_INDEX, CData::OBJECT_POINTER, CData::OBJECT_REFERENCE_INDEX, CData::OBJECT_TYPE, CDataValue::toSizeT(), CDataValue::toString(), CDataValue::toVoidPointer(), and CDataVector< CType >::updateIndex().
Referenced by CDataVector< CType >::applyData(), CDataVectorN< CType >::applyData(), CLGeneralGlyph::exportToSBML(), CLayout::exportToSBML(), CLReactionGlyph::exportToSBML(), CFunctionDB::removeFunction(), and CLLayoutRenderer::setDeduceSpeciesReferenceRoles().
operator!=()
template<class CType > bool CDataVector< CType >::operator!= (const CDataVector< CType > & rhs) inline
References CDataVector< CType >::begin(), CDataVector< CType >::end(), and CDataVector< CType >::size().
operator=() [1/2]
template<class CType > CDataVector< CType >& CDataVector< CType >::operator= (const CDataVector< CType > & rhs) inline
Assignment operator.
Parameters
const CDataVector< CType > & rhs
Returns
CDataVector< CType > & lhs
References CDataVector< CType >::add(), CDataVector< CType >::begin(), CDataVector< CType >::cleanup(), and CDataVector< CType >::end().
Referenced by CDataVectorN< CType >::operator=().
operator=() [2/2]
template<class CType > CDataVector< CType >& CDataVector< CType >::operator= (const std::vector< CType * > & rhs) inline
Assignment operator. The effect of this operator is that both vectors will share the same objects. However, the parentship of the objects is not affected This means that the assigned vector must be used with some care.
Parameters
const std::vector< CType * > & rhs
Returns
CDataVector< CType > & lhs
References CDataVector< CType >::add(), CDataVector< CType >::cleanup(), and CDataVector< CType >::end().
operator[]() [1/2]
template<class CType > CType& CDataVector< CType >::operator[] (const size_t & index) inline
Retrieve the indexed object.
Parameters
const size_t & index
Returns
value_type & object
References CCopasiMessage::EXCEPTION, MCDataVector, and CDataVector< CType >::size().
operator[]() [2/2]
template<class CType > const CType& CDataVector< CType >::operator[] (const size_t & index) const inline
Retrieve the indexed object.
Parameters
const size_t & index
Returns
const value_type & object
References CCopasiMessage::EXCEPTION, MCDataVector, and CDataVector< CType >::size().
Referenced by CDataVector< CType >::applyData(), and CDataVectorN< CType >::operator[]().
remove() [1/2]
template<class CType > virtual bool CDataVector< CType >::remove (CDataObject * pObject) inline virtual
Removes the pointer to the object, from the vector
Parameters
CDataObject * pObject
Returns
bool success
Reimplemented from CDataContainer.
Reimplemented in CUnitDefinitionDB.
References C_INVALID_INDEX, CDataVector< CType >::getIndex(), and CDataContainer::remove().
remove() [2/2]
template<class CType > virtual void CDataVector< CType >::remove (const size_t & index) inline virtual
Removes the index-th element from the vector
Parameters
const size_t & index
Reimplemented in CUnitDefinitionDB.
References CDataContainer::remove(), and CDataVector< CType >::size().
Referenced by CUnitDefinitionDB::remove(), CDataVectorN< CType >::remove(), CMIRIAMInfo::removeBiologicalDescription(), CLRenderInformationBase::removeColorDefinition(), CMIRIAMInfo::removeCreator(), CRootContainer::removeDatamodel(), CLRenderInformationBase::removeGradientDefinition(), CLRenderInformationBase::removeLineEnding(), CModel::removeMetabolite(), CMIRIAMInfo::removeModification(), COutputDefinitionVector::removePlotSpec(), CMIRIAMInfo::removeReference(), and CReportDefinitionVector::removeReportDefinition().
resize()
template<class CType > virtual void CDataVector< CType >::resize (const size_t & newSize) inline virtual
Resizes the vector but does not create new member objects
Parameters
const size_t & newSize
References CDataContainer::remove(), and CDataVector< CType >::size().
Referenced by CDataVector< CType >::deepCopy(), CDataVectorS< CType >::load(), CDataVectorNS< CType >::load(), and CCSPMethod::start().
size()
template<class CType > virtual size_t CDataVector< CType >::size () const inline virtual
Retrieves the size of the vector
Returns
size_t size
Referenced by CModelAdd::addCompartments(), CModelAdd::addCompartmentsExpressions(), CChemEq::addElement(), CModelAdd::addEvents(), CModelAdd::addMetabolites(), CModelAdd::addMetabolitesExpressions(), CDataModel::addModel(), CModelAdd::addModelValues(), CModelAdd::addModelValuesExpressions(), CModelAdd::addReactions(), CLGradientBase::addSBMLAttributes(), CLRenderInformationBase::addSBMLAttributes(), CMathContainer::allocate(), CMathEvent::allocate(), CDataVector< CType >::applyData(), CSSAMethod::buildKineticMatrix(), CModel::buildStateTemplate(), CModel::buildStoi(), CModel::buildUserOrder(), CLayout::calculateBoundingBox(), CDataVector< CType >::CDataVector(), CSBMLExporter::checkForPiecewiseFunctions(), CHybridMethod::checkModel(), CHybridMethodODE45::checkModel(), CModelAnalyzer::checkReaction(), CDataVector< CType >::clear(), CLGeneralGlyph::CLGeneralGlyph(), CLGroup::CLGroup(), CSBMLExporter::collectIds(), CChemEqInterface::completeCompartments(), CReactionInterface::connectNonMetabolites(), CModel::convert2NonReversible(), SBMLDocumentLoader::convertRenderInformationReferencesIds(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCModelFromSBMLDocument(), SBMLImporter::createCReactionFromReaction(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), CCopasiSpringLayout::createLayout(), CModel::createMetabolite(), CKinFunction::createParameters(), COutputDefinitionVector::createPlotSpec(), CLayoutInitializer::createReactionGlyph(), CXMLParserData::createRenderInformation(), CReportDefinitionVector::createReportDefinition(), CSBMLExporter::createSBMLDocument(), CSBMLExporter::createTimesTree(), CDataVector< CType >::deepCopy(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), CFitProblem::elevateChildren(), CObjectLists::existsFixedMetab(), CODEExporter::exportCompartments(), CODEExporter::exportKineticFunction(), CODEExporterC::exportKineticFunctionGroup(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelValues(), CODEExporter::exportModelValuesExpressions(), CSEDMLExporter::exportNthPlot(), CODEExporter::exportODEs(), CODEExporter::exportReacParamsAndFuncs(), CODEExporterC::exportTitleData(), CLayout::exportToDotFile(), CLGeneralGlyph::exportToSBML(), CLayout::exportToSBML(), CListOfLayouts::exportToSBML(), CLReactionGlyph::exportToSBML(), CCopasiSpringLayout::finalizeState(), SBMLImporter::findCorrespondingFunction(), findFunction(), CFunctionDB::findLoadFunction(), CModel::findMoiety(), CFunctionParameters::findParameterByName(), CLRenderFlattener::flatten(), CLRenderInformationBase::getColorDefinition(), CChemEqInterface::getCompartment(), CMetabNameInterface::getDisplayName(), CLGroup::getElement(), ResultData::getFitTask(), CLRenderInformationBase::getGradientDefinition(), CLGradientBase::getGradientStop(), CDataVector< CType >::getIndex(), CDataVectorN< CType >::getIndex(), CChemEq::getLargestCompartment(), CLRenderInformationBase::getLineEnding(), CChemEq::getMolecularity(), CFunctionParameters::getNumberOfParametersByUsage(), CLRenderInformationBase::getNumColorDefinitions(), getNumDefaultStyles(), CLGroup::getNumElements(), CLRenderInformationBase::getNumGradientDefinitions(), CLGradientBase::getNumGradientStops(), CLRenderInformationBase::getNumLineEndings(), CModel::getNumMetabs(), CModel::getNumModelValues(), CLGlobalRenderInformation::getNumStyles(), CLLocalRenderInformation::getNumStyles(), CDataVector< CType >::getObject(), SEDMLUtils::getObjectForSbmlId(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), ResultData::getOptTask(), CFunctionParameters::getParameterByUsage(), CCopasiSpringLayout::getPotential(), CListOfLayouts::getRenderInformation(), CLayout::getRenderInformation(), CLGlobalRenderInformation::getStyle(), CLLocalRenderInformation::getStyle(), CModel::getTotSteps(), CModel::hasReversibleReaction(), CChemEqInterface::init(), CCopasiSpringLayout::initFromLayout(), CMathReaction::initialize(), CCSPMethod::initializeOutput(), CLsodaMethod::initializeParameter(), CReactionInterface::isLocked(), SBMLImporter::isMassActionExpression(), CLNAMethod::isValidProblem(), CTSSAMethod::isValidProblem(), CFunctionParameters::isVector(), CODEExporterC::KineticFunction2ODEmember(), CMMLOutput::listReactionsForMetab(), CModel::load(), CDataVectorS< CType >::load(), CDataVectorNS< CType >::load(), CDataModel::loadModelParameterSets(), CModelMerging::mergeMetabolites(), CLayout::moveBy(), CLGeneralGlyph::moveBy(), CLReactionGlyph::moveBy(), CReaction::object2variable(), CDataVector< CType >::operator!=(), CLGeneralGlyph::operator=(), CLReactionGlyph::operator=(), CDataVector< CType >::operator[](), CODEExporter::preprocess(), CODEExporterC::preprocess(), CCSPMethod::printResult(), CILDMMethod::printResult(), CCopasiSpringLayout::randomize(), CModelAdd::reactionInvolvesCompartment(), CDataVector< CType >::remove(), CLRenderInformationBase::removeColorDefinition(), CLRenderInformationBase::removeGradientDefinition(), CLRenderInformationBase::removeLineEnding(), CDataModel::removeSBMLIdFromFunctions(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInReaction(), CDataVector< CType >::resize(), CCopasiXML::saveFunctionList(), CCopasiXML::saveGUI(), CCopasiXML::saveLayoutList(), CCopasiXML::saveListOfGlobalRenderInformation(), CCopasiXML::saveListOfLocalRenderInformation(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameterSets(), CCopasiXML::savePlotList(), CCopasiXML::saveReportList(), CCopasiXML::saveTaskList(), CCopasiXML::saveUnitDefinitionList(), CCSPMethod::setAnnotationM(), CDataArray::setCopasiVector(), SBMLImporter::setCorrectUsage(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), CReaction::setScalingFactor(), CModelMerging::simpleCall(), CFunctionParameters::size(), CModel::suitableForStochasticSimulation(), CFunctionDB::suitableFunctions(), CDataVector< CType >::swap(), CLGlobalRenderInformation::toSBML(), CLGroup::toSBML(), CLLocalRenderInformation::toSBML(), CLLayoutRenderer::update_associations(), CSBMLExporter::updateMIRIAMAnnotation(), CMMLOutput::writeDifferentialEquations(), and CMMLOutput::writeRHS().
swap()
template<class CType > virtual void CDataVector< CType >::swap (const size_t & indexFrom, const size_t & indexTo) inline virtual
Swap two objects in the vector.
Parameters
const size_t & indexFrom
const size_t & indexTo
References CCopasiMessage::EXCEPTION, MCDataVector, and CDataVector< CType >::size().
Referenced by CFunctionParameters::swap().
toData()
template<class CType > virtual CData CDataVector< CType >::toData () const inline virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
Reimplemented in CDataVectorN< CType >, CDataVectorN< CEventAssignment >, CDataVectorN< CCopasiTask >, CDataVectorN< CLayout >, CDataVectorN< CUnitDefinition >, CDataVectorN< CPlotSpecification >, CDataVectorN< CModelParameterSet >, CDataVectorN< CEvent >, CDataVectorN< CFunction >, CDataVectorN< CModelValue >, and CDataVectorN< CReportDefinition >.
References CData::addProperty(), CDataVector< CType >::begin(), CDataVector< CType >::end(), and CData::VECTOR_CONTENT.
updateIndex()
template<class CType > virtual void CDataVector< CType >::updateIndex (const size_t & index, const CUndoObjectInterface * pUndoObject) inline virtual
Update the index of a contained object This method needs to be re-implemented in container which care about the order of contained objects
Parameters
const size_t & index
const CUndoObjectInterface * pUndoObject
Reimplemented from CUndoObjectInterface.
References C_INVALID_INDEX, CDataVector< CType >::getIndex(), and min.
Referenced by CDataVector< CType >::insert().
Friends And Related Function Documentation
operator<<
template<class CType > std::ostream& operator<< (std::ostream & os, const CDataVector< CType > & d) friend
ostream operator
Parameters
std::ostream & os
const CDataVector<CType> & d
Returns
std::ostream & os
The documentation for this class was generated from the following file:
CDataVector.h