COPASI API: CLLocalStyle Class Reference
CLLocalStyle Class Reference
#include <CLLocalStyle.h>
Public Member Functions
void addKey (const std::string &key)
virtual int appliesTo (const CLGraphicalObject *pObject) const
virtual bool applyData (const CData &data, CUndoData::CChangeSet &changes)
CLLocalStyle (CDataContainer *pParent=NULL)
CLLocalStyle (const CLLocalStyle &source, CDataContainer *pParent=NULL)
CLLocalStyle (const LocalStyle &source, CDataContainer *pParent=NULL)
const std::set< std::string > & getKeyList () const
size_t getNumKeys () const
bool isInKeyList (const std::string &key) const
bool isKeyInSet (const std::string &key) const
void removeKey (const std::string &key)
void setKeyList (const std::set< std::string > &keyList)
virtual CData toData () const
LocalStyle * toSBML (unsigned int level, unsigned int version) const
Public Member Functions inherited from CLStyle
void addRole (const std::string &role)
void addSBMLAttributes (Style *pStyle) const
void addType (const std::string &type)
CLStyle (const CLStyle &source, CDataContainer *pParent=NULL)
CLStyle (const std::string &name, CDataContainer *pParent=NULL)
CLStyle (const Style &source, const std::string &name, CDataContainer *pParent=NULL)
CLGroup * getGroup ()
const CLGroup * getGroup () const
const std::string & getKey () const
size_t getNumRoles () const
size_t getNumTypes () const
const std::set< std::string > & getRoleList () const
std::string getRoleListString () const
const std::set< std::string > & getTypeList () const
std::string getTypeListString () const
bool isInRoleList (const std::string &role) const
bool isInTypeList (const std::string &type) const
void removeRole (const std::string &role)
void removeType (const std::string &type)
void setGroup (const CLGroup *pGroup)
void setRoleList (const std::set< std::string > &roleList)
void setTypeList (const std::set< std::string > &typeList)
~CLStyle ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CDataContainer
virtual bool add (CDataObject *pObject, const bool &adopt=true)
virtual bool appendDeletedDependentData (CUndoData &undoData) const
CDataContainer (const CDataContainer &src, const CDataContainer *pParent)
CDataContainer (const std::string &name, const CDataContainer *pParent=NO_PARENT, const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
virtual void createUndoData (CUndoData &undoData, const CUndoData::Type &type, const CData &oldData=CData(), const CCore::Framework &framework=CCore::Framework::ParticleNumbers) const override
virtual std::string getChildObjectUnits (const CDataObject *pObject) const
void getDescendants (CDataObject::DataObjectSet &descendants, const bool &recursive=false) const
virtual size_t getIndex (const CDataObject *pObject) const
virtual const CObjectInterface * getObject (const CCommonName &cn) const override
virtual objectMap & getObjects ()
virtual const objectMap & getObjects () const
virtual const std::string getUnits () const override
virtual const CDataObject * getValueObject () const override
virtual CUndoObjectInterface * insert (const CData &data) override
void objectRenamed (CDataObject *pObject, const std::string &oldName)
virtual bool remove (CDataObject *pObject)
virtual ~CDataContainer ()
Public Member Functions inherited from CDataObject
void addIssue (const CIssue &issue)
void addReference (const CDataContainer *pReference)
virtual void calculateValue () override
CDataObject (const CDataObject &src, const CDataContainer *pParent=NULL)
virtual void destruct () override
virtual CCommonName getCN () const override
virtual const CDataObject * getDataObject () const override
CDataContainer * getObjectAncestor (const std::string &type) const
CDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName () const override
const CObjectInterface * getObjectFromCN (const CCommonName &cn) const
const std::string & getObjectName () const
CDataContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const CObjectInterface::ObjectSet & getPrerequisites () const override
virtual const CValidity & getValidity () const override
virtual void * getValuePointer () const override
bool hasFlag (const Flag &flag) const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CCore::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const override
bool prerequisitsContains (const DataObjectSet &objects) const
virtual void print (std::ostream *ostream) const override
void removeIssue (const CIssue &issue)
void removeReference (const CDataContainer *pReference)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CDataContainer *pParent)
void validityChanged (const CValidity &changedValidity) override
void validityRemoved (const CValidity &changedValidity)
virtual ~CDataObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
CObjectInterface (const CObjectInterface &src)
virtual ~CObjectInterface ()
Public Member Functions inherited from CUndoObjectInterface
CUndoObjectInterface ()
CUndoObjectInterface (const CUndoObjectInterface &src)
bool generateUuid ()
const xg::Guid & getUuid () const
bool setUuid (const std::string &uuid)
bool setUuid (const xg::Guid &uuid)
virtual void updateIndex (const size_t &index, const CUndoObjectInterface *pUndoObject)
virtual ~CUndoObjectInterface ()
Static Public Member Functions
static CLLocalStyle * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CLStyle
static std::string createStringFromSet (const std::set< std::string > &set)
static void readIntoSet (const std::string &s, std::set< std::string > &set)
Static Public Member Functions inherited from CDataContainer
static CDataContainer * fromData (const CData &data, CUndoObjectInterface *pParent)
Static Public Member Functions inherited from CDataObject
static CDataObject * fromData (const CData &data, CUndoObjectInterface *pParent)
static void sanitizeObjectName (std::string &name)
Static Public Member Functions inherited from CObjectInterface
static const CDataObject * DataObject (const CObjectInterface *pInterface)
static CObjectInterface * GetObjectFromCN (const ContainerList &listOfContainer, const CCommonName &objName)
Static Public Member Functions inherited from CUndoObjectInterface
template<class CType >
static CType * fromData (const CData &, CUndoObjectInterface *)
Protected Attributes
std::set< std::string > mKeyList
Protected Attributes inherited from CLStyle
std::string mKey
CLGroup * mpGroup
std::set< std::string > mRoleList
std::set< std::string > mTypeList
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CDataContainer
objectMap mObjects
Protected Attributes inherited from CDataObject
ObjectSet mPrerequisits
std::set< CDataContainer * > mReferences
Protected Attributes inherited from CObjectInterface
CValidity mValidity
Additional Inherited Members
Public Types inherited from CDataContainer
typedef CDataObjectMap objectMap
Public Types inherited from CDataObject
typedef std::set< const CDataObject * > DataObjectSet
enum Flag {
Container , Vector , Matrix , NameVector ,
Reference , ValueBool , ValueInt , ValueInt64 ,
ValueDbl , NonUniqueName , StaticString , ValueString ,
Separator , DisplayName , ModelEntity , Array ,
DataModel , Root , Gui , __SIZE
}
Public Types inherited from CObjectInterface
typedef std::vector< const CDataContainer * > ContainerList
typedef std::set< const CObjectInterface * > ObjectSet
Static Public Attributes inherited from CDataContainer
static const CObjectInterface::ContainerList EmptyList
Protected Member Functions inherited from CDataContainer
template<class CType >
CDataMatrixReference< CType > * addMatrixReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataObjectReference< CType > * addObjectReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
template<class CType >
CDataVectorReference< CType > * addVectorReference (const std::string &name, CType &reference, const CFlags< Flag > &flag=CFlags< Flag >::None)
CDataContainer (const CDataContainer &src)
void initObjects ()
Protected Member Functions inherited from CDataObject
CDataObject ()
CDataObject (const std::string &name, const CDataContainer *pParent=static_cast< CDataContainer * >((void *) 0), const std::string &type="CN", const CFlags< Flag > &flag=CFlags< Flag >::None)
Constructor & Destructor Documentation
CLLocalStyle() [1/3]
CLLocalStyle::CLLocalStyle (CDataContainer * pParent = NULL)
Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and CLStyle::mKey.
Referenced by fromData().
CLLocalStyle() [2/3]
CLLocalStyle::CLLocalStyle (const CLLocalStyle & source, CDataContainer * pParent = NULL)
Copy Constructor.
References CKeyFactory::add(), CRootContainer::getKeyFactory(), and CLStyle::mKey.
CLLocalStyle() [3/3]
CLLocalStyle::CLLocalStyle (const LocalStyle & source, CDataContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
References CKeyFactory::add(), CLStyle::createStringFromSet(), CRootContainer::getKeyFactory(), CLStyle::mKey, and CLStyle::readIntoSet().
Member Function Documentation
addKey()
void CLLocalStyle::addKey (const std::string & key)
Adds another key to the set.
References mKeyList.
appliesTo()
int CLLocalStyle::appliesTo (const CLGraphicalObject * pObject) const virtual
Checks whether the style applies to the graphical object
Parameters
pObject the object to check
Returns
0, if the style does not apply, 1 if it applies by type, 2 if it applies by role, 3 if it applies by key
Reimplemented from CLStyle.
References CLStyle::appliesTo(), CLGraphicalObject::getKey(), and isKeyInSet().
applyData()
bool CLLocalStyle::applyData (const CData & data, CUndoData::CChangeSet & changes) virtual
Apply the provided data to the object
Parameters
const CData & data
Returns
bool success
Reimplemented from CDataContainer.
References fatalError.
fromData()
CLLocalStyle * CLLocalStyle::fromData (const CData & data, CUndoObjectInterface * pParent) static
Static method to create a CDataObject based on the provided data
Parameters
const CData & data
Returns
CLLocalStyle * pDataObject
References CLLocalStyle(), and NO_PARENT.
getKeyList()
const std::set< std::string > & CLLocalStyle::getKeyList () const
Returns the key list.
References mKeyList.
Referenced by SBMLDocumentLoader::convertLayoutObjectIds(), CLRenderResolver::fill_local_maps(), CLRenderFlattener::flatten(), and CCopasiXML::saveLocalStyle().
getNumKeys()
size_t CLLocalStyle::getNumKeys () const
Returns the number of keys in the key set.
References mKeyList.
Referenced by CCopasiXML::saveLocalStyle().
isInKeyList()
bool CLLocalStyle::isInKeyList (const std::string & key) const
Checks whether a given key is in the role list.
References isKeyInSet().
isKeyInSet()
bool CLLocalStyle::isKeyInSet (const std::string & key) const
Checks if a certain key is in the set or not.
References mKeyList.
Referenced by appliesTo(), and isInKeyList().
removeKey()
void CLLocalStyle::removeKey (const std::string & key)
Removes an key from the set.
References mKeyList.
setKeyList()
void CLLocalStyle::setKeyList (const std::set< std::string > & keyList)
Sets the key list.
References mKeyList.
Referenced by SBMLDocumentLoader::convertLayoutObjectIds().
toData()
CData CLLocalStyle::toData () const virtual
Retrieve the data describing the object
Returns
CData data
Reimplemented from CDataContainer.
References fatalError.
toSBML()
LocalStyle * CLLocalStyle::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
References CLStyle::addSBMLAttributes(), CLStyle::createStringFromSet(), mKeyList, and CLStyle::readIntoSet().
Referenced by CLLocalRenderInformation::toSBML().
Member Data Documentation
mKeyList
std::set<std::string> CLLocalStyle::mKeyList protected
Referenced by addKey(), getKeyList(), getNumKeys(), isKeyInSet(), removeKey(), setKeyList(), and toSBML().
The documentation for this class was generated from the following files:
CLLocalStyle.h
CLLocalStyle.cpp