COPASI API: SBMLUnitSupport.cpp File Reference
SBMLUnitSupport.cpp File Reference
#include <sbml/Model.h>
#include <sbml/Compartment.h>
#include <sbml/Species.h>
#include <sbml/SpeciesReference.h>
#include <sbml/Reaction.h>
#include "copasi/sbml/SBMLUnitSupport.h"
#include "copasi/model/CModel.h"
#include "copasi/core/CRootContainer.h"
#include "copasi/CopasiDataModel/CDataModel.h"
#include "copasi/sbml/SBMLIncompatibility.h"
Macros
#define SBML_AVOGADRO 6.02214179e23
Functions
bool areApproximatelyEqual (double x, double y)
Macro Definition Documentation
SBML_AVOGADRO
#define SBML_AVOGADRO 6.02214179e23
Function Documentation
areApproximatelyEqual()
bool areApproximatelyEqual (double x, double y)
References max.
Referenced by SBMLUnitSupport::areSBMLUnitDefinitionsIdentical(), SBMLUnitSupport::checkElementUnits(), and SBMLUnitSupport::createUnitExpressionFor().