COPASI API: CODEExporter.cpp File Reference
CODEExporter.cpp File Reference
#include <locale>
#include <cmath>
#include <iostream>
#include <fstream>
#include <sstream>
#include <ctype.h>
#include "copasi/copasi.h"
#include "copasi/CopasiDataModel/CDataModel.h"
#include "copasi/core/CRootContainer.h"
#include "CODEExporter.h"
#include "copasi/model/CModel.h"
#include "copasi/model/CMetab.h"
#include "copasi/model/CMetabNameInterface.h"
#include "copasi/core/CDataVector.h"
#include "copasi/model/CReaction.h"
#include "copasi/model/CMoiety.h"
#include "copasi/model/CChemEqElement.h"
#include "copasi/math/CMathContainer.h"
#include "copasi/function/CFunction.h"
#include "copasi/function/CExpression.h"
#include "copasi/function/CFunctionDB.h"
#include "copasi/report/CKeyFactory.h"
#include "copasi/function/CEvaluationTree.h"
#include "copasi/function/CEvaluationNode.h"
#include "copasi/function/CEvaluationNodeObject.h"
#include "copasi/function/CEvaluationNodeOperator.h"
#include "copasi/function/CEvaluationNodeFunction.h"
#include "copasi/utilities/CCopasiTree.h"
#include "copasi/utilities/CCopasiMessage.h"
#include "copasi/commandline/CLocaleString.h"
#include "copasi/trajectory/CTrajectoryTask.h"
#include "copasi/trajectory/CTrajectoryProblem.h"
Functions
std::string getQuantityParameterOrValue (const std::map< std::string, std::string > &map, const CDataModel *pDataModel)
size_t getReactionIndex (const CDataVector< CReaction > &reacs, const CReaction *react)
Function Documentation
getQuantityParameterOrValue()
std::string getQuantityParameterOrValue (const std::map< std::string, std::string > & map, const CDataModel * pDataModel)
References CDataVector< CType >::begin(), CDataVector< CType >::end(), CDataObject::getKey(), CDataModel::getModel(), CModel::getModelValues(), and CModel::getQuantity2NumberFactor().
Referenced by CODEExporter::exportExpression().
getReactionIndex()
size_t getReactionIndex (const CDataVector< CReaction > & reacs, const CReaction * react)
References CDataVector< CType >::getIndex().
Referenced by CODEExporter::exportExpression(), and CEFMTask::getFluxModeDescription().